_docs/environment.md

Fixes a missing closing parenthesis on your documentation page describing what environments are available for testing.
Obviously not anything major, just pointing out a grammatical error I happened to stumble across.

Add missing close-parenthesis to "environment" documentation page

---

_docs/code-coverage.md

Hi guys,
According to https://github.com/colszowka/simplecov#ruby-version-compatibility
simplecov is compatible with Ruby 1.9+ and the test suite is green until Ruby 2.2. 
Cheers! :smiley_cat:

Update compatible Ruby versions for Simplecov gem

---

circle.yml

The `jekyll build` command seems to return exit code 1 for some errors but not others. These causes scenarios where some docs aren't being build due to YAML issues, Jekyll says there is an error, yet the build passes successfully anyway.
Opened an issue, turns out there's already an issue.  Until this is fixed, we grep the output of Jekyll build, which is saved into a file.

Temporarily grep for Jekyll build errors until they fix their exit codes.

---

jekyll/_docs/continuous-deployment-with-ninefold.md

Added a `deprecated` front matter item with an explanation. This isn't technically supported in docs yet but will be.
Also removed the Ninefold link as it's now 404'ing.

Deprecated the NineFold guide.

---

circle.yml
jctl
jekyll/_config_production.yml
jekyll/_layouts/classic-docs.html

- make `.jctl start` duplicate less work so it's faster
- added _config_production.yml so that we can change `site.url` to something real in production. Useful for sitemaps, rss feeds, anything that needs an absolute URL.
- set `JEKYLL_ENV` to production for CircleCI builds so that we can choose avoid Google Tag Manager in dev environments.

Build tweaks

---

circle.yml

They won't show up on the prod site until we tweak nginx, but we can go directly to the bucket url to see them until we're ready for that.

Sync docs to prod

---

jekyll/assets/js/search.js

Prevents the user typing something in the search bar, clicking enter, and having the page reload for no reason.

Prevent search form from posting to nothing.

---

jekyll/_docs/environment.md
jekyll/sitemap.xml

Set the `lastmod` time in sitemap.xml to today, as a manual value. This is better than not having anything at all, which is where we've been at for awhile. In the future, will update `lastmod` dynamically by reading from Git.
The default `changefreq` value in sitemap.xml is 'monthly. An individual doc can now override that by using the `changefreq` Front Matter variable. For example, the Environment doc has been set to 'weekly' since it changes more often than other docs.

Gave sitemap.xml some smarts.

---

jekyll/_docs/phabricator.md

CircleCI integration was made available in the release *2016 Week 13* of Phabricator—older versions don’t have the *Build on CircleCI* item available in Harbormaster. We need to highlight that to eliminate all possible confusion.

Mention the release of Phabricator where CircleCI integration is available

---

jekyll/_docs/ios-builds-on-os-x.md

said 1.64, should be 1.66 - thanks to user kitsunde!

Updated text of fastlane version to actual current version

---

jekyll/_docs/configuration.md

Redis is not being started by default in the new image releases, so it would be important to mention it in the list of services that can be started via `circle.yml`.

Add Redis to the list of services that can be started during the build

---

jekyll/_docs/language-php.md

PHPUnit needs to be manually configure to create the JUnit XML file. Add a link in the PHP documentation for convenience.

Add link to test metadata for PHPUnit in PHP docs

---

jekyll/_data/precise/versions.yml

Related to https://github.com/circleci/circleci-docs/pull/65

Removing build-tools-23.02 from pre-installed list

---

jekyll/_docs/phabricator.md

A user ran into some confusion about this: the "Run build plans" action is not available for personal rules, so make it clear that the user must choose the "Global" rule type. Also changed the letter case of a couple of labels to match what appears in the UI.

Clarify that the Phabricator Herald rule must be "Global"

---

jekyll/_docs/docker.md

`ip addr show docker0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1` will figure out the IP address from the `docker0` interface.

Add example for add-host to connect to db

---

jekyll/_docs/ios-builds-on-os-x.md

We have recently changed the default iOS build command from `xctool` to `xcodebuild` (more details [here](https://discuss.circleci.com/t/xcodebuild-becomes-default-ios-build-command/3266)), so adding this change to the docs.

Reflect the change in the iOS inference build command in the docs

---

jekyll/_docs/google-cloud-platform.md

Currently, you can't use `gcloud` on CircleCI without running as root and using the full path. Until this changes in the build images, the doc has been updated to reflect correct usage.

Updated gcloud command example to reflect real usage.

---

jekyll/assets/css/main.scss

The H2-H4 headers were extremely similar in font size. In fact, H3s and H4s were the exact same size. While writing a guide, I noticed that this issue made it harder to read.
I've adjusted the sizes a bit.
Thoughts?

Adjust sizes of header tags.

---

jekyll/_docs/docker.md

Too many backticks were used for the docker exec workaround example, causing the curly braces and their contents to not be displayed.

Fix docker exec workaround example

---

jekyll/assets/css/main.scss
jekyll/assets/js/main.js

This PR adds an anchor link to article headings (h2-h6 tags) when they are hovered over.
Fixes #73 
Issue #72 will be addressed in a separate commit.

Added anchor links to article headings.

---

jekyll/assets/css/main.scss

Fixed issue where using anchor links causes the heading to be covered up by the nav. Didn't look right when a user clicks the link, should be visible.
Fixes #72

Fixed anchor links covered up by nav.

---

jekyll/_docs/android.md

I followed the docs and was not able to install build tools 23.0.3. I fixed it following the advice from the forums here:
https://discuss.circleci.com/t/installing-android-build-tools-23-0-2/924

Fix error when using Android build tools >= 23.0.2

---

jekyll/_docs/parallel-manual-setup.md

Thank you very much for providing great service and its documentations. 
In this PR, I modified the world `simply` to `simple`, as I personally thought writhing this way is more suitable; if it is not, please ignore this PR. 🙇

Fix typo from 'simply' to 'simple'

---

jekyll/_includes/edit-on-github.html

Clean up the instructions for contributing to the docs to make them a bit more scannable and add a link to the CONTRIBUTING.md page directly

Clean up the instructions for contributing to the docs 

---

jekyll/_docs/test-metadata.md

The [Test Metadata](https://circleci.com/docs/test-metadata/) page wasn't linked from the sidebar menu. This adds it to the 'how-to' section.

Add category to test-metadata so it shows in menu

---

jekyll/_docs/test-metadata.md

We found that the JSON formatter meant that the "Test Summary" didn't include
any details about the failures (other than the filename), meaning you had to
dig through each of the container tabs to find the detail, whereas the JUnit
formatter means the details are included in the summary.

Use JUnit formatter for cucumber output

---

jekyll/_docs/ios-builds-on-os-x.md

Update the docs with the versions of software installed in the new OS X build image, related to [this blog post](https://circleci.com/blog/xcode-7-3-1-and-why-we-changed-from-xctool-to-xcodebuild/).

Add Xcode 7.3.1 to OS X docs

---

jekyll/_docs/fork-pr-builds.md

The above list of kinds of configuration data is now 5 not 4 items long.

Fix typo in "Fork PR builds"

---

circle.yml

I want to access Trusty `versions.json` directly via url `/docs/trusty_versions.json` for reusability. We copy the file during CI build  on the fly instead of having the separate file in order to avoid the duplication.

Exposing trusty versions.json as a public page

---

jekyll/_docs/language-php.md

Update the paths referenced in the PHP doc. CircleCI images (starting with Ubuntu 14.04) now place languages and many other preinstalls in `/opt/circleci/<THING>`.
Fixed the formatting for headings.
-----
Fixes #98 
Fixes #133

Update PHP file paths. Small fixes.

---

jekyll/_docs/adding-read-write-deployment-key.md

when creating an SSH key to be used to tag the github repo

Add indication to not add a passphrase

---

jekyll/_data/trusty/versions.json

We were using a wrong command to get PSQL version which gets psql client version, but what we really need is server/daemon version. The command will be fixed at https://github.com/circleci/image-builder/pull/82

Updating wrong PSQL version

---

jekyll/_docs/android.md

I forgot to add this in a previous PR, and it stops the list being displayed as a list.

Add missing space before list

---

jekyll/_docs/ios-builds-on-os-x.md

removed * It is not possible yet to SSH into build containers

removed line about ios ssh

---

jekyll/_docs/docker.md

Notice `Id` part doesn't show up in our doc.

Escape curly braces

---

jekyll/_docs/api.md

The headings for "Artifacts of a Build" and "Artifacts of the latest
Build" had the same `id` attribute, which made a fragment link to the
latter impossible.

Fix duplicate id 'build-artifacts'

---

jekyll/_docs/parallel-manual-setup.md

I always for get which flavors of globbing do/don't support multiple directory expansion. Make it clear that ours does.

More ruby glob explanation

---

jekyll/_docs/composer-api-rate-limit.md

Correct typo in Composer API rate limit doc.

---

jekyll/_docs/test-metadata.md

Version 0.2.3 has been released, and there doesn't seem to be any reason to lock the gem to a specific version. (The gem originally needed to be run from the CircleCI fork, but that's no longer the case.)

Unlock rspec_junit_formatter gem version

---

jekyll/_docs/ios-code-signing.md

Distribution was described in the table of contents, but wasn't actually written about - I added a new section 👍

Updated iOS Code Signing guide to describe distribution

---

jekyll/_docs/ios-builds-on-os-x.md

Had the issue with new iOS customer NBCUniversal. The `ipa` gem tries to upload the file (no idea what file) anyways and then just fails and directly prints the Hockeyapp server output into stdout.

Added --file flag to iOS app distribution with Hockeyapp

---

jekyll/_docs/ios-builds-on-os-x.md
jekyll/_docs/troubleshooting-ios-and-OSX.md

Updated the iOS builds on OSX doc with a list of iOS simulator UUIDs and created a iOS troubleshooting doc outlining xcodebuild exit code 65 and how to mitigate it.

iOS docs update

---

jekyll/_docs/build-image-trusty.md

I just noticed that versions for integration tools were missing.

Add version for gcloud/awscli/heroku

---

jekyll/_docs/installing-elasticsearch.md

This ES healthcheck is prone to failure if ES takes longer than 10 seconds to boot and responds with a connection refused error. Switch to `wget` for the healthcheck to take advantage of the `--retry-connrefused` option, which will treat connection refused errors as transient and retry-able.

Update elasticsearch install instructions

---

jekyll/_docs/api.md

Was a sad :panda_face: that I couldn't authenticate using `Authorization` header, such as:
```
curl -H "Authorization: Basic <my-token>" https://circleci.com/api/...
```

Add note about authenticating w/ http basic

---

jekyll/_docs/language-php.md

Xdebug is enabled by default on the 14.04 build image. This updates the docs to reflect that and shows how to disable Xdebug if desired.

Update information about PHP Xdebug

---

jekyll/_docs/enterprise.html
jekyll/_docs/enterprise/resources.html
jekyll/_docs/enterprise/resources.md
jekyll/_includes/sidebar.html
jekyll/_layouts/classic-category.html

Fixed resources to rehid docs that aren’t ready for primetime.
Enforced enterprise ordering in all relevant enterprise parts

Fixes to tighten up docs

---

jekyll/_docs/test-metadata.md

This was a common mistake that I made the first few times trying out circle :(
Also made the sub-sections under "automatic test metadata collection" stand out more

Ensure that reports are written to a sub-directory under $CIRCLE_TEST_REPORTS

---

jekyll/_docs/enterprise.html
jekyll/_docs/enterprise/resources.html
jekyll/_layouts/classic-category.html
jekyll/index.html

The combination of the additional parenthesis added during the CCIE Docs merge in addition to updated Jekyll causes Liquid to spit out errors. This removes those unnecessary parenthesis.

Fix issue with parenthesis appearing in Liquid if blocks.

---

jekyll/_docs/language-go.md

Go commands fail when GOPATH is prefixed with "~"
```
go: GOPATH entry cannot start with shell metacharacter '~': "~/.go_workspace"
go get -t -d -v ./... returned exit code 2
Action failed: go get -t -d -v ./...
```

Fix to `GOPATH` in machine environments

---

jekyll/_docs/docker-btrfs-error.md
jekyll/_docs/docker.md

This suggestion was added to the first example YAML but was missing from the rest.

Clear up the suggestion to use `--rm=false` with `docker build`.

---

jekyll/_docs/test-metadata.md

This makes it clear how to configure Minitest to run in parallel.

Added a Minitest section to the test-metadata custom build guide.

---

jekyll/_docs/introduction-to-continuous-deployment.md

Here is a better regex to match all branches except the master branch. The current regex in there will match any branch that even contains the word "master", which would not technically be everything but master ;)

Better regex for every branch except master

---

jekyll/_docs/github-security-ssh-keys.md

Some markdown readers seem fine with the spaces around `**`, but GH is not one of them! So be it.
Made CircleCI links into...links!

small markdown fixes, linky links, phrasing clarification

---

jekyll/_docs/enterprise/aws-manual.md

Adding updated AMIs that patch CVE-2016-5195 (http://dirtycow.ninja/)

Update the manual AWS installation

---

jekyll/_docs/enterprise/aws-manual.md

These are new AMIs for the services box that patch CVE-2016-5195
(https://dirtycow.ninja/)

Update AWS manual doc with dirty cow AMIs

---

jekyll/_docs/capybara-timeout.md

I had the same issue as this user (https://discuss.circleci.com/t/parallelism-and-bash-case-anybody-understand-this-error-message/1023) when running this (different example, but same problem).  This ran correctly for me when the line pwd: ../firefox-20 was indented two additional spaces.

the line pwd: ../firefox-20 needs to be indented

---

jekyll/_config.yml
jekyll/_config_production.yml
jekyll/_includes/head.html
jekyll/_includes/segment.html

We added all the meta data to the tracking properties, and make the doc's root subcategory "default".
For all other pages the category is `docs` and the subcategory is the url that follows with the leading and trailing slashes removed (ie: `i-am-some-article` or `enterprise/some-enterprise-article`)

Added segment page tracking

---

jekyll/_docs/parallel-manual-setup.md

I've updated page https://circleci.com/docs/parallel-manual-setup/ with info about test suite parallelisation with knapsack gem for test runners like rspec, minitest, cucumber, spinach and turnip.

Add info about test suite split with knapsack gem

---

jekyll/_docs/npm-private-module-dependency.md

I updated the docs to include the `circle.yml` configuration to authenticate using npm auth tokens.

Update docs about using npm tokens with CircleCI.

---

jekyll/_docs/build-image-trusty.md

This doc referenced Ubuntu 12.04 as the default Linux image, which is no longer the case.

Fix reference to default Linux image (now 14.04).

---

jekyll/_docs/build-image-trusty.md

Changed to java 7 as default, but everything else uses site.data.trusty.versions.summary, which is also wrong so checking to see where that comes from.

WIP: Correct default java version and add missings

---

jctl

This is nothing life changing but, on my local machine, this improves `./jctl rebuild` time from approximately 38 seconds to approximately 13 seconds for subsequent builds.

Tell JCTL to use incremental Jekyll builds.

---

jekyll/_docs/installing-elasticsearch.md

Updating for consistency, see https://github.com/circleci/circleci-docs/pull/300:
"This ES healthcheck is prone to failure if ES takes longer than 10 seconds to boot and responds with a connection refused error. Switch to `wget` for the healthcheck to take advantage of the `--retry-connrefused` option, which will treat connection refused errors as transient and retry-able."

Use wget to wait throughout.

---

jekyll/_docs/api.md

Without the colon `:`, just doing `curl -u <circle-token>`, will prompt for the password.

Fix API HTTP basic auth curl example

---

jekyll/_docs/api.md

Because apparently I have to do everything around here :P

Fix grammar in Authentication section of API docs

---

jekyll/_docs/enterprise/aws-private-subnet.md

I used https://github.com/circleci/enterprise-setup as-is and couldn't make builders to work in the initial try because the subnet for builders didn't have the access to the internet.

Add a note for builder boxes' private subnet

---

jekyll/_docs/firebase-test-lab.md
jekyll/_docs/google-cloud-test-lab.md

Changed name from Google Cloud Test to  Firebase Test Lab

Changed name

---

jekyll/_docs/enterprise/faq.md

Making enterprise FAQ more visible in "Resources" section

---

jekyll/_docs/code-coverage.md

The Code Climate UI has changed a bit since this was initialy written. Notably, "Repo Settings" is now just "Settings".
Making this into a list and linking directly to their documentation should make things a bit more clear.

reword code climate section

---

jekyll/_docs/docker.md

When using the [`docker exec` workaround](https://circleci.com/docs/docker/#docker-exec) it's useful to know that commands are run inside the container's root directory instead of the docker working directory as it would if we ran `docker exec`

Added notes on working directory

---

jekyll/_docs/test-metadata.md

parallel and files requires 4 spaces indentation so that it can be recognized as a map.
also appending the reports folder with "reports" so that it will automatically get uploaded by the script instead of having the xml files be at the root level of the CIRCLE_TEST_REPORTS

incorrect override command for minitest metadata

---

jekyll/_docs/install-and-use-yarn.md

When the dependency step is overridden to use "yarn install", CircleCI doesn't add `node_modules/.bin` to the path.
Also, the yarn cache directory on CircleCI ends up being `~/.cache/yarn`, not `~/.yarn-cache`

Fix paths in yarn docs

---

jekyll/_docs/install-and-use-yarn.md

Yarn 0.18.0 was essentially a release candidate whereas 0.18.1 is a stable release (yes, the Yarn RC process needs some improvements, see https://github.com/yarnpkg/yarn/issues/2161). Because of this, the CircleCI docs should suggest installing 0.18.1.

Bump Yarn version to 0.18.1

---

jekyll/_docs/missing-dir.md

Typo correction from `direction` to `directory`

Fixed typo in the missing-dir doc

---

jekyll/_docs/enterprise.html
jekyll/_layouts/classic-docs.html
jekyll/_layouts/enterprise-cat.html

@ndintenfass This fixes the issue where the GitHub CTA (and license info while we're at it) doesn't appear in the footer of CCIE Docs.

Make FOSS CTA appear on CCIE Docs too.

---

jekyll/_docs/ios-builds-on-os-x.md

We no longer recommend specifying a device UUID in the `circle.yml`, so are replacing the list of simulator UUIDs with a list of simulator names and adding a few notices around using simulator names in all config files.

Remove mentions of device UUIDs, add list of simulator names

---

jekyll/_docs/troubleshooting-ios-and-OSX.md

We no longer recommend using UUIDs in `circle.yml`. We previously removed all UUID mentions from the [main](https://github.com/circleci/circleci-docs/pull/516) doc, now also removing it from the iOS / OS X troubleshooting doc.

Remove the mention of UUIDs from OS X troubleshooting doc

---

jekyll/assets/css/main.scss

This makes non-H1 headers a bit smaller, and makes inline code style not look so crazy when touching other code style on adjacent lines.

Style tweaks

---

jekyll/_docs/ios-builds-on-os-x.md
jekyll/_docs/ios-code-signing.md
jekyll/_docs/ios-getting-started.md

In macOS builds you can now upload provisioning profiles rather than
having to have them present in the repository.
- Update the docs to reflect this.
- Update the docs to use the new fastlane syntax
- Fix some line-wrapping errors in literal code blocks.

CIRCLE-2712 Provisioning Profiles upload in Project Settings

---

jekyll/_docs/ios-builds-on-os-x.md

Invoking `fastlane` directly is no longer recommended, we should suggest using `fastlane gym` everywhere instead.

Show how to call gym via fastlane in the iOS docs

---

jekyll/_includes/edit-on-github.html

@smart-alek and various readers occasionally point out how much vertical space the "Edit on GitHub" section of docs take up. This is most noticeable with docs that are very short where this section might actually be the same size as the doc itself.
This PR reduces the height of this section by approximately 60 pixels or so. The copy remains the same.

Reduce vertical space 'edit on GitHub' section takes up.

---

jekyll/_docs/nightly-builds.md
jekyll/_docs/parameterized-builds.md

I had some difficulty following the examples until I found a slight difference between the current API docs ([ref](https://github.com/circleci/circleci-docs/blob/master/jekyll/_docs/api.md)) and the example code. This PR is aimed at making the examples valid again.
Thanks for the consideration!

Add in :vcs-type to examples

---

jekyll/_docs/cant-follow.md

Specifically info about looking under the 'owner'  of the repo and noting that we don't support Mercurial.

Add info about following BitBucket repos

---

jekyll/_data/categories.yml
jekyll/_docs/enterprise.html
jekyll/_includes/sidebar-cci1.html
jekyll/_layouts/category-page.html
jekyll/index.html

The main point of this PR is to clean up the way categories will be handled within CircleCI Docs. Docs will soon have multiple sections, provided by Jekyll's Collections. So categories will need to work equally well between 1.0 docs, 2.0 docs, CCIE docs, but be attached to a single section. This first PR allows that to happen.
This is pulled from the actual commit:
```
- section: cci2                # mandatory - corresponds to the Jekyll collection this category is for
slug: getting-started        # mandatory - lower-case, no spaces, unique within section, filename of the category's page: `_collection/<slug>.md`
name: "Getting Started"      # mandatory - human version of category slug, how the category name is displayed on the website
index: gettingstarted        # optional - alternate …
```

Prepare categories.yml for upcoming changes.

---

jekyll/_docs/nodejs-and-npm.md
jekyll/_docs/npm-continuous-deployment.md

At @taskworld, we deploy packages to npm from CircleCI. I wanted to write a guide about it, but I think it may be more beneficial to just put it in CircleCI docs 😄 
p.s. [`npm` should be spelled using lowercase](https://github.com/google/shipshape/blob/master/third_party/node/lib/node_modules/npm/doc/misc/npm-faq.md#is-it-npm-or-npm-or-npm)
p.s.2. or is it called continuous __delivery__?

Add an npm continuous deployment guide

---

jekyll/_cci1/ios-getting-started.md

We no longer require the presence of these for a build to run, but we require them to infer test commands for the project, so the docs should reflect that too.

Update docs for Xcode validation changes

---

jekyll/_data/api.yml

We were missing a `}` - Thanks to https://twitter.com/gsdev90/status/832217568337342464 for seeing it

Fix invalid json in project_post

---

jekyll/_includes/head.html

Was considering `robots.txt` for this however after reading [this article](https://support.google.com/webmasters/answer/6062608?hl=en) by Google, determined that using the `noindex` meta tag is what we need. This method actually works better in statically generated sites for fine-grain control.
Simply, if the page is set to search=false, add the noindex meta tag to its head.
FYI: Related, `page.hide` is also used to hide from sidebar and the in-page search.

Tell search indexes not to index docs set to 'hide'.

---

jekyll/_layouts/category-page.html

Use short titles when available in cat page layout.

---

jekyll/_cci1/google-auth.md

-i, --ignore-garbage  when decoding, ignore non-alphabet characters

 --ignore-garbage - option for base64 --decode

---

jekyll/_layouts/index-page.html

We should consider showing way more than 3 per section -- the CCIE docs where you have to click to see "1 more" is unpleasant and not worth shortening. But, in the mean time this PR will at least prevent 404.

Fix broken more links on index - not sure why we even do this, though

---

jekyll/_cci2/about-circleci.md
jekyll/_cci2/index.md
jekyll/_cci2/language-guides.md

Adds a basic 2.0 about page and creates some links to existing content on the 2.0 docs index page.
This will be regularly updated with links to new docs as they are written during Beta.

Orientation for 2.0 landing page

---

jekyll/_cci2/migration-why-2.md

This page server as the first page in the migration section. The rationale is to give users benefits of moving from 1.0 to 2.0.

Add why migrating to 2.0 page

---

jekyll/_cci2/migrating-from-1-2.md

@technomancy suggested to group dependencies, database, and test sections into the same category because they are just bunch of run steps.
Also, cache_save -> save_cache

Grouping dependencies, database, and test together

---

jekyll/_cci2/job-steps.md
jekyll/_cci2/project-walkthrough.md

The `run` step does not accept a map, so there was incorrect indentation scattered across a couple of docs. Thanks to @drazisil for catching this!

Fix run indentation

---

jekyll/_cci2/configuration-reference.md
jekyll/_cci2/migrating-from-1-2.md

Following Discussion with Anton, we will have a full 'Configuration Reference' doc that has the full config spec. So this renames 'Job Steps' to 'Configuration Reference' ready for that doc to be filled out.

Create Configuration Reference doc

---

jekyll/_cci2/api-docs.md
jekyll/_cci2/configuration-reference.md
jekyll/_cci2/deployments-and-uploads.md
jekyll/_cci2/example-projects-list.md
jekyll/_cci2/integrations.md
jekyll/_cci2/job-info-and-insights.md
jekyll/_cci2/notifications.md
jekyll/_cci2/project-walkthrough.md
jekyll/_data/categories.yml

@keybits 
TODOs are awesome for knowing what we need to do, but they don't really belong in polished docs. I've moved these TODOS to JIRA and also hidden categories that either only had a TODO or were empty.

Remove todos

---

jekyll/_cci2/language-erlang.md
jekyll/_cci2/language-go.md
jekyll/_cci2/language-javascript.md
jekyll/_cci2/language-php.md
jekyll/_cci2/language-python.md
jekyll/_cci2/language-ruby.md

This was pulled from [this Discuss post](https://discuss.circleci.com/t/getting-started-with-picard-elixir/5804/3) and updated to the latest syntax.
@eric-hu @keybits Mind reviewing this for me?
One open question for this one is where (or if) we're hosting the sample project anywhere. I think Eric had this up and running [here](https://github.com/circleci/canary_phoenix).
So this might need one more commit to get the links in order.

Add Elixir guide

---

jekyll/_cci2/language-go.md
jekyll/_cci2/language-javascript.md
jekyll/_cci2/language-php.md
jekyll/_cci2/language-python.md
jekyll/_cci2/local-builds.md
jekyll/_cci2/migrating-from-1-2.md

We still had a few lingering references to `circle.yml`, but that's not a thing anymore!
Replaced all instances of `circle.yml` to `config.yml`.

replace instances of circle.yml

---

jekyll/_cci2/configuration-reference.md

```plain
Build-agent version 0.0.2680-e73f80d (2017-03-07T12:49:08+0000)
Configuration errors: 1 error occurred:
* In step 2 definition: Step should have one key but it has 2: map[key:projectname-<< .Branch >>-<< checksum "project.clj" >> restore_cache:<nil>]
```

Fix indent

---

jekyll/_cci2/migrating-from-1-2.md

The DB section is broken and inaccurate: `createdb` is missing in the ruby image. Also, you don't need to create a test DB by yourself in Rails.

Clarify DB section in the equiv

---

jekyll/_cci2/env-vars.md

Adding `CIRCLE_PROJECT_USERNAME` and `CIRCLE_PROJECT_REPONAME`. They will be available once https://github.com/circleci/workflows-conductor/pull/42 is deployed.

Add more env vars

---

jekyll/_cci2/local-builds.md
jekyll/_cci2/local-jobs.md
jekyll/_cci2/parallelism-faster-jobs.md

The CLI tool has been renamed to `circleci` from `picard`.
Update the guide to install the tool locally as `circleci-cli` instead of `circleci-builder`.
Refer to 'jobs' instead of 'builds' where relevant.

Rename picard circleci

---

jekyll/_cci2/demo-apps.md
jekyll/_cci2/language-erlang.md
jekyll/_cci2/language-go.md
jekyll/_cci2/language-javascript.md
jekyll/_cci2/language-php.md
jekyll/_cci2/language-python.md
jekyll/_cci2/language-ruby.md
jekyll/_data/categories.yml

This is a subtask of [CIRCLE-3339](https://circleci.atlassian.net/browse/CIRCLE-3339):
- rename category from "Demo Applications" back to "Languages and Tools"
- move "Demo App Index" into the sidebar under this category

Rename Demo App category and move demo app index inside it

---

jekyll/_cci2/executor-types.md

Currently `machine` only takes a map. Giving a single value will lead to config error.
Bad
https://circleci.com/gh/kimh/picard-test/1033
Good
https://circleci.com/gh/kimh/picard-test/1034

passing a map to machine

---

jekyll/_cci2/about-circleci.md
jekyll/_cci2/building-docker-images.md
jekyll/_cci2/demo-apps.md
jekyll/_cci2/executor-types.md
jekyll/_cci2/first-steps.md
jekyll/_cci2/index.md
jekyll/_cci2/local-jobs.md
jekyll/_cci2/migrating-from-1-2.md

Missed the whole "complete URL" bit when adding links in the docs. This PR should fix all current links in docs.

add trailing forward slash for several docs

---

jekyll/_docs/perform-maven-release.md

Without this procedure I found myself needing to run the Maven release target locally on my development machine; however, that felt very dirty given the pristine, deterministic environment of a CircleCI build.

Adding howto for performing Maven releases

---

jekyll/_cci2/configuration-reference.md

The current wording is a bit unclear and could be read as implying that you need to set up an agent for any `ssh` key use.

Clarify that ssh-agent isn't needed for normal SSH use.

---

jekyll/_cci1/how-cache-works.md

Suggesting overriding the inferred dependencies step without the context of what overriding does could (did :( ) cause someone to not notice they were reliant on inferred dependency steps later in their build.

Switch example to use pre

---

jekyll/_cci2/configuration-reference.md

There was only one left in the Configuration Reference docs.

Remove references to artifacts-store

---

jekyll/_cci2/language-php.md

Instead of confirming the composer installer using a hardcoded hash, which will fail the next time composer updates, you can instead copy down a signature file and compare that way.

CircleCI 2.0 PHP Improvement

---

jekyll/_cci1/api.md

This fixes the broken redirect from #795. Merge right away once tests pass since this is broken.

Fix 1.0 API doc redirect.

---

jekyll/_cci2/building-docker-images.md

Add missing period at end of Overview section.

Update building-docker-images.md punctuation mark

---

jekyll/_cci2/index.md

It's weird to be talking about "we're" doing as CircleCI devs and then shift
to a question where "I'm" new to CircleCI. This change makes the voice
consistent across the doc.

make audience/voice consistent across 2.0 index page

---

jekyll/_cci2/local-jobs.md

Minor spelling fix (it's -> its)

---

jekyll/_cci2/artifacts.md
jekyll/_cci2/configuration-reference.md
jekyll/_cci2/deployments.md

We should highlight the fact that CircleCI only runs `build` job automatically.

Adding a note about default job

---

jekyll/_cci1/browser-testing-with-sauce-labs.md

The current URL to https://docs.saucelabs.com/reference/sauce-connect/ redirects to https://wiki.saucelabs.com/display/DOCS/Setting+Up+Sauce+Connect results in an error page that the content has been deleted. Sauce Lab's documentation for Sauce Connect points to https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy

URL to Sauce Connect Documentation has changed

---

jekyll/_cci2/language-python.md

At the bottom of [this page](https://circleci.com/docs/2.0/language-python/), the snippets isn't formatted.

Fix open YAML code snippets on python language page

---

jekyll/_cci2/artifacts.md

Only adding a reference to artifact build because accessing them via file path is broken in 2.0.

Add a reference to artifact API

---

jekyll/_ccie/ios-install.md

Starting on the next CCIE release, it will no longer be necessary to run ESXI migrations when setting up iOS infrastructure. The migrations will be run via `circleci run-migrations` instead.

[CIRCLE-3496] Stop requiring ESXI migrations in CCIE iOS setup guide

---

jekyll/_cci1/ios-builds-on-os-x.md

The customers who want to pre-start the simulator can run into the case where there are two simulators with the same name, a phone-only one and a phone-plus-watch one.
Adding an example and explaining how to uniquely identify a phone-only simulator (which is what the customers need most commonly).

[CIRCLE-3110] Add example of pre-starting simulator

---

jekyll/_cci1/index.md
jekyll/_config.yml
jekyll/_includes/head.html

This allows search engines like Google to index docs from the 2.0 section.
Also, the change in `jekyll/_cci1/index.md` is actually a bugfix I caught while I was in that file.

Allow search engines to start indexing 2.0 docs.

---

jekyll/_cci2/building-docker-images.md
jekyll/_cci2/docker-compose.md
jekyll/_cci2/docker-layer-caching.md
jekyll/_cci2/private-images.md

`setup_docker_engine` step renamed into `setup_remote_docker`
Do not merge until https://github.com/circleci/build-agent/pull/318 released

renamed `setup_docker_engine` step

---

LABELS.md

Labels in use weren't actually correct.

update labels to reflect reality

---

jekyll/_cci1/parallel-manual-setup.md

Add new information from @eric-hu about parallelization, which routinely trips up even very experienced developers. Very open to reorganization if folks have opinions on that; going for "done is better than perfect" here, but "better" is even better than "good."
I am bummed about mentioning a backlogged bug in the docs, but the alternative is a logical assumption ("commands that appear to run in all nodes do indeed run in all nodes") being secretly wrong, which I'm even less enthusiastic about.
There were mixed header tags and Markdown in this file, which leads to an unclear hierarchy on the rendered page (e.g. `Splitting your test suite` and `Using the files configuration modifier` were the same level, even though one is logically under the other).
Since this is a Markdown file, I would …

clearly call out parallelization gotchas, cleanin'

---

jekyll/_cci1/docker.md

This is an important landing page for people who search Google for 'CircleCI Docker' - this update adds links and information to recommend that new users start with CircleCI 2.0.

Update 1.0 Docker docs with links to 2.0

---

jekyll/_cci1/docker.md

Fix typo in CCI1 Docker page

---

jekyll/_includes/edit-on-github.html

closes #706
This simplifies some text, adds a link to Discuss on all docs pages and makes the link to a new issue fill out the 'body' rather than the title:
This means the person submitting the issue will have to create a title (thus preventing lots of unhelpfully titled issues with file name links) while automatically providing a link to the referring page.

Improve 'make this document better' links

---

jekyll/_cci2/faq.md

Currently, we don't support source caching with go-git. This is because go-git doesn't support `git reset` command which is needed in order to handle checkout with source caching. Although I'm working on finding a solution,  currently we error out when source caching is found.

Add limitation of go-git

---

jekyll/_cci2/faq.md
jekyll/_cci2/project-walkthrough.md

Update FAQ and walkthrough with this info. Prompted by a first link to a working Android project on 2.0 and because this information was missing from our FAQ. (Calling out that we don't support Windows as there are support requests about this.)

What kind of apps can I build on 2.0

---

jekyll/_cci2/project-walkthrough.md

Without it, my build would be stuck on:
```
The authenticity of host 'heroku.com (50.xx.x.xx.xx)' can't be established.
RSA key fingerprint is 8b:48:5e:67:0e:c9:16:47:32:f2:87:0c:1f:c8:60:ad.
Are you sure you want to continue connecting (yes/no)?
```

Add heroku.com to ssh known host

---

jekyll/_cci2/configuration-reference.md

Pretty big restructure of the [Configuration Reference](https://circleci.com/docs/2.0/configuration-reference/). TOC looks like:
Addresses [this ticket](https://circleci.atlassian.net/browse/CIRCLE-3607) and should fix #786.

Clean up config ref structure

---

jekyll/_cci2/configuration-reference.md

Also clarify that the primary container is the only place that steps can run currently.

The reference docs should link to the executor description page.

---

jekyll/_cci2/language-clojure.md

2.0 doesn't support env-var interpolation yet

---

jekyll/_api/index.html
jekyll/_cci1/index.md
jekyll/_cci2/index.md
jekyll/_ccie/index.html

The URLs for section index pages were showing up incorrectly in the sitemap. This PR fixes that.
cc: @michaelcstearns

Fix section index page URLs.

---

README.md

fix links to jekyll/vagrant guides

---

jekyll/_cci2/configure_aws_cli.md
jekyll/_cci2/deployment_integrations.md
jekyll/_data/categories.yml

Now 2.0 uses AWS credentials configured from the project setting page.
I'm not sure if having a dedicated page for this is good since the page is very sparse. If there are better places, please let me know.

Add AWS CLI page

---

jekyll/_cci1/language-php.md

The location provided of libphp5.so provided is incorrect. just copying this example fails. I have sshed into the vm and found the correct location that worked for me.

fixed the location of the libphp5.so

---

jekyll/assets/js/main.js

When trying to trigger tracking events on the docs site, a strange `cross-origin request blocked` error is issued. I can call the `trackEvent()` function with no problem, and it passes the info to segment (I checked in the segment debugger). So, I suspect the issue has something to do with the data binding that is calling the event. 
This commit changes the way jQuery is implemented, using the same method as is used in the rest of docs. I think the xorigin error may have been due to trying to reference the jquery library on outer, but we shall see. I'll need to push it to be sure.
@lewisl9029 @travis @JustinC474

testing fix for x-origin issue

---

jekyll/_cci1/browser-testing-with-sauce-labs.md

curl dies immediately if the connection is refused (e.g. as the app is starting). wget can retry on connection refused, which is much more robust during an app boot.

wget instead of curl

---

jekyll/_api/index.html
jekyll/_api/v1-reference.md
jekyll/index.html

The current landing page for the API section looks cramped:
This adds some context and improves layout:
The current docs 'home' page does not have a link to the API:
This removes the 'Contribute' section (since that is at the bottom of all pages) and replaces it with an API section:
The title of the API reference page has been changed from `1.x` to `1.1` since the doc is specific to 1.1. URLs have not been changed.

Improve visibility of API docs

---

jekyll/_includes/third-party-info.html

Adds an include that will display like this:
Call it with:
```
{% include third-party-info.html app='GitHub'%}
```

Add a third party info include banner

---

jekyll/_cci2/circleci-images.md

It would be nice to eventually split the 'available' images listing so it differentiates between 'primary' images and 'service' images. This note clarifies things for now.

Add a note about language v database images

---

jekyll/_cci1/parallel-manual-setup.md

We added a Jekyll include after the original PR, so this is a rebase of: https://github.com/circleci/circleci-docs/pull/949
Thanks for your input @michaelcontento

Add small section about circielci-matrix

---

jekyll/_cci2/parallelism-faster-jobs.md

We added a Jekyll include after the original PR, so this is a rebase of: https://github.com/circleci/circleci-docs/pull/950
Thanks for your input @ArturT

Add examples how to use balancing libraries for 2.0

---

jekyll/_layouts/classic-docs.html

This restricts search to the current section of the docs:
- 1.0
- 2.0
- Enterprise
- API
The docs homepage (https://circleci.com/docs/) searches all sections.
To make the scope of the current search clear, the placeholder text has been updated for each of the above sections, e.g:

Restrict search to current docs section

---

jekyll/_cci2/migrating-from-1-2.md

This is a common 2.0 support request. Adding here for clarity.

Add info on add_ssh_keys to migration guide

---

jekyll/_cci1/language-python.md

The example was failing because the versions in the example were no longer on the 14.04 image.

Update Python versions in example Fixes #921

---

jekyll/_cci1/configuration.md
jekyll/_cci1/faq.md
jekyll/_cci1/getting-started.md
jekyll/_cci1/introduction.md
jekyll/_cci1/manually.md
jekyll/_cci1/setting-up-parallelism.md

No order was set, so it was defaulting to alphabetical. This makes it more logical.

Reorder getting started 1.0 menu

---

jekyll/_cci1/language-python.md

Noticed that https://github.com/circleci/circleci-docs/pull/583 erroneously dropped an s from the end of `nosetests`.

nosetests are plural

---

jekyll/_cci1/index.md

This sorts the headings in the main content section of https://circleci.com/docs/1.0/

Sort main content sections on 1.0 index page

---

jekyll/_cci2/project-walkthrough.md

Commit 2245bc8d409e0c3180bec6179ca49be065e589b2 introduced an extra white space.

Fix incorrect indent in config.yml example

---

jekyll/_cci1/docker.md
jekyll/_cci1/language-go.md
jekyll/_cci1/yarn.md

Fixes #1024.
The following commit broke the use of the OS Matrix. Fixed the datafile path. https://github.com/circleci/circleci-docs/commit/900897fef1b1ecd691a7dd407026e66c2a0ad959#diff-992354a1328175b1b05dfe6ae0d2f285

Fix OS Matrix occurrences.

---

jekyll/_includes/global-footer.html
jekyll/_includes/global-nav.html
jekyll/index.html

This patch adds three things:
* Missing link to Premium Support in the header nav (to match inner)
* Link "Support" in "/docs" index page to Premium Support (Only non-linked header on page)
* Adds "Premium Support" link to footer (This is new, open to removing it)

Add Premium Support links to match inner

---

jekyll/_cci2/custom-images.md

Current:
This moves the custom images doc out of the "configuing jobs" category which is already growing a bit long in the tooth. Also, the only relevant part to actual configuration here is where you can specify the custom image, but I honestly forgot where this page was -- it makes more sense under "docker" IMHO <3

Move custom-images under docker category

---

jekyll/_cci2/executor-types.md

This removes the banner now being used only for Beta features (see #1031) available to paying customers and replaces it with bold running text.

update executor-types.md remove banner&add warning

---

jekyll/_cci1/deploy-google-app-engine.md

During the testing phase, extra artifacts (not git commited) may be generated on CircleCI,
and will be deployed by `gcloud app deploy` to App Engine.
This behavior is normally not expected, so it should be noted.

Note that gcloud may deploy extra artifacts

---

jekyll/_cci2/language-python.md
jekyll/_cci2/project-walkthrough.md

This updates the language docs for Python and links to the correct demo projects on the CircleCI public org for Flask and Django from this doc and the walkthrough.
It's not complete yet, but I'm merging since the old demo Flask app was inaccurate and causing issues for people trying to follow the instructions.
More comments and information will be added soon.

Update Python demo projects

---

jekyll/_ccie/docker-install.md
jekyll/_ccie/on-prem.md
jekyll/_ccie/overview.md
jekyll/_ccie/troubleshooting-install.md
jekyll/_ccie/upgrade-to-GA.md
jekyll/_data/api.yml

This PR was meant to fix versions of the word GitHub to it's proper form. This PR does this, but also caught several spelling errors along the way.

Fix branding for GitHub.

---

jekyll/_cci2/language-go.md

I have updated the Go demo project to build using the official CircleCI images (https://github.com/CircleCI-Public/circleci-demo-go/pull/3)
This updates the associated language doc:
- link to the correct repo on the CircleCI public org
- remove 'sample config' section since we should keep these in the projects themselves
- restructuring for clarity
- grammar and clarity fixes

Update Go language doc

---

jekyll/_cci2/index.md
jekyll/_cci2/language-clojure.md
jekyll/_cci2/language-javascript.md
jekyll/_cci2/language-php.md
jekyll/_cci2/language-python.md
jekyll/_cci2/language-ruby.md

This fixes links to all the main language demos.
The language docs themselves have been simplified since they contained inaccurate and outdated information. We will expand the details in the docs over the coming days.
I'm hoping to get this merged on the principle that it's better to have limited but accurate information instead of extensive outdated information.

Update 2.0 language docs

---

jekyll/_cci1/parallel-manual-setup.md
jekyll/_cci1/test-metadata.md

Originally pointed out here by @conwayje:
https://discuss.circleci.com/t/metadata-collection-parallelization-leads-to-time-out-for-rspec/12720
Unless you specify a formatter which actually outputs to STDOUT, which junit formatter doesnt,
your rspec command will eventually be killed if it takes longer than 10 minutes (without output).
Also, this patch addresses unnecessary require and instructions for rspec_junit_formatter gem

Fix doc boog where rspec formatter missing from config

---

.circleci/config.yml
jekyll/_cci2/faq.md

We've found almost no body is using the image. The image will be still there but we should stop recommending this as we move to Convenience image.

WIP Delete the mention of circleci/build-image from FAQ

---

jekyll/_ccie/on-prem.md

Looks like a reference to an older provision-builder script got missed.

Update provision-builder script references

---

jekyll/_cci2/index.md

point language links to language guides as Nathan suggested, point other links to the get started and migration documents, fix up the text

Fix index links

---

jekyll/_ccie/faq.md

The prior command no longer worked due to a location change of where we save the secrets

Corrected command to get builder secret

---

jekyll/_cci1/configuration.md
jekyll/_cci1/faq.md
jekyll/_cci1/index.md
jekyll/_cci1/manually.md

Just a little love for the 1.0 collection, using the landing page to provide the language versions and limited set of links, overview information, and adding TOCs to the long getting started docs

Top level v1 doc update

---

jekyll/_ccie/single-box.md

Here's what it looks like in place:

Add a video walkthrough of the single-box install

---

jekyll/_cci2/language-javascript.md

In language_javascript.md the information pertains to NodeJS, but in the "Pre-built CircleCI Docker images" section, the instructions reference Python. I've updated this to say NodeJS.

Replace Python with NodeJS

---

jekyll/_api/v1-reference.md
jekyll/_data/api.yml

The artifacts API response changed recently. I have confirmed that the change is permanent.
This updates the examples and adds notes explaining the some of the response keys and values.

Update artifact API examples

---

jekyll/_cci2/demo-apps.md

Make it clear that the 'language' links go to our 'language guides'

Change heading label

---

jekyll/_cci2/google-container-engine.md

This PR introduces Google Cloud configuration documentation for CCI 2.0 for Google Cloud Platform (in the way of general authentication instructions for service accounts) and Google Container Engine.
This document draws on various sources, most notably the [1.0 documentation for GKE](https://circleci.com/docs/1.0/continuous-deployment-with-google-container-engine/).

2.0 Documentation for Google Cloud/GKE

---

jekyll/_cci1/build-image-macos.md
jekyll/_cci1/continuous-deployment-with-aws-codedeploy.md
jekyll/_cci1/ios-builds-on-os-x.md
jekyll/_cci1/ios-code-signing.md
jekyll/_cci1/ios-getting-started.md
jekyll/_cci1/language-php.md
jekyll/_cci1/language-ruby-on-rails.md

I've been reading through the Getting Started, Build Images, Languages, Mobile Platforms and How-To sections of the 1.0 documentation as part of my training. I noticed a few spelling mistakes while reading through the documents and thought I'd contribute to fix them. See the commit history/diff for which specific words were corrected and in what files. 😸

Fix spelling mistakes throughout 1.0 documentation

---

jekyll/_cci1/browser-debugging.md
jekyll/_cci1/ssh-between-build-containers.md
jekyll/_cci1/troubleshooting-ios-and-OSX.md

Similar to #1127, I read through the remainder of the 1.0 documentation today (specifically the Troubleshooting, Reference, Parallelism, and Privacy and Security sections) and found a few more spelling mistakes and thought I'd send a PR in that fixed them. See the commit history/diff for which specific words were corrected and in what files. 💃

Fix spelling mistakes throughout remainder of 1.0 documentation

---

jekyll/_ccie/aws.md
jekyll/_ccie/config.md
jekyll/_ccie/docker-install.md
jekyll/_ccie/gpu-configuration.md
jekyll/_ccie/logging.md
jekyll/_ccie/on-prem.md
jekyll/_ccie/proxy.md
jekyll/_ccie/quick-start.md

Similar to #1127 and #1132, I'm reading through all of the CircleCI documentation as part of my training. While I was reading through the CCIE documentation, I found a few spelling mistakes and a couple of other things that I thought could be improved. See the commit history/diff for which specific words were corrected and in what files. 🧀

Fix spelling mistakes throughout CCIE documentation

---

jekyll/_cci1/installing-elasticsearch.md

The variable referenced by the source file (`site.data.trusty.versions.summary.elasticsearch`) apparently isn't bound, resulting in the absurd statement in the rendered page: 
"The default version of Elasticsearch is ."

Identify the default elasticsearch version

---

jekyll/_cci2/artifacts.md
jekyll/_cci2/building-docker-images.md
jekyll/_cci2/caching.md
jekyll/_cci2/circleci-images.md
jekyll/_cci2/configuration-reference.md
jekyll/_cci2/custom-images.md
jekyll/_cci2/docker-compose.md
jekyll/_cci2/docker-layer-caching.md
jekyll/_cci2/env-vars.md
jekyll/_cci2/executor-types.md
jekyll/_cci2/faq.md
jekyll/_cci2/local-jobs.md
jekyll/_cci2/parallelism-faster-jobs.md
jekyll/_cci2/private-images.md
jekyll/_cci2/ssh-access-jobs.md
jekyll/_data/categories.yml

This wad adds a new category for Virtualization and changes Configuring Jobs to Configuration. The goal of the structure is to help a new person understand virtualization in 2.0 and their options first then to start at the beginning with configuration. I also retitled many articles to make them more meaningful and action-oriented.
Virtualization:
-Executor Types -> Configuring Test Machine Images
-CircleCI Images -> Using Pre-Built CircleCI Docker Images
-Building Custom Docker Images
-Using docker-compose -> Installing and Using docker-compose
-Docker Layer Caching-> Enabling Docker Layer Caching
-Using Private Images
Configuration:
-Running Jobs Locally -> Using the CircleCI Command Line Interface (CLI)
-Configuration Reference-> Writing Jobs with Steps 
-Environment Variables -> Using …

Restructure config sections

---

jekyll/_cci2/index.md
jekyll/_cci2/language-clojure.md

While including bin/lein in the repo might have some advantages, it's
still a very unusual practice with little uptake.

Use the lein script included in the image for Clojure.

---

jekyll/_cci2/defining-multiple-jobs.md

Reported on Twitter: https://twitter.com/nschloe/status/874900459194023936
The workflows PR removed this page. This adds a redirect to workflows from the removed page.
Merging to fix broken links from Google and internal search.

Add redirect for multiple jobs page

---

jekyll/_data/api.yml

Respecting parallelism set via the API (or project settings) leads to
unexpectedly parallel jobs.
This is pending acceptance of PRs in other repos.

2.0 parallelism is only to be set via config.

---

jekyll/_cci2/language-java.md

Saying "In each job, we have the option of specifying a working_directory" is misleading: my build immediately broke without providing a working directory in `config.yml`.

Working directory is mandatory, not optional

---

jekyll/_cci2/configuration-reference.md

Now we support top level shell option with `job.shell`.

Adding job.shell to reference page

---

jekyll/_cci2/migrating-from-1-2.md

Some context was lost in the environment variable section at some point.  It was in this pull request earlier:
https://github.com/circleci/circleci-docs/pull/1065/files

Re-add missing context for interpolating env vars

---

jekyll/_ccie/config.md
jekyll/_ccie/on-prem.md

urls remain valid, but will no longer appear in the navigation

hide the lxc docs in prep of sunsetting.

---

jekyll/_cci2/workflows.md

Seems like job with no config should be without colon. I was getting parsing error until removed trailing colon:
`* error parsing config: yaml: line 100: mapping values are not allowed in this context`
part of failing config example (lines 95-105):
```
workflows:
version: 2
build_and_deploy:
jobs:
- build:
- publish_api_client:
requires:
- build
filters:
branches:
only: master
```

Fix mistype in workflow example

---

jekyll/index.html
jekyll/support.html

This adds a temporary page at `/docs/support/` that will eventually be hosted on 'outer'. It will be linked from new item labelled 'Get Support' in this menu from the top bar:
Reason: Currently customers are unsure how to contact support since the 'middle way' for paid plans is not linked anywhere.
When the 'outer' team have created a page based on this one it will be removed.

Add temporary support info page

---

jekyll/_cci2/local-jobs.md

Users can set environment variables with `-e` flag, e.g.
```sh
circleci build -e MY_TEST_VAR=myvalue
```

Environment variables are settable now

---

jekyll/_cci2/high-uuid-error.md

There will be a link the page from the build-agent when hitting the error for more details.

CIRCLE-5559 Add troubleshooting for high userns remapping failure

---

jekyll/_cci2/building-docker-images.md
jekyll/_cci2/configuration-reference.md

We are starting to support to support specifying different non-default images, primarily to allow different versions of docker - a highly requested feature.
Will follow up with more documentation explaining our machine image management (e.g. announcements, deprecation policy, image content) as well as expected SLA for providing support once a Docker release is made.
This PR is to provide a soft-launch of the feature.

[CIRCLE-5502] Support specifying machine images

---

jekyll/_cci2/migrating-from-1-2.md

Fix example in migrating-from-1-2.md workflow doc
Without the `:` it doesn't work

Fix example in migrating-from-1-2.md workflow doc

---

jekyll/_cci2/configuration-reference.md
jekyll/_cci2/workflows.md

Mention both options for specifying branch filters.
Update the workflows example config to include both variants.

Clarify workflow filter specification

---

jekyll/_cci2/local-jobs.md

the directory is /usr/local/bin, not /usr/local/bin/circleci

circleci is a script, not a directory

---

jekyll/_cci2/configuration-reference.md

Replaced ‘what directory’ with ‘in which directory’ to improve how the description reads.

Updated configuration reference for Circle 2.0

---

jekyll/_cci2/migrating-from-1-2.md

Otherwise you get:
`tee: /etc/hosts: Permission denied`

Update docs to run tee as sudo when modifying /etc/hosts

---

jekyll/_cci2/private-images.md

It came to my attention we don't currently document the ability to use the `machine` executor for private images. We will also need to elaborate on the `executor-types.md` page.

Using a private image on the `machine`

---

CONTRIBUTING.md
jekyll/_cci2/executor-types.md

bringing [Machine Executor Overview](https://circleci.com/docs/2.0/executor-types/#machine-executor-overview) text in line with info in [Writing Jobs with Steps](https://circleci.com/docs/2.0/configuration-reference/#machine)
also fixed a tiny typo in `contributing.md`

update 'executor-types' language w.r.t `machine` executor

---

jekyll/_ccie/high-availability.md

This lets the user "follow" the logs so that they can see what is happening inside of the container.

update log command

---

jekyll/_cci2/configuration-reference.md

Without it we raise this error during "Spin up Environment":
* json: cannot unmarshal string into Go struct field JobDescription.docker of type config.ContainerConfig

Fix config error in config reference

---

jekyll/_cci2/workflows.md

Approvals are more of an advanced feature so don't lead with them.
Also
* Removes explicit transitive dependencies from config sample
* Minor wording fix for what happens once the approve button is clicked

CIRCLE-5713 - Move approval jobs to after the general workflows config

---

jekyll/_cci2/contexts.md

The code as written would not do what is expected: it would set `FOO` to an empty string and try to execute `bar` with the arguments `make` and `install`.

Fix typo: remove space in env variable assignment.

---

jekyll/_cci2/migrating-from-1-2.md

* Say where to set parallelism to 1 when migrating to 2.0
* Add an example for how to replace `checkout: post:` commands , it's not immediately clear that each command from the `checkout: post:` list should be a separate step otherwise.

CIRCLE-5713 - Some clarifications on how to migrate

---

jekyll/_cci2/configuration-reference.md

- The `jobs` stanza is a map, not a list.
- Be more clear about what jobs are run when.

Improve job and build descriptions

---

jekyll/_cci1/firebase-test-lab.md

For the latest version of `gcloud`, need to specify `firebase` group to invoke a test in Firebase Test Lab.
The documentation is [here](https://cloud.google.com/sdk/gcloud/reference/beta/firebase/test/android/run)

Fix the command to run a test in Firebase Test Lab

---

jekyll/_cci2/workflows.md

Sadly 2.0 build falls back to 1.0 when there are tabs in config yml. Therefore, copy/paste these examples won't run on 2.

Removing tabs

---

jekyll/_cci2/executor-types.md

Remove specific versions from this page so they don't need to be updated in two places when we change versions and add note about pinning image versions. This page contains the current version details: https://circleci.com/docs/2.0/configuration-reference/#machine

Update machine image options

---

jekyll/_cci2/artifacts.md

It was calling the C file `config.yml` instead of `main.c`, which is what the Makefile is looking for.

Fix typo in core dump example

---

jekyll/_cci1/oom.md

Tested this on a private OCaml project running on Circle. Thanks to @stedolan for the explanation and @sgrove for testing.

Update oom with instructions for OCaml/Reason

---

jekyll/_cci2/workflows-waiting-status.md

The current version does not make it clear whether, when using a workflow, one should _ever_ expect the `ci/circleci` status check to return.
I think what is being said is that if you use a workflow you will only see `ci/circleci:job_name` checks, but since my expectation was that I might still see a `ci/circleci` check complete at the end of the process this document does not provide clarity, and I suspected my integration was faulty. Noncommittal language like "may prevent the status from showing as completed" (surely it _always_ will, for a workflow?) obscures what you need to do. The term "reset" (along with the annotations) also made me think I may need to turn branch protection or certain checks off then on again (which again I guess is not what was meant).
If something to the …

Clarify whether the `ci/circle` Github check will ever run for a workflow

---

jekyll/_cci2/workflows.md

Was previously fixed (9160399b) due to misplaced tabs, but accidently not replaced with the right amount of spaces.

Fix indentation for use of context within Workflows

---

jekyll/_cci2/caching.md

Quote "pom.xml" since it is meant to be used as a string.

Fix example in caching.md

---

jekyll/_cci2/ios-migrating-from-1-2.md

This will make job runs faster for everyone who uses CocoaPods. We automatically run this on 1.0 platform, and we have to show customers how to do this on 2.0.

Add an example for downloading CocoaPods specs from S3

---

jekyll/_cci2/language-android.md

just a draft sentence about the emulator for https://github.com/circleci/circleci-docs/issues/1483
maybe this should also be mentioned in the docker images section (or only there)?

add limitation to language-android.md

---

jekyll/_cci2/configuration-reference.md

You shouldn't leave valuables just lying around in the environment map!

Typo fix in configuration reference

---

jekyll/_cci2/building-xcode-projects.md
jekyll/_cci2/ios-tutorial.md
jekyll/_cci2/sample-config.md

Hi @michelle-luna, I've made some quick updates targeting your mobile docs branch.
The changes are mostly about the new `config.yml` syntax, and limiting the examples to xcode `9.0` and `8.3.3`.
We also do not have support for running builds by specifying only the `x.y` build number at present, so I have removed that advice.

Fix up some example macOS config.yml 

---

jekyll/_cci2/ios-migrating-from-1-2.md

We recently updated the macOS 2.0 config, and we need to reflect the change in the docs.

Remove the Version stanza from the macOS 2.0 example

---

jekyll/_cci2/aws.md

The policy does not work in the current state. Including these two additional permissions will allow users to use our recommended IAM policy to install CircleCI Server on AWS with terraform.

[CIRCLE-6790] Update IAM policy document

---

jekyll/_cci2/caching.md

Addressing 2 issues:
1.  Old example implies caches are re-writeable: 
> Cache is written in chronological order. Consider a workflow of Job1 -> Job2 -> Job3. If Job1 and Job3 write to the same cache key, a rerun of Job2 may use the changes written by Job3 because Job2 ran last.
I reworked this example to emphasize that workflow jobs can share caches, and a race condition to be aware of.
2. Added an example of another kind of job cache race condition: a cache not yet existing when it's requested.  This came up in this ticket:
https://circleci.zendesk.com/agent/tickets/23696/events
Let me know if 1) changed the intent of the original doc too much and I can cut that part out.

Clarify jobs/workflows caching example

---

jekyll/_cci2/env-vars.md
jekyll/_cci2/parallelism-faster-jobs.md

The introduction of $CIRCLE_INTERNAL_TASK_DATA.
Test timing data is not stored in the same location between executor types.

$CIRCLE_INTERNAL_TASK_DATA

---

jekyll/_cci2/configuration-reference.md

Replacement indicators' text typically explains what it is (e.g,. a job name), not some particular replacement value (e.g., "build").

Update replacement indicators’ text.

---

jekyll/_cci2/executor-types.md

We currently recommend the Docker image `docker:17.05.0-ce-git` as the base, generic, use this if you just need a basic Docker image with git support.
That version of Docker is no longer supported. Docker has a release cycle that includes longer, "stable" versions and intermediate release images. Very similar to the model Ubuntu uses.
The Docker Hub repo has a tag `docker:stable-git` that will move in between stable, longer supported releases only and not intermediate releases (which Docker 17.05 was).

Change out base/generic Docker image tag recommendation.

---

jekyll/_cci2/configuration-reference.md

We do not automatically checkout git submodules. This causes confusion to customers who use them. While this is documented in the 1.0 docs https://circleci.com/docs/1.0/manually/#checkout it is completely missing from 2.0. Correcting this.

Added notes regarding submodules

---

jekyll/_cci2/language-ruby.md

The `--out test_results/rspec.xml` needs to follow the `--format RspecJunitFormatter`, not the `--format progress` command, otherwise, the rspec.xml file will have the non-xml contents written to it, and the test-output seen in the UI will be the XML format.
This will result in a "Test Summary" saying:
> The following errors were encountered parsing test results:
> rspec.xmlParseError at [row,col]:[2,1] Message: Content is not allowed in prolog

Fix order of format statements, resolves error "Message: Content is not allowed in prolog"

---

jekyll/_cci2/language-elixir.md

update Elixir docker image to the official address,  add `run: mix local.hex` and `run: mix local.rebar` since both are required to present in a common Elixir application for `mix deps.get`

Update to official Elixir docker image

---

jekyll/_cci2/sample-config.md

`step:` key should be `steps:`

Fix typo on sample-config.md

---

jekyll/_cci1/test-metadata.md

I'd always assumed that this was a hard requirement.  It looks like it works but just produces a confusing report summary in the build.

Clarify test results subfolder 'requirement'

---

jekyll/_cci2/language-ruby.md

Fixing old syntax reported here: https://discuss.circleci.com/t/is-there-a-difference-between-run-vs-type-shell-steps/17022

Fix old config syntax in Ruby doc.

---

jekyll/_cci2/hello-world.md

I thought that the dot was missing, so I changed it to `~/.circleci/config.yml`.

~/circleci/config.yml ➡️ ~/.circleci/config.yml

---

jekyll/_cci2/language-ruby.md

If you write multiple command in yml, need a vertical line after `run:`.

Add a vertical line to command of spec

---

jekyll/_cci2/configuration-reference.md

Just remove `:` because of yaml syntax error.

Fix yaml syntax error at sync git submodule

---

jekyll/_cci2/ios-tutorial.md

Xcode version number needs to be quoted as a string, or this example will fail.

enquote xcode version number

---

.circleci/config.yml
Gemfile
Gemfile.lock

There was a recent release with a number of security vulnerabilities:
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-3-5-released/

Bump ruby to latest 2.3.x patch level

---

jekyll/_cci2/building-docker-images.md

In the first example using the `machine: true` the comments refer to a docker container when I think you mean docker image. You don't build containers or push them to docker hub. You build images and run containers.

Use the proper vocabulary wrt docker images

---

jekyll/_cci2/ios-codesigning.md

Seemed like we were missing a link there.

Adding a link to the testing iOS doc

---

jekyll/_cci2/executor-types.md

Updating to reflect that we now support layer caching on machine executor
https://circleci.com/docs/2.0/docker-layer-caching/#nav-button

DLC is now supported on machine executor

---

jekyll/_cci2/configuration-reference.md

It was auto-recognized as a diff and so highlighted in red, because all lines started with a dash.

Specify language for code block

---

jekyll/_cci2/executor-types.md
jekyll/_cci2/faq.md
jekyll/_cci2/sample-config.md
jekyll/index.html

For the executor-types.md doc, should we add a compelte section for the macos executor type with information about available xcode versions/updates, etc? I just added a link in that document for now, but we might want to make a complete section for this third executor type to make this difference clear to customers?

WIP: ios changes

---

jekyll/_cci2/deployment_integrations.md

@keybits added `sudo` to the Heroku script [back in September](https://github.com/circleci/circleci-docs/commit/d9d919f5deb1c828e609a8bb9ef6527cdd17e43c#diff-63f3e207b64870e2bf3183435fb4921b), most likely because many customers use our [convenience Docker images](https://hub.docker.com/r/circleci), where the user is `circleci` rather than `root`; however `sudo` was taken back out a month ago in a [community-submitted PR](https://github.com/circleci/circleci-docs/pull/1672), most likely because most vanilla Docker images *do* have `root` as their user. Hopefully this is a good compromise?

add note re: sudo to Heroku deployment info

---

jekyll/_cci2/deployment_integrations.md

A user running our convenience image said that running the script with `sudo` failed later on in the script with SSH-ing into Heroku.  Re-arranging this to support our convenience image users first

Update note re: sudo to Heroku deployment info

---

jekyll/_cci2/backup.md

Two additional steps are required to successfully backup && restore from snapshots (removing the Nomad folder && restarting the "new" instance after the changes have been made to the replicated config).

Add 2 new steps

---

jekyll/_cci2/testing-ios.md

We noticed that the paths were set incorrectly in the fastlane example.
Fixing it here.

Set paths correctly in the fastlane example

---

jekyll/_cci2/gh-bb-integration.md

https://github.com/circleci/circleci-docs/issues/1767

fix typo in add ssh keys syntax

---

jekyll/_cci2/workflows.md

Added a note below the example config to stress the need for a tag filters section on job dependencies. Although this requirement is clearly stated at the top of the `Git Tag Job Execution` section - probably a good idea to re-iterate this concept within the example.

Emphasizing need for tag filters on dependent jobs

---

jekyll/_cci2/demo-apps.md
jekyll/_cci2/language-android.md
jekyll/_cci2/testing-ios.md

Link to the [React Native sample app](https://github.com/CircleCI-Public/circleci-demo-react-native)
in various doc sections.

[CIRCLE-6879] Link to the React Native sample app

---

jekyll/_cci2/ios-migrating-from-1-2.md

There was spacing in the link between `[]` and `()` causing the broken
link

Fixes a broken markdown link due to spacing.

---

jekyll/_cci2/docker-compose.md

As issue #1323 mentioned, using curl to download and directly pull files into `/usr/local/bin/docker-compose` will result in `permission denied error`.

Fix permission denied error of install docker-compose #1323

---

jekyll/_cci2/language-ruby.md

This patch will fix an issue that `{% raw %}` is [rendered in the document](https://circleci.com/docs/2.0/language-ruby/).

Add a missing {% endraw %} tag

---

jekyll/_cci2/workflows.md

Fixing syntax error in example file for sharing data among jobs.

Fixing syntax error in example file for sharing data among jobs

---

jekyll/_cci2/artifacts.md

Changed for consistency, users are instructed elsewhere in docs to set the env var `CIRCLE_TOKEN` to be their token, we shouldn't have them change it to a query string with their `CIRCLE_TOKEN` as they would need to change it again to do normal API things.

Update CIRCLE_TOKEN env var reference

---

jekyll/_cci2/collect-test-data.md
jekyll/_cci2/configuration-reference.md
jekyll/_cci2/faq.md
jekyll/_cci2/parallelism-faster-jobs.md

we were documenting the timing-based test-splitting + workflows issue slightly inaccurately—it's not that `store_test_results` doesn't work w/ workflows (it does—otherwise Test Summary wouldn't work at all); it's just that using `circleci tests split --split-by=timings` doesn't work w/ workflows. so really, the only place we need that note is on the Running Tests in Parallel page, imo at least...

Iynere test results workflows patch

---

jekyll/_cci2/configuration-reference.md

it's 1) confusing to link to a part of our 1.0 documentation that mentions `$CIRCLE_TEST_REPORTS` when this env var doesn't even exist in 2.0, and 2) probably just not ideal in general to be linking to our 1.0 documentation to explain things about 2.0, right ?
i took the info [here](https://circleci.com/docs/1.0/test-metadata/#metadata-collection-in-custom-test-steps) & just restated it, more or less, in a way that makes sense for 2.0

Update store_test_results in config reference

---

jekyll/_cci2/building-docker-images.md

This just updates the suggested URL for getting the docker client for a docker build.

The URL for getting the docker client is out of date

---

jekyll/_cci2/configuration-reference.md

Regex rules for `branches` and `tags` were confusing some folks. This is a potential fix for #1886.

Improve regexplanations

---

jekyll/_cci1/build-image-macos.md

Fix incorrect build numbers, add note about future Xcode versions. Potential fix for #1885.

update supported xcode versions

---

jekyll/_cci2/aws.md

All of this instance sizing guidance doesn't really apply to 2.0. The IAM user auth documentation is out-of-date too, and I don't think we should be encouraging non-instance-profile authentication anyway.

Delete some out-of-date info

---

jekyll/_layouts/classic-docs.html

see ticket: https://circleci.atlassian.net/browse/CIRCLE-8444
This PR addresses the problem by re-adding the js tags that where removed when the footer was changed. (I accidentally removed the tags - doing so because they were improperly placed at the bottom of the footer tag instead of in the site layout).

adding script tags to proper location

---

jekyll/_cci2/workflows.md

GMT is not the same as UTC, so shouldn't be included as if it were.

Removes GMT from the timezone description.

---

jekyll/_cci2/postgres-config.md

The wrong type of quote characters exist in examples. Copy-pasting leads to much confusion and frustration!

Fix quotes in postgres config examples

---

jekyll/_cci2/demo-apps.md

First link wasn't pointing to an actual demo application. Potential fix for #1937.

remove offensive android link

---

jekyll/_cci2/collect-test-data.md

Currently Minitest setup is invalid and does not work with 2.0. With the new updates this allows a user to auto upload the reports to circleci test summary without error as, by default the reports are generated and saved to a folder reports under test folder in the repo. These updates have been tested and are valid for 2.0 builds.

Update how to save minitest-ci reports

---

jekyll/_cci2/high-availability.md

Fixes #1956. Also makes "Note" capitalization consistent and removes dash from "high availability" phrase.

make HA language more explicit

---

jekyll/_cci2/language-android.md

It was unclear at first reading what "not supported" meant:
- Explicitly blacklisted, so don't even try?
- Not supported out of the box, but feel free to yak-shave?
- Not technically possible?
Language from the 1.0 docs clarifies that the correct choice is
"not technically possible," due to virtualization issues.
The language added is drawn from:
https://github.com/circleci/circleci-docs/blob/9b8e6b6fd055ca78ec20b558589f7f0bd1dfdb1b/jekyll/_cci1/android.md#starting-the-android-emulator

Android: Clarify "emulator not supported"

---

jekyll/_cci2/workflows.md

Fixes #1933 
There's a fair bit of revision in this PR. Highlights include:
- some editing of the **Overview** and **Limitations** sections
- italicized link to the specs for the `workflows` key at the top of the **Workflows Configuration Examples** section
- repositioning of the **Restart From Failed** scenario to reflect importance; performing this step requires configuring a valid workflow and the ordering should reflect that.

Move workflows spec link

---

jekyll/_cci2/circleci-images.md

I tried to install PostgreSQL with `- image: postgres:10.1-postgis`. It failed. What worked for me was `- image: circleci/postgres:10.1-postgis`. I assume, the other images work the same way.

Add circleci prefix to images

---

jekyll/_cci2/collect-test-data.md

I should have added these comments while #1990 was in review, but I merged before I made the edits. These comments just clean up this section and remove some links so people don't get scared off by the `--runInBand` issue.

Minor edits for Jest section

---

jekyll/_cci2/configuration-reference.md

`CPU` -> `vCPUs` is more for accuracy, less important.
The `1.0` -> `1` change I think is useful because there's no such thing as a fraction of a CPU or vCPU.

Alter CPU wording for resource classes.

---

jekyll/_cci2/circleci-images.md

This is a reworking of the beginning sections of the "Pre-built CircleCI Docker Images" article. It adds:
- a revised overview
- distinctions between **language** images and **service** images
- lists of tools pre-installed on every image
- explanations of image variants
Fixes #2009 and #2012.

Improve CircleCI Images Docs

---

jekyll/_cci2/collect-test-data.md

pytest expects the --junitxml argument to be the file to store the results in, not a directory.

Update pytest docs for collecting test results

---

jekyll/_cci2/workflows.md

We meant to reference the build job, not the test job in this workflow.
we might consider changing:
```
only: /^config-test.*/
```
to
```
only: /^v.*/
```
To represent an actual workflow of building and testing on every push, but only releasing on tags that start with `v` - as in: `v0.0.1`.

docs: minor typo

---

jekyll/_cci2/deployment-integrations.md

The `- checkout` step was missing in the Heroku deployment docs steps. I'm only familiar with Heroku and use Heroku but I'd assume the checkout step needs to be added to the other deployment provider docs as well as they're missing too.

Add - checkout step to Heroku deployment docs

---

jekyll/_cci2/deployment-integrations.md

I tried to deploy to heroku, and it did not work.
I found the solution adding `heroku git:remote -a jiayuan-example`.

Need to add heroku remote to git

---

jekyll/_cci2/caching.md

Fixes #2073 
@zzak I've added you here because I based the caching changes on one of your [workflows examples](https://github.com/CircleCI-Public/circleci-demo-workflows/blob/fan-in-fan-out/.circleci/config.yml).

replace cache keys with more generic example

---

jekyll/_cci2/glossary.html

Glossary was being sorted by filename rather than term name.

sort terms before generating list

---

jekyll/_cci2/ios-migrating-from-1-2.md

Fixes #2072
Bundle path must be specified before bundle command is used.

move up scope of BUNDLE_PATH

---

jekyll/_cci2/language-elixir.md

The link to the example repo is broken. I think this is the right one.

Fix link in elixir docs

---

jekyll/_cci2/migrating-from-1-2.md

Fixes #2085 
New environment variable behavior needed to be more explicitly called out in the migration doc. Specifically, workarounds re: env var interpolation were unclear.

Add details about changed environment variable behavior in 2.0

---

jekyll/_cci2/status-badges.md

Fixes #2097 
Rereading this makes me wonder why we don't just default to the shield style for status badges. Those seem to be the industry standard, so it's odd to force users to do extra work to get that.

Update status badges source

---

jekyll/_cci2/workflows.md

The first change was the missing word in the description of approval jobs, then I noticed there was some inconsistency in capitalisation, and a sentence about contexts that I felt was better suited to earlier in the docs.
I've noticed there's an inconsistency in referring to keys. Sometimes they are `keyname:` and sometimes `keyname` without the colon. Is there a preference?

Some updates and consistency for Workflows

---

jekyll/_cci2/ios-migrating-from-1-2.md
jekyll/_cci2/testing-ios.md

A customer pointed out that Fastlane outputs a file named `report.junit`.
This needs to be renamed to be picked up by our test results parser.

Correct macos test results

---

jekyll/_cci2/google-auth.md
jekyll/_cci2/google-container-engine.md

Fixes #2134 and fixes #1670.
While working on this document, I realized a couple of things:
1. There is a lot of overlapping information between [this document](https://circleci.com/docs/2.0/google-container-engine/) and the [Authenticating Google Cloud](https://circleci.com/docs/2.0/google-auth/) document.
2. Both documents are mostly focused on steps preceding the *actual deploy* (authentication, environment variables, etc.).
3. The actual deploy instructions seem to be on the [deploy landing page](https://circleci.com/docs/2.0/deployment-integrations/#google-cloud), but these seem to be a bit lean.
---
At the very least, we should consolidate [Authenticating Google Cloud Platform](https://circleci.com/docs/2.0/google-auth/) and [Deploying to Google Container …

Google Container Engine clarifications

---

jekyll/_cci2/contexts.md
jekyll/_cci2/deployment-integrations.md
jekyll/_cci2/env-vars.md

This is a clarification of order precedence and addition of couple of other env vars that are loaded but which were not documented. I changed the list around for clarity, then re-ordered the sections to match what I believe to be the correct ordering (but, please check this for accuracy).

Env vars update

---

jekyll/_cci2/gh-bb-integration.md

Fixes #2133. Fixes #1667.
These changes highlight the differences between user key generation for both GitHub and Bitbucket. The entire document could benefit from more clearly calling out these differences. It's a bit misleading to overgeneralize processes between the version control systems.
Will create a follow-up JIRA ticket to capture potential improvement.

Document differences between GitHub and Bitbucket user key creation

---

jekyll/_cci2/gh-bb-integration.md

This is a follow-up to #2164 and adds some necessary details around where to locate the generated Bitbucket user key.

Add context to Bitbucket user key workaround

---

jekyll/_cci2/ios-codesigning.md
jekyll/_cci2/ios-migrating-from-1-2.md
jekyll/_cci2/testing-ios.md

We no longer need to copy the .junit file over for TRS
Reverts and fixes up #2131

Adjust docs wrt CIRCLE-9621

---

jekyll/_cci2/google-auth.md
jekyll/_cci2/google-container-engine.md

Fixes #2193.
Some cleanup around base64 encoding of the JSON service account for GCP authentication.

JSON key should not be encoded

---

jekyll/_cci2/env-vars.md

This note was copied from the article on moving from Circle 1.0 to 2.0, but it would be good to have it here as well.

Added limitation and workaround for interpolating environment variables

---

jekyll/_cci2/env-vars.md

Replace outdated workaround with simple one. Explicitly call out lack of direct support for environment variable interpolation.

Replace interpolation workaround with simpler one

---

jekyll/_cci2/faq.md
jekyll/_cci2/parallelism-faster-jobs.md

Monster PR that fixes #1471. This is a full revision of the test splitting document with the following goals:
- clarify how split tests are actually run
- reorganize and reorder for better flow
- a slew of language improvements

Clarify how split tests are run

---

jekyll/_cci2/circleci-images.md

DockerHub limits the tags it shows to the 100 most recent.  For example:
https://hub.docker.com/r/circleci/ruby/tags/
There is no pagination on that page.  The previous template suggesting that link for "all available tags" was incorrect.

Change template text

---

jekyll/_cci2/aws.md

clarify that `m4.2xlarge` is for all instances

Iynere instance sizes patch

---

CONTRIBUTING.md

Link to wiki page that outlines GitHub Issue maintenance workflow.

link to issues workflow wiki page

---

jekyll/_includes/edit-on-github.html

Follow-up to new wiki page. This change aims to send people to the wiki page before filing an issue.

add link to wiki page in footer

---

jekyll/_cci2/postgres-config.md

It's possible that something else was going on, but I believe my config was not working due to the `=` syntax in the example. It appears to work now that I switched to `:`.

Updates YAML syntax in Postgres config examples.

---

jekyll/_cci2/concepts.md

Breadcrumb was linking to the same page.

fix breadcrumb link to basics landing page

---

jekyll/_cci2/env-vars.md

I wanted a way to consistently name artifacts created by one job that could be referenced by another job (i.e. for tagging Docker images). It took me a long time to realize that the undocumented `CIRCLE_WORKFLOW_ID` env var was available to me. 
I don't know if `CIRCLE_WORKFLOW_ID` is an "official" env var, and whether the description is accurate or not.

Document CIRCLE_WORKFLOW_ID in env-vars.md

---

jekyll/_cci2/ios-codesigning.md

I spent some time debugging my builds on CircleCI after migrating to 2.0 until I discovered that it was necessary to add this command to `before_all`. I think that this can be more explicit in the documentation.
Or at least I think the documentation should explain that `setup_circle_ci` is an actual Fastlane command and not just an example of a command one might add to their `Fastfile`.
Thanks 🙂

Add note about `setup_circle_ci`

---

jekyll/_cci2/artifacts.md

Resolves [this JIRA ticket](https://circleci.atlassian.net/secure/RapidBoard.jspa?rapidView=67&modal=detail&selectedIssue=CIRCLE-6366).

Document that build artifact URLs are encoded

---

jekyll/_cci2/non-aws.md

Fixes typo in first paragraph ("folloiwng") and adds a bit of language to correlate nomad with "builder fleet" depicted in the architecture diagram.

Minor cleanup in Non-AWS install doc

---

jekyll/_includes/edit-on-github.html

@keybits this is an adjustment of the issues we talked about last week. We had decided to add a link to the support center in the footer after the meeting re: Discuss.
However! After discussing with @michelle-luna, we feel like the footer should be reserved for links that explicitly help improve documentation. Since both Discuss and the Support Center are contained in the "Support" dropdown, we felt like it made sense to keep things consistent and not double link.
Resolves [CIRCLE-10317](https://circleci.atlassian.net/browse/CIRCLE-10317).

remove link to discuss

---

jekyll/_cci2/caching.md

Recommend lockfile checksums instead of files as cache keys.

Update caching.md: "Using a Lock File" section

---

Gemfile
Gemfile.lock
docker-compose.yml

This updates Jekyll to the last major release (v3.8.x) before Jekyll 4.0 which will have breaking changes. We'll need to pay attention to the changes in the future.
The Docker image we use for local dev is updated only to v3.8.0 for now as they haven't made an image for the latest point release.

Update Jekyll to v3.8.1.

---

jekyll/_cci2/gpu.md

Before, it required the user to copy and paste the result of `uname -r` three times, which could easily be simplified to a variable or inline command. This edit will prevent any need for user input throughout the installation process.

Removes the need for any user input in the installation commands

---

jekyll/_cci2/parallelism-faster-jobs.md

Installing the local CLI in a container will not work.

Do not install the CLI tool in a Docker container

---

jekyll/_cci2/examples.md

It looks like Microsoft switched away from using Circle CI in the TypeScript project: there is no .circleci/config.yml in the HEAD of master, so the link was dead.

Remove the link to TypeScript/.circleci/config.yml

---

jekyll/_cci2/api-job-trigger.md
jekyll/_cci2/artifacts.md
jekyll/_cci2/build-publish-snap-packages.md
jekyll/_cci2/building-docker-images.md
jekyll/_cci2/caching.md
jekyll/_cci2/collect-test-data.md
jekyll/_cci2/concepts.md
jekyll/_cci2/configuration-reference.md
jekyll/_cci2/executor-types.md
jekyll/_cci2/faq.md
jekyll/_cci2/language-android.md
jekyll/_cci2/language-clojure.md
jekyll/_cci2/language-elixir.md
jekyll/_cci2/language-go.md
jekyll/_cci2/language-java.md
jekyll/_cci2/language-python.md
jekyll/_cci2/language-ruby.md
jekyll/_cci2/private-images.md

Fixed the YAML code fence errors I found using `md-proofer`. Also standardize the use of the lowercase string `yaml` for code fences.
Not counting the superficial changes, was able to fix 11 separate code fences to be copy & pastable YAML.

Fix md proofer errors

---

.circleci/config.yml
jekyll/_cci2/api-job-trigger.md
jekyll/_cci2/artifacts.md
jekyll/_cci2/build-publish-snap-packages.md
jekyll/_cci2/building-docker-images.md
jekyll/_cci2/caching.md
jekyll/_cci2/collect-test-data.md
jekyll/_cci2/concepts.md
jekyll/_cci2/configuration-reference.md
jekyll/_cci2/executor-types.md
jekyll/_cci2/faq.md
jekyll/_cci2/language-android.md
jekyll/_cci2/language-clojure.md
jekyll/_cci2/language-elixir.md
jekyll/_cci2/language-go.md
jekyll/_cci2/language-java.md
jekyll/_cci2/language-python.md
jekyll/_cci2/language-ruby.md
jekyll/_cci2/private-images.md

Adding a tool I made [Markdown Proofer (`md-proofer`)](https://github.com/felicianotech/md-proofer) to validate code fences.
Markdown Proofer goes through a directory of `.md` files and looks for code fences (code between the backticks). If it finds YAML code fences (`  ```yaml`) it'll parse the YAML to make sure it's valid.
This will help us make sure we don't have YAML code fences with bad YAML that a user might copy & paste into their configs.
I'll open another PR to fix the issues uncovered by this PR. That PR will need to be merged first into this one before this one can passes and merged into `master`.

Add Markdown Proofer for additional testing.

---

jekyll/_cci2/add-ssh-key.md

Edited **Step 2** of this page to reflect the new navigation.
https://circleci.com/docs/2.0/add-ssh-key/
Changed it to:
> In the **Permissions** section, click on **SSH Permissions**
from 
> In the **Build Settings** section, click on **SSH Permissions**.

Edited Step #2 on Adding SSH key to CircleCI page

---

jekyll/_cci2/env-vars.md
jekyll/_cci2/parallelism-faster-jobs.md

Removed references to CIRCLE_INTERNAL_TASK_DATA. This env var seems to have been removed in this commit: https://github.com/circleci/picard-services/commit/14195162baca1243426ad0fb8fb0c93eda07f884

update CIRCLE_INTERNAL_TASK_DATA value and location

---

jekyll/_cci2/local-cli.md

CircleCI CLI supports --job option but it is not documented. 
--job string            job to be executed (default "build")
$ circleci version
circleci version: 0.0.5762-f6bc418
Build Agent version: 0.0.5763-f6bc418
built: 2018-05-22T19:06:47+0000

Added option to run jobs other than the default build

---

jekyll/_cci2/deployment-integrations.md
jekyll/_cci2/env-vars.md

Fixes #2314 and improves document flow and consistency.
Highlights include:
- Reordered sections. Sections listed in the same order as Overview
- "Setting" > "Declaring" / "Using" / "Adding". Corrected inconsistent usage.
- Created a follow-up to [reformat this section](https://circleci.atlassian.net/browse/CIRCLE-11426) with tables.
@ndintenfass and @marcomorain for technical accuracy
@michelle-luna for language edits

add warning to use environment variables in scripts

---

jekyll/_cci2/api-job-trigger.md

__WHY this PR was created__ There is an inconsistency within the `api-job-trigger.md` documentation page. The top part of the page talks about calling the `deploy_production` job while `config.yml` example at the bottom part of the page defines the `deploy_docker` job. 
__WHAT this PR changes__ This PR sets the name of the job at the top of the page to `deploy_docker` to match the `config.yml` definition

Make the name of the triggered job consistent

---

jekyll/_cci2/language-scala.md
jekyll/_cci2/tutorials.md

this was reviewed in https://github.com/circleci/circleci-docs/pull/2370 but I had the file in the wrong directory, so just moving it to cci2, fixing yaml errors found by checker, and adding link from the landing page with this update

Move scala guide to correct directory

---

jekyll/_cci2/migrating-from-1-2.md

Rather than repeat information, this change focuses users' attention on the major difference between 1.0 and 2.0 (lack of interpolation when defining certain variables), then links them to the current Env Vars document.
Resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-10062).

Remove duplicate env var section

---

jekyll/_cci2/browser-testing.md
jekyll/_cci2/caching.md
jekyll/_cci2/configuration-reference.md
jekyll/_cci2/containers.md
jekyll/_cci2/executor-types.md
jekyll/_cci2/hello-world.md
jekyll/_cci2/index.md
jekyll/_cci2/ios-migrating-from-1-2.md
jekyll/_cci2/language-python.md
jekyll/_cci2/migrating-from-1-2.md
jekyll/_cci2/parallelism-faster-jobs.md
jekyll/_cci2/reference.md
jekyll/_cci2/test.md
jekyll/_cci2/testing-ios.md
jekyll/_cci2/workflows.md

Updates "Configuration Reference" to "Configuring CircleCI" after file renaming completed #2355.
[JIRA ticket](https://circleci.atlassian.net/browse/CIRCLE-11486).

Fix inconsistent config ref naming

---

Gemfile
Gemfile.lock
docker-compose.yml

Update Jekyll and HTML Proofer to their latest, stable releases.

Update Jekyll to v3.8.3 and HTML Proofer to latest release.

---

jekyll/_cci2/building-docker-images.md

Fixes #2387 by dividing supported releases into stable and edge versions.

divide supported releases into stable/edge categories

---

jekyll/_cci2/artifacts.md
jekyll/_cci2/config-translation.md
jekyll/_cci2/env-vars.md
jekyll/_cci2/examples.md
jekyll/_cci2/status-badges.md

Updates wherever we mention making API tokens to point to the new API tokens document.
[JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-11318)

Point to new api permissions doc

---

jekyll/_cci2/language-elixir.md

If any test run has been done with this exact `mix.lock` file, use that
cache, regardless of what branch it was on.

If cache matches lockfile, branch is irrelevant

---

jekyll/_cci2/oss.md
jekyll/_data/categories.yml

This PR migrates information contained in [Building Pull Requests from Forks](https://circleci.com/docs/1.0/fork-pr-builds/) to a 2.0 document.
Since we already had a document that discussed this feature, I went ahead and stuffed the information in there. And then I got carried away with revisions.
I've added @felicianotech as primary reviewer (and original author), and @KyleTryon as the primary responder of the [related JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-11487).

Migrate forked PR build security info

---

jekyll/_includes/global-nav.html

To be consistent with Outer/Inner support dropdowns.
Left off "Docs" since we're already in docs.

Added feature requests to support dropdown

---

jekyll/_cci2/deployment-integrations.md

This PR updates the AWS section of the Deployment Integrations doc so that it isn't referring to 1.0 functionality.
This PR started as a 1.0 --> 2.0 migration in an [issue reported by Angel](https://circleci.atlassian.net/browse/CIRCLE-11833). It turned out that, while there already was a 2.0 document for deploying to AWS, it was missing a few steps and relying on a 1.0 feature.
TL; DR: original issue was different, but it exposed things that needed updating! :)

Update AWS Deploy doc for 1.0 EOL

---

jekyll/_cci2/migrating-from-1-2.md

Fix typo within migration from 1 to 2

---

jekyll/_cci2/gh-bb-integration.md

Request made by @sararead to move a 1.0 explanation about VCS permissions to 2.0. I have some open questions about:
- how this relates to Bitbucket
- how strongly we want to be encouraging our users to send their complaints to GitHub/Bitbucket
JIRA issue here: https://circleci.atlassian.net/browse/CIRCLE-11903

Migrate VCS permissions blurb to 2.0

---

jekyll/_cci2/oss.md

Since the default is to **not** build forked PRs (_Off_), changing it would require setting this to _On_.

Correct flipped instructions

---

jekyll/_cci2/workflows.md

A user brought up the lack of thorough, non-trivial examples involving workspaces in [this issue](https://github.com/circleci/circleci-docs/issues/1879). Rather than build a complete sample app from scratch, we realized that `circleci-docs` itself is actually a great example of several Workflows features.
JIRA issue: https://circleci.atlassian.net/browse/CIRCLE-8375

Link to CircleCI Docs configuration file in workspaces section

---

.circleci/config.yml

Proposing a switch to a lighter, more deterministic Docker image for the CircleCI Docs deployment.
I maintain several "CI Builds" Docker images geared specifically towards CI. This AWS image now has 10K+ pulls on Docker Hub and stable enough for Docs.
Also, it's hard to tell but this should reduce deployment time but only by a couple of seconds. We're already doing this fairly fast.
Also I did a `--dryrun` for the `sync` command to make sure it still does what we think: https://circleci.com/gh/circleci/workflows/circleci-docs/tree/try-aws-image

Use AWS Docker image for deployment.

---

jekyll/_cci2/yarn.md

Fallbacks are undesirable since they make `yarn.lock` essentially useless and caching yarn's cache also makes it so `node_modules/`is rebuilt and will also include globally installed packages.

Update yarn cache to be more reliable

---

jekyll/_cci2/add-ssh-key.md
jekyll/_cci2/configuration-reference.md

Resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-12038).
Users have been under the impression that all SSH keys are automatically added to containers by the `ssh-agent`. This PR should make it more clear that they have to explicitly use the `add_ssh_keys` special step to do that.

Clarify that the add_ssh_keys step is more necessary than you think

---

jekyll/_cci2/docker-layer-caching.md

This is to remove a backslash in the Dockerfile to prevent the curl command for installing docker-compose from being concatenated with the rm command.

Fix extra backslash in Dockerfile in Docker Layer Caching example

---

jekyll/_cci2/configuration-reference.md

On first impression and with no background in defining Regexes before, one might thinkg that you would have to define a Regex as such: `/s[a-zA-Z0-9 ]*/s` with the current documentation. This PR is a suggestion to improve the docs to become more clearer.

Improved instruction on how to define Regexes for branch filters

---

jekyll/_cci2/deployment-integrations.md

Adds cloud foundry section to deployment guide, uses blue/green deployment.
I wasn't sure if it was worth noting a full config but I have used this in https://github.com/eddiewebb/demo-blueskygreenbuilds/blob/master/.circleci/config.yml

added cloud foundry to deployment docs

---

jekyll/_cci2/caching.md

This PR changes the recommendation of basing the cache checksum on package-lock.json rather than package.json.
If a package.json has non fixed versions and these change, we could actually end up with a different `node_modules` which effectively means the cache we have saved will be outdated and it might make builds slower than unnecessary until another change to package.json actually forces an update.
See https://docs.npmjs.com/files/package-lock.json for more details.
I've decided not to include a mention to the differences between package.json and package-lock.json as the whole document seems to be not specific to node, but if a recommendation is being issued it should be a more correct one, even if it's not the purpose of the document to explain the reason of such a recommendation.

Base checksum on package-lock.json

---

jekyll/_cci2/parallelism-faster-jobs.md

Adds consistent quoting around examples of globbing for test splitting in the CLI.
Follow-up resolution for #2444 and [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-12137).

Add quotes around globbing example for consistency

---

.circleci/config.yml
jekyll/_cci2/api-job-trigger.md
jekyll/_cci2/configuration-reference.md
jekyll/_cci2/databases.md
jekyll/_cci2/env-vars.md
jekyll/_cci2/faq.md
jekyll/_cci2/ios-codesigning.md
jekyll/_cci2/ios-migrating-from-1-2.md
jekyll/_cci2/language-android.md
jekyll/_cci2/language-clojure.md
jekyll/_cci2/language-elixir.md
jekyll/_cci2/language-go.md
jekyll/_cci2/language-python.md
jekyll/_cci2/language-ruby.md
jekyll/_cci2/language-scala.md
jekyll/_cci2/migrating-from-1-2.md
jekyll/_cci2/postgres-config.md
jekyll/_cci2/project-walkthrough.md
jekyll/_cci2/sample-config.md
jekyll/_cci2/testing-ios.md

This PR does two things:
- makes all examples of the `environment` key use a map (rather than a list)
- makes a note of the fact that we **accept** but **discourage** using the `environment` key as a list
- adds several missing yaml tags and removes whitespaces
Resolves #2445 and [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-12110).
@marcomorain for technical review of the Configuration Reference, especially.
@michelle-luna for copy review.

make `environment` key type consistent across docs

---

jekyll/_cci2/language-elixir.md

The JUNIT test result location has moved. It is now in _build/test/lib/app/test-junit-report.xml

Update junit location

---

jekyll/_cci2/monitoring.md

This is just a small follow-up to #2467 to clean up the language and make the list of logging appliances easier to read.
@michelle-luna for copyedits

turn list of example logging appliances into proper list

---

jekyll/_cci2/local-cli.md

This PR removes an outdated limitation on relative paths in `working_directory` from the Local CLI docs. I've confirmed this limitation is gone on a local build of `circleci-docs`.
Fixes #2466 and resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-12216).
@ndintenfass for technical review
@michelle-luna for awareness.

remove relative path limitation

---

jekyll/_cci2/gpu.md
jekyll/_cci2/non-aws.md

The diagram has been updated to reflect that it is a nomad client fleet.
Nomad Clients should not be referred to as builders because it confuses
1.0 and 2.0 terminology, and gets confusing when referring to things
like machine executors.

Remove reference to builder fleet wrt nomad

---

jekyll/_cci2/circleci-images.md
jekyll/_cci2/faq.md

After #2009 was re-opened, I spent some time thinking about why users were still having trouble understanding how our image tags worked. This PR is the result.
Highlights include:
- incorrect: the instructions for copying a SHA referenced old menu options
- inconsistent: document was missing "Overview" section
- unclear: a caveat about image tags being maintained by upstream sources (**not** CircleCI)
- unclear: "Best Practices" section has been split into more appropriate sections (in the previous version, Best Practices were introduced before the kinds of images and tags were discussed).
@felicianotech for technical review.
@michelle-luna for copy feedback.
Resolves #2009 and [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-12356).

Revise document for better structure and explanation of image tags

---

jekyll/_includes/edit-on-github.html

Makes footer language more specific around how we request issue reports.
We don't want folks to hit the bottom of the document, have a problem unrelated to docs, and feel like they can report it through the docs repository.

specify what kind of problem is reportable

---

jekyll/_cci2/custom-images.md

This PR adds context on how to enable the Docker `ENTRYPOINT` instruction in a custom Dockerfile. It also addresses a number of other issues with this document, including:
- undocumented: adding a `LABEL` to enable the `ENTRYPOINT` instruction.
- incorrect: most of the required tools can be installed with the `RUN` instruction, **not** the `ADD` instruction.
- unclear: you must create a `Dockerfile` **before** choosing a base image; section headers now represent steps in manually creating a Docker image.
- grammatical errors: some article omissions and assorted language fixes.
Resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-11953).
Original request from @ndintenfass 
Tech review from @ryanwohara 
Writing review from @michelle-luna

Document required dockerfile label

---

jekyll/_cci2/monitoring.md

Some reference to docs about telegraf are dead because these docs is moved by this PR(https://github.com/influxdata/telegraf/pull/4406/files).
Fix some links.
Some link for telegraf docs  is already dead.(by moving telegraf docs)

Fix dead link to telegraf documents

---

jekyll/_cci2/env-vars.md

Adds a note to remind people in the Built-in Environment Variables section that they CAN NEVER INTERPOLATE. Also links to the section discussing the workaround.
This PR (hopefully) fixes #2510. 
@felicianotech for tech review.
@michelle-luna for copy review.

add note about interpolation to built-in env vars section

---

jekyll/_cci2/artifacts.md

This PR clarifies how to download all artifacts for a build by cleaning up language and adding a table that maps substitute values for their actual values.
A user stumbled while attempting to download all artifacts for a build. (See GitHub issue).
Fixes #2472 and resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-12355).
@felicianotech for technical accuracy.
@michelle-luna for copyedits.

Clarify how to download all artifacts for a build

---

jekyll/_cci2/docker-compose.md

Document that docker-compose is pre-installed
You don't need to install it when using CircleCI convenience images but
you do if you're using your own images.
N/A

Document that docker-compose is pre-installed

---

jekyll/_cci2/parallelism-faster-jobs.md

Fixed minor typo in sample config on the parallelism /test splitting page
- docker should be property of a specific job
- include parallelism in 2nd example  for consitency
- The first sample config is invalid due to nesting level of the docker property (should belong to the job named `tests` as seen in the 2nd example
- Added `parallelism` attribute to the 2nd example for consistency.
Current example when validated with out CLI
```
circleci config validate
* Error migrating config to version 2: 2 errors occurred:
* Config file is invalid:
at jobs: jobs: Invalid type. Expected: object, given: array
at jobs: jobs: Must validate one and only one schema (oneOf)
at jobs: machine: machine is required
at jobs: steps: steps is required
* Error in config file: The schema/shape of the YAML is …
```

Parallelism config typos

---

jekyll/_cci2/postgres-config.md

The image circleci/ruby:2.4.1-node-jessie is not on the list: https://hub.docker.com/r/circleci/ruby/tags/
So I propose to change to 2.4.4-node

Changing image reference cause the current on do not exist

---

jekyll/_cci2/collect-test-data.md

`jest-junit` is deprecating its `testResultsProcessor` flag. This updates the jest-junit to use its updated syntax.
Fixes #2539.

Fix deprecated jest junit instructions

---

jekyll/_cci2/postgres-config.md

Fixes a command that would incorrectly start the postgresql server while building.
Fixes #2548

prevent false start of postgres server

---

jekyll/_cci2/browser-testing.md

The sample configuration for running Sauce Labs within a build container was incorrect. This PR updates the sample config with the correct instructions.
Fixes #2540.

Fix incorrect information in sauce labs config

---

jekyll/_cci2/building-docker-images.md
jekyll/_cci2/configuration-reference.md

This updates the references for currently available machine: and remote_docker:
executor images with 18.x docker versions

machine: Update image lists

---

jekyll/_cci2/language-android.md
jekyll/_cci2/language-ruby.md

Corrects links to official Ruby and PostgreSQL images and removes confusing language.
Fixes #2558

Clarify which ruby images are used

---

.circleci/config.yml

Updating the Docker image that the deploy uses with a newer version of the AWS CLI.
No new changes here, just regular maintenance.
n/a

Update the AWS CLI to v1.15.73.

---

jekyll/_cci2/executor-types.md

Adjustment of the heading levels which were incorrect, and the removal of a double space.
The heading levels made it appear that Using Machine and macOS required Docker to be used in some way. This was terribly confusing at first.
No issue was created.

Fixes heading levels to improve clarity on Machine and macOS requirements

---

jekyll/_cci2/env-vars.md

Fixes typos and adds missing text in the environment variables documentation.

Correct typos related to environment variables

---

jekyll/_cci2/certificates.md

The uncommon word, `arbritatry` can be `arbitrary` in this context.
I suspect that is just a typo.
[Using Self-Signed Certificates](https://circleci.com/docs/2.0/certificates/#using-self-signed-certificates)

Replace the uncommon word with a common one

---

jekyll/_api/v1-reference.md
jekyll/_data/api.yml

Adds notes about the lack of significance of ordering in our API responses. Except for 2 endpoints where it actually does matter. 🙄 
Fixes #2562 and [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-12897).

Document ordering info for api lists

---

jekyll/_cci2/build-processing.md

Auto-cancel is now functional for workflows when you turn on build processing

Remove auto-cancel caveat

---

jekyll/_cci2/docker-layer-caching.md

Looks like the code block on DLC page is unhappy
This adds the newline under ``` required for code highlighting, and marks it as YAML type 

fix yml code block typo in DLC page

---

jekyll/_cci2/skip-build.md

fix typo in skip-build.md

---

jekyll/_cci2/usage-statistics.md

Typo; container name wrong
Customers will get an error
n/a

Container name in docs incorrect

---

pull_request_template.md

Removes redundant section from pull request template.
More often than not, I find myself deleting the Context section during pull requests. Two sections for **what** and **why** should be sufficient.

Remove redundant 'Context' section

---

.gitignore

Jekyll cache was being tracked in Git. This adds the `jekyll/.jekyll-cache/` directory to `.gitignore` and organizes the `.gitignore` file.
Seeing the cache update is not a noteworthy or committable change.

add jekyll cache and alphabetize

---

jekyll/_cci2/api-job-trigger.md

Fixes a typo in the title of the page ["Using the APi to Trigger Jobs"](https://circleci.com/docs/2.0/api-job-trigger/#section=jobs)

Fix typo in "Using the API to Trigger Jobs"

---

jekyll/_cci2/google-auth.md

- removes unnecessary Kubernetes cluster-checking command
- highlights the more important `GOOGLE_APPLICATION_CREDENTIALS` env var
Fixes #2589 and resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-13058).

Clarify google service account doc

---

jekyll/_cci2/ssh-access-jobs.md

This highlights the need for adding an SSH key with "Checkout SSH Key" for either
Fixes #2594 and resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-13159).

Make checkout ssh key req more explicit

---

jekyll/_cci2/local-cli.md

Add installation instructions for Homebrew and manual installation. Clarify that the one-line curl installation is for mac and Linux.
Ensuring all major installation options are documented.

Update CLI install instructions

---

jekyll/_cci2/contexts.md

fix syntax error at cotext.md , Creating and Using Context section 4. (see image below)
to activate link to https://circleci.com/docs/2.0/configuration-reference/#workflows

fix markdown syntax error at context.md

---

jekyll/_cci2/packagecloud.md
jekyll/_cci2/test.md
jekyll/_data/sidenav.yml

This pull request aims move the packagecloud docs from 1.0 -> 2.0
I've included the new CircleCI 2.0 configuration along with some examples for publishing different package types. I've tried to keep everything in line with the CircleCI style guide and contributing guidelines.
Any feedback would be appreciated!

Add 2.0 docs for packagecloud (migrating from 1.0 docs)

---

jekyll/_cci2/parallelism-faster-jobs.md

Fixes link at bottom of https://circleci.com/docs/2.0/parallelism-faster-jobs/ since it's not properly formatted in markdown.

Docs: Fix markdown formatting

---

jekyll/_cci2/executor-types.md

Cleans up copy in the executor types document with minor edits and more examples.
Fixes #2604 and resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-13250).

Clarify machine executor section

---

jekyll/_cci2/language-go.md

Change the path related to go cache directory
The go cache directory is given with the command ```go env GOCACHE``` which is "/home/circleci/.cache/go-build" when we log in a container (see: https://golang.org/cmd/go/#hdr-Build_and_test_caching)
After changing this path, the caching feature is working as expected.

Change cache folder

---

jekyll/_cci2/status-badges.md

A small typo in this file where a link was not fully closed. 
I was reading the documentation and saw this.

Fix typo in status-badges.md

---

jekyll/__glossary/layer_caching.md
jekyll/_cci2/building-docker-images.md
jekyll/_cci2/language-scala.md
jekyll/_cci2/local-cli.md

Fix typo relates to Markdown syntax
- Excess parenthesis
- Insufficient links to glossary

Fix minor typo and missing links

---

jekyll/_cci2/build-processing.md

Fix incorrect link to new API v1.1 endpoint.
It was pointing to the wrong endpoint/anchor tag.
Thanks to @KyleTryon for catching this.

Correct link to new API endpoint.

---

jekyll/_cci2/language-scala.md

A guide to parallelize tests in SBT on CircleCI. Here are the steps:
1. Modify SBT to print all classes to a file
2. Feed the file to circleci command line tool
3. Run `sbt testOnly`
4. Store test results
It took me a while to parallelize tests in SBT on CircleCI. So, I wrote it up and would like to share it.

Add "How to parallelize tests in SBT on CircleCI"

---

jekyll/_cci2/migration.md

Use `circleci-agent` instead of `circleci` when calling in-build commands of the build agent.
With the new CLI we are moving to using circleci-agent in the build. This is the most official place we document `step halt`, so it should use the new agent name.

Change step halt to use circleci-agent, which is now preferred

---

jekyll/_cci2/docker-layer-caching.md

We want to avoid confusion in case a customer hits DLC usage limits. So adding a note that states that there _is_ a limit.

Note around DLC usage limits

---

README-local-development.md

Adds a small note (and proper headings) to the local dev readme.

Add Docker tags script to local dev instructions.

---

jekyll/assets/js/instantSearch.js
jekyll/assets/js/main.js
jekyll/assets/js/sidebar.js

see title. 
The addition of another library caused enough latency in the page load to cause the data binding for the sidenav js to not work. Adding an onload wrapper (which should have been there to begin with) fixes this issue.

adding onload wrapper to sidenav function so that it consistently works

---

jekyll/_cci2/collect-test-data.md

This is my personal, unsupported tool and it only works on 1.0

Removing junit-merge as it doesn't have use on 2.0

---

jekyll/_cci2/local-cli.md

Update the local CLI docs
I noticed a few issues with this doc. We still reference the old local cli install instructions and local build was mentioned in two places.
This change moved all the install options into one section and moves the `local execute`instructions all together.

Update local CLI docs

---

jekyll/_cci2/sample-config.md

At the "See Also" section, the "Example Public Repos" wasn't pointing to that page itself.
Added the correct redirect to an incomplete link element.
Better navigation flow.

Fix incomplete link in Sample Config.yml Files

---

jekyll/_cci2/ssh-access-jobs.md

We wait for 10 mins until users ssh or cancel the job as you can see in the screenshot.

Fix SSH wait timeout

---

jekyll/_cci2/oss.md

Fixed link to Examples under "See Also" header.
Link points to unrelated page

Updating Link to Example Configs

---

jekyll/_cci2/update-2.14.1-to-2.15.0.md

A document to explain how to upgrade to mongo 3.6 if the customer is running externalized.

A document to explain how to upgrade to mongo 3.6 

---

jekyll/_cci2/update-2.14.1-to-2.15.0.md
jekyll/_data/sidenav.yml

need to refer server customers to support for upgrade/HA info
using HA requires support contract and making changes without SE could create issues

adding link to sidenave for JVM heap, removing mongodb ha info

---

jekyll/_sass/_instantsearch.scss

Fixes search term highlighting of search results.
Looks like setting the `escapeHits: true` option on the hits widget changed the CSS selector for highlighted search terms in results.
Do a search - the search term should be highlighted in bold and not italicized.

Fix CSS selector for highlighted search terms

---

jekyll/_cci2/jvm-heap-size-configuration.md

as part of 2.15.0 release, OX team finish validating output-processor's jvm heap size configuration but it's missing in the documentation. adding instruction to correct them
https://circleci.atlassian.net/browse/CIRCLE-13249 is worked on but the document was not published to inform the customer.

add output-processor jvm_heap_size customizations

---

jekyll/_cci2/testing-ios.md

We overwrote the Xcode 10.0.0 image with an upgraded base operating
system and replaced the Xcode GM with the actual released version.
This updates the documentation reference to point to the correct image
specification.

Update Xcode 10.0.0 documentation

---

jekyll/_cci2/language-go.md

Update Go language guide to include a commented config. 
Also, add missing step in the config walk through (build environment variable).
Related PR: [circleci-demo-go](https://github.com/CircleCI-Public/circleci-demo-go/pull/9)
[Github Card](https://github.com/circleci/circleci-docs/projects/6#card-9453327)

Update Go language guide with commented config

---

.circleci/config.yml

Remove updating Trusty versions json
We don't need to update the file since we sunset 1.0

Remove updating Trusty versions json

---

jekyll/_cci2/demo-apps.md
jekyll/_cci2/language-crystal.md
jekyll/_cci2/tutorials.md

Update Crystal language guide to go to [transferred repo](https://github.com/CircleCI-Public/circleci-demo-crystal/).
Relevant project [card](https://github.com/circleci/circleci-docs/projects/6#card-14181500).

Update Crystal doc links to transferred repo.

---

jekyll/_cci2/add-ssh-key.md
jekyll/_cci2/gh-bb-integration.md

fixes #2807 
Note: The gh-bb-integration page was linking to the production url of the docs site so I swapped in the `site.baseurl` var.

Link to gh-bb integration page from ssh keys page.

---

jekyll/_cci2/writing-yaml.md

just fixing a typo in the docs about writing yaml
was just reading through and thought I'd leave it better than how I found it

fix typo in writing yaml documentation

---

jekyll/_cci2/custom-images.md

just fixing a typo in the custom images documentation
was just reading through and wanted to leave it better than I found it

fix typo in custom images documentation

---

jekyll/_cci2/caching.md

fixes #2822 
I managed to break one of my own builds by using the `/` char in the key. It was a bit of a strange one to try and recreate, however. Usage of the `:` did not break my build, and at times the use of `//` still worked.

Add tip regarding reserved chars in cache-key

---

.circleci/config.yml

Ticket: https://circleci.atlassian.net/browse/CIRCLE-14271
The prior implementation of automating algolia with the build process caused it to replace our existing index with a blank one. Upon SSHing into the build, we discovered this was due to not targeting the right subdirectory for indexing. 
To solve the problem, we specified the site source with `--source jekyll` so that it will index properly.

[CIRCLE-14271] update-algolia

---

jekyll/_cci2/google-auth.md

User reported case that default permissions of the service account for GCR were not sufficient for pushing containers. Addd links to IAM console and permission docs.
Fixes #2589

Link to IAM docs for describing GCR permissions.

---

jekyll/_cci2/workflows.md

The Open Group removed the POSIX man pages from their site.

Link to crontab manpage is broken

---

jekyll/_cci2/using-orbs.md

There are two typos in the Using Orbs example stanzas.  This PR addresses both
Item 1: A "v" was between the Orb name and version in "hello: circleci/hello-build@0.0.5"
Item 2: The "sayhello" command was missing the local namespace "hello/sayhello"

Fixed two typos in the Using-Orbs Example stanzas

---

package-lock.json
package.json
src-js/instantsearch.js

JIRA ticket: [CIRCLE-14872](https://circleci.atlassian.net/browse/CIRCLE-14872)
Looks like there are some items in our index that have no content. Our code for formatting the results is expecting some content to be there, and is throwing exceptions when it isn't, causing issues like the one described in this ticket.
Spin up the app (don't forget to run webpack :wink:). Search for "Language Guides". There should be no console errors, and you should see an entry with just the title called "Language Guides". Search for "Go cace" - your first result should be the go language guide.

[CIRCLE-14872] Don’t assume search results have content or title

---

.circleci/config.yml
jekyll/_config.yml

JIRA ticket: [CIRCLE-14895](https://circleci.atlassian.net/browse/CIRCLE-14895)
Only run the Algolia search re-indexing with changes to the master branch.
Re-indexing on PR branches is not only unnecessary, but potentially problematic - e.g. if two re-indexing operations were happening at the same time.
- I created an empty test index on Algolia, "documentation-dev"
- I made the necessary changes to the CI workflows, set the Algolia index to the the test index, and left the re-indexing running on every branch so that I could test the new re-indexing job with the PR branch.
- As you can see [https://circleci.com/gh/circleci/circleci-docs/24525](here), the re-indexing worked. You can also see in Algolia that the test index matches the production index. This establishes that the work of …

[CIRCLE-14895] Only reindex search on master

---

jekyll/_cci2/jvm-heap-size-configuration.md

This is quick fix updating the JVM heap size documentation to refer to the correct container
When running the command given it actually errors out due to the container actually being called `test-results` – figured I'd clean it up for the next person

Fix typo in JVM heap size docs regarding test-results container

---

Gemfile
Gemfile.lock

Use a later version of `rack`.
`jekyll-assets` depends on `sprockets`, which depends on `rack`, which has two security vulnerabilities prior to 2.0.6.
We don't really use Rack, at least not in production, but this will satisfy GitHub's security checker.

Address "security vulnerabilities"

---

jekyll/_cci2/hello-world.md

fix and update orb version number `.0.0.5` -> `0.0.7`
No dot(.) is required for the first part of version num.

fix and update version number of hello-build orb

---

jekyll/_cci2/creating-orbs.md

Added a note to Overview section stating that private installations of CircleCI server are not currently supported for creating/using orbs. Fixes #2961 

Updated creating-orbs.md content

---

.circleci/config.yml
jekyll/_cci2/authentication.md
jekyll/_cci2_ja/index.md
jekyll/_config.yml
jekyll/_data/sidenav.yml
jekyll/_includes/mobile-sidebar.html
jekyll/_includes/sidebar.html
jekyll/_includes/translation_in_progress.html
jekyll/_layouts/cci2.html
jekyll/_layouts/classic-docs.html
jekyll/index.html
jekyll/ja/index.html
scripts/shim-translation.sh

Adding Japanese translation
This change is the base for localizing docs into Japanese.
Here are a few design considerations:
- All translated pages live under https://circleci.com/docs/ja
- Duplication must be avoided as much as possible
- English and Japanese versions can be maintained separately
A few notes about implementation
- We create a new collection `cci2_ja` that lives under `/ja/2.0`
- We add `lang:` metadata to specify language with default set in config.yml so that we don't need to add the metadata manually for all pages.
- We run `shim-translation.sh` only in CI. This allows us to keep untranslated pages for Japanese while avoiding having two same pages.

Start localizing into Japanese

---

jekyll/_cci2/google-auth.md

We don't have to decode $GCLOUD_SERVICE_KEY because it already raw JSON.
Before #2195 $GCLOUD_SERVICE_KEY was encoded in base64. Now it's not.
Current command with `base64 --decode` fails with error `invalid input`.

Fix command in google-auth.md

---

jekyll/_data/api.yml

While we officially support this endpoint, we've never documented.
Some customers found this endpoint anyway by themselves and already
using it, so it's nice to document it as our official API.

Document DELETE ssh-key

---

jekyll/_cci2/creating-orbs.md

[relevant discussion](https://discuss.circleci.com/t/unable-to-find-orb-with-inline-orb/27145)

Fix: inline orb example missing `orb` stanza.

---

jekyll/_cci2/status-badges.md
jekyll/_cci2_ja/status-badges.md

Translated status-badges.md to japanese
Wanted to start adding status badges to my repositories, and I thought might as well translate the instructions!

jp: translate status-badges.md

---

jekyll/_cci2/docker-compose.md

The section describing the usage of machine executor was not clear enough, I added a link to the documentation to help others better understand how to enable this feature.

Added link to machine executor docs

---

jekyll/_cci2/configuration-reference.md

Move branch filter to workflow since it's invalid to filter at job level (per [Configuring CircleCI - branches](https://circleci.com/docs/2.0/configuration-reference/#branches)):
> If you are using Workflows, job-level branches will be ignored and must be configured in the Workflows section of your config.yml file
Previously validation of example config failed with:
```
$ circleci config validate
Error: Job "build" has filters configured in the job definition. These filters are incompatible with workflows.
```

Fix invalid branch filter in full config example

---

jekyll/_cci2/docker-compose.md

Customer thought they had to install it since docs only said it was on our images.
Specify docker compose is on machine too.
Customer was avoiding machine because they thought they would have to waste time installing compose every run.

Clarify docker compose exists on machine

---

Gemfile
Gemfile.lock

GitHub is warning us about a vulnerability in the nokogiri gem version 1.8.4; this upgrades it to 1.8.5 to address the issue.
Verify that you can still build the site with jekyll.

Update nokogiri to address security vulnerability

---

jekyll/_cci2/migration-intro.md

Added links to the top section for Travis CI and Jenkins migration pages.
Added links to children pages for Jenkins and Travis CI.
We are linking from the home page to our migration material. Want to ensure we surface our most popular migration pages.

Suggested changes on the Migration introduction

---

jekyll/_cci2/orb-intro.md

Wave 3 partners are now available: Happo and DeployHub.
Adding these two partners to the orb page in documentation.
https://circleci.atlassian.net/browse/MKTG-1037

Added Happo and DeployHub as partner orbs

---

jekyll/_cci2/proxy.md

The current docs include numbers like 1.), 2.) etc that would cause shell to get angry.
This now comments them and adds information about the step.
Fixes invalid shell commands as described above, and see in current docs:
Allow uses to easily copy and paste the services and nomad proxy config without having to remove invalid characters.

Comments step labels in sample shell commands

---

jekyll/_cci2/building-docker-images.md

The default version of docker used in `setup_remote_docker` changed some time ago, this updates the documentation to reflect that
The current docs are inaccurate.

Update setup_remote_docker image version references

---

jekyll/_cci2/reusing-config.md

Typo: Change reference to `save_to_workspace` to `persist_to_workspace`
`save_to_workspace` is not a valid command according to [this](https://circleci.com/docs/2.0/configuration-reference/)- I think it should be `persist_to_workspace`

Should be "persist_to_workspace"

---

jekyll/_cci2/creating-orbs.md

I updated the "Personal API Token tab" link from https://circleci.com/accounts/api to https://circleci.com/account/api
The former links to a blank page, and the latter seems to be the correct link.

Fix "Personal API Token tab" link in Creating Orbs document

---

jekyll/_cci2/single-box.md

We suspect that the us-west-1 SPT AMI was recently deleted by mistake.  We transferred the us-east-1 AMI to us-west-2.  List has been updated to reflect changes.
https://circleci.atlassian.net/browse/CIRCLE-16234

[CIRCLE-16234] Update us-west-1 AMI ID

---

jekyll/_cci2/nomad-metrics.md

I mistakenly left a comment in not running nomad-metrics in daemon mode.  This is something that we do in our own fleet but the customer doesn't need to do.
https://circleci.zendesk.com/agent/tickets/45273

Remove comment about Daemon

---

jekyll/_cci2/google-auth.md

Having `sudo` in command was failing the build.
With `sudo`, the build fails with the message "command not found".

Removed `sudo` from command

---

jekyll/_cci2/configuration-reference.md

Our docs were wrong here: the YAML we provide as an example makes the default
the literal string `\"\"`, *not* an empty string. See https://discuss.circleci.com/t/problem-with-when-condition-and-empty-string/28375

Don't escape YAML strings unnecessarily

---

jekyll/_cci2/testing-orbs.md

It's just a broken link here: https://circleci.com/docs/2.0/testing-orbs/#testing-orbs-locally
`[](()` -> `[]()`, and it was also missing the `/2.0/` part.

Fix broken markdown on a link

---

jekyll/_cci2/configuration-reference.md

Show the absolute paths of the directories which are persisted, rather than the relative paths from `/tmp/dir`.
It's a trivial change that better demonstrates how to use the feature.

Clarify the behaviour of the relative paths.

---

jekyll/_cci2/language-clojure.md

Removed a `~/.lein` cache that was shown in the Clojure config walkthrough, but [removed from the sample config mid-June 2017](https://github.com/circleci/circleci-docs/commit/ed3bd149d182b72355e5901a60dc131b56281135#diff-3d61f9f0003cbef5fb7993bb9fdca4c8).
Noticed the inconsistency, and assumed the sample config was the source of truth. Happy to sync the other way if desired :)

Synchronize Clojure sample config and walkthrough

---

jekyll/_cci2/configuration-reference.md

Fixed links that had a space between their text and target.
Real clickable links are nice :)

Fixed broken links in configuration reference

---

jekyll/_cci2/testing-ios.md

We've just enabled Xcode 10.2 Beta 3 as an available macOS image.

Include Xcode 10.2 Beta 3 in the macOS versions list

---

jekyll/_api/index.html

Added some information about the endpoint to delete SSH key.
* The endpoint is not listed in the summary of endpoints
* The example command lacks URL

Tweak A Document About The API Endpoint To Delete SSH Key

---

jekyll/_cci2/building-docker-images.md

Fix broken link
Instead of a link, `[primary container][primary-container]` is displayed on https://circleci.com/docs/2.0/building-docker-images/

Fix broken link

---

jekyll/_cci2/databases.md

This changes two occurrences of _priviledges_ to _privileges_ :)

Fix typos in privileges in databases.md

---

jekyll/_cci2/collect-test-data.md

The test metadata setup for Maven/Gradle is non-optimal, producing the "n tests in unknown" [error](https://support.circleci.com/hc/en-us/articles/115015920668-Why-does-test-summary-show-tests-in-unknown).
As per [these docs](https://circleci.com/docs/2.0/configuration-reference/#store_test_results), the test metadata must be written to a subdirectory of the directory that is uploaded. It looks like the config is wrong for other build systems, but I've only fixed the Java ones.

Fix Maven/Gradle test metadata setup

---

.circleci/config.yml
Gemfile
Gemfile.lock
docker-compose.yml

A regular maintenance PR.
This updates the version of Ruby used to v2.6.1. This also updated Jekyll to v3.8.5.

Update version of Ruby and Jekyll used.

---

jekyll/_cci2/overview.md

Case study goes to a 404 link. 
I was asked to remove that case study some time ago by the Revenue team.

Remove Fanatics case study

---

jekyll/_cci2/ios-codesigning.md

We tell customers to set the `FL_OUTPUT_DIR:` env in their config. This explains why and what it does.
We tell customers to set the `FL_OUTPUT_DIR:` env in their config. This explains why and what it does.

Explain what `FL_OUTPUT_DIR:` does.

---

.circleci/config.yml

This PR sets up a scheduled workflow on CircleCI. It will cause this repo to build every night at 8am UTC.
This allows for dynamic content in Docs such as the Docker Tags JSON file to be rebuild and kept fresh even if Docs doesn't get a normal push/merge to master that day.
The time is 8am UTC because that is very early morning for both Eastern and Pacific Timezones as well as many hours after the nightly build for CircleCI Images (allowing that repo time to build).
Inspired to do this via this GitHub comment: https://github.com/circleci/circleci-images/issues/343#issuecomment-473717797

Tell CircleCI to do a nightly build.

---

.circleci/config.yml

This resolves reindex-search issues introduced in #3241

Bump ruby version in the other CI job to match

---

jekyll/_cci2/migrating-from-travis.md

I moved the "On Using Containers" section to be higher up, so it's one of the first things customers moving over from Travis and checking our docs see- since all Travis builds are based on specifying a language and CircleCI builds are done in docker containers, and that's information customers need before they can really take any other steps forward, I think having it earlier up in the table of contents makes sense. I've also included a table translating terms from Travis's yml configuration into the equivalent CircleCI terms with links to the relevant sections for quick reference.
I'm making these changes to help make it easier for Travis users to migrate to CircleCI.

Updating Travis Migration Docs

---

jekyll/_cci2/concepts.md

There was a small typo in the example script. 
It might lead to confusion on proper formatting.

Add missing colon to example

---

jekyll/_cci2/api-job-trigger.md

There is a mismatch in examples to call api triggers.
https://circleci.com/docs/2.0/api-job-trigger/#overview
```
curl -u ${CIRCLE_API_USER_TOKEN} \
-d build_parameters[CIRCLE_JOB]=deploy_docker \
https://circleci.com/api/v1.1/project/<vcs-type>/<org>/<repo>/tree/<branch>
```
In this case, Curl will ask for the user password https://ec.haxx.se/http-auth.html
Another doc page represents the right syntax: `curl -u ${CIRCLE_API_USER_TOKEN}: \`
https://circleci.com/docs/2.0/triggers/
CIRCLE_API_USER_TOKEN variable should end in a colon which means a blank password.
Current the description causes not working code.
```
Enter host password for user '--data':
curl: (3) [globbing] bad range in column 18
{
"message" : "Project not found"
}
```

Fix curl call syntax for api triggers

---

jekyll/_cci2/collect-test-data.md

The backticks for `store_test_results` enveloped the entire link, so it rendered as plain monospace text.
To correct improper formatting.

Correct markdown formatting to allow proper link

---

jekyll/_cci2/parallelism-faster-jobs.md

add instructions to glob golang packages in parallel containers
no golang instructions included

add instructions to glob golang packages

---

jekyll/_cci2/testing-ios.md

Closes: https://github.com/circleci/circleci-docs/issues/3303
Bumped the version over at https://github.com/CircleCI-Public/circleci-demo-ios/pull/15 which went [green](https://circleci.com/gh/CircleCI-Public/circleci-demo-ios/26?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

Bump Xcode versions

---

jekyll/_cci2/configuration-reference.md

A sentence in the docs was missing a field name.
I was thrown off by this briefly when skimming the [docs](https://circleci.com/docs/2.0/configuration-reference/#jobs-1).

Adds `type` to list of `job` fields.

---

jekyll/_cci2/language-haskell.md

Adding a workaround of "OUT OF MEMORY" for Haskell.
I believe this is a common issue and worthwhile noting here.

Adding a workaround of "OUT OF MEMORY" for Haskell

---

jekyll/_cci2/env-vars.md

This avoids line wraps in base64-encoded environment variables.
Line wraps in base64-encoded variables seem to cause problems when decoding in build steps.

Prevent line wraps when using base64 encoding

---

jekyll/_cci2/caching.md

Add warning about caching between executors and OS
This can cause frustration, confusion, and wasted time as customers deal with this.

Add warning about caching between executors and OS

---

jekyll/_cci2/collect-test-data.md

Added [trx2junit](https://github.com/gfoidl/trx2junit) for Visual Studio / .NET Core Tests conversion to JUnit XML.
`dotnet test` doesn't have a logger for JUnit XML, so some kind of post-processing must be applied to show test summary in CircleCI. This PR adds such a tool to the documentation.
Disclaimer: I'm the author of that tool.

Added trx2junit for Visual Studio / .NET Core Tests

---

jekyll/_cci2/orb-intro.md

Added new partners to the docs page. 
https://circleci.atlassian.net/browse/MKTG-1112
These new partners are part of the Wave 5 release for April.
This change can go live as soon as it's ready.

Added new partners for Wave 5-CryptoMove, Probely

---

jekyll/_cci2/testing-ios.md

Adds details of the xcode 10.2.1 image to the docs
This is to support the xcode 10.2.1 release
This shouldn't be merged until the image is fully available on the macos fleet.

Add xcode 10.2.1 details to the docs [CIRCLE-17534] 

---

jekyll/_cci2/jobs-steps.md

in `Orbs, Jobs, Steps, and Workflows` pages, there is a wrong indented `yaml` file example.
Indentation in `yaml` files is very important because it means structure.

fix: wrong yaml indentation in orbs example

---

jekyll/_cci2/deployment-integrations.md

Change link title to reflect its content.
This link points to documentation for the CodeDeploy orb, but is titled "AWS ECS".

Fix incorrect title for link

---

jekyll/_cci2/caching.md

There is no fixed upper limit, but any cache over 500Mb will not be checked for corruption.
A server customer ended up with failing builds due to a 6Gb (ish) cache, so this PR is just to add a short paragraph to explicitly state the situation.

add warning about cache sizes

---

jekyll/_cci2/writing-yaml.md

Update the multi-line string example showing a haiku to have the correct number of syllables per line
A haiku follows the format of 5-7-5: [wikipedia](https://en.wikipedia.org/wiki/Haiku) 🤓

Fixing haiku example in writing-yaml.md

---

jekyll/_cci2/language-haskell.md

Change the cache keys to save and restore to increase the chance of the cache being reused.
When you use `stack`,  `package.yaml` is updated every time you add, remove , or change the version of your application. Because of this, using `package.yaml` as the cache restore key will decrease the change of using cache. For example, if you add a new dependent package in `package.yaml`,   CircleCI will start building all the libraries from the scratch since it can't find the previous cache.
On the other hand, `stack.yaml` won't change much unless you change the version of LTS to use, so that we can add a secondary cache restore key using `stack.yaml`, to reuse the previous caches even when `package.yaml` is changed.

Better cache restoring for haskell

---

jekyll/_cci2_ja/config-intro.md

fix closing quotes from smart to straight
There are smart quotes instead of straight quotes.
Thank you for useful translation!
I found smart quotes and I couldn't run those codes.
I would be glad if you would confirm this!
Thanks!

fix closing quotes from smart to straight

---

jekyll/_cci2/configuration-reference.md

As part of the `deploy` step documentation, mention that SSH-enabled jobs will explicitly skip these steps.
We could not find this behaviour documented anywhere. Example job exhibiting this behaviour: https://circleci.com/gh/ministryofjustice/laa-legal-adviser-api/908

Document that SSH jobs will not run deploy steps

---

jekyll/_cci2/deployment-integrations.md

Fixes a minor typo. This orb definition pushes an image to ECR, not ECS.

Fix minor typo on deployment integrations page

---

jekyll/_cci2/creating-orbs.md

The step `my_inline_command` should receive `greeting_name` parameter in order to work properly:
```
steps:
- my_inline_command:
greeting_name: <<parameters.greeting_name>>
```
There's a typo inside `my_inline_job` on step `my_inline_command` parameter which causes `circleci config process` to return:
```
Error: Error calling workflow: 'build-test-deploy'
Error calling job: 'inline_example/my_inline_job'
Error calling command: 'my_inline_command'
Missing required argument(s): greeting_name
```

Fix typo in Creating Orbs: Example Inline Template

---

jekyll/_cci2/ecs-ecr.md

A quote was added at the end of the string. It is missing its start companion
It's not syntactically correct without the beginning quote.

ECS/ECR Deployment documentation: Add missing quote

---

jekyll/_cci2/config-intro.md

Add a space indentation to the `yml` blocks to begin with a proper 2 spaces indent where. All `yml` blocks on this page are missing a space at the top of each block.
> The trickiest part is typically indentation.
The docs mention that indentation is one of the main things that are difficult in `yml` files. Let's start them off without any inconsistencies. This is bound to be copy-pasted and will result in confusion when blocks don't line up after select-tabbing them to indent sections.

Consistent indentation - missing space for build: lines

---

jekyll/_cci2/using-orbs.md

The link to the cookbook should work now. :)

Fix broken markdown on orbs page

---

jekyll/_cci2/add-ssh-key.md

Currently users can add multiple SSH keys with blank hostnames. In the edge case where multiple of these keys can access the same hosts, but function for different purposes this will lead to the first key added to always be used unless explicitly changing the SSH config or removing keys from a containers ssh-agent
See CIRCLE-18579 for more info.
Multiple SSH keys without hostnames will set IdentitiesOnly no, and use ssh-agent instead. This isn't clearly documented and can cause confusion if a user isn't familiar with ssh-agent, or expects the `IdentitiesOnly yes` setting to be the default when injecting a key into a build.

Multiple SSH keys with no hostnames considerations

---

jekyll/_cci2/v.2.17-overview.md

The AMI's we specify use docker version 18.09.3, not 18.06.3.

Fix docker version

---

jekyll/_cci2/language-ruby.md

The old instructions used `bundle install` without the `--deployment` flag, but this installed into `/usr/local/bundle` and then the `save_cache` step doesn't do anything.  This commit adds the `--deployment` flag and also uses `--path` for `bundle check`.
Without this change the cache doesn't install into `./vendor/bundle` so the save_cache step stores an empty directory (because the libraries are installed elsewhere).  So the restore_cache step looks like it works, but since it is restoring an empty directory the libraries always need to be installed.
Given that other people have not proposed this change, maybe there was a better way to achieve what I did.  But for me the default instructions did not work "out of the box", so I wanted to provide this feedback so that others don't use …

Fixed bundle install to use --deployment

---

jekyll/_cci2/reusing-config.md

Added `run` keyword to some examples
examples cannot be processed

Fix examples in reusing-config.md

---

jekyll/_cci2/reusing-config.md

Fix Typo in reusing-config.md

---

jekyll/_cci2/skip-build.md

Re-running a skipped build will not run the workflow. The re-run will run the job again under the same circumstances, so `ci skip` will be applied again.
The information was not valid.

Remove invalid information on 'ci skip'

---

jekyll/_cci2/gh-bb-integration.md

Change section heading
The section is not about "Creating a Machine User". Rather, it's about "using a machine user to control Circle's access to GitHub repos". But that's too long.

Section heading with correct semantics

---

jekyll/_cci2/configuration-reference.md

Fixes #3462 
Performance Plans have resource_class and DLC automatically enabled. Container and unpaid plans must contact Support in order to change their plan for these features to be used.
Removed call to action for customers with Performance Plans as resource_class is automatically enabled.
Resource Class and DLC are automatic features for Performance Plan customers. Container Plan customers and unpaid customers need to contact Support to enable these features.

Change resource_class enable requirements

---

.circleci/config.yml
Gemfile
Gemfile.lock
docker-compose.yml

I was having trouble getting the Docker Compose local dev setup to work. This PR fixes it for me.
The Jekyll image contains Ruby v2.6.3 so this makes the Gemfile match it.
Then Ruby for each job.
Then it copies the whole repo into the image instead of just the jekyll directory.
Updates the AWS image.

Update Docker Compose setup.

---

jekyll/_cci2/certificates.md

This commit adds in an additional, CLI only, variant of installing the
CircleCI Server SSL certificate.
This was something that I came across while deploying CircleCI Server which made renewing certificates a much easier process to automate with Lets Encrypt and may be useful for other users to be made aware of.

Add additional certificate installation process

---

jekyll/_cci2/deployment-integrations.md

Use Python 3 to install awscli.
Read this article: https://dev.to/methane/use-pip3-to-install-awscli-44pk
Please recommend people to use Python 3 as possible.

Use Python 3 to install awscli

---

jekyll/_cci2/skip-build.md

Update text to say "Enable Pipelines" rather than "Enabling Pipelines (preview)"
I'm guessing that when this documentation was written, Pipelines were not yet a completed features, and the heading under Settings was called "Enabling Pipelines (preview)".

Change name of "Enable Pipelines"

---

jekyll/_cci2/postgres-config.md

Change mysql version in example config from 8.3 to 8.0.4
The mysql version is not available from this list: https://circleci.com/docs/2.0/circleci-images/#mysql
The current example config results in this error:
```
Starting container circleci/mysql:8.3
image cache not found on this host, downloading circleci/mysql:8.3
Error:
Error response from daemon: manifest for circleci/mysql:8.3 not found
```

Fix invalid mysql version in config example

---

jekyll/_cci2/artifacts.md
jekyll/_cci2_ja/artifacts.md

Suggest a method for downloading artifacts which doesn't use an insecure temporary file, and is more precise than the grep-based solution. Unfortunately, it does require `jq`.
https://github.com/circleci/circleci-docs/issues/3471

Don't suggest insecure temporary file for artifact download (#3471)

---

jekyll/_cci2/browser-testing.md

Updates to download URL for LambdaTest binaries in the samples, per partner's request.
Partner has changed the download location for their binaries.

update for new lambdatest download url

---

jekyll/_cci2/artifacts.md

Adds a note to docs that compressing artifacts and uploading them as a single file will significantly speed up artifact uploading step if there are hundreds of artifacts.
This note isn't currently surfaced in _docs_ and is only visible in 'known issues' section of support site.
This PR helps folks understand this sooner and prevents them from experiencing slow artifact uploads.
If there are hundreds of small artifacts then uploading them separately [seems to be significantly slower](https://support.circleci.com/hc/en-us/articles/360024275534?input_string=store_artifacts+step) than uploading a single, compressed file with all these artifacts.

Add note to compress if uploading many artifacts

---

jekyll/_cci2/jira-plugin.md

* Use the latest stable orb v1.0.5 which auto-fixes missing `jq` - https://github.com/CircleCI-Public/jira-connect-orb/pull/11
* Walk through setting up a suitable CircleCI API token
I found these changes were needed to get the integration working with a non-CircleCI image (`docker: - image: python:3`). I assume they will work more widely than the current suggestion.

Update Jira instructions to work more widely

---

jekyll/_cci2/circleci-images.md

Android docker images seem to also include the tools that other convenience images have, as noted in #3497 . @iynere do you mind confirming this?

Update: Android also installs additional tools.

---

jekyll/_cci2/caching.md

Change Mb -> MB
I really hope the recommendation is 500MB max cache and not 500Mb (~62MB) max cache.

typo - megabits to megabytes

---

jekyll/_cci2/configuration-reference.md

Modified this description regarding contexts.
We don't support using multiple contexts per job yet, so this phrasing seems misleading. Both I and a customer I was with on a call today misunderstood this. Idea for multiple contexts here: https://ideas.circleci.com/ideas/CCI-I-761

Removed ambiguous phrasing for contexts, Config Ref

---

jekyll/_cci2/collect-test-data.md

Remove duplicated "to" in sentence.
Enhance readability.

Remove duplicated word

---

jekyll/_cci2/language-haskell.md

Fixes output like this:
See the added comment, and the upstream source https://github.com/commercialhaskell/stack/issues/843 on this problem.
CircleCI cannot interactively delete characters from the output like a terminal can,
so stack needs to be told that CircleCI is not a terminal.

haskell: Fix examples producing garbage characters in logs

---

jekyll/_cci2/postgres-config.md

Refer: #3536
Description
mysql-client is not available no longer. So change the package from mysql-client to default-mysql-client .
Reasons
#3536

mysql-client is not available no longer

---

jekyll/_cci2/configuration-reference.md

Add the `tags` filter to the jobs example.
Closes #3529 
The `tags` are described above the example, but not actually showcased, which is confusing. This PR should fix it!

[configuration-reference] Enhance the jobs example

---

jekyll/_cci2/browser-testing.md

Ports were backwards in the port-forwarding section of the browser-testing doc.
`ssh -p $PORT -L 3000:localhost:8080` connects the local computer's port 3000 to the container's port 8080. In the original documentation states "The following example forwards requests to `http://localhost:8080` to port `3000` on the CircleCI container.", which is backwards and incorrect.

Documentation had ports backwards

---

jekyll/_cci2/yarn.md

Another user feedback fix from our doc polls.
A user wanted more clarity on how to custom install Yarn in the case of using an executor that does not have yarn preinstalled.

Add example custom yarn installation.

---

jekyll/_cci2/configuration-reference.md

User-feedback poll fix. 
A user stated that they found the `store_test_results` section of the config reference unclear when storing test results as an artifact.  I tried to clarify the language as much as possible.

Clarify "store-test-results" on configuration reference

---

jekyll/_cci2/executor-types.md

update examples to 16.04 and add intro from customer survey feedback
we want to push 16.04 in the docs for machine and customer feedback was that the doc needed to start with a description of an executor type.

update executor types example to 16.04 and add intro

---

jekyll/_cci2/security.md

add secomp profile link for docker and our appended json, plus clarify replicated section is only for server
request from glen

update security to mention docker secomp profile info

---

jekyll/_cci2/custom-images.md
jekyll/_cci2_ja/custom-images.md

It is unsafe to import GPG keys by short/long ID. This should be done by fingerprint.

import gpg keys by fingerprint

---

jekyll/_cci2/language-java-maven.md
jekyll/_cci2/language-java.md

Update java language guide in conjunction with changes to sample project
Update java language guide in conjunction with changes to sample project to use Gradle: https://github.com/CircleCI-Public/circleci-demo-java-spring/pull/9. The original Maven-based language guide will still be available via the https://circleci.com/docs/2.0/language-java-maven/ link and will link to the `maven` branch of the sample project at https://github.com/CircleCI-Public/circleci-demo-java-spring/tree/maven
The Java sample project has just gone through a major update to use Gradle.

Update Java language guide

---

jekyll/_cci2/testing-ios.md

Leaving both images in the doc as customers migrating to other versions might want to compare dependencies between the images. Will remove once we are past the EOL period.

Remove the deprecated Xcode 9.1 and 10.2.0 images

---

jekyll/_cci2/hello-world-windows.md

And add a note about Docker and Windows/Linux containers.

Remove the reference to installing .NET as it’s already installed in the base image

---

jekyll/_cci2/reusing-config.md

Fixes #3605 
Move naming restrictions to a more prominent place within the docs.
https://github.com/circleci/circleci-docs/issues/3605

Moving naming restrictions further up reusable config doc.

---

jekyll/_cci2/env-vars.md
jekyll/_cci2_ja/env-vars.md

Customer noted our example for filling env variables within bash was incorrect, this addresses that.
https://circleci.zendesk.com/agent/tickets/55507

Resolve incorrect variable interpolation in env vars documentation.

---

jekyll/_cci2/code-coverage.md

I added a screenshot of the build artifacts tab, and a clear statement that code coverage reports will be accessible as build artifacts, with a link to how to access them.
Two customer comments that the guidance was not clear on how to access code coverage reports.

Clear direction to build artifacts section

---

jekyll/_cci2/containers.md

Add a link to a Docker guide to the basics of containers for people who come to our Containers guide and need some context.

add link to Docker container overview

---

jekyll/_cci2/executor-types.md

Changes: 
- Updates the number of job environments to match the list
The docs currently state 3 environment types, immediately followed by a list of 4 environments. This updates the number to be consistent. 
Consistency / accuracy of the docs.

One-line fix for number of job environments within executor-types.md

---

jekyll/_cci2/language-clojure.md
jekyll/_cci2_ja/language-clojure.md

Update the Clojure examples to use a recent Leiningen image.
Clpjurians Slack conversation: https://clojurians.slack.com/archives/CJR0NB4MS/p1564997463001300

Use lein 2.9.1 in examples

---

jekyll/_data/sidenav.yml

Since the change made recently to add the getting started info fro each section into its own section in the sidenav, I realised the capitalised section headings are still clickable, and they all take you back to the welcome page. This PR changes this so each capitalised heading links to the getting started page for that section.

replace getting started links to top of each section in sidenav

---

jekyll/_cci2/optimizations.md
jekyll/_cci2/yarn.md
jekyll/_data/sidenav.yml

As pointed out by @rosieyohannan, the Yarn document might not be the best fit under "Configuring Deploys"; this PR removes it from the sidebar (open for discussion!) and also links to the Yarn doc from the optimizations section.

Remove yarn from sidenav; reference in optimization see-also section.

---

jekyll/_cci2/local-cli.md

Add link to FYAML under the config pack docs
We have a repo that describes the FYAML scheme at https://github.com/CircleCI-Public/fyaml, so linking to it from here makes sense to let users better understand the abstraction at work in config packing.

Add link to FYAML under the config pack docs

---

jekyll/_cci2/browser-testing.md

While Github renders the "Testing Locally Hosted..." header, it looks like the whitespace before the `#` header character breaks it [in the generated docs—see the header below this linked section](https://circleci.com/docs/2.0/browser-testing/#lambdatest). 
For Markdown cleanliness/consistency I also added some empty lines around this header and two others, but they're not necessary.
- Proper rendering so users don't get lost in the page
- Stylistic consistency

Fix Browser Testing section header to render properly in generated docs

---

jekyll/_cci2/config-intro.md

There were two changes to this code at around the same time that led to a formatting error - upping config version and including line numbers in the code blocks. This PR fixes the error.

fix code block formatting

---

jekyll/_cci2/faq.md
jekyll/_cci2/workflows.md

This has always been in the FAQ, but should be called out directly in the
scheduled workflows documentation.

[CIRCLE-19876] Document scheduled workflow delays

---

jekyll/_cci2/getting-started.md

Fix indent in step 1 of Using the Workflows Functionality
Right now the order number of steps is wrong like below:

docs(get-start): fix indent in step 1 of Using the Workflows Functionality

---

jekyll/_cci2/testing-ios.md

[Fixes 20139](https://circleci.atlassian.net/browse/CIRCLE-20139)

Describe disabling test report generation to speed up ios testing.

---

jekyll/_cci2_ja/collect-test-data.md

Fix a tiny coding error to write a link as code style.
Readers cannot click the link to the details of the keyword.

Unwrap back quotes from a link

---

src-api/source/includes/_overview.md

----
Added/removed full stops in API endpoint descriptions.
Typographical consistency.

Fix a couple typographical issues in API docs

---

jekyll/_cci2/configuration-reference.md

say `slashes` instead of `'/s'`.
`'/s'`can make it seem as if a regular expression is written like `/sv.*/s`.

Clarify how delimit a regular expression for filtration.

---

jekyll/_cci2/caching.md

More survey results are indicating some confusion with caching. This PR tries to clear up how templates work and how it's possible to interpolate variables and parameters in them.

Clarify cache key templates.

---

src-api/source/includes/_overview.md

The paragraph just above says it returns human-readable JSON by
default, and that is consistent with all the other examples in the
documets, and my experiments.

Remove note saying the API returns EDN by default

---

jekyll/_cci2/artifacts.md

Minor edit for consistency - the doc was using both `:your_token` and `:token` but I think `:your_token` used consistently would be preferred.
I just saw a slight inconsistency in the name of the circleci token and I suggest this edit. You used `:your_token` twice and `:token` once, in between those two usages of `:your_token`.

use :your_token in both instances we refer to it

---

jekyll/_cci2/orb-intro.md

Fix the link for "Orb Publishing Process"
Existing link returned a 404.

Fix link for Orb Publishing Process

---

jekyll/_cci2/configuration-reference.md

Included some documentation on using halt to end a job from within a step
Resolves https://ideas.circleci.com/ideas/CCI-I-260
and also pulls from https://support.circleci.com/hc/en-us/articles/360015562253-Conditionally-end-a-running-job-gracefully and https://discuss.circleci.com/t/ability-to-return-successfully-from-a-job-before-completing-all-the-next-steps/12969/5

added note on using halt 

---

jekyll/_cci2/language-javascript.md

...of the CircleCI config, NodeJS/NPM, and MongoDB. Most importantly, now that NPM generates a `package-lock.json`, that should be used for the dependency cache key, as suggested on [the caching page](https://circleci.com/docs/2.0/caching/).

update JavaScript page to use modern versions

---

jekyll/_cci2/orbs-best-practices.md

A link was left in from the originating repo that should not be public-facing. Though no user would have had access to view and the document contains no sensitive information, it is just a matter of presentation.

remove internal doc link to Orb Deployment best practices

---

jekyll/_cci2/configuration-reference.md
jekyll/_cci2/testing-ios.md

The shell is now always a login shell, so we remove the instructions to
add --login on the 'testing on ios' page.
We also need to make this clear on the config references page.
Add docs for Xcode 11.1 and update the 11.0 docs to remove the "GM"
designation, since GM 2 _was_ the final release.

Update macOS Docs

---

jekyll/_config.yml
jekyll/_includes/js-config.html
jekyll/_layouts/classic-docs.html
src-js/instantsearch.js

Currently Japanese language pages are not searchable. We want to make them searchable from Japanese docs pages under `/docs/ja` while not including those results in searches from English pages.
We're already indexing Japanese pages in the `cci2_ja` collection, and we were already filtering search results by collection, so enabling this was fairly simple.
We just need to:
1. Dynamically switch which collection we filter on at page load.
2. Write the page language into the JS config to drive some collection selection logic.
There are cases where we need to expose data that we have in the Ruby/Jekyll context to the JS context.
This enables that by building a `circleJsConfig` JS object in an HTML/JS snippet that gets included on every page.
In this initial usage, we use it to pass Algolia …

Enable multi-language search

---

jekyll/_cci2/orbs-best-practices.md

The naming convention area is outdated and incorrectly formatted. Will return with a new PR if we implement new naming practices.

Remove incorrect formatted "naming convention"

---

jekyll/_cci2/faq.md

Added FAQ about why a Performance Plan customer is seeing queuing on their builds.
Previously discussing adding information to docs about our soft concurrency limits for resource classes. Then the idea crossed our mind to add this to FAQ. Link to conversation here: https://circleci.slack.com/archives/C0KBNJGRH/p1569617121053300?thread_ts=1569534915.034100&cid=C0KBNJGRH

Add FAQ about queuing on performance plan

---

jekyll/_cci2/testing-ios.md

We are removing Xcode 9.2 from CircleCI so need to reflect that in the docs.

Remove Xcode 9.2 from the iOS docs due to EOL of the image

---

jekyll/_cci2/workflows-waiting-status.md

A user noted misunderstanding the template url for reaching the GitHub settings page.

Remove unnecessary url example.

---

jekyll/_cci2/orb-author.md

Changes a link label from "Test and Publish Your Orb" to "Validate and Publish Your Orb"
The title of [the linked page](https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/orb-author-validate-publish.md) is "Orb Author - Validate and Publish Orbs."

Fix link label

---

jekyll/_cci2/build-processing.md

Turns out that pipelines are enabled by default for most project, added that detail and changed the wording 
Also turns out that pipelines are compatible with config.yml 2 and 2.1

Updated some details on pipeline settings

---

jekyll/_cci2/configuration-reference.md

Added information in the docs about the different resource classes for each executor type.
Feedback was given that the information on resource_class was confusing. For example they didn't see information about whether there were different resource classes available for Windows or Mac, and there was a note in the description originally stating that resource_class is only configurable for Docker, which is not true.

[WIP]Update documentation w/ separate resource_class tables for each executor type

---

jekyll/_cci2/testing-ios.md

Apple have released Xcode 11.1  to the App Store, and it's the same version as the GM image that we have. In this case we don't need a new release, just a docs bump.

Xcode 11.1 GM is the release version

---

jekyll/_cci2/configuration-reference.md

Example expanded to show the `store_artifacts` step comes after the step that creates the artifact, after customer survey response: "store_artifacts should be place before or after commands reproducing artifacts?"

expand store_artifacts example

---

jekyll/_cci2/collect-test-data.md
jekyll/_cci2_ja/collect-test-data.md

Change `JEST_JUNIT_OUTPUT` to `JEST_JUNIT_OUTPUT_DIR`. 
Such change was introduced in jest-junit 2 months ago:
https://github.com/jest-community/jest-junit/commit/3e135819528f0bdbae19b0ed37d3c043fcff0caf
JEST_JUNIT_OUTPUT environment variable is not longer recognised by jest-junit.

Update Jest example in "Collect test data"

---

jekyll/_cci2/deployment.md

Adding an example of a NuGet deployment for .NET Core.
While learning about Circle CI, I had trouble finding examples of .NET Core CLI deployments so I created one with what I figured out.

Adding example for NuGet deployment via .NET Core CLI

---

jekyll/_cci2/browser-testing.md

nightwatch-saple-for-circleci
->
nightwatch-sample-for-circleci
Typo

Fix typo of the word "sample"

---

jekyll/_cci2/configuration-reference.md

Update `parallelism` entry in the config reference to make it clear that test splitting is the only optimization use, and that parallelism won't lead to a speedup without test splitting.
Also, update code snipped to reflect this description.

update parallelism description

---

jekyll/_cci2/code-coverage.md

“Generage” should be “generate”.
I fixed a typo in the JavaScript section of the Code Coverage docs.
I propose this change because “generage” is almost certainly a typo.

Fix a typo in the JavaScript section

---

jekyll/_cci2/building-docker-images.md

See https://github.com/jonashackt/molecule-ansible-docker-vagrant/issues/5
Added a short note, that DLC isn't available in the free tier anymore.
Fixes https://github.com/circleci/circleci-docs/issues/3860

Docker Layer Caching unavailable on free tier

---

jekyll/_cci2/local-cli.md

Add link to test splitting doc from the CLI doc to address survery repsonse: "I was looking for a way to have multiple machines to run tests in parallel. Sorry as I couldn't find it. ”

Link to test splitting info

---

jekyll/_cci2/migrating-from-gitlab.adoc

1. Fixed the repository from GitHub.com to GitLab.com at 2nd step for migration of the GitHub Enterprise section.
2. Minor typo fixed from Gitlab to GitLab in the header of a different table in the Build Configuration section.
1. The 'git clone' command shows the cloning of a repository from gitlab.com in the GitHub Enterprise section. But the 2nd step describes GitHub.com instead of GitLab.com.
2. **GitLab** is more correct word instead **Gitlab** in the header of a different table in the Build Configuration section. It is similar to that **CircleCI** is the correct one instead of **Circleci** on the published documentation.

Replaced the repository from GitHub.com to GitLab.com on migrating-from-gitlab.adoc

---

jekyll/_cci2/concepts.md

The Jobs section on the concepts page seemed out of date so I've added reference to all executor types and linked to the various executor type examples.

update jobs description to link to executor examples

---

jekyll/_cci2/optimizations.md

fixes #3870 
Remove text stating resource_class only available for `machine`.

remove incorrect ref to resource class use

---

jekyll/_cci2/collect-test-data.md

Improve the .NET `trx2junit` example by specifying the test conversion step should always run. In the current example if `dotnet test` fails, the test results won't get converted
https://support.circleci.com/hc/en-us/requests/60383

Improve .NET example to always convert test results

---

jekyll/_cci2/build-processing.md

This is not live yet, but will be soon. The environment variable
currently doesn't exist at all for builds with pipelines, but
injecting it into 2.0 builds with pipelines lowers the barrier for
switching on pipelines. 2.1 config is not affected.

Add a note about injecting CIRCLE_COMPARE_URL into 2.0 config
