- .gitignore
- circle.yml
In preparation for a real staging env for the static site.
> Deploy staging version of docs to staging bucket

- jekyll/assets/css/main.scss
- jekyll/assets/css/mobile.scss
Tested the site on Safari 9, Chrome 49, Firefox 45, Safari on iOS 9.0, Opera 36, and Chrome for Android 49.
Fixed some small issues for layout.
> Browser fixes

- jekyll/_docs/capybara-timeout.md
Struggled with this today, I think it will help a lot of people running older versions of selenium-webdriver.
****Author is Not a native English speaker
> More explanation on firefox version/error message

- jekyll/_docs/browser-debugging.md
- jekyll/_docs/chromedriver-moving-elements.md
- jekyll/_docs/configuration.md
- jekyll/_docs/continuous-deployment-with-heroku.md
- jekyll/_docs/docker.md
- jekyll/_docs/ios-builds-on-os-x.md
- jekyll/_docs/ios-code-signing.md
- jekyll/_docs/ruby-exception-during-schema-load.md
- jekyll/_docs/shipio-to-circleci-migration.md
- jekyll/_includes/edit-on-github.html
- jekyll/_includes/head.html
Fixing some external links here, but then keep external link checking off on the master branch for now due to length of test.
> Fix external links

- jekyll/_docs/docker-btrfs-error.md
- jekyll/_docs/docker.md
- jekyll/_docs/troubleshooting-docker.md
- Remove mtime caching hack
- Add btrfs error troubleshooting
> Update docker doc

- jekyll/_data/api.yml
- jekyll/_data/versions.yml
- jekyll/_docs/api.md
- jekyll/_docs/build-artifacts.md
- jekyll/_docs/manually.md
Sync docs as of March 30th 15:00 PST.
> Synced docs from old repo.

- LICENSE
- README.md
- jekyll/_includes/doc-footer.html
- jekyll/_includes/footer.html
- jekyll/_includes/license-notice.html
- jekyll/_layouts/classic-docs.html
- jekyll/assets/css/main.scss
- jekyll/assets/css/mobile.scss
Adds a LICENSE file containing the MIT license for the code in this repo. Added CC BY-NC-SA license notice at the footer of each doc to specify that the doc itself is covered under Creative Commons.
Updated README.md to reflect above.
> Added license information.

- jekyll/_docs/phabricator.md
Doc on how to make Phabricator work with Circle. This is orientated towards people who are already using Phabricator, so I have omitted general Phabricator setup and the Arcanist setup steps.
> Add Phabricator doc

- jekyll/_docs/configuration.md
- jekyll/_docs/environment.md
- jekyll/_docs/installing-elasticsearch.md
- jekyll/_docs/language-haskell.md
- jekyll/_docs/language-java.md
- jekyll/_docs/language-nodejs.md
- jekyll/_docs/language-php.md
- jekyll/_docs/language-python.md
- jekyll/_docs/language-ruby-on-rails.md
- jekyll/_docs/test-with-solr.md
- jekyll/_docs/test-with-sphinx.md
- jekyll/_docs/unrecognized-ruby-version.md
> Fixed references to the versions.yml data file.

- jekyll/_docs/language-python.md
Fixed Markdown and capitalization issues in the doc.
> Fixed up formatting in the Python doc.

- jekyll/_docs/test-metadata.md
adding some text to cover the question raised in Issue #55
> add note for cucumber about multiple --format option

- jekyll/_includes/edit-on-github.html
Change the footer that encourages contributions to have a clearer separation from the content of each document. Also, tweak the wording to make it clearer.
> Update footer that encourages contributions

- jekyll/index.html
> Fixed 'X more' links on the index page.

- jekyll/_data/trusty/versions.yml
- jekyll/_docs/build-image-trusty.md
- jekyll/_docs/language-java.md
Addressing extra issues surfaced by #78 
@felicianotech can you please a look?
> OpenJDK7 and OpenJDK8 are pre-installed on Ubutnu 14.04 build image

- jekyll/_docs/environment-variables.md
- Convert html to markdown
- Add CIRCLE_BUILD_IMAGE env var that will be available once a related PR is merged
> Cleanup env page

- jekyll/_docs/ios-builds-on-os-x.md
YAML does not accept comments in this particular position, so removing the comment.
> Fix the syntax of the suggested iOS command

- jekyll/_docs/browser-testing-with-sauce-labs.md
https://github.com/circleci/sauce-connect/blob/a65e41c91e02550ce56c75740a422bebc4acbf6f/circle.yml
> Update Sauce docs to match latest Sauce example

- jekyll/_docs/faq.md
- jekyll/_docs/getting-started.md
- jekyll/_docs/what-happens.md
updating /dashboard link. this is an inner page
> dashboard link is inner page

- jekyll/_docs/continuous-deployment-with-aws-ec2-container-service.md
This adds a new guide on how to deploy to AWS EC2 Container Service using CircleCI and AWS EC2 Container Registry.
> Added new guide - cd with ecs.

- jekyll/_docs/how-cache-works.md
https://discuss.circleci.com/t/cache-save-restore-algorithm/759
> Update how cache works under parallel builds

- jekyll/_docs/status-badges.md
> Formatting fix in status-badges.md.

- jekyll/_docs/build-image-precise.md
- jekyll/_docs/build-image-trusty.md
- jekyll/_docs/language-go.md
- jekyll/_docs/languages.md
Main Changes:
- added a main language doc for Go
- added Go version info to the Ubuntu 12.04 (Precise) doc
> Added docs for Go.

- jekyll/_docs/code-coverage.md
Just had a chat with Kunal Jain and previously @bellkev about adding Codecov docs.
Thank you and let me know if you would like any modifications.
> Add Codecov to coverage docs

- jekyll/_docs/android.md
Now that the Android SDK has been updated, removes workaround line from doc.
Includes other small grammar, style fixes.
-----
Fixes #112
> Update Android suggestions. Small fixes.

- jekyll/_docs/build-image-precise.md
> Fix display of Java versions for Precise image.

- jekyll/_docs/api.md
Fixed link and small formatting fixes.
> Fix link in API doc.

- jekyll/assets/css/main.scss
- jekyll/assets/js/search-index.json
- jekyll/assets/js/search.js
Enables full text search for docs. Search priority is title, category, URL,
then doc contents.
Also, shows "No results found" when nothing comes up. Hopefully this reduces
the number of people thinking the search box is broken.
> Improve CircleCI Docs Search Experience

- jekyll/_docs/build-image-trusty.md
> Fix MySQL version in Trusty build doc

- jekyll/_docs/configuration.md
https://discuss.circleci.com/t/circle-yml-allowed-syntax-inconsistent-with-documentation/4335/5?u=drazisil
> Added note regarding colon for modifiers

- jekyll/_docs/how-cache-works.md
Also swap order of cached items listed, showing defaults first.
> Add example to cache section

- jekyll/_docs/language-python.md
I have a number of libraries, which I test across multiple python versions using tox. It took me some time to figure out how to get this to work on circleci, and I thought it would be useful to add this information to the documentation.
> Added information on using multiple Python versions simultaneously.

- jekyll/_docs/test-metadata.md
This has been supported but undocumented for a while. Better document it :)
> Better document test metadata usage with 'files' modifier

- jekyll/_docs/test-metadata.md
Also added a section table of contents and re-alphabetized the customer runners are the list is getting a tad long.
> Added mocha

- jekyll/_docs/installing-elasticsearch.md
Make sure that Elasticsearch is up before running tests.
> Wait for Elasticsearch

- jekyll/_docs/build-artifacts.md
> Fix artifact URL.

- jekyll/_docs/build-image-trusty.md
Fixes https://github.com/circleci/circleci-docs/issues/226#issuecomment-232731601
> Hardcode java version for trusty

- jekyll/_docs/ios-builds-on-os-x.md
> Cocoapods -> CocoaPods

- jekyll/_docs/differences-between-trusty-and-precise.md
Hey @kimh, just small changes to your branch here. Mostly spelling fixes but also some front matter changes.
Let me know if you have any questions.
> Fix spelling & grammar for Ubuntu 12.04 vs Ubuntu 14.04 doc.

- jekyll/_docs/faq.md
> Fix FAQ by removing outdated info.

- jekyll/_docs/environment-variables.md
Example of storing secrets in encrypted files in source.
> Document encrypted files

- jekyll/_docs/faq.md
added bitbucket support, fixed formatting issues elsewhere
> Changes to text

- jekyll/_data/api.yml
- jekyll/_docs/api.md
This should fully update the API docs to reflect v1.1 changes as I understand them.
> Update for api v1.1

- jekyll/_docs/api.md
Also fixed a couple broken headers
> Fixed a small number of missed instances

- jekyll/_data/api.yml
> Fix malformed JSON in API 'New Build' example.

- jekyll/_docs/configuration.md
- jekyll/_docs/faq.md
- add info about subscribing to: https://discuss.circleci.com/c/announcements
- fix formatting 
- update info on chat application notifications
> Update FAQ and Config with announcements info and other fixes

- jekyll/_docs/differences-between-trusty-and-precise.md
SRE and Support team may have alternative way, so hiding this for now
from the official doc.
> Remove circleci-install from doc

- jekyll/_docs/enterprise/aws.md
- jekyll/_docs/enterprise/differences.md
Added fixes that address how jekyll and markdown differ. Also fixed up
another broken link. Ready for review now.
> AWS Enterprise Fixes

- jekyll/_docs/cabal-test-timeout.md
> Update documentation regarding timeouts

- jekyll/_docs/continuous-deployment-with-google-container-engine.md
Related JIRA ticket: https://circleci.atlassian.net/browse/CIRCLE-695
> Update gcloud upgrade instructions

- jekyll/_docs/docker-btrfs-error.md
Indefinite articles are definitely a favorite.
> add missing word

- jekyll/_data/api.yml
- jekyll/_docs/api.md
> Add doc info for /follow API endpoint.

- jekyll/_docs/language-python.md
> Fix grammar in _docs/language-python.md

- jekyll/_docs/build-image-trusty.md
- jekyll/_docs/cant-follow.md
- jekyll/_docs/configuration.md
- jekyll/_docs/faq.md
- jekyll/_docs/fork-pr-builds.md
- jekyll/_docs/getting-started.md
- jekyll/_docs/how-cache-works.md
- jekyll/_docs/migrating-from-jenkins.md
- jekyll/_docs/requires-admin.md
- jekyll/_docs/what-happens.md
> Updated docs to reflect Bitbucket support

- jekyll/_docs/configuration.md
> Reduce number of links to get to language versions.

- jekyll/_docs/configuration.md
This phrasing is... problematic.
> s/asking for trouble/problematic

- jekyll/_docs/enterprise/overview.md
And haven't been in a really long time.
> Non-AWS envs are no longer in beta

- jekyll/_docs/build-image-trusty.md
Fixes https://github.com/circleci/circleci-docs/issues/372
> Add a link to Ubuntu 14.04 Docker image

- jekyll/_docs/enterprise/debugging-replicated.md
- jekyll/_docs/enterprise/debugging.md
Includes tips for Replicated provided by @kimh
> Add Debugging section to CCIE docs

- jekyll/_data/api.yml
Users read these docs and think they can include $CIRCLE_ARTIFACTS in urls
> Removed $CIRCLE_ARTIFACTS

- jekyll/_docs/configuration.md
not everything is a web app :)
> web app -> app

- jekyll/_docs/manually.md
> Remove reference to a lack of root. Sudo is supported now.

- jekyll/assets/js/main.js
Initializing user before tracking
**Note:** unable to test locally because `localhost:4000/api/v1/me` cannot be resolved. We can potentially set up nginx to route it to `cci.com/api/v1/me` but ¯\\_(ツ)_/¯. It seems running cci.com locally also cannot resolve `localhost:4000/api/v1/me`
> [CIRCLE-1738] Initializing user before tracking

- jekyll/_docs/getting-started.md
Rather than asking y'all i thought i'd put something fwd for you to edit as you like :)
I specifically wanted to ensure Add Projects and Following Projects are more clear.
> update getting started to clarify add/follow

- jekyll/_docs/browser-debugging.md
Started with the description, then figured I'd give the rest of the article a read. A few typo corrects, a few changes of "I" to "we," a few corrections of Circle or Circleci to CircleCI, some more em-dashes instead of double-hyphens, more commands in backticks.
> a bunch of little edits

- jekyll/assets/css/main.scss
Darkening font color for legibility
@ndintenfass & @smart-alek & @felicianotech
> darkening font color for legibility

- jekyll/_docs/language-go.md
> Update Go page with syntax and version fix.

- jekyll/_docs/language-php.md
> Add `sudo` to PHP example.

- jekyll/assets/css/main.scss
- jekyll/assets/js/search.js
This adds an excerpt of the content of the suggested articles based on the full text search results of article content:
> Enhanced search results with content snippets

- jekyll/_docs/code-coverage.md
Discussion in https://github.com/scoverage/sbt-scoverage/issues/202#issuecomment-259670217.
> Upgraded to sbt-scoverage 1.5.0 and provided two full working examples.

- jekyll/_docs/configuration.md
> Fix PhantomJS download link.

- jekyll/_docs/android.md
> Update Android predexing link to something current.

- jekyll/_docs/configuration.md
> Revise configuration doc

- jekyll/_docs/installing-elasticsearch.md
Also some little grammar things, while I'm at it!
> updating elasticsearch download links & version

- jekyll/_docs/install-and-use-yarn.md
Fixes issue brought up by #488.
> Fix Yarn directory.

- jekyll/_docs/continuous-deployment-with-aws-ec2-container-service.md
> Fix typo in ECS deploy doc.

- jekyll/_docs/android.md
> Remove references to Android NDK as it's not installed.

- jekyll/_docs/enterprise/docker-install.md
Update docker doc to not require "init-builder-docker" script now that more of the logic is in the container itself.
> Update docker install doc

- jekyll/_docs/google-auth.md
The added instruction fixed for me issue #500
> Added documentation that fixed issue #500

- jekyll/_includes/sidebar-cci1.html
I'm pretty sure this was something that should have already existed but fell through the cracks.
> Hide hidden docs from the standard sidebar.

- jekyll/_docs/introduction.md
It was recommended that Lev's post in Discuss would make for good partial for docs and I agree. Here's a port of [that post](https://discuss.circleci.com/t/newbie-completely-confused/8271/7).
> Add Introduction doc.

- jekyll/_docs/language-ruby-on-rails.md
- jekyll/_docs/rvm-cache-ruby-binaries.md
- jekyll/_docs/troubleshooting-ruby.md
> Add discuss guide for caching pre-compiled Ruby binaries with RVM

- jekyll/_docs/enterprise/single-box.md
* Rephrased the sentence that notes potential long startup times.
> Clean up language around final startup time

- jekyll/_docs/environment-variables.md
> Add note on editing envars.

- jekyll/_docs/build-image-trusty.md
> Fixed wording in Trusty doc.

- jekyll/_docs/language-python.md
Fixes #490 
@li3n3, care to review since this stems from your Issue?
> Add more Inference examples to Python doc.

- jekyll/_docs/fork-pr-builds.md
Fixes #484.
@KunalJain Is the last line about Bitbucket still true?
> Update fork PR dock.

- jekyll/_docs/android.md
This PR fixes a mistake in commit 89becc564a0567e239aaf6797f5206fa8af66ad2. [Stack Overflow](http://stackoverflow.com/a/37191719) is where the correct command  comes from.
> Correct adb screenshot command

- jekyll/_docs/how-cache-works.md
> Update how-cache-works with better info.

- jekyll/_docs/yarn.md
> Add version widget to Yarn doc.

- jekyll/_docs/docker.md
> Add version widget to Docker doc.

- jekyll/_docs/how-cache-works.md
> clean up phrasing and other small edits

- jekyll/_docs/how-cache-works.md
The rendering on the main site was wrong (at least in my Firefox browser)
> Added missing close quote at line 52

- jekyll/_docs/how-cache-works.md
> Fixed syntax typo in cache doc.

- jekyll/_docs/continuous-deployment-with-heroku.md
> Update Heroku doc with how to add creds manually.

- jekyll/_layouts/classic-docs.html
@smart-alek @li3n3 
Fixes #631
> Make GitHub footer appear again.

- jekyll/_cci1/test-metadata.md
Adds example of how to collect test metadata with Ava
Prompted by https://twitter.com/circleci/status/830111551050829825
> Add Ava to the custom runner example

- LABELS.md
This is a first draft at a new labels schema for our Issues in `circleci-docs`.
> add labels style guide

- jekyll/_cci1/docker.md
> Update Docker Postgres example.

- jekyll/_cci1/test-metadata.md
> Added section on merging JUnit reports

- jekyll/_cci2/faq.md
This is the FAQ from Discuss, but heavily revised to keep it from being too "marketing-esque".
For example, I removed questions like "Why doesn't Build with SSH work?" because the answer is "It isn't implemented yet, sorry!"
> 2.0 add faq

- jekyll/_cci2/env-vars.md
Adding available environment variables and descriptions for CircleCI 2.0.
> 2.0 add env vars

- jekyll/_cci1/faq.md
> update url to https

- jekyll/_cci2/managing-parallelism.md
@keybits @felicianotech In the process of moving Discuss posts over to 2.0 docs. 
https://discuss.circleci.com/t/managing-parallelism-with-the-2-0-tests-cli/10360
> Managing parallelism

- jekyll/_cci2/executor-types.md
@keybits @felicianotech This is the Docker Engine post [here](https://discuss.circleci.com/t/getting-started-docker-engine/8957).
> Executor type

- jekyll/_cci2/first-steps.md
This guide gets people familiar with the UI basics and shows them how to authorize their code on either GitHub or Bitbucket. It didn't exist in Discuss and is modeled off "Getting Started with CircleCI" from the 1.0 docs.
@keybits @felicianotech
> First steps

- jekyll/_cci2/configuration.md
- jekyll/_cci2/configuring-circleci.md
- jekyll/_cci2/executor-types.md
- jekyll/_cci2/faq.md
- jekyll/_cci2/first-steps.md
- jekyll/_cci2/managing-parallelism.md
- jekyll/_cci2/quickstart-go.md
- jekyll/_cci2/quickstart-javascript.md
- jekyll/_cci2/quickstart-php.md
- jekyll/_cci2/quickstart-python.md
- jekyll/_cci2/quickstart-ruby.md
- jekyll/_data/categories.yml
Feature parity with Discuss docs.
> Initial 2.0 docs

- jekyll/_cci2/first-steps.md
@keybits @felicianotech Moving a few sections around for clarity and adjusting header size for next steps.
> revise first steps doc

- jekyll/_cci2/managing-parallelism.md
@keybits @felicianotech 
Headings were off since the title is automatically
made an h1. Also, added an intro paragraph to describe
why users should even read the guide.
> revise headings & add intro

- jekyll/_cci2/quickstart-go.md
- jekyll/_cci2/quickstart-javascript.md
- jekyll/_cci2/quickstart-php.md
- jekyll/_cci2/quickstart-python.md
- jekyll/_cci2/quickstart-ruby.md
Had this committed to the old repo earlier.
> Update quickstarts with latest syntax.

- jekyll/_cci2/configuration.md
- jekyll/_cci2/env-vars.md
- jekyll/_cci2/executor-types.md
- jekyll/_cci2/faq.md
- jekyll/_cci2/first-steps.md
- jekyll/_cci2/index.md
- jekyll/_cci2/managing-parallelism.md
- jekyll/_cci2/quickstart-go.md
- jekyll/_cci2/quickstart-javascript.md
- jekyll/_cci2/quickstart-php.md
- jekyll/_cci2/quickstart-python.md
- jekyll/_cci2/quickstart-ruby.md
- jekyll/_layouts/classic-docs2.html
> Add Beta banner to 2.0 docs

- jekyll/_cci2/configuration.md
- jekyll/_cci2/configuring-circleci.md
- jekyll/_cci2/env-vars.md
- jekyll/_cci2/executor-types.md
- jekyll/_cci2/first-steps.md
- jekyll/_cci2/getting-started.md
- jekyll/_cci2/language-go.md
- jekyll/_cci2/language-javascript.md
- jekyll/_cci2/language-php.md
- jekyll/_cci2/language-python.md
- jekyll/_cci2/language-ruby.md
- jekyll/_cci2/managing-parallelism.md
- jekyll/_cci2/quickstart-guides.md
- jekyll/_cci2/reference.md
- jekyll/_data/categories.yml
New top level categories for 2.0 docs. Discussed with @ndintenfass and should be inclusive of all 2.0 docs requirements for now.
> Update categories for 2.0 docs

- jekyll/assets/css/jquery.navgoco.css
> Tone down sidebar menu colors

- jekyll/_cci1/nightly-builds.md
> Add note to nightly builds regarding where the server is.

- jekyll/_cci1/build-artifacts.md
> Use API 1.1 and explain retention and file size for artifacts

- jekyll/_layouts/classic-docs2.html
Adds a missing letter to CircleCI
> fix typo in 2.0 disclaimer

- jekyll/_cci2/executor-types.md
- jekyll/_cci2/faq.md
- jekyll/_cci2/language-go.md
- jekyll/_cci2/language-javascript.md
- jekyll/_cci2/language-python.md
- jekyll/_cci2/language-ruby.md
A few of these in `configuration.md` too but I'm holding off on those due to potential conflicts with the "getting-started-config" branch.
> Catch a few stragglers of references to the old terminology.

- jekyll/_cci2/builtin-steps.md
> Fix layout link and replace 'builds' with 'jobs'

- CONTRIBUTING.md
Migrating this info from the wiki
> Add info on writing for 2.0

- jekyll/_cci2/migration-config-equivalents.md
- jekyll/_cci2/migration-config-mapping.md
I'm not sure if "Configuration Mapping" is a correct but I couldn't come up a better name. If anyone has a better idea, please just use it.
> Add configuration mapping

- jekyll/_cci2/docker-and-circleci-2.md
- jekyll/_cci2/getting-help-with-2.0.md
- jekyll/_cci2/specifying-versions.md
Some initial outline docs for empty 2.0 sections.
> Outline documents for 2.0 sections

- LABELS.md
- consolidate different types of editing
- add "Design" type for visual changes
- add "Maintenance" type for refactoring/reorganization
- remove "Question"; these should be closed instantly & sent to Discuss
> Continued iteration on labels

- jekyll/_cci2/env-vars.md
- jekyll/_cci2/managing-dependencies.md
> Reorder menu items for config category

- jekyll/_layouts/classic-docs2.html
Based on [this JIRA ticket](https://circleci.atlassian.net/browse/CIRCLE-3303) with a few edits for clarity.
> adjust copy for welcome blurb

- jekyll/_cci2/language-ruby.md
To catch up https://github.com/circleci/cci-demo-rails/pull/3
> Use PG instead of sqlite

- jekyll/_cci2/language-ruby.md
We are using PG in our sample Rails project https://github.com/circleci/cci-demo-rails/pull/3 
Although we don't have to add a step in circle.yml (because Rails will take care of creating test db in PG), some clarification is useful.
> Clarify DB section in the Rails guide

- jekyll/_cci2/executor-types.md
We're using underscores for new style config.
> Underscores for new config

- jekyll/_cci2/builtin-steps.md
This updates the copy to the new config syntax.
> Update builtin steps syntax

- jekyll/_cci2/about-circleci.md
- jekyll/_cci2/first-steps.md
I'm moving this section into Getting Started and revising a lot of the language.
> Revise about section

- jekyll/_data/categories.yml
Just some maintenance and removal of a category.
> Clean up categories + remove "What is CircleCI?" section

- jekyll/_cci2/about-circleci.md
Fixes a broken link from updated doc name.
> Fix broken link

- jekyll/_cci2/index.md
@keybits 
This injects some levity and hopefully points people in the right direction depending on their level of experience with CircleCI.
> Revise 2.0 index

- jekyll/_cci2/caching.md
@eric-hu Went to town on this doc. Please let me know if there was anything that was lost in translation!
> Eric cci2 caching

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/migrating-from-1-2.md
Make links more specific and add context around job steps.
> update links to configuration reference

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/env-vars.md
- jekyll/_cci2/glossary.md
- jekyll/_data/categories.yml
Create new reference category and move relevant articles into it:
- Configuration Reference
- Environment Variables
- Glossary
> Create reference category

- jekyll/_cci2/demo-apps.md
Add links to each demo app from the index page.
> Add links to index page for demo apps

- jekyll/_cci2/caching.md
- jekyll/_cci2/executor-types.md
- jekyll/_cci2/local-builds.md
- jekyll/_cci2/parallelism-faster-jobs.md
- jekyll/_cci2/remote-docker.md
Also reorder docs to make more logical sense within "Configuring Jobs" section.
> Revise local builds doc

- jekyll/_cci2/executor-types.md
- jekyll/_cci2/remote-docker.md
Some minor changes as a result of Anton's review of my copyedits.
> Address Anton's comments

- jekyll/_cci2/building-docker-images.md
- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/executor-types.md
- jekyll/_cci2/glossary.md
As discussed, the old title was not clear enough on the "why" of this feature.
> Building docker images

- jekyll/_cci2/language-erlang.md
- jekyll/_cci2/language-go.md
- jekyll/_cci2/language-javascript.md
- jekyll/_cci2/language-php.md
- jekyll/_cci2/language-python.md
- jekyll/_cci2/language-ruby.md
- put sample configuration at the top for easy access
- link to demo apps when available
- explicit labels for project walkthroughs
> Restructure language guides

- jekyll/_layouts/classic-docs.html
- jekyll/assets/css/main.scss
As discussed with Nathan, removes the useless sidebar from the new homepage.
> Cleanup homepage.

- jekyll/assets/css/main.scss
@keybits 
How is this looking? Give it a review!
> making searchbar results appear on the left

- jekyll/_cci1/config-sample.md
- jekyll/_cci1/configuration.md
This issue was kindly reported [via Twitter](https://twitter.com/iamtheotherian/status/839892482678644736) and confirmed in a few Postgres Docs places including [this one](https://jdbc.postgresql.org/documentation/head/logging.html).
> Correct Postgres's protocol links.

- LABELS.md
Remove:
- Available
- Blocked
- Needs Revision
- Needs Review
Add:
- Confirmed
- Inaccuracy
- Unconfirmed
Change:
- Edit
- all priorities
> Updates to labels

- jekyll/_cci1/migrating-from-jenkins.md
> Add missing link in Jenkins guide

- jekyll/_cci2/project-walkthrough.md
Revisions for clarity and a wonderful, magical onboarding experience.
> Revise project walkthrough

- jekyll/_cci2/configuration-reference.md
Doc was using old style in the example/
> change  test-results-store to store_test_results

- jekyll/_cci2/migrating-from-1-2.md
> Fixed /etc/host typo

- jekyll/_cci2/project-walkthrough.md
Links to inner should not have a trailing slash.
> remove trailing slash from inner link

- jekyll/_cci2/faq.md
- jekyll/_cci2/migrating-from-1-2.md
- jekyll/_cci2/project-walkthrough.md
https://circleci.atlassian.net/browse/CIRCLE-3490
> Remove no inference refs

- jekyll/_cci2/language-clojure.md
This one uses this sample project I just pushed.
> Add basic Clojure language guide.

- jekyll/_cci2/configuration-reference.md
Reverts circleci/circleci-docs#839
> Revert "Remove formatting from a header to test search."

- jekyll/_cci1/adding-read-write-deployment-key.md
> clarify copy for github keys

- jekyll/_cci1/manually.md
> add link to deployment guide

- jekyll/_cci2/building-docker-images.md
> remove extra 'a'

- jekyll/_cci1/test-metadata.md
> remove early reference to Cucumber/JSON

- jekyll/_cci1/polling-project-status.md
> update link target

- jekyll/_cci2/deployments-and-uploads.md
- jekyll/_cci2/deployments.md
I'm only addressing deployment part in this PR. Also, I renamed deployments-and-uploads.md to simply deployments.md because I thought the two topics have to deserve a dedicated page.
> CIRCLE-3354 First writing about deployment

- jekyll/_cci2/building-docker-images.md
- jekyll/_cci2/docker-compose.md
- jekyll/_cci2/private-images.md
- jekyll/_cci2/project-walkthrough.md
- jekyll/_data/categories.yml
1. Added separate section for docker
2. Split current docker doc into two
3. Added docker-compose doc
> Separate docker section and docker-compose doc

- jekyll/_cci1/yarn.md
> Clarify overriding in Yarn doc.

- jekyll/_cci2/configuration-reference.md
`run` step can take a `no_output_timeout` modifier
> [CIRCLE-3453] document no_output_timeout

- jekyll/_cci2/artifacts.md
- jekyll/_cci2/caching.md
- jekyll/_cci2/custom-images.md
- jekyll/_cci2/defining-multiple-jobs.md
- jekyll/_cci2/deployments.md
- jekyll/_cci2/executor-types.md
- jekyll/_cci2/glossary.md
- jekyll/_cci2/local-jobs.md
- jekyll/_cci2/parallelism-faster-jobs.md
> CIRCLE-3360 building custom images

- jekyll/_cci1/parallel-manual-setup.md
I'm going to be adding some info from @eric-hu, but some of this just needs some love. I am practicing as much willpower as I can. There is so much more I want to do.
WIP for a little longer!
> parallelization additions

- jekyll/_cci2/env-vars.md
> CIRCLECI_NODE_TOTAL -> CIRCLE_NODE_TOTAL

- jekyll/_cci2/building-docker-images.md
- jekyll/_cci2/docker-compose.md
- jekyll/_cci2/docker-layer-caching.md
- jekyll/_cci2/private-images.md
Whoops, got trigger happy again. Reverts circleci/circleci-docs#888
> Revert "renamed `setup_docker_engine` step"

- jekyll/_cci2/project-walkthrough.md
> Tweak walkthrough to make clear you need to commit and push config

- jekyll/_cci2/demo-apps.md
add Clojure guide to index page for demo apps
> add clojure to index

- jekyll/_ccie/ios.md
> Clarify iOS fleet in CCIE

- README.md
- cut down some lines of instruction
- replace GitHub Desktop recommendation with GitHub link
> keep README as lean as possible

- jekyll/_cci1/setting-up-parallelism.md
Fixes #645 @li3n3 @ndintenfass
> remove video & revise copy

- jekyll/_cci1/how-parallelism-works.md
Bringing back doc that was linked in many places.
> bring back parallelism doc

- jekyll/_cci2/docker-layer-caching.md
also moved alert about whitelisting to the top
> make docker caching doc public

- CONTRIBUTING.md
Add link to a simple tech writing style guide, change h1/h2 for clarity, update name of button in GitHub UI for small edits.
> update contributing.md with link an two changes

- jekyll/_cci1/ios-code-signing.md
This Pull Request will be helpful to copy and paste samples 😃
> Fix invalid YAML format

- jekyll/_cci2/about-circleci.md
- jekyll/_cci2/artifacts.md
- jekyll/_cci2/building-docker-images.md
- jekyll/_cci2/caching.md
- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/custom-images.md
- jekyll/_cci2/defining-multiple-jobs.md
- jekyll/_cci2/demo-apps.md
- jekyll/_cci2/deployments.md
- jekyll/_cci2/docker-compose.md
- jekyll/_cci2/docker-layer-caching.md
- jekyll/_cci2/env-vars.md
- jekyll/_cci2/executor-types.md
- jekyll/_cci2/faq.md
- jekyll/_cci2/first-steps.md
- jekyll/_cci2/glossary.md
- jekyll/_cci2/help-and-support.md
- jekyll/_cci2/index.md
- jekyll/_cci2/language-clojure.md
- jekyll/_cci2/language-elixir.md
- jekyll/_cci2/language-go.md
- jekyll/_cci2/language-javascript.md
- jekyll/_cci2/language-php.md
- jekyll/_cci2/language-python.md
- jekyll/_cci2/language-ruby.md
- jekyll/_cci2/local-jobs.md
- jekyll/_cci2/migrating-from-1-2.md
- jekyll/_cci2/parallelism-faster-jobs.md
- jekyll/_cci2/private-images.md
- jekyll/_cci2/project-walkthrough.md
Adds descriptions to each 2.0 doc. Fixes [this ticket](https://circleci.atlassian.net/browse/CIRCLE-3656).
> add brief descriptions for all 2.0 docs

- jekyll/_cci2/executor-types.md
https://public.wsu.edu/~brians/errors/undo.html
> Correct English word

- jekyll/_cci2/faq.md
Let people know that it's easy to try out 2.0 while still building on 1.0
> Add info to FAQ on switching between 1.0 and 2.0

- jekyll/_cci1/Artifactory.md
> Update Artifactory cli example

- jekyll/_cci1/ios-builds-on-os-x.md
> ios-build-on-osx article spelling updates

- jekyll/_cci2/faq.md
Copy revisions/improvements for 2.0 FAQ
> Fix up faq

- jekyll/_cci2/defining-multiple-jobs.md
- jekyll/_cci2/language-go.md
- jekyll/_cci2/language-javascript.md
- jekyll/_cci2/language-php.md
- jekyll/_cci2/language-python.md
- jekyll/_cci2/language-ruby.md
- jekyll/_cci2/project-walkthrough.md
Updates config in many places to use the shorthand syntax for the `run` step. Addresses [this JIRA ticket](https://circleci.atlassian.net/browse/CIRCLE-3678).
If this PR gets merged, we'll also need to update the `config.yml` for each demo project. This is probably another sign that we need to get some automatic synchronization between those repos and docs.
> Use run shorthand

- jekyll/assets/js/main.js
@JustinC474 trying to fix analytics tracking on button click. 
The page is throwing a cors error still; going to try a pure JS implementation of the function to see if that works.
> rewriting track function without jquery

- jekyll/_ccie/docker-install.md
- jekyll/_ccie/faq.md
Couple things I've been meaning to fix on the clustered docker install docs.
> Ccie docker fixes

- jekyll/_ccie/docker-install.md
Fix other instance of image uri
> One more small docker doc fix

- jekyll/_cci2/project-walkthrough.md
The cci-demo-walkthrough repo has been updated and tested with this: https://circleci.com/gh/circleci/cci-demo-walkthrough/8
> Fix caching strategy in project walkthrough, resolves #917

- jekyll/_cci2/faq.md
- jekyll/_cci2/migrating-from-1-2.md
Pointed out at https://discuss.circleci.com/t/cant-checkout-code/11592/13?u=kimh
> Add the requirement of ssh for checkout step

- jekyll/_cci2/configuration-reference.md
Clarify that test results are not currently available as artifacts
> Test results need uploading as artifacts

- jekyll/_cci1/oom.md
The value could be smaller as well as larger.
> Update JVM memory guidance

- jekyll/assets/css/main.scss
see ticket for more info: 
https://circleci.atlassian.net/browse/MKTG-278
> constraining docs grid; removing nav bg

- jekyll/assets/css/main.scss
> Fix nav background color for mobile.

- jekyll/_ccie/debugging-replicated.md
Per Chris this file is no longer auto-generated with Replicated 2
> Removed outdated info

- jekyll/_ccie/docker-install.md
in particular, there were some repetitions and missing words needed
> further grammar tweaks

- jekyll/_includes/beta-premium-feature.html
> Update beta-premium-feature.html for clarity

- jekyll/_cci2/faq.md
- jekyll/_cci2/migrating-from-1-2.md
This fixes some links and is also a blocker for #1039.
> Fix links.

- jekyll/_cci2/index.md
Add links with urls to demos and images, language versions, links to info about main features, and pricing.
> Update index.md for 2.0 docs

- jekyll/_cci2/language-clojure.md
> update language-clojure.md to replace link

- jekyll/_cci2/index.md
> update index.md to fix formatting

- jekyll/_cci2/demo-apps.md
- jekyll/_cci2/language-go.md
- jekyll/_cci2/language-javascript.md
- jekyll/_cci2/language-php.md
- jekyll/_cci2/language-python.md
- jekyll/_cci2/language-ruby.md
> Fix language doc links

- jekyll/_cci2/about-circleci.md
This renames About CircleCI to Overview and replaces general content about CI/CD with specific info about CircleCI and an image of the general flow of how it works.
> update about-circleci.md for overview

- jekyll/_cci2/build-project.md
- jekyll/_cci2/hello-world.md
new file for simple project build on 2.0
> Build project doc

- jekyll/_cci2/language-php.md
- jekyll/_cci2/language-python.md
Remove Python and replace with PHP
> Fix php doc

- jekyll/_cci2/deployment_integrations.md
- jekyll/_cci2/faq.md
- jekyll/_cci2/language-go.md
- jekyll/_cci2/migrating-from-1-2.md
- jekyll/_cci2/project-walkthrough.md
- jekyll/_cci2/sample-config.md
- jekyll/_data/categories.yml
This is a huge wad of edits to create a new Migration section, using most of the content we had already, but moved around a bit with more formal, declarative language and instructions. 
Migration
-Migration FAQ (removed troubleshooting and added 'Why Migrate?' content from the walkthrough)
-Sample 2.0 config.yml File (new overview of jobs and steps with javascript demo app config.yml example)
-Project Tutorial (renamed walkthrough and edited to streamline it and have sections build on each other a bit more, while removing info covered in the getting started docs and moving manual deploy steps to the end)
-Migrating from 1.0 to 2.0 (re-ordered and changed tack to first add version and re-nest all sections, then search and replace the changed/equivalent keys)
thanks,
Michelle
> Migration section

- jekyll/_includes/global-nav.html
- jekyll/assets/css/navbar.css
Fixing issue with the new nav, where `go to app` isn't displaying when logged in.
> fixing new nav

- jekyll/_cci2/parallelism-faster-jobs.md
This documents the flag added by [the merge commit](https://github.com/circleci/build-agent/commit/8faf5a5dcefaa063906b2e9beb2fcebb59abf7fa) for build agent PR number 396.
> Document new flag

- jekyll/_cci2/caching.md
WIP - needs copy editing and links updated to working versions.
> Initial update of 2.0 caching doc

- jekyll/_cci2/faq.md
Fixes #1115.
This was broke in PR #1078.
> Fix broken links in 2.0 FAQ.

- jekyll/_cci2/caching.md
- jekyll/_cci2/custom-images.md
- jekyll/_cci2/docker-layer-caching.md
- jekyll/_cci2/local-jobs.md
- jekyll/_cci2/parallelism-faster-jobs.md
- jekyll/_cci2/private-images.md
- jekyll/_cci2/ssh-access-jobs.md
- jekyll/_data/categories.yml
Hi,
After thinking more about Nathan's verbal suggestions last week and because more small sections will help the structure while we have only two levels, I have added two more categories:
Optimization (for the caching and perf content)
Troubleshooting (for the CLI and SSH content, but I'm sure this will grow over time)
And I fixed some categories that I messed up on the first pass.
Thanks,
Michelle
> More structure updates

- jekyll/_cci2/migrating-from-1-2.md
- jekyll/_cci2/workflows.md
some additions for clarity, minor fixes, and a note about parallelism
> Michelle luna patch 1

- jekyll/_ccie/docker-builder-config.md
Now matches https://github.com/circleci/circleci-docs/blob/master/jekyll/_ccie/docker-install.md
> Updated to show full config

- jekyll/_cci2/docker-compose.md
I put it under "containerization" instead
> docker-compose doesn't fit under deployment

- jekyll/_cci2/circleci-images.md
Following up on https://twitter.com/FelicianoTech/status/874763497527275520 :)
> Add link to pre-built docker images repository

- jekyll/_cci1/environment-variables.md
> Note that envars are case-sensitive.

- jekyll/_cci1/android.md
- jekyll/_cci1/background-process.md
- jekyll/_cci1/code-coverage.md
- jekyll/_cci1/config-sample.md
- jekyll/_cci1/configuration.md
- jekyll/_cci1/dont-run.md
- jekyll/_cci1/environment-variables.md
- jekyll/_cci1/external-resources.md
- jekyll/_cci1/github-privacy.md
- jekyll/_cci1/how-cache-works.md
- jekyll/_cci1/installing-custom-software.md
- jekyll/_cci1/ios-builds-on-os-x.md
- jekyll/_cci1/ios-code-signing.md
- jekyll/_cci1/ios-getting-started.md
- jekyll/_cci1/manually.md
- jekyll/_cci1/migrating-from-jenkins.md
- jekyll/_cci1/nightly-builds.md
- jekyll/_cci1/nodejs-and-npm.md
- jekyll/_cci1/parallel-manual-setup.md
- jekyll/_cci1/permissions-and-access-during-deployment.md
- jekyll/_cci1/setting-up-parallelism.md
- jekyll/_cci1/skip-a-build.md
- jekyll/_cci1/test-metadata.md
- jekyll/_cci1/web-notifications.md
- jekyll/_data/categories.yml
Hi,
This set of changes is to improve the structure of the 1.0 docs collection to the following:
Getting Started
Migration
Build Environments
Configuration 
Optimization
Integrations
Language Guides
Reference
Troubleshooting
> Doc restructure 1 0

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/executor-types.md
- jekyll/_cci2/faq.md
- jekyll/_cci2/hello-world.md
- jekyll/_cci2/migrating-from-1-2.md
- jekyll/_cci2/sample-config.md
Please review for errors and omissions
> Primary container image

- jekyll/_cci2/caching.md
update with feedback, re-order sections, remove source caching
> Caching feedback

- jekyll/_cci2/artifacts.md
Please review for accuracy and omissions
> Artifacts update

- jekyll/_cci2/custom-images.md
- jekyll/_cci2/executor-types.md
- jekyll/_cci2/faq.md
- jekyll/_cci2/gh-bb-integration.md
- jekyll/_cci2/migrating-from-1-2.md
- jekyll/_cci2/project-walkthrough.md
- jekyll/_cci2/sample-config.md
added the tips from discuss to this article
> Create custom image additions

- jekyll/_cci2/deployment_integrations.md
- jekyll/_cci2/deployments.md
- jekyll/_cci2/env-vars.md
- jekyll/_cci2/executor-types.md
- jekyll/_cci2/faq.md
- jekyll/_cci2/gh-bb-integration.md
- jekyll/_cci2/language-elixir.md
- jekyll/_cci2/migrating-from-1-2.md
- jekyll/_cci2/notifications.md
- jekyll/_cci2/project-walkthrough.md
- jekyll/_cci2/sample-config.md
- jekyll/_cci2/workflows.md
- jekyll/_data/categories.yml
- jekyll/_includes/beta-premium-feature.html
sweep all docs for editorial style, formatting, and incorporate new user feedback
> Gh bb integrations format fix

- jekyll/_cci2/configuration-reference.md
Added a note that feature is not compatible with workflows.
> Update store_test_results feature

- jekyll/_cci1/configuration.md
We get quite frequent support requests saying that a regex of `/.*/` doesn't match all branches or tags. As documented on Discuss you need `/.*?/`: https://discuss.circleci.com/t/regex-to-build-and-deploy-when-any-tag-is-pushed/4114
Adding it to 1.0 docs. (Need to add to 2.0 docs? @michelle-luna )
> Add regex example for building on any tag or branch

- jekyll/_cci1/configuration.md
- jekyll/_cci1/permissions-and-access-during-deployment.md
Spotted by @leocabeza via Support ticket.
> Added ssh keys need an empty passphrase

- jekyll/_cci2/high-uuid-error.md
Improvements to the high uuid error doc
> Grammar and typo fixes

- jekyll/_cci2/workflows.md
> Fix parallel job execution example

- jekyll/_cci2/postgres-config.md
> Update postgres example to current syntax

- jekyll/_cci2/local-jobs.md
> Local env vars

- jekyll/_cci2/configuration-reference.md
As always, I'd love help making this even clearer.
> Clarify the meaning of persist_to_workspace arguments.

- jekyll/_cci2/about-circleci.md
"SSH" isn't really parallel with the others in this list, so moving it out to a separate sentence
> Tweak to language

- jekyll/_cci2/hello-world.md
- jekyll/_cci2/migrating-from-1-2.md
- jekyll/_cci2/sample-config.md
- jekyll/_cci2/workflows.md
this is response to a few pieces of feedback where they want more examples, to the change to make working_directory optional, and to add missing checkout steps in each job.
> Worker checkout examples workflows

- jekyll/_cci2/collect-test-data.md
There is still more content in this doc to go through. Work in progress.
> Test data clarifications

- jekyll/_cci2/configuration-reference.md
It is mislead for workflow document for nested version and jobs.
> Fix workflow version and jobs nest level

- jekyll/_cci2/custom-images.md
> Fix minor typo in custom-images.md

- jekyll/_cci1/fork-pr-builds.md
> Build forked PR defaults to off for everyone

- jekyll/_ccie/single-box.md
change title, add generic instructions, and re-order sections with headings
> Enterprise trial install

- jekyll/_ccie/preview.md
* Add clearer instructions for working with enterprise-setup 
* Document workaround for issue where replicated hangs on initial start
> Update preview installation instructions

- jekyll/_data/trusty/versions-ubuntu-14_04-XXL.json
Merge once https://discuss.circleci.com/t/ubuntu-14-04-build-image-update-201707-02/14737/1 is fully rolled
> Image Update 201707-02

- jekyll/_cci2/caching.md
I found missing space on cache example
> Fix yaml space

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/workflows.md
This point still seems to be causing some confusion.  I'm hoping language change and putting it in bullet form is helpful.
> clarify tags difference from branches

- jekyll/_cci2/collect-test-data.md
see https://github.com/circleci/circleci-docs/issues/1362
> Update gradle test results reporting for 2.0

- jekyll/_cci1/build-image-macos.md
Also update the fact that the default xcode 8.3 is 8.3.3
> Update docs for xcode 9 beta 5

- jekyll/_cci2/migrating-from-1-2.md
- jekyll/_cci2/workflows.md
This update changes the emphasis from flexibility to speed in the overview, simplifies the first example and does some restructuring to simplify the TOC and put some of the features that enable efficiency at the top.
> Improve wf overview

- jekyll/_cci2/workflows.md
> Updating regex

- jekyll/_cci2/workflows.md
This is very minor so will merge on green.
> CIRCLE-5713 - Update YAML comment about workspace

- jekyll/_cci2/sample-config.md
Add more detailed explanation of what a jobs corresponds to.
Expand explanation of the different job executors
> CIRCLE-5713 - Expand jobs overview

- jekyll/_cci2/sample-config.md
Since they're rendered in the UI they look nicer with capitalisation and
spacing.
> CIRCLE-5713 - Command names can be free text

- jekyll/_cci2/index.md
I'm guessing this is the right target. This is just my opinion though.
> CIRCLE-5713 - Parallelism feature should link to parallelism docs

- jekyll/_cci2/project-walkthrough.md
Add a section about service containers (distinct from dependencies)
Expand the dependencies section
Reword the description of caching
> CIRCLE-5713 - Reword some of the project walkthrough for clarity.

- jekyll/_ccie/aws-manual.md
update for editorial clarifications, also I added the prereqs, subnet info and some next steps sections assuming those also apply here, please review for errors and omissions.
> Update instructions for installing CCIE on AWS manually for editorial and structure

- jekyll/_ccie/aws.md
Please review for accuracy and omissions, this is an editorial pass with some restructuring and a new title.
> Improve AWS install instructions for CCIE, editorial and restructuring

- jekyll/_cci2/configuration-reference.md
It might be bold text, not start decoration :)
> Fix broken markdown syntax

- jekyll/_cci2/gh-bb-integration.md
> Minor spelling fix

- jekyll/_cci2/migrating-from-1-2.md
Fixing a minor spelling error in the Overview section
> Fix spelling error

- jekyll/_ccie/backup.md
- jekyll/_ccie/logging.md
- jekyll/_ccie/proxy.md
- jekyll/_ccie/single-box.md
Round of editorial changes for style, grammar and headings
> Enterprise edits for editorial and style

- .circleci/config.yml
Adding workflows to run deployment
> Adding workflows

- jekyll/_cci2/aws-manual.md
- jekyll/_cci2/aws.md
new install doc that merges preview doc with aws doc, definitely need a review of the section about sizing AWS instances
> create aws.md file to start admin install v2

- jekyll/_cci2/env-vars.md
https://github.com/circleci/circleci-docs/issues/1440
> improve warning about secrect in env-vars.md

- jekyll/_cci2/sample-config.md
https://github.com/circleci/circleci-docs/issues/1429
> update sample-config.md with clarification

- jekyll/_cci1/how-cache-works.md
https://github.com/circleci/circleci-docs/issues/1344
> add info about save cache output

- jekyll/_cci2/configuration-reference.md
https://github.com/circleci/circleci-docs/issues/1466
> add link to sample for job map

- jekyll/_cci2/hello-world.md
https://github.com/circleci/circleci-docs/issues/1299
> update hello-world.md with git hook blog and circleci command info

- jekyll/_includes/global-nav.html
see ticket: https://circleci.atlassian.net/browse/MKTG-595
In summary: we needed to sync the nav changes between outer and docs.
> updating nav

- jekyll/_includes/sidebar.html
this indents the menus and adds white space to make the list easier to read
> add margins to docs menu for readability

- jekyll/_cci2/single-box.md
Some of these instructions could definitely be beefed up (or improved with other product options), but this is more accurate for now.
> Some updates to reflect the 2.0 install process

- jekyll/_cci2/configuration-reference.md
> add note about java and erlang to resource class section

- jekyll/_cci2/caching.md
- jekyll/_cci2/configuration-reference.md
update caching & config ref files w/ more detailed info on how to use env vars in cache keys
> Iynere patch 5

- jekyll/_cci2/faq.md
> add some billing questions to faq

- jekyll/_cci1/language-ruby-on-rails.md
Add details on running `bundle install` within the dependencies override
> bundle install override details

- jekyll/_cci2/configuration-reference.md
Letting people know we configure git to use ssh rather than https.
> Information on Checkout step

- jekyll/_cci2/configuration-reference.md
Sample build with service names being used: https://circleci.com/gh/circleci/picard-dummy/620#config/containers/0
> define service name

- jekyll/_includes/global-nav.html
see ticket: https://circleci.atlassian.net/browse/MKTG-622
> updating support section of global nav

- jekyll/_cci2/single-box.md
Some updates to reflect the current state of single-box installs.
> Single box doc updates

- jekyll/_cci2/env-vars.md
from https://github.com/circleci/circleci-docs/pull/1468
> adding note about injected env vars

- jekyll/_cci2/configuration-reference.md
have to do this in a new PR since it was before we added workflows, https://github.com/circleci/circleci-docs/pull/1422
> rebase changes from 1422 for default shell info and incorporate feedback

- jekyll/_cci1/browser-debugging.md
https://github.com/circleci/circleci-docs/pull/1231
> re-do the port swaps from previous old PR

- jekyll/_cci2/project-walkthrough.md
default user has been changed to root
> default user has been changed to root

- jekyll/_cci2/collect-test-data.md
Added an area on how to integrate with Jest.
> Add Jest to collecting metadata documentation.

- jekyll/_cci2/workflows.md
> Fix typo on workflows.md

- jekyll/_cci2/language-php.md
> Make PHP Docker Hub link look better.

- jekyll/_cci2/env-vars.md
I think that these references were stale from 1.0 docs?
> replace circle.yml with config.yml

- jekyll/_cci2/artifacts.md
Update to match API link on the Web UI
> Update to match Web UI

- jekyll/_cci2/overview.md
I fixed that `.circleci/config.yml` seems to be correct.
> /circleci/config.yml → .circleci/config.yml

- jekyll/_cci2/private-images.md
It's useful to know how to pull private images from ECR from the docs page, rather than diving into the blog!
> Ed: adding useful ECR example

- jekyll/_cci2/deployment_integrations.md
- Use DNS host key verification for Heroku deploy. This is the real answer, rather than using whatever host key is presented, Heroku has DNS keys containing the host key.
- Remove `sudo` from the commands that place the heroku CLI. It isn't needed.
- Instead of using a git remote, just use a `git push` command with the URL in it.
- Use SSH to connect to the git repo. There was no reason to set up the SSH key since it wasn't being used with the `https` protocol.
- Since SSH is used to connect, the credentials for `git.heroku.com` are not needed in `.netrc`.
- Force-push to Heroku to ensure that the deployment will occur even if the commit is not a fast-forward of the branch currently deployed to Heroku.
> Heroku deployment fixes

- jekyll/_cci2/env-vars.md
Also, separate & clarify doc for different types of envars:
- job
- image
- run steps
> Add docs about adding envars for a job

- jekyll/_includes/sidebar.html
- jekyll/assets/css/jquery.navgoco.css
- jekyll/assets/css/main.scss
see ticket: https://circleci.atlassian.net/browse/MKTG-646
> aligning sidebar arrows

- jekyll/_cci2/workflows-waiting-status.md
Customer suggested the exact error wording be added to aid it in being found via search
> Added the exact error to aid SEO

- jekyll/_api/v1-reference.md
> remove endpoint

- jekyll/_cci2/high-availability.md
create a proper header for replicated configuration
document using custom CAs
> documents Vault HA configuration

- jekyll/_api/v1-reference.md
- jekyll/_data/api.yml
modeled after adding an SSH key
> Add details for adding a heroku key

- jekyll/_api/v1-reference.md
An alert reader (customer!) wrote in to suggest this clarification.
> add clarification

- jekyll/_cci2/ios-codesigning.md
- jekyll/_cci2/ios-migrating-from-1-2.md
- jekyll/_cci2/ios-tutorial.md
- jekyll/_cci2/testing-ios.md
* Linking to our own code signing doc now that we have it.
* Removing a few things that are no longer relevant.
* Linking to our example project.
> Another pass on iOS docs

- jekyll/_cci2/language-ruby.md
https://circleci.com/gh/CircleCI-Public/circleci-demo-ruby-rails/34
> Catch up language guide for Rails app following demo changes

- jekyll/_includes/global-footer.html
- jekyll/_includes/global-nav.html
See ticket: https://circleci.atlassian.net/browse/MKTG-695
> [MKTG-695] updating nav and footer with recent changes

- jekyll/_cci2/open-source.md
- jekyll/_ccie/open-source.md
Update list based on new dependencies added in 2.0.
> Update open source list

- jekyll/_cci2/configuration-reference.md
https://github.com/circleci/circleci-docs/issues/1779
> fix workflows jobs indentation and add deploy jobs while I'm in there

- jekyll/_cci2/workflows.md
>  Fix YAML Syntax on Orchestrating Workflows Page

- jekyll/_cci2/language-ruby.md
This includes CircleCI-Public/circleci-demo-ruby-rails@8c75638,
CircleCI-Public/circleci-demo-ruby-rails#13 and
CircleCI-Public/circleci-demo-ruby-rails@635c789
> Update Ruby language guide to reflect latest changes from demo app

- jekyll/_cci2/testing-ios.md
> small grammar fix

- jekyll/_cci2/language-ruby.md
Potential resolution for #1891.
> Add context around `dockerize` command

- jekyll/_cci2/about-circleci.md
> Fix typo in title

- jekyll/_includes/global-footer.html
- jekyll/_includes/head.html
- jekyll/_includes/social-buttons.html
- jekyll/assets/css/footer.css
- jekyll/assets/css/main.scss
see ticket: https://circleci.atlassian.net/browse/MKTG-744
> swapping in new footer on docs

- jekyll/_cci2/deployment_integrations.md
Potential improvement for #1879
> Clarify data flow between jobs

- jekyll/_cci2/language-android.md
This PR cleans up wording in the Android language guide in response to #1876
> Document android ndk best practices

- jekyll/_cci2/migrating-from-1-2.md
Fix the issue of redirecting to a wrong web page.
> Fix redirecting to wrong page.

- jekyll/_cci2/configuration-reference.md
> Premium features require an existing paid plan

- jekyll/_cci2/language-android.md
got this: 
./gradlew: Permission deniedExited with code 126
Added the fix, but it's not well done. Maybe you know how to fix it?
> Error fixed

- CONTRIBUTING.md
- README-local-development.md
- STYLE.md
Captures specific style preferences for our documentation.
> add style guide

- jekyll/_cci2/postgres-config.md
https://github.com/circleci/circleci-docs/issues/1936
> update postgres doc with feedback/ticket info

- jekyll/_includes/global-footer.html
See ticket: https://circleci.atlassian.net/browse/MKTG-760
A minor copy change to a link in the footer.
> footer copy change

- jekyll/_includes/global-nav.html
see ticket: https://circleci.atlassian.net/browse/MKTG-729
Adding jobs to the company dropdown in the nav.
> adding jobs to nav

- jekyll/_data/api.yml
> add missing comma

- jekyll/_cci2/language-go.md
Tested in https://github.com/CircleCI-Public/circleci-demo-go/pull/8
> [CIRCLE-7910] Golang Language Guide missing caching

- jekyll/_cci2/demo-apps.md
> New tabs for language guides

- jekyll/_cci1/ios-builds-on-os-x.md
> Correct timeout ordering & clean up files

- jekyll/_includes/v2-banner.html
- jekyll/_includes/v2-dev-banner.html
see ticket: https://circleci.atlassian.net/browse/MKTG-786
> [MKTG-786] updating banner links

- jekyll/_cci2/gh-bb-integration.md
> Remove reference to removed feature

- jekyll/_cci2/language-elixir.md
Updated the Phoenix language guide to be simply an annotated configuration.
> Update elixir language guide

- jekyll/_cci2/aws.md
- jekyll/_ccie/preview.md
OK to remove trailing white space?
> Propose fixing two typos

- jekyll/_cci1/npm-private-module-dependency.md
I kill time solving this undocumented issue
> .npmrc must exist

- CONTRIBUTING.md
CircleCI Documentation Values!
1. **Create** the document.
2. Is it **correct**?
3. Is it **current**?
4. Is it **consistent**?
5. Is it **clear**?
> Add documentation values

- jekyll/_cci1/introduction-to-continuous-deployment.md
https://github.com/circleci/circleci-docs/issues/1020
> chmod +x for executing files

- jekyll/_ccie/custom-ca.md
Fixes #842 Adds note about needing a .crt file first
> Cleans up Custom Root CA Doc

- jekyll/_cci2/status-badges.md
> add note about unrequired API key for FOSS projects

- jekyll/_cci1/google-cloud-platform.md
Fixes #1018 
This was already updated in 2.0 docs, but just wanted to close the loop on the 1.0 version.
> Add missing flag to prevent passphrase prompt

- jekyll/_cci2/language-android.md
> Reword api images in android guide

- jekyll/_cci2/workflows.md
> update workflows example for versions

- jekyll/_cci2/deployment-integrations.md
> Pull functional workflows example into deploys

- jekyll/_cci2/testing-ios.md
Minor language cleanup for #2051
> Add fastlane back to ios

- jekyll/assets/css/main.scss
> Fix blank white line below footer.

- CONTRIBUTING.md
Formalizing rules surfaced in #2061 
- don't use "we"
- don't say "please"
> update style guide

- jekyll/_cci2/deployment-integrations.md
> Move add ssh keys step up

- jekyll/_cci1/language-nodejs.md
> remove dead PaaS

- jekyll/_cci2/deployment-integrations.md
The deploy workflow to heroku is only described by supporting ssh.
What about https? The doc for deploying to heroku do not support https which is even easier 
and do not required so much effort to get the deploy mechanism work like adding a bash script... adding a ssh private key and more..
Instead of that we use one single step that include the heroku api key as well the heroku app name and voilà we get our work deployed to heroku !!
the main step is the following:
```
git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:refs/heads/master
```
the above configuration is tested and it works great!
> Updated deploy config for heroku

- jekyll/_cci2/deployment-integrations.md
> Fix incorrect env var reference

- jekyll/_cci1/oom.md
> ensure consistency in var names

- jekyll/_cci1/skip-a-build.md
> remove [skip ci] tag example

- jekyll/_cci2/deployment-integrations.md
- jekyll/_cci2/google-container-engine.md
Fixes #1580 @eric-hu
Updates title to better reflect content.
> change gce title

- CONTRIBUTING.md
- remove existence of documentation as a value (values should all relate to how we judge the quality of a doc, whether writing a new one or fixing an old one)
- correct typo ("recommendating" lol)
- semantic linefeeds
> update values and style guide

- jekyll/_cci1/yarn.md
> Set NODE_ENV in Yarn 1.0 doc.

- jekyll/_api/v1-reference.md
this was a customer support ticket filed a long time ago
> fix incorrect refernce to username and add 2.0 doc links

- jekyll/_cci2/basics.md
- jekyll/_cci2/skip-build.md
> Add skip build docs to version 2

- jekyll/_cci2/overview.md
Fixes https://github.com/circleci/circleci-docs/issues/2070
> add info about nomad with link to the doc in overview

- jekyll/_cci2/caching.md
couple of jira tickets talk about this
> update caching to make it more clear

- jekyll/_cci2/local-cli.md
Fixes: #2108, circleci/local-cli#3
> Reorder Local CLI install instructions.

- jekyll/_cci1/build-image-macos.md
- jekyll/_cci2/configuration-reference.md
> Add xcode 9.2 docs for 1.0

- jekyll/_cci2/high-uid-error.md
- jekyll/_cci2/reference.md
Full revision of the infamous high UUID error. Fixes #1786 and fixes #1639
> Revise documentation of bad UID remapping error

- jekyll/_cci2/high-uid-error.md
> add link to example image

- jekyll/_includes/global-nav.html
Changed RESTful to JSON in API documentation
> RESTful to JSON

- jekyll/_cci2/tutorials.md
Reverts circleci/circleci-docs#2138
> Revert "adding code to open github in a new window"

- jekyll/_cci2/build-publish-snap-packages.md
Guide on building Snap packages on CircleCI 2.0.
@smart-alek To be clear, unlike that other PR, this one is a brand new Doc so please feel free to scrutinize the language.
Also, I don't know what "category" this belongs in.
> Add guide on building snap packages with CircleCI.

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/executor-types.md
> Update config ref for machine and dlc

- jekyll/_cci2/project-walkthrough.md
Fixes #1334.
Adding @keybits since I think he's the original author of this guide.
> Explicitly mention test runner used in example

- jekyll/_cci2/collect-test-data.md
$CIRCLE_TEST_REPORTS is not used on 2.0
> Remove outdated info

- jekyll/_cci2/build.md
- jekyll/_cci2/yarn.md
> Create Yarn doc for CircleCI 2.0.

- CONTRIBUTING.md
> Add preferred table markdown styling

- jekyll/_cci2/single-box.md
> add note to single box instructions for oauth app URLs

- jekyll/_cci2/ios-codesigning.md
> update ios codesigning with note about changes

- jekyll/_cci2/help-and-support.md
> Add support center link to support page

- jekyll/_cci2/contexts.md
- jekyll/_cci2/env-vars.md
Fixes #2184 and cleans up environment variable section.
> Add explicit inclusion of home env var

- jekyll/_cci2/testing-ios.md
> Add note on reordering UI tests for timeouts

- jekyll/_cci2/high-availability.md
> Update list of required psql databases

- jekyll/_cci2/google-auth.md
- jekyll/_cci2/google-container-engine.md
> Remove breaking component manager

- jekyll/_cci1/continuous-deployment-with-heroku.md
- jekyll/_cci2/about-circleci.md
- jekyll/_cci2/build.md
- jekyll/_cci2/circleci-images.md
- jekyll/_cci2/custom-images.md
- jekyll/_cci2/docker-layer-caching.md
- jekyll/_cci2/index.md
- jekyll/_cci2/test.md
- jekyll/_cci2/tutorials.md
- jekyll/_ccie/quick-start.md
- jekyll/_ccie/single-box.md
- jekyll/assets/css/main.scss
see ticket: https://circleci.atlassian.net/browse/CIRCLE-7059
See blog post for solution: https://css-tricks.com/NetMag/FluidWidthVideo/Article-FluidWidthVideo.php
> [CIRCLE-7059] adding flexible video wrapper to all youtube video embeds on dos

- jekyll/_cci2/browser-testing.md
> Flesh out details of ubuntu window manager

- jekyll/_cci2/deployment-integrations.md
> add link to S3 API docs

- jekyll/_cci2/env-vars.md
> Clarify project level env vars

- jekyll/_cci2/deployment-integrations.md
> migrate NPM deploy example

- jekyll/_cci2/env-vars.md
- jekyll/_cci2/migrating-from-1-2.md
> Revise interpolation workaround

- jekyll/_cci2/ios-tutorial.md
Update xcode version for circle CI to let users to use the recent version.
> Update xcode version

- CONTRIBUTING.md
- add link to style guide in wiki
- remove embedded style guide from CONTRIBUTING.md
> Add link to Style Guide in wiki

- jekyll/_cci2/non-aws.md
+ sundry spelling / grammatical fixes
> Add storage space reqs for services box

- jekyll/_cci2/faq.md
Resolves [this JIRA ticket](https://circleci.atlassian.net/secure/RapidBoard.jspa?rapidView=67&modal=detail&selectedIssue=CIRCLE-4274).
> Usage queue vs run queue

- jekyll/_cci2/test.md
The steps described in the video are complex enough I think it would help to write them out.
Fixes #2259
> Add the steps described in the video

- jekyll/_cci2/basics.md
- jekyll/_cci2/skip-build.md
Resolves [this JIRA ticket](https://circleci.atlassian.net/secure/RapidBoard.jspa?rapidView=67&modal=detail&selectedIssue=CIRCLE-4491).
> Document auto cancellation of redundant builds

- jekyll/_cci2/databases.md
- jekyll/_cci2/examples.md
- jekyll/_cci2/postgres-config.md
- jekyll/_cci2/test.md
> New database doc

- jekyll/_cci2/env-vars.md
Resolves [this JIRA ticket](https://circleci.atlassian.net/secure/RapidBoard.jspa?rapidView=67&modal=detail&selectedIssue=CIRCLE-4364).
> add note about base64 encoding of multiline env vars

- jekyll/_cci2/migrating-cloud-server.md
> Iynere cloud server migration

- jekyll/_cci2/non-aws.md
Adding some clarification about some of the settings that had me perplexed during testing.
Adding a troubleshooting section with information from testing as well.
> Non aws update

- jekyll/_cci2/deployment-integrations.md
On Tuesday, @digitalmaster and @technomancy attempted to deploy to Heroku using our documentation. This PR is a result of their feedback.
Resolves [this JIRA ticket](https://circleci.atlassian.net/secure/RapidBoard.jspa?rapidView=67&modal=detail&selectedIssue=CIRCLE-10297).
> Remove more complex heroku deployment example

- jekyll/_cci2/env-vars.md
Per conversation with @eric-hu, follow-up code example for recent PR re: multiline env vars #2273.
> add example of base64 encoding/decoding

- jekyll/_cci2/project-walkthrough.md
Updates the Project Walkthrough to:
- use the simpler Heroku deploy example
- use Workflows to deploy
**Note that** we will have to update the associated project's config before this PR can be merged. I just wanted to get the review process started on this PR.
This is one of two PRs that will resolve [CIRCLE-10353](https://circleci.atlassian.net/browse/CIRCLE-10353). The other will update the Sample Config document.
> Update project walkthrough heroku example

- jekyll/_cci1/configuration.md
I'm not a native english speaker, but I think the word "creating" was expected here.
> There is no such thing as 'cutting a release'

- jekyll/_cci2/deployment-integrations.md
- jekyll/_cci2/sample-config.md
Resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-11201) and [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-11202).
> simplify heroku deploy command

- jekyll/_cci2/language-python.md
If I new how I would have made a comment instead of editing but there is just one small typo in this really good document.
> Corrected one typo

- jekyll/_cci2/configuration-reference.md
Fixes #2296 and resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-10354).
> add name parameter to both steps

- jekyll/_cci2/executor-types.md
Resolves [CIRCLE-11248](https://circleci.atlassian.net/browse/CIRCLE-11248).
> Add resources to macos

- jekyll/_cci2/deployment-integrations.md
> Add ssh deploy example

- jekyll/_cci2/deployment-integrations.md
Addresses @eric-hu's [comment on a previous PR](https://github.com/circleci/circleci-docs/pull/2341#pullrequestreview-121404868) and fixes #2347.
> Update deployment guide

- jekyll/_cci2/local-cli.md
Minor revision following a recent contribution in #2356.
> clean up copy following contribution

- jekyll/_cci2/faq.md
- jekyll/_cci2/parallelism-faster-jobs.md
- jekyll/_cci2/test.md
A minor PR that clarifies questions around saving and viewing timing data.
Fixes #2327 and resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-11481).
> Clarify timing data requirements and document manual edits

- jekyll/_cci2/gh-bb-integration.md
https://circleci.zendesk.com/agent/tickets/34976
> Bb user key images

- jekyll/_cci2/basics.md
- jekyll/_cci2/writing-yaml.md
New document for writing YAML + documentation of map multi-merging for DRYer configuration files.
Resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-5832).
> Document yaml multi merge

- jekyll/_cci2/api-job-trigger.md
This commit/PR contains specific language addressing issues raised in #2383
> Add notes about jobs being triggered using the API

- jekyll/_cci2/api-job-trigger.md
Follow-up to #2390 and firmly fixes #2383.
> Revise notes on api job trigger example

- jekyll/_cci2/contexts.md
- jekyll/_cci2/databases.md
- jekyll/_cci2/env-vars.md
Tabular data should be tabular!
[JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-11426).
> Reformat builtin env vars as table

- jekyll/_cci2/api-job-trigger.md
__Why was this PR made__ To clarify that the API call can be made against any branch, not just `master`
This PR is in reference to this documentation page: https://circleci.com/docs/2.0/api-job-trigger/
> Update the curl command template

- jekyll/_cci2/env-vars.md
DEJA VU!
Resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-11866).
> clarify that 3 env vars are only for forked PRs

- jekyll/_cci2/api-job-trigger.md
Small fix as a follow-up for #2390. Resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-11727)
> distinguish between different API tokens

- jekyll/_cci2/caching.md
There were a few ambiguous/unclear pieces of the caching documentation.
Fixes #2415 and resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-11849)
> Clarify ambiguities in caching doc

- jekyll/_cci2/language-php.md
Added a couple of comments that explain how restore_cache works. Also comments reference relevant CircleCI page on caching.
> Add comments to explain restore_cache better

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/docker-layer-caching.md
> Dlc update

- jekyll/_cci2/caching.md
Resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-11490).
This PR attempts to document how different dependency managers deal with partial cache restoration. I have almost certainly muddled a few things up in here, so I'm counting on both @eddiewebb and @michelle-luna to catch me where that's happened!.
> Update caching best practices for specific dependency managers

- jekyll/_cci2/workflows-waiting-status.md
Capitalizing these consistently.
> Github -> GitHub

- jekyll/_cci2/help-and-support.md
Updating the removal of elev.io
> Update for new support location

- jekyll/_cci2/artifactory.md
- jekyll/_cci2/test.md
Adds basic config.yml and setup for artifactory.
Adding on 1.0 docs I added links to artifactory's guides for Maven and Gradle tools which simply setup
> porting artifactory from 1.0 docs

- jekyll/_cci2/monitoring.md
- jekyll/_ccie/logging.md
Adding LogDNA into the List of Logging Providers
> Adding LogDNA into the List of Logging Providers

- pull_request_template.md
Brief description of changes
This meta PR updates the PR template to match the formatting of the issue templates. There are section headings, a sample of **what** should go in each section, and a distinction between "Reasons" and "Context from a GitHub/JIRA issue".
> small quality of life improvement for PR template

- jekyll/_cci1/configuration.md
- jekyll/_includes/v2-dev-banner.html
> Config ref update

- jekyll/_cci2/certificates.md
THis updates the certificates.md docs page to update it to work with latest server install, and fix confusing layout.
1. Certbot steps and CircleCI specifi steps were intermingled
1. Referenced "dummy certs" but certificates actually need to be valid or containers will fail to start
1.  Adds an approach for "self-signed" certs for folks that doent want to use certbot.
> fixes inaccuracies and layout issues in certificates.md

- jekyll/_cci2/deployment-integrations.md
CF: quote username, password, organization name and space name as these can have spaces or special characters
> cf: add quotes

- jekyll/_cci2/project-build.md
> Project build page

- jekyll/_cci2/building-docker-images.md
> fixed typo in currently

- jekyll/_cci2/migration-intro.md
- jekyll/_cci2/migration.md
Add some feedback from Joe/Katie to migration pages
Migration support issue and redesign prep
> Migration improvements

- jekyll/_cci2/migrating-from-jenkins.md
Fix spelling of word from `anbd` -> `and`
> Fix typo in documentation

- jekyll/_api/v1-reference.md
- jekyll/_cci2/api-job-trigger.md
- jekyll/_cci2/build-processing.md
- jekyll/_cci2/faq.md
- jekyll/_cci2/workflows.md
- jekyll/_data/api.yml
new doc for build processing and updates to API docs
we have this feature in the UI as a preview and customers will get support for triggering builds with API using the new endpoint
https://circleci.atlassian.net/browse/CIRCLE-12607
> New endpoint for trigger workflows

- jekyll/_cci2/configuration-reference.md
Fix typo on configuration reference page.
> Fix typo on configuration reference page

- jekyll/_cci2/building-docker-images.md
- jekyll/_cci2/docker-layer-caching.md
update remote docker and dlc limitations 
requests from support and solutions
CIRCLE-13007
> Support fixes docker dlc

- jekyll/_cci2/build-processing.md
- jekyll/_cci2/faq.md
- jekyll/_cci2/skip-build.md
add auto-cancel info for workflows
feature landed today
https://circleci.atlassian.net/browse/CIRCLE-12753
> Auto cancel wf draft

- jekyll/_cci2/about-circleci.md
replace video with image, remove use cases
usability study
> Update about page

- jekyll/_cci2/concepts.md
- jekyll/_cci2/examples-intro.md
> Redesign landing pages

- jekyll/_cci2/adv-config.md
- jekyll/_cci2/deployment.md
- jekyll/_cci2/executor-intro.md
- jekyll/_cci2/optimizations.md
- jekyll/_cci2/settings.md
- jekyll/_cci2/triggers.md
redesign landing pages
usability study feedback
> Landing pages redesign

- jekyll/_cci2/gh-bb-integration.md
Clarifies the machine user section of the docs.
Fixes #2568 and resolves [this JIRA issue](https://circleci.atlassian.net/browse/CIRCLE-12935).
> Clarify machine user usage

- jekyll/_cci2/index.md
> Update 2.0 index for redesign

- jekyll/_cci2/index.md
- jekyll/index.html
> Fix more links

- jekyll/_cci2/caching.md
- jekyll/_cci2/collect-test-data.md
- jekyll/_cci2/concepts.md
- jekyll/_cci2/config-intro.md
- jekyll/_cci2/docker-compose.md
- jekyll/_cci2/first-steps.md
- jekyll/_cci2/hello-world.md
fix up the tocs and links
redesign
> Michelle luna patch 2

- jekyll/_cci2/ios-codesigning.md
- jekyll/_cci2/ios-migrating-from-1-2.md
- jekyll/_cci2/ios-tutorial.md
- jekyll/_cci2/java-oom.md
- jekyll/_cci2/jobs-steps.md
- jekyll/_cci2/language-android.md
- jekyll/_cci2/language-clojure.md
- jekyll/_cci2/language-elixir.md
- jekyll/_cci2/language-go.md
- jekyll/_cci2/language-java.md
- jekyll/_cci2/language-javascript.md
- jekyll/_cci2/language-php.md
- jekyll/_cci2/language-python.md
- jekyll/_cci2/language-ruby.md
- jekyll/_cci2/language-scala.md
- jekyll/_cci2/local-cli.md
- jekyll/_cci2/migrating-cloud-server.md
- jekyll/_cci2/migrating-from-1-2.md
- jekyll/_cci2/migrating-from-jenkins.md
- jekyll/_cci2/notifications.md
- jekyll/_cci2/optimizations.md
- jekyll/_cci2/oss.md
> Remove breadcrumbs paredown tocs

- jekyll/_sass/_sidebar.scss
- jekyll/assets/css/main.scss
- jekyll/assets/js/sidebar.js
fixing an issue with the new sidebar, where when a screen was larger than the content, the sidebar didn't render properly. Addressed minor style issues.
Things were broken.
https://circleci.atlassian.net/browse/CIRCLE-12374
https://circleci.atlassian.net/browse/CIRCLE-13371
> fixing sidebar error on large screens; fixing link color

- jekyll/_cci2/index.md
- jekyll/index.html
> Fix welcome table

- jekyll/_cci2/artifactory.md
- jekyll/_cci2/artifacts.md
- jekyll/_cci2/browser-testing.md
- jekyll/_cci2/deployment-integrations.md
- jekyll/_cci2/parallelism-faster-jobs.md
- jekyll/_cci2/postgres-config.md
- jekyll/_cci2/private-images.md
- jekyll/_cci2/project-build.md
- jekyll/_cci2/project-walkthrough.md
- jekyll/_data/sidenav.yml
updates for the redesign cleanup
> Remove breadcrumbs fix tocs

- jekyll/_cci2/demo-apps.md
- jekyll/_cci2/project-build.md
- jekyll/_cci2/sample-config.md
- jekyll/_cci2/security.md
- jekyll/_cci2/settings.md
- jekyll/_cci2/skip-build.md
- jekyll/_cci2/ssh-access-jobs.md
- jekyll/_cci2/status-badges.md
- jekyll/_cci2/testing-ios.md
- jekyll/_cci2/triggers.md
- jekyll/_cci2/tutorials.md
- jekyll/_cci2/using-shell-scripts.md
- jekyll/_cci2/workflows.md
- jekyll/_cci2/writing-yaml.md
- jekyll/_cci2/yarn.md
> Fix type add see also remove breadcrumbs

- jekyll/_data/sidenav.yml
> Add build proc to nav

- jekyll/_includes/head.html
- jekyll/_includes/header.html
The new archive pages needed to be noindexed/nofollowed; this PR addresses that.
> no-indexing archive pages; removing useless noindex

- jekyll/_archive/trusty-image.html
- jekyll/_cci1/trusty-image.html
these were missed when I removed old files from the sitemap
https://circleci.atlassian.net/browse/CIRCLE-13545
> Minor fix to sitemap

- jekyll/_cci2/admin-faq.md
- jekyll/_cci2/proxy.md
change builders to nomad clients
Fixes #2613
> Builders to nomad clients edits

- jekyll/_cci2/upgrading.md
Reverts circleci/circleci-docs#2741
> Revert "Update upgrading.md"

- jekyll/_cci2/configuration-reference.md
> Fix typos in configuration-reference.md

- jekyll/_config_production.yml
I made a copy paste oopsie in https://github.com/circleci/circleci-docs/pull/2744 😅
> fix rollbar production env

- jekyll/_cci2/demo-apps.md
> fix android guide link

- jekyll/_ccie/aws-manual.md
- jekyll/_ccie/aws-private-subnet.md
- jekyll/_ccie/aws.md
- jekyll/_ccie/backup.md
- jekyll/_ccie/cloudwatch.md
- jekyll/_ccie/config.md
- jekyll/_ccie/custom-ca.md
- jekyll/_ccie/debugging-replicated.md
- jekyll/_ccie/differences.md
- jekyll/_ccie/docker-builder-config.md
- jekyll/_ccie/docker-install.md
- jekyll/_ccie/docker.md
- jekyll/_ccie/export-import-projects.md
- jekyll/_ccie/failover.md
- jekyll/_ccie/faq.md
- jekyll/_ccie/gpu-configuration.md
- jekyll/_ccie/high-availability.md
> Sitemap work for ccie

- jekyll/_ccie/ios-install.md
- jekyll/_ccie/logging.md
- jekyll/_ccie/on-prem.md
- jekyll/_ccie/open-source.md
- jekyll/_ccie/overview.md
- jekyll/_ccie/preview.md
- jekyll/_ccie/proxy.md
- jekyll/_ccie/quick-start.md
- jekyll/_ccie/security.md
- jekyll/_ccie/self-signed.md
- jekyll/_ccie/single-box.md
- jekyll/_ccie/strategic_value.md
- jekyll/_ccie/troubleshooting-install.md
- jekyll/_ccie/upgrade-for-1.46.x-and-earlier.md
- jekyll/_ccie/upgrade-to-GA.md
- jekyll/_ccie/whycci.md
> More ccie sitemap work

- jekyll/_cci2/configuration-reference.md
There is clearly a word missing here; I've guessed what it is from context and added it in.
* add `of`
* increase clarity
> add word to clarify meaning

- jekyll/_cci2/monitoring.md
> lint and typos for monitoring

- jekyll/_cci2/update-2.14.1-to-2.15.0.md
> Mongo recommended reword

- jekyll/_config.yml
We were missing some settings from our search index config.
> Update Algolia index search config

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/workflows.md
> Tags clarification

- jekyll/_cci2/circleci-images.md
> Typo (availables -> available)

- .circleci/config.yml
- .gitignore
Reverts circleci/circleci-docs#2856
> Revert "[CIRCLE-14271] Automate algolia"

- jekyll/_cci2/reusing-config.md
Add executor and integer parameter types and rearrange a bit to clarify that scoping is not part of the types section
New types available and moved scoping out of the Types section.
> Add executor and integer parameter types and rearrange a bit

- jekyll/_cci2/configuration-reference.md
Reverting #2864  until the pertinent source lands for #2867. 
@johnswanson I'll come back and add the original content you posted after shipping!
> Revert 2864

- jekyll/_cci2/hello-world.md
- jekyll/_cci2/using-orbs.md
update hello-world and add link to other orb docs
> Fix hello world sections

- jekyll/_cci2/testing-ios.md
update supported Xcode version list to include 10.1.0
> Xcode 10.1.0 update

- jekyll/_cci2/creating-orbs.md
> fix typo in creating orbs doc

- jekyll/_cci2/api-job-trigger.md
Fixed a few minor typos in the api-trigger-job content
> Fixed typos in api-job-trigger content

- jekyll/_cci2/jvm-heap-size-configuration.md
> draft update for contexts service customization

- .gitignore
- jekyll/_sass/_instantsearch.scss
- jekyll/_sass/_sidebar.scss
- jekyll/assets/css/main.scss
Make sidebar background color stretch to the left edge of the page.
Design improvement
> Sidebar Design Tweaks

- jekyll/_cci2/index.md
- jekyll/_includes/edit-on-github.html
- jekyll/_sass/_sidebar.scss
- jekyll/assets/css/fonts.css
- jekyll/assets/css/main.scss
- jekyll/index.html
- Improving layout for home page
- Improving layout spacing for home page and article pages
- Eliminating obvious spacing issues
> Improving Layout Spacing

- jekyll/_cci2/browser-testing.md
> typo in browser-testing doc

- jekyll/_cci2/using-orbs.md
> using-orbs.md: Fix minor typo

- jekyll/_cci2/orbs-faq.md
Added a note to content that private installations of CircleCI are not currently supported for orbs. Fixes #2961
> Updated orbs-faq.md content

- jekyll/_cci2/api-job-trigger.md
> api-job-trigger: Fix minor typo

- jekyll/_cci2/migration.md
Markdown typo, please, correct
> Update migration.md (noticed typo)

- jekyll/_cci2/archive.md
- jekyll/_data/sidenav.yml
> add enterprise 1.0 doc links to archive

- jekyll/_cci2/orb-intro.md
Update the page to include the four new partners launched in December
> update partner orb list on orb-intro page

- jekyll/_cci2/build-processing.md
- jekyll/_includes/global-nav.html
Updating link to ideas portal from circleci.com/ideas/ to https://ideas.circleci.com/
> [CIRCLE-15565] Changing ideas portal link

- jekyll/_includes/global-footer.html
- jekyll/_includes/global-nav.html
**Ticket:** [CIRCLE-15093](https://circleci.atlassian.net/browse/CIRCLE-15093)
* Adding link to main nav and mobile nav for the partners page
* Updating footer partners link copy
> [CIRCLE-15093] updating/adding partner links in nav

- src-js/instantsearch.js
First pass of fix for xss on docs page
https://circleci.atlassian.net/browse/CIRCLE-15694
> Minimum fix to not put the search box as innerText not innerHtml

- jekyll/_cci2/features.md
- jekyll/_data/sidenav.yml
> Add features doc

- jekyll/_cci2_ja/getting-started.md
Translating https://circleci.com/docs/2.0/getting-started/
> Translate getting-started guide

- src-js/app.js
A no-op change to verify that changes we make to webpack-compiled JS make their way into the production JS files.
See [CIRCLE-15698](https://circleci.atlassian.net/browse/CIRCLE-15698)
> [CIRCLE-15698] Dummy change to test webpack build

- src-js/app.js
Remove the dummy code I added to test CIRCLE-15698.
> [CIRCLE-15698] Remove temp change

- jekyll/_cci2/migrating-from-jenkins.md
> remove old image

- jekyll/_cci2/ecs-ecr.md
persist_to_workspace step is missing "-"
I ran into issues after copy-pasting this
> cci2 ecs-ecr fix step formatting

- jekyll/_cci2/oss.md
- Angular was listed 2x
- Pandas no longer using CircleCI
> Cleanup OSS Project listing

- jekyll/_cci2/deployment-integrations.md
Found some links on this page that weren't being rendered correctly. Fixed the markdown for said links.
Who wants broken links?
> Fix markdown link issues

- jekyll/_cci2/workflows.md
add info about troubleshooting failed reruns of workflows after an outage
https://circleci.atlassian.net/browse/CIRCLE-14433
> Build processing error ts info

- jekyll/_cci2/triggers.md
> add example of triggering docker remotely.

- jekyll/_cci2_ja/getting-started.md
> Translation update

- jekyll/_cci2/build-publish-snap-packages.md
Adds a note on the expiration time of Snapcraft login files.
Also fixes the Markdown for the ordered list.
> Add note about Snapcraft login.

- jekyll/_cci2/about-circleci.md
- jekyll/_cci2/contexts.md
- jekyll/_cci2/hello-world.md
fixes #3080 
this also addresses some customer request for info about jobs and containers in the overvie and hello world docs
> Add info to contexts and overview

- jekyll/_cci2/help-and-support.md
Change the wording to not gate on paid plans
We allow a non-paid customer to open tickets, this changes the wording to reflect that.
> Change wording to remove paid requirement

- jekyll/_cci2/caching.md
> Rename cache expiry section; move up in document.

- jekyll/_cci2/collect-test-data.md
Relevant thread:  https://circleci.slack.com/archives/C0KBNJGRH/p1552635155012900
> Discourage use of hidden folders for store_test_results.

- jekyll/_cci2/testing-ios.md
Make it more clear how Ruby versions should be installed on macOS.
Fixes #3135
> Improve Ruby docs

- jekyll/_cci2/configuration-reference.md
> I got the new image tag slightly wrong

- jekyll/_cci2/creating-orbs.md
> Fix typo in creating-orbs.md

- jekyll/_cci2/migrating-from-travis.md
I done hecked it the first time and forgot to include a line break. This should fix it.
> Fixing table formatting, for real this time

- jekyll/_data/sidenav.yml
> add jira plugin to navigation menu

- jekyll/_cci2/contexts.md
> Minor updates

- jekyll/_cci2/ecs-ecr.md
> Fix links of the bottom of ecs-ecr.md

- jekyll/_cci2/contexts.md
- Updated to make it clear that anyone can add a context but only admins can restrict them
- Changed `workflows` to `job` to reduce confusion.
> Minor update

- jekyll/_cci2/testing-ios.md
https://discuss.circleci.com/t/when-can-we-expect-the-final-xcode-10-2-image-to-be-released/29261/39?u=drazisil
Updating xcode build id
Updating docs
> Updating xcode build id

- jekyll/_cci2/executor-types.md
Pertinent [discussion](https://circleci.slack.com/archives/C0KBNJGRH/p1555514865018100)
> Indicate ability to run multiple DBs in docker.

- jekyll/_cci2/caching.md
I think we want UID here. https://en.wikipedia.org/wiki/User_identifier
> UUID and UID are different things

- jekyll/_includes/global-nav.html
> fix api link in nav

- jekyll/_cci2/testing-ios.md
Add Xcode 10.2.1 image to the docs.
> Add Xcode 10.2.1 image to the docs

- jekyll/_cci2/high-uid-error.md
Simple fix, there's a cute joke about dreams or something here, too!
> Change imagine to image

- jekyll/_api/v1-reference.md
> remove from sitemap

- src-api/source/includes/_builds_and_jobs.md
Fix typo:
View fixed section [here](https://45567-48750547-gh.circle-artifacts.com/0/circleci-docs/api/index.html#trigger-a-new-build-by-project-preview)
> Update _builds_and_jobs.md to fix typo.

- jekyll/_cci2/ssh-access-jobs.md
> Fix wording on ssh connection durations.

- jekyll/_cci2/orb-intro.md
In addition to April and May, I also updated the new orb link for Datree
MKTG-1137
Each month we launch a few new orbs and need to keep this page updated.
> Added April and May orbs

- jekyll/_cci2/orb-intro.md
Changed "AWS EKS" to "Amazon EKS"
> Updated Amazon

- jekyll/_cci2/env-vars.md
> add info about restricted contexts to env vars doc

- jekyll/_cci2/reusing-config.md
> remove incorrect example from re-using config

- jekyll/_cci2/deployment-integrations.md
> add link and info about heroku CI option to deployment doc

- jekyll/_cci2/browser-testing.md
> Added LambdaTest CircleCI Orb

- jekyll/_cci2/workflows.md
Reverts circleci/circleci-docs#3286
> Revert "Update workflows.md"

- jekyll/_cci2/deployment-integrations.md
Improved the npm publish script with the npm set command.
Just a minor improvement and looks cleaner than using echo.
> Improve npm publish script with npm set command

- jekyll/_cci2/optimizations.md
Provide commentary and clarification on some of the optimizations
Add links to other CircleCI documentation
Reviewing document for clarity and completeness from a customer engineering perspective
> Add clarifying sentences

- jekyll/_cci2/workflows.md
> remove 2.1 from example

- jekyll/_cci2/hello-world-macos.md
- jekyll/_cci2/ios-tutorial.md
- jekyll/_cci2/testing-ios.md
Link iOS / macOS docs for better discoverability.
> Interlink iOS docs.

- jekyll/_cci2/containers.md
- jekyll/_cci2/ssh-access-jobs.md
I noticed this section said "VCS system" and the S stands for System. Changed this and a couple of other minor language changes for clarity.
> expand VCS

- jekyll/_cci2/executor-types.md
Direct users to the xcode versions page for more information.
Update language about "installed software" links. 
customer feedback
https://circleci.zendesk.com/agent/tickets/52577
> update macos executor

- jekyll/_cci2/gh-bb-integration.md
> specify bb cloud

- jekyll/_cci2/notifications.md
> Add notification orbs.

- jekyll/_cci2/high-uid-error.md
> add see also link

- jekyll/_cci2/monitoring.md
The link doesn't exist anymore.
> Fix nomad telemetry broken link

- jekyll/_cci2/faq.md
A quick note letting folks know that we have early access for Windows.
> Add Windows Early Access details to the FAQ

- jekyll/_cci2/optimizations.md
I got some more feedback from Will's team and have added the changes here.
> Optimization doc - Consistent language and requested feedback 

- jekyll/_cci2/orb-intro.md
Added Honeycomb and Pantheon for June launch
@michelle-luna
> Added Honeycomb and Pantheon

- jekyll/_data/sidenav.yml
this moves each landing page underneath the ALL CAPS heading 
5 folks said they never clicked the ALL CAPS headings (so they missed this content for a long time)
> update sidenav to make landing pages more obvious

- jekyll/_cci2/orb-intro.md
Added Styra, Provar and CodeScene
@michelle-luna please review this pull request for the last of our June partners
> Added Styra, Provar and CodeScene

- jekyll/_cci2/circleci-images.md
> Fix broken URL

- jekyll/_cci2/workflows-overview.md
- jekyll/_cci2/workflows.md
> Capitalization fix

- jekyll/_cci2_ja/testing-ios.md
Updating to the latest translation.
> Update Ja translation

- jekyll/_cci2/configuration-reference.md
Added missing `version` key to `setup_remote_docker`.
> Add version key to setup_remote_docker in configuration reference.

- jekyll/_cci2/adv-config.md
Added from [this thread](https://circleci.slack.com/archives/C0KBNJGRH/p1561452821115000).
> Update advanced config with new tips.

- package-lock.json
> fix security issue

- jekyll/_cci2/testing-ios.md
We are updating Xcode 11 from beta 2 to 3
> Xcode 11 Beta 3

- jekyll/_cci2/ios-codesigning.md
> Link to post re: signing ios without fastlane match.

- jekyll/_cci2/jobs-steps.md
- jekyll/_cci2/reusing-config.md
> Add comments to partial orb examples.

- jekyll/_cci2/workflows.md
Include some of the information from #3506 in the workflows document.
> Add advanced config tips to workflows document.

- jekyll/_cci2/building-docker-images.md
> Update instructions for correct docker cli login.

- package-lock.json
A contributor's pull request (#3537) seems to be [failing](https://circleci.com/gh/circleci/circleci-docs/46674) because we have a dependency vulnerability (or 100). I ran an NPM audit + fix so hopefully that will resolve allowing people to contribute.
> Audit/Fix NPM dependencies 

- jekyll/_cci2/about-circleci.md
- jekyll/_cci2/add-ssh-key.md
- jekyll/_cci2/api-job-trigger.md
- jekyll/_cci2/circleci-images.md
- jekyll/_cci2/concepts.md
Addressing survey feedback
requests from folks filling out the docs survey
> Update about page with simple ov and benefits

- jekyll/_cci2/reusing-config.md
updating with additional information based on twitter post and customer survey comments
customer feedback
> attempt to clarify special keys, conditionals, and env_var_name example

- jekyll/_cci2/tutorials.md
update heading from sample apps to sample projects
request from growth team to match their new on-screen text
> Update tutorials.md section heading for onboarding
