- jekyll/_cci2/hello-world-windows.md
A "hello world" document introducing user's to building with windows, similar to our [hello world](https://circleci.com/docs/2.0/hello-world/) document and [hello world on mac os](https://circleci.com/docs/2.0/hello-world-macos/) document.
This document runs alongside a companion [sample-app](https://github.com/CircleCI-Public/circleci-demo-windows).
> "Hello World" with Windows

- jekyll/_cci2/ecs-ecr.md
> Fix ecr version.

- jekyll/_cci2/gh-bb-integration.md
> fix typo in github/bitbucket integration

- jekyll/_cci2/v.2.17-overview.md
- jekyll/_data/sidenav.yml
Add rollback instructions to new server version overview steps (with a view to putting this in the install guide too)
> make separate what's new section for releases, add snapshot instructions

- jekyll/_cci2/orb-author-cli.md
- jekyll/_cci2/orb-author-cli.md (WIP)
> Create orb-author-cli.md (WIP)

- jekyll/_cci2/hello-world-windows.md
[jira 19964](https://circleci.atlassian.net/browse/CIRCLE-19964?atlOrigin=eyJpIjoiYTY4OWNlYTFiZGQyNGNjMGEyMGIwNWUxNTEzODhlNmYiLCJwIjoiaiJ9)
> update windows orb name/version

- jekyll/_cci2/hello-world-windows.md
- jekyll/_data/sidenav.yml
- add extra information to `Overview` section
- _blocked_: including the entire list of available software on windows executors in coming release.
> Add extra information about shell availability + windows details

- jekyll/_cci2/about-circleci.md
- jekyll/_cci2/demo-apps.md
- jekyll/_cci2/hello-world-windows.md
- jekyll/_cci2/tutorials.md
add windows links / refs to a few additional files
> Michelle luna patch 4

- jekyll/_cci2/hello-world-windows.md
This is to notify customers about any open issues they might hit when trying out Windows.
> Add a Known Issues section to the Windows doc

- jekyll/_cci2/demo-apps.md
- jekyll/_cci2/tutorials.md
> Add maven doc links

- jekyll/_cci2/executor-intro.md
Missed adding Windows to this doc 😓 .
> Update Executors Intro to include windows + add additional "see also" links.

- jekyll/_cci2/building-docker-images.md
> Fixed DOCKER_USER env var

- jekyll/_cci2/artifacts.md
> Update fetching artifact description.

- jekyll/_cci2/hello-world.md
improve hello world with examples and links, move orbs down based on customer feedback
got a few complaints about this document not being good enough
> Michelle luna patch 5

- jekyll/_cci2/aws-manual.md
- jekyll/_cci2/aws.md
- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/proxy.md
Changed all refs to black/whitelist to block(ed)/allow(ed)... Seems to read OK but happy to use an alternative if people agree on one :-)
> replace white/black list with block/allow

- jekyll/_cci2/config-intro.md
> Bump `version` key examples to 2.1

- jekyll/_cci2/faq.md
Request to update what constitutes an active user; I wasn't sure if this should be added to the list or the sentence introducing the list — happy to change or leave it either way!
> Update what constitutes an active user.

- jekyll/_cci2/gh-bb-integration.md
fixes #3530  add info about keys best practices
customer request for details
> update gh-bb-integration doc

- jekyll/_data/sidenav.yml
> Fix broken install PDF link

- jekyll/_data/sidenav.yml
> Formatting of PDF section in sidenav

- jekyll/_cci2/orb-intro.md
Notes:
- Please confirm Alcideio has right namespace
- Updated AWS, Azure, and GCP multiple orbs. Please confirm they are entered properly
- Whitesource has two orbs, please confirm the way I entered them is okay
> Updated partner orbs

- src-js/instantsearch.js
Remove autofocus on page load.
> Disable autofocus on algolia searchbox.

- src-js/instantsearch.js
Reverts circleci/circleci-docs#3680
> Revert "Disable autofocus on algolia searchbox."

- jekyll/_cci2/server-ports.adoc
> Fixing a minor typo

- jekyll/assets/js/sidebar.js
We are getting a bunch of [Rollbar exceptions](https://rollbar.com/circle/circleci-docs/items/206/) [in code that expands and collapses the sidebar](https://github.com/circleci/circleci-docs/blob/master/jekyll/assets/js/sidebar.js#L22). Users have also reported other similar bugs with the sidebar, so this is the first attempt at fixing them.
https://circleci.atlassian.net/browse/CIRCLE-20824
> CIRCLE-20824 Fix a Sidebar Bug

- jekyll/_cci2/contexts.md
Found this while improving the security.md doc.
> Fix typo in Contexts doc.

- jekyll/_cci2/hello-world-windows.md
> Include NVM in available windows software

- jekyll/_cci2/configuration-reference.md
Hide currently-unavailable resource classes from config reference.
> hide resource classes

- Gemfile
This latest beta update allows adding a comment to the front cover of the PDFs: Draft, Final, Ready for Review etc :-)
> update asciidoc pdf version to beta 5

- .circleci/config.yml
- widdershins.apiv2.yml
**Best reviewed commit-by-commit.**
Navigate to [the first commit](https://github.com/circleci/circleci-docs/pull/3757/commits/6c74ee5548b7444de76392dcde993272d5a662a3) and use <kbd>n</kbd> (next commit) and <kbd>p</kbd> (previous commit) to navigate.
Please review each commit's *message* as well. Each message should clearly describe the motivation for the change.
> Move Widdershins configuration to file

- widdershins.apiv2.yml
This is to tie into https://github.com/circleci/circle/pull/10249 and make it show up nicely on the docs
> added tag groups on v2 preview docs

- jekyll/_cci2/env-vars.md
> Fix a link

- jekyll/_cci2/security.md
We've been discussing / have had a request for providing user's with a checklist of how they can properly ensure they are using the platform securely. I've sourced a few points (thanks @glenjamin  and @mvxt) and am putting this up for consideration. All feedback / input appreciated.
> Add a User Security "Checklist" to Security document.

- jekyll/_cci2/configuration-reference.md
Reverts circleci/circleci-docs#3755
> Revert "hide resource classes"

- jekyll/_cci2/monitoring.adoc
PR for just changes to monitoring/metrics guide for 2.18
> [WIP]2.18/custom metrics

- jekyll/_data/sidenav.yml
Move best practices under side bar to orb authors.
> Move best practices under side bar to orb authors.

- jekyll/_cci2/orb-intro.md
Minor typo
barely noticeable, but hopefully it helps
> duplicate "to"

- jekyll/_cci2/orb-author-faq.md
- jekyll/_cci2/orbs-faq.md
- jekyll/_data/sidenav.yml
Proposal to add FAQ section for orb authors. This content has not yet been reviewed by the rest of the CPE team, requesting reviews via this PR which may result in changes. 
Do not merge until all reviewers have signed off.
Please review the included content and discuss any thoughts below.
To mirror our existing FAQ for users, this is a similar help doc for authors. This page also compliments our best practices doc.
> Orb author FAQ page

- jekyll/_cci2/orb-author-faq.md
> minor grammatical changes.

- jekyll/_cci2/orb-intro.md
Removed CryptoMove
Added ConfigCat, Cloudsmith, Fairwinds, F0cal, Quali, Packtracker, Sumo Logic, and Neocortix
> Added September Partners

- package.json
Updates the dependencies to match the latest working package versions.
The versions of a few dependencies had vulnerabilities and issues. The newer versions include bugfixes and improvements.
> Updates dependencies to latest package versions.

- package.json
Reverts circleci/circleci-docs#3799
> Revert "Updates dependencies to latest package versions."

- jekyll/_cci2/configuration-reference.md
Highlighting how to run a job for all branches after the following survey feedback for this section: "trying to configure how to run for all branches. it shouldn't be this difficult." :-)
> include how to run a job for all branches

- jekyll/_cci2/faq.md
ticket: [JIRA 20226](https://circleci.atlassian.net/browse/CIRCLE-20226?utm_medium=referral-external&utm_source=jira-slack&utm_term=)
> Update to new refill percentages for credit billing

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/orb-author-intro.md
- jekyll/_cci2/orb-author-validate-publish.md
Noticed a couple tables that didn't have the class set, so they weren't showing up like the others.
See above
> Fix tables that weren't formatted like others

- jekyll/_cci2/sample-config.md
Add clear link to config reference after this survey response: "No - no documentation for each config variable"
> Update sample config

- jekyll/_cci2/faq.md
request to add info from sales and product for legacy customers
> add question to faq for macOS container overages

- jekyll/_cci2/env-vars.md
A small word misspelling fix.
I think it's the right thing to do.
> Fix typo of the word "paramater"

- README-local-development.md
Added redirect link to the Ruby website to download the latest ruby version available
> added ruby link

- jekyll/_cci2/jobs-steps.md
- jekyll/_cci2/using-orbs.md
Improve linking between orbs sections, in response to survey comment: "How do I create an orb...where is that. It's not obvious"
> add some internal links to improve orbs visibility

- jekyll/_cci2/testing-ios.md
Also add the version of macOS to each item in the table.
> Add Xcode 11.2 Docs

- README-local-development.md
- WIDGETS.md
Fix "group" to "grouped" in documentation file WIDGETS.md
Improve clarity
> Fix typo on WIDGETS.md

- jekyll/_cci2/orbs-best-practices.md
add usage example docs link to orbs best practices
> add usage example docs link to orbs best practices

- jekyll/_cci2/credits.md
- jekyll/_cci2/faq.md
Align oss credit details with main site. Related: https://github.com/circleci/circleci.com/pull/2927
> Make requested credit updates.

- jekyll/_data/sidenav.yml
> Add viewing pipelines to sidenav.

- widdershins.apiv2.yml
added `(preview)` to the autogen categories to make it super clear that these endpoints are in preview
> added `(preview)` to the autogen categories

- jekyll/_cci2/user-accounts.adoc
Ensures that the availability of user management features is made clearer.
A user was confused about the availability of the user management feature within server and assumed it was also available in cloud. This helps clarify this availability.
> Ensure availability of user management feature is clear

- jekyll/_data/sidenav.yml
> Improve visibility of CircleCI Overview

- jekyll/_cci2/using-orbs.md
> clarified orb publish permissions

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/customizations.adoc
- jekyll/_cci2/executor-intro.md
- jekyll/_cci2/executor-types.md
- jekyll/_cci2/monitoring.adoc
- jekyll/_cci2/optimizations.md
- jekyll/_cci2/orb-intro.md
- jekyll/_cci2/vm-service.adoc
* Add in notes to show at which version features were introduced
* Add some notes to clarify where usage in Server is different to Cloud
> Server feature versioning and availability 

- jekyll/assets/css/main.scss
Fixes the alignment of the codetabs.
> Fix codetab widget margin.

- jekyll/_cci2/testing-ios.md
> Add Xcode 11.2.1

- jekyll/_cci2/nomad-metrics.adoc
- jekyll/_cci2/v.2.18-overview.md
> add nomad metrics timing info

- jekyll/_cci2/updating-server.adoc
* Fix the casing of Services box
* Fix the casing of Replicated
* Fix the version of Replicated required, based on our changelog (https://circleci.com/server/changelog/#2-17-00)
> Fix some minor issues with the server ugprade doc

- jekyll/_cci2/v.2.18-overview.md
Remove vm service metrics included in error.
> fix metrics errors

- jekyll/_cci2/status.md
The badge is labelled SUCCESS not PASSED.
> Fix incorrect label

- jekyll/_cci2/executor-intro.md
- jekyll/_cci2/executor-types.md
> update windows image

- jekyll/_cci2/java-oom.md
> Notate lack of support for +usecontainersupport.

- jekyll/assets/js/sidebar.js
If we don't have any previously open sidebar section state, open the "Welcome" section by default.
https://circleci.atlassian.net/browse/CIRCLE-13487
> [CIRCLE-13487] Open sidebar "Welcome" section by default

- jekyll/_cci2/testing-ios.md
> Typo: "be following" -> "by following"

- jekyll/_cci2/pipeline-variables.md
This PR adds the most immediately useful case and an illustration of how the particular values might work semantically. The hope is to leave the reader with less work to understand the usefulness of the abstraction.
> Add a more useful example of using pipeline values

- jekyll/_cci2/orbs-best-practices.md
Title is already shown on page via meta data
> Redundant title

- jekyll/_cci2/executor-types.md
Add machine large to executor type options.
> add machine large to executor types

- jekyll/_cci2/hello-world-windows.md
See commit
https://github.com/circleci/circleci-docs/pull/3943/files
> Use updated orb in Windows Hello World

- jekyll/_cci2/hello-world-windows.md
> Fix - windows is available on the free plan

- jekyll/_cci2/building-docker-images.md
Add info about how to connect to remote docker VMs via SSH
> ssh remote docker

- jekyll/_cci2/contexts.md
Fix spelling mistakes
Spelling mistakes bug me
> Fix spelling mistakes

- docs/Content-Reuse.md
> fix formatting

- jekyll/_cci2/circleci-images.md
Added a note on what image tags we won't build.
If anyone has a suggestion for a better heading though, feel free to change it.
> Add note to convimg doc.

- jekyll/_cci2/hello-world-windows.md
> Make note of the possibility of installing a shell

- jekyll/_cci2/language-java-maven.md
The original PR was from a customer's fork so couldn't merge - this is a straight copy of #3691.
> add dartov's contribution to java maven doc

- jekyll/_cci2/building-docker-images.md
> Amend minor typo on Building Docker Images

- jekyll/_cci2/api-intro.md
- jekyll/_cci2/api_v2_introduction.md
- jekyll/_data/sidenav.yml
Initial draft....more content to follow
> api_v2_introduction.md

- jekyll/_cci2_ja/concepts.md
Fix image key in config.yml example
It was a comment.
> fix image key in concepts.md (ja)

- jekyll/_cci2/configuration-reference.md
Fix missing link to hello-world-windows
> Fix missing link in configuration-reference.md

- jekyll/_cci2/api-intro.md
- jekyll/_cci2/build-processing.md
- jekyll/_includes/snippets/pipelines-benefits.adoc
The benefits displayed in the new UI, to show people why they should enable pipelines in their projects, are currently not accurate. This PR is to work on getting the text right and consistent across docs and the UI.
> update pipelines benefits

- jekyll/_includes/global-nav.html
Update our nav to reflect the current state of nav on circleci.com, with the exception of removing the link to docs.
https://circleci.atlassian.net/browse/CIRCLE-23276
> [CIRCLE-23276] Sync recent nav changes from circleci.com

- jekyll/_cci2/testing-ios.md
This image has not been distributed yet, so let's hold off publishing
for a few hours.
> Add Xcode 11.3.1

- jekyll/_cci2/env-vars.md
Fixes https://github.com/circleci/circleci-docs/issues/4060
> fix: incorrectly named env-var reference.

- jekyll/_cci2/api-developers-guide.md
This introduces an end to end example of using the v2 API.
**Note**: This is a PR _onto_ @thomasr8 's current work on #4053 .
Pending/Possible changes:
- adding illustrations / diagrams
> [WIP] V2 API - end to end example

- jekyll/_cci2/configuration-reference.md
A hopefully more successful version of circleci/circleci-docs/pull/4027.
> Add new GPU classes — attempt 2

- jekyll/_cci2/configuration-reference.md
> Clarify `when` clause.

- jekyll/_cci2/api-developers-guide.md
Add use case steps to api developers guide
> [WIP]Download artifacts with api v2

- jekyll/_cci2/hello-world-windows.md
> Update available windows softwares: python + conda

- jekyll/_cci2/nomad-metrics.adoc
- jekyll/_ccie/update-nomad-clients-2190.md
> [WIP][DO NOT MERGE][RE-294] First Draft of 2.19.0 Nomad Client Update Doc

- jekyll/_cci2/deployment-integrations.adoc
Second level bullets were not displaying correctly due to a formatting error - this PR is a fix.
> fix list formatting

- .circleci/config.yml
> fix typo in code comment.

- jekyll/_cci2/docker-compose.md
went ahead and updated the docker-compose version while I'm in here.
removed `sudo`
upversioned docker-compose
I copy and pasted this code and it blew up. Trying to protect others from the same fate.
> sudo won't work here

- jekyll/_cci2/testing-ios.md
Adding Xcode 11.4 Beta 1 to image list
> Xcode 11.4 Beta 1

- jekyll/_cci2/deploying-ios.md
A heading had incorrect markdown
> Quick heading fix

- jekyll/_includes/global-nav.html
- jekyll/_layouts/classic-docs.html
- jekyll/assets/css/navbar.css
- jekyll/assets/js/nav.js
- src-js/instantsearch.js
**Ticket:** [CIRCLE-24055](https://circleci.atlassian.net/browse/CIRCLE-24055)
This ports over a set of keyboard navigation improvements from circleci.com/outer: https://github.com/circleci/circleci.com/pull/3030.
Changes:
- Turn off autofocus on Algolia search box
- Add nav skip button
- Make items with dropdowns/submenus tabbable
- Make nav bar logo tabbable
> [CIRCLE-24055] Main nav keyboard accessibility

- jekyll/_cci2/vm-service.adoc
Updating custom VM Service creation guide to account for updates to the scripts.
You can find more information here: https://circleci.atlassian.net/browse/RE-234
> [RE-234] Update Custom VM Service Images

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/demo-apps.md
- jekyll/_cci2/executor-types.md
- jekyll/_cci2/tutorials.md
- jekyll/_includes/snippets/language-guides.md
- jekyll/_includes/snippets/machine-resource-table.md
> reusable snippets for content that appears multiple times

- jekyll/_cci2/migrating-from-jenkins.md
Just a small typo
It was erroneous enough to make me re-read the sentence a few times.
> Small typo

- jekyll/_cci2/parallelism-faster-jobs.md
fixes #4149 
Text no longer matched code snippet.
> fix error in test run section

- widdershins.apiv2.yml
Add missing search from api v2 docs.
> Fix: Add api search to v2.

- jekyll/_cci2/overview.adoc
Removed duplicate word "must must" to "must"
> Removed duplicate word

- jekyll/_cci2/language-java.md
> explain why disable gradle daemon

- jekyll/_cci2/testing-ios.md
> Add Xcode 11.4 Beta 3

- jekyll/_cci2/language-python.md
fixes https://github.com/circleci/circleci-docs/issues/3902
> remove example's caching of /usr/local/bin

- jekyll/_cci2/adv-config.md
- jekyll/_cci2/browser-testing.md
- jekyll/_cci2/building-docker-images.md
- jekyll/_cci2/pipeline-variables.md
- jekyll/_cci2/using-shell-scripts.md
Updating the Advanced config section to highlight orbs, fix some errors and improve interlinking from the overview page.
How it looks now:
With links to relevant sections:
> advanced config update

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/hello-world-windows.md
Add how to set windows resource class using orb parameter
> add windows resource class details

- docs/server-docs-release-process.adoc
- jekyll/_cci2/v.2.19-overview.adoc
- jekyll/_config.yml
- jekyll/_data/sidenav.yml
Updates for Server v2.19.1 release
> update server version and add bugfixes to whats new section

- jekyll/_cci2/hello-world-windows.md
> Make note of docker on windows capabilities.

- jekyll/_cci2/v.2.19-overview.adoc
Add known issue to warn HTTP proxy Server customers not to upgrade until safe
> server known issue 2.19

- jekyll/_cci2/notifications.md
Found a simple typo while looking through the documentation
> Fixes typo in notifications.md

- jekyll/_cci2/authentication.adoc
A few improvements to the authentication section
Some are suggestion from the style guide, others are wording improvements, clarifications, etc.
> Authentication

- jekyll/_cci2/configuration-reference.md
In the CIRCLE-20808 epic we've implemented matrix jobs! Now it's time to
document them for customers.
I've done my best to:
- provide a comprehensive example, with comments explaining each element
of the config
- provide a simple explanation of each argument to `matrix` and what it
means, in the key/required/type/description table
- provide a deeper explanation of each argument to `matrix`, and
instructions for some common use cases
JIRA: CIRCLE-20808 / CIRCLE-20816
> [CIRCLE-20816] Document matrix jobs

- jekyll/_cci2/configuration-reference.md
> Fix parameters table in matrix documentation

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/pipeline-variables.md
- widdershins.apiv2.yml
> clarify use of when

- jekyll/_cci2/executor-types.md
- Also provide a simple example for how to use it.
https://circleci.atlassian.net/browse/CIRCLE-25241
> [CIRCLE-25241] Add RAM disk reference documentation

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/custom-images.md
- jekyll/_cci2/env-vars.md
> Clarify Docker environment variable info

- jekyll/_cci2/hello-world-windows.md
Fixes https://github.com/circleci/circleci-docs/issues/4257
> Update docker on windows example

- jekyll/_cci2/proxy.adoc
- jekyll/_cci2/v.2.19-overview.adoc
> add 2.19.2 changes

- jekyll/_cci2/v.2.19-overview.adoc
I wrote some links in markdown syntax by mistake :-(
> fix links in Server content

- jekyll/_cci2/configuration-reference.md
> background commands

- jekyll/_cci2/project-build.md
> switch to describe pipelines rather than builds

- jekyll/_cci2/first-steps.md
> make steps fit with signup flow

- jekyll/_cci2/reusing-config.md
Mostly reorganizing the Conditional Steps section, which had some redundancies and inconsistencies, and didn't take `unless` into account in some parts.
I read this document for the first time and felt some parts could improve. 🤷
> Conditional steps reorganization and misc English/format fixes

- .circleci/config.yml
- .gitmodules
- jekyll/_layouts/classic-docs.html
- jekyll/assets/js/shared
Follows up on : https://github.com/circleci/circleci.com/pull/3407#pullrequestreview-398535169
This enables sharing code with with the main CircleCI website.
> Add: shared git submodule

- jekyll/_cci2/jira-plugin.md
This feature is removed from the new UI
> remove reference to creating jira tickets from cci app

- jekyll/_cci2/creating-orbs.md
remove duplicate word.
`to to` -> `to`
> remove duplicate word in creating-orbs.md

- jekyll/_cci2/orb-author.md
correct a grammer error.
`not be able to` -> `be not able to`
> correct a grammar error in orb-author.md

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/customizations.adoc
- jekyll/_cci2/server-ports.adoc
slack convo: https://circleci.slack.com/archives/CKCV4LZ8V/p1588289442337000
> nomad client cpu info

- jekyll/_cci2/testing-ios.md
Changed 3 occurrences of _Opti**mzi**ng_ into _Opti**mizi**ng_
Every little (fix) helps!
> Fix typos in Testing iOS Applications on macOS

- jekyll/_cci2/gh-bb-integration.md
suggest an edit.
either GitHub and Bitbucket -> either GitHub or Bitbucket
> suggest an edit gh-bb-integration.md

- jekyll/_cci2/status-badges.md
Making it easy to find the option.
> Instruction on location of project's settings option

- jekyll/_cci2/artifacts.md
> add note about pertsisting artifacts

- jekyll/_cci2/workflows.md
See [pertinent](https://circleci.slack.com/archives/C4C9J5KHN/p1589375720078700) conversation.
> Add: note on hold duration for approval jobs.

- jekyll/_cci2/updating-server-replicated-version.adoc
- jekyll/_cci2/updating-server.adoc
fix replicated version to 2.38.6
> fix replicated version

- jekyll/_cci2/language-ruby.md
- jekyll/assets/js/main.js
Updates the language guide to 2.1. 
**Blocked:**
Do not merge until [sample app](https://github.com/CircleCI-Public/circleci-demo-ruby-rails/blob/2.1-orbs-config/.circleci/config.yml) has been updated on master with 2.1 config.
> 📗 [wip] - Ruby Language Guide Update

- jekyll/_cci2/api-developers-guide.md
> fixing typo

- jekyll/_cci2/databases.md
> Fix psycopg2 typo

- jekyll/_cci2/contexts.md
- jekyll/_cci2/env-vars.md
- jekyll/_cci2/gh-bb-integration.md
Fix for: https://circleci.atlassian.net/browse/CIRCLE-26385
> add warning about renaming

- jekyll/_cci2/configuration-cookbook.md
- jekyll/_cci2/configuration-reference.md
Add logic statements to the config reference
[JIRA](https://circleci.atlassian.net/browse/CIRCLE-26314)
In short, we added this feature and now need docs for it.
> [CIRCLE-26314] Add logic statements to the config reference

- jekyll/_cci2/configuration-cookbook.md
Add another example of using compile-time logic.
[CIRCLE-26314](https://circleci.atlassian.net/browse/CIRCLE-26314)
> Add another example for using compile-time logic

- jekyll/_cci2/aws.adoc
- jekyll/_cci2/v.2.19-overview.adoc
- jekyll/_config.yml
- scripts/build_pdfs_local.sh
~- [ ] Change IAM permissions if required~
> changes for 2.19.3

- .circleci/config.yml
> Switch to Markdown Proofer orb.

- jekyll/_cci2/testing-ios.md
Switching out the SwiftLint image to my new image. The original image defined here was ~3 years out of date
> Switch SwiftLint image

- jekyll/_cci2/testing-ios.md
Replacing the Danger image with newer one that I have built
> Replace Danger image with newer one

- jekyll/_cci2/api-docs.md
- jekyll/_cci2/api-job-trigger.md
Relevant [slack conversation](https://circleci.slack.com/archives/CNPG1R4QZ/p1589563792358300). ➡️  
Screenshot
> Add legacy warning for api-trigger-build.

- jekyll/_cci2/configuration-reference.md
> Fix: clarify filters with an example.

- jekyll/_cci2/getting-started.md
Fixed typos for clarity.
Fixed typos for clarity.
> fixed typos

- jekyll/_cci2/configuration-cookbook.md
Split up huge PR of cookbook changes by section, starting at the end of the doc :-)
> fix slack recipe in cookbook

- jekyll/_cci2/env-vars.md
> just a small typo from bash to ash

- jekyll/_cci2/configuration-cookbook.md
Main changes are removing orb source code and replacing with usage examples
> fix examples in GKE recipe 

- jekyll/_cci2/credits.md
Correct a line about limits for user seats on free tier.
> state no seat limit on free plan

- jekyll/_cci2/contexts.md
> add note about getting to Contexts from the old UI

- jekyll/_cci2/contexts.md
> fix yml parse error

- src-api/source/layouts/layout.erb
- src-config-builder/package-lock.json
- src-config-builder/package.json
- src-config-builder/public/index.html
- src-config-builder/src/components/Sidebar.tsx
- src-config-builder/src/index.tsx
- src-crg/source/layouts/layout.erb
> Add analytics to api and config builder

- jekyll/_cci2/configuration-cookbook.md
* updated intro to include a list of prerequisites so we don't need them for each recipe
* split out env var into separate section
* clarify language used to describe ECR ECS processes
> cookbook - update ECS example and intro

- jekyll/_cci2/pipeline-variables.md
> Fixed typo

- jekyll/_cci2/java-oom.md
Update the Java docs to reference the upcoming rollout of cgroups information.
https://circleci.atlassian.net/browse/CIRCLE-24559
Because we are planning to rollout out a change to include the cgroups information in Nomad containers, the docs should include updated information to reflect this.
> [CIRCLE-24559] Update Java OOM docs to reference cgroups

- jekyll/_cci2/concepts.md
- jekyll/_cci2/jobs-steps.md
- jekyll/_cci2/project-build.md
- jekyll/_data/sidenav.yml
fixes #4308 
* tabbed 2.1/2 versions of code snippets in concepts guide 
* remove some out of date elements.
* other editorial fixes
> update concepts guides

- jekyll/_cci2/java-oom.md
Attempt to clarify the GC threads behaviour further
https://circleci.atlassian.net/browse/CIRCLE-24559
> CIRCLE-24559 Further refinements to the advice on java OOMs

- jekyll/_cci2/building-docker-images.md
- src-api/README.md
- src-api/source/includes/_overview.md
**external**: add note about rate limiting to v1.1 docs, and link to api developers guide for more information.
**internal**: Improve contributing documentation for api v1.1/2
> Add: note about rate limiting on v1.1

- jekyll/_cci2/gh-bb-integration.md
The URL mentioned no longer exists, so I've suggested navigating to the setting instead.
> Fixed reference to setting page

- jekyll/_cci2/updating-server.adoc
- jekyll/_cci2/v.2.19-overview.adoc
- jekyll/_config.yml
* up version of Server across docs
* add what's new in 2.19.4
> up server version and add what's new section

- jekyll/_cci2/local-cli.md
Relevant [conversation](https://circleci.slack.com/archives/C0KBNJGRH/p1592248264291400).
> Add: information regarding CLI's context capabilities

- jekyll/_cci2/configuration-reference.md
See relevant [conversation](https://circleci.slack.com/archives/C0KBNJGRH/p1592342888297300).
> Clean: support requests for DLC on container plan.

- jekyll/_cci2/contexts.md
https://circleci.slack.com/archives/C0KBNJGRH/p1591950450283600
> add note about refreshing permissions

- jekyll/_cci2/examples-intro.md
add windows examples to the examples landing page
Is this a good/best example to use?
> update examples-intro to include windows

- src-crg/source/index.html.md
[see relevant conversation](https://circleci.slack.com/archives/C0KBNJGRH/p1593104148341200)
> Fix: broken links in src-crg

- jekyll/_cci2/enable-checks.md
Added a note about how users can either trigger a re-run of all checks, or just failed checks. This is based on JIRA ticket Circle-21682.
> Update Enable Checks

- jekyll/_cci2/v.2.19-overview.adoc
Further information for customers following an update in 2.19 - this is copied across from the changelog: https://circleci.com/server/changelog/#2-19-02
> add known issue info to what's new 2.19

- jekyll/_cci2/caching.md
> Updating bundler clean instruction order.

- jekyll/_cci2/credits.md
- jekyll/_cci2/faq.md
Addresses [CIRCLE-26876](https://circleci.atlassian.net/browse/CIRCLE-26876/)
> Add: notes on queueing/preparing.

- jekyll/_cci2/configuration-reference.md
See pertinent [conversation](https://circleci.slack.com/archives/C0KBNJGRH/p1592922945319600).
> Add: Simpler logic statement.

- jekyll/_cci2/enable-checks.md
Checks are not available on server, and this is not made clear in the doc.
> Update enable-checks.md to make clear it's only available on cloud

- jekyll/assets/js/main.js
> Clean: log statement.

- jekyll/_cci2/faq.md
Update billing FAQ share and transfer and usage sections to reflect new UI
> update UI tasks in billing section to reflect new UI

- jekyll/_cci2/orbs-faq.md
Rewrite Orb FAQ from user perspective with frequent questions.
Removed all FAQs related to authorship.
> Orb user FAQ

- jekyll/_cci2/orb-intro.md
Initial draft for content changes to orb-intro page.
> [WIP] orb intro initial draft

- jekyll/_cci2/orb-author-faq.md
- jekyll/_cci2/orb-author-intro.md
- jekyll/_data/sidenav.yml
Re-write content for orb author intro to update content.
Will need to potentially come back to update information about inline orbs.
> Orbs content author intro/structure rework

- jekyll/_cci2/faq.md
Some additional changes to the plans FAQ changes. Requested by Rosejen.
> changes to plans FAQ

- src-api/widdershins.apiv2.yml
Add the context API with "(Preview)" to the TOC.
> [CIRCLE-27918] Add contexts API

- jekyll/_cci2/aws.adoc
- jekyll/_cci2/server-ports.adoc
https://circleci.atlassian.net/browse/CIRCLE-27212
> add recommendations for heavy usage

- jekyll/_cci2/gh-bb-integration.md
> Fix: description to get to "Add User Key"

- jekyll/_cci2/contexts.md
- jekyll/_cci2/env-vars.md
> note about no secrets masking in server

- jekyll/_cci2/deployment-examples.md
fixes other issues related to https://github.com/circleci/circleci-docs/issues/4585
> update AWS env var in deployment examples

- jekyll/_cci2/api-intro.md
- jekyll/_cci2/build-processing.md
- jekyll/_cci2/configuration-cookbook.md
- jekyll/_cci2/deployment-examples.md
- jekyll/_cci2/executor-intro.md
- jekyll/_cci2/executor-types.md
- jekyll/_cci2/reusing-config.md
- jekyll/_cci2/workflows.md
> remove references to needing to enable pipelines

- jekyll/_cci2/orbs-best-practices.md
> fixed typo dependancies -> dependencies

- jekyll/_includes/social-buttons.html
Using FontAwesome, let's add our Twitch account
We need to drive more awareness of our Twitch account, and Docs is a great place to start
Twitch. Where the cool kids hangout and laugh at the other kids doing live coding streams
> add Twitch to social buttons

- docs/server-docs.adoc
Link was generated that should be an example of how a link is formed
> formatting to show in text rather than create link

- jekyll/_cci2/configuration-cookbook.md
> update cookbook example to be clearer about pipeline parameter usage

- jekyll/_cci2/caching.md
- jekyll/_cci2/oss.md
Addresses [SEC-1469](https://circleci.atlassian.net/browse/SEC-1469).
> [WIP] Add: notes on cache sharing + env var sharing.

- jekyll/_cci2/_ops-guide.adoc
- jekyll/_cci2/storage-lifecycle.adoc
- jekyll/_data/sidenav.yml
Original request: https://gist.github.com/makotom/7a110394d4afba9988e548ec96bb854a
> add S3 lifecycle page to docs site and PDF

- jekyll/_cci2/env-vars.md
- Reward some prose to be clearer.
This change is inspired by https://github.com/circleci/circleci-docs/pull/4558 .
> Mention an docker image  exception to env var "non interpolation"

- src-config-builder/src/data/index.tsx
> Add: updated Mac executor versions

- jekyll/_cci2/language-android.md
> Clean: jdk 8 -> 11 + remove out of date alpha tags

- jekyll/_cci2/testing-ios.md
Added Xcode 12 beta 6 to images list
> Xcode 12b6

- jekyll/_cci2/configuration-cookbook.md
- jekyll/_cci2/orb-author-faq.md
- jekyll/_cci2/orbs-faq.md
- jekyll/_cci2/testing-orbs.md
- jekyll/_cci2/using-orbs.md
Reverts circleci/circleci-docs#4704
reverting to fix a merge issue
> Revert "add matrix example to config cookbook"

- jekyll/_cci2/configuration-cookbook.md
- jekyll/_cci2/orb-author-faq.md
- jekyll/_cci2/orbs-faq.md
- jekyll/_cci2/testing-orbs.md
- jekyll/_cci2/using-orbs.md
Reverts circleci/circleci-docs#4709
> Revert "Revert "add matrix example to config cookbook""

- jekyll/_cci2/hello-world.md
> Update node image and unfollow instructions in Hello World.

- jekyll/_cci2/testing-ios.md
> Xcode 12.2 Beta 1

- jekyll/assets/css/navbar.css
> Fix: font weight on nav to match outer.

- jekyll/_cci2/caching.md
fixed some incorrect indentation in yaml snippets 
Fixes #4747
> caching doc updates

- jekyll/_cci2/private-images.md
Followup to https://github.com/circleci/circleci-docs/pull/4744
Spread the good news.
> Highlight multiple contexts in private images doc [CIRCLE-29510]

- jekyll/_cci2/xcode-policy.md
> Resolve typo in Xcode policy

- jekyll/_data/sidenav.yml
Modified Welcome part of Japanese sitenav.
Obsoleted compared to English version.
> Update (partial) ja part of sidenav

- README.md
> Fix: missing header in readme.

- jekyll/_cci2_ja/private-images.md
(Sorry, this is a clean-up version of #4761 )
Update translation to sync w/ the original English version.
The original English version has been updated.
> Sync w/ English ver to reflect updates related to Docker rate limits 

- jekyll/_cci2/testing-ios.md
> Xcode 12.2 Beta 2

- jekyll/_data/sidenav.yml
Update of Japanese ver of left navigation bar
1. To sync w/ updates on English version
2. To update titles as their counterpart docs + title have updated
> Update Japanese left sidebar to sync w/ latest docs

- jekyll/_cci2_ja/caching.md
Fixed the document structure to be identical w/ English version
As the structure has not been kept from En to Ja via Crowdin, the generated page (by Jekyll) has been weird since the last update.
(Also synced w/ the latest English document structure)
> Update to fix broken document structure caused by Crowdin

- jekyll/_cci2/docker-hub-pull-through-mirror.adoc
- jekyll/_cci2/private-images.md
- jekyll/_data/sidenav.yml
Add pull through Docker Hub mirror doc.
Based on https://gist.github.com/makotom/07268621beeaf14a201eb35180f53314
Docker Hub rate limiting work https://circleci.atlassian.net/browse/CIRCLE-29752
> Server docker proxy [CIRCLE-29752]

- jekyll/_cci2/getting-started.md
A src block has an additional column of white space, making it invalid yaml.
> Fix: indentation

- jekyll/_cci2/xcode-policy.md
> Fixed missing heading

- jekyll/_cci2/workflows.md
> Fixed typo and surplus spaces

- jekyll/_cci2/using-orbs.md
> Fixed grammar

- jekyll/_cci2/help-and-support.md
- jekyll/_cci2/optimization-cookbook.md
Fix broken link in Docs/2.0/ optimization-cookbook
#Orbtoberfest
Easy navigation and easy reading.
> Fix broken link in Docs/2.0/ optimization-cookbook

- jekyll/_cci2/yarn.md
> Fixed broken link

- docs/server-docs-release-process.adoc
Made the first letter of the word as a capital letter.
Found it necessary.
> Fixed a word

- jekyll/_cci2/migrating-from-jenkins.md
!Please don't merge yet!
Adding information and instructions on our preview release Jenkinsfile Converter. Links being finalized, but would like to confirm that the copy looks good. Thanks!
> Add callout to Jenkinsfile Converter

- jekyll/_cci2/migrating-from-jenkins.md
Links to Jenkins Converter and related documentation were outdated--this PR fixes this.
> Update links to Jenkins Converter

- jekyll/_cci2/configuration-reference.md
This PR updates the Docs image list for the new Q4 images.
We're aiming for merging Thursday.
> Update images for Q4.

- jekyll/_cci2/testing-ios.md
> add notes and links for Xcode 12.1 and 12.2b3

- jekyll/_cci2/orb-author.md
Fix typo of programatic -> programmatic
Found a typo
> Fix typo in orb-author

- src-config-builder/src/data/baseConfigs.tsx
- src-config-builder/src/data/index.tsx
Addresses this [request](https://circleci.slack.com/archives/C0KBNJGRH/p1602795936092500).
- remove unnecessary DB images
- updated existing images to use new _cimgs_ + example steps.
- update machine image list.
> Clean up config builder to use new cimgs + update machine list.

- jekyll/_cci2/docker-compose.md
Connect `docker-compose` document to `custom-images` document.
> Clean: draw attention to custom docker image document.

- jekyll/_cci2/env-vars.md
> Fix swt typo in env-vars.md

- jekyll/_cci2/gh-bb-integration.md
UI image is fixed in a separate PR. The focus of this PR is mainly to make the following URL just an example, rather than a clickable link.
> fix URL and some editorial changes and update UI images

- jekyll/_cci2_ja/orb-author-faq.md
- jekyll/_cci2_ja/orb-author-intro.md
Update Japanese translations for orb-author-intro.md and orb-author-faq.md
Sync with English version updates.
> Update Japanese translations for orb-author-intro.md and orb-author-faq.md

- jekyll/_cci2/executor-types.md
- jekyll/_cci2/private-images.md
Document CircleCI/DockerHub partnership with regard to docker image pulls.
> [CIRCLE-30388] Document CircleCI/DockerHub partnership

- jekyll/_cci2/collect-test-data.md
> Fix: clarify screenshot intent.

- jekyll/_cci2/getting-started.md
See [pertinent conversation](https://circleci.slack.com/archives/C0109328RTR/p1603830259101200).
> Add: Note re: adding users.

- jekyll/_cci2/testing-ios.md
new Xcode 12.2b3 image build has been updated with an 80g disk
> update Xcode 12.2b3 build image

- jekyll/_cci2/testing-ios.md
> add `12.2.0` and `12.1.1`

- jekyll/_cci2/runner-api.adoc
Initial draft of CircleCI Runner API Guide
> [WIP] runner-api.adoc

- jekyll/_cci2/runner-installation.adoc
Initial draft of CircleCI Runner Installation Guide
> [WIP] Create runner-installation.adoc

- .circleci/config.yml
- jekyll/_cci2/runner-api.adoc
- jekyll/_cci2/runner-faqs.adoc
- jekyll/_cci2/runner-installation.adoc
- jekyll/_cci2/runner-overview.adoc
- jekyll/_data/sidenav.yml
Added Runner pages to side navigation
> Runner docs

- jekyll/_cci2/runner-installation.adoc
To sync with https://github.com/CircleCI-Public/runner-preview-docs/blob/a440ad32b02a617bc2e8a43bb2cf184f911b2770/INSTALL-docker.md
> Update runner Docker instructions

- jekyll/_cci2_ja/creating-orbs.md
- jekyll/_cci2_ja/orb-author-faq.md
- jekyll/_cci2_ja/orb-author.md
- jekyll/_cci2_ja/orbs-best-practices.md
- jekyll/_cci2_ja/testing-orbs.md
Update Orb related docs to sync with the latest En version.
En version of docs have been updated because of the release of Orb Development Kit.
> [JA Doc Update] Orb related translations

- jekyll/_cci2/runner-api.adoc
Rename agent -> runner in runner API docs
The draft of the API docs was taken from an older version of the preview docs
> Rename agent -> runner in runner API docs

- jekyll/_cci2/persist-data.md
See [pertinent conversation](https://circleci.slack.com/archives/C0KBNJGRH/p1605808296191400)
> Add: tips for network/storage control.

- jekyll/_cci2/configuration-reference.md
closes #4938 
edit: added in some table formatting for easier readability in-editor.
> Update: logic statement error state & truthy list.

- jekyll/_cci2/insights.md
> Fix: remove duplicate "see also"

- jekyll/_cci2/env-vars.md
> Fix: update incomplete job-parameter example.

- jekyll/_cci2/user-accounts.adoc
https://circleci.atlassian.net/browse/SERVER-470
> add note to contact us before removing users if GitHub hostname changed

- jekyll/_includes/global-footer.html
Update the language switcher URL of the Japanese language in the footer.
> Update language switcher url of the Japanese language

- jekyll/_cci2/managing-api-tokens.md
Update scope names to match the UI 
Update the scope names and their access to match their permissions. 
https://circleci.atlassian.net/browse/CIRCLE-31379
> update project token documentation

- jekyll/_cci2/configuration-reference.md
Adds to CUDA images to the list.
> Add CUDA v10.2 and v11.1 images.

- jekyll/_cci2/collect-test-data.md
- jekyll/_cci2/migrating-from-github.adoc
- jekyll/_cci2/notifications.md
Batch of SEO fixes for 4xx issues.
> Fixes: SEO 4xx 

- jekyll/__glossary/authenticate.md
- jekyll/_cci2/gh-bb-integration.md
See [pertinent conversation](https://circleci.slack.com/archives/C28N26P62/p1610051208496700).
**Note!** This PR is also formatted with Prettier to clean up our line breaks. The only actual changes to the document [are these lines](https://github.com/circleci/circleci-docs/compare/ts/clean-gh-bb?expand=1#diff-6a315a47aeac892be510d09ed297afce14f41cfd3810406d575410b1f9f12c9bL200-L209).
> Clean: remove out-of-date section.

- jekyll/_cci2/insights.md
Update insights doc to mirror new time ranges in the UI.
> Add: insights time ranges are now variable.

- jekyll/_cci2/runner-installation.adoc
- jekyll/_cci2/runner-overview.adoc
We've seen compatibility issues on older versions, usually around the systemd version.
> Note that runner expects Ubuntu 18.04+

- jekyll/_cci2/orb-author.md
- jekyll/_cci2/orbs-best-practices.md
Standardising/explaining orb changelog files.
We're trying to move to a more standard way of surfacing changes between orb versions.
> Add blurbs about orb changelog file.

- jekyll/_cci2/concepts.md
Added link to Caching Dependencies page. This fixes #4719 
> caching link update

- jekyll/_cci2/jenkins-converter.md
Added a caveat that we do not support Shared Libraries.
Increasing number of feedbacks refer to the use of Shared Libraries.
> Added caveat for use of Shared Libraries

- jekyll/_cci2/orb-intro.md
Added section on the difference between public and private orbs.
> added private orb content

- jekyll/_cci2/orb-intro.md
> update to private orbs to include cli commands

- jekyll/_cci2/configuration-reference.md
Added runner configuration examples in "machine" and "resource class" sections. This fixes #5019 
> runner config updates for machine and resource

- jekyll/_cci2/language-android.md
Added an updated docker image to the sample configuration.
> docker image updated

- jekyll/_cci2/building-docker-images.md
Add the two new versions of remote Docker available.
> Add new remote Docker versions.

- scripts/docs-stats.py
Walks over non-legacy docs and checks last updated date on docs. Sorts by folder, then by time last updated. 
```
----------------------------------------------------------------------------------
0    | _cci2     | language-guides.md                                 | 3 years, 11 months ago
1    | _cci2     | getting-help-with-2.0.md                           | 3 years, 11 months ago
2    | _cci2     | configuration.md                                   | 3 years, 11 months ago
3    | _cci2     | defining-multiple-jobs.md                          | 3 years, 8 months ago
4    | _cci2     | open-source.md                                     | 3 years, 3 months ago
5    | _cci2     | deployments.md                                     | 3 years ago         
6    | _cci2     | local-jobs.md …
```
> Add: script for providing docs-last-updated stats

- jekyll/_cci2/contexts.md
see [CIRCLE-30998](https://circleci.atlassian.net/browse/CIRCLE-30998)
> Add: Context rotation via cli/api

- jekyll/_cci2/android-machine-image.md
- jekyll/_cci2/language-android.md
- jekyll/_data/sidenav.yml
> Add: Android machine image document.

- jekyll/_cci2/contexts.md
So excited to have these docs available! 
Noticed a few opportunities for clarification/correcting terminology, and reducing duplication w/ our API docs. Also fixed up some formatting for consistency.
- Remove unnecessary backslashes
- Remove references to supported languages (those are really examples; we support any valid HTTP client)
- Normalize and clarify terminology
- Make formatting more consistent
- Defer to API docs for response schema/interpretation rather than duplicating it
> [CIRCLE-30998] Touch up contexts documentation

- jekyll/_includes/global-footer.html
- jekyll/_includes/global-nav.html
- jekyll/_includes/ja/global-footer.html
- jekyll/_includes/ja/global-nav.html
- jekyll/_includes/main-searchbar.html
- jekyll/_layouts/classic-docs.html
- jekyll/_sass/_sidebar.scss
- jekyll/_sass/_subnav.scss
- jekyll/assets/css/buttons.css
- jekyll/assets/css/main.scss
- jekyll/assets/css/navbar.css
* Add `container-semi-fluid` class to match the size of `main-body`
* Apply `container-semi-fluid` to headers, footers and search components
* Remove unnecessary `row` and `col-md-12` divs from header
* Reduce subnav padding & negative margins to match container padding and prevent overflow
* Match `right-links` right position to match container padding, preventing button from hitting the edge of the window
* Set `small` button height to auto, the default value of 50px was too tall, caused uncentered text.
* Match sidebar left padding to that of container (15px vs 16px)
**Ticket:** [WEB-103](https://circleci.atlassian.net/browse/WEB-103)
**Before**
**After**
> [WEB-103] Align Sidebar, Header, and Footer

- jekyll/_cci2/hello-world-windows.md
[pertinent conversation](https://circleci.slack.com/archives/C0KBNJGRH/p1614784013036200)
> Add: server 2.x code samples.

- jekyll/_cci2/contexts.md
Also move two similar line-items together for easier scanning.
> contexts: Fix typo

- jekyll/_cci2/runner-server.md
- jekyll/_data/sidenav.yml
Adding changes needed when setting up a Runner for Server.
https://circleci.atlassian.net/browse/CIRCLE-33129
> Runner in Server [CIRCLE-33129]

- jekyll/_cci2_ja/android-machine-image.md
- jekyll/_cci2_ja/language-android.md
Tickets: [DNAMEDIA-180](https://circleci.atlassian.net/browse/DNAMEDIA-180)
Recently, with the release of the Android machine image, we have updated our
docs. So, I am updating the translations of documents related to Android
machine images.
> [l10n] Added translations for Android machine image

- jekyll/_cci2/faq.md
Removed reference to the maximum number of users.....this is no longer relevant.
> FAQs Updated

- .idea/vcs.xml
- jekyll/_cci2/docker-hub-pull-through-mirror.adoc
- jekyll/_cci2/gpu.adoc
- jekyll/_cci2/private-images.md
- jekyll/_cci2/server-3-install.adoc
- jekyll/_cci2/server-3-operator-metrics-and-monitoring.adoc
- jekyll/_cci2/server-3-operator-vm-service.adoc
- jekyll/_cci2/server-3-whats-new.adoc
- jekyll/_cci2/vm-service.adoc
- jekyll/_data/sidenav.yml
> Working on fixes

- jekyll/_cci2/server-3-whats-new.adoc
Removing an item from known issues to match the Server 3 changelog.
> Syncing to server 3 changelog

- jekyll/_cci2/executor-types.md
> Add: note on the possibility of upstream changes.

- jekyll/_cci2_ja/runner-server.md
add translation of runner-server
https://circleci.atlassian.net/browse/DNAMEDIA-210
> add translation of runner-server

- jekyll/_layouts/classic-docs.html
- pass parameters to mobile-sidebar.html template to fix missing the topbar menu issue
bug
> fix missing the topbar menu

- jekyll/_cci2/reusing-config.md
Documents syntax for negated parameter evaluation
Undocumented feature confirmed by an employee in https://discuss.circleci.com/t/conditional-string-feature-but-with-inverse-logic/28708/5
> Add example of negated parameter evaluation

- jekyll/_cci2/runner-overview.adoc
> [CIRCLE-34038] Update runner-overview.adoc

- jekyll/_cci2/server-3-operator-overview.adoc
Clarification in ops guide on what an Operator is.
> Small change to ops guide

- .idea/vcs.xml
- jekyll/_cci2/server-3-install.adoc
Removing Nomad location from install instructions
> Removing region from Nomad install

- jekyll/_cci2/api-developers-guide.md
> Add: note on accept headers.

- jekyll/_cci2/server-3-install-migration.adoc
- jekyll/_cci2/server-3-install.adoc
Add more details around 2.19 to 3.0 migrations.
- Warnings around proper prerequisites
- When to use new resources vs copying config over from 2.19
- debugging tips
> [SERVER-1069] add prereqs and post migration steps

- jekyll/_cci2/server-3-install-migration.adoc
Add FAQ section to 2.0 -> 3.0 migration documentation.
Address concern with post-migration build behavior
> [SERVER-1059] Add FAQ Section and Questions

- jekyll/_cci2/configuration-cookbook.md
The path-filtering example had some inconsistencies in nomenclature. I also added some more descriptive comments to the exmaple config.
> Fixes for path-filtering example

- jekyll/_cci2/circleci-images.md
> Fix: Add interpolation to dynamic header-ids.

- jekyll/_cci2/configuration-reference.md
> Add: link to orbs in configuration ref.

- jekyll/_cci2/notifications.md
A tiny modification in the Orb name used by IRC notifications
> Update IRC Orb name in notifications.md

- jekyll/_data/sidenav.yml
[See pertinent conversation](https://circleci.slack.com/archives/C0KBNJGRH/p1619637596133600?thread_ts=1619106055.097200&cid=C0KBNJGRH).
> Add sidenav link to "welcome"  landing page.

- jekyll/_cci2_ja/config-editor.md
https://circleci.atlassian.net/browse/DNAMEDIA-187
Added Japanese translation of https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/config-editor.md.
> [DNAMEDIA-187] config-editor.md

- jekyll/_cci2_ja/arm-resources.md
https://circleci.atlassian.net/browse/DNAMEDIA-224
Added Japanese translation of https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/arm-resources.md.
> [DNAMEDIA-224] [Translation] arm-resources.md

- crowdin.yml
Add sidenav.yml to crowdin.yml for adding i18n for nav bar
https://circleci.atlassian.net/browse/DNAMEDIA-253
> Update crowdin.yml to include sidenav.yml

- jekyll/_cci2/configuration-reference.md
Introduced a threshold to the number of contexts allowed within the configuration
https://circleci.atlassian.net/browse/CIRCLE-32884
> Maximum allowed contexts

- jekyll/_cci2/building-docker-images.md
Add new supported remote Docker version.
> Remote docker 20.10.6

- jekyll/_cci2/workflows.md
> Add: table striped class to workflows document

- jekyll/_cci2/hello-world-macos.md
- jekyll/_cci2/testing-macos.md
> Recommended updates to macOS executor docs.

- jekyll/_cci2/docker-layer-caching.md
Edit examples
Examples for machine configuration give error
> Examples give error

- jekyll/_cci2/orb-author.md
> remove outdated orb dev pack video

- jekyll/_cci2/runner-server.md
- jekyll/_cci2/server-3-operator-backup-and-restore.adoc
Remove docs 'coming soon' notes for features available from this release
> [SERVER-1140]remove coming soon notes

- jekyll/_cci2/server-3-install-hardening-your-cluster.adoc
- jekyll/_cci2/server-3-install.adoc
* k8s nodes don't need to communicate
* The SSH port is 54782
* CLI commands to create the security group
https://circleci.atlassian.net/browse/SERVER-1229
> Improve VM service documentation

- jekyll/_cci2/configuration-reference.md
This PR will adjust the language around prefix matching to be more explicit.
Stemmed from a conversation with a customer. Updating to ensure the docs are as clear as possible.
> Update prefix information for matches condition

- jekyll/_cci2/server-3-operator-backup-and-restore.adoc
Clarify the conditions needs for restore.
https://circleci.atlassian.net/browse/SERVER-1268
> [SERVER-1268] Kots must be installed before a restore is done

- jekyll/_cci2/server-3-operator-backup-and-restore.adoc
Show the customer how to get backup names if the cluster does not exist anymore
https://circleci.atlassian.net/browse/SERVER-1267
> [SERVER-1267] get backup names for CLI restore

- jekyll/_cci2/server-3-operator-metrics-and-monitoring.adoc
Telegraph customisation example: https://circleci.atlassian.net/browse/SERVER-1025
> server - telegraf datadog example 

- jekyll/_cci2/server-3-install-migration.adoc
https://circleci.atlassian.net/browse/SERVER-1259
https://circleci.atlassian.net/browse/SERVER-1260
> Migration guide fixes

- jekyll/_cci2/_server-3-install-guide.adoc
missing [] prevented page being added to install PDF
> fix include in install PDF master

- jekyll/_cci2/testing-ios.md
https://discuss.circleci.com/t/xcode-deprecation-notice-9-4-1-10-0-0-10-1-0-and-10-2-1/40515
> Deprecation warnings for old Xcode versions

- jekyll/_cci2/_server-3-ops-guide.adoc
- jekyll/_cci2/server-3-operator-load-balancers.adoc
- jekyll/_cci2/server-3-overview.adoc
- jekyll/_data/sidenav.yml
https://circleci.atlassian.net/browse/SERVER-1156
To do:
> add operator guide page on load balancers

- jekyll/_cci2/configuration-reference.md
Moved sentence
It was in wrong place
> Sentence about working directory wandered from its sheep pen.

- jekyll/_data/sidenav.yml
- add translations for sidenav items
- https://circleci.atlassian.net/browse/DNAMEDIA-319
> Translate sidenav items [DNAMEDIA-319]

- jekyll/_cci2/runner-api.adoc
- [CIRCLE-36130]
[CIRCLE-36130]: https://circleci.atlassian.net/browse/CIRCLE-36130
> [CIRCLE-36130] Document queue depth API

- jekyll/_cci2/oss.md
> docs: update `note` for oss

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/ip-ranges.md
first pass at updating docs pages
Want to get docs pages for new feature ready to go
> first pass at docs

- jekyll/_cci2/ip-ranges.md
> address docs bot comments

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/ip-ranges.md
- jekyll/_data/sidenav.yml
@sebastian-lerner here's the new PR. Should be able to see a preview from here 🤞 .
@thomasr8 I've put the ip ranges content in a new branch so we can see the deploy-preview. Turns out this does not work for fork branches.
> Ip ranges docs

- jekyll/_cci2/ip-ranges.md
> one minor correction to be more precise

- jekyll/_cci2/ip-ranges.md
@rosieyohannan sorry for continuing to tweak, but when you get a chance can you please take a look and merge if it's okay?
> be more precise about what plans can access

- jekyll/_cci2/ip-ranges.md
> update the last updated field

- jekyll/_cci2/postgres-config.md
Eliminates Go 1.8 description by syncing PRs from [the demo repo](https://github.com/CircleCI-Public/circleci-demo-go).
- Update Go from 1.8 to 1.12 cf. CircleCI-Public/circleci-demo-go#11
- Use dockerize cf. CircleCI-Public/circleci-demo-go#10
I would like not to use Go 1.16 at this moment as there has been no test with Go 1.16 in the repo `CircleCI 2.0 Demo Application: Go (Golang)`.
Go 1.8 was already EOL'ed and we should provide how Go modules works on CircleCI.
> Use Go modules with Go 1.12 by syncing PRs from the demo

- jekyll/_cci2/security-server.adoc
- jekyll/_cci2_ja/security-server.adoc
We don't actually upload support bundles to Honeycomb
https://circleci.atlassian.net/browse/SERVER-1333
> Remove references to uploading support bundles to Honeycomb

- jekyll/_cci2/server-3-install.adoc
Documenting blocked_cidrs from the Nomad Terraform we offer
https://circleci.atlassian.net/browse/SERVER-1281
> Blocked CIDR note

- jekyll/_cci2/configuration-reference.md
updated linux image to -02 for pyenv fix
> updated linux image to 202107-02 for pyenv fix

- jekyll/_cci2/ip-ranges.md
> make pricing details more explicit

- jekyll/_cci2/testing-ios.md
Add NVM info and clarify Apple Silicon support
CPE-197
> Add NVM info and clarify Apple Silicon support

- jekyll/_cci2/ip-ranges.md
> add in macOS cloud info

- jekyll/_cci2/ip-ranges.md
> making Mac IPs sub bullets

- jekyll/_cci2/webhooks.md
See: [CIRCLE-36895](https://circleci.atlassian.net/browse/CIRCLE-36895).
> Add: payload signature to webhooks doc.

- jekyll/_cci2/runner-on-kubernetes.adoc
- jekyll/_cci2_ja/runner-on-kubernetes.adoc
- Remove runner on kubernetes preview note
- Move runner on k8s limitation to the bottom
JIRA: [CIRCLE-37006]
[CIRCLE-37006]: https://circleci.atlassian.net/browse/CIRCLE-37006
> [CIRCLE-37006] runner k8s cleanup

- jekyll/_cci2/webhooks.md
- jekyll/_cci2_ja/webhooks.md
Add documentation on how to validate a webhook signature.
https://circleci.atlassian.net/browse/CIRCLE-36895
> Add docs on validating webhook signatures

- jekyll/_cci2/building-docker-images.md
> added Docker v20.10.7

- jekyll/_data/ja/sidenav.yml
- jekyll/_data/sidenav.yml
Updated EN -> JA documentation translations
> Sync English and Japanese menus.

- jekyll/_cci2/configuration-reference.md
related to this thread: https://circleci.slack.com/archives/CKCV4LZ8V/p1628532818246700
> remove references to using machine executor without specifying an image

- jekyll/_cci2/configuration-cookbook.md
> Remove comments that don't seem to apply

- jekyll/_cci2/optimizations.md
> remove default reference

- jekyll/_cci2/testing-ios.md
Adding Xcode 13 RC to the table
> Xcode 13 RC

- jekyll/_data/sidenav.yml
https://circleci.atlassian.net/browse/DOCS-17?atlOrigin=eyJpIjoiNjg5YTQ0YjM5MTQ2NGU2ZGJhNjg1ZGZhNWRkYmEzZGIiLCJwIjoiaiJ9
> update side bar with sample config

- jekyll/_layouts/classic-docs.html
- jekyll/assets/css/main.scss
- jekyll/assets/js/main.js
This takes the current section link button and allows users to hover + click to copy the section URL to their clipboard. Original this included a icon change as well but the icon comes from Font Awesome and will be update in a future ticket.
JIRA: https://circleci.atlassian.net/browse/CIRCLE-36534?atlOrigin=eyJpIjoiZjliZjkwZGZhZjVlNDM4OTg5MDk1ODZiNmY0OTNiZTciLCJwIjoiaiJ9
https://user-images.githubusercontent.com/42252054/133318905-9c4d5b73-2f62-4d04-8fd6-8808299d5938.mov
> [CIRCLE-36534] Section URL Share Button (Docs Disco)

- jekyll/_cci2/_server-3-ops-guide.adoc
- jekyll/_cci2/server-3-operator-proxy.adoc
- jekyll/_data/sidenav.yml
https://circleci.atlassian.net/browse/SERVER-1400
> [WIP]Proxy doc for 3.2

- jekyll/_cci2/migrating-from-aws.adoc
- jekyll/_cci2/migrating-from-azuredevops.adoc
- jekyll/_cci2/migrating-from-buildkite.adoc
- jekyll/_cci2/migrating-from-github.adoc
- jekyll/_cci2/migrating-from-gitlab.adoc
- jekyll/_cci2/migrating-from-teamcity.adoc
- jekyll/assets/css/main.scss
- package-lock.json
**Ticket:** [CIRCLE-37844](https://circleci.atlassian.net/browse/CIRCLE-37844) [CIRCLE-37845](https://circleci.atlassian.net/browse/CIRCLE-37845)
Changes
=======
- add highlightJS badge to all code and configuration samples in the Migration pages
- adjust format and styling of all Migration pages
The current _"Migrating From..."_ pages have a lot of inconsistencies in both its styling and functionality. Because these pages are probably some of the most important given the fact that people are trying to migrate from a competitor to CircleCI, it is paramount that we improve the overall UI/UX. The goal is to provide the same consistent experience throughout the pages.
As there are many pages of changes, please pull down this branch and visit http://ui.circleci.com/docs/2.0/ to view all …
> [CIRCLE-37844 & CIRCLE-37845]: Make every code snippet HighlightJS ready and UX cleanup

- jekyll/_cci2/about-circleci.md
- jekyll/_cci2/arm-resources.md
- jekyll/_cci2/docker-layer-caching.md
- jekyll/_cci2/dynamic-config.md
- jekyll/_cci2/executor-intro.md
- jekyll/_cci2/insights.md
- jekyll/_cci2/migration-intro.md
- jekyll/_cci2/orb-intro.md
- jekyll/_cci2/runner-overview.adoc
- jekyll/_cci2_ja/insights.md
https://circleci.atlassian.net/browse/DOCS-19
> update academy links with access code

- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/credits.md
- jekyll/_cci2/faq.md
- jekyll/_cci2/migrating-from-travis.md
- jekyll/_cci2/optimizations.md
- jekyll/_cci2/runner-api.adoc
- jekyll/_cci2/runner-faqs.adoc
- jekyll/_cci2/runner-on-kubernetes.adoc
- jekyll/_cci2/runner-overview.adoc
- jekyll/_cci2_ja/faq.md
- jekyll/_cci2_ja/migrating-from-travis.md
- jekyll/_cci2_ja/orbs-faq.md
- package-lock.json
References to pricing plans updated to "Free plan," "Performance plan," and "Scale plan."
There wasn't consistency in how the terms were capitalized - we had both "Performance Plan" and "Performance plan," as an example.
I excluded URLs (e.g. 'https://circleci.com/pricing[Scale Plan]'). Also left it at "free plan" if it was referenced in conjunction with "paid" plans, or as "non-free plan."
> Fix pricing plan capitalization

- jekyll/_cci2/docker-layer-caching.md
Fixes issue #5728.
Extra right parenthesis.
> Remove stray parenthesis

- jekyll/_cci2/server-3-operator-orbs.adoc
https://circleci.atlassian.net/browse/SERVER-1400
Post release I will add something to the troubleshooting section about this too.
> [SERVER] orbs behind a proxy

- jekyll/_cci2/server-3-whats-new.adoc
Steps to help customers out with potential issues they might encounter when upgrading to 3.2.
> add upgrade notes and steps

- jekyll/_cci2/security.md
- jekyll/_cci2_ja/security.md
Add new audit logs event types, Update audit logs event in the Japanese language file to be the same as the English language
We started to track new event type (api token create)
> [CIRCLE-38093] Update audit logs event types

- jekyll/_cci2/circleci-images.md
- jekyll/_cci2/docker-compose.md
- jekyll/_cci2/executor-types.md
This PR is focusing on updating the copywriting and examples within our documentation around Docker and Docker Compose.
It is mainly copy fixes, for better readability (hopefully), as well as adding syntax highlights for our code snippets there.
As an update for Docker Compose, I also have a accompanying PR on the demo application for Docker Compose here:
https://github.com/CircleCI-Public/circleci-demo-docker/pull/9
I understand that we also have 🇯🇵 documents which would subsequently go through Crowdin for localization so I kept the 🇯🇵 components as-is for now! 🙇 
I noted that the documents around Docker and Docker Compose can be improved and updated, so I'd like to do my bit here! 🤓
> Update documents around Docker & Docker Compose

- jekyll/_cci2/configuration-reference.md
we need these changes to go live on november 1
> do not merge yet

- src-js/experiments/videoTutorials.js
- Use Q4 Exclusion group
https://circleci.slack.com/archives/C021NCSEM44/p1635717722172300
> [CIRCLE-38203] Switch experiment to Q4 exclusion group

- jekyll/_cci2/faq.md
- jekyll/_data/sidenav.yml
- Some rewording of the Billing section of the FAQ page to align with the pricing update.
- Adding the FAQ page to the nav
The pricing update required some adjustments in the wording we use on the FAQ page.
> Update FAQ page for gtm pricing, add to sidenav

- jekyll/_cci2/server-3-install-build-services.adoc
- jekyll/_cci2/server-3-install.adoc
- jekyll/_cci2/server-3-whats-new.adoc
- jekyll/_config.yml
https://circleci.atlassian.net/browse/DOCSTEAM-44?atlOrigin=eyJpIjoiYzA2MTJmMTRiOTYzNGNiNTg2MzljMDlkMzY2NmE1YzMiLCJwIjoiaiJ9
> Server 3.2.1 release docs

- jekyll/_cci2/configuration-reference.md
> clarity in config ref

- jekyll/_cci2/ssh-access-jobs.md
> small update

- jekyll/_cci2/configuration-reference.md
> remove note about 1.0 configs in config reference

- jekyll/_cci2/ip-ranges.md
> add a note to clarify a use case

- .gitignore
- .idea/.gitignore
- .idea/circleci-docs.iml
- .idea/misc.xml
- .idea/modules.xml
- Remove `.idea/*`
This directory is created by a JetBrains IDE and holds user preferences that don't need to be in git
> Chore: Remove `.idea/` folder

- src/js/site/main.js
Fixes ["(unknown): Script error."](https://rollbar.com/circle/circleci-docs/items/9/)
> Fix: add missing experimentContainer.

- jekyll/_layouts/classic-docs.html
- src/js/experiments/relatedResources.js
Rerun (current)Ticket: [CIRCLE-38943](https://circleci.atlassian.net/browse/CIRCLE-38943)
Original Ticket: [CIRCLE-37092](https://circleci.atlassian.net/browse/CIRCLE-37092)
- Updated experiment key
- Change position that `related resources` will appear
preview: [link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/CIRCLE-38943-article-suggester-preview/?force-all)
Note not all pages will have the change. See images below to see all pages effected.
We are going to run an experiment on the top 5 doc pages for an MVP version of the Article Suggester. This is a fairly simple experiment (nothing is smart/dynamic and selects the suggested articles) because we first want to validate that this is something users want. Pages + Links can be found here: …
> [CIRCLE-38943] Rerun of related resource experiment with new position

- jekyll/_cci2/arm-resources.md
- jekyll/_cci2/code-coverage.md
- jekyll/_cci2/configuration.md
- jekyll/_cci2/defining-multiple-jobs.md
- jekyll/_cci2/deployments.md
- jekyll/_cci2/hello-world-windows.md
- jekyll/_cci2/jira-plugin.md
- jekyll/_cci2/local-cli-getting-started.md
- jekyll/_cci2/local-jobs.md
- jekyll/_cci2_ja/arm-resources.md
- jekyll/_cci2_ja/hello-world-windows.md
- jekyll/_cci2_ja/jira-plugin.md
- jekyll/_cci2_ja/local-cli-getting-started.md
Some of our docs had multiple H1 headings. This was flagged up by the recent SEO audit. This PR fixes them.
> fix docs with multiple H1

- jekyll/_cci2/persist-data.md
Other teams have added information to the persist data page within the past few weeks, which I edited for clarity and consistency. 
I noticed a few mistakes on this page while I was working on my own stuff today and got distracted and decided to edit all the new information (which is why the branch name is not reflective of the page I ended up editing sorry 😂 )
> Edit new information on persist data page

- jekyll/_cci2/testing-ios.md
> Xcode 13.2 Beta 2

- jekyll/_cci2/server-3-install-prerequisites.adoc
SERVER-1498
Recommending k8s versions for our server versions.
https://circleci.atlassian.net/browse/SERVER-1498
We don't yet support k8s 1.22 until the 3.3 release
> Document supported k8s versions for server

- jekyll/_cci2/runner-api.adoc
Add running tasks endpoint documentation
A new runner API endpoint has been added to support autoscaling - This PR adds docs for this endpoint
> Add running tasks endpoint documentation

- jekyll/_cci2/orb-author-validate-publish.md
- jekyll/_cci2/orb-author.md
- jekyll/_cci2/server-3-operator-orbs.adoc
https://circleci.atlassian.net/browse/SERVER-1528
Server users need to use `--private` flag when creating orbs to keep private within their installation.
> warning about server orbs private

- jekyll/_includes/edit-on-github.html
- jest/global.js
- src/js/site/sidebar.js
- src/js/site/sidebar.test.js
- src/js/utils.js
- src/js/utils.test.js
- src/styles/main.scss
The original Highlight on scroll broke our main branch (see this [PR](https://github.com/circleci/circleci-docs/pull/5924)). This was because our tests were being imported into our production bundle due to glob imports. This issue has been fixed in [this pr](https://github.com/circleci/circleci-docs/pull/5966).
So, the changes in this PR are all the same as those introduced in the original at #5924 .
Preview visible [here](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/tees-hl-toc-preview/2.0/hello-world/).
> Feat: Re-implement TOC highlighting

- jekyll/_cci2/managing-api-tokens.md
- jekyll/_data/sidenav.yml
> update steps in managing API token doc to reflect UI

- jekyll/_cci2/pipelines.md
Pipelines are triggered not run
> triggered not run

- jekyll/_cci2/server-3-operator-vm-service.adoc
https://circleci.atlassian.net/browse/SERVER-1473
> update vm service options

- jekyll/_cci2/server-3-install-prerequisites.adoc
https://circleci.atlassian.net/browse/SERVER-1499
> server 3 specify kots version

- jekyll/_cci2/server-3-whats-new.adoc
https://circleci.atlassian.net/browse/SERVER-1508
> add known issue to server v3.2.x

- jekyll/_cci2/server-3-operator-extending-internal-volumes.adoc
https://circleci.atlassian.net/browse/SERVER-1504
> Server 3 volume reseize troubleshooting

- jekyll/_cci2/server-3-install-build-services.adoc
- jekyll/_cci2/server-3-install-post.adoc
- jekyll/_cci2/server-3-install-prerequisites.adoc
- jekyll/_cci2/server-3-install.adoc
- jekyll/_data/sidenav.yml
Backup and restore was missing from the post install phase of the installation guide.
Also - changes build environment to execution environment for consistency.
> Fix post install steps

- jekyll/_cci2/testing-ios.md
> Update testing-ios.md with image deprecations

- jekyll/_cci2/server-3-whats-new.adoc
- jekyll/_config.yml
https://docs.google.com/document/d/1XuROqvz4Xeio7XG7tzfXkYgNLh-AangjKZbbTOzBvt8/e
> server 3.2.2 release

- jekyll/_cci2/v.2.19-overview.adoc
https://docs.google.com/document/d/1HXGhuXD1MNLSOnKS4Dgc-O87olN9CywgLAaEk11j3qE/edit
> server 2.19.13 release

- jekyll/_cci2/building-docker-images.md
- jekyll/_cci2/config-intro.md
- jekyll/_cci2_ja/building-docker-images.md
- jekyll/_cci2_ja/config-intro.md
- jekyll/_includes/head.html
- package.json
- src/js/app.js
- src/js/site/main.js
- src/styles/main.scss
- yarn.lock
Jira: [DD-262](https://circleci.atlassian.net/jira/software/c/projects/DD/boards/477?modal=detail&selectedIssue=DD-262)
Preview link: [link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-262-add-line-references-for-code-blocks-preview/?force-all)
Have the code lines numbered so it’s easier for the docs team and end-user to refer to specific lines of a code block. 
Improve the end-user / docs teams' experience when referencing and writing the code
- Add new library[ Line numbering plugin for Highlight.js by Yauheni Pakala ](https://wcoder.github.io/highlightjs-line-numbers.js/)
- Remove linenos (old way of adding in line numbers)
Adding number for single line been reviewed with @danbeere
> DD-262 Line references for code blocks

- jekyll/_cci2/configuration-reference.md
> specify example for deploy job

- jekyll/_cci2/ip-ranges.md
> call out known limitation

- jekyll/_cci2/ip-ranges.md
this is what i get for trying to multitask in a meeting
> =( sorry for not proof reading

- jekyll/_cci2/faq.md
- jekyll/_cci2/persist-data.md
Updates to wording on where users need to look to find information about billable usage.
The UI changed.
> UI network updates

- jekyll/_includes/global-nav.html
- jekyll/_includes/sidebar.html
- jekyll/_includes/utility-icons/globe.svg
- src/js/services/lang.js
- src/js/site/nav.js
- src/styles/_global-nav.scss
**Ticket:** [DD-272](https://circleci.atlassian.net/browse/DD-272)
**Preview Link:** [here](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/relocate-language-picker-preview/?force-all)
**Note**: Changing languages in the preview link will take you to the production site due to a new url being generated for that language
- add new language selector to global nav
- remove old language selector from sidebar
- edit functionality for language selection in `lang.js` for new language selector 
- add language selector drop down menu functionality in `nav.js`
Reposition language selector with updated design for intuitive UI experience for the users.
Attempting to maintain a consistent UI with the outer sides as well.
**Before:**
**After:**
> [DD-272]: Language Selector - Repositioning, update design 

- jekyll/_layouts/classic-docs.html
- src/js/app.js
- src/js/services/index.js
- src/js/services/progressbar.js
- src/js/services/progressbar.test.js
- src/js/site/user.js
- src/styles/_global-nav.scss
- src/styles/_progressbar.scss
- src/styles/_variables.scss
- src/styles/main.scss
[Preview](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/docs-disco/scroll-depth-progress-bar-preview/?force-all)
[DD-273](https://circleci.atlassian.net/browse/DD-273)
**What and Why?**
Show the progress bar indicating how far the reader has finished reading so the user feels encouraged to finish reading the article
Impact: Encourage the readers to finish reading the article by gamification
**Definition of Done/Acceptance Criteria:** 
Refer to [design](https://www.figma.com/file/HrgpUU2M3ED7OT0p0f99bH/Docs-Disco-Experiments?node-id=4156%3A8738)
[Live Example](https://learn.hashicorp.com/tutorials/terraform/state-cli)
Calculate progress based on article progress (scrolling, similar to scroll highlighting change)
Design review with  @danbeere
> [DD-273] Scroll Depth Progress Bar

- .circleci/config.yml
- .gitignore
- src/js/app.js
- src/js/services/highlightJSBadge.js
- src/js/services/index.js
- src/js/services/optimizely.js
- webpack.config.js
[PREVIEW](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/fix-rollbar-errors-preview/?force-all)
[TICKET](https://circleci.atlassian.net/browse/DD-298?atlOrigin=eyJpIjoiNWZhOTE0NWVlODc1NDE5ZGE3YThhZmNjNTU1YmJiY2UiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
https://rollbar.com/circle/circleci-docs/items/2722/
https://rollbar.com/circle/circleci-docs/items/2769/
https://rollbar.com/circle/circleci-docs/items/2771/
more: https://rollbar.com/circle/all/items/?sort=%5Bobject%20Object%5D&status=active&date_from=&date_to=&environments=%22development%22&environments=development&environments=production&environments=staging&environments=system&environments=undefined&activated_to=&framework=&levels=40&levels=50&activated_from=&offset=0&timezone=&assigned_user=&date_filtering=seen&projects=226388&q …
> [DD-298] Fix rollbar errors

- src/js/dateFormatAgoHelper.js
- src/js/dateFormatAgoHelper.test.js
- src/js/services/progressbar.js
- src/js/site/main.js
- src/js/site/sidebar.js
[PREVIEW](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/home-page-bug-fixes-preview/?force-all)
There are console errors on the home page from the new Time Posted bar & the progress bar since they do not occur on the home page.
Additionally, the unit tests for the Date Formatter are breaking since they do not work for dates that end in the 30th or 31st. This is blocking the docs pipeline.
> Bug Fixes: home page console errors & date format helper unit tests

- src/js/dateFormatAgoHelper.test.js
Bug Fix for unit test for 31st. There's an edge case for where it does not work for months with 31 days.
> [BUG FIX] Edge case on months with 31 days

- jekyll/_cci2/runner-overview.adoc
This was in regards to a customer noticing that the link was incorrect.
> Update the rerun job with ssh link

- jekyll/_cci2_ja/configuration-reference.md
> Resolve conflicts

- jekyll/_cci2/ip-ranges.md
> get the correct messages in the information alerts

- src/js/site/sidebar.js
[Ticket](https://circleci.atlassian.net/browse/DD-306)
On mobile the sign up cta was being pushed below the fold.
> Update: don't auto open sidebar on mobile.

- jekyll/_includes/global-nav.html
- jekyll/ja/index.html
- src/js/experiments/forceAll.js
- src/js/services/lang.js
- src/styles/_global-nav.scss
**Ticket:[ DD-267](https://circleci.atlassian.net/browse/DD-267)
Preview Link:** http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/request-new-language-preview/?force-all
- add globe svg
- add new language requester form
- add appropriate style and functionality for language request form
- refactor code to changes languages to allow for dynamic URL for preview builds
- update href links with `{{ site.baseurl }}` for Japanese hompage 
Including new feature in the language selector to allow users to request languages that they would like to see as translation options for the future.
Please see associated PRs:
- #6084 
- #6096 
**Before:**
**After**
https://user-images.githubusercontent.com/57234605/148326854-cb70ce2b-165f-44fb-b022-35c709774b42.mp4
> [DD-267]: Request New Language Form 

- src/js/services/lang.js
- add `toLowerCase()` to `requestedLanguage` for amplitude data results 
Allow us to better aggregate and read our data results
> [CHORE]: lowercase new lang request data

- jekyll/_cci2/executor-types.md
> remove outdated comment

- jekyll/_cci2/server-3-install-build-services.adoc
We will be releasing support for nomad's autoscaler service with server `3.3.0`. This PR contains a rough draft of the documentation that we hope the docs team can make pretty :)
https://circleci.atlassian.net/browse/SERVER-1469
> [SERVER-1469] server 3.3 - adding docs for nomad-autoscaler on server

- jekyll/_cci2/executor-types.md
> get rid of reference to old 16.04 image

- jekyll/_cci2/configuration-reference.md
fixing typo deveoper -> developer
> fixing typo deveoper -> developer

- jekyll/_cci2/browser-testing.md
Link to Lambdatest. See https://circleci.atlassian.net/browse/WEB-629
> lambdatest link

- jekyll/_cci2/concepts.md
- jekyll/_includes/snippets/pipelines-benefits.adoc
Fixed typos and made minor style changes
https://circleci.atlassian.net/browse/DOCSTEAM-59
> DOCSTEAM-59 - Fix typos

- jekyll/_cci2/gh-bb-integration.md
Make the deploy key steps easier to follow after some customer feedback.
> fix up deploy key steps

- jekyll/_cci2/server-3-install.adoc
IAM role auth options for server 3.3
> add in auth options for object storage

- jekyll/_cci2/server-3-install-hardening-your-cluster.adoc
- jekyll/_cci2/server-3-install-migration.adoc
- jekyll/_cci2/server-3-install-post.adoc
> Fix typos and apply style guide

- jekyll/_cci2/private-images.adoc
- jekyll/_cci2/security-server.adoc
- jekyll/_cci2/server-3-operator-application-lifecycle.adoc
- jekyll/_cci2/server-3-operator-authentication.adoc
- jekyll/_cci2/server-3-operator-backup-and-restore.adoc
- jekyll/_cci2/server-3-operator-build-artifacts.adoc
- jekyll/_cci2/server-3-operator-extending-internal-volumes.adoc
- jekyll/_cci2/server-3-operator-externalizing-services.adoc
- jekyll/_cci2/server-3-operator-load-balancers.adoc
- jekyll/_cci2/server-3-operator-metrics-and-monitoring.adoc
- jekyll/_cci2/server-3-operator-orbs.adoc
- jekyll/_cci2/server-3-operator-overview.adoc
- jekyll/_cci2/server-3-operator-proxy.adoc
- jekyll/_cci2/server-3-operator-troubleshooting-and-support.adoc
- jekyll/_cci2/server-3-operator-usage-data.adoc
- jekyll/_cci2/server-3-operator-user-accounts.adoc
- jekyll/_cci2/server-3-operator-vm-service.adoc
Fixed typos, tidied up, and applied style guide
https://circleci.atlassian.net/browse/DOCSTEAM-101
> Fixed typos, tidied up, and applied style guide

- src/js/site/nav.js
Fixes [Rollbar#2806](https://rollbar.com/circle/circleci-docs/items/2806/?item_page=0&#traceback).
> Fix: Add null checks for mobile nav buttons

- jekyll/_cci2/server-3-install-prerequisites.adoc
Update server docs for object storage policy when using IRSA
https://circleci.atlassian.net/browse/SERVER-1626
> (SERVER-1626) Update server docs for object storage policy when using IRSA

- jekyll/_cci2/server-3-operator-vm-service.adoc
Updates the vm-service docs to include the IRSA authentication option. 
https://circleci.atlassian.net/browse/SERVER-1628
> (SERVER-1628) Update vm-service docs to include IRSA auth option

- jekyll/_cci2/server-3-install-build-services.adoc
- jekyll/_cci2_ja/server-3-install-build-services.adoc
Fix broken link for vm-service page
> (maint) Fix broken link for vm-service page

- jekyll/_cci2/server-3-overview.adoc
Moved kotsadm-kots error to correct column
> Moved kotsadm-kots error to correct column

- jekyll/_cci2/runner-installation.adoc
Update the Runner on Server documentation to have the right runner version for server 3.3
> Update runner version for server 3.3

- src/js/experiments/snippetFeedback.js
- src/js/experiments/snippetFeedback.test.js
- src/js/experiments/videoTutorials.js
- src/js/services/progressbar.js
- Rm unnecessary jquery onreadys in experiment files
- Remove extraneous space in snippet feedback
- Remove occasional and random green flicker on page load
> Miscellaneous changes made when working on Guided Tour

- src-api/v2/template.hbs
see #6219 
Revert file back to its minified format
> [FIX]: Revert file back to minified style

- jekyll/_cci2/runner-faqs.adoc
Removal of sentence that says we might charge for runner N&S in the future
We charge for runner N&S now
> Remove sentence about future runner charges

- jekyll/_cci2/server-3-whats-new.adoc
`nomad-autoscaler` is an anchor not a page, so it 404's in its current state.
Also fixed some whitespace issues.
> nomad-autoscaler is an anchor not a page

- jekyll/_cci2/runner-config-reference.adoc
- jekyll/_cci2/runner-installation-linux.adoc
Add examples and clarification to the Runner config reference.
https://circleci.atlassian.net/browse/RT-238
> Add examples to Runner config reference [RT-238]

- jekyll/_cci2/caching.md
- jekyll/_cci2/persist-data.md
- jekyll/_data/sidenav.yml
- Update the location of the page in the side nav
- Add note about not being able to customize duration of storage
- Change bold note of billable storage to blue info note
- Put link to page inside Caching page
[Jira Ticket](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-114) - first ticket on the N&S agenda
The page needed some minor updates and the location of the page in the nav has been changed for greater visibility.
> N&S edits for Persisting Data

- jekyll/_cci2/persist-data.md
Remove banner about non-customizable retention.
> Remove banner about not customizing retention

- jekyll/_cci2/caching.md
- Tidied text.
- Applied style guide.
- Adding warnings that code samples aren't appropriate for everyone.
https://circleci.atlassian.net/browse/DOCSTEAM-115
> DOCSTEAM-115

- jekyll/_cci2/migrating-from-teamcity.adoc
Replaced legacy image with next-gen image
> migrating-from-teamcity-update

- jekyll/_cci2/hello-world.md
Replaced reference to legacy image with reference to next-gen image
> hello world update

- jekyll/_cci2/examples-intro.md
Replaced legacy images with next-gen images
> example intro update

- jekyll/_cci2/runner-config-reference.adoc
- jekyll/_cci2/runner-installation-docker.adoc
- jekyll/_cci2/runner-on-kubernetes.adoc
Updating the Runner documentation about specifying the host address for server installations
https://circleci.atlassian.net/browse/RT-251
> add host details for server installation

- src/js/app.js
- src/js/site/main.js
[Ticket](https://circleci.atlassian.net/browse/DD-318)
[Preview](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/track-users-print-preview/?force-all) 
- add `checkIfUsersPrint` function to track user print behavior 
- import and invoke function in `app.js`
Adding feature to track if users are printing docs pages to validate if a feature to add Print button is needed
gauging interest first before spending the budget and effort on developing a new print button
> [DD-318] Track if Users are Printing 

- jekyll/_cci2/language-java-maven.md
Replaced instances of legacy images with next-gen images
> java-maven legacy image update

- jekyll/_cci2/language-python.md
Replaced legacy image reference to next-gen image
> language-python-update

- jekyll/_cci2/configuration-reference.md
Replaced reference to legacy image with next-gen image
> configuration reference update

- jekyll/_cci2/language-java.md
> language java update

- jekyll/_cci2/concepts.md
- General content refresh
- Renamed Workspaces, caches, artifacts section to Data Persistence
- Added explanatory text and links to Images section
https://circleci.atlassian.net/browse/DOCSTEAM-59
> DOCSTEAM 59 Concepts refresh 

- jekyll/_cci2/dynamic-config.md
- Removed outdated note about Scheduled Workflows
- Removed random line breaks
Spotted while working on DOCSTEAM-59!
> Removed outdated note about Scheduled Workflows and random line breaks

- jekyll/_cci2/dynamic-config.md
- jekyll/_cci2/webhooks.md
- Removed outdated reference to preview
- Removed random line breaks
Spotted while working on DOCSTEAM 59!
> DOCSTEAM 59 webhooks

- jekyll/_cci2/language-clojure.md
Replaced legacy images with next-gen images
> language-clojure-update

- jekyll/_cci2/concepts.md
> some concepts updates

- jekyll/_cci2/collect-test-data.md
- jekyll/_cci2/databases.md
Completing the items I have from the tracker.
> Translate legacy conv ref to next-gen ones

- jekyll/_cci2/ip-ranges.md
> remove references to preview

- jekyll/_cci2/authentication.adoc
- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/contexts.md
- jekyll/_cci2/env-vars.md
- jekyll/_cci2/workflows.md
- jekyll/_cci2_ja/authentication.adoc
- jekyll/_cci2_ja/configuration-reference.md
- jekyll/_cci2_ja/contexts.md
- jekyll/_cci2_ja/env-vars.md
- jekyll/_cci2_ja/workflows.md
- jekyll/_layouts/classic-docs.html
- src/js/experiments/index.js
- src/js/experiments/kbLinks.js
- src/styles/_sidebar.scss
[Ticket](https://circleci.atlassian.net/browse/DD-321)
This PR adds selective "helpful resource" links to the sidebar at the right of documents on desktop. The links added are being added as an experiment to track the efficacy of these links.
Screenshot:
> Add[Experiment]: more knowledge base articles under "helpful resources"

- jekyll/_cci2/caching-strategy.md
- jekyll/_cci2/caching.md
- jekyll/_cci2/persist-data.md
- jekyll/_cci2/workspaces.md
- jekyll/_data/sidenav.yml
* new "Caching Strategy" page to reduce length of caching page
* Link to Persisting Data page for info on network and storage
* Add steps to find network and storage tabs in the UI to persisting data page
* Add tips for 10x ROI to caching and workspaces docs
> Further caching updates

- jekyll/_cci2/caching.md
https://circleci.atlassian.net/browse/DOCSTEAM-141?atlOrigin=eyJpIjoiYWRmYjBmMGI2YzZiNGZlOWIwYzBjOTA3ZjYzNjQ5ZDYiLCJwIjoiaiJ9
> add note about dangers of very specific cache keys

- src/js/site/main.js
[Ticket](https://circleci.atlassian.net/browse/DD-415) 
- add try catch to local storage for `trackDarkModePreference`
Adding a try - catch to local storage for `trackDarkModePreference` to handle datadog errors 
See [Datadog Error](https://app.datadoghq.com/rum/error-tracking?issueId=98df0398-7d3f-11ec-ac3a-da7ad0900002&start=1644256840073&end=1644260440073&paused=false)
> [DD-415] Add Try - Catch to Local Storage

- jekyll/_cci2/security-server.adoc
Companion PR update the documentation and display the new known log type
> Updates the public documentation with the new know log type "context.secrets.accessed"

- jekyll/_cci2/examples-intro.md
- jekyll/_cci2/executor-intro.md
- jekyll/_cci2/executor-types.md
- jekyll/_data/sidenav.yml
Fixed broken links to AWS and GCP PDFs.
404 errors
> Fixed broken links to PDFs

- jekyll/_cci2/caching.md
* fix typo
* add in warning about increasing storage costs
> Fix warning in caching section

- jekyll/_cci2/optimizations.md
- jekyll/_data/sidenav.yml
Small adjustments to update the optimization page:
- Add to sidenav
- Add warning about copy and paste
- Update outdated info
I have not made the 10x ROI adjustments yet as I think we might end up duplicating information across multiple pages. I think it's better to add that info to the appropriate page(s) as a last step in this Epic.
[Jira Ticket.](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-120)
> Docsteam 120 - optimization page

- jekyll/_cci2/runner-faqs.adoc
Change some text to a warning about possibly incurring more costs for managing state vs reproducibility.
Add some links to relevant information about CircleCI data persistence concepts.
There was not clear enough information that some data persistence methods could incur more costs.
[Jira ticket](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-126)
> Adjust runner faq

- jekyll/_cci2/executor-types.md
> fix docs bug

- README.md
Add a link to our testing checklist inside of README file
For easy access and reminder
> Add a link to our testing checklist inside of README file

- crowdin.yml
The objective of this change is to translate snippets.
conversation: https://circleci.slack.com/archives/CJF173R4H/p1644473760605769
> Include snippets

- src/js/experiments/snippetFeedback.js
- src/js/experiments/snippetFeedback.test.js
- src/styles/_snippets.scss
[Ticket](https://circleci.atlassian.net/browse/DD-431)
[Preview Link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-431/update-code-feedback-copy-preview/2.0/migrating-from-github/?force-all)
- update copy for feedback text prompt 
- update feedback element class name
- update test name and cases 
Update the copy code feedback survey to say “Was this code helpful? Yes/No” to remove ambiguity around what the _feedback_ is about.
**Before:**
**After:**
> [DD-431] Update copy code feedback survey

- jekyll/_includes/global-nav.html
Reverts circleci/circleci-docs#6377
> Revert "[DD-417] Update the Sign-up CTA button verbiage "

- jekyll/_cci2/runner-config-reference.adoc
- Split the simple and custom examples up with preamble for each.
> Update runner-config-reference.adoc(2) [RT-409]

- jekyll/_cci2/server-3-install-prerequisites.adoc
A misplaced comma in the recommended policy
> [SERVER-1660] misplaced comma in IAM policy

- jekyll/_cci2/code-coverage.md
- jekyll/_cci2/server-3-install-post.adoc
- jekyll/_cci2/server-3-operator-backup-and-restore.adoc
SEO audit found broken links, this PR updates them to live links :-D
> update some broken links

- jekyll/_cci2/executor-types.md
Just a tiny copy update on the notes about using custom-built images.
Thought the sentence could be shortened. :)
> simplify notes on using a custom-built image

- jekyll/_cci2/server-3-install-build-services.adoc
The numbering got out of whack
The wrong SG was recommended
The VPC ARN was recommended when it is the VPC ID that is needed.
> [SERVER-1660] AWS IRSA Doc fixes

- jekyll/_cci2/persist-data.md
Change date of N&S billing
The date has been pushed back
> Change date for N&S

- jekyll/_cci2/faq.md
Change date for N&S billing
The date has been pushed back
> Change N&S date

- jekyll/_cci2/server-3-install-build-services.adoc
Small fix, Used "max" instead of "min".
> [SERVER-1660] max->min for nomad autoscaler

- jekyll/_cci2/faq.md
also related to this: https://github.com/circleci/circleci-docs/pull/6410
UI is not live yet, so please do not merge yet.
> prepare for new network transfer info in resources tab - not ready to merge

- jekyll/_cci2/persist-data.md
related to https://github.com/circleci/circleci-docs/pull/6411
> prepare for new network information in resources tab -not ready to merge yet

- jekyll/_cci2/ip-ranges.md
Making the same changes to IP ranges as the patch-PR from Sebastian that is failing due to image path.
The other PR is failing.
> Add IP pricing info with image

- jekyll/_cci2/ip-ranges.md
> add link to discuss post

- jekyll/_cci2_ja/plan-free.adoc
update the path of a snippet with the /ja/ subdirectory
> update path for the snippet

- jekyll/_cci2/getting-started.md
- Applying recommendations from content audit.
- Also simplified the reader workflow by leaving out the option to "use an existing repository" 
- Directed readers to commit a starter CI pipeline (this UI was also updated recently: https://circleci.com/changelog/#express-project-setup)
Help provide a smooth onboarding experience for new CircleCI users.
> Refresh of Your first green build

- jekyll/_cci2/architecture.adoc
- jekyll/_cci2/aws.adoc
- jekyll/_cci2/credits.md
- jekyll/_cci2/high-availability.md
- jekyll/_cci2/install-overview.adoc
- jekyll/_cci2/plan-overview.adoc
- jekyll/_cci2/runner-overview.adoc
- jekyll/_cci2/update-2.14.1-to-2.15.0.md
- jekyll/_cci2/upgrading.md
Updating the support plan names (ex: Platinum -> Premium)
Some of the support plan names haven't been updated yet.
[Jira Ticket](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-201)
> Fix plan mapping

- jekyll/_cci2/docker-to-machine.md
Remove pre installed list.
Will be on DevHub in the future.
> remove pre-installed list

- jekyll/_cci2/docker-layer-caching.md
Changed Docker Layer Caching to Docker layer caching
> Matching Docker layer caching mentions to our style guide

- jekyll/_data/sidenav.yml
Ja sidenav has not been updated for 5 months! The purpose of this PR is to fill the gap.
previous commit:
https://github.com/circleci/circleci-docs/commit/d6eba87ee23833eb7798109bb5396cd8825fc884
> sync-ja-sidenav-with-en-sidenav

- jekyll/_cci2/server-3-operator-android.adoc
Adding docs on how server customers can use Android builders
https://circleci.atlassian.net/browse/SERVER-1251
> Android builder support for server

- jekyll/_cci2/configuration-reference.md
> add examples for deploy step

- .github/CODEOWNERS
Reverts circleci/circleci-docs#6496
> Revert "Temporarily update CODEOWNERS"

- jekyll/_cci2/hello-world-windows.md
> add link to 2022 details

- jekyll/_cci2/hello-world-windows.md
> call attention to new image available

- jekyll/_cci2/arm-resources.md
Remove extra word.
Duplicate word which went unnoticed oops.
> Remove duplicate word

- src/js/experiments/signupLinksCta.js
https://github.com/circleci/circleci-docs/pull/6447 did not add track control events. This PR adds that.
> Add: track event to control link.

- jekyll/_data/sidenav.yml
> Update Japanese sidenav

- jekyll/_cci2/server-3-install-prerequisites.adoc
Adding a new supported version to the 3.4 release.
Also cleaned up some trailing whitespace in the doc.
> Support k8s 1.23 with the 3.4 release

- src/styles/pages/troubleshooting-and-common-issues.scss
I thought I added this small change and pushed this to #6481 , but I did not, and then I merged the previous branch.
> Add: scroll margin top to h1's

- jekyll/_cci2/server-3-install-build-services.adoc
Fixed some typos and added syntax to some snippets where missing.
> Typo fix in server installation guide

- src/styles/_sidebar.scss
Add a hover state to the side nav.
It's been bothering me for months that our docs don't have a hover state on the side nav.
> Add hover to side nav

- jekyll/_cci2/server-3-install-build-services.adoc
- jekyll/_cci2/server-3-install-migration.adoc
- jekyll/_cci2/server-3-operator-backup-and-restore.adoc
- jekyll/_cci2/server-3-operator-vm-service.adoc
UI text change, and reference IP as well as hostname. Hostname is AWS terminology, IP more inclusive for GCP users.
> Server installation docs updates

- jekyll/_cci2/server-3-install-build-services.adoc
[SERVER-1713](https://circleci.atlassian.net/browse/SERVER-1713) 
Add New variable in Nomad Example.  
[SERVER-1713](https://circleci.atlassian.net/browse/SERVER-1713)
> server-1713 | added new example for nomad

- jekyll/_cci2/server-3-install-build-services.adoc
- jekyll/_cci2/server-3-install-post.adoc
- jekyll/_cci2/server-3-install-prerequisites.adoc
Added Note to delete the static keys if enabling Workload Identity 
[Server-1714](https://circleci.atlassian.net/browse/SERVER-1714)
> server-1714 | Added note to delete the SA static keys

- jekyll/_cci2/openid-connect-tokens.adoc
- jekyll/_data/sidenav.yml
- jekyll/_includes/snippets/built-in-env-vars.md
A new page for OIDC
Table of claims/descriptions:
New stuff is fun and should be documented!
[Jira ticket](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-227)
> Add new OIDC page

- jekyll/_cci2/collect-test-data.md
Fixed some broken links, change link spacing for syntax reasons, added Test Insights to suggested reading
I noticed some links were not going to the correct place.
> Fix broken links, minor changes

- jekyll/_cci2/server-3-install-prerequisites.adoc
- jekyll/_config.yml
Update recommended KOTS version to 1.65.0
https://circleci.atlassian.net/browse/SERVER-1696
> Update recommended KOTS version to 1.65.0

- jekyll/_cci2/concepts.md
Organized concepts in alphabetical order
https://circleci.atlassian.net/browse/DOCSTEAM-143
> Organized concepts in alphabetical order

- jekyll/_cci2/concepts.md
Added missing ID attributes
Crowdin bot feedback.
> Added ID attributes

- jekyll/_cci2/ip-ranges.md
> [do not merge yet] needs an image update as well

- jekyll/_cci2/v.2.19-overview.adoc
- scripts/build_pdfs.sh
document release of server 2.19.5
> add fixes for server 2.19.15

- src/js/experiments/gettingStartedGuide.js
- src/styles/main.scss
- src/styles/pages/_getting-started.scss
[Ticket](https://circleci.atlassian.net/browse/DD-454)
[Preview](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/ts-dd-454-preview/?force-all)
*Note*: 
I tried to set the base branch for merge to be DD-450, but GitHub responded with:
> There are no new commits between base branch 'DD-450/getting-started-experiment-boilerplate' and head branch 'tees/DD-454/getting-started-new-badge'
This is maybe because I accidentally pushed my code to DD-450. I undid my commits but I'm not sure why I'm unable to set this Pr to merge  to `DD-450/getting-started-experiment-boilerplate`
> [DD-454] - Add "new" badge to sidebar for Quickstart Guide

- cypress/integration/sidebar/sidebar.spec.js
Jira [link](https://circleci.atlassian.net/jira/software/c/projects/DD/boards/477?modal=detail&selectedIssue=DD-523)
All tests for cypress were failing this makes all the tests pass but 1. 
Due to leaving the platform task had a time constraint to fix as many as possible.
> [DD-523] Fix cypress sidebar tests

- jekyll/_cci2/server-3-whats-new.adoc
SERVER-1734
We actually fixed these issues in 3.3.1 👍
> Changelog had some erroneous known issues

- src/js/experiments/popupCta.js
The Popup experiment (#6521) needs to be re-run with a new experiment key and amplitude keys due to errors in the original experiment
> Make new experiment

- jekyll/_cci2/persist-data.md
- jekyll/_cci2/plan-performance.adoc
- jekyll/_cci2/plan-scale.adoc
- jekyll/_cci2/plan-server.adoc
Since storage controls are not available to free users:
- Slight change in wording on the persisting data page.
- Add storage controls to list of features on paid plans.
Figured it would be nice to add on the plans page that this feature exists.
> Storage feature

- docs/Content-Reuse.md
Added AsciiDoc example
https://circleci.atlassian.net/browse/DOCSTEAM-195
> Added AsciiDoc example

- jekyll/_cci2/server-3-install-build-services.adoc
One merge conflict got missed in a PR that was merged today, this fixes it.
> fix merge conflict included in text

- jekyll/_cci2/jobs-steps.md
- jekyll/_data/sidenav.yml
ticket: https://circleci.atlassian.net/browse/DOCSTEAM-176?atlOrigin=eyJpIjoiNWZlZjdjMDJjN2JhNDQwY2JjNTE2NTk2MjVmYzRiYTQiLCJwIjoiaiJ9
reinstate jobs and steps overview in sidebar and update usage examples.
I'm doing this now because I need somewhere to link to for another ticket I'm working on: https://circleci.atlassian.net/browse/DOCSTEAM-32?atlOrigin=eyJpIjoiMTQwN2M0ODRlNjRlNDQyYWFiMzk1ZjRhNjRjZjBkNzYiLCJwIjoiaiJ9
> update jobs guide with examples

- jekyll/_data/sidenav.yml
- jekyll/assets/img/icons/sidebar/orbs.svg
> Orbs at top level of navigation in sidebar

- jekyll/_cci2/ip-ranges.md
> update to be more accurate given recent re-architecture

- jekyll/_cci2/circleci-images.md
> Fix spelling of Postgres

- jekyll/_cci2/slack-orb-tutorial.adoc
- jekyll/_data/sidenav.yml
- Changed title of tutorial.
- Added links to sidenav.
Feedback on https://circleci.atlassian.net/browse/DOCSTEAM-225
> DOCSTEAM 225 

- src/js/experiments/gettingStartedGuide.js
- src/js/site/toc.js
Small bug fix found while prod testing DD-450 Getting Started Experiment. See info on PR [here](https://github.com/circleci/circleci-docs/pull/6544)
Need to add variation to tracking
> [DD-450] Final tweaks for getting started experiment

- jekyll/_cci2/parallelism-faster-jobs.md
> make clear behavior for runner

- jekyll/_cci2/runner-installation-mac.adoc
- jekyll/_cci2/runner-on-kubernetes.adoc
- Small changes to the Kubernetes page
- Small changes to the macOS page
Taking care of some last few discrepancies between the UI and the docs. 
> Minor runner updates

- jekyll/_cci2/runner-installation-linux.adoc
> some updates

- jekyll/_cci2/configuration-reference.md
> update machine executor disk size

- jekyll/_cci2/arm-resources.md
> update machine executor resources

- jekyll/_cci2/config-overview.md
- jekyll/_cci2/configuration-reference.md
- jekyll/_cci2/deployment-integrations.adoc
- jekyll/_cci2/local-cli.md
- jekyll/_cci2/orb-concepts.md
- jekyll/_cci2/workflows.md
- jekyll/_cci2_ja/orb-concepts.md
redirects were broken due to missing `/`
> fix redirects

- jekyll/_cci2/executor-types.md
Fix the formatting of the macOS storage table to match the others on this page.
> Fix table formatting

- jekyll/_data/sidenav.yml
Fixing a link error in the sidenav reported by the SEO team.
> fix link error

- jekyll/_cci2/glossary.adoc
- jekyll/_cci2/migrating-from-jenkins.md
- jekyll/_cci2/openid-connect-tokens.adoc
- jekyll/_cci2/project-build.md
- jekyll/_includes/snippets/features-of-circleci.adoc
Fixed some link syntax to fix some 404s.
> fix links etc to solve 404s

- jekyll/_cci2/arm-resources.md
Update list of arm machine images that are available
> update arm resources list

- jekyll/_cci2/language-javascript.md
- jekyll/_cci2/language-python.md
Reviewing language-specific quickstart guides created by docs disco
To make it clear who the audience is, what prerequisites are, and simplify config as far as possible.
* Updated links to sample project to be current managed CFD project
* I've checked the pipeline passes when rewriting the config using this guide
* Added a prerequisites section
* Moved workflows to after jobs are created to make things simpler
* changed config to use default executors from orbs
> language quickstart review

- jekyll/_cci2/adv-config.md
Update postgres image version
The version we are using is very out of date and was brought up in a GH issue
> Update postgres image version

- jekyll/_cci2/server-3-install-build-services.adoc
Tiny fixes.
Fix typo in realitycheck project name.
Add link to realitycheck project.
> Fix typo in realitycheck project name

- jekyll/_cci2/openid-connect-tokens.adoc
Add note about CCI not supporting AWS ECR OIDC authentication.
This was an ask from the team working on the OIDC support.
> AWS ECR OIDC support

- jekyll/_cci2/server-3-install-prerequisites.adoc
Update KOTS download link
Fixes #6718 
It was broken
> fix download link

- jekyll/_cci2/executor-types.md
We expanded the `12.4.0` image for the Gen2 resource class to include more disk space.
> Update macOS VM storage for gen2 12.4.0 image

- src/js/experiments/docsDetangling.js
- src/js/experiments/index.js
Jira: [DD-647](https://circleci.atlassian.net/browse/DD-647)
This is the experiment we will be using to do a slow rollout of the new platform.
> [DD-647] Docs Detangling redirect Experiment

- jekyll/_cci2/runner-scaling.adoc
> remove reference to custom plan

- jekyll/_cci2/gitlab-vcs-support.adoc
Fix typos, minor edits for clarification.
> Edits for Gitlab preview doc

- jekyll/_cci2/server/Installation/3-install-execution-environment.adoc
We want to reference Helm instead of KOTS.  Please be critical, I have looked at a lot of text over the last few days...
We are getting rid of KOTS.
> [SERVER-1666] 4.0 execution

- jekyll/_cci2/server/Operator/externalizing-services.adoc
External RabbitMQ configuration in `helm` value file for `Server 4.0` 
[SERVER-1820](https://circleci.atlassian.net/browse/SERVER-1820)
> server-1820 | 4.0 External Rabbitmq

- jekyll/_cci2/server/Operator/troubleshooting-and-support.adoc
no kots to troublshoot anymore
> [SERVER-1666] remove kots references

- jekyll/_cci2/server/Overview/overview.adoc
> [SERVER-1666] 4.0 overview

- jekyll/_cci2/server/Operator/build-artifacts.adoc
Remove KOTS references, add helm instructions.  was this worth it's own PR?  you decide!
> [SERVER-1666] server artifacts

- jekyll/_cci2/server/Operator/metrics-and-monitoring.adoc
> [SERVER-1666] 4.0 monitoring

- jekyll/_cci2/gitlab-vcs-support.adoc
This change is to resolve asciidoctor warning.
This file has not been imported to Crowdin due to an error. I imported the fixed file manually which went well, so it would be great if we have this in master :)
> heading level adjustment

- jekyll/_cci2/server-3-faq.adoc
- jekyll/_cci2/server/Operator/faq.adoc
> [SERVER-1666] Cj/4.0 faq

- jekyll/_cci2/server-3-install-prerequisites.adoc
- jekyll/_cci2/server/Installation/1-install-prerequisites.adoc
- jekyll/_cci2/server/Installation/6-install-upgrade.adoc
- jekyll/_config.yml
Added helm diff as a prereq
Removed KOTS references
added helm instructions for upgrades
> remove kots references, add helm instructions

- jekyll/_cci2/workflows.md
> Update workflows banner

- jekyll/_cci2/configuration-reference.md
Update date in banner of config ref
> Update config ref banner

- jekyll/_cci2/server/Operator/vm-service.adoc
no KOTS anymore.  Add helm instructions for setting up VM service
> [SERVER-1666] 4.0 vm

- jekyll/_cci2/gitlab-vcs-support.adoc
> Add viewer as a supported role

- jekyll/_cci2/examples-and-guides-overview.adoc
- jekyll/_includes/snippets/language-guides.adoc
- jekyll/_includes/snippets/language-guides.md
This page will serve as the new overview/landing page for sample apps and guides available to readers who want to learn CircleCI using examples.
This new page will be added to the sidenav, replacing "Other supported languages" (i.e. the Tutorials page). That as well as page redirects will be done in #6869 .
The Tutorials page had content that didn't seem relevant or useful anymore, and ideally we would have a page with a title and url that was more indicative of its intended purpose. "Tutorials" also more specifically refers to content that walks a reader (new users in particular) through guided steps. A lot of the examples that we want to feature aren't so much "tutorials" but more "how-to guides" which also assume a certain level of knowledge. "Examples and Guides Overview" will be a …
> Add new Examples and Guides Overview

- jekyll/_cci2/tutorials.md
Archived pages opened up to 404s instead of being redirected to Tutorials.
> Trailing slashes for redirects

- jekyll/_cci2/introduction-to-yaml-configurations.adoc
- jekyll/_data/sidenav.yml
Quick PR to add the new config editor page to the side nav now that another PR has been merged and adds the new Onboarding section to Getting Started.
This page was inside the Configuration section, but since it's an intro to the in-app config editor, and can be used as a tool for users to gauge if this feature is useful to teams, it should be more visible in the intro section.
> Add config editor to side nav
