jekyll/_cci2/orbs-best-practices.md
Add best practices on installing binaries via Orbs with parameterized installation paths.
Reduce conflicts with orbs needing to interact with root when in environments where root is not accessible.
=> Install path best practices.

jekyll/_cci2/creating-orbs.md
On the live page, the link to "Validate and Publish Your Orb" appears to be broken and does not work. Perhaps it should instead link to: https://circleci.com/docs/2.0/orb-author-validate-publish/ ?
=> Link: "Validate and Publish Your Orb" doesn't work

jekyll/_cci2/java-oom.md
`LEIN_JVM_OPTIONS` -> `LEIN_JVM_OPTS`
=> Correct Leiningen environment variable in Java docs

.circleci/config.yml
Upgrades Markdown Proofer to v0.3. The new version allows users to specify multiple directories to check on the same line, saving the Docs config 9 lines.
=> Upgrade Markdown Proofer.

jekyll/_cci2/creating-orbs.md
This is to clear up any confusion in case someone tries to use a service account or machine user with only read permissions
=> note on user permissions for publishing

jekyll/_cci2/docker-layer-caching.md
The volume is removed if the disk has not been used for 7 days (ref: https://github.com/circleci/vm-service/blob/d953738/src/circleci/vm_service/gc.clj#L108).
Associated Slack discussion: https://circleci.slack.com/archives/C4C9J5KHN/p1573029882459000
=> Update volume deletion time period from 14 to 7 days

jekyll/_cci2/configuration-reference.md
Update use of `when` in workflows in the config reference
=> correct usage of when in workflows

jekyll/_cci2/add-ssh-key.md
Running `ssh-agent -D` puts `ssh-agent` into foreground mode, which will cause a build to run until timeout.
Running `ssh-add -D` drops all agent keys, which is what the docs is actually suggesting.
The command suggested is totally wrong.
=> Fixes incorrect command in "Adding an SSH Key to CircleCI" that will break build

jekyll/_cci2/env-vars.md
----
`CIRCLE_COMPARE_URL` is not present in v2.1 environments, but we do have an alternative, as outlined in https://discuss.circleci.com/t/is-circle-compare-url-still-a-thing/33366/2 -- we'll be trying to work this more fully into the official documentation, but in the interest of providing clarity early on I think this helps.
We've seen some posts in discuss about this, most recently in https://discuss.circleci.com/t/is-circle-compare-url-still-a-thing/33366 and I thought it would be nice to provide a bit more information.
=> Be explicit about CIRCLE_COMPARE_URL being absent from v2.1

jekyll/_cci2/_aws-install.adoc, jekyll/_cci2/_ops-guide.adoc
Some code blocks run off the PDF page and it's not handled well. Ends up with badly formatted code. This option attempts to resize the text to make it fit.
=> add autofit option to auto shink text in PDF output

jekyll/_cci2/testing-ios.md
- 11.2.0 has been removed, builds now run on 11.2.1.
- 11.2.1 beta replaced with GM version.
- 11.3 beta has been added.
=> 3 Changes to Xcode Version Docs

jekyll/_cci2/parallelism-faster-jobs.md
Removing Typo: Redundant use of "Machine" word.
I think it will look good this way.
=> Removing Typo: Redundant "Machine" Word

jekyll/_cci2/status.md
Currently we are directing people to info on our legacy container plan when they are having performance issues. This PR points them to the pricing page and our docs info on using credits instead.
=> link to performance plan pricing for those with queueing builds

jekyll/_cci2/customizations.adoc
path should be prepended by "/etc"
Add /etc to beginning of filepath for CIRCLE_DISPATCHER_RESOURCE_DEF
Incorrect filepath
=> Fix filepath for CIRCLE_DISPATCHER_RESOURCE_DEF

jekyll/_cci2/local-cli.md
Update shamelessly stolen from https://github.com/CircleCI-Public/circleci-cli/issues/79#issuecomment-505836719
This describes how to execute local jobs when the CircleCI config version is 2.1
https://github.com/CircleCI-Public/circleci-cli/issues/79
=> Update execute instructions for 2.1

jekyll/_cci2/testing-ios.md
Added a note about the Cocoapods 1.8 CDN
This will speed up builds and will be less reliant on our hosting of the specs (there have been cases where AWS outages have caused jobs to fail due to relying on the script)
=> Add a note about the Cocoapods 1.8 CDN

jekyll/_cci2/testing-ios.md
The method to switch Ruby versions has changes on macOS Catalina. Update
the docs to detail how to set the Ruby version older and newer images.
=> Using Ruby is different on Catalina

jekyll/_cci2/configuration-reference.md
The use of `when` under workflows is available in 2.1 config without using the v2 API, though it's most common use is with pipeline parameters passed via the v2 API. This PR updates the language to make that clearer to the reader.
=> Clarifying the use `when` under workflows

jekyll/_cci2/local-cli.md
This fixes the formatting for a heading.
It looked wrong:
=> Fix formatting for Add SSH Keys heading

jekyll/_cci2/java-oom.md
Adds more context for the UseContainerSupport flag, and why CircleCI builds can get OOM errors when running in containers.
Fixes #3938
=> Add information on UseContainerSupport in CircleCI

jekyll/_cci2/architecture.adoc
Note that LDAP authentication will fail if `domain-service` is down.
`domain-service` is responsible for LDAP authentication proper, while
`federations-service` binds the resulting LDAP identities to CircleCI
User objects.
=> Add a note on LDAP interaction for domain-service

jekyll/_cci2/optimization-cookbook.md
The sub TOC was not rendered correctly (see screenshot), and some links were showing URLs rather than appearing as links:
=> fix some linking issues

jekyll/_cci2/building-docker-images.md
Update the docker installation example, including moving installing a custom docker version out of the main body of the example.
Improves the security, and also makes it hopefully a little clearer.
Prompted by seeing a tweet suggesting the older method was insecure, which is arguably true.
The example was using very old versions of things.
=> Update the docker installation example

jekyll/_cci2/concepts.md
I changed the indentation in the YAML example.
It does not seem to be valid YAML (fails `cicreci config check`).
=> Fix invalid indentation in config example

jekyll/_cci2/aws.adoc
This page was under the heading for 2.18 server installation
Keep the server version consistent.
The instructions should be clear about which server version is being installed
=> Update server version from 2.17 to 2.18

jekyll/_cci2/configuration-reference.md, jekyll/_cci2/gh-bb-integration.md
Describes how to add custom SSH host keys to pipelines in the event a user is using custom checkout steps.
A customer mentioned that we don't have any documentation regarding the default checkout step that we provide, specifically regarding the SSH authenticity keys we add. This helps clarify this, and provides a sample command for fetching keys from their own servers in the case they have to authenticate with other servers safely.
=> Host authenticity keys

jekyll/_cci2/testing-ios.md
These two paragraphs are inaccurate and refer to problems that relate to 1.0 builds.
=> Remove iOS docs that refer to 1.0 issues

jekyll/_cci2/orb-author.md
The block of text for "quickstart" wasn't highlighting that these steps are actually required. And these steps were only documented one other place (that isn't clear either). 
My personal opinion is that the content in this "publish your first orb" section should instead be moved to the [Validate and Publish](https://circleci.com/docs/2.0/orb-author-validate-publish/) page. 
But I lost a lot of time not finding this info when I was finally ready to publish. _(I also assume most people don't "quick" start with publishing, but rather start with inline orbs)_
=> ORBS: make the call to the required steps stand out more

jekyll/_cci2/admin-faq.adoc, jekyll/_cci2/architecture.adoc, jekyll/_cci2/authentication.adoc, jekyll/_cci2/backup.adoc, jekyll/_cci2/build-artifacts.adoc, jekyll/_cci2/certificates.adoc, jekyll/_cci2/customizations.adoc, jekyll/_cci2/gpu.adoc, jekyll/_cci2/jvm-heap-size-configuration.adoc, jekyll/_cci2/language-scala.md, jekyll/_cci2/monitoring.adoc, jekyll/_cci2/nomad-metrics.adoc, jekyll/_cci2/nomad.adoc, jekyll/_cci2/ops.adoc, jekyll/_cci2/overview.adoc, jekyll/_cci2/proxy.adoc, jekyll/_cci2/security.adoc, jekyll/_cci2/server-ports.adoc, jekyll/_cci2/single-box.md, jekyll/_cci2/troubleshooting.adoc, jekyll/_cci2/usage-stats.adoc, jekyll/_cci2/user-accounts.adoc, jekyll/_cci2/v.2.17-overview.md, jekyll/_cci2/v.2.18-overview.md, jekyll/_cci2/vm-service.adoc, jekyll/_includes/snippets/server-only.adoc, jekyll/assets/css/asciidoc.css, jekyll/assets/css/main.scss
Some cloud users are finding their way to server docs, probably through keyword search, and finding info not relevant to them. This PR is an idea to more clearly show which content is only for server system admins.
In practice, looks like this:
=> indicate what content is only for server admin

jekyll/_cci2/hello-world-windows.md
The `vs2019` executor was renamed into `default`.
=> Update the Windows docs to use the `default` executor

jekyll/_data/sidenav.yml
Fixing typo - 'Architechture' to 'Architecture'
=> Fixing typo in side nav

jekyll/_cci2/hello-world-windows.md
The only occurrence of 1.0.0 left in that doc, replacing with 2.2.0 (more recent).
=> Update the Windows orb version to something more recent

jekyll/_cci2/executor-intro.md, jekyll/_cci2/executor-types.md, jekyll/_cci2/hello-world-windows.md
The `resource_class` part is important as otherwise the jobs will try to run on Linux VMs with a Windows image which won’t work.
=> Add the missing resource_class part to the Windows Server snippet

jekyll/_cci2/hello-world.md
Remove extraneous indents in "Hello World" config example
I've recently hosted a CircleCI 101 training, and about 2/3 of the participants (including myself when I prepared the training 😳) fell for the following inconsistency in the documentation :
1. In order to create a new CircleCI config file, participants would copy paste the config example of "Echo Hello World on Linux" into a new file in their IDE
2. Unfortunately, all copy-pasted lines would be indented by two extraneous spaces
3. The participants would assume only the leading spaces of the first line were extraneous, and would remove them
4. As such, the `jobs` line would be indented by 2 more spaces than the `version` line, which is not a valid configuration.
5. Participants would push the commit with the invalid config, a job …
=> Remove extraneous indents in config example

jekyll/_cci2_ja/concepts.md
Removed unnecessary spaces in japanese concepts.md.
The code block looked broken.
=> Fix markdown syntax in concepts.md (ja)

src-js/instantsearch.js
97% of our queries from docs to Algolia were blank. This is because instantsearch.js fires a query upon load by default (I think).
This change borrows a customization from circleci.com search to customize the search function and test whether the query is empty before executing it.
https://circleci.atlassian.net/browse/CIRCLE-23271
=> [CIRCLE-23271] Suppress blank search requests to Algolia

jekyll/_cci2/executor-intro.md, jekyll/_cci2/executor-types.md, jekyll/_cci2/hello-world-windows.md
`resource_class` is only available under `machine` in 2.1 config, in 2.0 it's required to be at the same level as the executor.
=> Fix the indentation for the resource class statement for Windows on Server

jekyll/_cci2/collect-test-data.md
Improved consistency: the pytest example was the only one that diverged from the "test-results" nomenclature.
=> PyTest: test-reports -> test-results

jekyll/_includes/snippets/pipelines-benefits.adoc
Fixed typos, changed 'resuable' into 'reusable'
It was distracting me while reading pipeline benefit documentation.
=> Fix typos in `pipeline-benefits.adoc`

jekyll/_cci2/status.md
Fixes a typo in the status document (`infomration` => `information`).
There was a typo.
=> Fix typo in Status document

src-api/source/includes/_overview.md
Clarify the handling of `Accepts` header for the API.
Sometimes, the API returns Clojure EDN syntax rather than JSON. After some
investigation by customers, it appears this happens when the Accept header is 
blank, which is the default for some request frameworks (e.g `request` for 
Python). This change helps clarify this quirk.
=> Clarify data formats returned by the API

jekyll/_cci2/status-badges.md
As the new UI rolls in, we'll be removing the settings page detailing the generation of a status-badge. In lieu of that, these documentation changes can describe how a user can construct their own status badge.
Related [CIRCLE-23454](https://circleci.atlassian.net/browse/CIRCLE-23454).
=> Describe how to create status badge (pending removal of old status badge page)

jekyll/_cci2/executor-intro.md, jekyll/_cci2/executor-types.md
fix inconsistency in docs - we were recommending two different linux images for `machine` including an old default.
Slack convo here: https://circleci.slack.com/archives/C0KBNJGRH/p1578482968001900
=> [WIP] update recommended machine image

jekyll/_cci2/executor-types.md
It seems this may be out-of-date, as the machine executor can now accept the resource_class key with the options medium and large.
Reference:
https://circleci.com/docs/2.0/configuration-reference/#machine-executor-linux
In the table comparing the Docker to Machine executor, I changed the value of the cell for Configurable resources (CPU/RAM), Machine from 'No' to 'Yes'.
=> Change machine `Configurable resources (CPU/RAM)` to Yes

jekyll/_cci2/orb-author.md
Update tag of ruby executor from 1.4.2 to 2.7.0
I tried to run this example inline code as it stands and received the following error:
`Error response from daemon: manifest for circleci/ruby:1.4.2 not found`
Red build: https://circleci.com/gh/annapamma/training_01_Hello_World/203
I updated the Ruby version and was able to run the sample code as expected.
Green build: https://circleci.com/gh/annapamma/training_01_Hello_World/205
=> Update ruby executor

jekyll/_cci2/jira-plugin.md
The orb integration to report build statuses depends on JWT tokens and Atlassian Connect, which is only available on their cloud offering. This is outside the control of CircleCI.
This change updates our docs to be explicit about this difference. Other features like "create an issue" will still work on server.
Adds explicit Cloud language to orb section
Amex was trying to get it work on server.  Our marketplace listing correctly made this distinction but our docs did not.
https://circleci.slack.com/archives/C0G6NTU4B/p1578515170003200
=> Explicit about need for Jira Cloud for orb support

jekyll/_cci2/hello-world-windows.md
The original code is missing the example for bash because the default shell is Powershell.
Using echo alone does not mean the correct shell is being used, hence the example adds the AND connective that is different in each of the 3 shells.
=> MIssing example for bash improved

jekyll/_cci2/configuration-cookbook.md, jekyll/_cci2/jira-plugin.md, jekyll/_cci2/notifications.md, jekyll/_cci2/optimization-cookbook.md, jekyll/_cci2/orbs-user-config.md, jekyll/_cci2/pipeline-variables.md, jekyll/_cci2/reusing-config.md, jekyll/_includes/snippets/enable-pipelines.md
This follows along closely after @rosieyohannan 's https://github.com/circleci/circleci-docs/pull/3988 in which we are using a `snippets` folder for commonly used pieces of the docs. In this case, I am creating a snippet that instructs the user on how to enable pipelines for their project, which occurs (as far as I could grep) at least 5 times in our project
=> Create `enable-pipelines` snippet.

jekyll/_includes/global-nav.html, jekyll/_plugins/language_relative_url_filter.rb, jekyll/_plugins/language_url_prefix.rb, jekyll/_plugins/outer_url_filter.rb
Since this project is not fully internationalized, we don't have an easy way to generate language-relative URLs for linking within a language site.
We can work around that though by using the existing `lang` param on pages that are part of non-English page collections.
This adds a plugin and Liquid filter to generate a URL to "outer" or the circleci.com site, and employs it on links to outer in the global nav include.
https://circleci.atlassian.net/browse/CIRCLE-23312
=> [CIRCLE-23312] Make global nav links language-aware

jekyll/_cci2/reusing-config.md, jekyll/_data/sidenav.yml
Orbs reference doesn't seem like the right name for this doc. It covers all reusable content. Changing to reflect this and adding a link outside the orbs section to make it easier to find.
=> change orbs ref to reusable config ref

jekyll/_cci2/configuration-reference.md
Added a footnote below the executors info table to explain the superscripted `(1)` note which indicates that there is a selection limit of one for choosing an executor
The options `docker` `machine` `macos` and `windows` all have a `(1)` superscript but no close footnote to explain its meaning. Looking at other similar footnotes, it can be deduced that this is supposed to mean that there is a selection limit of exactly 1 for a chosen executor.
=> Add executor footnote for executor selection limit

jekyll/_cci2/api-intro.md
Just noticed in the API intro doc there were errors in the auth command which meant it didn't work when copy pasted. This fixes the errors (I hope!)
=> fix auth command syntax

jekyll/_cci2/collect-test-data.md
'pretty' needs to be prepended with the format flag. Otherwise the commands gives error 'No such file or directory - pretty'
The command in the documentation gives an error - mentioned in the paragraph above. This change fixes that error.
=> Fix invalid cucumber command

jekyll/_cci2/gh-bb-integration.md
Remove reference to the [adding ssh keys document](https://circleci.com/docs/2.0/add-ssh-key) document from the "Enable Your Project to Check Out Additional Private Repositories" section.
The [adding ssh keys document](https://circleci.com/docs/2.0/add-ssh-key) is not relevant to enabling of a project to check out additional private repositories.  That document describes the addition of an SSH key *for deploying to one's server*, not for checking out repositories.
=> Do not reference irrelevant add-ssh-key page

jekyll/_cci1/configuration.md, jekyll/_cci1/faq.md, jekyll/_cci1/index.md, jekyll/_ccie/overview.md, jekyll/assets/code/project_import_export.clj
Reflect our removal of support for several chat notification integrations in docs.
Reopens https://github.com/circleci/circleci-docs/pull/4006 with a few additional edits.
Update docs to reflect the currently supported list of chat integrations.
Leave archive docs unmodified, and hold on to open-source acknowledgements for `clj-campfire` until the changes are released and made permanent in Server.
We've removed support for Campfire notifications in Cloud and are in the process of removing it from Server, so the docs should be updated to reflect this. We've previously removed HipChat notification support, so mentions of it should also be removed from docs.
Campfire support removal ticket: [CIRCLE-23110](https://circleci.atlassian.net/browse/CIRCLE-23110).
Re: …
=> [CIRCLE-23110] Remove unsupported notification docs

jekyll/_cci2/testing-ios.md
Added disabling the Homebrew auto-updater and iOS sim crash report collection to the best practices section
Disabling the Homebrew updater can save users 2-4 minutes per job and, in some instances recently, Homebrew updates have introduced bugs for customers.
Collecting iOS sim crash reports helps both users and support diagnose UITest failures.
=> iOS Best Practises Additions

jekyll/_cci2/language-ruby.md
Updated link for "CircleCI Docker Images" from **http://circleci.com/docs/2.0/circleci-images** to **https://circleci.com/docs/2.0/circleci-images/**
We ran an SEO audit through https://ahrefs.com/ and it reported the link was causing a redirect chain.
=> Updated CircleCI Docker Images link

jekyll/_cci2_ja/language-ruby.md
SEO audit - causing redirect chain issue
Updated link for "CircleCI Docker イメージ" from **http://circleci.com/docs/ja/2.0/circleci-images** to **https://circleci.com/docs/ja/2.0/circleci-images/**
We ran an SEO audit through https://ahrefs.com/ and it reported the link was causing a redirect chain.
=> CircleCI Docker イメージ link

widdershins.apiv2.yml
Adds a heading to the API docs for the v2 insights endpoints.
We've added the insights endpoints to the OpenAPI spec, and we'd like it to show up as "Insights (Preview)".
NOTE: Don't merge this until https://github.com/circleci/circle/pull/10616 is merged.
=> [CIRCLE-23725] Add v2 insights API docs heading

jekyll/_cci2/configuration-reference.md
The pricing for these is now available on the public website, so we’re good to include these in the docs:
https://circleci.com/pricing/
=> Add Machine XL, 2XL and Windows 2XL resources

jekyll/_cci2/deploying-ios.md
Created a new document detailing Fastlane configurations for deploying to App Store Connect, TestFlight and VS App Center
Our original [iOS deployment docs](https://circleci.com/docs/2.0/testing-ios/#configuring-deployment) were fairly out of date and required revamping. These sample FastLane configurations provide users with an opportunity to do CD from CircleCI with their apps in a totally automated fashion.
Some of the wording and structure will need to be adjusted as this is just an early rough draft, but the bulk of the content is done.
I believe a separate document for this is required as it is a bit lengthy and is mostly focused on Fastlane, though if it would be better as a drop-in replacement to the [current section](https://circleci.com/docs/2.0/testing-ios/#configuring-deploymen …
=> Adding iOS deployment documentation

jekyll/_cci2/customizations.adoc
Correct the path to the custom resource definition (`/etc` is not directly bound) and fix outdated example custom resource definition.
https://circleci.atlassian.net/browse/CIRCLE-23983
=> [CIRCLE-23983] Fix custom resource definitions docs

jekyll/_cci2/gh-bb-integration.md
I removed the reference to "user key" in the [description](https://circleci.com/docs/2.0/gh-bb-integration/#deployment-keys-and-user-keys) of a deploy key with write access.
In this one place in the documentation, it implies that a deploy key with write access is a "user key". This really confused me. This PR updates this section to be consistent with the rest of the documentation of deploy vs user keys.
Also, I indented the paragraph from PR #2958 to fix the numbering of the markdown list. Currently it is 1-1-2-3 when it should be 1-2-3-4.
cc: @pat-s
=> Clarify description of deploy key with write access

jekyll/_cci2/orb-author.md
Just found out that namespaces can't be deleted. This piece of information is not visible in the orb docs, so I added it.
Information visibility
=> Add note about namespace deletion

jekyll/_cci2/security.md
Update the description that the Server users are able to use the audit log feature via the UI. Add how to get an audit log from the cloud customers.
The current description is mentioned only the server users are able to use the audit log. But the cloud users also are able to request audit logs through Support. And a customer asked whether they can request an audit log or not.
=> Cloud users are able to request the audit log

jekyll/_cci2/env-vars.md
When reading this section and finding an alternative, I was quite lost on what the alternative actually was.
=> Provide a link to pipeline variables from CIRCLE_COMPARE_URL env var

jekyll/_cci2/language-go.md
The way it's presented is a bit confusing. The example uses go 1.12 (`image: circleci/golang:1.12`) which do not require to work inside the GOPATH, therefore it might lead to understand that it's a CircleCi requirement.
To set `working_directory` is not required, therefore I suggest to remove the lines above from the docs.
Also the [circleci-demo-go](https://github.com/CircleCI-Public/circleci-demo-go/blob/master/.circleci/config.yml) does not set `working_directory` which makes the doc page inconsistent.
Issue  #4102
=> Remove `working_directory` as to work inside GOPATH is not required

jekyll/_cci2/admin-faq.adoc, jekyll/_cci2/architecture.adoc, jekyll/_cci2/authentication.adoc, jekyll/_cci2/aws-prereq.adoc, jekyll/_cci2/aws-teardown.adoc, jekyll/_cci2/aws.adoc, jekyll/_cci2/backup.adoc, jekyll/_cci2/build-artifacts.adoc, jekyll/_cci2/certificates.adoc, jekyll/_cci2/customizations.adoc, jekyll/_cci2/deployment-integrations.adoc, jekyll/_cci2/gpu.adoc, jekyll/_cci2/install-overview.adoc, jekyll/_cci2/jvm-heap-size-configuration.adoc, jekyll/_cci2/monitoring.adoc, jekyll/_cci2/nomad-metrics.adoc, jekyll/_cci2/nomad.adoc, jekyll/_cci2/ops.adoc, jekyll/_cci2/overview.adoc, jekyll/_cci2/proxy.adoc, jekyll/_cci2/security.adoc, jekyll/_cci2/server-ports.adoc, jekyll/_cci2/troubleshooting.adoc, jekyll/_cci2/updating-server-replicated-version.adoc, jekyll/_cci2/updating-server.adoc, jekyll/_cci2/usage-stats.adoc, jekyll/_cci2/user-accounts.adoc, jekyll/_cci2/vm-service.adoc, jekyll/_config.yml
Include path was incorrect for snippets in asciidoc files, I hadn't noticed due to asciidoctor safe mode being turned on so local staging version is displaying correctly. 
This PR removes the content (non-essential) until I work out a fix.
=> fix include path

jekyll/_cci2/gh-bb-integration.md
Fix broken link to "add projects" page.
A request for [circleci.com/add-projects](https://circleci.com/add-projects) results in a 404 redirect to [onboarding.circleci.com/project-dashboard//](https://onboarding.circleci.com/project-dashboard//).  The URL for adding GitHub projects is [circleci.com/add-projects/gh](https://circleci.com/add-projects/gh).
=> Fix broken link to "add projects" page

jekyll/_cci2/orb-author.md, jekyll/_cci2/orbs-best-practices.md
-  Add display key information to orb-author page.
- Reference display key from orb-best-practices page.
- Correct links in orb-best-practices page to use proper `{{ site.baseurl }}` linking.
- Correct minor spelling mistakes found on page.
A new key has been added to orbs to allow users to prominently display the website for the service as well as the git repository.
=> Add display key documentation and update links

jekyll/_cci2/api-developers-guide.md
In markdown, if paragraphs are not indented correctly when creating numbered steps the numbers get out of sync, starting at `1` each time a para is left justified. This fixes this issue in the end to end example.
=> fix up numbered step errors and some typos

jekyll/_includes/global-footer.html, jekyll/_includes/global-nav.html
**Ticket:** [CIRCLE-23956](https://circleci.atlassian.net/browse/CIRCLE-23956)
⚠️ [NO MERGE BEFORE FEB 13 EOD] ⚠️
- Add links to CCI Academy to top nav and footer
- Remove footer docs link. This is probably a copy-paste error from the footer on outer. For the top nav, we exclude the "Docs" link on this site, since we're already on docs. We should do the same for this link in the footer.
=> ⚠️ [NO MERGE BEFORE FEB 13 EOD] [CIRCLE-23956] Add "Training" links to top nav and footer

jekyll/_cci2/optimization-cookbook.md
Testing Optmization becomes Testing Optimization
Found this typo while I was reading the docs.
=> Fix typo at heading

jekyll/_cci2/language-javascript.md
Update the title of the button for Adding GitHub projects to CircleCI... Docs did have it as "Build Project" but it's actually "Set Up Project"
Documentation is important and needs to reflect the actual steps and what the developer is seeing
=> update button title to add GitHub projects to CircleCI

jekyll/_cci2/customizations.adoc
I converted `:ga` flag to `:availability :general`. 
If we didn't set `:availability :general`, no one can use that `resouce_class`. There is another option in `:availability`, it's a `:performance-plan`, but server customers don't use that plan.
So, I just wrote `required field` into that description.
> https://github.com/circleci/picard-services/blob/a5ce64b2a63b182e563eec84b610eb25c2e5f1eb/dispatcher/src/picard_dispatcher/task_def_schema.clj
And also, if we use `:ga`, Server can't trigger any builds, and there is no error message.
=> Convert `:ga` to `:availability :general`

jekyll/_cci2/deployment-examples.md, jekyll/_cci2/ecs-ecr.md, jekyll/_data/sidenav.yml
fixes #4144 
Also: 
* remove unnecessary parameter definitions from config where env vars can be used
* it seemed to me there were too many sections, the last one about introducing workflows didn't actually add to the config, and the full example was just repeated at the end so I removed that. Happy to reintroduce though if others don't agree!
* change to use env var `AWS_REGION` so default is used for all orb commands without having to declare in config. This needs checking though in case I am over-simplifying :-)
* remove this page from the sidenav because it's covered in the main deployment examples page.
=> update references to ECS and ECR orbs

src-js/instantsearch.js
This appears to be broken on Algolia's side in the widget, as the close button is their native element that they create when the widget is created. I assume this originally had the timeout to allow Algolia to do its reset, which hopefully is completed by 100ms later when we trigger a re-render with the now-empty search field.
However this isn't working for whatever reason. Instead we can do what blog search does and clear the query string ourselves and immediately re-render. It's nice to be able to remove that timeout/asynchronous behavior too.
=> [CIRCLE-24660] Fix search box close button

jekyll/_cci2/configuration-reference.md
The [Pricing page](https://circleci.com/pricing/) has correct specs but in the docs I probably have copied the info incorrectly. Fixing here.
=> Fix Windows GPU specs

jekyll/_cci2/security.md
Artifacts service may start redirecting non-HTML resources, so we should both document this, and explain the security considerations behind it.
https://circleci.atlassian.net/browse/CIRCLE-24236
=> [CIRCLE-24236] Document artifacts service security

jekyll/_cci2/updating-server.adoc
Add a warning for user who's using 2.18 already (done for org rename script previously when they update 2.17 > 2.18) to skip the script step
It's not necessary for users who is already 2.18 - they will see this error when they're already done.
```
user=> (migrate)
===== Syncing orgs =====
==== Syncing contexts =====
Execution error (IllegalStateException) at user/migrate (REPL:6).
Attempting to call unbound fn: #'user/migrate-contexts
```
=> Add warning for rename script

jekyll/_cci2/customizations.adoc
Remove explanation about custom resource_class for machine executor. And add WARNING to share how to change the machine executor resources.
Updating `resource-definitions.edn` is not enough to change the machine and windows resource_class. We define the actual instance types in `app_config.edn` in `vm-service` container that made by replicated management console.
So, if we set custom resource_class for machine executor, the actual build machine isn't changed. 
> https://circleci.atlassian.net/browse/CIRCLE-24763
=> Remove explanation about custom resource_class for machine executor

jekyll/_cci2/docker-to-machine.md, jekyll/_cci2/executor-types.md
Adds some documentation around the steps required to move from a Docker executor to machine, and vice versa.
Occasionally, the machine executor is recommended to customers who require more memory for their project, but there is no clear documentation regarding the differences between the two executors, which can make the move difficult. This also lays out a list of manually installed software within the machine images.
=> Docker to Machine migration doc

jekyll/_includes/snippets/language-guides.md
Right now the JavaScript example points to the React Native example. In my opinion this is wrong and I've a found a React demo made by CircleCI so I guess that should be used instead.
=> Replace wrong JavaScript repo link

jekyll/_cci2/executor-types.md
Remove a note that suggests the machine executor is the only way to build a docker image on circleci... `setup_remote_docker` is a thing now.
=> docs: docker executor can build docker images

jekyll/_cci2/language-javascript.md
Just noticed this doc conflates config version with product version. I've talked to Gordon extensively about this and they are separate: "....We don't have a version of "CircleCI" really. We have a version of the execution engine, and a version of config etc."
=> fix up language around config version

jekyll/_includes/global-footer.html, jekyll/_includes/global-nav.html
- Update "API" link in main nav to `https://circleci.com/docs/api/v2/#circleci-api`, per the tickets below, for consistency with this change on circleci.com.
- Add `target="_blank"` to "Feature Requests" links to open in a new tab, for consistency with this same update to circleci.com.
[CIRCLE-24917](https://circleci.atlassian.net/browse/CIRCLE-24917)
[CIRCLE-23675](https://circleci.atlassian.net/browse/CIRCLE-23675)
=> [CIRCLE-24917] Navigation updates 20200305

jekyll/_cci2/configuration-cookbook.md
Use the default name (full title, of a section) for anchor links in Configuration Cookbook.
[CIRCLE-25022](https://circleci.atlassian.net/browse/CIRCLE-25022)
We are linking to specific sections of this page from the new https://circleci.com/orbs/ page, and the preference is that these anchors be more descriptive than the previous names `header1` etc.
=> [CIRCLE-25022] Use default anchor names in Cookbook

jekyll/_cci2/caching.md
Advise on install command
I've noticed that the out-of-box instructions on caching dependencies using yarn doesn't work.
Example:
https://discuss.circleci.com/t/circle-ci-2-0-yarn-dependencies/30912/3
=> Update caching instructions for yarn users

jekyll/_cci2/local-cli.md
Closes https://github.com/circleci/circleci-docs/issues/4162
Current install command is broken, as described in https://github.com/circleci/circleci-docs/issues/4162. So instead of follow redirect to github what causes curl to fail, use github url directly.
Updated install command so it would works again, perhaps not most elegant solution but will get things back to working order.
=> Use github url directly for cli install

jekyll/_api/index.html, jekyll/_api/v1-reference.md, src-api/source/includes/_artifacts.md
- Mention `3xx` redirects for artifacts downloading.
- Make the description of the the downloading uniform across the two APIs.
- Use header based authentication in examples, so the credentials aren't leaked into proxy logs, etc.
https://circleci.atlassian.net/browse/CIRCLE-24237
=> [CIRCLE-24237] Add artifacts redirect docs

jekyll/_cci2_ja/testing-ios.md
Added information from Xcode10.2.1 - Xcode11.4beta3 to testing-ios.md translated in Japanese.
When I refer to testing-ios.md translated into Japanese, it can be read that it does not support xcode11.
Since xcode11 is actually available, the information needs to be updated.
=> add Xcode10.2.1 – Xcode11.4 beta3 to japanese translated testing-ios.md

jekyll/_cci2/notifications.md
Added Chroma Feedback to the notifications page... I would prefer a third party tooling page but this is a temporary solution suggested by Tyler in https://github.com/circleci/circleci-docs/issues/4209
Because it is awesome:
=> Add Chroma Feedback to Notifications

.circleci/config.yml
Our nightly build failed on the new build_config_ref. Disabling it until it's fixed on another branch.
=> Temporarily disable `build_config_ref`

README-local-development.md
Docker instruction were just not working because of broken download.
I have no idea who linked a hashed bundle file that changes on each deployment.
=> Fix Docker instruction as of broken download

jekyll/_cci2/configuration-reference.md
Removed `windows` from the executors list
Windows builds are using orbs now, not using executors
=> Remove windows from the executors since windows is using orbs

jekyll/_cci2/language-elixir.md
- Explain that CircleCI 2.0 parallelism requires JUnit XML output via the JUnitFormatter library
- Explain that JUnitFormatter has an optional `include_filename` configuration that must be set for `--split-by=timings` to work
- Explain where the output file is stored by default and how to configure CircleCI to match that default
I raised [an issue in the CircleCI discussion forums](https://discuss.circleci.com/t/split-by-timings-on-elixir-project-fails-to-find-stored-timings-possibly-missing-file-names-in-junit-xml/34813) that my parallelization configuration suddenly stopped working last December. The solution turned out to be that 1) we had not been manually uploading our own JUnit XML test metadata and needed to add that and 2) there was actually an issue between JUnitFormatter and …
=> Add Parallelism - Splitting by Timings section to Elixir doc

jekyll/_cci2/artifacts.md
Alter the documenation to explain how long we keep artifacts for
We want to detail how long we keep artifacts for rather than the current nebulous timeframe we currently have in the documentation.  This change brings clarity.
=> Clarify Artifact Retention

jekyll/_cci2/concepts.md
Removed ``` A CircleCI project shares the name of the associated code repository and is visible on the Projects page of the CircleCI app. Projects are added by using the Add Project button.``` which appears twice.
=> Remove duplicated sentence in "Getting Started Concepts"

jekyll/_cci2/executor-intro.md
windows code blocks were being grouped with machine code blocks due to the use of the same tabgrorup.
=> Fix: remove duplicate grouping of tabs.

.circleci/config.yml
The nightly workflow for reindexing the search has been failing. Adding the new jobs to it should hopefully fix it and have the config builder and config references on master. Until we merge this, our nightly builds will fail.
=> Add new jobs to nightly workflow.

widdershins.apiv2.yml
Removes "(Preview)" from the heading for the v2 Insights API docs.
The insights API is going to be considered to be out of preview starting April 1st, 2020.
=> [CIRCLE-25351] Remove “Preview” from v2 Insights API doc heading

jekyll/_cci2/language-elixir.md
Removed multiple cache saves
Restore uses partial key matching, no need to explicitly save multiple caches
https://circleci.com/docs/2.0/caching/#writing-to-the-cache-in-workflows
=> Removed multiple cache saves in elixir example

jekyll/_cci2/configuration-reference.md
We only support matrix jobs in version 2.1, so now the docs clarify that, in the same way that other sections of the docs do so.
=> Clarify that build matrix requires version 2.1

jekyll/_cci2/skip-build.md
[request](https://circleci.slack.com/archives/C0KBNJGRH/p1586273983045000) to detail that a [skip-ci] or [ci-skip] tag should appear in the first line of a commit's body (or title)
=> Update [skip-ci] usage description.

jekyll/_cci2/language-scala.md, jekyll/_cci2_ja/language-scala.md
This PR cleans docs. It removes 2nd install `sbt`.
In command, `sbt` is installed by `dpkg`, so `apt-get` do not have to install `sbt`.
=> docs: rm 2nd install sbt

jekyll/_cci2/triggers.md
Copied the note "You cannot currently trigger jobs that use 2.1 config from the API" that is included here https://circleci.com/docs/2.0/api-job-trigger/
I am having trouble manually triggering a job via the API and now I noticed the note saying this is incompatible with 2.1 configs. If this was included in this page I'd have seen it sooner.
=> Added info about inability to trigger 2.1 jobs

jekyll/_cci2/migrating-from-teamcity.adoc
I think that Orbs are similar to TeamCity meta-runners, but not templates: https://www.jetbrains.com/help/teamcity/working-with-meta-runner.html
Meta-runners are basically XML files that can be shared between different TeamCity servers and used as build steps.
=> Migration from TeamCity: Template -> Meta-Runners

jekyll/_cci2/reusing-config.md
The example for `env_var_name` mislabeled the new file as the original file.
I was super confused.
=> fix example for env_var_name

jekyll/_data/sidenav.yml
Some items in the sidenav have ended up with names that exceed one line, it's not immediately clear when this happens that it is a two line item rather than two items. This PR proposes a fix for these items.
=> fix sidenav to one line per item

jekyll/_cci2/skip-build.md
All new projects have been using pipelines for a long time, and we're
actively migrating old projects to pipelines.
=> The pipelines feature is no longer in preview

jekyll/_cci2/configuration-reference.md
Add the new `ubuntu-1604:202004-01` image to the list of machine executor images
`ubuntu-1604:202004-01` is now available for use
=> Add ubuntu-1604:202004-01 image

jekyll/_cci2/configuration-reference.md, jekyll/_cci2/executor-types.md
Get to parity between configuration reference and executor types.
=> Add: resource_class information for docker.

Gemfile, Gemfile.lock, jekyll/_cci2/admin-faq.adoc, jekyll/_cci2/build-artifacts.adoc, jekyll/_cci2/certificates.adoc, jekyll/_cci2/env-vars.md, jekyll/_cci2/hello-world-macos.md, jekyll/_cci2/migrating-from-github.adoc, jekyll/_cci2/migrating-from-gitlab.adoc, jekyll/_cci2/monitoring.adoc, jekyll/_cci2/ops.adoc, jekyll/_cci2/v.2.17-overview.md, jekyll/_cci2_ja/creating-orbs.md, jekyll/_cci2_ja/deployment-integrations.md, jekyll/_cci2_ja/env-vars.md, jekyll/_cci2_ja/hello-world-macos.md, jekyll/_cci2_ja/monitoring.md, jekyll/_config.yml, jekyll/_plugins/target_links.rb
fixes https://github.com/circleci/circleci-docs/issues/4293.
Adds a new [jekyll plugin](https://github.com/keithmifsud/jekyll-target-blank/)  as well as patches it to make urls work with non-ascii characters.
Note: the `jekyll-target-blank` plugin also pointed out several invalid links that we had in our url. Many of these urls are in our server documentation serve as example urls. For example:
> Visit `https://<server>:8800/create-password` to create a new password or connect LDAP.
Where this will actually render a link, at least in ascidoc, which means we have weird dead links sprinkled throughout our documentation. I have removed all instances of `http|https` in these urls, so they remain plain text. If this behaviour is intention let me know cc @rosieyohannan .
=> All external links should open in new tabs

jekyll/assets/css/main.scss
This is probably a very clunky way of getting the desired result but.....
h6 now same size at h5, but h6 is generally in italics.
Original report here: https://circleci.slack.com/archives/C0KBNJGRH/p1587401595092400
before:
after:
=> size up h6 so they aren't smaller than main text

jekyll/_cci2/testing-ios.md
The dependencies haven’t changed, so the contents of the `index.html` from the old image and the new image are identical. Still, updating the docs in case this info is later used for troubleshooting or other purposes.
=> Reflect the minor change in the Xcode 11.4 image

jekyll/_cci2/configuration-reference.md, jekyll/_cci2/testing-ios.md
Revamped the whole document!
Our testing iOS apps documentation was a bit out of date/stale in areas and also a bit disjointed having been added to here and there.
I have gone ahead and rewritten various sections and moved sections around in an aim to simply the whole document and clarify important areas, along with some simple things like tidying up titles and the TOC.
=> Update Testing iOS documentation

jekyll/_cci2/configuration-reference.md
AWS ECR is AWS Elastic Container Registry
Corrected type EC2 to Elastic
=> docker aws_aut fix EC2 to Elastic

jekyll/_cci2/configuration-cookbook.md, jekyll/_cci2/deployment-examples.md, jekyll/_cci2/ecs-ecr.md, jekyll/_cci2_ja/deployment-integrations.md, jekyll/_cci2_ja/ecs-ecr.md
The orb command names are incorrect.
Sources:
- https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/commands/build-and-push-image.yml
- https://circleci.com/orbs/registry/orb/circleci/aws-ecr#jobs-build-and-push-image
When I tried to use aws-ecr-orb with `build_and_push_image` command (same as the document), it returned an error: `Cannot find a definition for job named aws-ecr/build_and_push_image`
=> Fix incorrect aws-ecr-orb command name

jekyll/_cci2/testing-orbs.md
fix typo.
`imputs` -> `inputs`
=> fix typo in testing-orbs.md

jekyll/_cci2/configuration-cookbook.md
fix typo.
`aws-ecs 0.0.4` -> `aws-ecr 0.0.4`
=> fix typo in configuration-cookbook.md

jekyll/_cci2/collect-test-data.md
* Remove reference to jest.config.js. This Jest config file is not required, as the example includes the parameters in the CLI arguments.
* Updated example CircleCI config for Jest test data. JEST_JUNIT_OUTPUT_DIR should be a folder, not a file, `store_test_results` was not present as a step, and should be for this config to work (and to be similar to other examples in this document)
* Added caveats for referenced article, as it's now out of date
=> Update test collection docs for Jest

jekyll/_cci2/reusing-config.md
Fix the "Database Examples" link at https://circleci.com/docs/2.0/reusing-config/#see-also.
The "Database Examples" link is broken.
=> Fix broken link to Database Examples

jekyll/_cci2/orbs-best-practices.md
This PR changes the language, suggesting explicitly that one executor is named `default`.
When reading this page it's not clear what one has to do to include one "default" executor.
=> More explicit name suggestion for default executor

README-local-development.md
Be more explicit about npm command in local development documentation.
`webpack-dev` is actually an npm package and can cause confusion(and potential security concerns) with developers that are not familiar with the webpack ecosystem.
https://www.npmjs.com/package/webpack-dev
=> Be more explicit about npm command

README-local-development.md
Add instructions to include the _src-shared @ 75ac85b_ submodule when cloning the forked repository.
Failing to pass `--recurse-submodules` when running the `git clone` command will result in an empty local _src-shared_ folder.
This will prevent the Docker container from starting and will produce the below error when running the `docker-compose up` command:
```
jekyll_1  | jekyll 3.8.6 | Error:  No such file or directory @ rb_sysopen - /srv/jekyll/jekyll/assets/js/shared
````
=> Add instructions to initialize and update the src-shared submodule

jekyll/_cci2/insights.md
Insights are only available on our server product now; this warning directs users to check out the api-v2. 
screenshot:
=> Add: note insights is only available on server.

jekyll/_cci2/configuration-reference.md
Right now there are a limited number of container customers who have
access to other resource classes, but we are taking steps to turn this
off and do not want to encourage more container customers to enable it.
Related to this Jira: https://circleci.atlassian.net/browse/CIRCLE-22185
=> Changing resource_class requires a performance plan.

jekyll/_cci2/orb-author.md
Example provides invalid YAML as the body of the example.
Followed example steps at https://circleci.com/docs/2.0/orb-author/
=> Replace JSON with YAML in example orb content

jekyll/_includes/edit-on-github.html
Added `/docs` segment in the URI so the link to "contributing guide" workds.
The link to 'contributing guide' on Github is pointing to a 404 error due to a missing a `/docs` segment in the link URI.
=> Fix 'contributing guide' link in docs footer.

jekyll/_cci2/language-javascript.md
Updates to the language guide to use 2.1/orbs. 
_Do not merge_ until 2.1 config changes are merged into master in the [sample repo](https://github.com/CircleCI-Public/circleci-demo-javascript-react-app/pull/17/files). I think this guide will get more content, so it will be revisited. For example, the sample app only demonstrates testing - it might be useful to demonstrate _building_ the react app.
=> Node language guide update

jekyll/_cci2/code-coverage.md, jekyll/_cci2_ja/code-coverage.md
Changed 2 occurrences of config.yaml into config.yml
Because .yaml is not recognized.
=> fix: typo /_cci2_ja/code-coverage.md

jekyll/_cci2/vm-service.adoc
Fixes "Winows" to "Windows".
Noticed the spelling error reading documentation.
=> Fix spelling (Winows -> Windows) in vm-service.adoc

jekyll/_cci2/api-developers-guide.md
Fix the "Personal API Tokens page" link at https://circleci.com/docs/2.0/api-developers-guide/#add-an-api-token.
The "Personal API Tokens page" link is broken.
=> Fix broken link to Personal API Tokens page

jekyll/_cci2/gh-bb-integration.md
Co-authored-by: Anna Calinawan <anna.calinawan@circleci.com>
State that some permissions actually require admin-level access.
The previous wording caused confusion, as it implied that write-level access to a repository was sufficient to set up a project in CircleCI. [A user must be a GitHub admin to add deploy keys or service hooks](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level), and through experimentation, we found that a Bitbucket user must have admin access to add a [deploy key](https://confluence.atlassian.com/bitbucket/access-keys-294486051.html), which is required to set up a Bitbucket project.
Maybe there's a better place to clarify this? We think that …
=> Adding deploy keys and service hooks requires admin permission.

jekyll/_cci2/oss.md
=> fix typo in oss.md

.circleci/config.yml, docs/local-development.md, jekyll/_archive/build-image-precise.md, jekyll/_cci1/build-image-precise.md, jekyll/_cci2/build-publish-snap-packages.md, jekyll/_cci2/caching.md, jekyll/_cci2/java-oom.md, jekyll/_cci2/jira-plugin.md, jekyll/_cci2/packagecloud.md
Where correct, use possessive pronoun "its" instead of contraction for "it is"
Just grammar.
Grammatical correctness.
=> Minor English fixes

jekyll/_cci2/building-docker-images.md
A new remote Docker version is now available. :)
=> Add remote Docker v19.03.8 to list.

jekyll/_cci2/executor-types.md
Support tickets are no longer needed to enable DLC. They can self-serve on performance plan
Improved accuracy
=> support tickets no longer needed for DLC

jekyll/_cci2/configuration-reference.md
Modified the heading for the final section in the configuration reference.
There was odd continuity between the previous section and the final section - reader potentially confused into thinking the "Full Example" is a full example of logic statements.
=> Minor change in section heading in Config Reference

jekyll/_cci2/api-developers-guide.md
Document the rate limits that we will be adding to the API in advance of us enforcing any limits.
See [the initiative brief](https://docs.google.com/document/d/1s3ZIR6f5d95lD--PulaHPlvZEKle2x77FtCXlYRcTrE/edit#).
Do not merge until we have sign-off from all stake-holders.
=> Document our API rate limit policy

jekyll/_cci2_ja/managing-api-tokens.md
remove duplicate `[`
https://circleci.com/docs/ja/2.0/managing-api-tokens/
=> fix markdown syntax managing-api-tokens.md

.circleci/config.yml
Ruby bundles for API and cfg were not being cached correctly. this should fix that. Further, there was an unused command which did bundling. Overall this PR cleans up the config and speeds up builds.
With caching:
Without caching:
Improves run times & cleans up config.
=> [Build] Improve caching

jekyll/_cci2/reusing-config.md
Update the `when`-step docs to include logic statements under the `condition` key.
I had changed the configuration reference but forgot about this bit here.
=> Correct the when-step docs to include logic

jekyll/_cci2/workflows.md
Removes the (legacy ui) image header on the workflow document, at least until we find a suitable open source repo that we can use an example workflows screenshot from.
=> Clean: remove out of date workflow image.

jekyll/_cci2/customizations.adoc
Earlier in this month we found out that the current example of custom resource class configuration breaks Windows builds, because it will delete all internal resource classes for `machine` executors, and Windows builds will be defaulted to incompatible resource classes for Linux VMs. This update fixes the issue by reviving the default resource class configuration for machine builds.
=> Custom resource class: Reviving mandatory configuration for machine bulids

.circleci/config.yml, jekyll/_cci2/security-server.adoc
During an update yesterday I missed off a section from the server security doc. This adds it back in.
=> add best practices to Server security doc

jekyll/_cci2/env-vars.md
- Move deprecated and internal variables to the bottom of the list.
- Bring `CIRCLECI` to the top of the list.
- Make clear that `CIRCLE_INTERNAL_TASK_DATA` is internal.
- Improve the accuracy of other descriptions.
=> Improve descriptions of some environment variables

jekyll/_cci2/configuration-cookbook.md
- Fixes to keep recipe in line with most recent version of the orb.
- Remove heroku example as it needed fixes and is covered in detail in the main deployment guide
=> changes to EKS recipe examples

jekyll/_cci2/yarn.md
The code snippet in the doc contains `--frozen-lockfile` as an argument to `yarn install`. That argument has been renamed to `--immutable`.
The compatibility alias `--frozen-lockfile` will be removed in later versions, according to the [yarn docs](https://yarnpkg.com/cli/install).
=> Update `yarn install` argument name

jekyll/_cci2/api-developers-guide.md
- fixes heading jumping
All documents should have only one h1 (for jump-to-heading, for seo, etc). This PR bumps all headings down to achieve that.
=> Clean: only use >= 2 level headings for content.

jekyll/_cci2/configuration-reference.md
`deploy` and job level `branches` are deprecated
=> add deprecated notes for some keys

jekyll/_cci2/security-server.adoc
Make customers aware that we upload traces from support bundles to a
third-party vendor, what kind of data they contain, and how long they
are retained for. This is based on functionality that was shipped in
2.19.3 and the process in our internal documentation.
It's not strictly an integration because the data is "manually" uploaded
after we receive a support bundle from a customer, but this page and
heading seems like the most appropriate place to put it.
https://circleci.atlassian.net/browse/CIRCLE-27179
=> [CIRCLE-26254] security-server: Add support bundle processing

jekyll/_cci2/concepts.md
There are two slashes in the link to the checkout job reference. This PR changes to a single slash.
The link is broken.
=> Fix a typo in link to the checkout job reference

jekyll/_cci2/skip-build.md
Added a note that `[ci skip]` doesn't cancel the scheduled workflow. 
The message below is the answer from the engineering team.
> If you change the cron schedule and put [ci skip] into the commit message then we never tell workflows-conductor about the updated cron schedule.
We got a question about this, and it's better to write on the document.
> https://circleci.slack.com/archives/C4C9J5KHN/p1591346914466500
=> Add note for the skip build

jekyll/_cci2/optimization-cookbook.md
I spoke to the CPE team about the example using Eddie Webb's orb, and the consensus is this use case should be removed - orbs providing missing features should not be recommended, customers should rather be directed to the Ideas page to vote for the feature to accurately record user need. Also, this particular use case is not strictly an optimization.
=> remove queueing example

jekyll/_cci2/testing-ios.md, jekyll/_cci2_ja/testing-ios.md
I was setting out config for CircleCI for my new iOS project and noticed that `bundle clean` was missing in the document and this might lead cache to grow unnecessarily.
`bundle install` do not clean unused old gems by default and without cleaning them will lead cache to grow unnecessarily.
In addition, `bundle clean` is mentioned here https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/caching.md#bundler-ruby and I suppose this is the best practice for cache setting for gems in CircleCI.
As you know, since bundler version 2.1 `bundle install --path` is deprecated. 
ref : https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#210pre1-august-28-2019
I am happy if this is fixed since warning message appears in most cases when setting following to the CircleCI …
=> doc: add clean option to bundle install

jekyll/_cci2/configuration-reference.md
Fixes a singular vs. plural inconsistency in docs. Singular does not work. Also rest of the docs uses plural everywhere.
Because I want to help others to avoid having problems and the example configs should absolutely be working
=> docs: pipeline.parameters are always plural

jekyll/_cci2/orbs-best-practices.md
Adds a brief section on handling sample data when writing Orbs.
There isn't a clear "standard" when it comes to handling sample data, but generally we've settled on using a `sample` directory - this helps clarify this to others writing Orbs.
=> Add guidelines for Orb sample data.

jekyll/_cci2/local-cli.md
Switch semantic priority of `curl|bash` and package managers for local CLI installation as piping curl to bash is generally considered bad.
https://circleci.atlassian.net/browse/SEC-1344
=> Fix SEC-1344

jekyll/_cci2/update-nomad-clients.adoc
Pins the docker-ce-cli version to prevent api mismatch errors
Without pinning the CLI version, the default install uses too new a version of the CLI. This pins the version to prevent an error
Below is the result of the script being executed as defined in the documentation
```
Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39
```
```
ii  docker-ce                        5:18.09.9~3-0~ubuntu-xenial                amd64        Docker: the open-source application container engine
ii  docker-ce-cli                    5:19.03.9~3-0~ubuntu-xenial                amd64        Docker CLI: the open-source application container engine
```
=> pins the docker-ce-cli version to prevent api mismatch error

jekyll/_cci2/concepts.md
Clarify the relationship between "step vs. job vs. workflow vs. pipeline".  Research has found that these concepts are a little unclear to users. 
In this PR:
- Move the "configuration" section up in the document.
- Some re-wording in the section under `#configuration` (although @rosieyohannan has done lots of great work on this document recently as well, especially the graphics). 
- Cleans up the table of contents to not be nested. 
@KateCatlin is wondering if we can get some other designs that can better represent the relationship between steps/jobs/workflow/pipelines, but for now, hopefully this prose clears it up.
=> Add: clarify config relationship; fix headings.

jekyll/_cci2/jvm-heap-size-configuration.adoc, jekyll/_cci2_ja/jvm-heap-size-configuration.md
Change to use maxMemory rather than totalMemory
`totalMemory` doesn't return the maximum heap size, it returns the total amount of memory in the Java virtual machine.
So, if the customer changes the JVM_HEAP_SIZE, `totalMemory` doesn't return the same value of it.
=> change to use maxMemory rather than totalMemory

jekyll/_cci2/configuration-reference.md
* Job's `parameters` field is missing in the (partly chaotic, see below) table of contents (TOC).
* Reserved words for parameter names added. Please complete the list before merging. Related:
* [`matrix` is accepted as valid job-parameter-name](https://github.com/CircleCI-Public/circleci-cli/issues/424)
[CircleCI's YAML-config API-reference](https://circleci.com/docs/2.0/configuration-reference/) misses a quick overview for all possible fields which could be set.
The best place for it would be the table of contents, IMO.
As good example would be the [TOC from Github Actions' reference documentation](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions).
So, see this PR as a first step in this direction. I hope you, CircleCI employees, will continue on this. I …
=> config-ref.: `job.{}.parameters` properly documented

jekyll/_cci2/skip-build.md
Now that all Cloud customers have pipelines enabled by default we need to update what we have documented for the auto-cancel builds feature, while keeping in relevant info for Server customers.
=> edits to reflect current auto-cancel feature status

src-crg/Gemfile.lock
Reverts circleci/circleci-docs#4493
=> Revert "Bump ffi from 1.9.17 to 1.13.1 in /src-crg"

src-crg/Gemfile.lock
Downgrading `rack` to 2.0.9 to fix Config Reference Guide.
I don't know the reason but it worked. :P
=> Anchor to rack < 2.1.0

scripts/build_api_docs.sh
This should help avoid us shipping any broken assets in future.
https://app.circleci.com/pipelines/github/circleci/circleci-docs/24561/workflows/c42fbe58-8b04-483e-b104-03c3ad3d30a0/jobs/61314/parallel-runs/0/steps/0-108
=> Include what broke when docs building breaks (and fail the job)

jekyll/_config.yml
Current search options only build md and html content, and only indexed content in <p> I think. Exploring more options here:
* add asciidoc content
* add heading and content in tables and code blocks (probably not a good idea to include code blocks but can dicuss)
Info from here: https://community.algolia.com/jekyll-algolia/options.html#extensions-to-index
=> [WIP] explore algolia search options

jekyll/_cci2/configuration-reference.md
Missing content transferred over from https://circleci.com/docs/2.0/reusing-config/#using-pre-and-post-steps
=> add pre and post steps to config ref

jekyll/_cci2/configuration-reference.md
As noted elsewhere in the docs, caches now expire after 15 days.
This was causing confusion for a customer in a support ticket
=> Update another reference to the cache expiry duration

jekyll/_includes/snippets/language-guides.md
Added references to sample projects for Visual C++ (i.e. Windows)
(Background0 It was developed as a show case for a specific customer onboarding Windows builds on CircleCI. It is encouraged by the team in charge of sample projects to retune it for broader audience. The project showcases how unit tests in VC++ should be implemented - actually it needs special architectural design; I believe this is a good demonstration of best CI/CD practices for VC++-based apps.
=> Added references to VC++ sample projects

jekyll/_config.yml
This change adds the [minProximity](https://www.algolia.com/doc/api-reference/api-parameters/minProximity/) setting to the search index, with a value of 3.
This change loosens the precision of the engine in matching words that are close together. Due to how Algolia's ranking formula works, if we search "parallel tests", a page will rank higher if it includes "parallel tests" _even if it's buried far down the page_. What we'd likely prefer is that if a page _title_ includes "tests in parallel", the fact that the word "in" separates the two isn't a strong indicator the result is not relevant - the fact this match is in the _title_ is what we care about.
With this new setting, the ranking will only differentiate if there are 3 or more words separating the search terms.
Increasing this value …
=> Add minProximity setting to search index

.gitignore, docs/local-development.md
This PR adds documentation on how to set up search to work locally on your own Algolia account.
I couldn't see any existing documentation on how to accomplish this, potentially making it harder for contributors to work on search related functionality.
=> Add docs on working on search locally

jekyll/_cci2/configuration-reference.md
CPE has put out a new, quarterly Linux machine image. Adding it to the list.
Also updated a nearby example for this image since it was using a 2019 version.
=> Add ubuntu-1604:202007-01 image.

jekyll/_cci2/nomad-metrics.adoc, jekyll/_cci2/update-nomad-clients.adoc
Due to CIRCLE-27149, we updated [a reference launch configuration for Nomad clients](https://github.com/circleci/enterprise-setup/commit/f0fe945e23b4ec601960f034bb95c47cda321589) in [`enterprise-setup`](https://github.com/circleci/enterprise-setup). This PR reflects that update to documentations as well so that customers using CircleCI Server in private subnets on AWS can mitigate the issue that the `Rebuild With SSH` feature is broken.
I've confirmed that both updated launch configuration passed [`realitycheck`](https://github.com/circleci/realitycheck) and another tests for SSH rebuilds.
=> Synchronize launch configuration for Nomad clients with enterprise-setup

jekyll/_cci2/reusing-config.md
This PR will update the "Authoring Parameterized Jobs" section to have additional details around what happens when you invoke the same job multiple times with different parameters. It gives an example of how to utilize the `name` option in workflows.
I swapped to `sayhello-1` as the example since the section above this section has an example utilizing that job name, so wanted to keep it consistent. 
Making these changes to ensure its clear that without the `name` key jobs will be appended with a number if invoked multiple times with parameters.
=> Add further clarification of invoking the same job multiple times with parameters

jekyll/_cci2/building-docker-images.md
Add remote docker version `19.03.12`
Remote docker version `19.03.12` is now available
=> Add remote docker 19.03.12

jekyll/_cci2/add-ssh-key.md
Making instructions in the _"Adding an SSH Key to CircleCI"_ documentation consistent with the layout of the new UI.
This PR addresses issue #4473
Steps currently present in the documentation apply to the legacy/old UI.
=> Update "Adding SSH Key" steps for new UI

jekyll/_cci2/reusing-config.md
Replaces the following docs:
- https://circleci.com/docs/2.0/orb-author/#writing-inline-orbs
- https://circleci.com/docs/2.0/orb-author/#example-inline-template
Both of these should be removed in the final pull request though may not show in this PR as we are working on multiple PRs at once.
=> inline orb docs

jekyll/_cci2/getting-started.md
Updates this comment for the `checkout` step in the [Getting Started guide](https://circleci.com/docs/2.0/getting-started/#section=getting-started)
> this pulls pulls code down from GitHub
which contains the word `pulls` twice
=> Fix repeating word in comment explaining checkout

jekyll/_cci2/non-aws.md
We have a page in the main docs that documents how to go through a static install of Server. This info was moved to the Server Documentation repo so this PR removes the content.
=> remove static install info and direct to support

jekyll/_cci2/ecs-ecr.md
The AWS-CLI library has changed its default environment variable, previously AWS_REGION to AWS_DEFAULT_REGION. A change can be reflected in the docs for deploying codebase to ECR and ECS. Fixes issue #4585.
=> Change Environment Variable name for AWS Region

jekyll/_cci2/contexts.md
Add the requirement to trigger builds with a restricted context
Users need to sign up for CircleCI to trigger builds with a restricted context. Even if they don't sign up for CircleCI, they can trigger builds, but to trigger a build with a restricted context, CircleCI needs to check the accounts permission, so users must sign up for CircleCI.
=> Add a requirement to trigger builds with a restricted context

jekyll/_api/v1-reference.md, jekyll/_cci2/artifacts.md, jekyll/_cci2/config-translation.md, jekyll/_cci2/env-vars.md, jekyll/_cci2_ja/artifacts.md, jekyll/_cci2_ja/config-translation.md, jekyll/_cci2_ja/env-vars.md, jekyll/_ccie/faq.md, jekyll/_plugins/api_endpoint.rb, src-api/source/includes/_artifacts.md, src-api/source/includes/_builds_and_jobs.md, src-api/source/includes/_environment_vars.md, src-api/source/includes/_keys.md, src-api/source/includes/_overview.md, src-api/source/includes/_projects.md, src-api/source/includes/_user.md, src-api/source/includes/environment_variables.md
Document that we are deprecating putting the token in query parameters and use basic auth in examples
https://circleci.atlassian.net/browse/CIRCLE-27357
=> [CIRCLE-27357] Deprecate putting token in query parameters

jekyll/_cci2/reusing-config.md
This update adds a note that the name assigned to the `name` key needs to be unique.
I previously added (https://github.com/circleci/circleci-docs/pull/4536) this disclaimer about job names appending numbers when calling multiple times with parameters. However, I didn't note that the name assigned via `name` needs to be unique, otherwise the numbers will still be appended.
=> Add note about job name needing to be unique

jekyll/_cci2_ja/index.md
Links on the Japanese index page were pointing to the English version of the
docs.
I am fixing it to point to the Japanese version instead.
Links on the Japanese index page were pointing to the English version of the
docs.
=> Fix link on Japanese index page

Gemfile.lock, jekyll/_cci2/orbs-faq.md, jekyll/_cci2/reusing-config.md
- clear up what's going on with env_var_name param type -  original request: https://circleci.slack.com/archives/C0KBNJGRH/p1595872682016600
- move parameters section to the start of the doc as this needs to be understood for all other sections
- update a couple of examples
=> [WIP] Further explain `env_var_name` parameter type

jekyll/_cci2/configuration-reference.md
Fixing typo in the [Ending a job from within a step](https://circleci.com/docs/2.0/configuration-reference/#ending-a-job-from-within-a-step) section.
I think `by using using` is a typo.
=> fix typo in instruction

jekyll/_cci2/configuration-reference.md
This was prompted after someone was surprised by an error after specifying `project/project-name` as the working directory.
=> Make it clearer whether working directories are relative or absolute

jekyll/_cci2/language-go.md
The go language guide was out of date with the latest sample application. This PR updates it. 
Closes #4557
=> Update: Go language guide

jekyll/_cci2/docker-compose.md
At the moment we don't support using docker with the `macos` executor. I wanted to ensure that was noted on this page to avoid any confusion.
These changes are from a suggestion from a customer that we did not note on this page that docker isn't supported for MacOS. Adding this to avoid future confusion amongst customers.
=> Add disclaimer about docker support in MacOS

jekyll/_cci2/configuration-reference.md
Workflows are now active on all projects on CircleCI. There is no longer a "Run", which may now be considered a pipeline. One piece of information omitted in this commit that might be worth adding back, if the user does not specify a workflow, and has a job named "build" we will automatically generate a workflow for the build job.
=> Update lang from "run" to assume Workflow usage

jekyll/_cci2/optimizations.md
At the moment, Docker Layer Caching (DLC) is only available for Performance Plan users.
This documentation was outdated and asking users to create a support ticket, which does not help.
Updated the note to clarify that DLC is only available on Performance Plan.
At the moment, DLC is only available for Performance Plan users.
=> Updated note about DLC on optimizations page

jekyll/_data/sidenav.yml
It looks like we are now forwarding `https://circleci.com/docs/api/` to our v2 API documentation. This means the existing link we have in the documentation for the "API v1.1 Reference" was pointing to the v2 documentation instead of the v1 documentation.
This PR takes care of that by adding `v1` to the link so it points to the proper API docs. So as of right now it directs to:
```
https://circleci.com/docs/api/#section=reference
```
After this change it will direct to:
```
https://circleci.com/docs/api/v1#section=reference
```
This PR takes care of CIRCLE-28511
=> [CIRCLE-28511] Update v1 reference link to point to v1 API docs

scripts/build_api_docs.sh
Partial revert of #4578 
`circleci.com/docs/api/` root should continue pointing to v1 (until, if at all, v1 is deprecated). 
V1 will still be available at `docs/api/v1`
v2 will still be available at `docs/api/v2`
=> Fix: revert default api/ root to v1.

jekyll/_cci2/security.md
Updating `jekyll/_cci2/security.md` to reflect two new audit log events for SSH key create/delete.
Audit log events for adding and deleting SSH keys were requested with https://circleci.atlassian.net/browse/CIRCLE-27340
PR with changes: https://github.com/circleci/circle/pull/11434
=> CIRCLE-27340 - Document two new audit log events for SSH key actions

jekyll/_cci2/deploying-ios.md
This PR removes an extra bracket `[` that we had in a link within the docs. It was not allowing the markdown to work and causing this to be displayed in the docs:
The extra bracket was making the content display as text and not a link, the update will ensure its rendered as a link and references the proper documentation section.
=> Remove extra bracket in ruby versions link

jekyll/_cci2/browser-testing.md
We were providing the incorrect steps to get this working. The port information needed to be swapped in step 3 (did that) and added a note that they will need to update port `8080` to whatever port they are actually running in the container.
Before making these changes I tested these steps out myself and verified the information was indeed incorrect.
We were alerted by a customer that the port information was swapped in section 3 (it said to visit port `8080` locally, but you need to visit port `3000` locally).
=> Update port information in local browser testing section

jekyll/_config.yml, jekyll/_includes/global-nav.html, jekyll/_plugins/devhub_url_filter.rb
**Ticket:** [CIRCLE-28743](https://circleci.atlassian.net/browse/CIRCLE-28743)
* Create `devhub_url` filter so Japanese link are formed correctly (is different structure from outer_url)
- use full `https://circleci.com/developer` url in config so that links still work locally
- pass empty string `''` rather than `'/'` to prevent trailing slash, not used in the DevHub project
* Add link to `Developer` in main nav
* Add link titled `Developer Hub` as new link under `Developer` in mobile nav
* Remove `s` from `Developers` in navigation.
Supporting the launch of Developer Hub on August 25th, 2020
* This does not add the `data-analytics` data attributes that were included on the [PR for outer](https://github.com/circleci/circleci.com/pull/3761) as none of the other link here had these …
=> [CIRCLE-28743] Add DevHub link and url filter to global-nav

jekyll/_cci2/circleci-images.md
Update the convenience image page with details on the next gen images and links to the developer hub.
CIRCLE-28757
=> Update convenience image docs with next-gen images and dev hub links

jekyll/_cci2/contexts.md
Updated context doc to reflect that it is now possible to use more than one context in a workflow.
The doc did not have any examples of multiple contexts to tell users it was possible to do.
=> Updated doc to include multi context info

jekyll/_cci2/language-dart.md, jekyll/_includes/snippets/language-guides.md
Added an entry to the `tutorials` table and a language guide for Dart.
Adding more examples and more languages/frameworks, building out our examples to prove the concept that CircleCI can support various use cases
=> Add language guide and entry in table for Dart

jekyll/_cci2/language-dart.md
Minor cosmetic fix to recently merged PR
My VIM autosave automatically strips trailing whitespaces but Markdown needs them for newlines
=> Cosmetic fix for link in Quickstart section

jekyll/_cci2/jenkins-converter.md
Initial draft of documentation for the Jenkins Converter--introduction, instructions on use, current limitations, and supported plug-ins.
The Jenkins Converter web tool will be released as part of the Developer Hub, estimated mid-August. Instructions on the tool page will point to this page for instructions on use.
https://circleci.atlassian.net/browse/CIRCLE-28142
https://circleci.atlassian.net/browse/MKTG-1841
=> Add documentation for Jenkins Converter - Developer Hub

jekyll/_cci2/gh-bb-integration.md
Add `public` and `private` prefixes when referring to an SSH deploy key
Noticed this could be noted explicitly to increase clarity in the steps. It is mentioned in the paragraph before, but that might be skimmed and missed when going for a quick copy paste
=> Clarify where to copy public/private key for GitHub and Bitbucket Integration

jekyll/_cci2/server-ports.adoc
Add a note to mention CircleCI Server only supports x86_64 architecture into the below page
> https://circleci.com/docs/2.0/server-ports/#nomad-clients
A customer asked us that the Server can uses `m6g` image type, but the instances type is arm-based architecture.
CircleCI Server doesn't support other than x86_64 architecture, so we should mention this.
=> Add a note to mention CircleCI Server only supports x86_64 architecture

jekyll/_cci2/configuration-reference.md
This PR will remove the `condition:` key from the workflow example as that isn't supported/doesn't work and it also adds a note specifically to not include it at the workflow level.
A customer raised this in a ticket and I tested and confirmed the current functionality. These changes will hopefully prevent future confusion.
=> Remove condition key and add note about workflows

jekyll/_cci2/contexts.md
Change casing in Creating and Using a Context from BitBucket to Bitbucket
Update the casing from BitBucket to Bitbucket
Continuity in the doc
=> Change casing in Creating and Using a Context

jekyll/_cci2/testing-ios.md
Deprecation warning for Xcode 9.0.1 and 9.3.1
Adding clarity to the image table due to upcoming deprecation:
https://discuss.circleci.com/t/deprecation-notice-xcode-9-0-1-and-xcode-9-3-1/37382
=> Deprecation warning for Xcode 9.0.1 and 9.3.1

jekyll/_cci2/configuration-cookbook.md, jekyll/_cci2/orb-author-faq.md, jekyll/_cci2/orbs-faq.md, jekyll/_cci2/testing-orbs.md, jekyll/_cci2/using-orbs.md
fixes #4260 
This PR:
* adds an example of matrix jobs
* expands the current logic in config section to show multiple recipes rather than a couple of use cases under a category. I changed this for consistency and to make the recipes easier to find.
=> add matrix example to config cookbook

jekyll/_cci2/api-intro.md
Add a note that API v2 isn't supported project token
Some customers asked this issue via support tickets.
=> Add a note that API v2 isn't supported project token

jekyll/_cci2/customizations.adoc
Remove duplicate backtick ('`') to improve display of the server customizations page:
=> Zap duplicate backtick that ends up on the site

jekyll/_cci2/env-vars.md, jekyll/_cci2/project-build.md, jekyll/_cci2/settings.md, jekyll/_cci2_ja/project-build.md, jekyll/_cci2_ja/settings.md
Reverts circleci/circleci-docs#4690
@teesloane I propose reverting this change and instead I'll update the page to be an actual intro section to this docs section?
What do you think?
=> Revert "Clean: remove settings page."

jekyll/_cci2/examples-intro.md
Incorrect use of _peak_ instead of **peek**.
> See the following snippets for a ~peak~ peek into how you can customize..."
Noticed the typo when following the docs, doesn't take away from content, just fixing a homophone issue.
=> Typo fix: peak -> peek

jekyll/_cci2/contexts.md
the indent made examples unusable when copied and pasted
=> fix: remove indent from tabbed examples

jekyll/_cci2/optimizations.md
I noticed this reference to accessing plans info is out of date.
=> fix access plan info description

jekyll/_cci2_ja/hello-world.md
A customer submitted a ticket that they follow the Japanese version of the hello world doc, but the config doesn't work. 
An indent in config is broken, and some code block syntaxes are missing.
It seems crowdin which is the translation management tool might causes this issue. I'll reach out localization team in APAC.
=> Fix indent and add code blocks

jekyll/_cci2/private-images.md, jekyll/_data/sidenav.yml
Originally we were going to add a new document just for rate limits.  The contents of that document ended up being similar to the existing `private-images`, so I decided to merge the two.
We are specifically mentioning this because Docker Hub intend to enforce rate limits starting November 1, 2020.
https://circleci.atlassian.net/browse/CIRCLE-29510
=> Add rate limits as motivation to use authenticated docker pulls

jekyll/_cci2/testing-ios.md
Clarify Ruby changes that apply to 11.7 and later
Originally these changes were only meant for Xcode 12 and later, but were back-ported to 11.7
=> Clarify Ruby changes

jekyll/_cci2/private-images.md
Just referencing the page and noticed this very quickly.
cirlce->circle
=> Fix blaring typo on private images page

jekyll/_cci2/aws.adoc
Fix a typo in [Installation on AWS for Server 2.x](https://circleci.com/docs/2.0/aws/#installation-setup).
Easier to read.
=> Fix typo in Installation on AWS for Server 2.x

src-api/source/includes/_overview.md
Fix a typo in [the API v1 overview](https://circleci.com/docs/api/v1/#accept-header).
Easy to read
=> Fix typo in API v1 overview

jekyll/_cci2/orb-author-validate-publish.md
* retain manual orb creation steps to link to as an alternative to the orb dev kit
=> manual orb auth steps

jekyll/_cci2/orb-author-intro.md
Fix a broken link in the Docs/2.0/ orb-author-intro
Easy navigation and easy reading.
=> Fix a broken link in Docs/2.0/ orb-author-intro

jekyll/_cci2/building-docker-images.md, jekyll/_cci2/configuration-reference.md
- Add 19.03.13 to list of supported remote docker versions
- Udate software version list for beta ubuntu 20.04 image
Docker 19.03.13 is now supported
=> Add 19.03.13 to list of supported remote docker versions

docs/local-development.md
Fixed the link provided for Gemfile to https://github.com/circleci/circleci-docs/blob/master/Gemfile.
The link was leading to a 404 Error page and needed a fix.
=> Fixed the link for Gemfile

jekyll/_cci2/local-cli-getting-started.md, jekyll/_cci2/local-cli.md
The link in the docs is leading to 404 page,  so I replaced it with the correct one.
Easy navigation and easy reading.
=> Fix Broken Link in Docs/2.0/ local-cli

jekyll/_cci2/local-cli-getting-started.md
Fix Typo which caused the Link to be dead in Docs/reference-2-1/
#Orbtoberfest
Easy navigation and easy reading.
=> Fix Typo which caused the Link to be dead in Docs/reference-2-1/

jekyll/_cci2/code-coverage.md
The link https://coveralls.io/docs is an old link and is not maintained anymore.
This PR replaces the link with the updated link to the coveralls doc.
Should fix https://github.com/circleci/circleci-docs/issues/4782
=> docs: fix the coveralls link

jekyll/_cci2/testing-macos.md, jekyll/_data/sidenav.yml
Created a new document to outline how to test macOS Apps on CircleCI
Companion documentation to the new orb: https://circleci.com/orbs/registry/orb/circleci/macos
=> Create macOS App UI Testing documentation

jekyll/_cci2_ja/docker-hub-pull-through-mirror.adoc
Fixed wrong hyperlink format
Some hyperlinks have modified in *.md notation, not *.adoc notation by mistake.
=> Update to fix hyperlinks

jekyll/_cci2/triggers.md
Adding outer single quotes  the ["Trigger a Job Using curl and Your API Token" example](https://circleci.com/docs/2.0/triggers/#trigger-a-job-using-curl-and-your-api-token).
In the current example:
```
curl -u ${CIRCLE_API_USER_TOKEN}: \
-d build_parameters[CIRCLE_JOB]=deploy_docker \
https://circleci.com/api/v1.1/project/<vcs-type>/<org>/<repo>/tree/<branch>
```
The absence of outer quotes around the data "name=value" pair will cause the command to fail with:
```
no matches found: build_parameters[CIRCLE_JOB]=deploy_docker
```
A note could be added to mention that double quotes can also be used, instead of single quotes.
=> Adding necessary outer single quotes around the parameter

src-api/source/includes/_builds_and_jobs.md
Add missing closing quote in the "**Trigger a new Job**" shell example ([API v1 documentation](https://circleci.com/docs/api/v1/#trigger-a-new-job))
The current syntax is incorrect.
```
curl -X POST --header "Content-Type: application/json" -H "Circle-Token: <circle-token>" -d '{
"tag": "v0.1", // optional
"parallel": 2, //optional, default null
"build_parameters": { // optional
"RUN_EXTRA_TESTS": "true"
}
}
https://circleci.com/api/v1.1/project/:vcs-type/:username/:project
```
The above cURL request will not be executed, and won't trigger any job.
=> Add missing closing quote

jekyll/_cci2/pipelines.md
This page contained a note and screenshots for access the old UI with the "Old Experience" button. However, access to the old UI was sunset as of Aug 14.
This proposed change removes those instructions, to prevent readers from looking for a button they no longer have access to.
Remove outdated reference to old UI for clarity
=> Remove instructions for accessing the old UI

jekyll/_cci2/triggers.md
Removing note "_You cannot currently trigger jobs that use 2.1 config from the API_." in the ["Trigger a Job Using curl and Your API Token" example](https://circleci.com/docs/2.0/triggers/#trigger-a-job-using-curl-and-your-api-token).
I ran tests with a `config.yml` that uses `version: 2.1`. The job I successfully triggered includes [conditional steps](https://circleci.com/docs/2.0/reusing-config/#defining-conditional-steps), and is part of a workflow that contains [`post-steps`](https://circleci.com/docs/2.0/configuration-reference/#pre-steps-and-post-steps-requires-version-21).
=> Remove note about jobs that use 2.1 config 

jekyll/_cci2/private-images.md, jekyll/_cci2_ja/private-images.md
This example explains how to authenticate to docker hub to avoid Docker hub rate limiting. However, this example doesn't include the docker login step, so I add it. 
```
jobs:
machine-job:
machine: true
steps:
- docker/pull:
images: 'circleci/node:latest'
```
↓
```
jobs:
machine-job:
machine: true
steps:
- docker/check:
docker-username: mydockerhub-user  # DOCKER_LOGIN is the default value, if it exists, it automatically would be used.
docker-password: $DOCKERHUB_PASSWORD  # DOCKER_PASSWORD is the default value
- docker/pull:
images: 'circleci/node:latest'
```
=> Add missing docker login step

jekyll/_cci2/hello-world-windows.md
Updates link to Visual Studio licensing terms.
The link to Visual Studio licensing terms seems to have changed.
=> Update link to Visual Studio licensing terms.

src-api/source/includes/_builds_and_jobs.md
Adding missing closing quote in the "**Trigger a new Job with a Branch**" cURL example ([API v1 documentation](https://circleci.com/docs/api/v1/#trigger-a-new-job-with-a-branch))
The current syntax is incorrect (closing single quote missing).
```
curl -X POST --header "Content-Type: application/json" -H "Circle-Token: <circle-token>" -d '{
"parallel": 2, //optional, default null
"revision": "f1baeb913288519dd9a942499cef2873f5b1c2bf" // optional
"build_parameters": { // optional
"RUN_EXTRA_TESTS": "true"
}
}
https://circleci.com/api/v1.1/project/:vcs-type/:username/:project/tree/:branch
```
The above cURL request will not be executed, and won't trigger any job. (Similar to [PR #4817](https://github.com/circleci/circleci-docs/pull/4817))
=> Adding missing closing quote in API doc example

jekyll/_cci2/api-job-trigger.md
1. Add necessary outer quotes to cURL requests
1. Add note with alternative syntaxes (use double quotes, escape square brackets)
In the [current example](https://circleci.com/docs/2.0/api-job-trigger/#overview):
```
curl -u ${CIRCLE_API_USER_TOKEN}: \
-d build_parameters[CIRCLE_JOB]=deploy_docker \
https://circleci.com/api/v1.1/project/<vcs-type>/<org>/<repo>/tree/<branch>
```
The absence of outer quotes around the data "name=value" pair will cause the command to fail with:
`no matches found: build_parameters[CIRCLE_JOB]=deploy_docker`
(See [PR #4818](https://github.com/circleci/circleci-docs/pull/4818))
&nbsp;
Alternative syntaxes can't hurt ¯\\\_(ツ)\_/¯
=> Add outer quotes and alternative syntaxes (cURL request example)

jekyll/_cci2/nomad.adoc, jekyll/_data/sidenav.yml
* Formatting failed for some steps due to lack of line space. This fixes it.
* Also update "Nomad" in navigation to "Intro to Nomad" - just for clarity
=> fix step formatting and improve side nav naming

jekyll/_cci2/building-docker-images.md
Clarify docker installation in 3rd party images
Acting on recent feedback with regards to running docker commands in a container using a 3rd party image that doesn't already have docker installed.
=> Clarify docker installation in 3rd party images

jekyll/_cci2/configuration-reference.md
I think, based on the context of this section, that the example image was suppose to be a Windows image not a Linux one.
=> Fix a mislabled image.

jekyll/_cci2/sample-config.md
On [**Sample Configuration with Fan-in/Fan-out Workflow**](https://circleci.com/docs/2.0/sample-config/#sample-configuration-with-fan-infan-out-workflow) section, the `auth` key within `docker` element is improperly indented on some jobs like: prepare-dependencies, build-production and test, So I have fixed it 
it might mislead/confuse someone who read the guide if he wasn't vigilant enough that there's a typo in indentation
=> 🔧 Fix some jobs indentation on sample-config.md

jekyll/_cci2/workflows.md
This PR adds an additional example of how to utilize tag and branch filtering to run specific workflows.
We had a customer make the suggestion of adding this example to the documentation and I believe it adds some additional clarity to the different ways you can use tags to filter workflows.
=> Add additional example on tag filters for workflows

jekyll/_cci2/oss.md
Even if the only build pull requests option is enabled, tag pushing triggers builds. 
A customer asked this question through the ticket, and we didn't mention about this behavior on the doc.
=> Update the note for the only build pull requests option

src-crg/README.md
I have fixed the broken link for Slate Docs.
The link was leading to a 404 error page and needed a fix.
=> Fixed the link for Slate Docs

README.md
I have fixed the link for Server Build Documentation. 
The link was leading to a 404 error page and needed a fix.
=> Fixed the link for Server Documentation

jekyll/_cci2/concepts.md, jekyll/_cci2/executor-intro.md
Reference new `ubuntu-2004:202010-01` image in examples
We have an Ubuntu 20.04 machine image available now
=> Update machine image examples to use Ubuntu 20.04 image

jekyll/_cci2/docker-hub-pull-through-mirror.adoc
Added an instruction to configure VMs for `machine` executors and jobs with `setup_remote_docker` to use the pull through cache server. This is to mitigate impacts of _the_ rate limit on those VMs.
To introduce the solution upon customer requests: Without this or a similar solution, `machine`/`setup_remote_docker` jobs are prone to be impacted by the rate limit.
=> Added an instruction to configure machine/remote docker to use the proxy

jekyll/_cci2/custom-images.md
Add bash to the list of required tools for primary images.
I was surprised to see a build using a custom image built on Alpine Linux fail because `bash` wasn't installed. Alpine apparently doesn't include `bash` by default, so I'm hoping to save the next person a few minutes by implying they should check to ensure that `bash` is present in their image.
=> List bash as a required tool

jekyll/_cci2/orbs-best-practices.md
Link directly to the relevant orb categorization section in the orb authoring page
The current link to the orb categorization reference links to the entire orb authoring page instead of to the relevant section.
=> Update link to orb categorization docs

jekyll/_cci2/caching.md
Lerna has changed the command for package output in the latest major release: https://github.com/lerna/lerna/blob/master/CHANGELOG.md#breaking-changes
this should prevent any errors for people copy/pasting the command. I've tested this locally and it produces the expected output.
=> Update lerna command to latest version

jekyll/_cci2/faq.md
* refills now at 2%
* clarify jobs fail when no credits left on free plan
=> Plans updates

jekyll/_cci2_ja/reusing-config.md
Link to https://circleci.com/ja/ instead of http://circleci.com/ja on https://circleci.com/docs/ja/2.0/reusing-config
Part of Q3 2021 SEO audit. HTTPS page is linking to HTTP pages on our website.
=> SEO audit: Update http to https on /ja/2.0/reusing-config/  

jekyll/_cci2/reusing-config.md
Link to https://circleci.com instead of http://circleci.com on https://circleci.com/docs/2.0/reusing-config/ 
Part of Q3 2021 SEO audit. HTTPS page is linking to HTTP pages on our website.
=> SEO audit: http to https on /2.0/reusing-config/

jekyll/_cci2/usage-stats.adoc
Link to https://circleci.com/legal/enterprise-license-agreement/  instead of https://circleci.com/outer/legal/enterprise-license-agreement.pd on https://circleci.com/docs/2.0/usage-stats/ 
No longer will lead to a 404
=> SEO audit: Update 404 link

jekyll/_cci2/configuration-reference.md
Added clarity around the the `when` attribute, `store_artifacts` and  `store_test_results` not running if the job has been **killed** by a cancel request or reaching the global 5 hour timeout.
Support Ticket #80787
=> Clarify where steps aren't run due to being killed

jekyll/_cci2/orb-concepts.md, jekyll/_cci2/using-orbs.md
fix some incorrect orb name template in two document pages.
related to #4883
=> fix wrong orb name template in orb-concept and using-orbs pages.

jekyll/_cci2_ja/about-circleci.md
Link to https://circleci.com/ja/ instead of https://circleci.com/ja on https://circleci.com/docs/ja/2.0/about-circleci/ 
Part of Q3 2021 SEO audit. Update link to no longer go to a redirect.
=> SEO audit: /2.0/about-circleci/

jekyll/_cci2/executor-types.md
This line mentions users need to submit a support ticket to enable DLC. This is no longer the case. They simply need to be on a plan which has it enabled by default. They can see which plans have it available on the pricing page.
It's outdated
=> Clarify use for docker layer caching

jekyll/_cci2/private-images.md
Add titles sections for quick access and ease of reading.
From my experience, a structured document is much easier to read.
It also allows TL;DR for people without the need to overview the whole document while searching or go `ctrl+F`.
=> Add Titles

jekyll/_cci2/proxy.adoc, jekyll/_cci2_ja/proxy.md
A customer failed to set up the proxy setting to the Replicated, and we noticed some scripts in this doc have the wrong syntax.
Tickets
> https://circleci.zendesk.com/agent/tickets/80913
=> [Patch/proxy] fix wrong bash syntax

jekyll/_cci2/testing-ios.md
- update `12.2.0` to point from beta to `12.2 RC`
- add `12.1.1` (this will later redirect from `12.1.0`)
=> update Xcode release list

jekyll/_cci2/aws.adoc
Hello!
This suggested PR makes small edits to the language, replacing uses of the word "see" with "read" where applicable, and more appropriate language where "read" was not accurate. I also replaced a purely text image with text in a code block. The reason for these changes is to make the document more accessible to users reading documentation with a screen reader.
I also noticed this document referenced both "Nomad clients" and "Nomad Clients" in line 34, and after perusing HashiCorp's documentation, chose to edit them for consistency to lower case in this doc.
Cheers,
Jorie
=> Edit: Installation on AWS for a11y and consistency

jekyll/_cci2/ios-codesigning.md
CircleCI only supports Fastlane match officially, so removing this old link to prevent confusion
=> Remove non-Match code signing link

jekyll/_cci2/orb-author-intro.md
I have included further descriptions of the values in the command line to more easily understand and follow these setup instructions
When attempting to follow these instructions to set up a new namespace for the first time, the arguments were unclear, especially considering these are getting started docs. It would be helpful to include this brief description for first time authors to understand what they need to input to the command line
=> Include further description of command line values

jekyll/_cci2/docker-hub-pull-through-mirror.adoc
* Adding instructions to setup a mirror listening for HTTPS connections.
* Tuning other parts accordingly
There was a customer report that the mirror needs to be secure in certain use cases, especially if the VMs are configured to use BuildKit. This was the initial motivation to update this page.
Upon making this update, I'm also adding touches to enhance the entire document. Especially, there was an advice from @ryanwohara that we need to clarify that service containers will not be pulled through the proxy, and that it is our intention: This is what I did in the second commit.
=> Updates on instructions to setup pull through cache

jekyll/_cci2/migrating-from-jenkins.md
Update link to jenkins file converter. Add text for link, rather than raw link.
Was not actually a link.
=> Fix raw link to jenkins converter

jekyll/_cci2/testing-ios.md
Fixed a minor spelling mistake `environement` to `environment`
Came across this while reading through the docs, figured I'd fix it
=> fixes minor typo in ios docs

jekyll/_cci2/runner-overview.adoc
Align runner docs with wording from the [build environments page](https://circleci.com/build-environments/runner/)
This wording pre-dates the environments page.
=> Align runner docs with wording from build environments page

jekyll/_cci2/enable-checks.md
fixes #4871 
Parts of the GitHub checks guide are currently confusing: GitHub checks and GitHub status updates are separate features that enable/disable each other to avoid having workflow and job status shown concurrently, although projects can be set like that if desired.
I still need to do some testing but this PR is to make the guide clear and correct.
=> clarifications around github status updates and github checks

jekyll/_cci2/add-ssh-key.md, jekyll/_cci2/gh-bb-integration.md, jekyll/_cci2_ja/add-ssh-key.md, jekyll/_cci2_ja/gh-bb-integration.md
Modern SSH key formats are now supported.
Additionally we support keys in OpenSSH's default "openssh" encoding, and no-longer require users to specify `-m PEM`.
https://circleci.atlassian.net/browse/CIRCLE-30948
=> [CIRCLE-30948] Document that modern SSH keys are supported

jekyll/_cci2/testing-ios.md
There is a missing cell block in the table as shown [here](https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions). This adds in the missing field. 
The missing data is in the first two rows, in the `macOS UI Testing Supported` column.
We do not want missing data cells on our public documents.
=> iOS Testing Update Missing Cell Block

jekyll/assets/js/sidebar.js
See [pertinent conversation](https://circleci.slack.com/archives/C0KBNJGRH/p1607020012220300).
Demo that compares `Prod<>Local`:
=> [Prototype] Add: Scroll to active sidebar element.

jekyll/_cci2/configuration-reference.md
We have a note that combined two concepts:
1. Info about possibly needing to pin the number of CPU count
2. Info about how to find the amount of memory you have been allocated
Combined it reads that the command to find memory helps find information about CPU usage, but in reality, they are separate concepts.
This PR will move the information about finding memory allocation to it's own note so the concepts are split up.
Was working with a customer and was referencing this section and it caused some confusion.
=> Move information about tracking available memory to own note

jekyll/_cci2/proxy.adoc
Change the scripts for setting proxy
The initial document's script doesn't work for the current server, and we noticed `/etc/circle-installation-customizations` is just a shell script, so to set environment variables, it needs to set `export` before the environment variables.
=> fix proxy setting

jekyll/_cci2/testing-ios.md
Updated `Xcode 12.2` from `RC` to `final release`.
The already released the `final release` but never updated the documentation.
=> Updated Xcode 12.2 links

jekyll/_cci2/configuration-reference.md
Add a note for the `requires` option
> https://circleci.atlassian.net/browse/CIRCLE-28227
A customer reported an issue that the requires option ignores the filter job dependency.
For example, the customer expected job C won't run when the customer pushes a commit to master, because job B won't run due to the filter option. However, the `requires` option ignores the filter job dependency so that after Job A finished, Job C will run. 
```
workflows:
version: 2
workflow:
jobs:
- A
- B:
filters:
branches:
only: master
- C:
requires:
- A
- B
```
=> Add note for requires option 

jekyll/_cci2/building-docker-images.md
Add 17.09.0-ce version which is the default version of the setup_remote_docker
A customer asked about it
=> Add default setup_remote_docker version

jekyll/_cci2/gh-bb-integration.md
Document limitations w.r.t. the name of default (personal) Bitbucket
workspaces.
Add documentation outlining limitations of Bitbucket personal workspace names within CircleCI.
https://circleci.atlassian.net/browse/CIRCLE-30060
=> [CIRCLE-30060] Add doc on personal BB workspace constraints

jekyll/_cci2/yarn.md
- Make it clear which Yarn version the example is for
- Adds example for caching with Yarn 1.x versions
The fourth  Documentation value states
> 4. Clear: documentation should be clear.
> https://github.com/circleci/circleci-docs/blob/master/docs/CONTRIBUTING.md#circleci-documentation-values
The documentation examples do not make it clear which version of Yarn they are referring to.
Yarn 1.x is still very popular and frequently used in projects. Users of Yarn 1.x may be confused by the current example.
=> Indicate which version of Yarn examples are referring to and add Yarn 1.x example

jekyll/_cci2/local-cli.md
Specify where the `sudo` should go.
Since this is a piped operation, doing `sudo curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | bash` won't work.
=> Add note on where "sudo" should go

jekyll/_cci2/configuration-reference.md
Workspace caches have a hard limit of 15 days.
We received a ticket from someone who has designed a workflow that can have a lifetime between 1-90 days through the use of an on-hold job. They attempted to approve the on-hold job after 16 days, which failed the deployment because the files no longer exist. they were lead to believe the workspaces would exist indefinitely because of the wording here.
=> Clarify workspaces cache expiration.

jekyll/_cci2/optimizations.md, package-lock.json, package.json
Adding missing link to the [`attach_workspace` documentation](https://circleci.com/docs/2.0/configuration-reference/#attach_workspace).
In [this section](https://circleci.com/docs/2.0/optimizations/#workspaces), the link to the `attach_workspace` documentation is missing, which contrasts with the formatting for ` persist_to_workspace`.
=> Add missing link to attach_workspace documentation

jekyll/_layouts/classic-docs.html
This applies a design change to align the left side of search results with the left side of the search bar spyglass and header/nav. Previously it was indented.
I didn't un-indent the contents of the div that was removed in order to keep the diff clean and not muddy the line history, but I'm happy to change that if desired.
Note that using a `row` element without a child `col` element is a misuse of the Bootstrap grid system, but the header and search bar are already doing this so we have to make the same mistake here to get them to align with each other.
=> [CIRCLE-31528] Align search results with search bar and nav

jekyll/_cci2/testing-ios.md
Xcode 12.3 has been built and released.
Jira: https://circleci.atlassian.net/browse/MAC-268
=> [MAC-268] Add Xcode 12.3

jekyll/_cci2/gh-bb-integration.md
Bitbucket seems to no longer support "squatting" your personal workspace
ID (matching username) after renaming the original default user
workspace. Remove the advice that notes this as an alternative from our
BB personal orgs documentation.
Remove documentation on (now unsupported) Bitbucket personal workspace alternative.
Follow-up to work on [CIRCLE-30060](https://circleci.atlassian.net/browse/CIRCLE-30060)
=> [CIRCLE-30060] Remove alternative BB personal workspace advice

jekyll/assets/css/main.scss
Helps smooth out the fallback behavior when Roboto isn't present (e.g Google Fonts down/blocked).
I have Google Fonts blocked (mostly for performance reasons), which leads to the docs falling back to a serif font.
=> Add sans-serif to all font-family entries.

jekyll/_cci2/runner-overview.adoc
This adds some clarification on steps customers can take if we don't currently support their runner use case.
=> Update runner docs

.circleci/config.yml, jekyll/_config.yml
Best reviewed by https://github.com/circleci/circleci-docs/pull/4997/files?w=1
This change allows us to automatically deploy docs that passed tests to a non-production s3 bucket.
To deploy from multiple branches at the same time so that they don't override each other, we need to have different `baseurl` instead of canonical "docs" baseurl.
e,g, http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/deploy-preview
This is mostly achieved by creating `_config_override.yml` with some CircleCI config tweaks.
If this approach looks, good, we can set lifecycle management for preview s3 bucket so that stale preview deployment can be automatically deleted.
=> Deploy preview

.circleci/config.yml
The existence of symlink made `aws s3 sync` to fail in deploy job https://app.circleci.com/pipelines/github/circleci/circleci-docs/26932/workflows/0dea04d6-07e6-474f-b4cc-d1bc5497bef3/jobs/73385
=> Delete symlink workaround once htmlproof passes

.circleci/config.yml
Slightly simplifying the build process by only creating symbolic link when `${JEKYLL_BASENAME}` is not `docs`.  Removing symbolic link is not needed because it won't create symbolic loop since it always be linked to something that's not `docs`.
=> Only create symlink when jekyll base is not docs

jekyll/_cci2/demo-apps.md
Updated the language 'Ruby and Rails' to 'Ruby on Rails'.
I could not make this change on the language-guides.md - can you make this update?  Thanks!
It should be called Ruby and Rails, not Ruby on Rails.
=> Changed 'and' to 'on' for Ruby on Rails

jekyll/_cci2/runner-installation.adoc
Add a brief note about the necessary permissions to execute the steps
It was not clear that you need to be an org admin to create resource classes and tokens.
=> Add note about necessary permission

jekyll/_cci2/config-intro.md
Docker auth is not required except for in specific rate-limiting examples/private images; the examples in this introductory document should be simple and minimal. A recent PR that made note of optional docker image authentication misaligns the line numbers in code samples with the prose text.
Fixes #4996
=> Clean: simplify config-intro example

jekyll/_cci2/executor-types.md, jekyll/_cci2/private-images.md
We identified that image pulling from non us-east-1 ECR repositories is significantly slower than pulling from us-east-1 ECR repositories.
Adding a tip to encourage people to use us-east-1 ECR when using ECR image for Docker executor.
https://circleci.atlassian.net/browse/CIRCLE-31743
=> [CIRCLE-31743] Add tip to use us-east-1 ECR

jekyll/_config.yml, jekyll/_includes/js-config.html, jekyll/_layouts/classic-docs.html, src-js/instantsearch.js
Adds Convenience Image search, following the pattern established for Orbs Registry search. Includes config necessary to generate i18n Dev Hub URLs from image names.
=> [CIRCLE-31447] Add Convenience Images to search

jekyll/_cci2_ja/about-circleci.md
Update link from https://circleci.com/jp to https://circleci.com/ja/ on https://circleci.com/docs/ja/2.0/about-circleci/. Will no longer lead to a 404 error.
Part of Q4 SEO audit fixing a broken redirect.
=> Update broken redirect on /docs/ja/2.0/about-circleci/

jekyll/_cci2_ja/language-ruby.md
Update link from https://circleci.com/docs/ja/2.0/circleci-images to https://circleci.com/docs/ja/2.0/circleci-images/ on https://circleci.com/docs/ja/2.0/language-ruby/. Will no longer create a redirect chain.
Part of Q4 SEO audit fixing a redirect chain.
=> Update redirect link on /docs/ja/2.0/language-ruby/

jekyll/_cci2/sample-config.md
I'm working on a build-agent change that will remove this need.
`CIRCLE_WORKING_DIRECTORY` was set as a pure string, so any variable expansion on the envvars does not take place, e.g.
```
circleci@default-314602d9-7782-4a60-9048-17ff8feba347:/$ echo $CIRCLE_WORKING_DIRECTORY
~/project
circleci@default-314602d9-7782-4a60-9048-17ff8feba347:/$ cd $CIRCLE_WORKING_DIRECTORY
-bash: cd: ~/project: No such file or directory
```
As stated in some docs examples, https://circleci.com/docs/2.0/sample-config/#sample-configuration-with-multiple-executor-types, it's suggested you do `eval cd $CIRCLE_WORKING_DIRECTORY`, however, this is not very straightforward or expected from a new user's perspective. 
The intended fix evaluates `~` to `$HOME` and evaluates any envvar before being set. 
The newly …
=> Remove need to eval for variable expansion

jekyll/_cci2/sample-config.md
I tried fixing working directory expansion, but it appears to not be worth fixing. Adding this hack back
=> not fixing circle_working_directory

jekyll/_cci2/runner-overview.adoc
Replaced reference to intel with x86_64
This fixes #4934 
=> runner updates (reference to intel removed)

jekyll/_cci2/hello-world-macos.md
Added a snippet explaining Xcode cross compilation and universal binaries to hopefully clear up how
these work for customers.
https://circleci.atlassian.net/browse/MAC-287
=> Xcode Cross Compilation documentation added

jekyll/_cci2/parallelism-faster-jobs.md
This PR will add a note that the `circleci tests split` command cannot be run locally.
We had customers asking if this was possible or not, and at the moment it isn't. We note in the docs steps on adding the CLI locally (since it can be used for other things) but could lead to confusion that the command could be run. 
See comment here for confirmation this command cannot be run locally:
https://github.com/CircleCI-Public/circleci-cli/issues/383#issuecomment-755330662
=> Add a note that circleci tests split cannot be run locally

jekyll/_cci2/add-ssh-key.md
Added Note to page notifying users that they may need to add the public key to "~/.ssh/ authorized keys"
=> public key update

jekyll/_cci2/configuration-reference.md
Add new 20201 Q1 machine images as well as Ubuntu 16.04 EOL note.
=> Add Q1 images.

jekyll/_cci2/parallelism-faster-jobs.md
I recently updated the docs to add a note that the split command couldn't be run locally with the CLI:
https://github.com/circleci/circleci-docs/pull/5049
However, you also can't run the `glob` command. This PR will update the note to add that information and also add a disclaimer above the tutorial video that the commands being run would have to be done in an SSH session.
Wanted to further clarify what could and couldn't be run locally and how to follow the video in the docs.
=> Update disclaimer to note both glob and split are unable to be used locally

jekyll/_includes/ja/global-footer.html, jekyll/_includes/ja/global-nav.html, jekyll/_layouts/classic-docs.html, jekyll/_plugins/include_localized.rb
Using the strategy discussed on the Jira ticket, this adds Japanese versions of the global header (nav) and footer, as well as a custom Liquid tag for automatically including the page's language's version of the given template.
=> [CIRCLE-31923] Internationalize header and footer

jekyll/_cci2/api-developers-guide.md
Our API developers guide has a fair bit of content that is duplicated (in the actual API specification. This PR performs the following:
- Clean: remove duplicate content in intro.
- Fix: description of how to get api token.
- Clean: remove superfluous HTTP code section.
- Clean: simplify rate-limiting language.
- Clean: simplify table of contents.
- Clean: remove redundant api endpoint section
- It is better that we link users to the actual api specification guide
which will always be up-to-date (as it is generated from spec in
the actual API) rather than re-create the documentation.
=> Update: Api developers guide

jekyll/_cci2/runner-installation.adoc
This PR will add a note that the commands can only be run by the owner/admin of the Organization.
We note this information for claiming namespaces for orbs:
https://circleci.com/docs/2.0/orb-author-faq/#errors-claiming-namespace-or-publishing-orbs
But the same information was not noted for Runner and I received a ticket from a customer wondering why they couldn't setup runner.
=> Add note to runner docs that commands can only be run by org admin

jekyll/_cci2/runner-installation.adoc
While systemd-run does offer slightly more isolation, the additional
complexity and compatibility concerns make this awkward, and leads
to some users struggling to get up and running
As the user already needs to be careful with leaking state to the
filesystem, it doesn't seem unreasonable to leave the also responsible
for leaking processes
=> Drop systemd-run in favour of sudo -u

jekyll/_cci2/configuration-reference.md
The description on `checkout` states that if the path already exists in the workspace, then it will _pull_ origin. In reality, the script does a _fetch_ command and it doesn't integrate remote changes into the current branch, if there are any.
Updating the docs to use more accurate wording, as a `git pull` is different from a `git fetch`
I've recently updated my workflow to use `checkout`. Because the description states that the script does a pull, I assumed that meant `gill pull`, however, after my workflow failed and looking at the `checkout` script, it only does a `git fetch`. I'm suggestion an update to the docs to reflect a more accurate wording that mimics Git's commands
=> Update description of "checkout" step

jekyll/_cci2/language-android.md
Include mention of the Android machine image that is now available for preview and which supports x86 Android emulator tests
Keep our docs up-to-date
=> Include preview Android machine image

jekyll/_cci2/orbs-faq.md
We recently launched the private orb function for scale customers, so I updated the Private Orb faq section.
> https://circleci.slack.com/archives/CNHFJ07LZ/p1612340604057800
=> add Private orb information

jekyll/_cci2/docker-hub-pull-through-mirror.adoc
The customization is only available after 2.19 and later versions.
A customer failed to configure this due to the old server version.
=> Update a warning for the customization script to use docker proxy in machine / remote docker

jekyll/_cci2/workflows.md
This PR adds a disclaimer that setting up a range of days written out is not supported. 
Crontab says this is valid:
https://crontab.guru/#0_5_*_*_Tue-Sat
And while that might be the case for some systems, it isn't valid within a CircleCI config. Instead, the values need to be comma separated digits like: https://crontab.guru/#0_5_*_*_2,3,4,5
=> Add note about range elements for days

jekyll/_cci2/workflows.md
Clarifies and closes #5000.
See discussion in https://github.com/circleci/circleci-docs/pull/5069
=> Add: clarification on valid cron syntax.

jekyll/_cci2/env-vars.md
When setting the job level environment variable yaml will convert an integer that has 7 or more digits to an exponential number. I.e. `7777777` would become `7.777777e+06` in the job. 
To avoid this automatic conversion the value instead needs to be stored as a string so instead of `7777777` you would set it to `"7777777"`.
This only happens when setting these variables in the `config.yml` itself -- it doesn't happen when you set these as project-level variables.
CIRCLE-23958 -- this is something that was noted as a natural consequence of using YAML, so want to ensure this is documented has customers have encountered this previously. I will also be adding a support article as well.
=> Add note about 7 digit integers converting to exponential number

src-api/source/includes/_builds_and_jobs.md
Clearly state that `https://circleci.com/api/v1.1/project/:vcs-type/:username/:project/build` endpoint is not available for CircleCI Server.
To use this endpoint, one must enable pipelines, but the pipeline is a CircleCI 2.1 feature and it is not yet available for CircleCI Server. Since it is not stated clearly that is it not available, it is causing some confusion.
=> Clarify that api v1 /build endpoint is not available on Server

jekyll/_cci2/orb-intro.md
Fixes the `circleci config validate` orb command optional flag name so it's accurate in private orbs doc
This is a small fix so there's no JIRA. We're launching private orbs, so this needs updating
=> Fix instructions for validating config with private orbs in them

jekyll/_cci2/configuration-reference.md
A dependent job is only filtered if all of its dependencies are
filtered, which is not very clear right now.
Describe job dependency filtering more accurately
We sort of discovered this oddity together this morning. We cannot change it without breaking existing users, but are looking into changing it in future config versions.
=> Describe job dependency filtering more accurately

jekyll/_cci2/about-circleci.md
I replace the word master with main
I saw this word master in our text and considering that the industry is replacing these words with more generic and acceptable terms I suggest we use main as a replacement for master moving forward.
=> Changed the words master to main

jekyll/_cci2/hello-world-windows.md
Updated page to include .NET Core SDK 3.1.406
=> .NET Core SDK 3.1.406 Update

jekyll/_cci2/faq.md
removed reference to macOS in Container Plans section of page
=> macOS in Container Plan removed

jekyll/_cci2/enable-checks.md
"...using a Github Checks because..." --> "...using a Github Check because..."
"...using a Github Checks because..." --> "...using a Github Check because..."
Because the typo bothered me more than any theoretical SEO or UX benefits
=> Grammar/typo fix in enable-checks.md

jekyll/_layouts/classic-docs.html, src-js/instantsearch.js
We can use the `dynamic-fixed` mode of the subnav component to accomplish this, with a custom top nav offset param to account for the fixed-position search bar.
We also need to scroll the document back to the top upon tab changes, which we can do by attaching a handler to the boostrap tab shown event.
=> [WEB-7] Make search result category tabs sticky

jekyll/_cci2/reusing-config.md
Corrected the version of python specified in the compiled config snippet to match that of the parameter being passed in
3.8 -> 2.7
Having two conflicting version numbers in the config would lead to people getting confused when reading the docs, and perhaps reuse that incorrect config for their builds.
=> Correct version of Python in example config

jekyll/_includes/main-searchbar.html, jekyll/_layouts/classic-docs.html, jekyll/_sass/_instantsearch.scss, jekyll/_sass/_subnav.scss, jekyll/_sass/_variables.scss, jekyll/assets/css/navbar.css, src-js/instantsearch.js
This adds a mobile version of the search result category subnav, as well as some page layout structure improvements to enable that change.
Those changes resolve some long-standing Bootstrap grid misuse in the header and search bar:
1. Search query bar and results container had a row without   accompanying columns (should just be a container sans row). The   query bar CSS had manually implemented (and incomplete for mobile)   margins to compensate, which are now removed.
2. The header logo was absolutely positioned, resulting in it appearing   outside its surrounding column/container (too far left). This commit   removes that, allowing it to be positioned on the left edge of its   container where it will align with other containers on the page,   such as the search query bar and results …
=> [WEB-95] Search Results for mobile

jekyll/_cci2/pipeline-variables.md
This PR will update the description of `pipeline.git.base_revision` and add a note about known caveats on when it will and will not be present.
The variable name itself `base_revision` has caused some confusion historically with our customers, as it implies that it will be the base of the tree. In reality, that isn't the case, and it will be associated with the last build.
Technically speaking we grab this value from the following places:
1. In GitHub, we get it from the `before` key in the webhook payload
2. In Bitbucket we get it from the `hash` key in the `parents` array in the webhook payload
=> Add clarifying information around 'pipeline.git.base_revision' variable

jekyll/_cci2/configuration-reference.md
Add a note that `large` resource class for macOS is available only for annual plans
Add a note that large resource class for macOS is available only for customer with annual contracts.
There is an increasing number of support tickets that requests for macOS large resources with M2M plans We had a feedback from those support requesters that being told posteriori that the resource is available only for annual plans is not a good experience. Adding this pre-emptive note mitigates such sentiment risks.
See also: https://circleci.slack.com/archives/CJNASDDEZ/p1614815062028700?thread_ts=1614809740.026300&cid=CJNASDDEZ
=> Add a note that large resource for macOS is available only for annual plans

jekyll/_cci2/runner-installation.adoc
- Tested and added instructions for execution on CentOS/RHEL distros. Also tested and confirmed that Ubuntu instructions work for Debian.
- **Why:** Customer(s) want it.
- Migrated supported/unsupported platforms lists to a table for easier viewing.
- **Why:** Easier to skim and read. We can discuss this a bit more and/or discard changes if you want.
- Modified a few commands in installation script
- **Why:** Cross-platform issues. Some linux distros didn't recognize `sha256sum --ignore-missing` so I directly find the relevant SHA by grepping for it in `checksums.txt`
See attached images
- Primarily for a specific customer looking to get started on RHEL/CentOS.
**Before:**
**After:**
**Before:**
```bash
... (unchanged)
file="$(grep -F "$platform" checksums.txt | cut -d ' ' -f 2)" …
```
=> Update runner docs for CentOS, RHEL, Debian

jekyll/_cci2/configuration-reference.md
Additional touches in regard to #5124: Inserting a line break for better legibility of footnotes.
=> Insert a linebreak inbetween numbered footnotes

src-js/lang.js
Make sidebar language selector redirect to the same content.
It used to redirect to the base URL. So, I was not using this selector,
because directly writing `ja` to the URL were much easier.
This implementation relies on regexp to parse the current full URL to
replace the `docs/ja` or `docs` part to the target slug.
It also redirects to the base URL as a fallback if the URL does not match.
=> Language selector now redirects to the same content

jekyll/_cci2/configuration-reference.md
The current regex example will trigger if a branch name starts with `server/`, but for it to match any string that contains `server/` it would need to be `/.*server\/.*/`.
Changing the wording will help clarify the outcome.
=> Clarify regex usage

jekyll/_cci2/runner-installation.adoc
The current heading level was off, leaving this to be nested under macOS.
Also reword `command_prefix` to be a bit clearer.
=> Fix runner config reference heading levels

.circleci/config.yml, .gitignore, Gemfile, Gemfile.lock, Rakefile
- use `parallel` feature in `html-proofer` to speed up test
- use medium+ resouce_class in CircleCI
- export `html-proofer test` and `jekyll build` commands into Rakefile
- pack artifacts before uploading them into CircleCI artifacts
The `html-proofer` test generally takes 4 to 5 mins, so I customized it to use `parallel` feature in  `html-proofer` to speed up this test. Also, I changed circleci.yml to use `medium+` resource_class, and now the `html-proofer` test tasks about 1 min.
> https://app.circleci.com/pipelines/github/circleci/circleci-docs/27419/workflows/0309440a-a3fe-4bc0-8e5e-9667ab5002e6/jobs/75692/parallel-runs/0/steps/0-120
Also, the html-proofer and jekyll build commands were complexed. And it prevents running these commands locally.
So, I exported `html-proofer test` and …
=> Speed up `html-proofer`  test 

jekyll/_cci2/contexts.md
Adding context fields validation/restrictions docs
[CIRCLE-32867](https://circleci.atlassian.net/browse/CIRCLE-32867)
* Add criteria for validation for environment variable names/values
* Add docs on maximum number of environment variable per contexts
* Add docs on maximum number of context per organizations
* Add criteria for validation for context names
[CIRCLE-32867]: https://circleci.atlassian.net/browse/CIRCLE-32867
=> [CIRCLE-32867] Adding contexts field restrictions doc

jekyll/_cci2/contexts.md
We thought the wording around `null` seemed misleading
* Got rid of the `null` constraints 
* Renamed it to constraints instead of validation
=> [CIRCLE-32867] a bit of re-wording to provide more clarity around contexts

jekyll/_cci2/local-cli.md
Move the above into a code block.
*Note*: We should probably word wrap on `code` tags, but this will need a closer inspection across multiple pages to make sure style changes don't break; this is a temporary fix.
=> Fix: prevent long non-wrap of `code` tag.

README.md, docker-compose.yml
Changed the docker image on docker-compose to fix an issue in the local build. This is because we bumped the ruby version to `2.7.2`, and the previous image is no longer applicable. 
Slack: https://circleci.slack.com/archives/C0KBNJGRH/p1616802657027600
cc: @mvxt
=> Patch local build

jekyll/_cci2/updating-server.adoc
Small typo fix in 2.19 upgrade guide.
=> Hardcoding version in, since this is a 2.19 specific upgrade guide

jekyll/_cci2/server-3-install-migration.adoc
Change hostnames is not addressed in the migration script
Give guidances to customers on how to resolve broken webhooks if they change hostnames when migrating from 2.19 to 3
@annabaker as always, I will defer to you for formatting
=> [SERVER-1002] add warning about webhooks when using new hostname after migration

jekyll/_cci2/artifacts.md
Reference to `sed` no longer relevant.
Closes #5203
=> Update curl request example description

jekyll/_cci2/android-machine-image.md
Update orb version to include v30
Customer could not access v30 on orb version 1.0
=> Update orb version to include v30

jekyll/_cci2/runner-installation.adoc, jekyll/_cci2/runner-server.md
Some minor tweaks to the runner on Server docs
- Simplified the final systemd unit step slightly
- the `host` parameter doesn't exist, it should have been `url`
=> Some minor tweaks to the runner on Server docs

jekyll/_cci2/caching.md
Move `- run: bundle clean --force` below `- run: bundle install` base on https://circleci.com/developer/orbs/orb/later/ruby-rails-setup this example (line 53-62)
If bundle clean execute first it will through an error
=> Move bundle clean below bundle install 

jekyll/_cci2/status-badges.md
The branch page is now accessed with a query param instead of a URL path
These instructions are out of date, and create links that 404 if you follow them as written.
=> Update badge target to work with new UI

jekyll/_cci2/private-images.adoc
After fixing the style violations of private-images.md, it was converted to adoc file. And, I did not realize that when fixing conflicts, and merged them. I am removing the style fixes introduced in https://github.com/circleci/circleci-docs/pull/5187 from this adoc file.
It is a markdown jekyll style and does not apply to adoc files.
=> Fix private-images.adoc

jekyll/_cci2/runner-overview.adoc
There are a few standard features that aren't yet available on runner jobs - they were previously documented somewhere but got lost in a reshuffle.
https://circleci.atlassian.net/browse/CIRCLE-34038
=> CIRCLE-34038 Document the feature gaps between runner and normal jobs

jekyll/_includes/hits-target.html
I updated the classic-docs in [this PR](https://github.com/circleci/circleci-docs/pull/5245) to use hits-target template, but the inline version of hits-target component has changed. So, I merge the change in the original hits-target component.
=> merge the change in the original hits-target component

jekyll/_cci2/arm-resources.md
Remove contact form alert for ARM resources.
As we are opening up ARM for GA this step is not necessary anymore.
https://circleci.atlassian.net/browse/CIRCLE-34307
=> [CIRCLE-34307] Remove contact form alert for ARM resources

jekyll/_cci2/api-intro.md, jekyll/_cci2_ja/api-intro.md, jekyll/_data/api.yml, src-api/source/includes/_overview.md, src-api/source/includes/_projects.md
Remove references to the `DELETE /api/v1.1/project/:vcs-type/:username/:project/build-cache` API. This API became useless with the demise of CircleCI 1.0, returned 410 from 2020-09-25 to 2020-11-05 at which point it was removed permanently. It now returns a 404 for all customers.
At least [one customer](https://circleci.zendesk.com/agent/tickets/89483) has mistakenly tried to use this API.
=> Remove references to /project/:vcs-type/:username/:project/build-cache

jekyll/_cci2/circleci-images.md
Updates deprecated Docker images with the latest ones in [the image docs](https://circleci.com/docs/2.0/circleci-images/).
- cimg/base: 2021.04
- go: 1.16
This is from 1-hour hackathon run by CircleCI Japan at https://circleci.connpass.com/event/209710/ (cf. https://twitter.com/search?q=%23CircleCIJp&f=live)
=> Update deprecated Docker images with the latest ones

.circleci/config.yml
Removes meaningless and unused environment variable from the `build` job.
This variable was originally introduced in 0fd59b4a in 2016-03: https://github.com/circleci/circleci-docs/commit/0fd59b4a0a298c9d95e9ecd
On migration from v1 to v2, this project did not remove the variable: https://github.com/circleci/circleci-docs/pull/1048
Ref. Jekyll is not using the variable any more with CircleCI 2.0: https://github.com/jekyll/jekyll/pull/8410
Also this variable has been set only for `build` job, but [`ruby-deps` step](https://github.com/circleci/circleci-docs/blob/7354b6c9582be79565aae799a2e3c7fac0c6939d/.circleci/config.yml#L35-L43) is used in other jobs, which is inconsistent with the job.
=> Remove meaningless and unused environment variable from build job

docs/local-development.md
This PR updates URLs in local development guide `/docs/local-development.md`
Ruby version is incorrect. Other URLs are updated to reduce unnecessary redirection on a browser. 
=> Update URLs in local development guide

jekyll/_cci2/configuration-cookbook.md
Fixed the typo in the sample configuration of dynamic configuration.
There was a typo in the sample configuration.
=> Fixed a typo in sample configuration

jekyll/_cci2/configuration-reference.md
This is a new config logic element which performs regular expression
matching and can be used e.g. to check a branch name.
Convenient link: https://circleci.atlassian.net/browse/CIRCLE-32157
=> CIRCLE-32157 Add documentation for the matches logic element

jekyll/_cci2/security-server.adoc, jekyll/_cci2/security.md
Some of the fields currently documented are not actually included today in our audit logs. Their addition is currently under review w/ SecOps, but for the time being, we should remove these fields from our public docs.
**Note: https://github.com/circleci/circleci-docs/blob/ae71de285dc72df4dd184fbb47e7a665e6904648/jekyll/_cci2_ja/security.md will also require an update, but it wasn't easy for me to figure out which part of the text to delete to make a clean edit.**
_TODO: Add Jira ticket link_
=> [TODO JIRA LINK] Remove missing fields from audit log schema docs

jekyll/_cci2/artifactory.md
Signed-off-by: Adam Harvey <adaharve@cisco.com>
Running the example commands to call the JFrog CLI from CircleCI installs the latest version. In doing so, I discovered  the current JFrog CLI has deprecated one of the config commands. This PR updates the two examples, and provides a link to the CLI documentation.
Relevant docs from JFrog: https://www.jfrog.com/confluence/display/CLI/JFrog+CLI#JFrogCLI-JFrogPlatformConfiguration
=> Fix Artifactory example due to deprecation in JFrog CLI

jekyll/_sass/_instantsearch.scss
Reduce horizontal margin to fit on narrow screens with result counts populated.
Specificity rules required the inclusion of `.subnav.component` and the extra first/last child specifications.
=> [WEB-102] Prevent search result tabs from wrapping

jekyll/_cci2/server-3-operator-backup-and-restore.adoc
The velero command as written will not work because it's missing a few \'s. Adding them in.
=> Added in missing line separators

docker-compose.yml
closes. https://github.com/circleci/circleci-docs/issues/5270
Pronto requires `cmake` and `pkg-config`. So, it needs to be installed
before bundle install and docker-compose was not installing it.
=> Fixes dependency issue on docker-compose

jekyll/_cci2/executor-types.md
replicating #5258 (the pipeline was not running).
=> Remove reference to machine image in server example.

jekyll/_cci2/runner-server.md
Indicated in the Server on Runner doc a specific version of launch-agent to install with 3.0. The version is the latest stable release: `1.0.11147-881b608`
[Ticket](https://circleci.atlassian.net/browse/CIRCLE-35329), but probably more helpful is the following: as `launch-agent` version cannot be pinned in server, this docs update indicates a stable version for the initial `launch–agent` install.
Tickets to follow: [CIRCLE-35328](https://circleci.atlassian.net/browse/CIRCLE-35328?atlOrigin=eyJpIjoiMTBmYjVlYWM0YzNiNGQyNzlkZDY1MTk2NzdkOTliZGUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ) and [CIRCLE-33759](https://circleci.atlassian.net/browse/CIRCLE-33759?atlOrigin=eyJpIjoiOWEzY2UwYjczYzA2NDRkNTg2MjNlNGE5N2Q3NjkyODAiLCJwIjoiamlyYS1zbGFjay1pbnQifQ).
=> [CIRCLE-35329] Indicate launch-agent version for install with server 3.1

jekyll/_cci2/yarn.md
Updated the instructions to mention Zero Installs, and fixed the example for non-Zero Installs.
It seems like the caching instructions for yarn 2 are outdated. The caching instructions are also completely unneeded if you're using Zero Installs.
=> Update caching instructions for yarn 2

jekyll/_cci2/server-3-install.adoc
This adds the documentation for using an external MongoDB instance
SERVER-1166
=> Add external MongoDB documentation

jekyll/_cci2/server-3-operator-overview.adoc
Customers found the default terraform instance size cannot run the largest docker resource classes.  This adds some documentation around how to choose an instance size.
This is not specific to 3.1, and can target the Master branch.
This change is coupled with improvements to the server-terraform documentation on resource classes: https://github.com/CircleCI-Public/server-terraform/pull/106
https://circleci.atlassian.net/browse/SERVER-1177
=> [SERVER-1177]add clarity about how to choose instance sizes for nomad client VMs

jekyll/_cci2/server-3-install.adoc
This is a redo of https://github.com/circleci/circleci-docs/pull/5415 which was incorrectly based off of main
Server now supports Externalizing Vault. Add documentation so people know how to do it.
https://circleci.atlassian.net/browse/SERVER-1169
Please critique the formatting. The internal/external part is particularly bad
=> [SERVER-1169] details on how to configure an external vault instance

jekyll/_cci2/configuration-reference.md
This PR will add information around the `match` conditional logic. We don't automatically prefix match, so a full pattern needs to be provided.
We had a customer open a ticket on this situation and the docs could be a bit more clear on the subject.
=> Add clarification around prefix matching for conditional logic match

jekyll/_cci2/pipeline-variables.md
This PR will add a note about what occurs if an empty pipeline variable is passed into a variable set in the `environment` key. It also notes the proper way to get an empty string, which is to set it in a shell command.
This stemmed from a support case, the way to get this to work for `pipeline.git.tag` was to use the following:
```
- run:
name: Set tag variable
command: |
CIRCLECI_GIT_TAG=<< pipeline.git.tag >>
echo "export CIRCLECI_GIT_TAG=$CIRCLECI_GIT_TAG" >> $BASH_ENV
```
As not all builds will have `tag` set. This ensures the variable is set to an empty string instead of `<nil>` as it will execute while the job is running instead of being set at config compilation time.
=> Add note about nil values in environment key

jekyll/_cci2/server-3-install-prerequisites.adoc
The minimum requirements listed for a cluster were not sufficient for actually running a server installation
SERVER-1183
=> SERVER-1183: Update minimum cluster requirements

jekyll/_cci2/optimizations.md
Fixed broken anchors in links from Optimizations page.
The links work, but do not redirect to the specific location in the page, which a correct anchor should.
=> Fixed broken anchors in links from Optimizations page

jekyll/_cci2/circleci-images.md, jekyll/assets/css/main.scss
Updates to our convenience image document. This change reorganizes the order of paragraphs to first display next-gen convenience images  over legacy documentation.
=> Update circleci-images to better display next-gen images.

jekyll/_cci2/deploying-ios.md
Fixes #5380 
It looks like we may need to do a bit of a one over on the Fastlane content in our docs as things have changed from an authentication perspective. For the time being, I'm adding a section calling out some of the changes, as raised in the linked issue.
=> Add: notes on using new app store connect api vs 2fa.

jekyll/_cci2/language-guides.md, jekyll/_cci2_ja/language-guides.md
This PR removes two index pages that auto aggregate files categorized with "language-guides" in jekyll. Reason for removal:
-These pages often confuse users when they land on them.
- There are properly maintained pages located [here](https://circleci.com/docs/2.0/tutorials/)
=> Clean: remove unused language guide index pages.

jekyll/_cci2/configuration-reference.md
Fix wrong linked anchor for jobs in workflow
`jobs` in the top-level and `jobs` in a workflow has same anchor name, so confused these links.
=> Fix wrong linked anchor for jobs in workflow

jekyll/_cci2/deploying-ios.md
Description
Update the document to reflect the new method for authenticating with app store connect for deplyoment
Reasons
MacOS document improvements initiative
=> Add app store connect api key info to ios deployment guide

jekyll/_cci2/server-3-operator-user-accounts.adoc
This doesn't work for server 3.x
Removing the CLI instructions for user management
Just spotted this, this doesn't apply for server 3
=> Removing CLI instructions for user management

jekyll/_cci2/runner-installation.adoc
Add steps to the runner installation docs on how to configure an SELinux policy for runner on RHEL 8.
Runner on RHEL 8 requires an SELinux policy with certain permissions in order to launch and run jobs.
See: https://circleci.atlassian.net/browse/CIRCLE-35397
=> Update RHEL runner install docs with SELinux policy

jekyll/_cci2/oss.md
This updates the section about caching for OSS builds and tries to clarify it.
The symptom "the build is slow on the first PR commit because it does not seem to find the cache" is hard to google and it took me a while to find this part of the documentation.
In an ideal world there would be a from the main [cache doc page](https://circleci.com/docs/2.0/caching/#restoring-cache) to this caveat.
=> Clarify cache section for OSS

jekyll/_cci2/server-3-install-migration.adoc
When to upgrade postgres to 12 when migrating from 2.19 to 3.1.
Do it before the migration.  Reality check runs on 2.19 with postgres 12 so the risk is low.  Also requesting a backup be taken to further reduce risk.
https://circleci.atlassian.net/browse/SERVER-1274
Thanks @soulchips for doing all the work on this one!
=> [SERVER-1274] external datastores migration postgers update

jekyll/_cci2/server-3-whats-new.adoc
We fixed this issue just before we released so we can remove it from the known issues.
=> We fixed SSHing into the machine executor in 3.1

jekyll/_cci2_ja/configuration-reference.md
The configuration-reference page's layout is broken. This is caused by merging crowdin translations. 
I found some other small issues, so I manually fix some parts.
https://circleci.slack.com/archives/CJF173R4H/p1625729783019200
=> fix ja/2.0/configuration-reference 

jekyll/_cci2/configuration-reference.md
Add Ubuntu 20.04-based GPU machine image
Document the image
=> Update GPU machine image list

jekyll/_cci2/webhooks.md
- Adds documentation on new webhook functionality
- [Preview link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/feat-webhooks-preview/2.0/webhooks/)
Notes / Todo
=> Add: webhooks documentation

jekyll/_cci2/configuration-cookbook.md
This example uses `path-filtering/filter` as a reusable command, but it's only exposed as a job in the [path-filtering orb](https://circleci.com/developer/orbs/orb/circleci/path-filtering).
Also added line breaks to the example's comments to improve readability.
=> Fix to path-filtering cookbook example

jekyll/_cci2/orb-intro.md
This PR will adjust our language to note that private orbs are only available to paid plans listed on our plans page, as legacy plans, even if paid, do not currently have access.
This came about from a discussion with a customer, so updating to make sure it's clearer.
=> Update private orb access information

jekyll/_cci2/hello-world-windows.md
I think Scale plan customers can also use Windows based on our pricing page
=> potential mistake in who gets access to windows executors?

jekyll/_cci2/configuration-cookbook.md
Fix a sample config of the dynamic configuration, the current configuration is completely broken, so split the config to `config.yml` and `continue_config.yml`, and fix some small issues.
Also, add a note for the dynamic configuration. Currently, CircleCI doesn't allow to call the dynamic configuration feature more than once, and that's why I split the config.yml to `config.yml` and `continue_config.yml`.
This is an example of the failed build by using the dynamic configuration twice.
> https://app.circleci.com/pipelines/github/cheekit/circleci-setup-workflow/85/workflows/b724ba84-96e5-4852-b6fe-964cf23defde/jobs/78
CircleCI user pointed out about this issue.
=> Fix a sample config of the dynamic configuration

jekyll/_cci2/migrating-from-1-2.md, jekyll/_cci2/packagecloud.md
Use Ruby 2.7 image (buster) instead of 2.3 (jessie). cf. #5553 for ja docs.
Ruby 2.3 has reached EOL in 2018, so force users to use the stable. Ruby 3.0 has some incompatibility so using 2.7 instead.
=> Use Ruby 2.7 image (buster) instead of 2.3 (jessie)

jekyll/_cci2/adv-config.md, jekyll/_cci2/browser-testing.md, jekyll/_cci2/code-coverage.md, jekyll/_cci2/collect-test-data.md, jekyll/_cci2/config-intro.md, jekyll/_cci2/configuration-reference.md, jekyll/_cci2/docker-layer-caching.md, jekyll/_cci2/env-vars.md, jekyll/_cci2/examples-intro.md, jekyll/_cci2/executor-types.md, jekyll/_cci2/migrating-from-travis.md, jekyll/_cci2/optimizations.md, jekyll/_cci2/packagecloud.md, jekyll/_cci2/sample-config.md, jekyll/_cci2/triggers.md
Updates the versions of `circleci/node` image on Docker Hub, keeping the minor/revision specifications.
Node.js 4.x, 7.x, 8.x, 9.x, and 10.x got EOL'ed, so we need to use 14.x LTS or 16 stable. Also `jessie` reached EOL, so these should be updated to the latest `buster`. `stretch` is still stable, but these can be updated now.
=> Update circleci/node images to latest

jekyll/_cci2_ja/migrating-from-1-2.md, jekyll/_cci2_ja/packagecloud.md
Use Ruby 2.7 image (buster) instead of 2.3 (jessie) in ja docs. cf. #5552 for the original (en) docs.
Ruby 2.3 has reached EOL in 2018, so force users to use the stable. Ruby 3.0 has some incompatibility so using 2.7 instead.
=> Use Ruby 2.7 image (buster) instead of 2.3 (jessie) (ja)

jekyll/_cci2/server-3-install.adoc
If no VPC ID is given, AWS will use the default VPC. We cannot assume that the user is using the default VPC.
SERVER-1331
=> Add vpc ID for vm-service SG command

jekyll/_cci2/caching.md
Fixes a typo in caching.
`~.cache` is different from `~/.cache`.
=> Fix typo in caching

jekyll/_cci2/server-3-install.adoc
On Friday we realized these commands don't actually work as-is because of how a named security group can exist in multiple regions. Using the ID prevents any confusion or mistakes.
=> Update SG commands to use group-id instead of group-name

jekyll/_cci2/runner-overview.adoc
Jira: [CIRCLE-36399](https://circleci.atlassian.net/browse/CIRCLE-36399)
Updates the runner documents to show that RHEL, Docker, and Kubernetes are now out of preview and are supported.
This change affects the `Supported` and `Preview` sections listed [here](https://circleci.com/docs/2.0/runner-overview/#supported)
Screenshot of the change:
=> [CIRCLE-36399] Update runner docks for  RHEL, docker, and kubernetes to show supported status

jekyll/_cci2/server-3-operator-externalizing-services.adoc
This step no longer necessary
https://circleci.atlassian.net/browse/SERVER-1247
=> [SERVER-1247] remove setting up DB step for external postgres in server

jekyll/_cci2/code-coverage.md, jekyll/_cci2/language-go.md
Updates `circleci/golang` image to the latest stable. This PR does not intend to move forward with `cimg/go`, which can be done in another one.
Go 1.11 and 1.12 were EOL'ed years ago.
=> Update golang image to the latest

jekyll/_cci2/webhooks.md
Updating webhook docs to reflect a new change to the job-completed events.
I also need to document all the HTTP headers including how we sign payloads, but that will come in a separate PR.
=> Add started_at and stopped_at keys to job structure in webhooks

jekyll/_cci2/orb-author.md
This document outlines the process for creating an Orb with the development kit utilizing GitHub as your VCS. However, the kit also works with Bitbucket repos, so I added a note to clarify that it's possible.
This was brought to my attention from a ticket I was working on with a customer. While this note will help clarify the situation, as a bigger project, we may want to split this document into two sections. One outlining the process for GitHub and one outlining the process for Bitbucket.
=> Add note about orb kit working with Bitbucket

.circleci/config.yml
Our builds are failing based on a debian release change. The flag I am adding is described as such:
```
--allow-releaseinfo-change
Allow the update command to continue downloading data from a repository which changed its information of the release contained in the repository indicating e.g a new major release. APT will fail at the update command for such repositories until the change is confirmed to ensure the user is prepared for the change. See also apt-secure(8) for details on the concept and configuration.
Specialist options (--allow-releaseinfo-change-field) exist to allow changes only for certain fields like origin, label, codename, suite, version and defaultpin. See also apt_preferences(5). Configuration Item: Acquire::AllowReleaseInfoChange.
```
The error we are getting:
```
E: …
```
=> Fix: try using --allow-releaseinfo-change to build docs.

.circleci/config.yml
This PR is mainly to swap the Ruby image. The legacy image, which is currently used, is deprecated. This switches over to the next-gen Ruby image.
The orb is updated too because 1) why not and 2) we needed a newer version of the orb in order to use the next-gen image.
---
This will also fix an occasional issue with the `build` job which is failing [due to Debian 10](https://www.feliciano.tech/blog/debian-10-apt-fix/).
=> Update Ruby orb and use next-gen image

.circleci/config.yml
This PR is mainly to swap the Node.js image. The legacy image, which is currently used, is deprecated. This switches over to the next-gen Noide.js image.
The orb is updated too because 1) why not and 2) we needed a newer version of the orb in order to use the next-gen image.
One thing to pay attention to here, this updates the Node.js version by a lot. From v8 all the way to v14. The pipeline passed successfully so that's good but we'll want to make sure there isn't any other unintended changes.
=> Update Node.js orb and use next-gen image

.circleci/config.yml
The [reindex-search job failed](https://app.circleci.com/pipelines/github/circleci/circleci-docs/30936/workflows/1bfe5d5d-b4f6-4f53-892f-ebdcc05c2e77/jobs/87463) after the Ruby changes. The next-gen Ruby image doesn't have cmake installed so we need to install it manually.
I didn't catch this in the other PR because the `reindex-search` job doesn't run for PRs.
=> Fix Ruby dev step

jekyll/_cci2/server-3-install.adoc
Apostrophes are an invalid character for descriptions. The command will fail if an apostrophe is present.
=> [No Jira] Apostrophes are an invalid character for descriptions

jekyll/_cci2/server-3-install.adoc
We're improving the section on preflight checks to make it a bit more obvious on what the checks are.
Currently, the section on preflight checks is a bit hidden, appearing to be a part of the nomad MTLS section. This change clearly separated the preflight checks as another step and what to expect from this step
=> Server 1256

jekyll/_cci2/next-gen-migration-guide.md
As we deprecate the legacy Convenience Images, I've made a migration guide to help get people over to the next-gen images. I started the Markdown file by copying another doc page and then just enter my content.
Can someone from the @circleci/docs-disco help me massage this into a real, proper doc?
=> Add next-gen Conv img migration doc

jekyll/_cci2/parallelism-faster-jobs.md
Current command could remove unwanted characters
`/.py/` is not precise enough (files that contain a letter followed by `py`). It might match parts of a dir name + `.` is a catch all etc. Changed to `/\.py$/` (files that end with `.py`)
https://circleci.com/docs/2.0/parallelism-faster-jobs/#using-test-splitting-with-python-django-tests
=> Fix regexp to list test packages in parallel tests tutorial.

jekyll/_cci2/webhooks.md
We truncate commit subjects and bodies to prevent unboundedly-large
event payloads.
https://circleci.atlassian.net/browse/CIRCLE-34613
=> [CIRCLE-34613] Doc trunc of webhook commit info

jekyll/_cci2/dynamic-config.md
This PR will add a note to the documentation that without adding `setup: true` to your config.yml that your CircleCI pipelines will continue to operate as normal.
We had a customer who had some concerns over enabling this feature and it causing issues with their existing setup. I can understand the concern there so this update is to ensure customers know that just enabling the feature doesn't do anything out of the box. It only comes into play after you add in `setup: true` to your config.
=> Add note about needing setup key of true for dynamic configs to start

Gemfile, Gemfile.lock, docker-compose.yml, jekyll/_config.yml, jekyll/_includes/js-assets.html, jekyll/_includes/mobile-sidebar.html, jekyll/_includes/sidebar.html, jekyll/assets/js/main.js
- Replace `jekyll-assets` to `jekyll-minibundle` 
- Use  `JEKYLL_MINIBUNDLE_MODE` env variable to disable asset fingerprinting in dev
With https://github.com/circleci/circleci-docs/pull/5601 landing, developers working on that repo are pretty much required to use Docker if they want to mimic a true-to-life experience (e.g. being able to call the circleci API) and jekyll being pretty slow to build, sometimes up to 10 minutes, we needed to make the developer experience a little better. With the help of the `--incremental` jekyll [option](https://jekyllrb.com/docs/configuration/incremental-regeneration/), we are able to only regenerate the content that changes and thus shorting the wait time. 
Something I discovered while working on this PR is that our `jekyll-assets` plugin was not …
=> Use jekyll-minibundle in place of jekyll-assets to solve docker issues while editing files

jekyll/_cci2/webhooks.md
This PR will add a note to the documentation noting we limit the number of webhooks to 5 per project.
We present this information/error when trying to add more than 5, but we didn't have it noted in the documentation. This PR will add that information to the docs.
=> Add note about 5 webhook limit per project

jekyll/_layouts/classic-docs.html, jekyll/assets/css/main.scss
Ticket: [WEB-390](https://circleci.atlassian.net/browse/WEB-390)
Currently, if you click a link with child elements inside (like svg/span/img/etc), the child element triggers the click and become the target element causing our analytics tracking code to skip it over. 
- Used CSS to make the child elements inside an `a` tag have no pointer events so they stop registering as the target element in event listeners.
=> [WEB-390] Allow recursive event tracking when `a` tag includes another element

jekyll/_cci2/runner-installation.adoc, jekyll/_cci2/runner-overview.adoc
Adds documentation for enabling rerun with SSH on runner.
JIRA: [CIRCLE-36663](https://circleci.atlassian.net/browse/CIRCLE-36663)
=> [CIRCLE-36663] Add documentation for enabling rerun with SSH on runner

jekyll/_cci2/webhooks.md
While preparing https://github.com/circleci/circleci-docs/pull/5652, I noticed a discrepancy between our webhook docs and reality: the `pipeline.trigger.actor.id` nested field is never populated.
This was proposed as part of the alpha implementation, but never implemented. I'd like to remove this field for clarity until we properly add that in.
=> Remove "actor" field from webhook trigger object

src-js/optimizelyClient.js
- Transform the way to get `userId` so it doesn't have to wait on the `userDataReady` if the data is already there
While pairing with @ccgeller we realized that `getVariationName()` was acting strange and will not always resolve. The reason why was based on pure timing between the time the API is called and the `userDataReady` event was registered. This PR fixes that by first checking if `userData` is already present, if not it will wait on the event to resolve.
=> Fix OptimizelyClient.getVariationName() so it doesn't always have to wait on userData

jekyll/_cci2/webhooks.md
Since webhook "test pings" are a subset of the data that an actual webhook will receive, we need a full example payload somewhere for developers to use for testing & debugging. I'm adding two sample payloads at the end of the webhooks document.
=> [CIRCLE-37451] Add example payload for workflow-completed and job-completed webhooks

jekyll/_includes/head.html, jekyll/_includes/js-assets.html, jekyll/assets/css/main.scss, jekyll/assets/js/highlightJSBadge.js, package-lock.json, package.json, src-js/app.js
**Ticket:** [CIRCLE-36533](https://circleci.atlassian.net/browse/CIRCLE-36533)
Changes
=======
Paired with @tshen815 
- Add in `highlightJS-badge` npm package
- Add in optimizely logic to change between treatment vs control on Copy code button
Rationale
=========
Based on the [spike](https://circleci.atlassian.net/wiki/spaces/GD/pages/6227427500/CIRCLE-36042+Copy+code+button+for+Docs+DevHub) Nav Ramabadran and the work Chantelle Gellert started with [CIRCLE-36634: Experiment - Add copy code button to devhubDEV](https://circleci.atlassian.net/browse/CIRCLE-36634) we want to make an experiment that brings the copy code button everywhere on the Doc site. For example here is a page where it’s missing: [Hello World - CircleCI ](https://circleci.com/docs/2.0/hello-world/)
Screenshots …
=> [CIRCLE-36533] Add copy code button docs

jekyll/_cci2/arm-resources.md, jekyll/_cci2/executor-intro.md
Server 3.2 will support Arm executors. This work updates the Arm resources docs to call out the differences on server and note that server 3 is supported
[SERVER-1250](https://circleci.atlassian.net/browse/SERVER-1250)
=> SERVER-1250 | Document Arm executors for Server 3

jekyll/_data/sidenav.yml, jekyll/_includes/mobile-sidebar.html, jekyll/_includes/sidebar.html, jekyll/assets/js/sidebar.js
- Remove the use of the URL parameter `?section=` and instead used the `data-section` attribute
- Remove the use of localstorage and use `data-section` attached to the `active` item to know which section to open
- Apply `slugify` to both `current_url` and `item_link` when comparing them to prevent mismatch when trailing slash is not present
[CIRCLE-36338](
https://circleci.atlassian.net/browse/CIRCLE-36338)
This PR improves the way both sidebars work by removing some logic around local storage and by doing a slug comparison (see Description) to prevent a mismatch of URLs. Currently, if you open this [URL](https://circleci.com/docs/2.0/server-3-install-migration/) in a private tab with 0 local storage (to simulate a brand new visitor) the section will not automatically open. 
This is …
=> [CIRCLE-36338] Fix navbar active items 

docker-compose.yml, jekyll/_cci2/env-vars.md, jekyll/assets/css/main.scss, scripts/docker_command.sh
The table of environment variable was wrapping them. This change adds a
new CSS class for environment variables that can be used to prevent
wrapping.
I also needed to fix the docker-compose setup to get it working locally.
=> Add a class for env vars to prevent wrapping

jekyll/_cci2/configuration-cookbook.md
Closes #5611 
I've updated the example to one that actually works. The Node.js orb doesn't support Windows so it shouldn't have been in the example.
I've verified that this example config runs: https://app.circleci.com/pipelines/github/felicianotech/cci-testing-pub/544/workflows/6836fa45-e9f5-4795-8ca6-94886906e174
=> Update OS matrix example

jekyll/_cci2/server-3-install.adoc
https://circleci.atlassian.net/browse/SERVER-1385
Remove Nomad setup example and instead point to server terraform readmes that show the official example and explain all the required and optional parameters.
=> clear up nomad client setup and remove duplication

jekyll/_archive/ios-builds-on-os-x.md, jekyll/_archive/shipio-to-circleci-migration.md, jekyll/_cci1/ios-builds-on-os-x.md, jekyll/_cci1/shipio-to-circleci-migration.md, jekyll/_cci2/faq.md, jekyll/_cci2/jenkins-converter.md, jekyll/_cci2/language-clojure.md, jekyll/_cci2/language-go.md, jekyll/_cci2/language-java.md, jekyll/_cci2/language-php.md, jekyll/_cci2/language-ruby.md, jekyll/_cci2/migrating-from-github.adoc, jekyll/_cci2/projects.md, jekyll/_cci2_ja/env-vars.md, jekyll/_cci2_ja/faq.md, jekyll/_cci2_ja/jenkins-converter.md, jekyll/_cci2_ja/language-clojure.md, jekyll/_cci2_ja/language-go.md, jekyll/_cci2_ja/language-java-maven.md, jekyll/_cci2_ja/language-java.md, jekyll/_cci2_ja/language-javascript.md, jekyll/_cci2_ja/language-php.md, jekyll/_cci2_ja/language-ruby.md, jekyll/_cci2_ja/local-cli-getting-started.md, jekyll/_cci2_ja/migrating-from-github.adoc, jekyll/_cci2_ja/projects.md
=> [WIP] SEO audit link fixing

jekyll/_cci2/testing-ios.md
These images have been removed from CircleCI so need to be removed for our docs
=> Update table to remove deprecated Xcode versions

jekyll/_cci2/server-3-install.adoc
Leaving a note that scaling Traefik replicas will break LetsEncrypt support.
https://github.com/circleci/server/pull/2380#discussion_r708376116
https://circleci.atlassian.net/browse/SERVER-1412
=> LetsEncrypt is only supported with 1 Traefik replica

jekyll/_cci2/orbs-faq.md, jekyll/_cci2_ja/orbs-faq.md
Added some extra clarification around what certified orbs are. 
Received a customer question about what kind of security testing (if any) uncertified orbs receive, which then prompted the question around what is considered an uncertified/certified orb.
=> Added clarification around the definition of certified orbs

jekyll/_cci2/index.md, jekyll/assets/css/main.scss, jekyll/index.html, src-js/addOrbSection.js, src-js/app.js
**Ticket**: [CIRCLE-37763](https://circleci.atlassian.net/browse/CIRCLE-37771)
- hide `Orbs`, `Using Orbs`, and `Creating Orbs` links from other sections when in control 
- add in section for orbs with associated links for docs and docs 2.0
- add `id` and `class` attributes to display specific links and sections for treatment and control variations
- add `window.AnalyticsClient.trackAction` for each link in orbs section
In an effort to try and help surface the orbs feature more and building engagement to developer resources, we decided that it would be helpful to include a section for orbs on the landing page of Docs with the appropriate links. 
Current links and copy is still a WIP. Some possible link candidates could be [Orbs Intro](https://circleci.com/docs/2.0/orb-intro/), [Orbs …
=> [CIRCLE-37763]: Include a section for Orbs on the landing page of Docs

jekyll/_cci2/workflows.md
This PR will update our documentation to match the current time limits for approval jobs.
This stemmed from a conversation with a customer, and testing/working with engineering confirmed these time limits.
=> Adjust known time limits on approval jobs

jekyll/_cci2/getting-started.md, jekyll/_cci2/hello-world.md, jekyll/_cci2/project-build.md, jekyll/_cci2/workflows.md, jekyll/_cci2_ja/getting-started.md, jekyll/_cci2_ja/hello-world.md, jekyll/_cci2_ja/project-build.md, jekyll/_cci2_ja/workflows.md
Tabbed content was created to show difference between v2.19.x and Cloud but they were just labelled "Server". Now Server 3 is close to parity with Cloud we need to update the tab labels to be more specific :-)
https://circleci.atlassian.net/browse/DOCS-9?atlOrigin=eyJpIjoiOGQxNDhkNWI2ZDI2NDRjOGFiZDI0NzM3MjhmODc5NTEiLCJwIjoiaiJ9
=> all tabbed content to ref server v2.19

jekyll/_cci2/collect-test-data.md, jekyll/_cci2/configuration-reference.md
* the new UI does not use the directory name of the test results anymore
* we recently changed it so that you can supply the location of a specific test
file (since doing this was a very common error that delayed people seeing test
results on their builds)
=> Update store_test_results step documentation

jekyll/_cci2/testing-ios.md
No changes to Xcode this time as the same RC build (13A233) is now marked as a release version by Apple, therefore updating the docs appropriately
=> Update 13 RC to 13

jekyll/_cci2/security.md
The new Scheduled Pipelines feature will emit new events to the `audit-log-service`.
These new events are added to the public docs via this PR.
See above
Upstream PR in `audit-log-service`:
https://github.com/circleci/audit-log-service/pull/177
=> Add audit log events for schedules

jekyll/_cci2/runner-installation.adoc
Jira: [CIRCLE-37827](https://circleci.atlassian.net/browse/CIRCLE-37827)
Adds documentation info for `runner.mode`
This is already enabled and being used for Windows runner installs. Making this public for other use cases as well (docker, runner auto scaling)
Screenshot:
=> [CIRCLE-37827] Add documentation for `runner.mode`

jekyll/_cci2/runner-installation.adoc
Add documentation for the optional runner parameter, `runner.idle_timeout`. This parameter will cause the polling loop in the launch agent to terminate if no tasks are claimed within the timeout period. This will help to support autoscaling in the event that too many runners are scaled up.
Jira ticket: https://circleci.atlassian.net/browse/RT-100 (https://circleci.atlassian.net/browse/CIRCLE-36413)
=> Document `runner.idle_timeout` parameter [RT-100]

jekyll/_cci2/server-3-install.adoc, jekyll/_cci2/server-3-operator-vm-service.adoc
VM service accepts more than one subnet now in AWS. Modified docs to note this and added the limitation that they must be in the same AZ.
SERVER-1426
=> SERVER-1426 |  VM service can accept more than on subnet

jekyll/_cci2/creating-orbs.md
Added further instruction to confirm the `[semver:<increment>]` is in the subject/first line of the commit message before trying to merge. 
Closes #5722 
The orb tool checks the subject/first line of the commit message, but Bitbucket seems to preserve the PR title in the body of the commit rather than the subject, causing the process to fail.
=> Instruction to confirm semvar in subject of commit

.circleci/config.yml, src-js/experiments/forceAll.js, src-js/optimizely.js
- Add a `force-all` query key to enable all experiments by default
We have a preview system but when sharing these links with stakeholders the experiments are not able to resolve. This URL query key helps short-circuiting the optimizely client
=> Add URL query key to enable experiments

jekyll/_cci2/hello-world-windows.md
I think the example config connecting to this change is for Server (i.e., where `version: 2.0`) and so this is a fix on a minor typo.
Ref: https://circleci.com/docs/2.0/hello-world-windows/
=> Update tag from Cloud to Server

jekyll/_cci2/testing-ios.md
Improve commands for switching Rubies in 11.7+
The current suggestion is to append the new version to the end of the bash profile, however this causes at least two switches to Ruby when the profile is sourced and can lead to some odd behaviour in certain circumstances.
This method replaces the existing line in the bash profile with the new chruby command required
=> Improve commands for switching Rubies in 11.7+

jekyll/_cci2/orb-author-faq.md
Remove reference to `orb info` not working with Private Orbs.
Closes #5866 .
This command is now available for Private Orbs.
=> orb info is now available for Private Orbs

jekyll/_cci2/circleci-images.md
Remove links to the legacy `Dockerfile`s from [/docs/2.0/circleci-images/](https://circleci.com/docs/2.0/circleci-images/).
https://github.com/CircleCI-Public/circleci-dockerfiles was archived in 2021-04 and there is no replacement for it in public repos the CircleCI users can access.
=> Remove links to the legacy Dockerfiles from circleci-images

jekyll/_cci2/certificates.adoc
Fix a typo in "[Setting Up Certificates](https://circleci.com/docs/2.0/certificates/#adding-the-certificate-to-circleci-server)".
=> Fix typo in "Setting Up Certificates"

.circleci/config.yml
Ticket: [CIRCLE-38726](https://circleci.atlassian.net/browse/CIRCLE-38726)
- Replace the old scheduled trigger with the new Scheduled pipeline
The pipeline team has asked us to migrate to this new way of handling scheduled workflow. You can see the process in [their documentation](https://circleci.atlassian.net/wiki/spaces/CD/pages/6301483319/Schedule+Pipelines+Migration).
Here's the curl command to check the schedule pipeline: 
```
❯ curl --location --request GET 'https://circleci.com/api/v2/project/github/circleci/circleci-docs/schedule' \
--header 'circle-token: <your token>'
[ {
"description" : "Nightly build for running build/maintenance tasks such as pulling in docker image tags or automating our api documentation",
"name" : "nightly-build",
"id" : "<redacted>",
"project_slug" : …
```
=> [CIRCLE-38726] Migrate Scheduled Workflows to Scheduled Pipelines

webpack.config.js
Ticket: [CIRCLE-38589](https://circleci.atlassian.net/browse/CIRCLE-38589)
- Use `ignoreWarnings` config key to tell webpack to ignore this specific warning
Some of our legacy code that is imported in `app.js` are not modules and so we want to silence that warning until we eventually refactor that code.
=> [CIRCLE-38589] Ignore default export warnings for `app.js`

jekyll/_cci2/env-vars.md
Added a definition for the `CIRCLE_WORKFLOW_WORKSPACE_ID` environment variable
We received a customer inquiry about `CIRCLE_WORKFLOW_WORKSPACE_ID` and they asked why we don't have any documentation on it, so this definition was added.
=> Updated docs for CIRCLE_WORKFLOW_WORKSPACE_ID

jekyll/_cci2/configuration-reference.md
Taking the `name` key out of the same table as the `require` key because it is its own valid key and needs its own space.
The `name` key was likely accidentally merged with the `require` key, but it needs its own definition and table.
=> [WIP] Separate out name key from require key

jekyll/_includes/youtube-grid.html, jekyll/assets/css/main.scss, src-js/experiments/videoTutorials.js
Ticket: https://circleci.atlassian.net/browse/CIRCLE-38203
- Add video `title` metadata to `docs-video-tutorials-video-clicked` event
- Add video `element` metadata to `docs-video-tutorials-video-clicked` event
- Fix anchor element underline when link is visited
We want to add more metadata to the `docs-video-tutorials-video-clicked` event so we can more accurately tell which video was clicked and from where it was clicked:
=> [CIRCLE-38203] Add metadata to video experiment analytics

src-js/site/main.js
**Ticket:** [CIRCLE-38683](https://circleci.atlassian.net/browse/CIRCLE-38683)
- add new `section` property to `trackAction` for  tracking analytics to know explicitly 
- Adding new metadata property to our tracking analytics in amplitude for the share section button to explicitly know which sections users are sharing so we can prioritize those to update and kept up to date.
=> [CIRCLE-38683]: Add Property to Amplitude event to see what sections are being shared

jekyll/_cci2/circleci-images.md
Removes Docker image tag list from circleci-images.
Closes #5535
=> Remove Docker image tag list from circleci-images

src-js/experiments/highlightJSBadge.js
**Ticket:** [CIRCLE-38681](https://circleci.atlassian.net/browse/CIRCLE-38681)
- add `codeSnippetPosition` property as `trackAction` metadata 
- we want to add more metadata to our tracking analytics, in this case to let use know explicitly what code snippets are being copied so that we may better prioritize them for updates and upkeep
=> [CIRCLE-38681]: Add property to Amplitude event to see which snippets are copied (Docs)

jekyll/_cci2/orb-author-intro.md, jekyll/_cci2/orb-author.md
There was some confusion around personal and "normal" orgs within CircleCI. This hopefully clarifies the terminology we use, especially around orbs.
=> Clarify 'personal org' concept.

jekyll/_cci2/runner-installation-linux.adoc
Remove specifying a UID (i.e., 1500) for the `circleci` user in the runner installation docs for Linux.
`adduser` will default to the next available UID defined by the range in `/etc/adduser.conf`, and specifying an arbitrary UID could have a conflict if it's already in use. The `launch-agent` and `task-agent` also don't care about the UID.
Jira: https://circleci.atlassian.net/browse/RT-151?focusedCommentId=165890
Some discussion around the UID for the `circleci` user in the launch agent Docker image: https://github.com/CircleCI-Public/circleci-runner-docker/pull/13#discussion_r741754265
=> Don't specify a UID for the `circleci` user on Linux runner [RT-151]

jekyll/_cci2/configuration-reference.md
Adds a new available CUDA image to the list.
=> Images: add Linux CUDA 11.4 image to 'available list'

jekyll/_cci2/gh-bb-integration.md
Further clarification of instructions for both non-admin and admin users to authorize GitHub organizations to CircleCI.
Further clarification was needed for these instructions as the whole process wasn't documented.
[Jira Ticket](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-43)
=> Add instructions for non-admin and admin requests

docker-compose.yml, package.json
- Use `container_name` in `docker-compose.yml` to force  containers name.
A bit of a TIL for me but @devinmarieb @ccgeller and I realized that default docker containers might not have a consistent name across machines until you expressively name them. This resulted in breaking the `yarn clean` command because it was expecting a specific name.
=> Make container names consistent across machines

jekyll/_config.yml
Ticket: [CIRCLE-38657](https://circleci.atlassian.net/jira/software/c/projects/CIRCLE/boards/376?modal=detail&selectedIssue=CIRCLE-38657)
Reviewed with @rosieyohannan 
- Changed 'jekyll/_config.yml' file to go form H1 to H6. Jekyll-toc docs found [here](https://github.com/toshimaru/jekyll-toc)
- Missing tags are a result of specified command `{:.no_toc}` any tags hidden by the command must be manually 
- trying to drive engagement for the content we currently have in docs 
- improving the overall experience for users by giving them an easier time to find what they need
Based on a discussion with Rosie, there are lower level sub headings that we should add to the side nav in the Config Reference page in addition to the current h2 - h4 tags that are there. 
As the Config Reference page is …
=> [CIRCLE-38657] Adding H5 and H6 Headings to Side Nav in Docs

scripts/datadog-synthetics-ci.sh
Forked PRs are failing on the new Datadog Synthetics CI step because the key is not available to forks.
Example: https://app.circleci.com/pipelines/github/circleci/circleci-docs/33379/workflows/d4e67abe-b00a-46be-b811-4ff2ba826833/jobs/95984
This exits with status code 0 if there is no such key.
We want to allow for open contributions.
=> Fixes forked repo PRs with missing Datadog keys

src/js/services/analytics.js
I needed to prepend the class the static method is called from.
=> Fix: getSessionId not defined - now defined.

jekyll/_cci2/configuration-reference.md
- Add a note in the config ref about `save_cache paths` not supporting wildcards. 
- Add example of a workaround that is appropriate in some instances. 
[Jira Ticket](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-35)
This is a feature most developers would just expect to be supported. It's a popular feature request on the Ideas board, so we wanted to note that it is not currently supported and to point users to vote on the feature if it's crucial to their workflow.
=> Add note about wildcards in save_cache paths

jekyll/_includes/head.html
Ticket: [WEB-549](https://circleci.atlassian.net/browse/WEB-549)
- Add `hreflang` tags in the `head.html` include so they are are used across all pages
If you have multiple versions of a page for different languages or regions, telling Google about these different variations is highly recommended. Doing so will help Google Search point users to the most appropriate version of our page depending on the language or region. More info: https://developers.google.com/search/docs/advanced/crawling/localized-versions
On an `en` page:
Same page but for `ja`:
=> [WEB-549] Add alternate hreflang to all pages

jekyll/_cci2/faq.md
A slightly shorter version of the added changes to the Persisting Data page about how to calculate monthly billing. 
There is a billing section in the FAQ page, so it make sense to include it here as well.
=> Add altered version of billing to faq page

src/js/experiments/DevHubDocsNav.js, src/js/experiments/highlightJSBadge.js, src/js/experiments/relatedResources.js, src/js/experiments/surfaceFullExampleConfig.js, src/js/experiments/videoTutorials.js, src/js/services/optimizely.js
- Change `getVariationName()` definition to require a `experimentContainer` attribute
- Return early when tracking `Experiment Viewed` if the `experimentContainer` is not in the DOM
- Update all experiments to provide an `experimentContainer` attribute
We realized that we track an experiment as viewed as soon as we get a resolution from optimizely (`control` or `treatment`). This works well for experiments that are globally seen across the entire site (like the `Doc/DevHub merge` exp) but produces bogus results for experiments that are only focusing on a subset of pages (like the `Recomended Resources` exp).
By providing an `experimentContainer` we can make sure that the experiment is in the DOM before tracking a view.
=> Fix: Add a `experimentContainer` to accurately track `Experiment Viewed` events

src/js/services/optimizely.js
- Bring back parameters in order of how they are supposed to be called
Parameters bacame out of order after a quick refactor and so the `experimentContainer` was using the `experimentId` and the `experimentId` was using the `experimentContainer` 😬
=> Fix: argument order for trackExperimentViewed

jekyll/_cci2/pipeline-variables.md
This PR simply adds a few links to examples and detailed documentation where they are referenced, so users can get a complete picture of how to use pipeline variables. I also de-duplicated a bit of the truthy/falsy explanation since it's more thoroughly covered in the linked-to section.
It's difficult to find the reference documentation for `when`/`unless` clauses and logic statements/expressions when you're digging through the documentation. If you are immensely familiar with the documentation, you know to look in the configuration reference page for this information, but users don't have that knowledge.
=> Help users find examples by linking to them from where they are referenced

.circleci/config.yml
Previously, the server PDF build script: /scripts/build_pdfs_asciidoc.sh was run for any branch starting with `server/*`. This needs to change to `*/server` so that we can start branch names with the jira ticket reference. 
I am not sure I've done it right though! 😬
=> redefine on which branches server PDFs are built

jekyll/_cci2/runner-installation-docker.adoc
A change to the runner docker image requires sudo to be used for some commands that require admin privileges. This change updates our extension docs to note that. 
Keep docs up to date with the current state of the runner docker image.
=> update runner image extension docs to use sudo

src/styles/_global-nav.scss
Ticket: [WEB-374](https://circleci.atlassian.net/browse/WEB-372)
[Preview link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/WEB-374-update-cta-button-in-docs-preview/?force-all)
Update the ‘Sign up / Go To Application' CTA button per the latest designs here: WEB-373: Buttons: primary, alternate, secondary color changeNEW 
The entire /assets/css/buttons.css can probably be removed, with fresh styles placed in the jekyll/_sass/_global-nav.scss file.
- Remove `assets/css/buttons.css`
- Update colour hex codes
To keep styles consistent throughout all applications.
=> [WEB-374] Update CTA Button in Docs Navbar per Latest Designs

jekyll/_cci2/runner-on-kubernetes.adoc
updating runner k8 installation to reference circleci-runner-k8
circleci-runner-k8 readme was updated to include additional configuration options, updating the docs here to reference circleci-runner-k8 readme to ensure the latest options are shown
https://circleci.atlassian.net/browse/RT-210
=> updating runner k8 docs to reference circleci-runner-k8 readme [RT-210]

src/styles/_sidebar.scss
Jira ticket: [DD-6](https://circleci.atlassian.net/browse/DD-6)
Preview [link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-6-max-width-side-nav-preview/?force-all)
Devin Beliveau Reported an issue in slack about the nav width not having a max in circleci-docs https://circleci.slack.com/archives/C021NCSEM44/p1637336044022100
This will cause issues for titles that are very long.
Example page where it fails
https://circleci.com/docs/2.0/runner-upgrading-on-server/
#After
554384d.png">
=> [DD-6] Overflow issue on side nav

src/js/app.js, src/js/experiments/index.js, src/js/services/analytics.test.js, src/js/services/index.js, src/js/site/index.js
Preview: [link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/rs/fix/remove-globing-to-avoid-tests-in-bundle-preview/?force-all)
- Use an `import/export` pattern in each directory to precisely bring in the build what is needed 
While working on [DD-181](https://circleci.atlassian.net/browse/DD-181), @teesloane and I realized that with the current setup, tests were spilling into the bundle and were creating problems in production. This PR ensures that only the files we actually need make it to the bundle.
Please thoroughly test the [preview build](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/rs/fix/remove-globing-to-avoid-tests-in-bundle-preview/?force-all) as we changed the way everything is imported. Thank you 🙏
=> Fix: remove globing to prevent tests from spilling into the app.bundle.js

src/js/experiments/index.js
- Fix wrong import name for `highlightJSBadge`
PR https://github.com/circleci/circleci-docs/pull/5966 broke the copy code button because of a wrong import name. This PR fixes that.
=> Fix: wrong import name for highlightJSBadge

jekyll/_cci2_ja/collect-test-data.md
- remove the unwanted extra ` ```yaml` code block
While looking at some doc, I stumbled upon this sentence that was repeated twice by mistake:
```
yaml
A working `.circleci/config.yml` section might look like this:
```
https://circleci.com/docs/ja/2.0/collect-test-data/#trx2junit-for-visual-studio-net-core-tests
=> Fix: Remove repeated code block in `_cci2_ja/collect-test-data.md`

jekyll/_cci2/jenkins-converter.md, jekyll/_cci2_ja/jenkins-converter.md
Ticket: [WEB-555](https://circleci.atlassian.net/browse/WEB-555)
- Add `sitemap: false` to the two JC pages 
The two pages are already in `noindex` for robots and so they need to be removed from the `sitemap.xml`
before:
after:
=> [WEB-555] Remove jenkins-converter pages from sitemap.xml

src/styles/main.scss
Ticket: [DD-256](https://circleci.atlassian.net/browse/DD-256)
- Add a `min-height` to the main content to ensure it always fills the available space and doesn't show background from the sidebar
When content is too short, a grey box is shown at the end because the content is not filling up the whole available space. This PR adds a `min-height: calc(100vh - header size)` to fix that. Depending on your monitor size, you can experience the issue for yourself here: https://circleci.com/docs/2.0/server-3-faq/
=> [DD-256] Make sure content always fills available space

src/js/site/user.js
- Change `cci-customer` expiration from 10 years to 1 year
Cookies lifetime were not GDPR compliant
=> Fix: Change `cci-customer` expiration from 10 years to 1 year

src/js/site/user.js, src/js/utils.js
**Ticket:** [WEB-610](https://circleci.atlassian.net/browse/WEB-610)
NOTE: I was unable to test this locally, due to a problem installing the `liquid-c` gem I was unable to resolve in reasonable time. Someone should give this a try in a dev or staging environment before merging.
The goal of this ticket is to reduce our long (10-year) expirations on various cookies to 2 years. This commit changes the expiry that we write when creating cookies.
In addition, since cookie setting is conditional, we can't count on those being re-created with the current expiry date on each visit. So we add and call a function to update the expiration date on an existing cookie (but won't set the cookie if it doesn't already exist).
See also: [WEB-611]
There are two paths to test:
A pre-existing cookie has its …
=> [WEB-610] Update long cookie expirations

jekyll/_cci2/parallelism-faster-jobs.md
A new flag was implemented and this PR will update the docs to have information about it, and how to use it.
This was recently implemented and we want it documented so customers can start to use the new flag.
=> Add time-default flag to test split documentation

jekyll/_cci2/server-3-install-prerequisites.adoc
We found a problem with k8s 1.21 in server 3.2.1. We're going to fix this in 3.2.2.
=> Server 3.2.1 supports k8s < 1.21

jekyll/_cci2/ip-ranges.md
We use A records to share IP ranges with our customers, but they were shared using a service which converts DNS to JSON. This was down for several hours last night promting customer complaints that were outside of our control.
We should remove the third party service and share the A records directly with the customer, making sure they know that they can use whatever tool they want to retrieve them, but including an example.
* [Slack thread](https://circleci.slack.com/archives/C028JJL4AMN/p1638471095021200)
=> Remove broken third party service from IP ranges docs

jekyll/_cci2/private-images.adoc
I have updated our https://circleci.com/docs/2.0/private-images/ page to include notes on how to use personal access tokens in-place of passwords from Docker Hub.
Based on a customer's feedback, and having resolved their issue around how to use personal access tokens from Docker Hub, I am updating our docs to make it easier for others in the future.
=> docs: add notes on using personal access tokens from Docker Hub

jekyll/_cci2/pipeline-variables.md
Add the new pipeline values related scheduled pipelines to the public docs
As the scheduled pipelines feature went into GA, the customers should know that there're new pipeline values that are available to use in the config when it's a scheduled pipeline
=> Add schedule related pipeline values

jest/global.js, src/js/services/analytics.test.js, src/js/site/user.js, src/js/site/user.test.js
This story is for adding unit tests for site/user.js as it is a critical part of our experiment resolving process.
If you are looking for guidance, we already have some tests in the js/ repository:
[utils.test.js](https://github.com/circleci/circleci-docs/blob/master/src/js/utils.test.js)
[analytics.test.js](https://github.com/circleci/circleci-docs/blob/master/src/js/services/analytics.test.js)
[rum.test.js](https://github.com/circleci/circleci-docs/blob/master/src/js/services/rum.test.js)
Unit tests help make sure we are not breaking anything critical, especially when it comes to how we resolve experiments (userId is used by optimizely)
Critical aspects of the site/user.js file are thoroughly tested. This includes:
- setUserData
- setLoggedIn
- setLoggedOut
- setAmplitudeId
- Mocking …
=> [DD-69] user.js unit test

jekyll/_cci2/runner-api.adoc
Update example API response
The example API response for the `/api/v2/runner/tasks/running` request was malformed. Updated to make this more accurate.
=> update running runner tasks API response code snippet

jekyll/_cci2/building-docker-images.md
This was available as of a couple of weeks ago. The version is all scaled up now and available.
=> Add new remote Docker version

jekyll/_cci2/hello-world-macos.md
Updated the example macOS config to point to a newer Xcode image.
Since many customers look at our docs when getting started (and often copy the examples directly), we want to encourage them to use the latest images.
=> Update to newer Xcode image in macOS example config

jekyll/_cci2_ja/server-3-operator-backup-and-restore.adoc
Fixed wrong format of link anchor in AsciiDoc.
In addition, remove unnecessary sentence that was inserted in during translation.
Incorrectly formatted anchors are causing errors in `yarn start`
=> fix link anchor typo

jekyll/_cci2/docker-to-machine.md
=> Typo fix on executor migration page

jekyll/_cci2/orb-author-faq.md
Fixing a typo on the page
For grammatical correctness
=> fix: typo "or example" vs "for example"

src/styles/_global-nav.scss
**Ticket:** [DD-277](https://circleci.atlassian.net/browse/DD-277)
- Removed divider line in header
- fixed margin between outer link and button to match what we have in outer
Remove the line next to CircleCI in the header of the docs to be consistent with the circelCI.com website to provide a consistent UI experience for the users
=> [DD-277]: Header - Remove the Line next to CircleCI - Docs

jekyll/_cci2/runner-installation.adoc
When a server administrator installs runners they need to have the CircleCI CLI configured with their server API key.
=> add notes round CLI config for runner on server

jekyll/_cci2/testing-ios.md
No change in build number for the release version of Xcode 13.2, therefore we do not need to re-build this image. Updating docs accordingly
=> Update Xcode 13.2 RC to Release

jekyll/_cci2/scheduled-pipelines.md
Scheduled pipelines are not yet available in Server 3.x and will not be available until 3.4. This needs to be accurately reflected in our Docs page.
Received a question from a customer about Scheduled Pipelines not being available in their installation. They noticed that the feature is being [listed as available in Server 3](https://circleci.com/docs/2.0/scheduled-pipelines/#overview) in our docs page.
=> Scheduled Pipelines are not yet available in 3.x

jekyll/_cci2/server-3-install-build-services.adoc
Fixes the contexts table in server-3 docs.
There was a formatting issue with the table showing contexts and their variables in the server-3 docs seen [here](https://circleci.com/docs/2.0/server-3-install-build-services/#github-enterprise).
**Before**:
**After**:
=> (NO-JIRA) Fix contexts table in server-3 docs

jekyll/_cci2/server-3-install-prerequisites.adoc
SERVER-1497
Warn users that failing to host CircleCI & GHE on the same
domain will lead to images failing to load. (This is a GH bug)
=> Put GHE & CircleCI on same domain

docs/local-development.md
Move the PR instructions up, as well as making a note in the first section that this process is different.
Internally we have some non-developers who are asked to make changes to their docs for their teams. This makes the instructions a little more clear for non-developers.
=> Move submitting a PR

docs/local-development.md
We can't accept PRs to our translated content since it will be overwritten by Crowdin. I've removed the reference to the -ja folder for local development. I also updated a url.
We've received a PR for translated content from last year that has been sitting. We unfortunately can't do anything with this as it will just get overwritten by Crowdin. Removing this line and only referencing the english folder will imply that is the location to make any changes allowed.
=> Remove reference to -ja folder, fix link

jekyll/_cci2/configuration-reference.md
Changed the workflow version anchor a unqiue name
In the _On This Page_ section both the top-level **version** and the workflows **version** elements are linked to `#version`.  
Without a unique identifier, both of those entries link to the top-level **version** meaning when I click **version** within the **workflows** hierarchy _it does not go to worklows/version_, but goes to config.yaml/version.
=> Gave workflow `version` anchor a unique name

src/js/services/optimizely.js, src/js/services/optimizely.test.js
Jira link: [DD-72](https://circleci.atlassian.net/browse/DD-72 )
Preview link: [link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-72-add-unit-test-OptimizelyClient-preview/?force-all)
This story is for adding unit tests for the OptimizelyClient as it is a critical part of our experiment resolving process.
Work in progress, add unit tests to optimizely client
- Function inside of optimiely had to be exported so that tests could be ran on them
- Keys were exported such that tests are dependant on latest key
Better test coverage
Unit tests help make sure we are not breaking anything critical, especially when it comes to how we resolve experiments (in that case the OptimizelyClient)
Critical aspects of the OptimizelyClient file are thoroughly tested. This includes: …
=> [DD-72] Add unit test optimizely client

Dockerfile, Gemfile, Gemfile.lock, jekyll/_config.yml, jekyll/_includes/js-assets.html, jekyll/_includes/mobile-sidebar.html, jekyll/_includes/sidebar.html
- Remove dependency to `jekyll-minibundle` in Gemfile & jekyll `config.yml`.
- Update includes to not use `jekyll-minibundle` (called `ministamp`) anymore.
@teesloane and I are unsure at this point why/if `jekyll-minibundle` is useful. It is causing a bunch of problems in dev because it is [incompatible](jekyll-minibundle) with `--incremental`. Some of the examples includes: broken icons in the sidebar and JS files not found.
Currently, it is only used to md5 fingerprint some assets (not all) in prod and it doesn't seem like other non-fingerprinted assets are giving us any trouble? I'm suggesting that we try this for a while and monitor datadog/rollbar to look for any issues.
=> Fix: Remove jekyll-minibundle

jekyll/_includes/sidebar.html
**Associated Ticket:** [DD-272](https://circleci.atlassian.net/browse/DD-272)
- remove old language selector in sidebar
When reverting `sidebar.html` to origin master version, the old language selector was accidentally left in 
See #6084
=> [FIX]: Remove Old Language Selector in Sidebar

src-api/source/javascripts/app/_toc.js, src-api/source/layouts/layout.erb, src-api/source/stylesheets/_variables.scss, src-api/source/stylesheets/screen.css.scss
Jira case: [DD-268](https://circleci.atlassian.net/jira/software/c/projects/DD/boards/477?modal=detail&selectedIssue=DD-268)
Preview link: [link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-268-Add-banner-atop-legacy-CircleCI-v1-API-preview/api/v1/#circleci-v1-api-overview)
Add banner atop legacy CircleCI v1 API docs to direct to CircleCI v2 API docs so that user use the v2 APIs
Direct users to v2 APIs so the v1 APIs can eventually be deprecated
- add in css for banner
Banner sticky to top
=> [DD-268] Add banner atop legacy circle ci v1 api

jekyll/_includes/global-nav.html, jekyll/assets/img/compass/globe.svg, src/js/experiments/forceAll.js, src/styles/_global-nav.scss
**Ticket:**[ DD-299](https://circleci.atlassian.net/browse/DD-299)
**Preview Link:** http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/update-globe-svg-preview/?force-all
**Note:** if globe icon is still broken, hard reset and clear browser cache with `cmd + shift + r` 
- store `globe.svg` as an asset to be used in img tag
- update style and design of icon 
We dont currently have a working version of the globe icon for the language selector in our preview links due to not having the correct dynamic img path for our preview builds.
We are also updating the the actual format of the globe icon svg as previously we were including the entire svg directly in our HTML instead of storing it as an asset and referencing it in an img or picture tag. 
See associated PR #6084 
**Before:** …
=> [DD-299]: Update Globe SVG Format and Fix Display in Preview Link 

jekyll/_cci2_ja/getting-started.md
Using `.circleci/config.yml` as indicated in Using the workflows functionality gives an error as follows:
Unable to parse YAMLwhile parsing a block mapping in 'string', line 22, column 9:          - run: echo "A more familiar hi" # ...             ^
The proposed spacing (killing two spaces) will eliminate the error.
This fix will eliminate the error caused by extra spacing that makes the list parsed incorrectly.
It's such a simple change that I went ahead with this PR instead of submitting an issue.
=> fix a wrong spacing in the 2nd config.yml

src-api/source/includes/_overview.md
Jira link: [DD-303](https://circleci.atlassian.net/browse/DD-303)
Preview link: [link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-303-Jekyll-code-added-to-md-file-in-src-api-outside-of-jekyll-folder-preview/api/v1/#cache-control-header)
Remove jekyll code found in prod.
{: #cache-control-header }
Most likely a suggestion from circledocs-bot
=> DD-303 Remove jekyll code from non jekyll file

src/styles/_progressbar.scss
[Issue cropped up after Progress Bar](https://circleci.slack.com/archives/C021NCSEM44/p1641314809268800)
Make UI visually as it was before
**Before**
**After**
=> [Fix] Grey left of sidebar on large width displays

jekyll/_cci2/gh-bb-integration.md
Fix typo reported by Docs Disco team, as well as some general edits to page.
I also removed one paragraph that seemed to make some commentary about our account and permissions system; it didn't seem helpful nor informational for readers.
=> Edit GitHub/Bitbucket integration page

jekyll/_cci2/concepts.md, jekyll/_cci2/configuration-cookbook.md, jekyll/_cci2/configuration-reference.md, jekyll/_cci2/deploying-ios.md, jekyll/_cci2/examples-intro.md, jekyll/_cci2/executor-intro.md, jekyll/_cci2/executor-types.md, jekyll/_cci2/hello-world-macos.md, jekyll/_cci2/hello-world.md, jekyll/_cci2/ios-codesigning.md, jekyll/_cci2/ios-tutorial.md, jekyll/_cci2/language-dart.md, jekyll/_cci2/migrating-from-1-2.md, jekyll/_cci2/migrating-from-aws.adoc, jekyll/_cci2/migrating-from-azuredevops.adoc, jekyll/_cci2/migrating-from-buildkite.adoc, jekyll/_cci2/migrating-from-github.adoc, jekyll/_cci2/migrating-from-gitlab.adoc, jekyll/_cci2/migrating-from-teamcity.adoc, jekyll/_cci2/sample-config.md, jekyll/_cci2/testing-ios.md, jekyll/_cci2/testing-macos.md
Update macOS docs to encourage adoption of newer Xcode images and add Gen2 resource specs.
With today's release of the macOS Gen2 resources, we want to make sure we're encouraging best practices among customers by removing old Xcode image references.
=> Macos gen2 updates

jekyll/_cci2/v.2.17-overview.md, jekyll/_cci2/workflows.md
Add banner notifying users of sunsetting scheduled workflows.
Fix link in a server doc.
Correct instances of rollback as a noun vs roll back as a verb.
There is still a significant number of users who are using scheduled workflows who have not migrated yet. Hopefully this will be an additional reminder to migrate to scheduled pipelines.
=> Add workflow banner, fix broken link

jekyll/_cci2/collect-test-data.md
* Organize test runners by language
* TOC with the languages
* Table with summary of languages, test runners, formatters, and links to
example/docs
* Added a couple more things (how to use pytest to produce test results for
unittest, kaocha runner for clojure)
https://circleci.atlassian.net/browse/TD-6
=> [TD-6] more structure for junit documentation

jekyll/_cci2/configuration-reference.md, jekyll/_cci2/env-vars.md
Taking care of some English suggestions to links/headers that were a part of an open source PR that couldn't be addressed because it was majority Japanese content updates which can't be merged.
Some of the internal docs links were entered as external links + some of those links were going to confusing URLs based on headers which also needed updating.
=> Update links/header text

jekyll/_cci2/collect-test-data.md
Remove a tags from headers in markdown files.
Some older pages had a tags as headers which was resulting in a bug with the external link indicator.
[Jira Ticket](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-98)
=> Fix headers wtih a tags

jekyll/_cci2/configuration-reference.md, jekyll/_cci2_ja/configuration-reference.md
We typoed yarn.lock and were missing quotes.
Also fixed some whitespacing in the translated content
=> Fix yark typo, include quotes

jekyll/_cci2/runner-installation-mac.adoc
This PR reorders the steps for enabling the `launchctl` service on mac to make it less error prone for users who are installing runner for the first time
Jira: [RT-289](https://circleci.atlassian.net/browse/RT-289)
Screenshot:
=> Reorder steps for `launchctl` on mac

jekyll/_includes/global-nav.html, src/js/services/lang.js, src/styles/_global-nav.scss
**Ticket:** [DD-314](https://circleci.atlassian.net/browse/DD-314)
**Preview:** http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/request-new-language-preview/?force-all
- use `<button>` in place of `<a>` with correct styles when disabled
- refactor how language form input is processed and submitted to amplitude 
Addressing  a bug where the language input is sent to amplitude multiple times upon submission on click due to how it is being handled and processed in lang.js . We are also refactoring the Submit button to be more SEO friendly. 
Refactor associated with: #6097
=> [DD-314]: Refactor Language Submission Process

jekyll/_data/api.yml, src-api/source/includes/_builds_and_jobs.md, src-api/source/includes/_projects.md
It's not a thing any more, as of https://github.com/circleci/circle/pull/13269
=> [ORCH-355] Remove scheduled status/lifecycle for jobs

src/styles/_sidebar.scss
- Add right-side padding on TOC items to account for smaller screens
The layout doesn't look correct on a smaller screen. This PR is adding padding on the right side of the TOC items to give a little more breathing room. 
before:
after:
=> Fix: Add right-side padding on TOC for smaller breakpoint

jekyll/_cci2/server-3-install-build-services.adoc, jekyll/_cci2/server-3-operator-vm-service.adoc
I have moved all config options into the VM service operator guide, and all setup steps to the installation guide and linked the two. There was a lot of overlap and duplication.
=> Add missing sections to VM service guide

src/styles/_global-nav.scss
- update padding for submit btn
Removing the padding for the submit button so that its aligned according to the figma design (previously was `<a>` tag that had no inherent padding)
See original PR #6097 
**Before:**
**After:**
=> [FIX]: fix padding for submit btn

jekyll/_cci2/server-3-install-build-services.adoc
When server 3.3.0 is released, we will have support for deploying server in a shared vpc environment in GCP. This PR adds adds these instructions
https://circleci.atlassian.net/browse/SERVER-1538
=> [Server-1538] server 3.3 - Adding instructions for deploying nomad and vm-service in a shared VPC

src/js/site/sidebar.js
- Check for typeof `IntersectionObserver` before using it.
While the `IntersectionObserver` is [fairly well supported everywhere](https://caniuse.com/intersectionobserver) we have a few errors every day on [DD](https://app.datadoghq.com/rum/error-tracking?issueId=f63406d4-6899-11ec-b77f-da7ad0900002&start=1641921449048&end=1641925049048&paused=false) that suggests that it might not be available for everyone completely. This PR prevents calling it without checking first.
=> Fix: Check for IntersectionObserver existence before using it

jekyll/_includes/google-tag-manager-noscript.html, jekyll/_includes/google-tag-manager.html, jekyll/_includes/head.html, jekyll/_layouts/classic-docs.html
Per Google, they want the GTM tag as high in the head as possible, and the noscript version in the body (also as high as possible).
I selected this position in the head somewhat arbitrarily, but it's below the items that are actually critical to be at the beginning (meta charset, redirect).
=> [WEB-696] Split GTM noscript, move include to head

jekyll/_cci2/env-vars.md
Explained that CIRCLE_USERNAME variable available only if user has CCI account.
https://circleci.atlassian.net/browse/DOCSTEAM-53
=> Clarify use of CIRCLE_USERNAME variable

package.json, src/js/app.js, src/js/site/main.js, yarn.lock
Ticket: [DD-342](https://circleci.atlassian.net/browse/DD-342)
- Remove package and `initLineNumbersOnLoad()` 
The line plugin is causing the copied code to lose its formatting. There isn't a specific error about the formatting, so this could be confusing to people who may not know what to look for
=> [DD-323] Temporarily disable code snippet line numbers

jekyll/_cci2/server-3-install-build-services.adoc, jekyll/_cci2/server-3-install.adoc
In server 3.3, we allow users on EKS to generate service account roles in place of IAM access keys. This PR updates our docs to add this option and links to AWS's docs on how to make it work.
https://circleci.atlassian.net/browse/SERVER-1543
=> [Server 1543] - Adding instructions for generating roles for our 3.x server services

jekyll/_cci2/configuration-reference.md
Removed reference to non-existent AWS Project Settings.
https://circleci.atlassian.net/browse/DOCSTEAM-74
=> Remove reference to AWS Project Settings

jekyll/_cci2/orb-author.md
After some trial and error I found a markdown format that cleans up the numbered lists and indentations. 
The orbs page was confusing as the instructional list was breaking format.
Markdown numbered lists break when things like code blocks and images are added to the lists. With proper formatting and some HTML, the lists can be cleaned up.
**Before:**
**After:**
=> Fix orb page numbers and indentation

jekyll/_cci2/runner-on-kubernetes.adoc
Adding a new configuration value for the values.yaml chart for the runner kubernetes release. This allows users to specify environment variables for the pod they are running runner in. 
To update the docs with the new configuration option added in this [runner k8s PR](https://github.com/CircleCI-Public/circleci-runner-k8s/pull/9)
=> Update runner k8s doc with env configuration

jekyll/_cci2/server-3-install.adoc
[SERVER-1564](https://circleci.atlassian.net/browse/SERVER-1564)
Everything is still referencing Traefik so I left it as-is
and filed [SERVER-1622](https://circleci.atlassian.net/browse/SERVER-1622) to address the change.
=> Document the Kong healthcheck

src/js/site/nav.js, src/styles/_global-nav.scss
[Ticket](https://circleci.atlassian.net/browse/DD-329)
[Preview](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/disable-search-when-mobile-menu-open-preview/?force-all)
-  toggle display for search icon when mobile menu is clicked
There is a bug for the mobile view where we still allow the search feature to work when the mobile menu is open.
The search button and feature should be disabled when the mobile menu is open to present a more unified and cleaner experience while also getting rid of the menu layout change that is currently occurring. 
**Before:**
https://user-images.githubusercontent.com/57234605/149603918-1bd076aa-4d0f-435b-a20d-f3d2dc2459d1.mp4
**After:**
https://user-images.githubusercontent.com/57234605/149603963-e8c4eb2e-2baa-4622-9341-dbb47acf7775.mp4
=> [DD-329]: Disable Search when Mobile Menu Open

jekyll/_cci2/runner-installation.adoc
On the Runner Installation for MacOS page we needed to add further clarification on how to run certain steps/commands.
The directions were unclear on how to set your platform.
Two commands were potentially being run concurrently when they should be run consecutively.
=> Add ex of platform command, separate out export commands

.datadog/development.synthetics.json, .datadog/production.synthetics.json
- Use new Tests IDs for tests running on CI
The DD synthetics tests got removed by mistake and so we had to create new ones and adjust the IDs in the `.datadog` directory.
=> Fix: Bring back DD synthetics tests for CI

src-api/source/layouts/layout.erb, src-api/v2/template.hbs
[Ticket](https://circleci.atlassian.net/browse/DD-317)
- add link tag with `hreflang` attribute to header 
Adding in missing `hreflang` attribute to pages for api v1 and v2
It seems Google prefers the `hreflang` attribute compared to other language identifiers
=> [DD-317] Add in hreflang Attribute 

jekyll/_cci2/runner-installation-linux.adoc, jekyll/_cci2_ja/runner-installation-linux.adoc
Add back a note about setting runner launch-agent environment on Linux (e.g., for proxy settings, etc.).
I think this may have got omitted accidentally after the runner docs reshuffle a while back.
Original PR: https://github.com/circleci/circleci-docs/pull/5795
=> Add back a note about runner launch-agent environment on Linux

jekyll/_cci2/runner-installation-windows.adoc
Clarify exact services Runner on Windows needs.
The Windows installation scripts have been updated to be compatible with more SKUs.
- I've tested the installation process works with Windows Server 2019
Datacenter Core w/ Desktop and RDS installed.
=> Clarify Runner Windows SKU requirements. [RT-323]

jekyll/_cci2/workflows.md
Added a notice to the workflow.mb about jobs older that 90 days not being able to be re-ran.
Customer issue prompted this to be added to the docs.
ALSO, this is a new PR on a previously approved PR, for some reason the original wouldn't build.
=> Added notice about jobs > 90 days old.

src/js/app.js, src/js/site/main.js
[Ticket](https://circleci.atlassian.net/browse/DD-334)
[Preview](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/track-darkmode-preview/?force-all)
- add `trackAction` for user dark mode preference
- set storage key is user preference already recorded
We are gauging the interest of users to switch to dark mode since developers tend to work in dark mode and it’s considered as table-stakes
=> [DD-334] Track if Users Enable Dark Mode

src/styles/_global-nav.scss
[Ticket](https://circleci.atlassian.net/browse/DD-293)
[Preview](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/header-preview/?force-all)
- set header height with media query for views larger than 768px
Addressing bug where header becomes broken and expands in height if users shrink down the window, opens and closes the drop down menu, and then expands the window view again. Users have to reload the page to fix issue.
=> [DD-293] Fix header Nav Height when Expanded

docs/local-development.md
- Replace fork link to actually send reader to the GH Doc 
The original link is a little confusing and only brings you to a place where you can see the `Fork` button. I think we should replace it and instead link to the Github doc so readers can learn how the Fork/PR workflow works.
=> Doc: update fork link

jekyll/_cci2/reusing-config.md
Update boolean example to use less mustache.
Based on customer feedback that the mustache syntax was confusing.
=> Update boolean example

jekyll/_cci2/ip-ranges.md
Fix "thorugh" to "through"
Spelling!
=> fix spelling

jekyll/_cci2/browser-testing.md
Fixing the markdown numbered lists and indentations on this page as they were broken.
**Before**
**After**
The lists kept resetting at 1 because of the code blocks, which breaks the markdown logic.
=> Fix broken numbers and indentations on page

jekyll/_cci2/code-coverage.md
SEO audit fix: only a single H1 per page.
=> remove multiple h1 from code coverage

jekyll/_cci2/customizations.adoc
Rephrasing ambiguous/improper wording on explanations about customizations of server 2.x.
While l10n work has been ongoing the team found out several phrases which were unreasonably difficult to translate. Most of them stems from some ambiguity of the phrases. This PR address them by clarifying what it should mean, both to facilitate translation works and to make things clearer to our customers.
=> Rephrasing explanation for server 2.x customizations

jekyll/_cci2/xcode-policy.md
Update Xcode versions in example image policy chart.
This will make it easier for customers to understand the support lifecycle for the most recent Xcode versions.
=> Update Xcode versions in image policy
