cypress/integration/sidebar/sidebar.spec.js, cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.js, jekyll/_data/sidenav.yml, jekyll/_includes/mobile-sidebar.html, jekyll/_includes/sidebar.html
Preview [link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-274-circle-ci-docs-add-cypress-e-2-e-testing-framework-preview/2.0/docker-to-machine/#pre-installed-software)
Revert using the hash inside of the sidenav.yml
Original PR [link](https://github.com/circleci/circleci-docs/pull/6190/files)
There was an issue that if you go to a link with a `#` in the url the proper side nav panel would not open up.
Example link on live: [link](https://circleci.com/docs/2.0/executor-types/#using-docker)
Example link fixed: [link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-274-circle-ci-docs-add-cypress-e-2-e-testing-framework-preview/2.0/executor-types/#using-docker)
=> cypress PR

src/js/app.js
- initializing `lang.js` when the DOM is fully loaded in `app.js`
We are getting errors in rollbar due to `langValue.domEl` being null as we are trying to add an event to the element before the DOM has been fully loaded and the element has been defined
Addressing the errors from rollbar [here](https://rollbar.com/circle/circleci-docs/items/2901/?item_page=0&)
=> [FIX] Initialize lang.js when DOM is Loaded

jekyll/_cci2/credits.md
Updating the existing free page for confusing language.
The concurrency/parallelism/test-splitting was misleading.
=> Rephrase concurrency

jekyll/_cci2/workflows.md, jekyll/_cci2/workspaces.md, jekyll/_data/sidenav.yml
N&S tasks - workspaces: https://circleci.atlassian.net/browse/DOCSTEAM-118?atlOrigin=eyJpIjoiODRhYjVkZDM5ZGNlNGM0Yjg0OGFmODU5YjNjNzFlMmUiLCJwIjoiaiJ9
Things I've done:
- pull out workspaces into its own page
- linked to new workspaces page from the old place in workflows doc
- added network egress info, how to find usage
- put items back into the TOC in workflows doc so things are easier to find
to do...
I guess I should add info about charges for storage as well as network egress. Is network egress just for runner users, and overages storage costs is for all users @devinmarieb?
=> Update workspaces docs for clarity and add billing and credits info

jekyll/_cci2/configuration-reference.md, jekyll/_cci2/ios-tutorial.md, jekyll/_cci2/language-scala.md
Remove the information about the deploy step in the config ref and link to the new step/alternatives.
Adjust the examples on two pages that still used the deploy key. _Note: there is still one page referencing deploy steps for v1 of the API that needs addressing._
[Jira Ticket](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-99)
Some people are still using the deploy step. By removing the information and replacing the examples, we hope to decrease the usage.
=> Remove deprecated deploy step from config, update examples

jekyll/_cci2/next-gen-migration-guide.md
A duplicate of a stuck image PR that updates the example of how to change the namespace for the new images.
People need to be aware they need to change the namespace of the image, not just the version number.
=> Update image upgrade example

jekyll/_cci2/configuration-reference.md
Updated incorrect spelling of `explicilty` to `explicitly`.
Made these changes for correct spelling and for customer sentiment.
=> Bugfix: Correct Misspelling

jekyll/_cci2/runner-config-reference.adoc
Updating the docs to include the option to not automatically update runners for server usage.
It is currently unclear that server runners should be configured to not automatically update.
=> note runner auto update disable option

jekyll/_cci2/runner-installation-windows.adoc
The Windows installation of runner is quite involved, if anything goes wrong, it can be difficult to try to reinstall.  This adds reinstall steps.
https://circleci.atlassian.net/browse/RT-142
=> Add instructions to reinstall runner on Windows [RT-142]

src/styles/main.scss
Jira [link](https://circleci.atlassian.net/jira/software/c/projects/DD/boards/477?modal=detail&selectedIssue=DD-345)
Preview [link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-345-config-docs-for-save-cache-has-confusing-wrapping-preview/?force-all)
The left-hand column of the “Save Cache” table (“Template”) has very confusing line wrapping that makes it nearly unreadable.
The table is here: https://circleci.com/docs/2.0/configuration-reference/#savecache
[link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-345-config-docs-for-save-cache-has-confusing-wrapping-preview/2.0/configuration-reference/#savecache)
=> [DD-345] Remove pre-wrap

src-api/v2/template.hbs
It was requested that we add a clarifying call to action to the top code samples pane in our API v2 documentation.
Ticket: [DD-323](https://circleci.atlassian.net/browse/DD-323)
Todo: Waiting on suggestions or changes to copy.
Users were expression confusion at the blank space at the top of the page.
=> Add CTA to the top of the code pane in API v2

jekyll/_cci2/faq.md, jekyll/_cci2/persist-data.md
Add a similar messaging as Outer in the form of a banner to indicate the March 1 N&S billing update.
We've made a lot of changes to the docs about N&S costs and those changes are not GA and have been delayed.
=> Add banner for NS billing date

jekyll/_cci2/runner-api.adoc, jekyll/_cci2_ja/runner-api.adoc
JIRA: [RT-328]
- To better support future work that might require in flight tasks, we
are making the tasks listing endpoints generic, as opposed to be
runner specific
- This is technically a breaking change, but the route is currently only used
by an internal staff
- The code change: https://github.com/circleci/distributor/pull/1282
[RT-328]: https://circleci.atlassian.net/browse/RT-328
=> [RT-328] Rename /runner/tasks routes to /tasks

jekyll/_cci2/jira-plugin.md, jekyll/_cci2/notifications.md
This setting is deprecated. All projects (apart from server v2.x) have Pipelines enabled by default now.
=> remove references to enabling pipelines

jekyll/_cci2/language-javascript-experimental.md, jekyll/_cci2/language-python-experimental.md
Bug fix for Node.js references in Python tutorial
Typos can be confusing.
=> [BUG FIX] Node references in Python

jekyll/_cci2/images/linux-vm/14.04-to-20.04-migration.md
This is the first version for this guide. Creating this PR now as we need it available, with a steady URL, for comms coming soon for Linux VM deprecation.
The plans:
- this guide will get updated frequently to add more/better information as we learn it
- there will be 16.04 to 20.04, 14.04 to 22.04, and 16.04 to 22.04 versions of the guide in the future
- this guide won't currently be linked from another page, it will once we get more Image Docs merged in
Related/main organizing PR: https://github.com/circleci/circleci-docs/pull/6216
=> Add first version of 14.04 to 20.04 migration guide

jekyll/_cci2/examples-intro.md, jekyll/_cci2/executor-intro.md, jekyll/_cci2/executor-types.md, jekyll/_cci2/hello-world-macos.md, jekyll/_cci2/testing-ios.md
Remove warnings in docs that using macOS executor requires a paid plan and isn't supported on server.
With today's launch of freemium support for macOS, the paid plan prerequisite is no longer accurate. Additionally, Server has supported macOS since v3.1
=> Update macOS docs for freemium launch

jekyll/_cci2/executor-intro.md
The example config referenced two different Xcode versions, so this PR will correct that.
=> Fix xcode image reference mismatch

src/styles/main.scss
[Jira case](https://circleci.atlassian.net/browse/DD-345)
[Preview link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-345-bug-fix-preview/?force-all)
There was a request to make the table that had code on [configuration-reference](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-345-bug-fix-preview/2.0/configuration-reference/?force-all)/#savecache the columns be longer but the code in columns on [/migrating-from-aws/](https://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-345-bug-fix-preview/2.0/migrating-from-aws/?force-all) were getting messed up.
I made the css code more specific to change just the the requested table
=> Make change more specific

jekyll/_cci2/optimization-cookbook.md, jekyll/_cci2/optimizations.md
- Remove the example of caching optimization from cookbook.
- Small wording adjustments.
This was duplicate content from the optimizations page and was not an example that a user could copy and paste, making it not an ideal example for a cookbook. Instead, we mention the method in the cookbook, but link out to the optimizations page to avoid duplication and miscommunication around pre-set config examples.
[Jira ticket](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-121)
=> Optimizations cookbook changes

jekyll/_cci2/faq.md, jekyll/_cci2/persist-data.md
Only applicable to self-hosted runners
Update network transfer guidance to reflect the fact that it only applies to restoring caches/workspaces to self-hosted runners.
Current guidance is misleading.
=> Fix network transfer guidance

jekyll/_cci2/runner-config-reference.adoc
- Make the 2 hard requirements more clear.
- Clarify the execute arbitrary commands before and after bit.
The existing copy is leading to some customer confusion https://circleci.slack.com/archives/CP4LXVD1T/p1644278215195299
=> Clarify requirements of command_prefix runner config [RT-409]

jekyll/_cci2/server-3-install-prerequisites.adoc
SERVER-1632
We found a bug in our k8s 1.22 support. Until we update prometheus this will be the case.
=> We don't yet support k8s 1.22

jekyll/_cci2/images/linux-vm/14.04-to-20.04-migration.md, jekyll/_cci2/images/linux-vm/16.04-to-20.04-migration.md
Hey team,
This is my second PR now for the migration guides. Specifically, this is for the deprecated Linux VM migration guides. In this PR:
- The original guide gets a new section at the top. This section provides a before and after config example of how swapping the image out might work.
- The original guide has been copied over for the 16.04 to 20.04 guide.
- the top section was tweaked for 16.04. For example, there's no default image.
- the CircleCI changes section was tweaked for the software that would be in 16.04 specifically.
=> Add second migration guide, and some tweaks

jekyll/_cci2/authentication.adoc, jekyll/_cci2/configuration-reference.md, jekyll/_cci2/contexts.md, jekyll/_cci2/env-vars.md, jekyll/_cci2/workflows.md, jekyll/_cci2_ja/authentication.adoc, jekyll/_cci2_ja/configuration-reference.md, jekyll/_cci2_ja/contexts.md, jekyll/_cci2_ja/workflows.md, jekyll/_layouts/classic-docs.html, src/js/experiments/kbLinks.js
Ticket [DD-419](https://circleci.atlassian.net/browse/DD-419))
[Preview](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-419-helpful-resources-section-is-not-properly-working-on-some-pages-preview/?force-all) - NOTE preview builds experiment always turned on so you should test locally to see experiment as control
People not in the experiment are not seeing sections that should be permanent
Japanese was always seeing experiment
Open an Incognito tab
Go to [Configuring CircleCI - CircleCI](https://circleci.com/docs/2.0/configuration-reference/)  
Observe that the Helpful resources section is not showing up
What needs to be hidden is the experiment links not the entire sidebar
/env-vars
/authentication
/configuration-reference
/contexts
/workflows
Authentication no change - …
=> [DD-419] Helpful resources section is not properly working on some pages

jekyll/_cci2/plan-free.adoc
The macOS freemium support is shipping this week and this callout is no longer needed.
=> macOS freemium - remove coming soon callout

jekyll/_includes/global-nav.html
[Ticket](https://circleci.atlassian.net/browse/DD-417) 
[Preview Link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-417/update-CTA-copy-preview/?force-all)
- update copy for button html when not signed in
update the sign-up CTA button verbiage for non logged-in users to "Start Building for Free" so it's more encouraging to sign-up
**Before:**
**After:**
=> [DD-417] Update the Sign-up CTA button verbiage 

jekyll/_cci2/caching.md
Document the enforced maximum length of cache keys. Happy to adjust the wording as the docs folks see fit
See [TASKS-891](https://circleci.atlassian.net/browse/TASKS-891?atlOrigin=eyJpIjoiNzA4MzE5YzVlMzQ2NDc3MTkwMDVlMDhkYmEyOTQyMGIiLCJwIjoiaiJ9)
=> [TASKS-891] Document the max length of a cache key

jekyll/_cci2/scheduled-pipelines.md
Added a FAQ question about the expected scheduled time for a scheduled pipeline.
As discussed internally, our scheduling system is not expressed like the CRON expression as such.
=> docs: add notes about scheduled pipeline run times

jekyll/_cci2/runner-config-reference.adoc
Add example to show how to use a custom script for `command_prefix`.
generated page: https://github.com/circleci/circleci-docs/blob/2daf05334468c44d19817a90256cad1ba4f3cb0c/jekyll/_cci2/runner-config-reference.adoc#runner-command_prefix
https://circleci.atlassian.net/browse/RT-409
=> Add custom script example to command_prefix runner config [RT-409]

jekyll/_cci2/building-docker-images.md
Removing old Docker versions that we either don't want new users on or are technically gone (see [Discuss](https://discuss.circleci.com/t/remote-docker-updates/43026)).
We will have a new Docker version that I will add in April.
=> Remove deprecated remote Docker versions

jekyll/_cci2/executor-types.md
The Docker image updates are because it makes more sense to show our own images as examples when it fits the situation.
The machine image update is because the Ubuntu 16.04 images are deprecated.
=> Update img ref in Executor Type doc

jekyll/_cci2/migrating-from-gitlab.adoc, package.json, src/js/app.js, src/js/services/index.js, src/js/services/trackCopyCode.js, src/js/site/toc.js
[Ticket](https://circleci.atlassian.net/browse/DD-436)
[Preview Link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-436/track-copy-code-preview/?force-all)
- add `trackCopyCode` service 
- add `id` attribute to `toc.js` to help provide clarity on code snippet position meta data for Amplitude
- include removing `.jekyll-metadata` file in `yarn dev clean` to account for cache issues occuring in incremental dev builds 
- fix code snippet syntax typo in `migrating-from-gitlab.adoc`
When moving to PrismJS, we forgot to add the `docs-copy-code-clicked` event tracking back. Being able to track this data is important for potential future experiments
We are keeping the event and meta data the same same as the previous `trackAction` for …
=> [DD-436] Track Docs Copy Code

jekyll/_cci2/env-vars.md
This is from @jabsci 's [PR](https://github.com/circleci/circleci-docs/pull/6439) which did not trigger a build. 
Passing in project or context specific env vars to secondary/service containers is currently not possible.
=> Contexts & project specific env vars in secondary containers

jekyll/_cci2/concepts.md
Added section on Concurrency, to distinguish it from Parallelism.
https://circleci.atlassian.net/browse/DOCSTEAM-139
=> DOCSTEAM-139 Added section on concurrency

jest/global.js, src/js/services/optimizely.js, src/js/services/optimizely.test.js
- Add a `guestExperiment` option for `getVariationName()` function
- Add more test to validate that `getUserId()` works well with logged in user & guest users
We want to start to run experiments on guest users. We can call `analytics.user().anonymousId()` to get a consistent anonymous `userId` that can be used to resolve the experiment variation. More info: https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/identity/#anonymous-ids
Trying the implementation on @tshen815 experiment: https://github.com/circleci/circleci-docs/pull/6396
"resetting" the device (by clearing local storage and cookie), we also get `control` since you get assigned a new `anonymousId`:
=> Add `guestExperiment`option for OptimizelyClient

jekyll/_includes/global-nav.html, src/js/experiments/index.js, src/js/experiments/signUpCTA.js
[Ticket](https://circleci.atlassian.net/browse/DD-417)
[Preview Link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-417/update-signup-CTA-experiment-preview/?force-all)
**NOTE:** Tested with the work @rsylvian did on #6427 guest user experiments. Was able to get treatment variation for as an unsigned in user.
To test out please log out of CCI and view in preview link. If you see the control variation delete your local host and cookies and refresh until you see variation copy
- update copy for CTA button in header
Update the sign-up CTA button verbiage for non-logged-in users to "Start Building for Free" so it's more encouraging to sign-up.
We originally wanted to run this as an experiment but realized that we are unable to do so due to the user not being able to be …
=> [DD-417] Update Signup CTA Copy

jekyll/_cci2/hello-world-windows.md
Removing the software section. Will adjust and link out to more specific resources when those links are available or when the information in included in DevHub.
Apologies for a very unclear commit message - I came back to this and had forgotten what I had done on that particular change 🙃 
This section kept getting out of date too quickly and there was a lack of communication around when changes happened.
=> Remove pre-installed software section

jekyll/_cci2/server-3-install-prerequisites.adoc
the line removed references permissions used for vm-service, however this section of the doc is about object storage.
the command does not need these permissions as the object storage permissions are added in a later command
https://circleci.atlassian.net/browse/SERVER-1485
=> removing unnecessary line in creating gcp prereqs

jekyll/_cci2/customizations.adoc, jekyll/_cci2/orb-author-validate-publish.md, jekyll/_cci2/v.2.18-overview.md, jekyll/_cci2/v.2.19-overview.adoc
Make a few clarifications that we mean CircleCI organization name, not GitHub
Because we deal with both CCI usernames and GH usernames, sometimes this can be confusing out of context. The ticket seemed like there would be a lot of work to do, but searching the docs for certain terms came up with very few results. There might be outstanding issues when we just use the term "organization" or "org" without the continued phrase "organization name" or "org name" but that is so many results that it doesn't make sense to have on one ticket.
[Jira Ticket](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-45)
=> Clarify organization

src/js/services/optimizely.js, src/js/services/optimizely.test.js
- Check for `analytics` & `analytics.user()` existance before requesting the `anonymousId`
We are seeing multiple errors since we launched the new guest user experiment resolver. They are most likely happening because Ad blockers are preventing segment to load.
=> `OptimizelyClient.getVariationName()` should return null when analytics object is not available

jekyll/_config.yml, jekyll/_includes/quick-info-list.html, src/styles/main.scss
Ticket [Link](https://circleci.atlassian.net/browse/DD-446)
In [DD-425: Move the "top reasons why my build failed..." from support to docDEV IN PROGRESS](https://circleci.atlassian.net/browse/DD-425) we want to disable the read-time because it might not completely make sense for this page (no one read the entire page). We should add an option as a front matter variable to let this be customizable.
- A variable called readTime: false can be set in a markdown page to disable the read time for the output page
- by defaults readTime needs to be true for all pages (in _config).
You will have to test it locally by adding in new `readTime` value into md file
=> [DD-446] Implement option to disable read time

jekyll/_cci2/first-steps.md
This follows up on #6447 in which the CTA buttons did not refer back to the page. Since the behaviour seemed a little dicey (it was returning me to circleci.com) I went with just opening the button's link in a new tab.
=> Dd 423 - Follow up fix - open cta links in new tabs.

jekyll/_cci2/local-cli.md
Add Homebrew CLI update instructions
`update circleci` does not work if you've installed the CLI through Homebrew. You need to run `brew upgrade circleci` instead.
=> Add CLI update Homebrew instructions

jekyll/_cci2/android-machine-image.md
Removing the pre-installed software for Android Image. Link out to quarterly update on Discuss instead.
The list was out of date and the content will move to DevHub in the future.
=> Remove pre-installed software Android

jekyll/_config.yml, jekyll/_includes/quick-info-list.html, src/styles/main.scss
- revert styles
- declare `!= false` for pages to show readtime
Fixing a bug that occurred in #6460 for disabling read time
If we want to disable the read time for a page, we have to add the `readtime: false` variable and value to the front matter
=> [FIX]DD-446: Disable Read Time Fix

jekyll/_config.yml, jekyll/_config_production.yml, jekyll/_config_staging.yml, jekyll/_includes/quick-info-list.html
- Move `readtime` to the global scope configuration to make it work how it is intended
`readtime` was undefined when it was setup in the previous spot
=> Move `readtime` to the global scope configuration

jekyll/_data/sidenav.yml
Just confirming this sidenav.yml is used for the actual Japanese sidenav.
=> Update Ja sidenav for CircleCI Plans

jekyll/_cci2/server-3-install-build-services.adoc
Enabling the Nomad Client to use Private Image repo, rather than public docker repository
Customers want to use their own image repository to pull the image i.e. - `circleci/picard`
=> server-1647 Added Notes for using Private Image Repository

jekyll/_cci2/server-3-install-prerequisites.adoc
Once server 3.4.0 is released, we will have support for k8s 1.22
https://circleci.atlassian.net/browse/SERVER-1632
=> Update for server k8s support 1.22

jekyll/_cci2/server-3-install-build-services.adoc, jekyll/_cci2/server-3-install-prerequisites.adoc, jekyll/_cci2/server-3-operator-vm-service.adoc
Add GCP IAM Workload Identity for K8s Service Account in CCI Cluster 
[SERVER-1544](https://circleci.atlassian.net/browse/SERVER-1544)
[GCP Workload Identiyy for K8s](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity)
*Kots Config View*
**Code Change**
[server-1544 | GCP workload identity for VM Services](https://github.com/circleci/server/pull/4980)
=> Server-1544 | Add GCP workload identity for VM services

jekyll/_cci2_ja/index.md
- remove `loading-deffered` from ja/index.md
JA homepage doesn't need `loading-deffered` because the language guide experiment is not running on our JA site.
=> Fix: remove `loading-deffered` from ja/index.md

jekyll/_cci2/orb-author-intro.md, jekyll/_cci2/orb-author-server.md, jekyll/_cci2/orb-concepts.md, jekyll/_cci2/orb-intro.md, jekyll/_cci2/orbs-best-practices.md, jekyll/_cci2/server-3-operator-orbs.adoc, jekyll/_data/sidenav.yml
The current orb authoring guide talks about categorising orbs, which is not available for server customers. Creating a separate guide to avoid confusion.
=> add server-specific orb author guide

jekyll/_cci2/server-3-install-prerequisites.adoc, jekyll/_cci2_ja/server-3-install-prerequisites.adoc
Changed `eksctrl` to `eksctl`
Typo
=> Fix: Typo for eksctl

jekyll/_cci2/hello-world-windows.md
we'll be shipping support for a new image: Windows Server 2022 within ~one week.  I want to prepare the docs for that.  please do not merge yet as the image is not ready for external consumption.  I'll comment on this when it's ready
=> [do not merge yet] prepare docs for windows server 2022 image

jekyll/_cci2/configuration-reference.md
Preview: [here](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/chore/remove-config-ref-readtime-preview/2.0/configuration-reference/?force-all)
Original Request Thread: [here](https://circleci.slack.com/archives/C021NCSEM44/p1646911591991159)
- set `readtime` variable to `false` in config reference markdown
As Configuration Reference is a reference doc it is not meant for reading "cover to cover" and in its current form with the long read time might overwhelm users.
**Before:**
**After:**
=> [CHORE] Remove Readtime for Config Ref

src/js/experiments/signUpCTA.js
Optimizely: [here](https://analytics.amplitude.com/circleci/chart/74xr9av)
Original PR: #6396 
- add new event to track when users click the old signup CTA
We want to see specifically the user engagement with the old signup CTA when they are in the control group versus the engagement for the new signup CTA when they are in the treatment group.
-  `Clicked New Signup CTA`
- `Clicked Old Signup CTA`
=> [CHORE]: Add Tracking for Old Signup CTA when Users are in Control

jekyll/_cci2/code-coverage.md, jekyll/_cci2/orb-concepts.md, jekyll/_cci2/orb-intro.md
* clear up language around orb types - there are no 3rd party orbs,only Certified and Uncertified. And within Uncertified there are Partner and Community
* move descriptions of public and private orbs to the orbs concepts page
* make content accurate - private orbs can be viewed in the dev hub if you are logged in and have a direct URL
* general readability improvements
* add a note to codecov orb usage example to make people aware they need to opt-in to use uncertified orbs
=> Clear up language around different orb types

jekyll/_cci2/circleci-images.md, jekyll/_cci2/executor-intro.md, jekyll/_cci2/executor-types.md
- Update banner text about legacy convenience image deprecation last quarter.
- Some cleanup on general image-related content (fixed typos, applied style guidelines, small edits for clarity).
Banner text was not updated on a couple of pages.
Only focused on the [Executors and Images](https://circleci.com/docs/2.0/executor-intro/) and [Choosing an Executor Type](https://circleci.com/docs/2.0/executor-types/) pages to keep this PR smaller and quicker.
=> Cleanup for general image-related pages

jekyll/_cci2_ja/dedicated-hosts-macos.adoc
Adding ```yaml, which was removed by Crowdin in the translation process.
=> FIx Crowdin's bug

jekyll/_cci2/concepts.md
Changes link from resource_class to resourceclass
resource_class is not the appropriate URL and the link was just going to the top of the config ref
=> Fix broken resource class link

jekyll/_data/sidenav.yml
As there are more releases the server admin section in the side bar is becoming unmanageable. This PR splits out the versions to make things easier to find.
=> separate sections for server 2 and 3 in sidebar

jekyll/_cci2/persist-data.md
Update April 1 to May 1 and add clarification about the ability to test usage controls.
We are allowing customers to test out usage controls for 30 days before we start new charges.
=> Update banner in Persist Data

src/js/services/optimizely.js, src/js/services/optimizely.test.js
- Add `getAnonymousId` to guarantee a consistent userId while experiment resolving
It was a little confusing to attempt to do both resolvings of `userId` and `anonymousId` in the same function. This created side effects where the `anonymousId` will be used while the call to the API was still resolving.
=> Fix: add `getAnonymousId` to guarantee a consistent userId

jekyll/_cci2/faq.md, jekyll/_cci2/persist-data.md
One more change to the storage banners. We are making it the dates specific to performance plan customers.
The timeline is slightly different for scale and custom users, who will see these charges at a later date.
=> Add clarity around performance plan changes

jekyll/_cci2/configuration-reference.md, jekyll/_cci2/executor-intro.md, jekyll/_cci2/executor-types.md
Similar to the legacy convenience images deprecation, we are adding banners to warn users of Ubuntu 14.04 and 16.04 images deprecation (first upcoming brownout in two weeks, EOL end of May). This change adds banners to the following docs:
https://circleci.com/docs/2.0/executor-intro/
https://circleci.com/docs/2.0/executor-types/#using-machine
https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
Part of communications out to CircleCI users to make the appropriate changes to their pipelines in advance of the image brownouts/EOL.
=> Add banners for machine images deprecation

jekyll/_cci2/concurrency.adoc
Removing an extra `/` that made it into the URLs.
Some of the URLs are broken.
=> Fix broken links

jekyll/_cci2_ja/first-steps.md
The experimental code broke the first-steps page, so I revert this file to the file before the translation.
Page URL:
https://circleci.com/docs/ja/2.0/first-steps/
Used this file:
https://github.com/circleci/circleci-docs/blob/e0cf299bb8871ba41065650f5371d6a4ff166432/jekyll/_cci2_ja/first-steps.md
Conversation:
https://circleci.slack.com/archives/C021NCSEM44/p1647473157089129?thread_ts=1647472616.498809&cid=C021NCSEM44
Checked the page locally.
=> Revert to the file before translation

jekyll/_cci2/server-3-install-hardening-your-cluster.adoc, jekyll/_cci2/server-3-install.adoc, jekyll/_cci2/server-3-whats-new.adoc
We currently have the "Traefik load balancer" documented for our customers, but we have since moved to Kong. The service name in Kubernetes did not change (`circleci-server-traefik`) in order to persist the existing load balancer. We are now updating our docs to reflect this change
https://circleci.atlassian.net/browse/SERVER-1622
=> updating referrences from traefik to kong

jekyll/_cci2/v.2.19-overview.adoc
It seems that by 2.19.14 that we changed the way we reference tags in jobs. This update to the changelog reflects this change 
https://circleci.atlassian.net/browse/SERVER-1691
https://circleci.zendesk.com/agent/tickets/105747
=> updating 2.19.14 changelog with changes to git checkout

.github/CODEOWNERS
I realised docs team weren't listed as code owners for the `_data` and `_includes` dirs. This fixes it!
=> update codeowners so docs team own sidebar and snippets etc

jekyll/_cci2/configuration-reference.md
There is a link from the app project settings > ssh keys to the config reference. The link was broken. This PR fixes the link
.
=> fix link tag in doc to fix link from app

src/js/experiments/signupLinksCta.js, src/styles/_first_steps_cta.scss
The content of `/first-steps` got translated into Japanese, but the styling and javascript were not built to run on the japanese page. This makes the experiment run on `docs/ja/2.0/first-steps`/
=> Fix: Signup experiment on JA

jekyll/_cci2/hello-world-windows.md
Link to Dev Hub for image software.
Currently there is no good resource for someone to find what software is pre-installed on the windows image. The most relevant link we have is the Dev Hub, which links out to some discuss posts.
=> Update link from Discuss to Dev Hub

src/js/experiments/popupCta.js
- The original code had the "lastSeen" date being reset every time the counter reset. This would result in the popup not  accurately representing the duration of "one day" between being shown.
=> Fix: date does not reset.

jekyll/_cci2/server-3-install-prerequisites.adoc
Update flag `--name` to `--cluster`
eksctl version 0.80.0 states `Flag --name has been deprecated, use --cluster`
=> Update Deprecated Flag Name

jekyll/_cci2/language-python.md
The note references the legacy circle CI image for python and a version which does not match the code example above.
Let's make the doc consistent
=> Fix docker image name in note

src/js/app.js, src/js/site/main.js
Ticket
Original PRs: #6272 & #6221 
- remove tracking logic from `main.js`
- remove import from `app.js`
We have enough data for user printing and dark mode preferences, we are cleaning up our code base in terms of best practice and also reducing our overall bundle size and amplitude calls. 
No new data will be gathered for our amplitude charts for both User Printing Preferences and Dark Mode preferences from when this PR is merged.
No visual changes
=> [DD-498] User Printing Preference & User Darkmode Preference Teardown 

src/styles/_asciidoc.scss
* Some features of asciidoctor require additional CSS to work. 
* This PR is to add the CSS required to use sidebars: https://docs.asciidoctor.org/asciidoc/latest/blocks/sidebars/
* The admonitions look bad (as they do always!) but we can tackle that in another ticket :-D
They look like this - I just added some random content to show how they look - the whole "Interesting" box is a "sidebar":
=> add css to allow use of asciidoc sidebars

jekyll/_cci2/server-3-overview.adoc
In the server v3 overview we have a list of services included in an installation. This PR is to keep the list up-to-date.
Changes detailed here: https://circleci.slack.com/archives/GKZGNMNR5/p1646920165906649
=> remove deprecated services from server v3 list

jekyll/_includes/two-up.html, src/styles/includes/two-up.scss, src/styles/main.scss
[Ticket](https://circleci.atlassian.net/browse/DD-451)
- add a new include for a "two-up" component where the left side is text and the right side is an image.
- this PR adds no content - just the structure for the include.
- however, one can view an example of it implemented at [this preview link](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-451-two-up-preview/2.0/workflows/)
Here is a screen-recording representing breakpoints. I think it should change sooner, but I just used the standard mobile breakpoint we use everywhere.
https://user-images.githubusercontent.com/12987958/159349694-fc5855ae-093c-4d7f-aa38-c002fc45cd2c.mp4
=> Add: two-up include for new quick start guide

jekyll/_cci2_ja/migration.md, scripts/snippets_csv/index.js, scripts/snippets_csv/package.json, scripts/snippets_csv/runArticleTracking.js, scripts/snippets_csv/runSnippetTracking.js
Regenerate the code snippets spreadsheet. Over time, the links we generated to specific lines of content that contain code snippets have drifted.  Since this will always be a problem, let's change the output to include:
-fileName
-lines
-snippetSize
-link to Docs Article,
-updatesCount
-age
-link to github
Provide stakeholders with valuable information about code snippets
Right now it cuts off at the first . need to cut off .md or .adoc
=> [DD-439] Regenerate the code snippets spreadsheet

jekyll/_includes/getting-started-section-header.html, jekyll/assets/img/docs/quick-start--first-step.svg, jekyll/assets/img/docs/quick-start--second-step.svg, jekyll/assets/img/docs/quick-start--third-step.svg, src/styles/includes/_getting-started-section-header.scss, src/styles/main.scss
[Ticket](https://circleci.atlassian.net/browse/DD-452)
[Preview](http://circleci-doc-preview.s3-website-us-east-1.amazonaws.com/DD-452/getting-started-experiment-header-preview/2.0/concepts/?force-all)
**NOTE:** The preview link is just demoing the section header on the concepts page as we currently dont have the layout in place for the Getting Started experiment yet. 
- add includes HTML layout for section header
- add styles for section header
- import SVGs for header banner image
We need to create an include section that we can reuse for each section for the Getting Started experiment. The includes layout should accept the title, banner image and intro paragraph as per the design. The includes should also be responsive to window size changes. 
This PR is a part of the [Getting Started …
=> [DD-452] Jekyll include for the section header + illustration + paragraph

jekyll/_cci2/server-3-operator-metrics-and-monitoring.adoc
Prometheus graphs in the kots admin dashboard is broken for KOTS versions 1.65+
We need to make note of this with a warning
https://circleci.atlassian.net/browse/SERVER-1711
=> adding warning about supported kots version

jekyll/_cci2/optimizations.md
Section `See the resource_class section of the Configuration Reference for more information.`
reference a bad link that causes a 404
❌  https://circleci.com/2.0/configuration-reference/#resourceclass
good link ✅ https://circleci.com/docs/2.0/configuration-reference/#resourceclass
404 error for customer
=> chore(optimizations): replace baseURL to baseurl - 404 error

jekyll/_cci2/server-3-install-prerequisites.adoc
Updated the links since we are now recommending v1.64.0 (previously v1.47.3)
> You can confirm the download links here https://github.com/replicatedhq/kots/releases/tag/v1.64.0
It seems we use the `{kotsversion}` template to declare the latest supported version.
(see https://github.com/circleci/circleci-docs/pull/6450)
I wanted to use the same `{kotsversion}` template on these links so that we can skip manual link updates too.
However, I noted that the Mac (Darwin) release URL pattern from v.1.47.3 to v.1.64.0 has changed:
```diff
- https://github.com/replicatedhq/kots/releases/download/v1.47.3/kots_darwin_amd64.tar.gz
+ https://github.com/replicatedhq/kots/releases/download/v1.64.0/kots_darwin_all.tar.gz
```
Hence, I decided for this commit, I'll skip using the `{kotsversion}` template …
=> Update KOTS installation links for v1.64.0

docs/WIDGETS.md, jekyll/_cci2/aws.adoc, jekyll/_cci2/customizations.adoc, jekyll/_cci2/gh-bb-integration.md, jekyll/_cci2/insights-glossary.md, jekyll/_cci2/insights-tests.md, jekyll/_cci2/insights.md, jekyll/_cci2/jira-plugin.md, jekyll/_cci2/notifications.md, jekyll/_cci2/orb-author.md, jekyll/_cci2/pipelines.md, jekyll/_cci2/webhooks-airtable.md
For accessibility, we should always include alt text when including images in our docs. This PR adds those that were missing.
=> Ensure all images have alt text

jekyll/_cci2/configuration-reference.md
The indentation on the linux GPU example was incorrect. Also the resource class table was incomplete.
=> fix linux GPU example

jekyll/_includes/quick-info-list.html
[Ticket](https://circleci.atlassian.net/browse/DD-497)
- Fix: conditionally show "reading time" popper text if reading time is enabled for that document.
Original bug:
=> Fix: only show "reading time" in tooltip if it exists for doc.

.github/workflows/assign-reviewer-ja.yml
This introduces a GitHub action workflow to assign a reviewer randomly if a new PR is created `master <- ja-localization`.
* We need a reviewer to merge l10n works.
* We don't want to overwhelm a single person with reviews.
=> Init impl of auto assignment of reviewer for l10n

jekyll/_cci2/runner-installation.adoc
Update Launch-Agent Version for Server 3.4
This version is taken from the server-3.4 branch [here](https://github.com/circleci/server/blob/e54a984cf22f071cd9d56231aa811dcb77738843/tests/cypress/integration/runnerTests/launch-agent.sh#L3)
Server 3.4 is being released soon and we're updating the documentation to show the appropriate version
=> Update Launch-Agent Version for Server 3.4

jekyll/_cci2/server-3-install-prerequisites.adoc, jekyll/_cci2/server-3-install.adoc
* Added missing GCP Workload Identity information
* Updated doc link 
[SERVER-1733](https://circleci.atlassian.net/browse/SERVER-1733)
=> server-1733/GCP_WI_update | update link and GCP WI detail

jekyll/_cci2/persist-data.md
Add a note about storage billing to the Managing / Reducing section of the Persist Data page.
This was a suggestion in another PR that I had to merge for timeline reasons - coming back to it now.
=> Add note about storage billing on persist data

jekyll/_cci2/ip-ranges.md
Remove no-longer-used IP addresses and add newly allocated IP addresses for IP ranges
[Jira issue](https://circleci.atlassian.net/browse/FLEETS-763)
=> [FLEETS-763] Re-arrange valid IPs based on current infrastructure

jekyll/_config.yml
Update base directory for asciidoc content to widen the scope of content outside `_cci2`. We already have a style guide, and soon "Vamp" docs will live outside the `_cci2` dir.
Reference here: https://github.com/asciidoctor/jekyll-asciidoc/tree/v2.1.x#specifying-the-base-directory
(ignore the other commits, I was playing around with the images path and previews)
=> Update asciidoc attributes

jekyll/_cci2/xcode-policy.md
- Add a link to the DevHub on this page since this is what appears in google searches first.
- Some text updates.
- Some example updates.
We want users to be able to find the macOS devhub pages quickly.
[Jira ticket](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-38)
=> Xcode page minor updates

jekyll/_cci2/server-3-install-build-services.adoc
* Default value updated as `false` for variable `unsafe_disable_mtls` in nomad gcp example. 
[SERVER-1701](https://circleci.atlassian.net/browse/SERVER-1701)
=> server-1701 | Updated mtls value in nomad gcp example

jekyll/_cci2/configuration-reference.md, jekyll/_cci2/env-vars.md, jekyll/_cci2/reusing-config.md, jekyll/_data/sidenav.yml
We had previously updated references to "pipeline variables" to "pipeline values and parameters," but there were a few remaining that needed to be changed.
There isn't an "official" term that encompasses both pipeline values and parameters. This update is just to make sure we are being more consistent and clear in what we are referring to.
=> Quick patch for pipeline values and parameters

jekyll/_cci2_ja/yarn.md
"キャッシ" (Kyasshi) → "キャッシュ" (cache)
=> Fixed typo in yarn.md

jekyll/_cci2_ja/notifications.md
Fixes a typo in notifications markdown (72e60d15 part of #5993)
- notifications (production URL): https://circleci.com/docs/ja/2.0/notifications/#set-or-change-email-notifications 
We do not need to wrap link text with an extra `[]`.
=> Fix typo in notifications (72e60d15)

jekyll/_cci2/variables.md
Use `cimg/*` images for example on [/variables/](https://circleci.com/docs/2.0/variables/).
The `circleci/node` image is legacy and has been deprecated on 2021-12-31.
> Legacy images with the prefix "circleci/" were [deprecated](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) on December 31, 2021.
=> Use cimg/* images for example on /variables/

docs/server-docs.adoc, jekyll/_cci2/server-3-overview.adoc, jekyll/_style/style-formatting.adoc, src/styles/_asciidoc.scss
Update asciidoc admonitions with to look like html alerts.
This is how they looked before:
This is how they look now:
I have updated the style guide section on formatting too, to include info on how to use them.
=> update admonition styles in asciidoc content

jekyll/_cci2/hello-world-windows.md
Updates [Windows executor page](https://circleci.com/docs/2.0/hello-world-windows/) in docs to include example of using the new Windows 2022 image.
This also includes a change to the Windows orb version used, as well as a quick refresh of the [example application](https://circleci.com/docs/2.0/hello-world-windows/#example-application) since the example config had been previously updated.
https://discuss.circleci.com/t/march-2022-beta-support-for-new-operating-system-for-windows-executors-windows-server-2022/43198
=> New Windows Server 2022 image

jekyll/_cci2/language-python.md
This had been previously removed in the full config example at the end of the
page but not in the stepthrough in the doc.
Resolve inconsistency around caching as pointed out in [this issue](https://github.com/circleci/circleci-docs/issues/6409#issuecomment-1085922457).
=> Remove caching of /usr/local/bin in stepthrough

jekyll/_cci2/ecs-ecr.md
Replace outdated environment variables with new.
Replaced environment variables are no longer used in the script so the build fails when it's configured as described currently.
=> Update environment variables

jekyll/_cci2/building-docker-images.md
Docker version `20.10.12` is available to use, so this adds it to the list of available versions
Keeps the list of available Docker versions up-to-date
=> add 20.10.12 to list of available docker versions

jekyll/_cci2/language-java.md
Remove an unsupported key 'when' from store_artifacts step.
The key has no effect since this step is always executed according to [docs](https://circleci.com/docs/2.0/configuration-reference/#the-when-attribute).
=> Remove unsupported key 'when' from store_artifacts

jekyll/_data/sidenav.yml
Removing the "Introduction" link of Configuration in the side nav.
There is only one section now and that page is repetitive to the page directly under it. This is how we've gone about organizing in other sections, like Insights.
=> Remove solo intro section

jekyll/_cci2/configuration-reference.md
Add most recent Ubuntu images to config reference's list of available machine images. 
Resolves issue [#6570](https://github.com/circleci/circleci-docs/issues/6570)
Ideally, we would just either link to the Developer Hub, or wherever the single source of truth is, and not maintain a separate list of images in other docs pages such as the Config Reference. However, for now we want to keep the list in the config reference that includes the Ubuntu 16.04 images because they are technically still available, albeit deprecated. 
This also means that with the upcoming release of the new 22.04 images, following this pattern we'd have to do at least another addition to the list before May of this year.
When the 14.04 and 16.04 images are EOL in May, we should remove the list entirely from the …
=> Update available linux machine images list

src/styles/includes/two-up.scss
Small bug fix found while prod testing DD-450 Getting Started Experiment. See info on PR [here](https://github.com/circleci/circleci-docs/pull/6544)
Alignment of the pictures to the right.
=> [DD-450] Post prod testing

jekyll/_cci2/orb-author.md
Add warning to make clear that new orb repos MUST be empty
=> docs: warn new orb repos must be empty

.github/pull_request_template.md
The PR adds a link to the style guide, plus a content checklist to the PR template.
To help contributors check for things that will improve our content for consistency, SEO and so they are easier to consume.
=> add content checklist items to PR template

.circleci/config.yml
Allow rendering previews for branches that also build server PDFs.
We need to do both these things in single branches and I've just realised we can't.
=> change server pdf build syntax to allow -preview

jekyll/_cci2/optimizations.md
Noted that the intended link is to https://circleci.com/docs/2.0/persist-data/#custom-storage-usage
Hence, this small fix!
=> fix: broken link to Custom Storage Usage

jekyll/_cci2/openid-connect-tokens.adoc
Additional information regarding setting up with AWS
We got user feedback that this info wasn't in our docs. The information is from the blog post:
https://circleci.com/blog/openid-connect-identity-tokens/
=> Add AWS instructions to OIDC page

jekyll/_cci2/runner-overview.adoc, jekyll/_includes/snippets/built-in-env-vars.md
Document environment variables that are not set on runner executors
[RT-344](https://circleci.atlassian.net/jira/software/c/projects/RT/boards/485?modal=detail&selectedIssue=RT-344)
=> [RT-344] Document missing runner env vars

jekyll/_cci2/xcode-policy.md
Update Xcode image policy document
CPE-496 as a result of the policy review to manage image disk usage
cc @alexazl for additional review (please do not merge until Alexa has reviewed)
=> Update Xcode image policy document

jekyll/_cci2/configuration-reference.md
Avoids POSTGRES_USER=root environment variables and old images on [/configuration-reference](https://circleci.com/docs/2.0/configuration-reference/). Also the deprecated images (PostgreSQL 9.2 was already EOL'd) are updated to the latest minor.
Part of #6700
=> Avoid POSTGRES_USER=root env on /configuration-reference

jekyll/_cci2/postgres-config.md
Avoids POSTGRES_USER=root environment variables and old images on [/postgres-config](https://circleci.com/docs/2.0/postgres-config/).
Part of #6700
n/a
=> Avoid POSTGRES_USER=root env on /postgres-config

jekyll/_cci2/project-walkthrough.md
Avoids POSTGRES_USER=root environment variables and old images on [/project-walkthrough/](https://circleci.com/docs/2.0/project-walkthrough/). Also the deprecated images (PostgreSQL 9.6 was already EOL'd) are updated to the latest minor.
Last part of #6700
n/a
=> Avoid POSTGRES_USER=root env on /project-walkthrough

jekyll/_cci2/oss.md
- Remove [`facebook/relay`](https://github.com/facebook/relay) repo from Example open source projects on [/oss/](https://circleci.com/docs/2.0/oss/).
- Storybook is not `StoryBook` (https://github.com/storybookjs/storybook).
- Org rename in storybook: https://github.com/storybookjs/storybook/pull/6954
- https://github.com/facebook/relay/pull/2892
=> oss: Relay does not use CircleCI any more

jekyll/_cci2/parallelism-faster-jobs.md
This PR adds a note about using a legacy XML format with pytest if you want timing-based test splitting.
Using pytest 6.1 the default junit_family format changed to no longer include filenames, which will break timings-based test splitting. The format will need to be changes to `xunit1` for this feature to work. 
=> add note about pytest 6.1

jekyll/_cci2/concepts.md
Avoids `POSTGRES_USER`=`root` environment variables and old `postgres` image tag on [/concepts](https://circleci.com/docs/2.0/concepts/).
Part of #6700
=> Avoid POSTGRES_USER=root env and old postgres image tags

jekyll/_cci2/projects.md
Added a link to the new Creating a Project tutorial that was merged yesterday.
Linked to https://circleci.atlassian.net/browse/DOCSTEAM-235
=> Added link to Creating a Project doc

src/styles/main.scss
- Remove blanket `pointer-events: none;` on all link's child
It was reported to us that search results are not clickable on Chrome latest update. I was able to reproduce on `Chrome Version 101.0.4951.41`
=> Fix: search hits not clickable on chrome v101

jekyll/_cci2/runner-installation-cli.adoc
We are missing the Runner `circleci-launch-agent` for Server 3.4. 
This PR adds the correct version to both:
1. Continued for Linux, macOS, and Server
2. Self-hosted runners for server compatibility
There is a different version for Server 3.4. 
- [N/A] Break up walls of text by adding paragraph breaks.
- [N/A] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [N/A] Keep the title between 20 and 70 characters.
- [N/A] Consider whether the content would benefit from …
=> Add circleci-launch-agent version for Server 3.4

jekyll/_cci2/concepts.md
Replaces `buildpack-deps` (by `@docker`, not by `@circleci`) with the latest version of `cimg/base` on /concepts.
Part of #6746
n/a
=> Replace buildpack-deps with cimg/base:2022.04-20.04 on /concepts

jekyll/_cci2_ja/language-ruby.md
Make URLs clickable by using half-width spaces around them.
They should be clickable in some editors (e.g. VSCode) while they are not on https://circleci.com/docs/ja/2.0/language-ruby/.
=> ja: Make URLs clickable

jekyll/_cci2/building-docker-images.md, jekyll/_cci2_ja/building-docker-images.md
The latest version of docker that can be set to setup_remote_docker seems to be 20.10.12, so I have updated it.
=> updated sample setup_remote_docker version to latest

jekyll/_cci2/openid-connect-tokens.adoc
Updating the instructions for a user to find their org id.
The UI to find an organization ID is changing from Context page to Overview page in the UI.
=> Change UI instructions for org id

jekyll/_cci2/configuration-reference.md
A remaining piece of code from older command was used to persist the workspace folder
Because when copying/pasting the code example, we are getting an error in config.yml version 2.1
=> updating save_workspace to persist_to_workspace

src/js/experiments/gettingStartedGuide.js
[Ticket](https://circleci.atlassian.net/browse/DD-589)
[Optimizely](https://app.optimizely.com/v2/projects/16812830475/experiments/21268663100/variations)
- add event listener to track clicks on `getting-started` link for both control and treatment variations in sidebar
- make `setUpTracking` dynamic for both treatment and control variations
We didnt have tracking set up for the link to `docs/2.0/getting-started/` in the sidebar
The `clicked-sidebar-getting-started` event will be fired when users click on either `Quickstart Guide`(treatment) or `Your First Green Build` (control). We can compare the click rate for both in amplitude by segmenting them with the `variation` property.
1. `clicked-link-to-gettingStarted`
- `variation`
- `linkLocation`
- `referrer`
**Link in sidebar:**
**Link in …
=> [DD-589] Add Tracking for Quickstart Guide NEW Badge in Sidebar

jekyll/_cci2/building-docker-images.md
New version of remote Docker was published this morning. This PR adds it to Docs.
=> Add 20.10.14 remote Docker version

jekyll/_cci2/orb-intro.md
Re-framing the definition of orbs to match the glossary definition as well as language used on outer.
The definition felt a bit outdated.
[Jira ticket](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-205)
=> Update orb-intro to match glossary

jekyll/_includes/snippets/machine-resource-table.md
Update the table to reflect 100gb RAM across all resource classes
RAM is now different for Linux resource classes
=> Update machine resource table Linux

jekyll/_cci2/dedicated-hosts-macos.adoc, jekyll/_cci2/executor-types.md
I'm updating the column headers for the Dedicated Hosts specs table to be more consistent with other spec tables and clarify that storage info is for total storage, rather than available. I'm also adding a section to the macOS docs with details about our available VM storage.
We get a lot of questions around macOS storage and want to provide an easy reference for customers in our docs.
=> Macos storage

jekyll/_includes/snippets/machine-resource-table.md
Update RAM column in machine executor table in config ref
Values were in fact disc size.
=> update snippet to correct RAM values

jekyll/_cci2/runner-installation-mac.adoc
Add clarity around installing runner on macOS for a second time.
The banner didn't make it clear you needed to run both commands, not just the second one.
=> Clarity on macOS runner banner

jekyll/_cci2/configuration-reference.md, jekyll/_cci2_ja/configuration-reference.md
Ubuntu 22.04 Machine images are now available 🙌 
https://discuss.circleci.com/t/ubuntu-22-04-jammy-jellyfish-now-available-for-beta-testing/43440
I was able to confirm the Docker & Docker Compose versions through a sample build here:
https://app.circleci.com/pipelines/github/kelvintaywl-cci/deprecated-machines/17/workflows/2755ec39-56a7-4b44-a3c9-78929d271d66/jobs/49
=> add ubuntu-2204:2022.04.1 image under Available Linux Machine images

jekyll/_cci2/server/Installation/2-install-core.adoc, jekyll/_cci2/server/Installation/3-install-execution-environment.adoc, jekyll/_cci2/server/Installation/4-install-post.adoc, jekyll/_cci2/server/Installation/7-install-migration.adoc, jekyll/_cci2/server/Operator/operator-overview.adoc
Update core service docs to reference helm instead of KOTS
4.0 will be KOTS free
=> [SERVER-1666] update core install guide to use helm instead of KOTS

jekyll/_cci2/dedicated-hosts-macos.adoc
Update Dedicated Hosts table header from `Memory` to `RAM`.
The rest of our executor/resource class tables use `RAM` and this change will provide more consistency across the docs.
=> Update dedicated hosts table header to match other executors

src-api/source/includes/_overview.md
* Removes "build parameters" link that pointed to [test splitting and parallelism](https://circleci.com/docs/2.0/parallelism-faster-jobs/)
* Removes mention of different 1.0 and 2.0 build parameters
The [test splitting and parallelism](https://circleci.com/docs/2.0/parallelism-faster-jobs/) link did not seem at all relevant to build parameters. There does not seem to be documentation on any difference between 1.0 and 2.0 build parameters (1.0 /2.0 is not the same as v1/v2 of the api)
=> Remove non build params link

jekyll/_cci2/executor-intro.md
Changed the deprecated  ubuntu version to supported one. 
The image is chosen from here : https://circleci.com/docs/2.0/configuration-reference/#available-linux-gpu-images
[Deprecating Ubuntu 14.04 and 16.04 images: stay secure with modern Ubuntu](https://circleci.com/blog/ubuntu-14-16-image-deprecation/)
=> Fix gpu executor image to supported ubuntu version

jekyll/_data/sidenav.yml
- Remove extra `-` in front of `i18n_name`
A `-` was prepending a `i18n_name` attribute which resulted in breaking the JA sidebar 
=> Fix: incorrect yml for JA sidenav

jekyll/_cci2/server-3-install-prerequisites.adoc
We are advocating customers to install v1.65.0 as can be seen on https://circleci.com/docs/2.0/server-3-install-prerequisites/#install-required-software
I noted [a previous PR](https://github.com/circleci/circleci-docs/commit/b8124b42f9eb170011d35abbdd26055b5145209f) addressed the earlier broken link.
However, as a customer noted, this is pointing to a different version @ 1.69.1 instead.
We can verify the updated link for Mac download in this PR here:
https://github.com/replicatedhq/kots/releases/tag/v1.65.0
Customer noted this link points to a different version (v1.69.1) which is not the same as the link for Linux (1.65.0).
Our docs recommend customers to use 1.65.0 as well. 
Please follow our style when contributing to CircleCI docs. Our style guide is here: …
=> fix KOTS cli Mac download link to 1.65.0

jekyll/_cci2/server-3-install-prerequisites.adoc
Updated the table to account for Server 3.4.1
3.4.1 has been released.
Specifically, we noted that 3.4.1 supports k8s version of the same range (1.16 - 1.23), as seen here:
https://circleci.com/docs/2.0/server-3-whats-new/#known-issues
=> include 3.4.1 in list for supported k8s versions

jekyll/_cci2_ja/code-coverage.md
Just sync en->ja to update circleci/node images to latest.
- #5554 port to ja
=> ja: Update circleci/node images to latest

jekyll/_cci2/runner-installation-linux.adoc
Reorder sections of runner linux install after customer feedback.
One of the steps makes more sense coming later in the process than we have instructed.
closes #6885 
=> Adjust section order, add heading syntax

jekyll/_cci2/runner-on-kubernetes.adoc
Updates the Runner Kubernetes docs on how to set a pinned launch agent version for server. The launch agent binary is now built into the image and the image tag is used for versioning.
See this related PR: https://github.com/CircleCI-Public/circleci-runner-k8s/pull/19
Jira: https://circleci.atlassian.net/browse/RT-578
=> Update instructions for pinning launch agent versions in Helm chart

jekyll/_cci2/server-3-whats-new.adoc
This is a follow-up from https://github.com/circleci/circleci.com/pull/5996
We noted that since 3.4.0, for newer pipelines, the config files are now stored on S3 rather than Postgres.
As such, some customers were seeing errors when accessing certain pipelines due to the fact that they had retention policy set for their S3.
This change caused the config files for newer pipelines to be deleted (due to lifecycle rule on their S3), and thus errors on the UI.
Please take a moment to check through the following items when submitting your PR (this is just a guide …
=> Mention change in config file storage destination from CCIE 3.4.0

jekyll/_cci2/configuration-reference.md, jekyll/_cci2/executor-intro.md, jekyll/_cci2/using-linuxvm.md
Banner removed from https://circleci.com/docs/2.0/using-linuxvm/ and https://circleci.com/docs/2.0/executor-intro/#linux-vm. Keeping the banner on https://circleci.com/docs/2.0/configuration-reference/#available-linux-machine-images to help guide users who are still trying to migrate to newer images at this time.
Ubuntu 14.04 and 16.04 machine images were EOL on May 31 2022.
=> Update banners for 14.04 and 16.04 EOL

jekyll/_cci2/server/Installation/5-install-hardening-your-cluster.adoc
Adding docs for:
- use of single loadbalancer and nginx as our exposed reverse proxy
- the kong and nginx status endpoints
https://circleci.atlassian.net/browse/SERVER-1811
=> docs for single LB and LB status endpoints

jekyll/_cci2/orb-author.md
Afer Kyle's PR I saw this page had a wonky number system for the list items. I also fixed some indenting in the list items as well as moved the videos below the written content.
Numbered list was not continuing in the right order. After seeing the videos live, I think it makes more sense to have the videos below the text content.
=> Fix page indents and number system

jekyll/_cci2/using-arm.md
Fixed broken Canny link for Arm Docker executor support.
Previously this 404'd.
- [na] Break up walls of text by adding paragraph breaks.
- [na] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [na] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [na] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [na] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
=> docs(using-arm): fix typo in canny link

jekyll/_cci2/server-3-operator-metrics-and-monitoring.adoc
This updates the warning message to mention the Prometheus feature explicity, to reduce any potential ambiguity.
I noted that due to the spacing afforded between sections, the warning message around Prometheus not available on KOTS v1.65 - v.167 may be ambiguous (low risk I think, but some readers may think this refers to the section below instead).
Current:
Original PR adding this warning message can be found here:
https://github.com/circleci/circleci-docs/pull/6581
=> Update copy on warning message to refer to Prometheus explicitly

jekyll/_cci2/containers.md, jekyll/_cci2/optimizations.md, jekyll/_cci2/reusing-config.md
* Removed references to the container plan as it is no longer an option.
* Updated the container plan page to push people to migration steps. Once fully deprecated this page will be archived.
=> Deprecating container plans

jekyll/_data/api.yml, src-api/source/includes/_builds_and_jobs.md, src-api/source/includes/_overview.md
Update the retry build command to change from `username` to `org_name`
This was requested by a support engineer
[Jira Ticket](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-328)
=> Update retry a build command in API v1

jekyll/_cci2/add-ssh-key.md, jekyll/_cci2/runner-overview.adoc
- Remove the `add_ssh_keys` step as a known limitation from self-hosted runners. We have confirmed this is working and [added it to our smoke test suite](https://github.com/circleci/launch-agent/pull/333).
- Add a clarifying note on using the `add_ssh_keys` step with a self-hosted runner. 
Jira: https://circleci.atlassian.net/browse/RT-515
=> Remove add_ssh_keys step as a known runner limitation

jekyll/_data/sidenav.yml
- on the new docs platform (deployed last night) we are running into an error where clicking "welcome" in the sidebar causes a too many redirects error. 
- This pr removes the `/2.0/` that we were linking to, and links directly where that would have redirected to `/`.
=> [DD-698] Fix: remove 2.0 from sidebar and link to /

jekyll/_cci2/workflows.md
Change "test" to "build" in git tag workflow example.
It required "build", which was not a defined job for that workflow. I assume "test" was meant?
=> Fix git tag workflows example

jekyll/_plugins/json_data.rb, jekyll/_plugins/json_pages.rb
- Use `dup` to copy the jekyll objects
https://github.com/circleci/circleci-docs/pull/7000 introduced a minor bug that directly alters the jekyll internal objects rather than copying them beforehand. This was introducing a lot of unnecessary extra metadata that was not needed. This is explaining why Algolia refused to `index` our content because the data will be too large:
=> Fix: Do not alter jekyll internal objects directly

jekyll/_cci2/openid-connect-tokens.adoc, jekyll/_cci2/plan-free.adoc, jekyll/_cci2/plan-overview.adoc, jekyll/_cci2/plan-performance.adoc, jekyll/_cci2/plan-scale.adoc, jekyll/_cci2/plan-server.adoc
Adding crowdin tags for O and P adoc pages.
I did not touch some server files because some of the syntax was weird and it wasn't accepting the tags as normal syntax. I will need to sort out whether or not this is an issue.
Adoc files missing crowdin tags.
=> Add crowdin tags for o and p pages

jekyll/_cci2/android-machine-image.md, jekyll/_cci2/docker-to-machine.md, jekyll/_cci2/using-linuxvm.md, jekyll/_data/sidenav.yml
Updating "Using ..." pages for all execution environments to standardise how this information is formatted and presented. This is the Linux VM PR, there will be a PR for each execution environment.
[A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.](https://circleci.atlassian.net/browse/DOCSTEAM-326?atlOrigin=eyJpIjoiYmYxYzVkNDRiZTlkNGQxOWJhYTIzMDIxMzgyNjJkODAiLCJwIjoiaiJ9)
=> updates to standardise execution env use pages - linux VM

jekyll/_cci2/orb-author.md
- Add orb dev kit section to orb author page.
- Clarify what the kit actually is.
[Jira](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-353)
We have a bunch of places in our docs that were linking to a section on the orb authoring page that did not exist. I created this section both to have a valid link as well as expand on what the orb dev kit actually is as the definition was fairly convoluted.
=> Add orb dev kit section

jekyll/_cci2/webhooks.md
Clarify webhook duplicates and how to deduplicate requests
Jira ticket [EXT-271](https://circleci.atlassian.net/browse/EXT-271)
This comes from a support ticket where the customer was confused why they were seeing duplicate requests
=> [EXT-271] Clarify webhook duplicates

jekyll/_cci2/runner-overview.adoc
I'm fairly sure this is wrong:
from: https://circleci.com/docs/2.0/runner-overview
I believe my PR makes this part of the docs more readable.
=> Fix list nesting in self-hosted runner docs

jekyll/_cci2/configuration-reference.md, jekyll/_cci2_ja/configuration-reference.md
The Ubuntu Machine Executor image ubuntu-2004:2022.04.1 states that it is Ubuntu 22.04, but it is 20.04.
Confirmed via this job: https://app.circleci.com/pipelines/github/Chekote/BehatRetryExtension/18/workflows/7936a3df-4143-4b38-bfc6-eaba52ba8bc3/jobs/62
Pull Request https://github.com/circleci/circleci-docs/pull/6825 added additional images to the docs, and it seems that the lines were copy-and-pasted, but only the tag was updated on the newly pasted line. Unfortunately, the Ubuntu version seems to have been overlooked.
Correct the error so that the correct Ubuntu version is stated.
=> Fix ubuntu-2004:2022.04.1 image incorrectly states Ubuntu 22.04

jekyll/_cci2/building-docker-images.md, jekyll/_cci2/docker-compose.md, jekyll/_data/sidenav.yml
* moved the docker compose docs out of the execution environments section and into the configuration how-to section
* Removed the DLC page from the execution environments section - it's an optimization feature rather than executor usage
* updated the building-docker-images page because there were some obvious issues and the flow of the doc was confusing
[A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.](https://circleci.atlassian.net/browse/DOCSTEAM-371?atlOrigin=eyJpIjoiYWQ1NmFlYWZlN2VlNDIzNzk1N2U5YWUzMDRkM2E2OWMiLCJwIjoiaiJ9)
Please take a moment to check through the following items when submitting your …
=> Docsteam 371 move content out of execution envs

jekyll/_includes/snippets/built-in-env-vars.md
After checking in with our Engineering team, we noticed that the definition of this CIRCLE_PREVIOUS_BUILD_NUM built-in environment variable (env var) was incorrect.
A customer has reached out, observing this CIRCLE_PREVIOUS_BUILD_NUM env var is not present in their builds.
We need to update the doc to say that this env var is not always present and depends on the workflow which the job is running in.
Importantly, we want to alert users that this env var is not necessarily present, and not deterministic.
Ideally, we would like to ask users to avoid using it, as our goal would be to deprecate it.
Please take a moment to check through the following items when submitting your …
=> docs: update definition of CIRCLE_PREVIOUS_BUILD_NUM env var

jekyll/_cci2/ip-ranges.md
Three new IP CIDRs have been provisioned for use by MacOS VMs in our data center.
- 38.23.38.0/24
- 38.23.39.0/24
- 38.23.40.0/24
https://circleci.atlassian.net/browse/MAC-1147
=> Update ip-ranges.md with newest MacOS VM CIDRs

jekyll/_data/sidenav.yml
Add [Sign Up](https://circleci.com/docs/first-steps) to **Getting Started** section, under **Overview**
The Sign Up page was only navigable from the docs homepage and not the sidenav. 
=> Add Sign Up page to side nav

jekyll/_cci2/api-developers-guide.md
Adjustment to the verbiage of the Onboard project section to match other similar documentation.
[EXT-446](https://circleci.atlassian.net/browse/EXT-446)
The original description failed to encapsulate the change in the org and project name in the url to org id for gitlab updates. Now doc matches style of other documentation and should be easier to maintain if the url structure varies again.
=> Gitlab GA update to API doc

.gitignore, jekyll/_cci2/server-3-install-build-services.adoc, jekyll/_cci2/server-3-install-prerequisites.adoc, jekyll/_cci2/server-3-install.adoc, jekyll/_data/sidenav.yml
- Remove internal links that have `index.html` in it
- Cleanup `sidenav.yml` where one link had an extra `/` 
Some internal links have `index.html` in them which triggers an extra set of redirects to route the user to the right place. This PR removes them to optimize users' experience.  
=> [DD-747] Remove links with `index.html` in it

jekyll/_cci2/collect-test-data.md
Jest example is being changed to remove the folder as it causes issues
A customer has explained with examples that setting the folder in that way causes issues.
https://circleci.zendesk.com/agent/tickets/112947
They have also explained that this is outlined in the following support article
https://support.circleci.com/hc/en-us/articles/360021624194?input_string=store_test_results+with+jest+shows+no+results+in+the+%22tests%22+tab+despite+valid+junit.xml
N/A formatting is not changed
=> Change jest example to remove ./reports/junit/

jekyll/_cci2/introduction-to-yaml-configurations.adoc
config.yaml replaced with config.yml
A customer was using config.yaml and it broke their config
https://circleci.zendesk.com/agent/tickets/113201
N/A only text changes
=> We do not support config.yaml only config.yml

jekyll/_cci2/workflows.md
Removed outdated embedded YouTube videos.
The videos were from 2018 and show some outdated examples.
=> Remove outdated videos

jekyll/_cci2/server/installation/migrate-from-server-3-to-server-4.adoc, jekyll/_cci2/server/operator/using-metrics.adoc
By default we ship with telegraf which provides aggregated component metrics in prometheus format. The telegraf pod can be scraped if needed but including Prometheus as part of the server stack is out of scope so let's leave it disabled.
https://circleci.atlassian.net/browse/SERVER-1954
=> [SERVER-1954] Remove references to prometheus

Gemfile, Gemfile.lock, jekyll/_plugins/json_pages.rb
Ticket: [DD-734](https://circleci.atlassian.net/browse/DD-734)
- Use `HTMLEntities.new.decode` on the document title before it goes to the JSON file
In Asciidoc, titles are automatically escaped with HTML encoding which is then reflected on the site. This PR forces to decode the title before writing it to the HTML. More info here: https://docs.asciidoctor.org/asciidoc/latest/subs/replacements/
=> [DD-734] Add `HTMLEntities` to force decoding html character

jekyll/_cci2/runner-faqs.adoc
Just realized I missed this bit in [my last PR](https://github.com/circleci/circleci-docs/pull/7097) about getting runner tokens for deletion which doesn't make much sense in context of the simplified resource class deletion method...
Jira: https://circleci.atlassian.net/browse/RT-295
=> Remove reference to tokens for deleting Runner resource class

jekyll/_cci2/server/installation/phase-1-prerequisites.adoc
Some [regions require the location constraint ](https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html#options)
We had it before, and I removed it in a[ pervious PR](https://github.com/circleci/circleci-docs/pull/6995/files#diff-234110c59a9f2eea648e2f961c2225034458b3ab97213eeb92eeb04ba3bfc988L379)
also some whitespace cleanup
=> [SERVER-1962] include location constraint on bucket creation

jekyll/_cci2/artifacts.md, src/styles/prism/_theme.scss
[DD-763](https://circleci.atlassian.net/browse/DD-763) 
This was discovered during our QA mob session. Please refer to the [mob session spreadsheet](https://docs.google.com/spreadsheets/d/1woo91rYq34wdePSnxfJYMpGzeTfX1KUu3Pu809bc2ZY/edit#gid=1786852033) for examples of pages that are impacted by that issue.
We want to fix some prism display issues.
=> [DD-763] Prism wrapping / scrolling: change capital C to little c

jekyll/_cci2/configuration-reference.md
This is to clarify that an already failing job will still fail when calling `circleci-agent step halt`
Clarification of `step halt`.
The current wording is misleading and implies that `step halt` will cause a job to result in `Success` even if a step is already failing. This is not the case, and the job will still fail.
- [*] Break up walls of text by adding paragraph breaks.
- [*] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [*] Keep the title …
=> Clarification on "without failing"

jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
This PR adds in an AWS command that creates an ingress rule between the spun up VMs of VM service in EC2, and the nomad clients' subnet CIDR range.
This is a necessary requirement for VM service to work.
=> Add in AWS command to create SSH rule between VM service instances and nomad clients

jekyll/_cci2/triggers-overview.adoc
This commit fixes the URL for triggering a pipeline with the API which points to a 404 Page not found.
Self explanatory
=> Fix Bad URL reference in Trigger Overview page

jekyll/_cci2/selecting-a-workflow-to-run-using-pipeline-parameters.adoc
Update curl command to use double quotes as single quotes are not compatible with Windows. (the -d should fix the one line that still uses single quotes).
[Issue 7133](https://github.com/circleci/circleci-docs/issues/7133)
=> Update curl command/resolve issue 7133

jekyll/_cci2/runner-installation-cli.adoc, jekyll/_cci2/runner-installation-mac.adoc
Update the working directory created by the install script to match to the default used elsewhere in the install instructions. Also add a section detailing how to give this directory the correct permissions on MacOS
An internal user was attempting to follow the MacOS install instructions and ran into a permission error
=> Update launch agent install instructions on macos

jekyll/_cci2/browser-testing.md
Change config version to 2.1 for Selenium code example.
Change the config version to 2.1 for Selenium code example as well as adding newlines.
The other code examples on the page reference version: 2.1 and it would be good to unify all of the examples.
=> Update browser-testing.md code example to use version:2.1

jekyll/_cci2/server/installation/phase-2-core-services.adoc
Replacing Docker Hub with Azure, but not being overly specific because public images are still hosted in Docker Hub.
https://circleci.atlassian.net/browse/SERVER-2007
=> Do not reference Docker Hub anymore

jekyll/_cci2/server/installation/phase-1-prerequisites.adoc
We have (and may have more) customers that need to terminate TLS outside the CircleCI application. Adding brief instructions on which CircleCI service binds to which ports to hopefully make this type of TLS configuration a bit less cryptic.  
- [SERVER-2000](https://circleci.atlassian.net/browse/SERVER-2000)
=> [SERVER-2000] Add information about upstream TLS termination

jekyll/_cci2/server/installation/phase-1-prerequisites.adoc
Earlier versions will throw an error like this (seen on v1.21):
```
Error: INSTALLATION FAILED: Kubernetes cluster unreachable: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```
=> Minimum k8s version is 1.22 for server 4.0

jekyll/_cci2/server/operator/configuring-external-services.adoc
We had mongo specified twice by accident, causing some tab issues
=> Specify postgres in the right place

jekyll/_cci2/server-3-install-build-services.adoc
Adds a note on the hard requirement for the EKS service account name to be `vm-service`.
Currently, this `vm-service` name is hard-coded on CircleCI's end, so users would need to ensure they create a EKS service account with the same name.
Addresses https://circleci.atlassian.net/browse/DOCTEAM-394
=> docs: add requirements on EKS service account name

jekyll/_cci2_ja/concepts.md
Fix for removing unnecessary p-tag. 
This was determined to be unnecessary because only the end of the P tag remained.
I have confirmed that the `</p>` does not show up in the markdown preview on GitHub, but `</p>` does show up on https://circleci.com/docs/ja/concepts.
https://circleci.com/docs/ja/concepts#configuration
=> Fix: remove unnecessary p-tag

jekyll/_cci2/server/operator/configuring-external-services.adoc
new customers are not presented the option to use external vault
for existing customers we have internal docs on how to support them [here](https://support.circleci.com/hc/en-us/articles/7705503434011?page=1#comment_7706384164507)
=> [server-2019] remove external vault docs

jekyll/_cci2/server-3-install.adoc
The start of a link to a page that does not exist yet was left in a server three install doc. This PR points the link to the section on the page instead.
https://circleci.atlassian.net/browse/DOCTEAM-702?atlOrigin=eyJpIjoiMDYwNGViNzYyYWQ5NGQ3ZWI4OWFlZjZkMmE3NDk1ZWIiLCJwIjoiaiJ9
=> Fix incorrect link

jekyll/_cci2/server/installation/installation-reference.adoc
The tricky part is specifying the org as null
and we don't want customers to be confused.
(Also some whitespace)
Question: do we want to just specify `<registry>` and it will be provided to them? I'm unclear how much information is provided them with the license.
=> Specify the registry for server 4.x installs

jekyll/_cci2/server/installation/phase-2-core-services.adoc
An update to the upstream TLS termination section was missed the first time around. Adding the small changes to this PR to stay consistent with what we have in the pre-reqs section. See https://github.com/circleci/circleci-docs/commit/37129734ed021c9ec53677546d651e1f4f030139.
- [SERVER-2000](https://circleci.atlassian.net/browse/SERVER-2000)
=> [SERVER-2000] Update info for upstream TLS termination (core instructions)

jekyll/_cci2/using-windows.md
There was no Windows support in server 2.x
There was also no config processing (the 2.1 syntax)
=> Windows was not available in server 2.x

jekyll/_cci2/runner-installation-linux.adoc
- Update the Linux runner to use more conventional file locations:
- `circleci.service`: `/usr/lib/systemd/system/circleci.service`
- `launch-agent-config.yaml`: `/etc/opt/circleci/launch-agent-config.yaml`
- SELinux policy (for RHEL): `/etc/opt/circleci/policy/` 
- Task agent working directory: `/var/opt/circleci/workdir`
- Launch agent binary: `/opt/circleci/circleci-launch-agent`
- Run launch agent as the `circleci` user so that it doesn't require root privileges
- Move the step to verify the launch agent service to the end of the section for creating and running the systemd service as it's dependent on it
- Update the relevant systemctl commands that need sudo
- Add a step for starting launch agent while pointing to the optional instructions of running it as a systemd service daemon …
=> Update the runner Linux installation docs

jekyll/_cci2/using-windows.md
Reverts circleci/circleci-docs#7243
Turns out I was wrong: 
https://github.com/circleci/server-manifest/blob/de7dc0ab9eb60e44c65c3135a3dc0aede3d4183c/rcli/templates/replicated_yml_template/components/vm_service.yml#L147-L151
It's not clear to me if anyone was able to actually use this feature though because we didn't provide a Windows image builder at the time.
I also noticed we need a 4.x tab on this page now :(
=> Revert "Windows was not available in server 2.x"

jekyll/_cci2/configuration-reference.md
Move "Using `when` in Workflows" to under "<`workflow_name`>" section.
The `when` clause is used to determine whether or not to run that workflow. So it should under "<`workflow_name`>" section.
=> Move Workflow `when` section to current nav section

jekyll/_cci2/configuration-reference.md
Update the list of Ubuntu Machine images to include newer images for 2022 July Q3 updates.
See https://discuss.circleci.com/t/linux-machine-executor-update-2022-july-q3-update/44873 for more info.
=> add 2022.07.1 Ubuntu images

jekyll/_cci2/executor-intro.md
Add a banner on macOS and GPU section of page to clarify it's not compatible with server. This is a temporary solution until we have tagging in place.
Not enough clarity on whether or not someone can use certain builds with server because the page tags indicate the content is for both cloud and server.
[Jira ticket](https://circleci.atlassian.net/jira/software/c/projects/DOCTEAM/boards/554?modal=detail&selectedIssue=DOCTEAM-444)
=> Clarify server use, minor fixes

jekyll/_cci2/glossary.adoc
Remove the "Authentication" entry from the glossary page. Also fixed some capitalization.
This entry was out of date. After looking at other places where we talk about authentication in the docs, it is not always in reference to VCS authentication (which is what the entry specified). Presumably authentication will further change as we continue with the work on GH, BB and GL.
[Jira ticket](https://circleci.atlassian.net/jira/software/c/projects/DOCTEAM/boards/554?modal=detail&selectedIssue=DOCTEAM-397)
Please take a moment to check through the following items when submitting your PR (this is just a …
=> Remove authentication entry

jekyll/_cci2/env-vars.md
Correct "Alpine Linux environment variables with bash" configuration example.
The environment should be a Map, instead of array of map.
=> Correct Alpine Linux environment variables configuration example

jekyll/_cci2/server/installation/migrate-from-server-3-to-server-4.adoc
No Jira
We removed the need for using az.
(and trailing whitespace got trimmed)
=> `az` is no longer a prereq

jekyll/_data/sidenav.yml
Change sidenav items to sentence case.
Left PDF doc titles alone.
Standardization. 
[Jira ticket](https://circleci.atlassian.net/browse/DOCTEAM-728)
=> Sentence case for sidenav

jekyll/_cci2/config-policies.md
Adjusted the resource_class_by_project example to use `check_resource_class` as the var instead of `ban_orbs_versioned`.
Fixing a type
=> fix resource_class_by_project example var

jekyll/_cci2/browser-testing.md, jekyll/_cci2/contexts.md, jekyll/_cci2/custom-images.md, jekyll/_cci2/docker-layer-caching.md, jekyll/_cci2/env-vars.md, jekyll/_cci2/ios-tutorial.md, jekyll/_cci2/oss.md, jekyll/_cci2/postgres-config.md, jekyll/_cci2/ssh-access-jobs.md, jekyll/_cci2/testing-ios.md, jekyll/_cci2/using-shell-scripts.md, jekyll/_cci2/workflows.md
- Removes "...in the following sections:" from page introductions.
- Also removes the no_toc tag from the Overview heading so that it is also included in the right hand side nav / toc.
- A few minot text edits.
Previously, we had this phrase in some doc intros as a lead in to a table of contents. We have since moved the TOC to the right hand nav, and no longer need this phrase.
[Jira ticket](https://circleci.atlassian.net/browse/DOCTEAM-484)
=> Remove 'in the following sections' from intro

jekyll/_cci2/config-policies.md
- Add `cimg` and required import to docker image example
- Removed unnecessary imports from orb examples 
Include new image namespace in example and remove any unnecessary imports to reduce any confusion.
=> Example fixes

jekyll/_cci2/server/installation/hardening-your-cluster.adoc
Adding in docs highlighting the caveats when dealing with public / private IPs assigned to VMs, and how to secure the cluster in both situations.
SERVER-1992
=> [SERVER-1992] Expand on VM networking using public and private IPs

jekyll/_cci2/ssh-access-jobs.md
- Change RSA to ed25519 in examples on page.
- Changed the format of the page a little and fixed some other minor errors.
This is GH's directive on what they think is best/most secure.
These changes were made in another PR that got stuck in a build.
[Jira ticket](https://circleci.atlassian.net/jira/software/c/projects/DOCTEAM/boards/554?modal=detail&selectedIssue=DOCTEAM-755)
=> Change rsa to ed25519

jekyll/_cci2/server/overview/release-notes.adoc
I couldn't get some links working for the server release yesterday so I removed them. I now see where my error was so this fixes them.
=> add links in to server 4 release notes

jekyll/_cci2/databases.md, jekyll/_cci2/deploy-service-update-to-aws-ec2.adoc, jekyll/_cci2/env-vars.md, jekyll/_cci2/openid-connect-tokens.adoc, jekyll/_cci2/orb-author-faq.md, jekyll/_cci2/sample-config.md
Place double quotes around env var names in BASH_ENV examples
Also add comment explaining why `source`  might included in code example
If any of the variables contain spaces or special characters in them, adding double-quotes in the right places will ensure that any spaces or special characters are properly escaped.
[Jira ticket](https://circleci.atlassian.net/browse/DOCTEAM-559)
=> Update BASH_ENV code examples

jekyll/_cci2/runner-overview.adoc
this link doesn't work: "<<#docker-to-machine,machine execution environment>>"
=> this link doesn't work

jekyll/_cci2/first-steps.md
- Remove signup buttons that were part of a Docs Disco experiment.
- Add a section for signing up with GitLab.
- Modify Sign up with email instructions as there is actually some overlap with the email signup process and GitLab signup.
GitLab integration is GA and this page needed to be refreshed.
Docs Disco will also be creating components that can be reused as CTAs on pages such as these so the code from the experiment is no longer needed.
=> Remove experiment and add GitLab signup steps

jekyll/_cci2/circleci-images.md
A reader reported that the language around pre-installed packages in convenience images was ambiguous. This PR fixes that and a few other formatting and style bits.
* Removed list of images and replaces with a link to the dev hub
* Removed `no_toc` so all sections are visible in the right hand TOC
https://circleci.atlassian.net/browse/DOCTEAM-512?atlOrigin=eyJpIjoiODE0YjNlMzFiOGFjNGFjNThiZmJlNWFkNWIzZGYxMDYiLCJwIjoiaiJ9
=> clear up that docker compose is pre-installed and a few formatting fixes

jekyll/_cci2/server/installation/phase-2-core-services.adoc
Adding a helper command for generating random alphanumeric strings which can be used for the various secrets. Placing this in the "core services" section right below the api-key.
- [SERVER-1948](https://circleci.atlassian.net/browse/SERVER-1948)
=> [SERVER-1948] Add random string command

.gitignore, jekyll/_config.yml, scripts/frontmatter_tagging/frontmatter_tagging.py, scripts/frontmatter_tagging/frontmatter_template_tags.j2
[DD-841](https://circleci.atlassian.net/browse/DD-841)
Wrote a script that:
1. Traverses adoc and md files inside of _cci2 and _cci2_ja
2. Checks if version metadata exists
3. Rewrites file in temporary folder with new format
In preparation of allowing content tagging to exist in all files
1. Navigate to scripts/frontmatter_tagging in terminal
2. run `python3 ./frontmatter_tagging.py`
Test files:
`_aws-install.adoc` ---> has no existing front matter
` about-circleci` ---> has version in front matter and other keys
` storage-lifecycle.adoc` ---> only has version in front matter
`v.2.18-overview.md` ---> does not have version in front matter
Also do various 'spot' checks
1. This is a Draft PR until testing can be done in `docs-platform` 
2. Files are rewritten as EditFrontMatter will not …
=> [DD-841] write a script that transforms all the current doc files frontmatter

jekyll/_cci2/server/installation/phase-2-core-services.adoc
Documents a limitation when using AWS IAM keys, a S3 backend, and MinIO that causes uploads of greater than 5GB to fail. Workaround/recommendation is to use IRSA.
[SERVER-2071]
[SERVER-2071]: https://circleci.atlassian.net/browse/SERVER-2071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Documenting MinIO Uploads - 5GB Limit

jekyll/_cci2/runner-overview.adoc
Fix small typo in the `Getting started` section of [this](https://circleci.com/docs/runner-overview#machine-runner-use-case) page:
Typo.
=> fix: typo in the runner overview page

jekyll/_cci2/using-docker.md
The "mongod, --smallfiles" are for a MongoDB Daemon arguments and are incompatible with MariaDB
When users attempt to try out the example code "as is", the incompatible entrypoint args will potentially cause the MariaDB service container to fail on startup.  The fix will resolve the issue.
=> Removed incompatible entrypoint arguments

jekyll/_cci2/workflows.md
This PR fixes a typo in the `canceled` state of a workflow.
The correct value is `canceled` and not `cancelled`.
We spotted this error while checking the status of a workflow. We had followed the docs with `cancelled` (with 2 `l`s) but it turned out that the real value was `canceled` (with 1 `l` only).
=> Fix typo in canceled state of workflow

jekyll/_cci2/container-runner.adoc
Add documentation for the custom token secret feature in the container agent helm chart
Documentation supporting this feature: https://circleci.atlassian.net/browse/RT-703
=> [RT-703] Add documentation for container agent custom token secret

jekyll/_cci2/api-developers-guide.md, jekyll/_cci2/api-intro.md, jekyll/_data/sidenav.yml
Our docs currently mention basic auth (by passing in the API token as the username, no password) but do not specify that this can be used only with public repositories. 
If the basic auth method is used with private repositories, it will return a 404 error "Project not found".
[Jira ticket](https://circleci.atlassian.net/browse/DOCTEAM-761)
=> Clarify basic auth for API v2

jekyll/_cci2/container-runner.adoc
The runner team has migrated the container agent helm chart to a new repository. This updates the install instructions to use the new repository
https://circleci.atlassian.net/browse/RT-700
=> [RT-700] Update container agent helm chart to point at new package cloud repo

jekyll/_cci2/configuration-reference.md
Removes hardcoded lists of Linux and Windows GPU images and directs readers to Dev Hub.
The Linux CUDA list remains for now as there is no available reference in the Dev Hub.
The config reference currently has to be updated every time a new image is available, and this is becoming increasingly difficult to maintain. 
[Jira ticket](https://circleci.atlassian.net/browse/DOCTEAM-747)
=> Clean up machine images list in config reference

jekyll/_cci2/runner-config-reference.adoc, jekyll/_cci2/runner-installation-linux.adoc, jekyll/_cci2/runner-installation-mac.adoc
Update the RUNNER_NAME description on the Mac and Linux install pages, as well as in the config reference.
closes #7429 
The Mac install page was missing information about RUNNER_NAME and AUTH_TOKEN. The other pages just needed a minor update for more clarity.
=> Update RUNNER_NAME description

jekyll/_cci2_ja/orb-development-kit.adoc
Fixes broken link here:
[Orb  テンプレート](https://github.com/CircleCI-Public/Orb-Template)
Link was broken, gave a HTTP 404 error.
=> Fix a broken link to the orb template repository

jekyll/_cci2/pipeline-variables.md
This fixes the example as I ran into the issue when trying this just now
I ran into this issue just now and we have updated the latest tag to now be current so the build fails when using the example.
=> The latest tag no longer exists its now current

jekyll/_cci2/container-runner-installation.adoc
A tiny PR to fix the instructions for installing the Helm chart for container Runners.
The Helm repo for our container Runners was added as per:
```shell
helm repo add container-agent https://packagecloud.io/circleci/container-agent/helm
```
As such, the Helm repo's name would be `container-agent` , not `circleci`. The Helm chart would thus also be found under `container-agent/container-agent` , not `circleci/container-agent`.
```console
$ helm repo list
NAME           	URL
container-agent	https://packagecloud.io/circleci/container-agent/helm
$ helm show chart container-agent/container-agent
apiVersion: v2
appVersion: "3"
description: For deploying a CircleCI Container Agent
icon: https://raw.githubusercontent.com/circleci/media/master/logo/build/horizontal_dark.1.png
name: …
```
=> fix: correct Helm repo name

jekyll/_api/v1-reference.md, src-api/source/includes/_overview.md
The plan field given in this example is not meaningful since container plans have been deprecated and as such we shouldn't be including it in examples, even though the example here doesn't have anything to do with the plan; it could be misinterpreted as committing to support this field.
The `plan` field here is based on data which we are intending to shut off in the future: https://circleci.atlassian.net/browse/MONEY-2924
=> MONEY-2924 Remove mention of the plan field in api-key example.

jekyll/_cci2/collect-test-data.md
Removing the alternative example for storing test results with the .cucumber file format.
The Cucumber file format was previously accepted for processing when Cucumber did not support JUnit formatting.  As part of upcoming changes to test results processing, the Tasks team is looking to consolidate our recommendations to use JUnit formatting exclusively, which is consistent with our examples for other test runners.
=> Remove example for .cucumber file format

jekyll/_cci2/style/using-images.adoc
Minor update to last week's PR to add more detail regarding pixel widths.
Was waiting on some final details from design to clear up some guidelines.
=> Add pixel widths to style guide images

jekyll/_cci2/server/installation/phase-3-execution-environments.adoc, jekyll/_cci2/server/operator/manage-virtual-machines-with-vm-service.adoc
Docs for VM service in server 4 need improvements, and there are some missing sections:
https://circleci.atlassian.net/browse/DOCTEAM-779?atlOrigin=eyJpIjoiMjI4YjU2YzZjMTdiNDY5MmI3ZWExYmY3ZDlmYjM5ZjQiLCJwIjoiaiJ9
=> Improvements to server 4 VM service docs

jekyll/_cci2/runner-faqs.adoc
Adding information to the runner FAQ about authorization precedence and IAM role configuration for container runner
A customer ran into an issue where how the precedence for authorization was not clear https://circleci.slack.com/archives/C0306RYMR8D/p1666881989011949?thread_ts=1666632048.029859&cid=C0306RYMR8D
=> add information about ECR auth precidence for container runner

jekyll/_cci2/server/operator/expanding-internal-database-volumes.adoc
Adds instructions for resizing redis cluster PVCs.
Due to redis disk persistence, it is sometimes necessary to resize redis PVCs for the cluster.
=> [SERVER-2134] Instructions for resizing redis PVC

jekyll/_cci2/testing-ios.md
Update Ruby info in iOS testing doc to reflect current image support. Also bumped version numbers and tidied the NodeJS TOC section to make it cleaner.
The oldest image we now support is Xcode 11.7, therefore a lot of the old documentation is no longer relevant. We will be switching to rbenv shortly, so needed to tidy the chruby based information in advance.
=> Update Ruby info in iOS testing doc

jekyll/_cci2/deploy-ios-applications.md, jekyll/_cci2/testing-ios.md
* Add in config.yml for integrating projects with Fastlane to the start of the iOS deploy page.
* Also removed some `no_toc`s from the testing iOS page
Relevant thread: https://circleci.slack.com/archives/CEX928FM3/p1667218438678789
https://circleci.atlassian.net/browse/DOCTEAM-807?atlOrigin=eyJpIjoiNjA1MDFmYjhkZmU0NDEyMGFiZDlmZDJhMTZmNGU3MjQiLCJwIjoiaiJ9
=> add section detailing CCI config for Fastlane deployment examples

jekyll/_cci2/config-policy-management-overview.adoc, jekyll/_cci2/use-the-cli-and-vcs-for-config-policy-management.adoc
Adding documentation for `settings` sub-command under `policy` command.
https://circleci.atlassian.net/browse/SECENG-853
=> [SECENG-853] Adding documentation for `settings` sub-command

jekyll/_includes/snippets/xcode-intel-vm.md
RC 2 has been promoted to Release by Apple. We therefore do not need to build a new image for the Release version of Xcode 14.1. Updating the table accordingly
=> Promote Xcode 14.1 RC 2 to Release

jekyll/_cci2/testing-orbs.md
This PR fixes a minor typo (ran vs. run), and while there changes `JUNIT` to `JUnit`, which is how the JUnit project refers to itself.
Improve quality!
=> chore(docs): Fix typo

jekyll/_cci2/container-runner-installation.adoc, jekyll/_cci2/runner-installation-linux.adoc, jekyll/_cci2/runner-installation-mac.adoc, jekyll/_cci2/runner-installation-windows.adoc, jekyll/_cci2/troubleshoot-self-hosted-runner.adoc
Update code snippet in t[roubleshooting step](https://circleci.com/docs/troubleshoot-self-hosted-runner/#i-installed-my-first-self-hosted-runner-on-macOS-and-the-job-is-stuck-in-preparing-environment-but-there-are-no-errors-what-should-i-do) with correct filepath.
Also adds links to Troubleshoot self-hosted runner page from platform-specific installation docs.
[Jira ticket](https://circleci.atlassian.net/browse/DOCTEAM-823)
The launch-agent installation script does not make circleci-launch-agent executable by root, which is necessary for the `launchd` service to start the launch-agent. When running a job, it gets stuck at the "Preparing environment" step.
The troubleshooting step is linked on the sidenav, but isn't necessarily easy to find as the reader is going through the actual install …
=> Troubleshooting runner install on M1 macOS

jekyll/_cci2/server/installation/installation-reference.adoc
[edited]
~This is to document how to add the GitHub Enterprise (GHE) defaultToken.~
I noted the defaultToken for GHE is missing from the installation reference's table:
https://circleci.com/docs/server/installation/installation-reference/#all-values-yaml-options
Our document **already** informs the admin to create & add this personal access token on their GHE instance:
- https://circleci.com/docs/server/installation/phase-1-prerequisites/#github-enterprise
- https://circleci.com/docs/server/installation/phase-2-core-services/#github-enterprise-integration
I noted the defaultToken is missing from the installation reference's table:
https://circleci.com/docs/server/installation/installation-reference/#all-values-yaml-options
Please follow our style when contributing to CircleCI docs. Our …
=> docs: add notes on GHE defaultToken

jekyll/_cci2/collect-test-data.md
CMake is one of the most popular build systems for C and C++ projects. Recently, I learnt that CTest can output JUnit test results that CircleCI can ingest and we are using it for one of our internal projects at Postman.
I wasn't able to run the docs locally, but I think these changes are a good start for documenting how it works.
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>
=> Document collecting tests results for CMake / CTest projects

jekyll/_cci2/container-runner.adoc
Added ` to URL to remove the clickability since the link leads to a 404. 
The link lead to a 404
=> Remove click-ability on 404 URL

jekyll/_cci2/server/installation/phase-1-prerequisites.adoc
We can now recommend a tighter scoped k8s user for customers to install and administer server
Also I removed the section about permissions around pods as that is not completly accurate, the users needs more than just full control of the pods.
Auto fixed some extra whitespace
=> [SERVER-2167] add namespaced admin permission recomendation

jekyll/_cci2/openid-connect-tokens.adoc, jekyll/_cci2_ja/openid-connect-tokens.adoc
Added the `--no-cli-pager` flag to the `aws sts get-caller-identitiy` command example so that the job won't hang indefinitely.
This will create a better customer experience to avoid having the aws command causing the job to hang indefinitely.
=> No cli pager fix

jekyll/_cci2/orbs-faq.md
Update language in [Orbs FAQ doc](https://circleci.com/docs/orbs-faq/#report-an-issue-with-an-orb) so that only public orbs are indicated to be open source.
This PR does not make changes to any applicable text within the Dev Hub.
[Jira ticket](https://circleci.atlassian.net/browse/DOCTEAM-850)
Existing language is misleading and implies that private orbs are also open source and CircleCI owns private orb code under the MIT license.
Docs Disco (in collaboration with CPE) will address the changes needed for the Dev Hub.
Please take a moment to check through the following items when submitting your …
=> Clarify that only public orbs are open source and licensed to CircleCI under MIT

jekyll/_cci2/openid-connect-tokens.adoc
Added the missing mapping `attribute.org_id` -> `assertion.aud` to the GCP OIDC setup docs.
Encountered errors due to the missing field
=> Include missing required attribute mapping

jekyll/_cci2/ip-ranges.md
The MacOS Team is adding three additional subnets for MacOS executors:
- 38.23.41.0/24
- 38.23.42.0/24
- 38.23.43.0/24
[Jira Ticket](https://circleci.atlassian.net/browse/MAC-1372)
=> Update IP Ranges for MacOS Cloud [MAC-1372]

jekyll/_cci2/caching.md
Replaced duplicated cache keys with anchor (`&cache-key`) and reference (`*cache-key`)
To encourage users to reduce duplication and makes it easier to maintain confing.
=> Use anchor/reference to reduce duplication in cache keys

jekyll/_cci2/parallelism-faster-jobs.md
Adds additional information regarding the `--timings-type` flag and its corresponding values.
The current documentation briefly mentions the `--timings-type` flag but stops short of including valid flag values. This PR expands on the existing documentation and includes known flag values.
=> Update test splitting documentation

jekyll/_cci2/config-policy-management-overview.adoc, jekyll/_cci2/config-policy-reference.adoc, jekyll/_cci2/use-the-cli-and-vcs-for-config-policy-management.adoc, jekyll/_cci2/use-the-cli-for-config-and-policy-development.adoc
This PR adds a caution banner on config policy management doc pages, notifying the readers that it should **not** be used for compliance purposes during the open-preview stage.
https://circleci.atlassian.net/browse/SNC-30
=> [SNC-30] Adding caution about open-fail behavior in open preview stage

.circleci/config.yml
Remove unused minimize-img deploy step
This step is not useful anymore because images are imported as submodule into nextjs. NextJS does an optimization itself too anyway - via Romain
=> Fix min img step

jekyll/_cci2/executor-intro.md
Fix indentation in executor examples.
Copying and pasting the examples would give users problems.
=> Fix indentation in executor examples

jekyll/_cci2/parallelism-faster-jobs.md
"```"seems to have been accidentally deleted in the last PR ([#7577](https://github.com/circleci/circleci-docs/pull/7577))
Screenshot:
=> Revert ``` that was accidentally deleted

jekyll/_cci2/configuration-reference.md
Add section for Android machine image in config reference. The section links out to the image page on Dev Hub.
It also mentions that there are two methods for using the Android image (the other using the Android orb).
[Jira ticket](https://circleci.atlassian.net/browse/DOCTEAM-480)
The Android image was missing from the config reference.
=> Add Android machine images to config reference

jekyll/_cci2/orb-development-kit.adoc
Fix the orb init and orb pack links to match the corresponding descriptions. They were switched.
The links are backwards as seen here: https://circleci.com/docs/orb-development-kit/
=> Fix init and pack links which have incorrect description

jekyll/_cci2/hello-world-macos.md
* Updated the corresponding demo app repo config to use latest Xcode, and remove unnecessary workflows version: https://github.com/CircleCI-Public/circleci-demo-macos
* Fixed config example formatting
* Linked to "supported Xcode versions"
https://circleci.atlassian.net/browse/DOCTEAM-855?atlOrigin=eyJpIjoiMDJlYWY4MTBkOTIxNDdkNTgxZjA5NmIyYmE3ZTM1NDAiLCJwIjoiaiJ9
=> fix macOS code snippet formatting

jekyll/_cci2/runner-config-reference.adoc
While investigating some runner issues, I discovered that the env var for disabling auto update is incorrect, and the env var for specifying whether the working directory should be cleaned is missing.
This can be verified from running help on the latest version of launch-agent:
```
Usage: circleci-launch-agent
This is the launch agent for CircleCI runner. It is responsible for bootstrapping the task agent.
For more information on configuring CircleCI runner, visit https://circleci.com/docs/2.0/runner-config-reference/.
Flags:
-h, --help                                     Show context-sensitive help.
-c, --config="launch-agent-config.yaml"        Path to configuration YAML file.
-v, --version                                  Print version information and quit. …
```
=> Fix env var configuration in Runner config ref

jekyll/_cci2/container-runner.adoc
Due to an upstream issue with the latest `Buildah` image and building images, this PR pins the Buildah version to the last working version with container-agent. See: https://circleci.atlassian.net/browse/RT-838?focusedCommentId=233319
https://circleci.atlassian.net/browse/RT-838
=> [RT-838] Pin Buildah image version to `v1.27.0`

jekyll/_cci2/runner-faqs.adoc
There's a difference between cloud and runner where cloud, for backward compatibility reasons, injects symlinks to the `circleci-agent` binary with the aliases `circleci` and `picard`, but these are all the same binary. Runner doesn't support this and only has the `circleci-agent` on the path. This adds an FAQ to help clear up this difference.
Jira: https://circleci.atlassian.net/browse/RT-719
=> Add an FAQ for runner on `circleci` vs. `circleci-agent` [RT-719]

jekyll/_cci2/code-coverage.md
Update format and some minor content changes to the code coverage page. Created new intro section and moved the "View" section to the bottom after the various ways to set it up.
This page seemed like it hadn't been touched in a while as a few things were quite outdated. Updated page is necessary to continue to work on the larger task of new examples for code coverage/parallelism.
=> code coverage page udpate

jekyll/_data/sidenav.yml
Split out orbs pages into new sections
There are a log of pages in the orbs docs set, some of which have got overly long. We plan to split some of the pages up further so they are easier to consume. The first stage of this process is to get the categorisation right. The sections come from the sidebar reorg plan.3
=> New orbs sections in sidebar

jekyll/_cci2/collect-test-data.md
Adds a section that describes how to use BATS (the unit-test framework recommended by CircleCI for testing scripts in orbs).
This is non-trivial because CircleCI can't ingest the format output by BATS natively and the CircleCI "bats" orb doesn't do it either (see bats orb [issue 4](https://github.com/CircleCI-Public/BATS-orb/issues/4)), leaving users without a good example/easy path to follow without this documentation.
...and this is important because BATS is highlighted as "the" way of testing scripts in orbs, and orb development is core to CircleCI.
=> Describe how to use BATS

jekyll/_cci2/gitlab-integration.adoc, jekyll/_cci2/scheduled-pipelines.md
- Add a bit about the scheduled pipelines feature not being available for GitLab users to the Scheduled pipelines and GitLab pages.
- Remove bit about slug URLs for GitLab on Scheduled pipelines page
We are missing clarification that the scheduled pipelines feature is not available for GitLab.
[Jira ticket](https://circleci.atlassian.net/jira/software/c/projects/DOCTEAM/boards/554?modal=detail&selectedIssue=DOCTEAM-878)
=> Add clarification of scheduled pipelines for gitlab

jekyll/_cci2/parallelism-faster-jobs.md
Fixing a typo on the CircleCI parallelism docs
=> typo: `testss` -> `tests`

jekyll/_cci2/orb-author-faq.md
Forgot to change the quote style back to single quotes after I was troubleshooting the syntax of the code blocks.
Single quotes are best used for Ruby, Node and Python if referencing a literal string, which we are in these examples.
=> Update quote style

jekyll/_cci2/runner-faqs.adoc
The previous link tried to access a heading within the same page, returning the user to the top of runner-faqs.
This links to the correct page and information.
=> fix: correct link to building-container-images

jekyll/_cci2/server/installation/phase-2-core-services.adoc
SERVER-2214
Updating the doc to reference the default self-signed certificate behavior.
https://circleci.atlassian.net/browse/SERVER-2214
=> fix: Let's Encrypt is not default in server 4.x

jekyll/_cci2/server/installation/phase-2-core-services.adoc
SERVER-2215
The DNS documentation can apparently be confusing for folks that are not using GCP or AWS as their DNS provider. Instead of trying to enumerate all the possible methods and providers of managing DNS, we are going to remove it and assume a given organization has a process to follow.
=> chore: Remove DNS suggestions

jekyll/_cci2/env-vars.md, jekyll/_includes/snippets/secrets-masking.md
* Secrets masking was confirmed working in server 3.4 and 4.x
* Whitespace/formatting
https://circleci.atlassian.net/browse/SERVER-2210
=> fix: Clarify secrets masking is available in server 3.x and 4.x

jekyll/_cci2/using-linuxvm.md
The previous link went to an archived repo (https://discuss.circleci.com/tag/machine-images).
This links to the replacement.
=> fix: correct link to ubuntu image definition

jekyll/_includes/snippets/xcode-intel-vm.md
Remove RC from Xcode 14.2 in the versions table. The release version is the same as the RC version
=> Xcode 14.2 RC -> 14.2

jekyll/_cci2/migrating-from-github.adoc, jekyll/_cci2/migration-intro.adoc
- Move the "why migrate to CircleCI" from the GHA migrate page to the intro migration page.
- Minor updates to the content
- Fix link style
Copy was outdated and didn't really belong on the GHA migration page specifically.
[JIRA ticket](https://circleci.atlassian.net/jira/software/c/projects/DOCSS/boards/554?modal=detail&selectedIssue=DOCSS-921)
[DOCSS-921]: https://circleci.atlassian.net/browse/DOCSS-921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …
=> Move content from GHA to intro page

jekyll/_cci2/audit-logs.adoc
Remove three audit log events.
These events do not actually get logged and therefore should not exist on this list.
=> Remove three audit log events

jekyll/_cci2/webhooks-reference.adoc, jekyll/_cci2/webhooks.md, jekyll/_data/sidenav.yml
The webhooks guide is a mix of content. This PR refreshes the structure, removes some unwanted content, and pulls out reference material into a separate page.
=> Split out webhooks reference and refresh overview page

jekyll/_cci2/server/v4.1/operator/using-metrics.adoc
The default Telegraf configuration has changed, just slightly. This PR clarifies adding custom configuration using the `telgraf.config.custom_config_file` block in `values.yaml`. 
See https://circleci.atlassian.net/browse/SERVER-2220.
=> [SERVER-2220] Clarification around adding custom Telegraf config

jekyll/_cci2/server/installation/hardening-your-cluster.adoc, jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
Cleans up whitespace
One can use custom subnetting in GCP ,this removes the recommendation that it is not possible
We have been recommending customers put k8s nodes, Nomad Clients and VMs for machine jobs in separate subnets.  
We we also suggesting three firewall rules to accompany the separate network.  The `source` for the firewall rules was overlapping and no guidance was provided on how to deal with that.  This removes those recommendations
There is still the recommendation that customers keep everything behind a private VPC and use a VPN to connect, which is a good first step in securing the networking.
The information needed to build out the firewall rules between subnets is still provided in the "hardening your cluster" section, which is now linked from here.
The bottom line is …
=> [SERVER-1940] remove gcp vm service networking rules

jekyll/_cci2/add-ssh-key.md, jekyll/_cci2/bitbucket-integration.adoc, jekyll/_cci2/github-integration.adoc, jekyll/_cci2/gitlab-integration.adoc, jekyll/_data/sidenav.yml
Clarification around automatic SSH key pairing vs additional SSH keys for other sources. Updates GitHub, Bitbucket, GitLab Integration pages as well as the Add SSH key page. A snippet did not make sense here as the instructions slightly vary per VCS.
Users can be confused about whether or not they need to actually use the instructions to create additional SSH keys, not understanding that CircleCI automatically creates deploy keys for GitHub and Bitbucket.
=> SSH keys update

jekyll/_cci2/runner-upgrading-on-server.adoc
Previously, the link to the launch-agent server compatibility chart link to the docs on using the runner web app. However, this is unsupported on server.
This PR fixes that link.
The wrong link to the server compatibility chart was used in the launch-agent server docs.
=> Fix link to launch-agent server compatibility chart

jekyll/_cci2/config-policies-overview.adoc, jekyll/_cci2/config-policy-management-overview.adoc, jekyll/_cci2/config-policy-reference.adoc, jekyll/_cci2/create-and-manage-config-policies.adoc, jekyll/_cci2/test-config-policies.adoc, jekyll/_cci2/use-the-cli-for-config-and-policy-development.adoc, jekyll/_data/sidenav.yml
This PR updates use of "config policy management" to "config policies". Also the warning around open preview is reduced in severity.
The feature has changed name, now config policies, not config policy management. Also severity of issues due to open preview has reduced.
=> Config policies feature name change

jekyll/_cci2/ip-ranges.md
we got feedback from a couple of large customers that the redirect to Discuss for pricing makes it feel not official and ephemeral.  can we just put the pricing in the actual docs page?
=> remove redirect to discuss

jekyll/_cci2/runner-installation-cli.adoc, jekyll/_cci2/runner-installation-linux.adoc, jekyll/_cci2/runner-overview.adoc
CircleCI is enabling support for `s390x` and `ppc64le` machine runners. Documentation needs to reflect the support so customers can utilize the new runner binaries.
Link to JIRA ticket:  [RT-555](https://circleci.atlassian.net/browse/RT-555)
Enabling `s390x` and `ppc64le` allows us to better serve the open source community and more enterprise customers.
Additionally, the PR also includes a spelling fix on runner overview page.
[RT-555]: …
=> Updating runner docs with support for s390x and ppc64le Machine Runner

jekyll/_cci2/runner-installation-linux.adoc
The `circleci` user should have ownership of the directory the launch-agent binary is installed at to ensure that auto-update will work as expected.
Jira: https://circleci.atlassian.net/browse/RT-877
=> Fix ownership on launch-agent binary directory [RT-877]

jekyll/_cci2/openid-connect-tokens.adoc
Currently, the documentation for authenticating with AWS using OIDC shows an example that uses the entire `aws sts` command to generate temporary keys and session token. Although the example works, the `aws-cli` orb's `setup` command does the same thing but in 6 lines.
This `PR` replaces the original example with one that uses the orb.
=> docs: update aws oidc example to use aws-cli orb

jekyll/_cci2/how-to-use-the-circleci-local-cli.adoc, jekyll/_cci2/run-a-job-in-a-container.adoc, jekyll/_cci2/testing-orbs.md, jekyll/_cci2_ja/how-to-use-the-circleci-local-cli.adoc, jekyll/_cci2_ja/run-a-job-in-a-container.adoc, jekyll/_cci2_ja/testing-orbs.md
Since https://github.com/CircleCI-Public/circleci-cli/pull/825, local execution now occurs without the `--job` argument, instead making the job name mandatory and this command's first argument, e.g.:
circleci local execute orb-tools/pack
This change updates all documentation where the previous form was used.
https://github.com/CircleCI-Public/circleci-cli/pull/825 changed how `circleci`'s CLI tool is called.
=> Remove `--job` argument from circleci local execute calls

jekyll/_data/sidenav.yml
- Move glossary to About
- Move Config ref to Dev Toolkit, remove all duplicate entries
The glossary was overlooked in the re-org, and we are starting to work on removing the Reference section completely.
=> Move glossary/config ref

jekyll/_cci2/api-developers-guide.md
With the move to the API Gateway, there are new headers that express the functioning of the system. These `X-RateLimit-*` headers have been added, as well as some clarifications around the other headers.
Note that the API Gateway adds both style headers, but upstream services may still implement their own rate limiting and override the original headers. A note has been added for this purpose.
[API-529]: …
=> API-529: Public documentation for additional rate limit headers

jekyll/_cci2/troubleshoot.adoc, jekyll/_includes/snippets/troubleshoot/self-hosted-runner-troubleshoot-snip.adoc
- Add the same menu to the top of Troubleshoot that exists in FAQ
- Fix the self-hosted runner troubleshoot link tags
To standardize the experience across these larger pages. (Note, the link tag #orbs is also not working here, both in the menu and the ToC. I'm wondering if there is a character limit? It makes no sense that "orbs" specifically causing problems on two pages).
=> Add menu to troubleshoot page

scripts/build_api_docs.sh
Temporarily removes Ruby Native code examples from https://circleci.com/docs/api/v2/index.html
The Ruby Native examples provided use a "disable SSL" option, which would make the API implementation susceptible to MITM attacks. We are working on figuring out how to be able to customize the code examples provided in our API reference docs, which are currently generated using a third party library. While working on a solution, the fastest way to prevent users from copying these examples is to temporarily pull them from our docs.
Please take a moment to check through the following items when submitting …
=> Remove Ruby Native snippets [DOCSS-983]

jekyll/_data/sidenav.yml
Remove reference section from sidenav
The reference section is being removed as part of the side nav re-org and the rest of the pages are duplicate pages. Help and support is being redirected in the docs platform PR.
=> Remove reference section

jekyll/_cci2/container-runner.adoc
This was fixed in release `3.0.4` of container runner: https://circleci.com/changelog/self-hosted-runner/#container-runner-version-3-0-4
Jira: https://circleci.atlassian.net/browse/RT-744
=> Remove container runner Alpine images on MicroK8s limitation [RT-744]

jekyll/_cci2/testing-ios.md
Add information about `rbenv` in Xcode images
Our Xcode 14.2 images use `rbenv` instead of `chruby` and we will continue using `rbenv` moving forward
=> Update Ruby information for Xcode images

jekyll/_cci2/server/installation/installation-reference.adoc
the nomad.buildAgentImage attribute in our values.yaml assumes the image will be pulled from dockerhub which will not work in environments where dockerhub cannot be reached. This PR adds a note that the full image reference including registry is needed when not pulling from dockerhub
https://circleci.atlassian.net/browse/SERVER-2181
=> server-2181/update-buildagent-attribute

jekyll/_cci2/server/installation/phase-2-core-services.adoc
There has been an update to the TLS options.
https://github.com/circleci/circleci-docs/pull/7638
Since this is no longer 4 options, I think keeping the copy future-proof may be best this way.
I encountered this while noting a discrepancy in this TLS section between our official 🇺🇸 vs 🇯🇵 version.
The discrepancy on 🇯🇵 version is that the PR above has yet to be reflected on our 🇯🇵 version.
=> docs: fix wording around TLS options for Server 4.x

jekyll/_cci2/artifacts.md, jekyll/_cci2/collect-test-data.md, jekyll/_cci2/container-runner.adoc, jekyll/_cci2/workspaces.md, jekyll/_cci2_ja/artifacts.md, jekyll/_cci2_ja/caching-strategy.md, jekyll/_cci2_ja/caching.md, jekyll/_cci2_ja/collect-test-data.md, jekyll/_cci2_ja/container-runner.adoc, jekyll/_cci2_ja/workspaces.md
I noticed the links to our Managing network and storage usage section are wrong.
```diff
- #managing-network-and-storage-use
+ #managing-network-and-storage-usage
```
See https://circleci.com/docs/persist-data/#managing-network-and-storage-usage
=> fix: correct links to Managing network and storage usage section

jekyll/_data/sidenav.yml
As part of the sidebar reorg, on the EN site, the [Config Reference](https://circleci.com/docs/configuration-reference/) currently lives under the Developer Toolkit section, whereas on the JA site it can be found under both the Configuration (設定ファイル) as well as Reference (リファレンス) sections. The Reference section has been removed/reorganized in the EN site. The JA site does not yet have the new Developer Toolkit section.
As we are progressing through the sidebar reorg and trying to sync the JA site, we'll keep the JA Config Reference under the "Configuration" section for now.
Currently our sidebar does not consistently open to the correct section if a page happens to be added to multiple sections.
Please follow our style when contributing to CircleCI docs. Our style guide is here: …
=> Remove config reference from JA Reference section

jekyll/_cci2_ja/new-relic-integration.adoc
there is a gap at the top of frontmatter in crowdin. I removed the space but the page is showing as a new page in the autogenerated PR from crowdin even though it already exists. I'm adding the space back in to see if that removes this page from the crowdin PR. If this works this will be a good way to fix the process, or at least simplify it.
=> match crowdin content to fix branch

jekyll/_cci2/configuration-reference.md, jekyll/_cci2/dedicated-hosts-macos.adoc, jekyll/_cci2/deploy-ios-applications.md, jekyll/_cci2/executor-intro.md, jekyll/_cci2/hello-world-macos.md, jekyll/_cci2/ios-codesigning.md, jekyll/_cci2/migrating-from-aws.adoc, jekyll/_cci2/migrating-from-azuredevops.adoc, jekyll/_cci2/migrating-from-buildkite.adoc, jekyll/_cci2/migrating-from-github.adoc, jekyll/_cci2/migrating-from-gitlab.adoc, jekyll/_cci2/sample-config.md, jekyll/_cci2/testing-ios.md, jekyll/_cci2/testing-macos.md, jekyll/_cci2/using-macos.md, jekyll/_cci2/using-matrix-jobs.adoc, jekyll/_includes/snippets/macos-resource-table.md, jekyll/_includes/snippets/xcode-intel-vm.md, jekyll/_includes/snippets/xcode-silicon-vm.md
We are launching M1 support this month, as well as announcing the deprecation of the gen1 macOS resource classes (`medium` & `large`). In preparation for these changes, we want to be sure the new M1 specs are added to the docs and all examples reference relevant Xcode images and resource classes.
* Updated macOS available resources: provide clarity around the specs and availability for the new M1 resource class
* Updated examples: we want to be sure any macOS examples reference the latest Xcode versions and resource classes
* Remove VM storage section: the differences in available storage across macOS are going to be minimal with the addition of M1 and deprecation of gen1
Please follow our style when contributing to CircleCI docs. Our style guide is here: …
=> [DOCSS-955] Update macOS docs for M1 launch and resource class deprecation

jekyll/_cci2/openid-connect-tokens.adoc
Fix indentation and typographic quotation in OIDC yaml example
* Indentation fix : yaml is valid, but cumbersome to use as a copy-paste source in your own config
* Typographic quotation : I don't even want to know what a Yaml parser woud do with those. Probably consider them as part of the string ? Either way, better replace them.
N/A
=> Fix indentation and typographic quotation in OIDC yaml example

jekyll/_cci2/env-vars.md
Add link to how-to
The env var docs are one of our highest ranking pages. After the recent split of the page we need to ensure people can find the how-to section that was previously part of the main page. It is linked to from the "order of precedence" section but should also be in the "see also" list and the intro.
=> link to setting an env var how to guide

jekyll/_cci2/server/installation/installation-reference.adoc, jekyll/_cci2/server/operator/expanding-internal-database-volumes.adoc
Our postgres volume expansion docs are outdated. They should have been updated when we updated the PG chart
https://circleci.atlassian.net/browse/SERVER-2302
=> server-2302/update-pg-vol-expansion-docs

src-api/source/layouts/layout.erb
- Removes the v1 API deprecation banner per discussion with Product
- Leaves the styling in place (v2-banner class) for the reintroduction of a new banner at some future point with revised language.
- [Ticket: DOCSS-1035](https://circleci.atlassian.net/browse/DOCSS-1035)
- [Slack Thread](https://circleci.slack.com/archives/C04ML0S9J66/p1678311676418189)
We originally published a 1-year deprecation warning about the v1 API in December of 2021, but weren't actually prepared in some ways to undertake that deprecation. We should remove that deprecation warning until we have a more concrete plan of action and timetable for it. In discussion with folks including Product, it could be nice to decouple removing the deprecation warnings on v1 from the work around how we message moving folks over to …
=> (DOCSS-1035) Remove v1 deprecation banner, leave styling

crowdin.yml, jekyll/_layouts/classic-docs.html
As discussed with the team today, this pares back the Crowdin config file to a minimal state so that we can get the workflow spun up and slowly built it back up from a minimal state.
The next steps would be:
1. merge this into `ja-localization`
2. let Crowdin pick up the config updates
3. delete Crowdin's branch and let it re-create it using the new config
4. check the resulting proposed diff, and hope it's better than what we started with
5. un-comment additional files in the config one-by-one until everything is synced up
The default commit message [1] seems more useful than the custom one that was previously set. This removes the custom config to allow the default one to be used.
[1] "New translations {fileName} ({languageName})"
This reorders the `files` config to group like files, …
=> Crowdin Minimal Config

crowdin.yml
Expanding on the pared-down minimal Crowdin config from #7819, this adds back (by uncommenting) a couple more sets of docs pages:
- `/server/operator/*`
- `/server/overview/*`
=> [WEB-1410] Extend Crowdin Config (adds server overview, operator)

jekyll/_includes/snippets/built-in-env-vars.adoc
The value for `VCS` column is missing for this row, which breaks the layout for all rows below. Not sure if `GitHub, Bitbucket, GitLab` is the correct list of supported VCSs, so please adjust if it's incorrect.
=> Fixing the layout of built-in-env-vars.adoc

jekyll/_cci2/configuration-reference.md, jekyll/_cci2/sample-config.md
* Update simple config examples so you can copy paste and run with no editing
* Clearly link to dev hub and workflows doc for further reading
* Put VS Code extension paragraphs in their own section to make doc easier to follow
* Also change the name of the configuration reference to "configuration reference" .... currently it's hard to find, and searching doesn't bring it up
I want to link to this page as example of basic configs to get people started, it would be much easier for people if they can just copy and paste the snippets, and they can easily find the dev hub to update the docker images if they want
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide- …
=> make simple samples runnable

jekyll/_cci2/server/installation/phase-1-prerequisites.adoc
The command we had provided was not guaranteed to work based on the customers specific environment.  It is is best to instead point to GCP's docs which will provided the full context and information a customer needs to make a good decision.
=> [SERVER-2337] point to GCP docs on how to reserver an IP address

jekyll/_cci2_ja/reusing-config.md
HTTPS page has internal links to HTTP
This can damage our overall website authority and user experience.
I went ahead and added HTTPS to some internal links that were missing "S".
=> Fixed HTTP links to HTTP with "S" (HTTPS)

.circleci/config.yml, Gemfile, Gemfile.lock
- Add back `jekyll-algolia` gem
`jekyll-algolia` was inadvertently removed with https://github.com/circleci/circleci-docs/pull/7862 but is needed by the `Update Algolia Index` CI step
N/A
=> Fix: Bring back Algolia indexer

Gemfile, Gemfile.lock, jekyll/_config.yml
- Re-add `jekyll-last-modified-at` to generate the needed page metadata 
Some of the metadata was missing:
now:
N/A
=> Fix: Bring back page metadata

jekyll/_cci2/config-policy-reference.adoc
Add documentation for `get_element_name` helper function.
https://circleci.atlassian.net/browse/SNC-194
=> Add docs for get_element_name policy helper

jekyll/_cci2/configuration-reference.md, jekyll/_cci2/using-docker.md
Fixes #7800 and #7729 
* Not clear that all containers can communicate with eachother when using multiple containers for a job
* Use of name rather than hostname for defining the `name` key was not clear
=> Docker multi container setup clarifications

jekyll/_cci2/github-integration.adoc
Updates Github's RSA SSH host key, per https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/.
=> Update github-integration.adoc to use new Github RSA SSH host key

jekyll/_cci2_ja/create-project.adoc
=> Fix typo in create-project.adoc

jekyll/_cci2/databases.md, jekyll/_cci2/language-javascript.md, jekyll/_cci2/language-python.md, jekyll/_data/sidenav.yml
Remove examples and guides section from sidebar, and move pages to correct sections
Sidebar reorg project
=> remove examples and guides section

jekyll/_cci2/create-an-orb.adoc, jekyll/_cci2/orb-author-intro.md
Add a warning to a couple of orb authoring pages to let readers know that orbs cannot be deleted once created
Give readers warning before they create an orb. Previously customers have been frustrated that they have only found this information after they have created an orb.
=> add warning that orbs cannot be deleted

crowdin.yml
Re-enable adoc translation in Crowdin
Issues with other files have been resolved, re-enabling adoc translation in Crowdin should be more manageable now. 
**Ticket**: [WEB-1410](https://circleci.atlassian.net/browse/WEB-1410)
~I'm not sure if this change will have an effect on `master` or if it will need to be brought into the `ja-localiation` branch~ 
Todd confirmed these will need to be merged into `ja-localization` to have an effect, since my branch is based on `master` it would include other changes if merged directly into `ja-localization`. I imagine the desired flow here is to merge  into `master` first, then bring that change into `ja-localization`. If I'm wrong about that I can open a new PR that is based off the current `ja-localization` instead.
I will open a seperate PR for …
=> [WEB-1410] Re-enable adoc translation in Crowdin

jekyll/_cci2/rerun-failed-tests-only.adoc
Fixes a couple of typos found when reviewing the Rerunning Failed Tests documentation.
Self-explanatory 😄 
=> Fix typos in Rerun Failed Tests doc

jekyll/_cci2/caching-strategy.md
Changed the `save_cache` to only save the necessary cache. Support got a report that it can include sensitive information that should not be leaked.
Customer shared that we cache ` ~/.gradle` in our documentation which can include `~/.gradle/gradle.properties` from being leaked as it can contain sensitive information. Also for `~/.m2` it can include `~/.m2/settings.xml` and also can be leaked.
=> save_cache example can cache sensitive information

jekyll/_cci2/create-and-manage-config-policies.adoc
Removed the CAUTION banner describing policy service failure.
In the rare occurrence of a policy service failure, pipelines will now be blocked by default. Admins may temporarily disable policies if necessary in this scenario to unblock their teams.
=> Remove policy service failure warning

jekyll/_cci2/server/v4.1/installation/installation-reference.adoc, jekyll/_cci2/server/v4.1/installation/phase-2-core-services.adoc
Server 4 customers now have the option to use Tink instead of Vault to manage their secret encryption
https://circleci.atlassian.net/browse/SERVER-2355
=> Server 2355/tink in server 4.1

jekyll/_cci2/server/v4.1/installation/phase-2-core-services.adoc
When trying to access the [TLS](https://circleci.com/docs/server/v4.1/installation/phase-2-core-services/#tls) section in v4.1, the link incorrectly brings up the Postgres TLS section instead of the actual TLS settings for CircleCI server. 
The [Phase 2 - Core Services](https://circleci.com/docs/server/installation/phase-2-core-services/) page for v4.0 works as expected since it seems to have anchors defined for `#postgres`, `#postgres-credentials`, and `#postgres-tls`.
The change will bring consistency across multiple versions of v4 (4.0 and 4.1) and direct users to the right section when looking for `postgres-tls` and `TLS` sections when installing/managing server. 
Both v4.1 and v4.0 will work as expected when a user tries to access `postgres` vs `TLS` related documentation. 
Please …
=> Add missing anchors for postgres in v4.1 docs

jekyll/_cci2/server/installation/migrate-from-server-2-to-server-4.adoc
Introduces workload identities as a prerequisite for the 2x to 4x migration in GCP environments. Google service account credentials will not mount due to a limitation with init containers in the migration process.
[Server ticket](https://circleci.atlassian.net/browse/SERVER-2371?atlOrigin=eyJpIjoiZDc3Y2JiNzI5MWNjNDYzN2I0ZDNlMmE1YjZkNDMyZDUiLCJwIjoiaiJ9)
=> Adding workload identities requirement to GCP 2x to 4x server migration.

jekyll/_cci2/orbs-best-practices.md
Describe the new `env subst` usage for orbs
=> feat: add env subst docs for orbs

jekyll/_cci2/rotate-project-ssh-keys.adoc
Add a space after the closing ` to correct the formatting of the text.
There was no space between the closing back-tick and the word "or" so the formatting applied to more text than necessary.
Here is the url for the page:
https://circleci.com/docs/rotate-project-ssh-keys/#rotate-a-user-key-github
Adding the space improves the readability of the sentence.
=> Update rotate-project-ssh-keys.adoc to fix formatting

jekyll/_cci2/runner-api.adoc, jekyll/_cci2/runner-concepts.adoc, jekyll/_cci2/runner-config-reference.adoc, jekyll/_cci2/runner-faqs.adoc, jekyll/_cci2/runner-installation-cli.adoc, jekyll/_cci2/runner-installation-docker.adoc, jekyll/_cci2/runner-installation-linux.adoc, jekyll/_cci2/runner-installation-mac.adoc, jekyll/_cci2/runner-installation-windows.adoc, jekyll/_cci2/runner-installation.adoc, jekyll/_cci2/runner-overview.adoc, jekyll/_cci2/runner-scaling.adoc, jekyll/_cci2/troubleshoot-self-hosted-runner.adoc, jekyll/_cci2/upgrading-circleci-machine-runner-on-cloud.adoc, jekyll/_includes/snippets/runner-1.0-deprecation-first.adoc
This PR adds a banner informing readers that runner 1.0 will be sunset in July and will have a planned brownout in June.
The banner will be saved as a snippet and added to the following pages:
https://circleci.com/docs/runner-overview/
https://circleci.com/docs/runner-concepts/
https://circleci.com/docs/runner-installation/
https://circleci.com/docs/runner-installation-cli/
https://circleci.com/docs/runner-installation-docker/
https://circleci.com/docs/runner-installation-linux/
https://circleci.com/docs/runner-installation-mac/
https://circleci.com/docs/runner-installation-windows/
https://circleci.com/docs/runner-api/
https://circleci.com/docs/runner-faqs/
https://circleci.com/docs/troubleshoot-self-hosted-runner/
https://circleci.com/docs/runner-config-reference/ …
=> Add runner 1.0 deprecation banner

jekyll/_cci2/server/installation/migrate-from-server-3-to-server-4.adoc
The most recent version of server 4.0 is currently 4.0.4. This is an update to our migration doc which currently references server 4.0.3.
We have had a few customers ask if they should specifically use 4.0.3 since our docs page refers to that version. This update will bring our [migration docs page](https://circleci.com/docs/server/installation/migrate-from-server-3-to-server-4/) in line with our [latest server 4.0](https://circleci.com/server/changelog/#release-4-0-4) version as of May 3rd, 2023.
Please take a moment to check through the following items when submitting your PR (this is just a …
=> Update 4.0.3 references to 4.0.4 in the server v3 -> v4 migration doc

jekyll/_cci2/audit-logs.adoc
This event is published by workflows-conductor (WFC) after processing user deletion requests from data-deletion-service. After WFC deletes all workflow data associated with the org, we need to publish an audit log.
https://circleci.atlassian.net/browse/PIPE-4019
=> [PIPE-4019] Add org.workflows.deleted audit event

jekyll/_cci2/optimizations.md, jekyll/_data/sidenav.yml
I thought this would make a good reference page. The original ask in the ticket was to split this page up and make overview sections for the three optimization sections we have. I felt this wasn't the right thing to do at this time as we've been talking about making landing pages instead, so thought a reference page would work instead to find a place for the page in the sidebar.
Optimizations overview was not on the sidebar.
=> add optimization overview to sidebar and refresh

jekyll/_cci2/insights-snapshot-badge.adoc
Fixes #7531 
Include templates from Insights snapshot badges so people with private repos can reuse API tokens from status badges rather than creating a new one.
In docs we mentioned it is possible to reuse the token from a status badge for an Insights snapshot badge, but without the templates this is not possible because the process of generating the badge in the web app includes creating a new token.
=> Add Insights badge templates and options

jekyll/_cci2/code-coverage.md
Rearrange page to make it clear  how to store and view code coverage reports, and add a section on using test splitting/parallelism AND code coverage, to make it clear they are two completely separate systems/processes
Reports that people were looking for info on how to use code coverage reporting, while taking advantage of test splitting and parallelism.
=> Code coverage and parallelism

jekyll/_cci2/server/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.1/installation/phase-1-prerequisites.adoc
fixes #7774  
* Clarify why a service account is created when creating a new cluster for a server v4 installation
* Add the service account steps to the optional section for those who have an existing cluster and want to switch to use Workload Identity. Previously there was no indication that the steps in the previous section needed to be followed.
Reports that this section was confusing because readers were asked to create a service account with no explanation why.
Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for …
=> Server v4: Service account clarifications

jekyll/_cci2/container-runner-installation.adoc, jekyll/_cci2/container-runner.adoc, jekyll/_cci2/runner-api.adoc, jekyll/_cci2/runner-overview.adoc, jekyll/_data/sidenav.yml, jekyll/_includes/snippets/faq/self-hosted-runner-faq-snip.adoc
* Remove conceptual content from container runner reference so that it is more purely a reference guide, and transfer that content to the self-hosted runner overview
* Update titles for consistency
* Also includes fixes for runner API reference section headers
Continuation of runner content reorg
=> Container runner reference

jekyll/_cci2/scheduled-pipelines.adoc
fixes #8050 
Video was not displayed, just the html. Fixed by enclosing the html in a pass through block
=> fix video with passthrough block

jekyll/_cci2/using-shell-scripts.md, jekyll/_data/sidenav.yml
* Add https://circleci.com/docs/using-shell-scripts/ to side navigation 
* Minor text edits
* Move to different section in JA side nav
The EN doc was not in the side nav. This PR adds the doc to the Orchestrate & Trigger side nav section in order to surface it to readers who are learning about configuring and managing their pipelines and configs
=> Add shell script doc to side nav

jekyll/_cci2/manage-contexts-with-config-policies.adoc
Remove references of `OIDC` in config policy helpers
Jira: https://circleci.atlassian.net/browse/SNC-310
=> [DOCSS-1130] Remove references of `OIDC` in config policy helpers

jekyll/_cci2/troubleshoot-test-splitting.adoc
ref: [Troubleshoot test splitting](https://circleci.com/docs/troubleshoot-test-splitting/)
- Fixed link typo containing a parenthesis
- Fixed a tag typo for a shell command
- Link did not open correctly
- Bash command was wrongly formatted
=> Fix phpunit-finder link typo and bash command formatting

jekyll/_cci2/parallelism-faster-jobs.md, jekyll/_cci2/workflows.md
* Add link to Concurrency overview from Parallelism overview to catch people who have searched "parallel" when they want concurrent jobs in workflows etc
* Use correct terminology on Workflows overview page
Clear confusion from reader feedback
=> Consistent use of parallel and concurrent

jekyll/_includes/snippets/xcode-intel-vm.md
Add deprecation notice for affected Xcode images
These images are now deprecated: https://discuss.circleci.com/t/xcode-image-deprecation-and-eol-notice-2023/48264/2
=> Add deprecation notice for affected Xcode images

jekyll/_cci2/parallelism-faster-jobs.md
fixes #7833 
Remove reference to --total flag, as this was confusing, and the way it was presented as an alternative to the parallelism key was incorrect.
Incorrect content
=> remove reference to --total flag

jekyll/_cci2/config-policy-management-overview.adoc
* Add a section to show that policies are evaluated against setup and continuation configs as well as normal configs.
* Also suggest ways to have policies only apply to the setup or continuation parts
Customer request
=> Add section on config policies for dynamic config

jekyll/_cci2/config-policy-reference.adoc
Removes outdated caution
This has already been removed from other config policies pages
=> remove caution re config policies

jekyll/_cci2/how-to-use-the-circleci-local-cli.adoc, jekyll/_cci2/local-cli.md, jekyll/_data/sidenav.yml
* Link to how to guides from CLI installation page, both into and next steps section
* Move validate config how to to the How to page
* Remove how to and reference sections from dev toolkit section until we have better sidebar UX
* Move all links to support portal on the CLI page to "separate" section at the end of the page
There was no linking between the installation and how-to pages
=> Improve CLI docs structure for findability

jekyll/_cci2/runner-api.adoc, jekyll/_cci2/runner-concepts.adoc, jekyll/_cci2/runner-config-reference.adoc, jekyll/_cci2/runner-faqs.adoc, jekyll/_cci2/runner-installation-docker.adoc, jekyll/_cci2/runner-installation-linux.adoc, jekyll/_cci2/runner-installation-mac.adoc, jekyll/_cci2/runner-installation-windows.adoc, jekyll/_cci2/runner-on-kubernetes.adoc, jekyll/_cci2/runner-overview.adoc, jekyll/_cci2/runner-scaling.adoc, jekyll/_cci2/troubleshoot-self-hosted-runner.adoc, jekyll/_cci2/upgrading-circleci-machine-runner-on-cloud.adoc, jekyll/_includes/snippets/runner-1.0-deprecation-brownout.adoc
This PR updates the existing runner 1.0 deprecation banners with the following message regarding the brownout on June 28th:
> **Self-hosted runner version 1.0 is temporarily unavailable today.** Version 1.0 will permanently sunset on July 27, 2023.
The updated message is saved as a .adoc snippet and the snippet added to the following pages:
https://circleci.com/docs/runner-overview/
https://circleci.com/docs/runner-concepts/
https://circleci.com/docs/runner-installation-linux/
https://circleci.com/docs/runner-installation-windows/
https://circleci.com/docs/runner-installation-mac/
https://circleci.com/docs/runner-installation-docker/
https://circleci.com/docs/runner-config-reference/
https://circleci.com/docs/upgrading-circleci-machine-runner-on-cloud/ …
=> Update runner 1.0 deprecation banners with brownout notice

jekyll/_cci2/gitlab-integration.adoc, jekyll/_cci2/insights-snapshot-badge.adoc, jekyll/_cci2/status-badges.md
Add banners to state that status and Insights badges aren't currently supported for GitLab projects
GitLab support across docs
=> Badges not supported for GitLab projects

jekyll/_cci2/configuration-reference.md
Remove mention of the functionality to opt out of parallelism in a "parallelism aware" step
Resolves #8135 .
The `deploy` step is deprecated.
=> Remove mention of 'parallelism-aware steps'

jekyll/_cci2/container-runner.adoc
This adds the `customSecret` parameter to the yaml config along with a link to a support article on instruction for how to do it.
=> Add a parameter and link to the Custom Token runner section

jekyll/_cci2/runner-api.adoc, jekyll/_cci2/runner-concepts.adoc, jekyll/_cci2/runner-config-reference.adoc, jekyll/_cci2/runner-faqs.adoc, jekyll/_cci2/runner-installation-docker.adoc, jekyll/_cci2/runner-installation-linux.adoc, jekyll/_cci2/runner-installation-mac.adoc, jekyll/_cci2/runner-installation-windows.adoc, jekyll/_cci2/runner-on-kubernetes.adoc, jekyll/_cci2/runner-overview.adoc, jekyll/_cci2/runner-scaling.adoc, jekyll/_cci2/troubleshoot-self-hosted-runner.adoc, jekyll/_cci2/upgrading-circleci-machine-runner-on-cloud.adoc, jekyll/_includes/snippets/runner-1.0-deprecation-post-brownout.adoc
Replace brownout banner with new post-brownout banner urging runner 1.0 users to update to 1.1.
circleci.com/docs/upgrading-circleci-machine-runner-on-cloud/ has the banner hardcoded as it is the page being linked to in the snippet.
Runner 1.0 will sunset July 27, 2023.
=> Post-brownout banner for runner 1.0 deprecation

jekyll/_cci2/deploy-to-aws.adoc, jekyll/_cci2/ecs-ecr.md, jekyll/_data/sidenav.yml
* Added page to sidebar
* Removed deploy-service-update-to-aws-ecs from deploy section because it's also int he orbs section
* Also I found a reference to 2.0 config in another AWS deploy how-to so fixed
* Made page title better reflect what's on the page
Just to note, we have 3 pages that cover AWS deployment use cases, one is marked at outdated but looks like the content is still useful. I'll make a separate ticket to review all this content.
All pages should be available in the navigation
Please take a moment to check through the following items when submitting your PR (this is just a guide so …
=> Add AWS deploy page to sidebar

jekyll/_includes/snippets/xcode-intel-vm.md, jekyll/_includes/snippets/xcode-silicon-vm.md
Update Xcode 14.3.1 to release version
Update Xcode 14.3.1 release version replaces the RC release
=> Update Xcode 14.3.1 to release version

jekyll/_cci2/config-policy-management-overview.adoc
Adds an import that was previously missing, which was causing the snippet to be invalid.
The SSH rerun snippet was previously missing the `import data.circleci.utils` line, which is necessary for the `    count(utils.to_set(job.context) & sensitive_contexts) > 0` line further down in the snippet.
This was previously invalid, and would not compile.
This means the code snippet can be copied and will work without the need to make changes, which is particularly useful as  `data.circleci.utils` does not appear elsewhere in this doc.
Please take a moment to check through the following items when …
=> Add necessary import to ssh_rerun snippet

jekyll/_cci2/openid-connect-tokens.adoc
Changed the OIDC GCP docs by providing a useful attribute mapping for the OIDC provider setup.
The current docs are pretty vague about which attribute mappings are needed for the OIDC provider in GCP. The ones provided as example don't work (they can't even be saved because one of them seems to be invalid). This makes this already complex setup process even harder and it took me quite some googling and trial and error to figure out a mapping that actually works with the provided example config-file.
Please take a moment to check through the following items when submitting your PR (this is just a …
=> Define correct attribute mapping for OIDC GCP

jekyll/_cci2/examples-and-guides-overview.adoc
Suggesting a link to the reference guide from "Examples and Guides Overview" page as it is hard to find the reference guide
=> suggest link to reference guide

jekyll/_cci2/reusing-config.md
Removes `{:.no_toc}` for the `executor` parameter type.
It's confusing that it wasn't in the sidebar when the other types are.
cc @kbatuigas as the other parameter types had `{:.no_toc}` removed in 9af117cb438caa6cd569ddcb9969ec5041891c75
=> Include executor parameter type in sidebar

jekyll/_config.yml
- Add `sectionTags: null: null` in jekyll config.yml
Similar to what we did with `contentTags`, we want to ensure that there is always a `sectionTags: null` set for all the FrontMatter generated.
N/A - Not a content PR
=> [DOCSS-1205] Force `sectionTags` to always be `null` in FrontMatter

jekyll/_cci2/contexts.md, jekyll/_cci2/custom-images.md, jekyll/_cci2/databases.md, jekyll/_cci2/docker-compose.md, jekyll/_cci2/docker-to-machine.md, jekyll/_cci2/ios-codesigning.md, jekyll/_cci2/local-cli.md, jekyll/_cci2/orb-author.md, jekyll/_cci2/orb-concepts.md, jekyll/_cci2/postgres-config.md, jekyll/_cci2/reusing-config.md, jekyll/_cci2/security-supply-chain.md, jekyll/_cci2/using-windows.md
Remove all instances of no_toc across docs
Previously we would manage the TOC to prevent it getting too long, this was back when the TOC appeared at the top of a page. With the right hand page TOC this is no longer necessary and actually can be confusing to the reader.
=> remove no_toc

jekyll/_cci2/rerun-failed-tests.adoc, jekyll/_cci2_ja/rerun-failed-tests.adoc
add missing colon to cypress example Re-run failed tests
The yml was invalid, it was missing the colon. Other examples using `store_test_results` have the colon
=> add missing colon to cypress example Re-run failed tests

jekyll/_cci2/rerun-failed-tests.adoc
A bunch of changes were removed from the Rerun failed tests doc in error, this PR puts them back.
=> Re-add sections to rerun failed tests page

jekyll/_cci2/how-to-use-the-circleci-local-cli.adoc
In the "How to use the CircleCI local CLI" page, adds details to limitations as pertains to Machine and macOS "executors".
* [Jira](https://circleci.atlassian.net/browse/DEVEX-1189)
* [GitHub](https://github.com/CircleCI-Public/circleci-cli/issues/963)
=> add details to CLI local jobs executor limitations

jekyll/_includes/snippets/faq/self-hosted-runner-faq-snip.adoc
Add a mention of what the runner resource class token has access to.
Customer requested official documentation that the runner resource class token can only be used to claim tasks
=> add runner resource class token access information

jekyll/_cci2/insights-snapshot-badge.adoc
Fixed link to Insights dashboard for the Insights Snapshot Badge Markdown example
Should be 
`https://app.circleci.com/insights/<VCS_FULL>/<ORG_NAME>/ `
instead of 
`https://app.circleci.com/insights/github/<VCS_FULL>/<ORG_NAME>/`
=> Fix Insights link for Markdown format Insights Snapshot Badge

jekyll/_cci2/rerun-failed-tests.adoc
1. added in something that some customers are missing when it comes to using the halt command
2. added to output file names section that the halt command is probably needed to avoid a failure if using parallelism
3. added to troubleshooting section an error for an edge case that 3 ppl reported last week
4. add store_test_results to all examples since i've talked to a few customers who forgot to add that because they just copied from the docs and didn't read the prereqs
=> batched updates to rerun failed tests page

jekyll/_cci2/runner-api.adoc
The runner V3 API doc has the incorrect routes for the runner `/tasks` endpoints. These routes should be:
- [/api/v3/runner/tasks](https://github.com/circleci/runner-admin/blob/main/api/external/v3/api.go#L50) instead of `/api/v3/tasks`
- [/api/v3/runner/tasks/running](https://github.com/circleci/runner-admin/blob/main/api/external/v3/api.go#L51) instead of `/api/v3/tasks/running`
Jira: https://circleci.atlassian.net/browse/RT-1232
=> Fix routes for the runner tasks endpoints on the V3 API [RT-1232]

jekyll/_cci2/pull-an-image-from-aws-ecr-with-oidc.adoc
Changing reference from image ARN to image URI to use when pulling an image from AWS ECR with OIDC.
After following the documentation I noticed that the process is not working with the ARN but with the image URI instead.
=> Replace reference to image ARN to image URI in "Pull an image from AWS ECR with OIDC" doc

jekyll/_cci2/rerun-failed-tests.adoc
1. make clear that this is a new workflow, not just a new job that gets kicked off (this may need some work). basically it's not clear (and has come up with a couple of customers) that this is a brand new workflow just like "rerun workflow from failed", not just a job in isolation (like ssh rerun)
2. typo with whitespace
3. add elixir tests example
4. another typo
5. add that kotlin and gradle can use the same mechanism to run their tests with this feature
6. add phpunit example
7. I've had ~5 ppl this week reach out that they were confused why it wasn't working for them. They all forgot the `xargs` in their --command.  Several of them said it would be good to have an explicit reminder in the language-specific examples to use `xargs`.  I tend to agree so I added that in.
=> batched updates to rerun failed tests docs

jekyll/_cci2/workflows.md
Removes a link to a blog post that no longer exists on the CircleCI site.
The link to a blog article no longer works, and even worse, redirects to this page.
The content is available on web.archive.org if there's a desire to re-publish it in the blog instead of removing this link.
http://web.archive.org/web/20201111192633/https://circleci.com/blog/manual-job-approval-and-scheduled-workflow-runs/
NA
=> Remove broken link from workflows.md header

src-api/source/includes/_builds_and_jobs.md, src-api/source/includes/_overview.md
* Remove the `parallel` param from the Trigger a new job and Trigger a new job with branch calls, which make references to 2.0 architecture
* Edits to Overview
* The existing 'Getting Started' section doesn't appear to serve any function so I've replaced that content with the 'API syntax' section for now
* Rearranged subsections to reflect this general flow: Authentication -> Get started (API syntax) -> Additional details about requests -> Additional details about responses
References to "CircleCI 1.0/2.0" is no longer relevant to most users
Please take a moment to check through the following …
=> V1 reference refresh: config version

jekyll/_cci2/test-splitting-tutorial.adoc
* Updates the Test Splitting tutorial to accommodate GitLab projects.
The main section that is affected is the project setup, since the project onboarding experience is slightly different for GitLab:
The sample project has also been added to CircleCI-Public: https://github.com/CircleCI-Public/circleci-react-test-splitting-tutorial
* Minor text/syntax changes
GitLab support
=> GitLab update for test splitting tutorial

jekyll/_cci2/language-go.md
Add Go links to last section of Go Quickstart
Python links were left in there by mistake
=> Go links updates

jekyll/_includes/snippets/macos-resource-table.md
Expand deprecation alert to include details for remaining Intel-based macOS deprecations.
We're deprecating all Intel macOS resources over the next 6 months.
=> Add deprecation warnings for Intel macOS resources

jekyll/_includes/snippets/macos-resource-table.adoc, jekyll/_includes/snippets/macos-resource-table.md
* Update deprecation banner in the `macos-resource-table.adoc` snippet
The Using macOS page is written in .adoc and the corresponding snippet is in an .adoc file as well
=> Fixes to the macOS resource class banners

jekyll/_cci2/config-editor.md
Add banner to config editor page to state it's not available for GL or GH Apps. Apart from when creating a project (GL Cloud only).
Standalone support across docs
=> [GITHUB APPS] config editor banner

jekyll/_cci2/configuration-reference.md, jekyll/_cci2/executor-intro.md, jekyll/_cci2/hello-world.adoc, jekyll/_cci2/optimizations.adoc, jekyll/_cci2/using-gpu.md, jekyll/_includes/snippets/gpu-linux-resource-table.md, jekyll/archived/_cci2/executor-types.md
Mainly went through references to GPU images that were outdated and/or were using a resource class that is not compatible. for reference, [these are the resource classes that are compatible](https://github.com/circleci/machine-provisioner/blob/main/deploy/conf/machine-provisioner-config.yml#L1190)
[CPE-1884](https://circleci.atlassian.net/browse/CPE-1884)
- [N/A] Is …
=> [CPE-1884] chore: Update relevant GPU docs

jekyll/_cci2/runner-api.adoc, jekyll/_cci2/runner-concepts.adoc, jekyll/_cci2/runner-config-reference.adoc, jekyll/_cci2/runner-faqs.adoc, jekyll/_cci2/runner-installation-docker.adoc, jekyll/_cci2/runner-installation-linux.adoc, jekyll/_cci2/runner-installation-mac.adoc, jekyll/_cci2/runner-installation-windows.adoc, jekyll/_cci2/runner-on-kubernetes.adoc, jekyll/_cci2/runner-overview.adoc, jekyll/_cci2/runner-scaling.adoc, jekyll/_cci2/troubleshoot-self-hosted-runner.adoc, jekyll/_cci2/upgrading-circleci-machine-runner-on-cloud.adoc, jekyll/_cci2_ja/runner-api.adoc, jekyll/_cci2_ja/runner-concepts.adoc, jekyll/_cci2_ja/runner-config-reference.adoc, jekyll/_cci2_ja/runner-faqs.adoc, jekyll/_cci2_ja/runner-installation-cli.adoc, jekyll/_cci2_ja/runner-installation-docker.adoc, jekyll/_cci2_ja/runner-installation-linux.adoc, jekyll/_cci2_ja/runner-installation-mac.adoc, jekyll/_cci2_ja/runner-installation-windows.adoc, jekyll/_cci2_ja/runner-installation.adoc, jekyll/_cci2_ja/runner-on-kubernetes.adoc, jekyll/_cci2_ja/runner-overview.adoc, jekyll/_cci2_ja/runner-scaling.adoc, jekyll/_cci2_ja/troubleshoot-self-hosted-runner.adoc, jekyll/_cci2_ja/upgrading-circleci-machine-runner-on-cloud.adoc
Remove deprecation notice for runner 1.0
Runner 1.0 was sunset 3rd Aug 2023
=> Remove 1.0 deprecation notice (including JA pages)

jekyll/_includes/snippets/xcode-intel-vm.adoc, jekyll/_includes/snippets/xcode-intel-vm.md, jekyll/_includes/snippets/xcode-metal.adoc
* remove deprecated images from Xcode support table
* update resource class deprecation warnings for Intel & Dedicated Hosts
* fix small typo in Dedicated Host Xcode support table
We have removed the deprecated Xcode images as of 8/9/23 and will be removing Intel macOS resources over the next 6 months. Our docs should reflect this to avoid customer confusion.
=> Update Xcode and Dedicated Host tables

jekyll/_cci2/config-intro.adoc
It seems like you had an earlier version of this tutorial that included lines for supplying Docker registry credentials and although these lines were taken out, the line numbers in the explanations that followed were not corrected. 
I have attempted to correct them, and added in a small statement that notes the Docker credentials are omitted for your examples.
Simple corrections to match seemingly new docs.
=> Update line numberings for code block descriptions

jekyll/_cci2/linux-cuda-images-support-policy.adoc, jekyll/_cci2/using-gpu.md
Update the existing banner on https://circleci.com/docs/using-gpu/ and https://circleci.com/docs/linux-cuda-images-support-policy/ to inform readers of ongoing brownout.
Scheduled brownouts: https://discuss.circleci.com/t/linux-cuda-deprecation-and-image-policy/48568
Next are the 19th and 25th of September (images removed 30th of September)
=> Linux CUDA images brownout #1

jekyll/_cci2/github-apps-integration.adoc, jekyll/_cci2/github-integration.adoc, jekyll/_data/sidenav.yml
* Create GitHub App integration page 
* Update original GitHub integration page to specify GitHub OAuth app
* Remove signup info from GitHub OAuth app integration page
=> [GitHub Apps] integration page

jekyll/_cci2/config-intro.adoc
Mostly updates to the [first section](https://circleci.com/docs/config-intro/#part-1-using-the-shell) of the Configuration Introduction doc so that readers are redirected to the Quickstart for project setup/creation steps. 
Quickstart guide already describes the difference between setting up or creating a project based on whether or not it is a standalone project. Removing those steps in this doc makes it a bit shorter and easier to maintain as it is one less page to account for differences in the legacy/standalone experience.
Please take a moment to check through the following items when …
=> Config intro refresh for standalone

jekyll/_cci2/rerun-failed-tests.adoc
Update anchor to "configure-a-job-running-django-tests" to match the section.
An incorrect anchor tag was used for the Django section.
This updates it to the correct value:
configure-a-job-running-playwright-tests --> configure-a-job-running-django-tests
Updating the anchor link will provide a better experience for users using the navigation bar.
=> Update rerun-failed-tests.adoc anchor tag

jekyll/_cci2/container-runner.adoc
The docs currently refer to `edge` as the default image tag for the container runner agent. This tag is not considered stable and only used for testing and triaging. This PR updates the default tag to match what is in the default helm chart values for the latest stable release of the container runner agent. 
We were providing inaccurate and possibly breaking information about the the version of agent to use for container runners. 
=> update to current container runner image tag

jekyll/_cci2/ip-ranges.md
The macos team will be decommissioning the network (`mke-1a`) in which these IPs are living. Therefore, we are retired these IP ranges from use
Therefore, we are retired these IP ranges from use. Here is a linked [JIRA Ticket](https://circleci.atlassian.net/browse/MAC-1719)
None of the below were necessary since only lines were being deleted from existing page.
=> [MAC-1719] remove mke-1a IP ranges

jekyll/_cci2/linux-cuda-images-support-policy.adoc, jekyll/_cci2/using-gpu.md
Swap Linux CUDA images deprecation notice back into docs.
First brownout date has passed
=> Replace brownout banner with deprecation notice

jekyll/_cci2/collect-test-data.md
this is needed for split by timings, and rerun failed test as jest-junit doesn't include the `file` attribute by default.
add JEST_JUNIT_ADD_FILE_ATTRIBUTE to jest section
this is needed for split by timings, and rerun failed test to work as jest-junit doesn't include the `file` attribute by default.
=> add JEST_JUNIT_ADD_FILE_ATTRIBUTE to collect-test-data

jekyll/_cci2/templates/template-how-to.adoc, jekyll/_data/sidenav.yml
An AsciiDoc template for creating how-to guides.
This template aims to help docs contributors develop a how-to page more quickly and conform to CircleCI docs' style guide.
=> Template for how-to guides

jekyll/_cci2/server/v4.1/operator/troubleshooting-and-support.adoc
Our docs suggest that the `disable_concurrency` flag needs to be set to `false` in order to disable concurrency. However, when the value is set to `false`, the feature still remains disabled. 
This value needs to be set to `true` for the `distributor_dispatcher` to completely override concurrency and start all jobs for server.
A customer ran into an issue ([CIRCLE-40328](https://circleci.atlassian.net/browse/CIRCLE-40328)) where two GitHub orgs alone were blocked and setting the value to true fixed the issue.
```
distributor_dispatcher:
...
disable_concurrency: false
```
This update would ensure that other customers are not blocked as well. 
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://ci …
=> The disable_concurrency flag needs to be true for it to work

jekyll/_cci2/linux-cuda-images-support-policy.adoc, jekyll/_cci2/using-gpu.md
Update the existing banner on https://circleci.com/docs/using-gpu/ and https://circleci.com/docs/linux-cuda-images-support-policy/ to inform readers of ongoing brownout.
Scheduled brownout on the 19th of Sept: https://discuss.circleci.com/t/linux-cuda-deprecation-and-image-policy/48568
Next is the 25th of September (images removed 30th of September)
=> Linux CUDA images brownout #2

jekyll/_cci2/webhooks-reference.adoc
Update standalone project info on webhooks reference page to include GitHub Apps as well as GitLab, and point people to the integration page to help them work out which integration type they have.
Standalone support across docs
=> GitHub App updates to webhooks reference page

jekyll/_cci2/workspaces.adoc
This PR changes the Workspaces documentation page at https://circleci.com/docs/workspaces/ to avoid specifically referring to "containers" since Workspaces work across different execution environments. I've made terminology more generic and related to execution environment rather than container.
The documentation on Workspaces currently suggests that Workspaces are only limited to containers but they work elsewhere on different types of executors.
=> Generify container-specific wording in Workspaces docs

jekyll/_cci2/install-machine-runner-3-on-linux.adoc
The Web App installation instructions still refer to launch agent and aren't updated for this preview
Followup to PR #8342. The Web App installation guide is only for launch agent, and therefore isn't applicable to setting up Machine Runner 3.0 on Linux at this time. For now, we should just have the CLI instructions for creating a namespace and resource class.
The Web App installation instructions still refer to launch agent and aren't updated for this preview
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide …
=> Remove Web App instructions for Machine Runner 3.0 on Linux

jekyll/_cci2/how-to-use-the-circleci-local-cli.adoc
Document job name requirement for local running.
When running `circleci local execute`, the job name required is exactly that; the job *name*, not its *key*. I thought it might be useful to make that clear.
=> Document job name requirement for local running

jekyll/_cci2/migrate-from-launch-agent-to-machine-runner-3.adoc, jekyll/_cci2/migrating-from-launch-agent-to-the-machine-runner-agent-3-0-preview.adoc, jekyll/_data/sidenav.yml
[A link to a GitHub and/or JIRA issue (if applicable).](https://circleci.atlassian.net/browse/ONPREM-326)
Adding in a reduced version of [this PR](https://github.com/circleci/circleci-docs/pull/8146) to only provide update instructions for linux hosts - the only supported host for the Machine Runner 3.0 preview. 
=> Onprem 326/machine runner preview migration

jekyll/_cci2/linux-cuda-images-support-policy.adoc, jekyll/_cci2/using-gpu.md
Update Linux CUDA pages to display brownout notice (brownout #3, 25th Sept)
Final scheduled brownout https://discuss.circleci.com/t/linux-cuda-deprecation-and-image-policy/48568
Images removed 30th of September
=> Linux CUDA brownout 25th Sept

jekyll/_cci2/linux-cuda-images-support-policy.adoc, jekyll/_cci2/using-gpu.md
Revert from brownout to deprecation notice. The brownout happened on 25th
=> revert to deprecation notice until 30th

jekyll/_cci2/ssh-access-jobs.md, jekyll/_cci2/workflows.adoc
Inform readers that rerunning workflows that contain jobs which were rerun with SSH will have those jobs SSH-enabled in the new workflow.
DOCSS-1186
=> Note for readers regarding SSH enabled jobs on rerun workflows

jekyll/_cci2/hello-world-windows.md
Remove content asking server users to workround use of orbs. This content is from when orbs were not available on server.
=> remove outdated server reference

jekyll/_cci2/machine-runner-3-configuration-reference.adoc
The config example for cleanup_working_directory was missing the actual cleanup_working_directory example. This PR adds them in
The working directory example was also updated to match the example above and the default configuration. 
A note from Logan brought this up while troubleshooting a Machine Runner 3.0 install for a customer. 
https://circleci.atlassian.net/browse/ONPREM-533
=> fix missing code in config example for machine runner 3.0

jekyll/_cci2_ja/openid-connect-tokens.adoc
I updated Japanese translations OIDC docs.
We don't need a context to use OIDC tokens, but Japanese version of OIDC docs doesn't reflect this fact.
=> update Japanese translations of openid-connect-tokens.adoc

jekyll/_cci2/configuration-reference.md, jekyll/_cci2/executor-intro.md, jekyll/_cci2/using-linuxvm.md
Add note to relevant sections that `machine: true` is deprecated
=> Deprecate machine:true

jekyll/_includes/snippets/macos-resource-table.adoc, jekyll/_includes/snippets/macos-resource-table.md
Updated Gen2 deprecation date to June 28 from Jan 31
Date was changed to June 
- Context: https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718#:~:text=The%20sunsetting%20of%20Intel%20resources%20is%20now%20June%2028%2C%202024
=> Update Gen 2 Intel Deprecation date to June 28, 2024

jekyll/_cci2/container-runner.adoc
Add link to container runner helm repo in reference docs
The container runner helm chart repo is now public. This PR adds a link to the repo in the reference docs for container runner
=> [ONPREM-330] Add link to container runner helm repo in reference docs

jekyll/_includes/snippets/xcode-intel-vm.adoc, jekyll/_includes/snippets/xcode-intel-vm.md, jekyll/_includes/snippets/xcode-silicon-vm.adoc, jekyll/_includes/snippets/xcode-silicon-vm.md
xcode 15.1 beta 2 was rerolled last night to update the OS to Sonoma so the manifest and discuss posts are now different
=> [MAC-1930] chore: update Xcode 15.1 Beta 3

jekyll/_cci2/add-ssh-key.adoc
Add note that when adding an SSH key to a job the finger print must be MD5 hash
To avoid confusion, or users having to find out by trial and error
=> Add note about SSH key encryption

jekyll/_cci2/github-integration.adoc
Add a short section informing people that if they enable SAML SSO for an org they need to check settings for GH Checks and GH Status updates are correct.
=> Add SAML warning to GH OAuth app integration page

jekyll/_includes/snippets/xcode-intel-vm.adoc, jekyll/_includes/snippets/xcode-intel-vm.md
The date for the EOL of intel macOS resources below the supported Intel Xcode versions table wasn't updated to reflect the new deprecation date of June 28, 2024.
We want to ensure that people who read the docs are getting accurate information.
=> Fix xcode intel warning

jekyll/_cci2/remote-docker-images-support-policy.adoc
You cannot pin a date tag for remote docker so this is incorrect information
=> [FIX]: Remove incorrect info about pinning date for remote docker

jekyll/_cci2/building-docker-images.md
Add Docker 24 tag so customers can know they will not be booted to docker24 without warning if want to pin directly to docker24
=> add docs about docker24 tag

jekyll/_cci2/container-runner-installation.adoc
Add a helpful command to the container runner install docs for waiting on the SSH Gateway to be ready for connections.
https://circleci.atlassian.net/browse/ONPREM-608
=> Document command for waiting on the container runner SSH Gateway to be ready [ONPREM-608]

jekyll/_cci2/oidc-tokens-with-custom-claims.adoc, jekyll/_cci2/on-demand-oidc-tokens-with-custom-claims.adoc, jekyll/_cci2/openid-connect-tokens.adoc, jekyll/_data/sidenav.yml
Add a new page for multi oidc tokens custom claims to docs under "Security and Permissions -> Authentication"
Also, add link from the default oidc token overview to the multi oidc token with custom claims doc.
https://circleci.atlassian.net/browse/SNC-520
=> SNC-520: Add multi oidc tokens with custom claims to docs

jekyll/_cci2/code-coverage.md
fixes #8258 
Removes a section that was recently added to try to inform people that if they want to use test splitting and also generate code coverage reports they would need to use the store test results and the store artifacts keys. This paragraph was clearly confusing, and along with other supporting content I don't think we need it so this PR just removes the paragraph.
Please take a moment to check through the following items when submitting your PR (this is just a guide so will …
=> Remove ambiguous content

jekyll/_cci2/github-apps-integration.adoc, jekyll/_cci2/github-integration.adoc
I believe that OAuth apps have “pipelines” in the URL, as well as clarity on the username/organization name.
My pipelines endpoint is `https://app.circleci.com/pipelines/github/<org name>` and using this doc as a diagnostic of which type of app installation I had confused me.
=> Update github-integration.adoc for OAuth app URL clarity.

jekyll/_cci2/artifacts.md
Fix the artefacts download command from documentation.
Also, add `-s` (silent) option to curl to reduce logs.
#8502
=> Fix artefacts download command

jekyll/_cci2/using-windows.md
- Removed "Connecting to a Windows job via SSH and using the `bash` shell results in an empty terminal prompt."
- Replaced with note that `add_ssh_keys` step is required
This is part of a discussion in a private channel with @makotom to update known issues and limitations with Windows
- it no longer mentions "rerun with SSH with Bash" as a limitation (see screenshot below)
- it adds instead that explicit add_ssh_keys will be needed for any SSH key used in the job in any case (the key is used only in the checkout step) 
Please take a moment to check through the following items when submitting your …
=> Windows Known Issues update

.circleci/config.yml
- Edit `config.yml` to add `preview` deployment capabilities
This was originally sitting in the `preview` branch but never made it to the `master` branch. 
=> Fix: Bring back `preview` deployment

jekyll/_cci2_ja/runner-installation-mac.adoc
Add the macos attribute the main page to display table content in macos machine runner installation docs 
Table was not showing because the macos attribute was not set correctly
=> Add attribute to display table

jekyll/_cci2/server/v4.1/operator/troubleshooting-and-support.adoc, jekyll/_cci2/server/v4.2/operator/troubleshooting-and-support.adoc
This flag was removed in [ONPREM-512](https://circleci.atlassian.net/browse/ONPREM-512), permanently disabling concurrency limits for distributor-dispatcher. The docs should be updated to reflect that change.
https://circleci.atlassian.net/browse/ONPREM-742
[ONPREM-512]: …
=> Update Server 4.x docs for the removal of the disable_concurrency flag [ONPREM-742]

jekyll/_cci2/insights-glossary.md
Update Insights Metrics glossary to note that success rate calculation now excludes cancelled runs.
We recently made a change which excludes cancelled runs from this calculation.
=> [PEMON-596] update docs to note that success rate now excludes cancelled runs

src-api/source/includes/_keys.md
This PR updates the v1 API docs to indicate recently added support for sha256-type fingerprints on checkout and ssh key operations.
API supports sha256 fingerprints now, so updating docs
=> (CIRCLE-40436) Update v1 key docs to show support for sha256

jekyll/_cci2/rerun-failed-tests.adoc
This PR adds a section to https://circleci.com/docs/rerun-failed-tests/#additional-examples on how to configure Knapsack Pro to use the CircleCI rerun failed tests feature.
A DevOps Customer Engineer from CircleCI (Denis) signed up for Knapsack Pro to document the integration himself after some customers asked CircleCI how to integrate the two.
Knapsack Pro already has customers using the rerun failed tests feature, so we decided to take over the task and contribute to the docs.
Notice that Knapsack Pro is already mentioned in CircleCI docs on https://circleci.com/docs/parallelism-faster-jobs/#other-ways-to-split-tests
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/s …
=> document rerun failed tests with knapsack pro

jekyll/_cci2/server/overview/release-notes.adoc, jekyll/_cci2/server/v4.1/overview/release-notes.adoc, jekyll/_cci2/server/v4.2/overview/release-notes.adoc, jekyll/_cci2/server/v4.3/overview/release-notes.adoc
Update server changelog links to new format to fix some brokken links
The changelog link format has changed recently so some old server links pointed to the top of the changelog, rather than the specific entry
=> Update server changelog links to new format

jekyll/_cci2/machine-runner-3-manual-installation.adoc
A parameter was missing for the machine runner manual invocation in the documentation. This PR adds the missing parameter.
=> add missing parameter to machine runner manual start

jekyll/_cci2/openid-connect-tokens.adoc
With the current documentation, the authenticate piece fails with the following error:
```
google.auth.exceptions.OAuthError: ('Error code unauthorized_client: 
The given credential is rejected by the attribute condition.', 
'{"error":"unauthorized_client","error_description":
"The given credential is rejected by the attribute condition."}')
```
It fixed my issue!
N/A
=> Update attribute mapping example for OIDC

jekyll/_cci2/add-ssh-key.adoc, jekyll/_cci2/configuration-reference.md
We now support sha256 keys in the Add ssh keys step. This commit updates the docs to indicate this.
https://circleci.atlassian.net/browse/CIRCLE-40436
=> (CIRCLE-40436) Update docs to indicate sha256 support in `add-ssh-keys` step

jekyll/_cci2/server/v4.4/operator/manage-virtual-machines-with-machine-provisioner.adoc
Server AMIs for 4.4 were out of date; this updates the table with their references for both x86 and arm archs.
=> Adds server 4.4 AMIs to update docs

jekyll/_cci2/machine-runner-3-configuration-reference.adoc, jekyll/_cci2/machine-runner-3-manual-installation.adoc
https://circleci.atlassian.net/browse/ONPREM-849
Mentions the non-support of the `%s` substitution for working directory in Machine Runner 3.0.
Also, fixes a tiny typo re: chmod.
We do not support the `%s` substitution for working directory value in Machine Runner 3.0 config.
=> [Machine Runner 3.0] Clarify non-support of `%s` substitution feature for working directory

jekyll/_cci2/parallelism-faster-jobs.md
The `npx playwright test -- --shard=${shard}` command has an extra `--` in it, causing it to not actually shard. When passing arguments to the command through `npm run test`, any arguments passed before the `--` will be interpreted by `npm`, and any after by the command - so `playwright`, in this instance. But with `npx`, arguments are passed straight to the command being run - in this instance, `playwright`, so the `--` is both unnecesary and causes the sharding to not work.
A colleague of mine spent a while trying to make this work, so I figured I'd update it for anybody coming later.
Edit: I'm worried that comes off a little harsh. To be clear, I'm very grateful for this documentation!
=> Fix Playwright Sharding command

jekyll/_cci2/templates/template-conceptual.adoc
modified:   jekyll/_cci2/templates/template-conceptual.adoc
- Fixed broken link to page template
- Changed anchor text per accessibility standards
- Added alt text per accessibility standards
=> Updates to templates/template-conceptual.adoc

jekyll/_cci2/server/v4.1/air-gapped-installation/phase-2-configure-object-storage.adoc, jekyll/_cci2/server/v4.2/air-gapped-installation/phase-2-configure-object-storage.adoc, jekyll/_cci2/server/v4.3/air-gapped-installation/phase-2-configure-object-storage.adoc, jekyll/_cci2/server/v4.4/air-gapped-installation/phase-2-configure-object-storage.adoc
Context in this [Slack thread](https://circleci.slack.com/archives/C05LH7BMR2A/p1707237100251759). Essentially, we _shouldn't_ be recommending users host the _current_ version of build-agent in air-gapped server. Each server version should have their own specified version pinned.
https://circleci.atlassian.net/browse/ONPREM-888
Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be …
=> Use the pinned build-agent version on air-gapped server instead of latest [ONPREM-888]

jekyll/_cci2/openid-connect-tokens.adoc
We have expanded the number of triggers avaible to include Incoming Webhooks, which does not have a VCS Origin or Ref associated with it. As a result we need to clarify the documentation.
* Clarify when VCS data is available to the `sub`, `vcs-ref` and `vcs-origin` claims  in the OIDC token.
https://github.com/circleci/oidc-tasks-service/pull/121
=> Update OIDC subject and additional claims details

jekyll/_cci2/rerun-failed-tests.adoc
This PR fixes outdated docs for:
https://circleci.com/docs/rerun-failed-tests/#configure-a-job-running-ruby-rspec-tests-across-parallel-ci-nodes-with-knapsack-pro
The documentation was introduced some time ago after one of CircleCI engineers contacted us:
* https://github.com/circleci/circleci-docs/pull/8542
Current PR changes:
* Update outdated example of the RSpec integration with Knapsack Pro.
* We released [the knapsack_pro gem 7.0.0](https://github.com/KnapsackPro/knapsack_pro-ruby/blob/master/CHANGELOG.md#700) that simplifies integration with the [rspec_junit_formatter](https://github.com/sj26/rspec_junit_formatter) gem. This simplifies [the integration with CircleCI rerun only failed tests feature](https://docs.knapsackpro.com/ruby/circleci/#rerun-only-failed-tests).
* Remove …
=> docs(rerun failed tests): Update outdated example of the RSpec integration with Knapsack Pro.

jekyll/_cci2/datadog-integration.adoc
Removes the trailing `)` character from the link `https://app.circleci.com/projects)`
This fixes an invalid URL link on https://circleci.com/docs/datadog-integration/
Not Applicable to this PR
=> Fix broken CircleCI link on datadog-integration.adoc

jekyll/_cci2/server/v4.3/installation/phase-3-execution-environments.adoc
I noticed there is a missing comma in the policy JSON for machine provisioner.
Added the fix so that the JSON is valid.
=> fix: add missing comma

jekyll/_cci2/server/v4.3/installation/phase-3-execution-environments.adoc
I removed the mention of fetching CIDR block for the VPC re: Machine Provisioner.
I observed that the CIDR block fetched is not used in the AWS security group created for Machine Provisioner:
https://circleci.com/docs/server/v4.3/installation/phase-3-execution-environments/#set-up-security-group
=> docs: rm fetching of CIDR block for MP

jekyll/_cci2/building-docker-images.adoc
The `docker_layer_caching: true` is on line 13, not 14, as seen here: https://circleci.com/docs/building-docker-images/#run-docker-commands-using-the-docker-executor
=> Fix line number referencing docker layer caching in yaml

jekyll/_cci2/release/configure-your-kubernetes-components.adoc
Rearrange sections so the project ID annotation is added in the first section along with the required labels
See changes here once preview is built: https://internal.circleci.com/docs/release/configure-your-kubernetes-components/
Project ID is now required, previously it was optional
=> Rearrange Kubernetes config page to add project ID annotation at start

jekyll/_cci2/configuration-reference.md
Added a brief section detailing a workaround for missing git objects with blobless clones.
Our rollout of blobless clones has caused some customers issues related to the missing blobs, and this is our first pass at providing a workaround that can get customers back to passing pipelines without requiring direct-touch opt-outs via support or product.
=> [EXEC-4332] First pass at blobless workaround docs

jekyll/_cci2/android-machine-image.adoc, jekyll/_cci2_ja/android-machine-image.adoc
Update the example config.yml for using an android image in order to not use a deprecated image
The image that this example uses is going away, as per [this discuss post](https://discuss.circleci.com/t/android-image-deprecations-and-eol-for-2024/50180)
(note, none of the above check list items are relevant)
=> Update android image examples

jekyll/_cci2/release/configure-your-kubernetes-components.adoc, jekyll/_cci2/release/manage-releases.adoc, jekyll/_cci2/release/releases-overview.adoc, jekyll/_cci2/release/set-up-a-release-environment.adoc, jekyll/_cci2/release/update-the-kubernetes-release-agent.adoc
Remove open preview banners and `Coming soon` section.
We are going GA on March 18 and no longer need references to open preview. Since we are going GA, we will use the public roadmap for future improvements, rather than maintaining a `Coming soon` section.
=> Remove open preview references in prep for March 18 GA

jekyll/_cci2/server/v4.1/air-gapped-installation/phase-2-configure-object-storage.adoc, jekyll/_cci2/server/v4.2/air-gapped-installation/phase-2-configure-object-storage.adoc, jekyll/_cci2/server/v4.3/air-gapped-installation/phase-2-configure-object-storage.adoc, jekyll/_cci2/server/v4.4/air-gapped-installation/phase-2-configure-object-storage.adoc
This came out of some work with Adobe. Turns out the picard binary needs to be uncompressed to match the checksum file.
```
$ echo $CIRCLE_AGENT_VERSION 
1.0.225796-1dfdc7bb
$ curl -O --compressed https://circleci-binary-releases.s3.amazonaws.com/circleci-agent/$CIRCLE_AGENT_VERSION/linux/amd64/circleci-agent
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 10.1M  100 10.1M    0     0  11.3M      0 --:--:-- --:--:-- --:--:-- 11.3M
$ curl -O https://circleci-binary-releases.s3.amazonaws.com/circleci-agent/$CIRCLE_AGENT_VERSION/checksums.txt
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   752  100   752    0     0   3342      0 …
```
=> fix: Uncompress picard binary

jekyll/_cci2/contexts.adoc
Add note to clarify that you need to be an organization administrator to set an expression restriction
=> Org admins can set expression restrictions

jekyll/_cci2/migrating-from-github.adoc, jekyll/_cci2/migrating-from-gitlab.adoc, jekyll/_cci2/migration-intro.adoc, styles/config/vocabularies/Docs/accept.txt
Add banner to relevant migration guides to direct people to the config translator
=> add banner to introduce the config translator

jekyll/_cci2/faq.adoc, jekyll/_cci2/getting-started.adoc, jekyll/_cci2/optimizations.adoc, jekyll/_cci2/orb-author-faq.adoc, jekyll/_cci2/orb-development-kit.adoc, jekyll/_cci2/runner-config-reference.adoc, jekyll/_cci2/runner-faqs.adoc, jekyll/_cci2/sumo-logic-integration.adoc
Some banners were displaying a title incorrectly. This was due to a missing attribute in asciidoc files: `:icons: font`
For example:
Before
After
Looked bad!
=> fix banner titles

jekyll/_includes/snippets/built-in-env-vars.adoc
Added CIRCLE_PROJECT_ID, CIRCLE_ORGANIZATION_ID and CIRCLE_PIPELINE_ID
Recently CIRCLE_PROJECT_ID, CIRCLE_ORGANIZATION_ID and CIRCLE_PIPELINE_ID have been exposed as environment variables.
The only thing is for `CIRCLE_PIPELINE_ID` should we keep the same "value" as we have for `pipeline.id` which is `A globally unique id representing for the pipeline.` to keep things consistent.
=> Added CIRCLE_PROJECT_ID, CIRCLE_ORGANIZATION_ID and CIRCLE_PIPELINE_ID

jekyll/_cci2/first-steps.adoc, jekyll/_cci2/getting-started.adoc, jekyll/_cci2/github-apps-integration.adoc, jekyll/_cci2/set-up-multiple-configuration-files-for-a-project.adoc, styles/config/vocabularies/Docs/accept.txt
Edit all pages that mentioned the add SSH key step for GitHub App to remove the requirement
Note: don't worry about the lint fail, it's to do with the experimental formatting on the quickstart quide
HTTPS checkouts mean SSH key no-longer required to set up a project and trigger
=> Remove instruction to add an SSH key during project creation for GitHub App

jekyll/_cci2/how-to-use-the-circleci-local-cli.adoc
* Content refresh
* Add config policies use cases
=> Add config policies to the CLI usage guide

jekyll/_cci2/server/v4.3/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.3/installation/phase-2-core-services.adoc, jekyll/_cci2/server/v4.4/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.4/installation/phase-2-core-services.adoc
As of server 4.3, customers are able to disable presigned URLs to allow for larger artifact uploads but this has not been documented. This PR adds these instrutions
https://circleci.atlassian.net/browse/ONPREM-908
=> Adding docs for disabling presigned URLs in server 4.3+

jekyll/_includes/snippets/windows-resource-table.adoc
Fixed a typo in the "large" resource class's name in windows-resource-table.adoc.
The large resource class name had an extra space and the formatting is not showing correctly on the docs:
https://circleci.com/docs/using-windows/#available-resource-classes
- [ N/A ] Break up walls of text by adding paragraph breaks.
- [ N/A ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ N/A ] Keep the …
=> Fixed typo in windows-resource-table.adoc

jekyll/_includes/snippets/server/migrate-internal-mongo-to-external.adoc
the migrate to external mongo docs in server have a typo in the mongo restore command. its missing the host and port tags to target the external mongo. Without this the command will just restore to the mongodb internal to the cluster.
https://circleci.atlassian.net/browse/ONPREM-62
=> missing port and host for restore to ext mongo intructions

jekyll/_cci2/docker-compose.md
Compose V1 has been end-of-life'd
Compose V2 is a Docker CLI plugin and installed a bit differently.
This updates the CircleCI docs with the new way to install it.
https://github.com/docker/roadmap/issues/257
=> Update docker-compose.md for Compose v2

jekyll/_cci2/server/v4.1/installation/phase-2-core-services.adoc, jekyll/_cci2/server/v4.2/installation/phase-2-core-services.adoc, jekyll/_cci2/server/v4.2/installation/upgrade-server.adoc, jekyll/_cci2/server/v4.3/installation/phase-2-core-services.adoc, jekyll/_cci2/server/v4.4/installation/phase-2-core-services.adoc
We have effectively deprecated vault and now recommend that customers on 4.2+ use tink instead
https://circleci.atlassian.net/browse/ONPREM-676
=> Tink is installed by default on server 4.2. +

jekyll/_cci2/release/configure-your-kubernetes-components.adoc, jekyll/_cci2/release/releases-overview.adoc, jekyll/_cci2/release/update-the-kubernetes-release-agent.adoc
The release agent has been updated to use `circleci.com/component-name` and `circleci.com/version` in place of `app` and `version` for detecting new components on the cluster. Old labels are still supported for the time being
https://circleci.atlassian.net/browse/REL-2978
Thsi will be merged only after the new release agent version has been released.
=> Updating documentation for releases with the new labels to be used to onboard components

jekyll/_cci2/configuration-reference.adoc
_A brief description of the changes._
See title.
PS: I also checked the Japanese translation and this particular bug does not exist there. (The example is slightly different.)
_A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes._
Customers deserve syntactically valid configuration examples.
=> Add missing colon in example workflow configuration

jekyll/_cci2/machine-runner-3-configuration-reference.adoc
Adding a new configuration option for machine runners in preparation for cutting a machine runner release.
A new feature for using the users ssh directory for checkout keys was added to machine runners. This PR advertises this option in our docs. Once the release is cut and this PR is approved it will be merged in.
=> add machine runner ssh dir config option

jekyll/_cci2/machine-runner-3-manual-installation.adoc, jekyll/_cci2/migrate-from-launch-agent-to-machine-runner-3-on-linux.adoc, jekyll/_cci2/migrate-from-launch-agent-to-machine-runner-3-on-macos.adoc, jekyll/_cci2/migrate-from-launch-agent-to-machine-runner-3-on-windows.adoc
Adding a reference to the manual installation documentation for machine runner migration after some confusion was noted by a customer during a launch-agent migration. The configuration example for linux + macos manuall installation was also updated to be usable as copied on cloud with the correct URL specified. 
A customer was confused when migrating to Machine Runner 3.0 and trying to invoke it in a similar manner to how launch-agent was. This links in the manual installation documentation as an additional resource to make it easier to discover the documentation going over usage. 
Please take a …
=> add reference to manual installation from runner migration docs

jekyll/_cci2/set-up-multiple-configuration-files-for-a-project.adoc
Corrects typographic error, **GitHhub** -> **GitHub**.
There's an extra "h" in **GitHub App**.
=> Correct typo in set-up-multiple-configuration-files-for-a-project.adoc

jekyll/_cci2/github-apps-integration.adoc
no longer needed https://circleci.com/changelog/auto-cancel-redundant-workflows-for-github-app-projects/
=> update auto-cancel docs

jekyll/_includes/snippets/troubleshoot/self-hosted-runner-troubleshoot-snip.adoc
This is supported on Container runner now:
- https://circleci.com/docs/container-runner-installation/#2-enable-the-rerun-job-with-ssh-feature
- Supported in Open Preview as of 3.0.15 (https://circleci.com/changelog/runner-3-0-15/)
Removed the note about no ssh rerun support on container runner in `self-hosted-runner-troubleshoot-snip.adoc`
This is now supported
=> Removed SSH re-run note about lack of container runner support

jekyll/_cci2/container-runner.adoc
This PR fixes the default value documented for the `agent.image.repository` setting on our Container Runner Helm chart.
As per our Container Runner Helm chart, this `agent.image.repository` now defaults to `circleci/runner-agent` .
(Ref: https://github.com/CircleCI-Public/container-runner-helm-chart/pull/7/files)
Specifically, we can also confirm that the `circleci/runner-agent:kubernetes-3` image-tag is available:
https://hub.docker.com/layers/circleci/runner-agent/kubernetes-3.0/images/sha256-ed37b242bcfb978fa66998989dcc0d523611d168527fb268d56a2f9ee027d823?context=explore
Please take a moment to …
=> docs: correct agent.image.repository for container runner

jekyll/_cci2/install-machine-runner-3-on-docker.adoc, jekyll/_cci2/install-machine-runner-3-on-linux.adoc, jekyll/_cci2/install-machine-runner-3-on-macos.adoc, jekyll/_cci2/install-machine-runner-3-on-windows.adoc, jekyll/_cci2/machine-runner-3-configuration-reference.adoc, jekyll/_cci2/machine-runner-3-manual-installation-on-windows.adoc, jekyll/_cci2/machine-runner-3-manual-installation.adoc, jekyll/_cci2/migrate-from-launch-agent-to-machine-runner-3-on-linux.adoc, jekyll/_cci2/migrate-from-launch-agent-to-machine-runner-3-on-macos.adoc, jekyll/_cci2/migrate-from-launch-agent-to-machine-runner-3-on-windows.adoc, jekyll/_cci2/runner-overview.adoc, jekyll/_data/sidenav.yml, styles/circleci-docs/CapitalizationDocs.yml
Add docs for using the machine runner 3.0 docker image
We support running machine runner 3.0 in a docker image as we did for launch agent. We hadn't documented this though which had led some customers to assume this had been removed. This PR adds those docs
=> [ONPREM-1092] Add machine runner 3.0 docker docs

jekyll/_cci2/container-runner.adoc, jekyll/_includes/snippets/faq/self-hosted-runner-faq-snip.adoc
Minor PR to remove the warnings about using a single replica for container runner. We've tested with multiple replicas and have large customers doing the same without issue. 
A customer had noted they haven't tried increasing their replicas because of our documentation. We now consider it safe to use more than 1 container agent replica. 
=> remove warnings about increasing container-agent replicas

jekyll/_cci2/manage-contexts-with-config-policies.adoc
The Config Policy helpers are incorrect and should use `()` around their arguments instead of `{}`.
I have tested this locally to verify they work.
[Incorrect syntax highlighted internally](https://circleci.slack.com/archives/C06JL6KC4TV/p1714591318698049)
- N/A
- N/A
- N/A
- N/A
- N/A
- N/A
- N/A
=> Fix syntax for Config Policy helpers

jekyll/_cci2/roles-and-permissions-overview.adoc
anyone with push access to a repo can trigger a build so this is wrong. gitlab/github app triggers cant be run via the CCI UI or API today. so im making this more specific to say "reruns"
https://circleci.slack.com/archives/C055HTSAN8K/p1714667491334609
=> more specific

jekyll/_cci2/install-machine-runner-3-on-docker.adoc, jekyll/_cci2/install-machine-runner-3-on-linux.adoc, jekyll/_cci2/install-machine-runner-3-on-macos.adoc, jekyll/_cci2/install-machine-runner-3-on-windows.adoc, jekyll/_cci2/machine-runner-3-manual-installation-on-windows.adoc, jekyll/_cci2/machine-runner-3-manual-installation.adoc
* Add GPG dependency to the linux package installation for machine runner 3.0
* Cross link the installation documentation for other platforms on each machine runner 3.0 install page
Some support tickets arose around customers experiencing installation woes due to non-compatible GPG versions when trying to install runner via the linux package, so the GPG version has been added to the dependency. 
Some users were also not finding the manual installation instructions when they were unable to install the package due to incompatible GPG versions (AL2, and CentOS 7 in particular) so to improve visibility of these options the resources for installing runner on other platforms has been included as additional resources at the bottom of the installation doc pages. 
Please follow our style when …
=> Jrahme cci/update machine runner install docs

jekyll/_cci2/machine-runner-3-configuration-reference.adoc, jekyll/_cci2/machine-runner-3-manual-installation.adoc, jekyll/_cci2/migrate-from-launch-agent-to-machine-runner-3-on-windows.adoc
There were a few runner documentation pages with ` - Open Preview` suffixed in the titles - this PR is to remove those on 3 remaining pages where I located this discrepancy
Runner 3.0 is GA as of Nov 2023
> https://discuss.circleci.com/t/machine-runner-3-0-ga-now-w-support-for-macos-and-windows/49812
=> Removing `Open Preview` Titles on Runner docs

jekyll/_cci2/skip-build.md
This change makes it clear that we will not execute the pipeline only when the skip tag is in the last commit.
In our docs, it says that in a multi-commit push, any commit that has the skip tag would make the whole push be skipped. However, that only applies if the last commit has the tag. 
=> [PIPE-4713] Updates [ci skip] docs

jekyll/_includes/snippets/xcode-silicon-vm.adoc
Xcode 15.4 Release Candidate (RC) is now available for use.
https://circleci.atlassian.net/browse/MAC-2173
=> [MAC-2173] Add xcode 15.4 RC to Apple silicon documentation

jekyll/_includes/snippets/xcode-silicon-vm.adoc
Updating Xcode Image documentation for the 15.4 GA image, which is now available.
Xcode 15.4 GA has been [released](https://developer.apple.com/documentation/xcode-release-notes/xcode-15_4-release-notes)
=> Update Xcode 15.4 Documentation for GA release

jekyll/_cci2/caching.adoc
Update the anchor tag to point to the correct section.
Section on this page where the bad link is: https://circleci.com/docs/caching/#using-keys-and-templates
The current link is pointing to the anchor tag `which-cpu-architectures-does-circleci-support` whereas the correct one is `cpu-architecture-circleci-support`.
To make the docs consistent, and take users to the correct section in the page.
=> Update anchor link on cache page

jekyll/_cci2/openid-connect-tokens.adoc
fix AWS typo in OIDC docs
no reason, just boy-scouting 
=> fix AWS typo in OIDC docs

jekyll/_cci2/container-runner.adoc
Add a config reference entry for setting up and explaining unsafe retries. Design doc: https://circleci.atlassian.net/l/cp/eDoD37SS
https://circleci.atlassian.net/browse/ONPREM-1081
=> Add config entry for unsafe retries on container runner [ONPREM-1081]

jekyll/_cci2/server/v4.3/air-gapped-installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.4/air-gapped-installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.5/air-gapped-installation/phase-1-prerequisites.adoc
I changed the SERVER_4_x_IMAGE_LIST env var used in our example scripts to reflect the Server 4.x version correctly.
Server [4.1](https://circleci.com/docs/server/v4.1/air-gapped-installation/phase-1-prerequisites/#b-download-all-images-required-for-this-release) and [4.2](https://circleci.com/docs/server/v4.2/air-gapped-installation/phase-1-prerequisites/#b-download-all-images-required-for-this-release) were consistent;
From Server 4.3 onwards, this wasn't changed. Hence, this PR to clean up for clarity.
Please take a moment to check through the following items when submitting your PR (this is …
=> docs: update env var (holder) for images based on Server version

jekyll/_cci2/server/v4.5/air-gapped-installation/phase-2-configure-object-storage.adoc, jekyll/_cci2/server/v4.5/air-gapped-installation/phase-3-install-circleci-server.adoc
This PR adds the missing steps to 1. include files into the Minio bucket, as required by certain services, 2. update the runner_admin.external.launch_agent_base_url to also point to the Minio bucket.
While working on the air-gapped installation with a customer, we noted the distributor-internal-xxxx and radm-external-xxxx pods would end up in a CrashLoopBackOff state.
After looking at the logs, it appears that:
- distributor-internal-xxxx pod was trying to look up the canary.txt file in the `circleci-data` Minio bucket.
- radm-external-xxxx pod was trying to look up the candidate.txt file in the `circleci-data` Minio bucket.
Based on the default  Helm values for `distributor.agent_base_url` and `runner_admin.external.launch_agent_base_url`, I noted these .txt files can be copied from the …
=> docs: add missing instructions for required files in Minio

jekyll/_cci2/container-runner.adoc
Adds `aws_auth.oidc_role_arn` as a limitation on container runner
Suggested to add as a limitation here: https://circleci.slack.com/archives/C05LH7BMR2A/p1717578610993799?thread_ts=1708097814.789569&cid=C05LH7BMR2A
=> aws_auth.oidc_role_arn limitation on container runner

jekyll/_cci2/configuration-reference.adoc, jekyll/_cci2/optimizations.adoc
* Add links to all parallelism/test splitting resources to the optimization overview
* Add reference to rerun failed tests
Help people find the info
=> Improve linking for parallelism docs

jekyll/_cci2/machine-runner-3-manual-installation.adoc
For the runner manual install some versions of grep caused extra output to enter the arch variable. This PR redirects the `/usr/bin/arch` stderr and stdout to avoid contaminating the variable with extra output. 
Issue was raised in an on-prem support workflow https://circleci.slack.com/archives/C05LH7BMR2A/p1713553512725209
=> redirect output to avoid arch variable contamination

jekyll/_cci2/server/v4.2/installation/phase-2-core-services.adoc, jekyll/_cci2/server/v4.2/installation/upgrade-server.adoc
The RabbitMQ secret requires an annotation if self-managed during a 4.1 -> 4.2 migration. However, it was missed on the list of secrets requiring intervention. This PR addresses that.
https://circleci.atlassian.net/browse/ONPREM-1276
=> Add `rabbitmq-key` to the list of secrets requiring migration in 4.2 [ONPREM-1276]

jekyll/_cci2/server/v4.2/installation/upgrade-server.adoc
With Server 4.2 release, we are upgrading RabbitMQ helm chart which requires the Password to be present in env var `RABBITMQ_PASSWORD` when upgrade happens  
=> ONPREM-1276 | Added rabbitmq instruction in Server-4.2

jekyll/_includes/snippets/faq/scheduled-pipelines-faq-snip.adoc
The prior version read awkwardly, the first sentence didn't make much sense to me.
=> Improve sentence structure in scheduled pipelines FAQ

jekyll/_cci2/install-machine-runner-3-on-macos.adoc
Addressed issues encountered when installing machine runner 3.0 on macOS, especially for non-GUI sessions.
Applied changes are based on the corresponding updates made in https://github.com/CircleCI-Public/homebrew-circleci/pull/93
https://circleci.atlassian.net/browse/ONPREM-1225
=> Revise install steps for macOS machine runner 3.0 [ONPREM-1225]

jekyll/_cci2/parallelism-faster-jobs.md
I found a typo in an example of parallelism tests. `--split-by` option must be passed to `circleci` command but be wrongly included by `--command` option.
> This change does not relate to the following checks.
=> [typo] --split-by option must be passed to circleci

Gemfile.lock
Vulnerability fixed in version 3.2.7, but we can update all the way to current without violating any version constraints in our other dependencies.
=> Update rexml for CVE-2024-35176

jekyll/_cci2/ip-ranges.adoc
This PR adds `98.80.165.0/24` to the Mac IP ranges list.
This new range will be used for Mac executors on or after August 5th 2024
=> Add 98.80.165.0/24 to Mac IP Ranges documentation

jekyll/_cci2/server/v4.3/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.3/installation/upgrade-server.adoc, jekyll/_cci2/server/v4.4/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.5/installation/phase-1-prerequisites.adoc
- Update the 4.3+ prerequisite guides requiring S3 bucket versioning for DLC
- Add a note to the DLC upgrade guide for 4.3 specifically on this requirement
Jira: https://circleci.atlassian.net/browse/ONPREM-1361
=> Update server 4.3+ docs on DLC requiring S3 bucket versioning [ONPREM-1361]

jekyll/_cci2/server/latest/installation/phase-1-prerequisites.adoc
https://github.com/circleci/circleci-docs/pull/8870
https://circleci.atlassian.net/browse/ONPREM-1361
=> Add S3 bucket versioning as a requirement for DLC [ONPREM-1361] [server-4.6]

jekyll/_cci2/server/latest/installation/phase-2-core-services.adoc
Update a k8s template & update a kubectl query to be more reliable (the service name can differ but the label is stable)
ONPREM-1242
=> [ONPREM-1242] Set aws_acm enable to true in server installation docs

jekyll/_cci2/ip-ranges.adoc
Adding information about the changelog and technical contacts to the MacOS IP Range section to better inform users about where to they can receive information about updates to the MacOS IP Range list.
This helps direct customers to multiple streams where they can receive updates so they don't feel like they have to monitor changes to the list in the docs.
=> Add Where To Find MacOS IP Range Updates

jekyll/_cci2/release/update-the-kubernetes-release-agent.adoc
Remove an old warning and update another warning to CAUTION, instead of WARNING alert
The warning being removed is for a change made long enough ago that customers shouldn't face the issue anymore. The updated alert can be downgraded to CAUTION due to it not impacting customers who are just getting started (which is most customers at this point).
=> Update release agent warnings

jekyll/_cci2/server/v4.4/installation/phase-2-core-services.adoc, jekyll/_cci2/server/v4.5/installation/phase-2-core-services.adoc
ONPREM-1242
The `aws_acm` value should be set to true when enabling ACM managed ingress certs
=> [ONPREM-1242] Update aws_acm value to true

jekyll/_cci2/server/v4.2/installation/installation-reference.adoc, jekyll/_cci2/server/v4.3/installation/installation-reference.adoc, jekyll/_cci2/server/v4.4/installation/installation-reference.adoc, jekyll/_cci2/server/v4.5/installation/installation-reference.adoc
If AWS S3 Region is not defined, it defaults to `us-east-1` which clashes the `endpoint` value if set different
=> ONPREM-1408 | updated the default s3 region details

jekyll/_cci2/server/v4.1/operator/troubleshooting-and-support.adoc, jekyll/_cci2/server/v4.2/operator/troubleshooting-and-support.adoc, jekyll/_cci2/server/v4.3/operator/troubleshooting-and-support.adoc, jekyll/_cci2/server/v4.4/operator/troubleshooting-and-support.adoc, jekyll/_cci2/server/v4.5/operator/troubleshooting-and-support.adoc
The :start command was failing when there is no REPL to connect to. Using :start allows the shell to download assets to be committed via Docker and then utilized within an air-gap environment.
=> fix: Air-gap should use :start to download assets

jekyll/_includes/snippets/pipeline-values.adoc
A new pipeline value that represents whether the branch the pipeline was triggered on is the default, following the below criteria:
- `true` when it is the default branch.
- `false` when it isn’t the default branch.
- `false` when it is any other push (e.g. tag push).
- omitted when it is not a VCS-triggered pipeline.
https://circleci.atlassian.net/browse/PIPE-4728
Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be …
=> PIPE-4728 Add is default branch pipeline value

jekyll/_cci2/configuration-reference.adoc, jekyll/_cci2/dynamic-config.adoc, jekyll/_cci2/server/latest/installation/installation-reference.adoc, jekyll/_cci2/server/latest/operator/operator-overview.adoc, jekyll/_cci2/server/v4.1/installation/installation-reference.adoc, jekyll/_cci2/server/v4.1/operator/operator-overview.adoc, jekyll/_cci2/server/v4.2/installation/installation-reference.adoc, jekyll/_cci2/server/v4.2/operator/operator-overview.adoc, jekyll/_cci2/server/v4.3/installation/installation-reference.adoc, jekyll/_cci2/server/v4.3/operator/operator-overview.adoc, jekyll/_cci2/server/v4.4/installation/installation-reference.adoc, jekyll/_cci2/server/v4.4/operator/operator-overview.adoc, jekyll/_cci2/server/v4.5/installation/installation-reference.adoc, jekyll/_cci2/server/v4.5/operator/operator-overview.adoc
Update server links to point to correct set of server docs
Links from main dev docs were going to older versions of server docs. Should always point to /latest/. Also links between server docs within a version should use cross references to link to the correct version page.
=> Correct some server links

jekyll/_cci2/pipelines.adoc
=> docs(pipelines): remove redundant 'for example'

jekyll/_cci2/server/v4.2/overview/release-notes.adoc
The CLI is being updated to use the _runner_ API v3 (https://github.com/CircleCI-Public/circleci-cli/pull/1065), which is only supported on 4.3+. While 4.2 is now unsupported with the release of 4.6, this is just a courtesy for users still on 4.2.
https://circleci.atlassian.net/browse/ONPREM-237
=> Specify last compatible CLI version for server 4.2 [ONPREM-237]

jekyll/_cci2/install-machine-runner-3-on-windows.adoc
https://circleci.atlassian.net/browse/ONPREM-346
=> Update Windows runner version compatibility and prerequisites [ONPREM-346]

Gemfile.lock
Updated `rexml` to `3.3.7` to address CVE-2024-43398.
=> Update rexml for CVE-2024-43398

jekyll/_cci2/sample-config.md, jekyll/_cci2/workflows.adoc
_A brief description of the changes._
Replace some references to "workflow map" with the proper term.
_A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes._
Our documentation refers mostly to "workflow graph", which is the proper terminology. We should consolidate on that.
=> Replace "workflow map" with "workflow graph"

jekyll/_cci2/testing-llm-enabled-applications-through-evaluations.adoc
On Testing LLM docs, display a banner to notify the reader the documenation is only applicable for orb versions 1.x.x.
We are releasing orb version 2.0 and these docs only work for 1.x.x versions. We will be adding more docs at a later point in time. Till than this note will be kept.
=> docs: test llm lock to version 1 evals orb

jekyll/_cci2/release/configure-your-kubernetes-components.adoc, jekyll/_cci2/release/releases-overview.adoc
Release jobs is now the recommended approach for linking CI workflows to releases, rather than using kubernetes annotations.
We are removing references to the old annotations to avoid confusion.
=> Remove old deployment trigger annotation references

jekyll/_includes/snippets/docker-resource-table.adoc
Updating the snippet in the x86 Docker page to link you to the pricing page like ARM.
=> Update Docker x86 to link to pricing page

jekyll/_cci2/server/v4.6/installation/phase-1-prerequisites.adoc, jekyll/_includes/server/latest/installation/phase-1.adoc
CircleCI Server 4.7 and 4.6 were documented as being 4.5.x
Made this change so that customer wouldn't be confused and also matching with the right document version.
https://circleci.com/docs/server/latest/installation/phase-1-aws-prerequisites/#supported-kubernetes-versions
https://circleci.com/docs/server/v4.6/installation/phase-1-prerequisites/#supported-kubernetes-versions
=> update cci server version to match the documented version

jekyll/_includes/snippets/faq/billing-faq-snip.adoc
https://circleci.zendesk.com/agent/tickets/157020 --> discussed over slack with libby & kami, this 25% string is not quite accurate.  it's roughly 25% but we do some fudging to make sure we have whole numbers for the credit package
=> update to be more accurate

jekyll/_cci2/configuration-reference.adoc
Update documentation of `requires` job field. 
[Ticket.](https://circleci.atlassian.net/browse/PIPE-4937)
The new functionality allows users to define what statuses the upstream job dependency should have for the dependent job to start running.
=> [PIPE-4937] update requires docs to allow dependency on different statuses

jekyll/_cci2/configuration-reference.adoc
Follow-up for https://github.com/circleci/circleci-docs/pull/9097.
[Ticket.](https://circleci.atlassian.net/browse/PIPE-4937)
Fixes spacing in the config example
=> [PIPE-4937] add space to example of requires

jekyll/_cci2/language-python.md
Replacing the executor name `python/default` with `heroku/default`, in the [Full configuration file](https://circleci.com/docs/language-python/#full-configuration-file-new) example of the "Configure a Python application on CircleCI" tutorial.
The executor currently specified isn't the appropriate one.
- https://discuss.circleci.com/t/typo-in-configure-a-python-application-on-circleci-tutorial/52464
- https://circleci.atlassian.net/browse/DOCSS-1663
=> Specifying appropriate executor name for `deploy` job

jekyll/_cci2/ssh-access-jobs.adoc
Adds a note to the Debug with SSH page to direct runner users to head to the runner docs for steps to enable the feature
Improved xrefs, get people to the steps they need
=> Add note RE runner users need to enable ssh rerun feature

jekyll/_cci2/orb-concepts.md
Updating the description of Development orbs to accurately reflect the process.
Currently the docs state that Development orbs do not appear in the registry but that is not true.
Development orbs do appear in the registry but do not properly publish unless the orb has had a production version published initially. The orb-tools workflow [includes a link to the Registry page](https://circleci.com/developer/orbs/orb/circleci/orb-tools#jobs-publish) when an creating a Development orb.
The CLI output bug [has been logged](https://circleci.atlassian.net/browse/LIFE-1124)
Please take a moment to check …
=> update dev orb info

.circleci/config.yml, jekyll/_cci2/about-circleci.adoc
Base directory for linter is not working as expected so no files are currently being linted. Remove base dir until we work out a solution.
=> Remove base dir to lint files

jekyll/_cci2/machine-runner-3-configuration-reference.adoc
Removes an outdated line stating there can be multiple runners on one machine. This is no longer supported on machine runner 3
Removes a sentence presumably taken from the launch agent docs that refers to multiple runners on one host.
Redo of #9124 
Running multiple machine runner 3 instances on one host is not supported, so this was giving false information.
=> Removes reference to using multiple machine runners on one instance

jekyll/_cci2/config-policy-management-overview.adoc, jekyll/_cci2/config-policy-reference.adoc, jekyll/_cci2/create-and-manage-config-policies.adoc
Clarifies that users must be org admins to make changes to manage config policies
Adds a line clarifying that users must be org admins to manage config policies
Redo of #9125 
Previously, the only way users would know this is by trying and failing, or reading one of our blog posts.
This will reduce confusion about who can manage policies
=> Clarifies that admin permissions are required to manage policies

jekyll/_cci2/release/configure-release-markers.adoc, jekyll/_cci2/release/configure-your-kubernetes-components.adoc
Fixing a shell command syntax error in the release job examples.
Customers who copy/paste the examples will run into issues with this error.
=> Fix syntax error in examples

jekyll/_cci2/release/configure-release-markers.adoc
Fix a typo in the release marker command.
=> Fix release marker typo

jekyll/_cci2/enable-checks.md
Adding some context for checks naming between OAuth and App integrations
These are different enough that it could cause some customer confusion.
=> [NOTIFY-94] Indicate difference between OAuth and App Checks naming

jekyll/_cci2/scheduled-pipelines.adoc, jekyll/_includes/partials/pipelines-and-triggers/scheduled-pipeline-setup.adoc, jekyll/_includes/snippets/faq/scheduled-pipelines-faq-snip.adoc
* Add notes to trigger setup steps to say GitHub App pipelines won't appear in the menu when setting up scheduled 
pipelines
* Add FAQ to help Kapa
* expand on existing steps
=> Clarify no options to select GitHub App pipeline in scheduled form

jekyll/_cci2/configuration-reference.adoc
Add details of the serial-group key to the configuration reference
=> Add serial-groups section to config reference

jekyll/_cci2/contexts.adoc, jekyll/_cci2/github-apps-integration.adoc, jekyll/_cci2/version-control-system-integration-overview.adoc, jekyll/_cci2/webhooks.adoc, jekyll/_cci2/workflows.adoc
Changed `#security-goup-restrictions` to `#security-group-restrictions`
Fix typo
=> Fix typo in security group section header

jekyll/_cci2/webhooks.adoc
The current custom webhook example includes an example URL with a variable asking for the user to enter the full URL at the end.
```bash
curl -X POST -H "content-type: application/json" 'https://internal.circleci.com/private/soc/e/<your-URL>?secret=<your-secret>'
```
Updated the example to remove the example URL and just have the variable
```bash
curl -X POST -H "content-type: application/json" '<your-URL>?secret=<your-secret>'
```
Clear up confusion
=> Update Custom Webhook Example

jekyll/_cci2/server/latest/operator/managing-orbs.adoc
Fix typo in server installation URL.
There is a typo in the example for the case of using a server vs. the hosted service.
=> Fix typo in orbs doc

jekyll/_cci2/test-splitting-tutorial.adoc
Fixes #9010 
This PR removes references to using test splitting to reduce credit spend. Test splitting offers a wall clock time optimization.
=> remove references to credit savings when using parallelism

jekyll/_cci2/server/v4.4/installation/phase-3-execution-environments.adoc, jekyll/_cci2/server/v4.5/installation/phase-3-execution-environments.adoc, jekyll/_cci2/server/v4.6/installation/phase-3-execution-environments.adoc, jekyll/_includes/server/latest/installation/phase-3.adoc
…r policy
Correct Machine provisioner IAM policy to include the missing comma `,` after the `<SECURITY_GROUP_ID>` for 4.4/4.5/4.6/4.7 server installation docs
* Prevents confusion when the policy is copy/pasted, improves doc quality
=> Correct missing comma after <SECURITY_GROUP_ID> in policy

jekyll/_cci2/variables.adoc
These environment variables are present in Server
=> Update environment variables that are in server

jekyll/_cci2/server/latest/operator/introduction-to-nomad-cluster-operation.adoc
We made some changes to which address Nomad binds to that makes port-forwarding directly possible again
=> [ONPREM-2101] Update instructions on how to access the Nomad UI

jekyll/_cci2/container-runner.adoc
The logging-collector container requires `list` permissions as of container runner 3.1/GOAT.
=> [ONPREM-1819] Update RBAC permissions required by container runner

.github/CODEOWNERS
Renovate used to require that we remove CODEOWNERS for files in order to auto-merge PRs. It no longer requires this, so let's remove this workaround. 
By _not_ having CODEOWNERS those of us who use GitHub notificatinos don't get pinged for Renovate PRs that touch only the affected files.
cf https://circleci.slack.com/archives/C06BR4CLXAT/p1747045241350629?thread_ts=1747045174.500279&cid=C06BR4CLXAT
NB. It is the owner's responsibility to merge this PR.
[_Created by Sourcegraph batch change `stig/restore-codeowners`._](https://circleci.sourcegraphcloud.com/users/stig/batch-changes/restore-codeowners)
=> Restore CODEOWNERS now that Renovate does not require this workaround

jekyll/_cci2/triggers-overview.adoc
We've had issues where GitHub has changed how they respond to us such that the responses aren't fully consistent. This means there is a possibility that we are returned with data that is slightly stale when their system is processing write requests to their backend.
This note attempts to highlight to customers that this is the case and it's something we can point customers to if they experience any issues like this.
Please take a moment to check through the following items when …
=> Adds consistency information to the custom webhooks triggers overview

jekyll/_cci2/introduction-to-the-circleci-web-app.adoc, jekyll/_cci2/vs-code-extension-overview.adoc
The setting has been enabled for standalone orgs, so it is available in org and project settings under the `Advanced` tab
=> Update `Trigger pipelines with unversioned config` org and project setting docs

jekyll/_cci2/configuration-reference.adoc, jekyll/_includes/snippets/orchestration-examples/override-with.yml
Adding a section for the `override-with` key to the configuration reference page.
The `override-with` key is new and needs to be documented.
=> Adding `override-with` key to config reference

jekyll/_cci2/configuration-reference.adoc, jekyll/_cci2/orb-intro.adoc, jekyll/_includes/snippets/orchestration-examples/override-with.yml
Add content to orbs intro to include URL orbs and introduce the differentiating term "registry orbs"
=> Intro URL orbs

jekyll/_cci2/server/latest/operator/application-lifecycle.adoc, jekyll/_cci2/server/v4.6/operator/application-lifecycle.adoc, jekyll/_cci2/server/v4.7/operator/application-lifecycle.adoc
With the release of [server 4.8](https://circleci.com/changelog/server-release-4-8-0/), the 4.6 version was now EOLed as per [our release cadence](https://circleci.com/changelog/server-releases-moving-to-twice-yearly/).
@vjpandian reminded us to do that [here](https://circleci.slack.com/archives/C016ZEHS3L5/p1751922107926539?thread_ts=1751921030.565419&cid=C016ZEHS3L5).
=> server: update date for 4.6 EOF

ui/src/partials/landing.hbs
- This will avoid needless status `302` redirects in production, and also allow these links to work in the CI preview.
=> Use trailing slashes on all relativised URLs

docs/server-admin/modules/ROOT/partials/installation/phase-3.adoc
Updated AWS MP policy with the explicit subnet input in Server 4.8
This will allow us to have multiple AWS MP Policies controlling different subnets, also, enable the multiple "server" install within the same aws infrastructure. 
=> ONPREM-2481 | SERVER | Update AWS Machine Provisioner policy with explicit subnets

ui/src/js/04-copy-to-clipboard.js, ui/src/js/vendor/highlight.bundle.js
Disable global line numbering for all code blocks. Line numbering created a table structure leading to double spaces when the copy to clipboard button was used.
**In future we will reinstate or create a new line numbering system that we can apply when needed.**
```
version: 2.1
jobs:
hello-job:
docker:
- image: cimg/node:17.2.0 # the primary container, where your job's commands are run
steps:
- checkout # check out the code in the project directory
- run: echo "hello world" # run the `echo` command
workflows:
my-workflow:
jobs:
- hello-job
```
This PR fixes lis by copying just the code lines and connecting them together with single line breaks
```
version: 2.1
jobs:
hello-job:
docker:
- image: cimg/node:17.2.0 # the primary container, where your job's commands are run
steps:
- checkout # …
```
=> Fix code block copy button content

docs/guides/modules/optimize/pages/persist-data.adoc, docs/reference/modules/ROOT/pages/configuration-reference.adoc
The original text is misworded - it says "Job retention reduces the organization-level retention" but job retention has no effect on the overall organization-level retention.
=> Simplify wording in cache retention to add clarity

ui/src/partials/component-explorer-nav.hbs, ui/src/partials/header-content.hbs
The logo top left was linking to the website homepage which is not expected. I have made this link to the docs homepage. 
This change means there is no link to the website from the docs so I added that to the header. Not sure if we want this or not though 🤔 open to opinions:
Make link go to the place you expect
=> link to docs and website homepages

docs/guides/modules/execution-managed/pages/xcode-policy.adoc
Update the Xcode release & deprecation policy with the new deprecation policy and ensure the rest of the document is consistent with current practices.
Current practice with regards to Xcode image release and deprecation diverged from our policy, especially regarding how we announce new images.
=> [EXEC-5670] Update Xcode release & deprecation policy

docs/server-admin/modules/operator/pages/backup-and-restore.adoc
recommend scaling down application before taking backups on server. this will limit the possibility of data corruptions in the backups. Backups are suggested before performing upgrades
https://circleci.atlassian.net/browse/ONPREM-2508
=> recommend scaling down application before backups on server

docs/guides/modules/deploy/pages/configure-deploy-markers.adoc, docs/guides/modules/deploy/pages/configure-your-kubernetes-components.adoc, docs/guides/modules/toolkit/pages/environment-cli-usage-guide.adoc
Added a warning to the deploy markers documentation to clarify that the `circleci run release update` command should only be used with deploy markers (agentless deployments) and not with the CircleCI release agent for Kubernetes deployments.
To prevent confusion and misuse of the `circleci run release update` command when users are working with different deployment methods. The release agent automatically handles status updates, so manual updates should not be used in that context.
REL-4233
=> REL-4233: Add warning about release agent compatibility in deploy markers docs

docs/guides/modules/orchestrate/pages/pipeline-variables.adoc, docs/reference/modules/ROOT/pages/configuration-reference.adoc
Adds documentation with examples for the new `method` key available on the `checkout` step.
=> Document new checkout method key

.github/CODEOWNERS
This batch change replaces all occurrences of '@circleci/lifecycle' with '@circleci/webex' in the matched files.
[_Created by Sourcegraph batch change `kira-m/Webex-Codeowners`._](https://circleci.sourcegraphcloud.com/users/kira-m/batch-changes/Webex-Codeowners)
=> Replace '@circleci/lifecycle' with '@circleci/webex'

docs/guides/modules/migrate/pages/migrating-from-aws.adoc, docs/guides/modules/migrate/pages/migrating-from-azuredevops.adoc, docs/guides/modules/migrate/pages/migrating-from-buildkite.adoc, docs/guides/modules/migrate/pages/migrating-from-github.adoc, docs/guides/modules/migrate/pages/migrating-from-gitlab.adoc, docs/guides/modules/migrate/pages/migrating-from-teamcity.adoc, ui/src/css/doc.css
Our migration pages are (I think) the only pages where we have code blocks in a table.
Some fixes for other UI bugs have made the formatting break on these pages:
- Remove nonumbers class, this is old, from a time when all code blocks had numbered lines
- apply table scroll class correctly
- CSS rule `.tableblock code { white-space: nowrap !important; }` was forcing all code elements in tables to collapse whitespace, removing indentation and line breaks
- target inline code contexts like `td p code`, `td li code`, `.tableblock p code`, and `.tableblock li code` for better reliability and browser support
- Created new CSS rule targeting `.listingblock` elements in tables with `white-space: pre !important` to preserve exact formatting for `[source,yaml]` code blocks
- Eliminated a rule that …
=> fix css for code blocks in tables to fix migration pages

docs/guides/modules/deploy/pages/configure-deploy-markers.adoc
The condition is on_fail and not on_failure.
CCI configs fail if on_failure is used.
=> Change Deploy Markers failure helper text to use the right condition.
