jekyll/_cci2/creating-orbs.md, jekyll/_cci2/orb-author.md, jekyll/_cci2/testing-orbs.md
Adds video tutorials to orb documentation
Easier to understand orb development process
- [x ] Break up walls of text by adding paragraph breaks.
- [x ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [x ] Keep the title between 20 and 70 characters.
- [x ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [x ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [x ] Is …
=> docs(orbs): add instructional videos

jekyll/_cci2_ja/config-overview.md, jekyll/_cci2_ja/configuration-reference.md, jekyll/_cci2_ja/deployment-integrations.adoc, jekyll/_cci2_ja/local-cli.md, jekyll/_cci2_ja/orb-concepts.md, jekyll/_cci2_ja/workflows.md
Fixed redirect settings.
Some English content is getting redirected to Japanese content.
=> Fix redirect

jekyll/_cci2/server-3-operator-vm-service.adoc
https://circleci.atlassian.net/browse/SERVER-1884
* Cleaning up some trailing whitespace
* Adding a section for `vm-service` to utilize encrypted EBS volumes
=> How to encrypt vm-service volumes

jekyll/_cci2/deploying-ios.md
Mostly directing readers to Fastlane Appfile doc in case they need clarification on what credentials should be used.
Hotjar feedback for page
=> Appfile clarification, plus minor fixes

jekyll/_cci2/runner-on-kubernetes.adoc
- Fix a code snippet that was missing proper syntax to render.
- Add headings for crowdin
[Jira Ticket](https://circleci.atlassian.net/jira/software/projects/DOCSTEAM/boards/412?selectedIssue=DOCSTEAM-349)
=> Fix code snippet on page

jekyll/_cci2/gitlab-vcs-support.adoc
Please refer to the following JIRA ticket.
https://circleci.atlassian.net/browse/ACT-274
Please also refer to this PR on `circleci/web-ui-onboarding`.
https://github.com/circleci/web-ui-onboarding/pull/2577
While this copy edit is contained on the New Org Creation Page, it is also repeated here in the docs...so updated here as well.
=> ACT-274: Update copy on New Org Creation Page to be less doom and gloom

jekyll/_data/sidenav.yml
- Add back `Languages` subsection
Currently, a section cannot have a mix of alone pages and subsections. Since `Examples and Guides` already has subsections this is breaking the new site [CI build](https://app.circleci.com/pipelines/github/circleci/docs-platform/1653/workflows/e051e609-cdd4-4d2f-8d2f-4f078815e7fd/jobs/7852) and is preventing the daily content update. 
=> Fix: update `sidenav.yml` structure

jekyll/_cci2/bitbucket-integration.adoc, jekyll/_cci2/github-integration.adoc
This change is to resolve asciidoctor warning.
Crowdin failed to import these two files with the following error 😐 
I checked the fixed file locally and confirmed the page appearance wouldn't break.
=> Fix numbered list

jekyll/_cci2/parallelism-faster-jobs.md
=> add sub-heading for Runner so that we can link to it

jekyll/_cci2/open-source.md
We want the table to have the same classes of the other tables.
Consistency in styling  for `open-source`
=> [DD-696] add classes to table

jekyll/_cci2/gitlab-vcs-support.adoc
Fix broken formatting in GL doc
=> fix Important formatting

jekyll/_cci2/gitlab-vcs-support.adoc, jekyll/_cci2/glossary.adoc, jekyll/_cci2/how-to-use-the-circleci-local-cli.adoc, jekyll/_cci2/insights-snapshot-badge.adoc, jekyll/_cci2/migrating-from-aws.adoc, jekyll/_cci2/migrating-from-azuredevops.adoc, jekyll/_cci2/migrating-from-buildkite.adoc, jekyll/_cci2/migrating-from-github.adoc, jekyll/_cci2/migrating-from-gitlab.adoc, jekyll/_cci2/migrating-from-teamcity.adoc
- Update more crowdin tags - through letter M
- Minor formatting updates
Some asciidoc pages are missing crowdin tags
=> Update crowdin tags

jekyll/_cci2/cci-academy-faqs.md
Created a FAQ page for CircleCI Academy
CircleCI Academy will be down for maintenance for 3 days. During that time, the URL will redirect to this page.
=> Added FAQs page

jekyll/_cci2/server/Installation/phase-1-prerequisites.adoc
In prep for the 4.0 release this PR includes updates to the GKE/GCP instructions for the pre-req section of the installation guide.
- https://circleci.atlassian.net/browse/SERVER-1899
=> Update GKE cluster, DNS and GCP bucket storage instructions

jekyll/_cci2/circleci-images.md, jekyll/_cci2/using-docker.md, jekyll/_data/sidenav.yml
Updating "Using ..." pages for all execution environments to standardise how this information is formatted and presented. This is the Docker PR, there will be a PR for each execution environment.
=> updates to standardise execution env use pages - docker

jekyll/_cci2/test.md, jekyll/_data/sidenav.yml
Revamp of the existing [Test page](https://circleci.com/docs/2.0/test).
Page needs to be revamped to make it a more useful overview.
To do for PR:
=> Revamp Testing overview

jekyll/_cci2/testing-ios.md
Add banner to accompany list of Xcode images and notify readers of deprecation and upcoming EOL.
https://discuss.circleci.com/t/xcode-image-deprecation/44294
=> Xcode image removal warning

jekyll/_data/sidenav.yml
We don't have cookbooks anymore so removing last mention from side nav
=> remove cookbooks from sidebar

jekyll/_cci2/server/installation/migrate-from-server-3-to-server-4.adoc, jekyll/_data/sidenav.yml
copy across changes from #7011
=> Server 1745 version 2

jekyll/_cci2/server/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
More doc fixes for the execution env setup
There is an open question about what Subnets to recommend and how to enforce Security group rules.  But that can come in a later PR
=> [SERVER-1900] execution env

jekyll/_cci2/server/operator/troubleshooting-and-support.adoc
- Added Steps to generate support bundle 
[SERVER-1937](https://circleci.atlassian.net/browse/SERVER-1937
)
=> server-1937-review-support-bundle | added support bundle steps

jekyll/_cci2/server/installation/phase-3-execution-environments.adoc, jekyll/_cci2/server/operator/manage-virtual-machines-with-vm-service.adoc
Adjusting exec environment GCP installation steps for Server 4.0.
- [SERVER-1899](https://circleci.atlassian.net/browse/SERVER-1899)
=> [SERVER-1899] Update execution environment docs

jekyll/_cci2/server/installation/phase-2-core-services.adoc
- Remove a couple of values that area already the default
- add client ID and Secret explicitly to the GHE step
=> SERVER-1900 default values

jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
remove references to a github branch that does not exist
=> [Server-1846] reality check verification

jekyll/_cci2/server/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/installation/phase-2-core-services.adoc, jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
=> Server 4 formatting style

jekyll/_cci2/api-developers-guide.md, jekyll/_cci2/status-badges.md
API related document updates with changes made for Gitlab GA
[EXT-446](https://circleci.atlassian.net/browse/EXT-446)
=> API gitlab doc updates

jekyll/_cci2/webhooks.md
Document new pipeline data model with trigger parameters in webhook docs
https://circleci.atlassian.net/browse/EXT-447
=> Add new webhook data model with trigger parameters

jekyll/_cci2/config-intro.adoc
Hi, i find the config-intro has some a little mistakes in intro every  line code functions
=>  config-intro has some a little mistakes in intro every line code functions

jekyll/_cci2/server/installation/phase-2-core-services.adoc
This PR introduces an example yaml manifest in the docs outlining the basic params that need to be provided for a working cluster in a GCP environment.
https://circleci.atlassian.net/browse/SERVER-1907?atlOrigin=eyJpIjoiYjBiM2Q3NTE0OGIwNGJlZGJjNzQ3ODY4ZDM0NGEyNzciLCJwIjoiaiJ9
=> [SERVER-1907] Adding GCP Happy-Path YAML

jekyll/_cci2/server/installation/phase-4-post-installation.adoc, jekyll/_cci2/server/operator/backup-and-restore.adoc
* Velero Command Update 
[SERVER-1951](https://circleci.atlassian.net/browse/SERVER-1951)
=> server-1951-velero-backup | fixed backup commands

.circleci/config.yml
Ticket: [DD-742](https://circleci.atlassian.net/browse/DD-742)
- Trigger a new pipeline in `docs-platform` when ready to deploy on `master`
- Remove all connections to S3 deployment
- Update nightly build to trigger the `docs-platform` pipeline as well
We need to trigger a pipeline build in `docs-platform` when something is merged in the master of `circleci-docs`. This is done by using our [API](https://support.circleci.com/hc/en-us/articles/360050351292-How-to-trigger-a-workflow-via-CircleCI-API-v2) 
=> [DD-742] Automatic Content Updates

jekyll/_cci2/server/installation/phase-2-core-services.adoc
need to tell the customers where to put it
=> [SERVER-1946] instructions for adding license to values.yaml

jekyll/_cci2/server/installation/phase-2-core-services.adoc
* Introducing a template for AWS to use with CircleCI server 4.0
* Cleaning up whitespace
https://circleci.atlassian.net/browse/SERVER-1906
=> feat: AWS helm chart template for server 4.0

jekyll/_cci2/server/installation/installing-server-behind-a-proxy.adoc, jekyll/_cci2/server/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/installation/phase-2-core-services.adoc, jekyll/_cci2/server/installation/phase-3-execution-environments.adoc, jekyll/_cci2/server/installation/phase-4-post-installation.adoc, jekyll/_cci2/server/operator/managing-build-artifacts.adoc
I have moved the proxy setup steps into the core services installation phase with all the other steps to add to `values.yaml`.
=> move proxy install and formatting

jekyll/_cci2/scheduled-pipelines.md
Added some changes around the scheduled pipeline documentation.
The main motivation is this commit https://github.com/circleci/circleci-docs/commit/975cd7541fea201620f4bef2e05dd92bd8ef1a79, to address the conversations in #7076
Hope this helps!
Happy to update the copy too, as I am not sure if this is the most succinct copy.
=> Update notes about scheduled pipelines

docs/WIDGETS.md
adding syntax for tabs in asciidoc. I'll add to the style guide separately.
=> add asciidoc tabs syntax

jekyll/_cci2/container-agent-kubernetes-runner-open-preview.adoc
Create file for PM to use for new runner doc
Environment not set up locally for PM yet to start own file.
=> Create file for runner doc

jekyll/_cci2/gitlab-vcs-support.adoc
Update the permissions section of the gitlab preview. 
- Update content about roles
- Add permissions matrix
[Jira](https://circleci.atlassian.net/jira/software/c/projects/DOCTEAM/boards/554?modal=detail&selectedIssue=DOCTEAM-699)
=> GitLab permissions

jekyll/_cci2/server/installation/phase-2-core-services.adoc
Here I am, trying to create my own values.yaml override file, and only after I am done do I see the template I needed at the beginning 😄
=> [Server-1962] values examples

jekyll/_cci2/concepts.md, jekyll/_cci2/concurrency.adoc
Update two pages saying which plans can request limit increases.
[Jira](https://circleci.atlassian.net/jira/software/c/projects/DOCTEAM/boards/554?modal=detail&selectedIssue=DOCTEAM-709)
Updated guidance on this.
=> Concurrency limit changes

jekyll/_cci2/docker-layer-caching.md
=> fix bug in docs

docs/CONTRIBUTING.md
- Update style guide link in `CONTRIBUTING.md`
That link was giving me a 404 but the other one is working.
=> Update style guide link

jekyll/_cci2/gitlab-integration.adoc
Update GitLab file name and url
In preparation for wider launch.
=> Change file and url name

jekyll/_cci2/server/installation/phase-2-core-services.adoc, jekyll/_cci2/server/operator/configuring-external-services.adoc
We updated postgres, and now the structure it expects in values.yaml is different
also, whitespace
=> [Server-1996] external postgres

jekyll/_cci2/gitlab-integration.adoc
Change GitLab doc page title.
Consistency around messaging as well as the rest of the VCS documentation.
=> Change page title for conistent messaging

jekyll/_cci2/gitlab-integration.adoc
Change page title for consistency, take two.
[Earlier PR](https://github.com/circleci/circleci-docs/pull/7150) didn't add quite the right title.
=> Change page title for GitLab support doc

jekyll/_cci2/server/operator/configuring-external-services.adoc
Update external mongo setup instructions
@rosieyohannan, may I ask for your help implementing the tabbing structure here as well 🙏
=> [server-1995] configuring creds for external mongo

jekyll/_cci2/server/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/installation/phase-2-core-services.adoc, jekyll/_cci2/server/installation/upgrade-server-4.adoc
needed to update the install instructions to better reflect helm commands referencing and Azure Container Registry
https://circleci.atlassian.net/browse/SERVER-1978
=> Server 1978 install doc updates

jekyll/_data/sidenav.yml
- Change API links so they are treated as external links
This is PR made in tandem with https://github.com/circleci/docs-platform/pull/215. Reasoning is described in that PR :) 
=> [DD-765] Make API links external links

jekyll/_cci2_ja/gitlab-integration.adoc
Translated GitLab support documentation.
As this page is awaited by users, I'm updating it separately from the weekly translation PR.
=> JA translation for GitLab support docs

jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
* Adding command to check Nomad Server-Client communication 
=> no_jira_adding_nomad_command | added nomad node status cmd

jekyll/_cci2/server/installation/phase-2-core-services.adoc, jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
add helm commands for updating
Correct helm commands for installation
also whitespace
=> update helm commands for install, and add them for updates

jekyll/_cci2/server/operator/configuring-external-services.adoc
Update external services instructions to match 4.0
=> [Server-1994] external services

jekyll/_config.yml
Missed the jekyll config in my previous PR
=> Min helm version is now 3.9.2

jekyll/_cci2/collect-test-data.md
Fixed some typo including broken links.
Also, I broke up a long sentence into 2, as I think it may help make it easier to read.
While looking up our docs following debugging for a customer, I noticed the typos around this section.
=> update copy and links for Test Insights section

jekyll/_cci2/server/operator/using-metrics.adoc
The server instructions for telegraf reference KOTS however in server 4.x we will be applying changes via helm directly. This PR updates our instructions
https://circleci.atlassian.net/browse/SERVER-2013
=> Server 2013/update telegraf docs

jekyll/_cci2/reusing-config.md
- Update the code snippet as the current snippet no longer appears in the orb source. The new code snippet is from the current orb source.
- Add note that CircleCI uses mustache syntax behind the scenes, as in this orb.
Mustache syntax can be confusing when users see it, since we don't use it everywhere. This code snippet was brought up in issue https://github.com/circleci/circleci-docs/issues/7130.
=> Update orb syntax

jekyll/_cci2_ja/concepts.md
Fix for markdown emboldening not working properly due to whitespace.
| Before | After |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/37968814/182013812-88694128-db4d-4660-83ad-bcb69495ece2.png" width=500> |  <img src="https://user-images.githubusercontent.com/37968814/182014032-6fb0facf-4399-46eb-bfc4-02911b666ac4.png" width=500> |
https://circleci.com/docs/ja/concepts#%E5%AE%9F%E8%A1%8C%E7%92%B0%E5%A2%83
=> Fix: emboldening

jekyll/_cci2_ja/concepts.md
Corrected markdown italic styling.
| Before | After |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/37968814/182015526-a6859796-d19d-4875-9e35-99d001d202f5.png" width="500"> | <img src="https://user-images.githubusercontent.com/37968814/182015731-f3103744-983b-47b2-9651-2e46473a909a.png" width="500">  |
https://circleci.com/docs/ja/concepts#%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88
=> Fix: making italic

jekyll/_cci2/deploy-to-heroku.adoc
Use adoc snippet (not markdown)
=> Use adoc snippet

.github/pull_request_template.md
This PR fixes the link to the style guide that appears in the PR template
=> fix link to style guide

jekyll/_cci2/runner-on-kubernetes.adoc
Change "sel-hosted" to "self-hosted".
This change fixes a typo in "self-hosted".
=> Change "sel-hosted" to "self-hosted"

jekyll/_data/sidenav.yml
Remove duplicate sidenav
"Using metrics" appears twice in the sidenav
=> Remove duplicates

jekyll/_cci2/runner-installation-linux.adoc
=> missed some i think

jekyll/_cci2/configuration-reference.md
Fix an indentation issue in your YAML.
Invalid indentation.
=> chore(docs): fix indentation

jekyll/_cci2/runner-config-reference.adoc, jekyll/_cci2/runner-faqs.adoc, jekyll/_cci2/runner-installation-linux.adoc, jekyll/_cci2/runner-installation-mac.adoc, jekyll/_cci2/runner-on-kubernetes.adoc
Update instructions for macOS and Linux runner installation.
Update the path for /opt/circleci
New/missing instructions for macOS and Linux install process.
=> Runner installation updates

jekyll/_cci2/artifacts.md, jekyll/_cci2/configuration-reference.md
There was an example for this use case in the wrong place in the config reference. I've moved it into the artifacts page instead.
https://circleci.atlassian.net/browse/DOCTEAM-565?atlOrigin=eyJpIjoiY2Q0ZjhiMDcxMTAxNDgwY2I1MjcwM2I1YmI1ZjQzMzUiLCJwIjoiaiJ9
=> How to upload artifacts for failed tests

jekyll/_cci2_ja/introduction-to-yaml-configurations.adoc
FIx: remove broken a-tag.
Invalid sentence.
=> Fix: remove broken a-tag

jekyll/_cci2/server/installation/phase-2-core-services.adoc, jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
Updates use of the word "secret" with the more accurate "Kubernetes Secret". Also some formatting fixes.
https://circleci.atlassian.net/browse/DOCTEAM-721?atlOrigin=eyJpIjoiZWUzYWNjZDY3NWFjNGUxMTg4YWZiZTM5MjRjMjZiODkiLCJwIjoiaiJ9
=> replace secret with Kubernetes Secret where appropriate

jekyll/_cci2/using-dynamic-configuration.adoc
Update links to correct syntax.
Asciidoc file using markdown syntax.
Closes issue #7226 
=> Udate links

jekyll/_cci2_ja/server/installation/hardening-your-cluster.adoc, jekyll/_cci2_ja/server/installation/migrate-from-server-3-to-server-4.adoc, jekyll/_cci2_ja/server/installation/phase-1-prerequisites.adoc, jekyll/_cci2_ja/server/installation/phase-2-core-services.adoc, jekyll/_cci2_ja/server/installation/phase-3-execution-environments.adoc, jekyll/_cci2_ja/server/installation/phase-4-post-installation.adoc
Updated EN -> JA documentation translations
=> Ja localization

jekyll/_cci2/style/links.adoc
- delete 2.0 from the example URL's path
https://github.com/circleci/circleci-docs/pull/7060
=> delete 2.0 from example URL

jekyll/_cci2/configuration-reference.md
Windows section had translation tag/link to Linux section instead
Bug found in link
=> Fix windows machine image link

jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
Fixed the option number. ("Option 1" is repeated).
https://www.loom.com/share/b7d4b0ad76e2496d8b7aec7c062bca1e
=> Fix option number

jekyll/_cci2/runner-installation-cli.adoc
Updates the table for the correct launch-agent for server 4.0
Server 4.0 was released recently and we're updating which version should be used for it. Using any version newer than this will cause problems and will not be able to run jobs with it.
=> Update the launch-agent version for server 4.0

jekyll/_cci2/caching-strategy.md, jekyll/_cci2/containers.md, jekyll/_cci2/credits.md, jekyll/_cci2/faq.md, jekyll/_cci2/migrating-from-azuredevops.adoc, jekyll/_cci2/migrating-from-gitlab.adoc, jekyll/_cci2/migrating-from-travis.md, jekyll/_cci2/runner-concepts.adoc
Change any examples of "build" to "job" when discussing concurrency if necessary. Also some minor page changes.
Inconsistency with using build vs. job in some areas.
[Jira ticket](https://circleci.atlassian.net/jira/software/c/projects/DOCTEAM/boards/554?modal=detail&selectedIssue=DOCTEAM-543)
=> Build vs job

jekyll/_cci2/style/formatting.adoc, jekyll/_cci2/style/headings.adoc, jekyll/_cci2/style/links.adoc, jekyll/_cci2/style/style-and-voice.adoc, jekyll/_cci2/style/using-code-samples.adoc, jekyll/_cci2/style/using-tables.adoc, jekyll/_data/sidenav.yml
A bunch of updates and additions to the style guide. Here's a link to the marketing style guide too for reference: https://docs.google.com/document/d/1dw9AuGVdNXvxOnaU6fDulaPNPaYhSFncUiiDSzBJOR4/edit#
https://circleci.atlassian.net/browse/DOCTEAM-620?atlOrigin=eyJpIjoiZWVkZGVhZjc3M2JmNDFiOTlkMDI4YTY2YzlhNjVjZDEiLCJwIjoiaiJ9
=> Style guide updates

jekyll/_cci2/server/installation/installation-reference.adoc
I thought this is what it meant while translating. Please close this PR if I'm wrong 😅 
=> Add punctuation

jekyll/_cci2/server/installation/phase-2-core-services.adoc, jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
Use correct quotes in values.yaml examples in server 4 docs
https://circleci.atlassian.net/browse/DOCTEAM-725?atlOrigin=eyJpIjoiOWRhNzg0MWNmY2U1NGJmZmExMjM0OTUyNTg1ZGNlYWIiLCJwIjoiaiJ9
=> Formatting updates for values.yaml

jekyll/_cci2/using-macos.md, jekyll/_includes/snippets/macos-resource-table.md
- Remove examples using unsupported images.
- Minor updates to content.
Two images were being referenced that are no longer being maintained which had already been removed from another page.
[Jira ticket](https://circleci.atlassian.net/jira/software/c/projects/DOCTEAM/boards/554?modal=detail&selectedIssue=DOCTEAM-421)
=> Update macOS page, remove old examples

jekyll/_cci2/runner-overview.adoc
=> can we add to this page as well?

jekyll/_cci2/container-runner.adoc
=> urgent fix

jekyll/_cci2/gitlab-integration.adoc
Clarify what happens when a new email/password account is connected to a VCS account.
[Jira ticket](https://circleci.atlassian.net/browse/DOCTEAM-740)
=> Clarify account merging

jekyll/_data/sidenav.yml
Add Container Runner to sidenav
Forgot this step 😬
=> Add container runner to sidenav

jekyll/_cci2/container-runner.adoc
=> first changes

jekyll/_cci2/container-runner.adoc
=> some additional changes

jekyll/_cci2/deploy-android-applications.adoc, jekyll/_data/sidenav.yml
Tutorial describing deployment for Android apps, using the Android orb. 
[Jira ticket](https://circleci.atlassian.net/browse/DOCTEAM-732)
=> New tutorial for deploying Android apps

jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
* Add filter in AWS commands to output the information customer required
[SERVER-1943](https://circleci.atlassian.net/browse/SERVER-1943)
=> server-1943 | added filters in aws commands

jekyll/_cci2/configuration-reference.md
Remove note about deprecation / EOL of Ubuntu 14.04 and 16.04 images.
These images have been permanently removed from our system.
=> Remove note about deprecated Ubuntu images

jekyll/_cci2/container-runner.adoc
=> update to be more prescriptive

jekyll/_cci2/container-runner.adoc
=> make docs less misleading

jekyll/_cci2/config-policies.md
Help authors avoid collions by calling out need for specific project IDs.
I also tweaked the decide example sto fix CLI changes and call out meta
COpy and pasting docs  will cause policy engine failures and user frustration. 
=> config-policies.md: Update examples for bundle

jekyll/_cci2/deploy-service-update-to-aws-ec2.adoc, jekyll/_cci2/deploy-to-aws.adoc, jekyll/_cci2/ecs-ecr.md
Update config examples to be accurate to the updates to the AWS-ECS orb.
Config examples using this orb are out of date and result in a failing config.
[JIRA ticket](https://circleci.atlassian.net/jira/software/c/projects/DOCTEAM/boards/554?modal=detail&selectedIssue=DOCTEAM-745)
=> aws ecr examples

jekyll/_cci2/runner-api.adoc
=> update bug in docs

jekyll/_cci2/runner-faqs.adoc
=> change wording a bit

jekyll/_cci2/container-runner.adoc
=> fix typos (runner)

jekyll/_cci2/executor-intro.md
=> syntax issues

jekyll/_cci2/container-runner.adoc
Update docs for container-agent about how to run ARM64 container jobs
We are adding ARM64 job support to container-agent, these doc additions let people know some information about that and how to run ARM64 jobs in mixed architecture clusters.
=> Add arm64 container-agent job docs

jekyll/_cci2/runner-faqs.adoc
=> add how to delete tokens

jekyll/_cci2/server/overview/circleci-server-v4-overview.adoc
- s/to not/not to
- gramatically preferred and more idiomatic
=> nit: server4 overview small grammar fix

jekyll/_cci2/runner-on-kubernetes.adoc
=> Change link style

jekyll/_cci2/container-runner.adoc
Add documentation for the Container Agent constraint checker
https://circleci.atlassian.net/browse/RT-674
=> [RT-674] Add docs for constraint checker

jekyll/_cci2/runner-on-kubernetes.adoc
=> make it more obvious that container runner is the way to go

jekyll/_cci2/runner-installation-docker.adoc
=> make more obvious

jekyll/_cci2/server/installation/migrate-from-server-3-to-server-4.adoc
* Removed Postgres chart migrations Instructions as those will be executed as migration script
* `circle-migrator` job will be automatically deleted if completed successfully. 
[SERVER-2047](https://circleci.atlassian.net/browse/SERVER-2047)
=> Server-2047 | Simplified flyway & postgres chart migration

jekyll/_cci2/server-3-operator-vm-service.adoc, jekyll/_cci2/server/operator/manage-virtual-machines-with-vm-service.adoc
Updated list of AMIs for VM service (server v3 and v4)
https://circleci.atlassian.net/browse/SERVER-2037?atlOrigin=eyJpIjoiZjNlNTZlNjcwZjY4NDhkZmIyNjZmYjRiNzE1ZGMzYzAiLCJwIjoiaiJ9
=> Server 3.4.3 ami list update

jekyll/_cci2/env-vars.md
Update project env var doc to clarify that the values can be edited after creation.
Project env vars can currently be "edited" in the web UI by creating a new env var of the same name. 
[Jira ticket](https://circleci.atlassian.net/browse/DOCTEAM-751)
=> Editing project env var

jekyll/_cci2/server/installation/hardening-your-cluster.adoc
Fixes a spelling error with the word "virtual", removes a period from a table.
N/A
=> Fixing spelling error

jekyll/_cci2/executor-intro.md, jekyll/_cci2/runner-faqs.adoc
Fix one typo, change links on one page.
Some changes were overwritten in the last PR.
=> Minor changes, feedback

jekyll/_cci2/runner-installation.adoc
=> language updates

jekyll/_cci2/runner-overview.adoc
=> slight language changes

jekyll/_cci2/runner-installation-linux.adoc
not sure how to edit this but the container runner example shouldnt show up here
=> we shouldnt show the "container runner" on this screen

jekyll/_cci2/container-runner.adoc
=> re-word this

jekyll/_cci2/container-runner.adoc
=> make hello,world more straightforward

jekyll/_cci2/troubleshoot-self-hosted-runner.adoc
=> this link looks weird on the docs

jekyll/_cci2/runner-faqs.adoc
Spelling correction: From Maachine to Machine
=> Spelling correction of Machine

jekyll/_cci2/collect-test-data.md
* Fixed table formatting so easier to read in IDE
* Tagged language examples using data tags
* I have not tagged the Cucumber example - as it's not language specific it will always be visible regardless of which language page filter is selected
https://circleci.atlassian.net/browse/DOCTEAM-777?atlOrigin=eyJpIjoiYjRhODJiNTcwYjNiNDgxYmIwMGQ2ODY1MWZlMGI0ZWMiLCJwIjoiaiJ9
=> Get testing page ready for tagging

jekyll/_cci2/webhooks.md
=> Fixed dead url (404 error)

jekyll/_cci2/env-vars.md
Removed unnecessary parenthesis.
=> Remove unnecessary parenthesis

jekyll/_cci2/server/overview/release-notes.adoc
I‘m not sure if I'm following the right naming convention but it seems that Crowdin requires section tags to be unique. (The updated file was imported successfully.)
Crowdin failed to import the updates with the following messages.
=> Make section tags unique

jekyll/_cci2/server/installation/migrate-from-server-3-to-server-4.adoc
Based on a feedback from customer, I am contributing this PR on their behalf.
As our latest Server version is 4.0.1, I'd like to update the instructions specifying the Server version:
```diff
- 4.0.0
+ 4.0.1
```
> Ideally, the latest version can be dynamically picked up [from our Server release notes](https://circleci.com/docs/server/overview/release-notes) I guess.
In addition, we noted that the `--contexts` option should be `--context` when using `helm diff upgrade`.
```diff
- --contexts
+ --context
```
Ref: https://github.com/databus23/helm-diff#:~:text=for%20Capabilities.APIVersions-,%2DC%2C%20%2D%2Dcontext,-int%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20output%20NUM
Otherwise, a brief sentence about why you made these …
=> update Server 3.x -> Server 4.x migration doc

jekyll/_cci2_ja/orb-intro.md
- Update correct table format for the namespace designations
Table on the [JA page](https://circleci.com/docs/ja/orb-intro) is not rendering correctly. That being said, it does work correctly on the [EN page](https://circleci.com/docs/orb-intro). 
EN: 
JA:
=> Fix: Update `orb-intro.md` to have the correct table format

jekyll/_cci2/hello-world.adoc
I started tagging but there have been some subtle changes since, this fixes them!
https://circleci.atlassian.net/browse/DOCTEAM-789?atlOrigin=eyJpIjoiNzk2Njc1OWQ5OGZiNGEyM2IwZTE3MTcxYmRjZDU3YzkiLCJwIjoiaiJ9
=> Fix hello world tags

jekyll/_cci2/container-runner.adoc
=> link seems dead

jekyll/_cci2/runner-faqs.adoc
=> update to be accurate

jekyll/_cci2/container-runner.adoc
add example to kaniko. but link to Discuss for now because we havent actually tried it ourselves we've only heard customers who said it works for them
=> add example to kaniko

jekyll/_cci2/insights-partnerships.md
Hii CircleCi dev team,
We have many users on our platform who are using CircleCi and would like to instrument it. We’d love to provide a smooth experience for CircleCi users who need to use monitoring solutions, such as New Relic. Please see our [documentation here](https://newrelic.com/instant-observability/circleci).
Please consider adding a link for your direct users to provide an option for New Relic.  For your convenience, we have submitted this PR with our proposed content.
Please feel free to let us know if you have any questions or concerns.
Thank you for your consideration.
=> Updated insights-partnerships.md

jekyll/_cci2/runner-overview.adoc
=> remove preview reference

jekyll/_cci2/runner-on-kubernetes.adoc
=> remove reference to preview

jekyll/_cci2/container-runner.adoc
=> remove references of preview

jekyll/_cci2/orb-intro.md
* Banner to show not currently available on server
* General refresh
https://circleci.atlassian.net/browse/DOCTEAM-769?atlOrigin=eyJpIjoiMTk4Nzc4NDU2M2JlNGRmMmI2N2Y2NDQwNzE2YWExODgiLCJwIjoiaiJ9.
=> Orb view page updates

jekyll/_cci2/runner-faqs.adoc
Add information about container runner versions and support to the FAQ
https://circleci.atlassian.net/browse/RT-735
=> Rt 735/container agent support def

jekyll/_cci2/circleci-config-sdk.adoc
Fixed typo conguration -> configuration
=> fix tiny typo

jekyll/_cci2/api-developers-guide.md, jekyll/_cci2/api-intro.md
=> Private repos can use basic auth with API calls

jekyll/_cci2/container-runner-installation.adoc
=> can we just simplify this and not have this auth stuff?

jekyll/_cci2/config-intro.adoc
Seems like there was an update which cause description and code snippet not match.
To make the reader not confused about the tutorial for the first time.
=> Correct tutorial description

jekyll/_cci2/container-runner.adoc
=> add a known limitation

jekyll/_config.yml
Increase Maximum record size to conform to paid limits in Algolia.
With additional features, we need to allow utilization of the storage space already allowed to us on our plan
=> [DD-903] increase record size for algolia records

jekyll/_cci2/config-policy-management-overview.adoc
Adding a link to quickstart how to steps to the feature overview page for people who just want to have a go
Also added one sentence to scope who should be interested in the doc/feature.
https://circleci.atlassian.net/browse/DOCTEAM-809?atlOrigin=eyJpIjoiYzc1NmFlNmU3OGI1NDE2ZWE5NTNhYmY5NjY4ZWQxMzUiLCJwIjoiaiJ9
=> CPM quickstart pointer

jekyll/_cci2/gitlab-integration.adoc
Account merge info no-longer accurate
https://circleci.atlassian.net/browse/DOCTEAM-795?atlOrigin=eyJpIjoiODEwOWI3NGZlMmE3NGQ1YmFiOWFlZWYzZWM0Y2I1NGYiLCJwIjoiaiJ9 (this ticket has been reopened)
=> remove content around account merging

jekyll/_cci2/migrating-from-gitlab.adoc
Remove requirement to move GL source code to GH or BB and replace with guidance to connect GL account with CircleCI.
https://circleci.atlassian.net/browse/DOCTEAM-773?atlOrigin=eyJpIjoiMjI2MTFiM2Y3ZTIwNDVhZTg1ODdhN2VhNzI4MDUwNDgiLCJwIjoiaiJ9
=> GitLab migration guide to include connect GL account to CCI

jekyll/_cci2/container-runner.adoc
=> add a reference to this page for how to get started

.circleci/config.yml
update text in config.yml to indicate tool used to generate api v2 docs
=> update tool used for api v2 gen

docs/CONTRIBUTING.md
Made line 5 easier to read and rephrased line 35. @Mayuko-Sa Please review.
Split the sentence of line 5 to make it easier to understand. Rephrased line 35 to make it look better.
To improve the quality of the documentation.
=> Fixed documentation errors.

jekyll/_cci2/gitlab-integration.adoc
Account merge has been removed
https://circleci.atlassian.net/browse/DOCTEAM-795?atlOrigin=eyJpIjoiNDM5MTIyNjg0YmI2NGJkMzg2YzFmN2UzYWFkNGM3NGYiLCJwIjoiaiJ9
=> remove details of modal RE account merge

jekyll/_cci2/faq.md
- Update refill from 2% to 0
- Add all sections to the table of contents
Update to billing.
[JIRA ticket](https://circleci.atlassian.net/jira/software/c/projects/DOCTEAM/boards/554?modal=detail&selectedIssue=DOCTEAM-819)
=> Updates credits FAQ

jekyll/_cci2/contexts.md
We found this typo re: removing a project from restricted contexts, when Saori was translating this contexts.md page.
Thank you Saori!
=> fix: typo re: removing projects from context restriction

jekyll/_cci2/ip-ranges.md
Saori (translator) asked about this alt text. Is this what it means? 😅 
Screenshot:
=> Update alt text for a screenshot

jekyll/_cci2/concepts.md, jekyll/_cci2/config-intro.adoc, jekyll/_cci2/configuration-reference.md, jekyll/_cci2/ecs-ecr.md, jekyll/_cci2/gitlab-integration.adoc, jekyll/_cci2/index.md, jekyll/_cci2/language-javascript.md, jekyll/_cci2/language-python.md, jekyll/_cci2/notify-a-slack-channel-of-a-paused-workflow.adoc, jekyll/_cci2/triggers-overview.adoc, jekyll/_cci2/workflows.md, jekyll/_cci2/workspaces.md
Change descriptions of workflows to "orchestrate" where relevant
https://circleci.atlassian.net/browse/DOCTEAM-800?atlOrigin=eyJpIjoiZWQ1MjNlMzQxOTYzNGZkYmE2NTU2NzlhZjJlMWY0ZTkiLCJwIjoiaiJ9
=> Language change: workflows orchestrate, not just schedule

src-api/README.md
Add some draft details for how we can update templates for api v2 docs
=> draft details for developing api v2 docs content

jekyll/_includes/snippets/xcode-intel-vm.md
Update xcode version in table.
New xcode release.
closes #7510 
=> Update xcode table

jekyll/_includes/snippets/xcode-intel-vm.md
Table formatting in: https://circleci.com/docs/testing-ios/ has got _wobbly_.
=> table formatting fix

jekyll/_cci2_ja/language-javascript.md
Updated JA URLs to EN
These were 404s:
=> 404 to JA Blog Post

src-api/openapi-patch.json
This PR updates the template for our API code examples to use the `Circle-Token` request header.
[Jira ticket](https://circleci.atlassian.net/browse/DOCTEAM-761)
We want to encourage users to use the preferred `Circle-Token` authentication method.
=> Update authentication scheme for API code examples

jekyll/_includes/snippets/xcode-metal.adoc
Fixed URL syntax.
Sorry I was one of the approvers of this change ([#7506](https://github.com/circleci/circleci-docs/pull/7506)) 😅 
Screenshot:
=> Change URL syntax

jekyll/_cci2/caching.md
=> storage misspelled in caching.md

src-api/README.md
Some changes I made recently turned out to be inaccurate.
=> some api docs generation updates

jekyll/_cci2/android-machine-image.md, jekyll/_cci2/deploy-android-applications.adoc, jekyll/_cci2/deploy-ios-applications.md, jekyll/_cci2/deploy-over-ssh.adoc, jekyll/_cci2/deploy-service-update-to-aws-ec2.adoc, jekyll/_cci2/deploy-to-artifactory.md, jekyll/_cci2/deploy-to-aws.adoc, jekyll/_cci2/deploy-to-azure-container-registry.adoc, jekyll/_cci2/deploy-to-capistrano.adoc, jekyll/_cci2/deploy-to-cloud-foundry.adoc, jekyll/_cci2/deploy-to-firebase.adoc, jekyll/_cci2/deploy-to-google-cloud-platform.adoc, jekyll/_cci2/deploy-to-heroku.adoc, jekyll/_cci2/deploy-to-npm-registry.adoc, jekyll/_cci2/deployment-overview.adoc, jekyll/_cci2/publish-packages-to-packagecloud.md, jekyll/_includes/snippets/add-version-number.adoc, jekyll/_includes/snippets/add-version-number.md
- Add blurb about new deploy focused images
- Minor page changes to deploy section
- Add snippet to include for examples with placeholders
New images exist for four deployment methods
=> Deploy examples

jekyll/_cci2/using-windows.md
=> updated windows orb versions & docker ex. (cloud)

jekyll/_cci2/language-javascript.md, jekyll/_cci2/language-python.md, jekyll/_cci2/parallelism-faster-jobs.md
* Linked to test splitting tutorial from relevant docs
* Some content refresh work to test splitting page to improve flow mainly
I have made a separate ticket for making a quickstart guide for test splitting which eventually can be linked to from this doc straight after the Introduction as per the content template.
https://circleci.atlassian.net/browse/DOCTEAM-674?atlOrigin=eyJpIjoiZWE5NWY5OGU0NDBlNDBhYmFhOWZjMzJkMTY1NzlhN2IiLCJwIjoiaiJ9
=> Test splitting page and tutorial updates

.circleci/config.yml
ensure that the deploy does not go forward without a valid build of the project
Seeing a default behavior surface in which deploy may complete without a valid build.
=> add require to deploy

jekyll/_cci2/configuration-reference.md, jekyll/_cci2/migrate-scheduled-workflows-to-scheduled-pipelines.adoc, jekyll/_cci2/workflows.md
Update note about postponement
^^
=> Postpone deprecation of scheduled pipelines

jekyll/_cci2/oss.md
=> add note that you can ovrerride this via support ticket

jekyll/_cci2/orb-intro.md
Content refresh of orbs intro page
Needed a refresh
=> Refresh orbs intro

jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
I was setting up Server 4 when I noticed some minor typos.
This is a PR to address them :)
=> docs: fix typos on Phase 3 docs for Server 4

jekyll/_cci2/github-integration.adoc
Our description was outdated
https://circleci.atlassian.net/browse/DOCSS-864?atlOrigin=eyJpIjoiODg2NTNlNjFjMDg4NGJiZGFiOTA0Y2YzMDE1OTkwMzQiLCJwIjoiaiJ9
=> Update section describing GH scope limitations

jekyll/_cci2/server-3-whats-new.adoc, jekyll/_config.yml
* What's new entry for 3.4.4 (link won't work until https://github.com/circleci/circleci.com/pull/6562 goes live)
* Update server version in Jekyll config
3.4.4 release
=> server 3.4.4 release docs

jekyll/_includes/snippets/xcode-intel-vm.md
Add Xcode 14.2 RC to Xcode table with link to manifest and release notes
=> Add Xcode 14.2 RC to Xcode table

jekyll/_cci2/server-3-faq.adoc
https://circleci.slack.com/archives/C4C9J5KHN/p1670880353020899?thread_ts=1670873048.024299&cid=C4C9J5KHN
=> make more explicit that Insights data is not stored indefinitley

jekyll/_cci2/orb-author-faq.md
https://circleci.atlassian.net/browse/FLEETS-1198
=> https://circleci.atlassian.net/browse/FLEETS-1198

jekyll/_data/sidenav.yml
This PR reorganizes some of our existing pages into a new (top level) Security and permissions section on the sidenav.
It does not include a "Tutorials" subsection yet, as we don't have existing content for it (one tutorial in our ticket backlog).
In the current side nav, Security is a subsection of the top level "Projects" section. Security and permissions is an important topic and should have a more prominent, findable place within our documentation.
=> New section: Security and permissions

jekyll/_data/sidenav.yml
This PR adds a new section called Developer Toolkit, which encompasses varying tools and feature sets that help developers interact with and manage their CircleCI projects. This section also helps developers navigate to other helpful / reference pages such as Examples and Guides Overview (which links out to pages that are still currently in a standalone "Examples and guides" section in the sidenav - this will go away when the other pages have been reorganized).
Putting these pages together under one section/category makes them more easily navigable and findable.
Please take a moment to check …
=> New Developer Toolkit section

jekyll/_cci2/server/overview/release-notes.adoc
Section for server 4.0.2
[Jira ticket](https://circleci.atlassian.net/browse/DOCSS-919)
=> Add section for server 4.0.2

jekyll/_cci2/audit-logs.adoc
=> Changes to self serve audit logs

jekyll/_cci2/audit-logs.adoc
=> Fix for bulleted list

jekyll/_cci2/rotate-project-ssh-keys.adoc, jekyll/_data/sidenav.yml
New page detailing how to rotate project SSH keys for each VCS
[Jira ticket](https://circleci.atlassian.net/jira/software/c/projects/DOCSS/boards/554?modal=detail&selectedIssue=DOCSS-926)
=> [WIP] Rotate SSH keys page

jekyll/_cci2/rotate-project-ssh-keys.adoc
=> Fix capitalization

jekyll/_data/api.yml, src-api/source/includes/_keys.md
As of [circle/#14273](https://github.com/circleci/circle/pull/14273/files) the checkout-key endpoint supports a `digest` query parameter on the v1 API. The V1 API is documented manually, so this PR updates the documentation to reflect this parameter.
- See https://github.com/circleci/circle/pull/14273 and CIRCLE-40018
=> (CIRCLE-40018) document digest flag

src-api/README.md
=> update readme to show how to build API v1 docs locally

jekyll/_cci2/testing-orbs.md
=> Add example for how to ignore for Review

jekyll/_cci2/about-circleci.md, jekyll/_cci2/benefits-of-circleci.adoc, jekyll/_cci2/concepts.md, jekyll/_cci2/introduction-to-the-circleci-web-app.adoc, jekyll/_data/sidenav.yml, jekyll/_includes/snippets/pipelines-benefits.adoc
=> About section

jekyll/_cci2/credits.md, jekyll/_cci2/plan-free.adoc, jekyll/_cci2/plan-overview.adoc, jekyll/_cci2/plan-performance.adoc, jekyll/_cci2/plan-scale.adoc, jekyll/_cci2/plan-server.adoc, jekyll/_data/sidenav.yml
Keeping this section in the same position in the sidebar.
This PR also moves the Credits page from Projects > Settings to the Plans section. In a later PR we'll redistribute the Credits content to relevant pages and archive credits.md
Sidebar reorg
=> Sidebar: Plans and pricing

jekyll/_data/sidenav.yml
Updating sidenav icons on JA site to match EN.
There are some new sections/pages that haven't been added to the JA site yet - this will be completed in a separate PR.
=> Sync icons for JA site

jekyll/_cci2/fail-fast.adoc
Fix code snippet indentations
Code snippet indentation fixes for consistency, and one comment that was not displaying as a proper comment because it needs to be on its own line to properly display with comment styling.
=> Fix code snippet indentations

jekyll/_cci2/jira-plugin.md, jekyll/_cci2/notifications.md, jekyll/_data/sidenav.yml
* Created Integration section
* Fixed JIRA -> Jira
Sidebar plan
=> create integration section

jekyll/_data/sidenav.yml
Remove the YAML config intro from beginner tutorials.
This page is not actually a tutorial as there are no actionable steps for a user, rather it is a reference tool. This page also exists in the Onboarding section.
=> Remove duplicate item in navigation

jekyll/_cci2/server-3-install-prerequisites.adoc, jekyll/_cci2/server/installation/phase-1-prerequisites.adoc
- removed minio api gateway reference
- Minio API Gateway is deperecated. 
=> server-2264 | removed minio api gateway reference

jekyll/_cci2/insights-glossary.md, jekyll/_cci2/insights-snapshot-badge.adoc, jekyll/_cci2/insights.md, jekyll/_data/sidenav.yml
This PR renames the existing Insights section to Project Insights. 
The old Data partnerships page has been removed from this section and split into multiple pages under a new Integrations section in PR #7702 .
This PR also includes a minor refresh of the Insights content (e.g. some rephrasing, updates in URL syntax, etc)
Docs sidebar reorg
=> Project insights section

jekyll/_data/sidenav.yml
Reorg the getting started section in the sidenav.
Was not up to date with the current plan.
=> Reorg getting started section

jekyll/_cci2/parallelism-faster-jobs.md
=> works on windows now

jekyll/_cci2/databases.md
Duplicate of #7685 
Original PR is unresponsive with issue relating to PR.
=> Update databases optimization

jekyll/_data/sidenav.yml
name change confusion in feature name change has broken this link
=> correct file name

jekyll/_cci2_ja/create-and-manage-config-policies.adoc
update snippet to ja version for ja doc
an english snippet was being displayed on a translated page
=> update link to ja snippets

jekyll/_cci2/runner-installation-cli.adoc
Update launch agent versions for server to include new patched versions
Jira ticket: https://circleci.atlassian.net/browse/RT-923
=> [RT-923] Update launch agent versions for server

jekyll/_cci2/server/installation/phase-2-core-services.adoc
=> correct helm value

jekyll/_cci2/sample-config.md
Add server 4 example tabs
v4 is the latest version of server so this needs to be reflected in our examples. v3 and v4 samples are the same so when v2 is removed we can revert back to just Cloud and Server tabs 🎉 .
=> add server 4 examples on sample config page

jekyll/_cci2/server-3-whats-new.adoc, jekyll/_config.yml
Docs  for patch release server 3.4.5
=> Server 3.4.5

jekyll/_cci2/executor-intro.md
- Add a small section in the executor intro page about port ranges.
- Update link style in file.
Customer was looking for this information in the docs and couldn't find it. This could potentially be an issue customers come across and not understand why.
=> Add port ranges info

jekyll/_cci2/server/v4.1/operator/troubleshooting-and-support.adoc
Describing to a customer in an air-gap environment how to utilize a REPL.
REPL usage is sometimes offered as a solution to problems by our support teams.
=> Air-gap REPL

jekyll/_data/sidenav.yml
This document was previously not included in the sidenav. We'll add it under the Optimize section for now until more of the sidenav reorg is complete.
This doc is relevant for the Docker executor as well as runner, so in the future this how-to will be added under those relevant sidenav sections as well.
=> Java OOM doc to sidenav

jekyll/_cci2/scheduled-pipelines.adoc
This PR rolls back new content for the scheduled pipelines orb.
Request from CPE.
=> Roll back update for orb

jekyll/_cci2/runner-installation-cli.adoc
Update launch agent versions for server to include new patched versions
Jira ticket: https://circleci.atlassian.net/browse/RT-923
=> [RT-923] Update server launch agent versions

jekyll/_cci2/container-runner.adoc
Container agent now set resource limits for the logging container, updating docs to specify the specs
Jira: https://circleci.atlassian.net/browse/RT-744
=> updating container-agent logging spec

jekyll/_cci2/config-policy-management-overview.adoc, jekyll/_cci2_ja/config-policy-management-overview.adoc
https://circleci.atlassian.net/browse/SNC-183
Fix reference to create-a-policy
Link was broken
=> [SNC-183] Fix create-a-policy reference

jekyll/_cci2/config-policy-management-overview.adoc, jekyll/_cci2/use-the-cli-for-config-and-policy-development.adoc
This PR adds reference to `vcs` metadata in Config Policies.
https://circleci.atlassian.net/browse/SNC-166
=> [SNC-166] Add documentation for `vcs` metadata

jekyll/_cci2/config-editor.md, jekyll/_cci2/introduction-to-yaml-configurations.adoc, jekyll/_cci2/vs-code-extension-overview.adoc, jekyll/_data/sidenav.yml
=> Overview page for VS Code extension

jekyll/_cci2_ja/server/installation/migrate-from-server-2-to-server-4.adoc
Add translated version of existing page
=> Translated version of server 2 to 4 migration guide

jekyll/_cci2/fail-fast.adoc
=> typos & a new note

jekyll/_cci2_ja/server-3-operator-metrics-and-monitoring.adoc
Remove all metrics other than prometheus from server 3 docs
mirroring change to EN page
=> New Japanese Translations

jekyll/_cci2/insights.md
=> Fixing a typo

jekyll/_cci2/testing-ios.md, jekyll/_cci2/using-macos.md, jekyll/_includes/snippets/macos-resource-table.md
Update "Apple silicon support" section now that we have M1 support. Also add M1 Xcode support table to "Using macOS" page.
=> Update apple silicon support

jekyll/_cci2/first-steps.adoc, jekyll/_cci2/gitlab-integration.adoc
- Describes config setup options that are now available for new GitLab projects in CircleCI. Does not include screenshots.
- Also edits/moves existing content around in the Sign up and Trigger a pipeline sections of the [GitLab integration doc](https://circleci.com/docs/gitlab-integration/), for flow and clarity.
Did not include screenshots because we already have similar ones on our [Quickstart guide](https://circleci.com/docs/getting-started/) with GH and BB projects, although the UI copy is slightly different. Holding back on screenshot in case the UI is changed for consistency. The text should describe the config setup options in detail.
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://ci …
=> New config setup for GitLab

jekyll/_cci2/openid-connect-tokens.adoc, jekyll/_includes/snippets/built-in-env-vars.adoc
Update OIDC doc
There is a new OIDC token available, and new additional claims
=> OIDC updates

jekyll/_cci2_ja/vs-code-extension-overview.adoc
=> VS code extension Japanese

jekyll/_cci2/fail-fast.adoc
=> update clojure example

jekyll/_cci2/parallelism-faster-jobs.md
Added a comma in the Introduction
First line: Pipelines are often configured so that each time code is committed, a set of tests are run.
For understanding/clarity.
=> Added a comma in the Introduction

jekyll/_cci2/about-circleci.md, jekyll/_cci2/bitbucket-integration.adoc, jekyll/_cci2/github-integration.adoc, jekyll/_cci2/gitlab-integration.adoc, jekyll/_data/sidenav.yml
=> SEO FIX: update page titles and sidebar

jekyll/_cci2/test-config-policies.adoc
Updated incorrect file extensions
-
=> FIX: config policy test files should be .yaml

jekyll/_cci2/test-config-policies.adoc
Added description of JSON + JUnitXML support.
https://circleci.atlassian.net/browse/SNC-193
=> [SNC-193] Config-Policies testing update

jekyll/_cci2/server/installation/hardening-your-cluster.adoc, jekyll/_cci2/server/installation/installation-reference.adoc, jekyll/_cci2/server/installation/installing-server-behind-a-proxy.adoc, jekyll/_cci2/server/installation/migrate-from-server-2-to-server-4.adoc, jekyll/_cci2/server/installation/migrate-from-server-3-to-server-4.adoc, jekyll/_cci2/server/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/installation/phase-2-core-services.adoc, jekyll/_cci2/server/installation/phase-3-execution-environments.adoc, jekyll/_cci2/server/installation/phase-4-post-installation.adoc, jekyll/_cci2/server/installation/upgrade-server-4.adoc, jekyll/_cci2/server/operator/application-lifecycle.adoc, jekyll/_cci2/server/operator/backup-and-restore.adoc, jekyll/_cci2/server/operator/circleci-server-security-features.adoc, jekyll/_cci2/server/operator/configuring-external-services.adoc, jekyll/_cci2/server/operator/expanding-internal-database-volumes.adoc, jekyll/_cci2/server/operator/faq.adoc, jekyll/_cci2/server/operator/introduction-to-nomad-cluster-operation.adoc, jekyll/_cci2/server/operator/manage-virtual-machines-with-vm-service.adoc, jekyll/_cci2/server/operator/managing-build-artifacts.adoc, jekyll/_cci2/server/operator/managing-load-balancers.adoc, jekyll/_cci2/server/operator/managing-orbs.adoc, jekyll/_cci2/server/operator/managing-user-accounts.adoc, jekyll/_cci2/server/operator/operator-overview.adoc, jekyll/_cci2/server/operator/troubleshooting-and-support.adoc, jekyll/_cci2/server/operator/usage-data-collection.adoc, jekyll/_cci2/server/operator/user-authentication.adoc, jekyll/_cci2/server/overview/circleci-server-v4-overview.adoc, jekyll/_cci2/server/overview/release-notes.adoc
Correct content tagging syntax to make platform tag visible
=> update content tagging syntax

jekyll/_cci2/xcode-policy.md
Just a few small tweaks to some of the wording to clarify things
=> Tweaks to wording of Xcode image policy

jekyll/_cci2/server-3-whats-new.adoc, jekyll/_cci2/server/installation/migrate-from-server-3-to-server-4.adoc, jekyll/_cci2/server/overview/release-notes.adoc, jekyll/_cci2/server/v4.1/air-gapped-installation/phase-3-install-circleci-server.adoc, jekyll/_cci2/server/v4.1/installation/migrate-from-server-3-to-server-4.adoc, jekyll/_cci2/server/v4.1/installation/phase-2-core-services.adoc, jekyll/_cci2/server/v4.1/installation/phase-3-execution-environments.adoc, jekyll/_cci2/server/v4.1/overview/release-notes.adoc, jekyll/_config.yml
Patch releases for server v3.4.6, v4.1.1 and v4.0.3
=> Patch releases for server

jekyll/_cci2_ja/ssh-access-jobs.md
I accidentally added a character to a page description. This PR removes it.
=> Fix page meta data

jekyll/_data/sidenav.yml
remove item from sidebar, duplicate
=> remove item incorrectly placed and duplicated in the sidebar

jekyll/_cci2/deploy-to-aws.adoc
Resolves #7919 .
The `overwrite` parameter is no longer used in this version of the s3 orb.
=> Remove out of date parameter from code example

jekyll/_cci2/rerun-failed-tests-only.adoc
=> remove the "note"

jekyll/_data/sidenav.yml
=> Fix sidebar section title

jekyll/_cci2/test.md
=> add a link to preview

jekyll/_cci2/env-vars.md
Document the new `env subst` circleci cli command
=> docs: add 'env subst' command

jekyll/_includes/snippets/macos-resource-table.md
Quick fix to remove disclaimer that M1 is only available on annual plans.
On April 18, we added M1 to Perf plans.
=> Update availability since M1 is available on all paid plans

jekyll/_cci2/server-3-whats-new.adoc
Add new section on what's new page with link to changelog for server 3.4.7
=> server 3.4.7

jekyll/_includes/snippets/xcode-silicon-vm.md
The remaining Xcode images are now available on our M1 resource class.
[MAC-1586](https://circleci.atlassian.net/browse/MAC-1586)
[MAC-1586]: https://circleci.atlassian.net/browse/MAC-1586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MAC-1586] Update Apple silicon table with remaining images

jekyll/_cci2/high-uid-error.md, jekyll/_data/sidenav.yml
This page was not in the sidebar
Sidebar reorg
=> Add debugging page to sidebar

jekyll/_cci2/rerun-failed-tests-only.adoc
=> add split by timing to examples to avoid confusion

crowdin.yml
Update crowdin config to include all snippets in directories
currently there's a bunch of untranslated snippets
=> translate all snippets

jekyll/_includes/snippets/faq/ja/architecture-faq-snip.adoc, jekyll/_includes/snippets/faq/ja/billing-faq-snip.adoc, jekyll/_includes/snippets/faq/ja/dedicated-hosts-macos-faq-snip.adoc, jekyll/_includes/snippets/faq/ja/dynamic-configuration-faq-snip.adoc, jekyll/_includes/snippets/faq/ja/general-faq-snip.adoc, jekyll/_includes/snippets/faq/ja/host-faq-snip.adoc, jekyll/_includes/snippets/faq/ja/migration-faq-snip.adoc, jekyll/_includes/snippets/faq/ja/orb-author-faq-snip.adoc, jekyll/_includes/snippets/faq/ja/orb-faq-snip.adoc, jekyll/_includes/snippets/faq/ja/pipelines-faq-snip.adoc, jekyll/_includes/snippets/faq/ja/scheduled-pipelines-faq-snip.adoc, jekyll/_includes/snippets/faq/ja/self-hosted-runner-faq-snip.adoc, jekyll/_includes/snippets/faq/ja/workflows-faq-snip.adoc, jekyll/_includes/snippets/troubleshoot/ja/orb-troubleshoot-snip.adoc, jekyll/_includes/snippets/troubleshoot/ja/pipelines-troubleshoot-snip.adoc, jekyll/_includes/snippets/troubleshoot/ja/self-hosted-runner-troubleshoot-snip.adoc
This PR is made up of the cheery-picked commits from the auto-generated PR made by Crowdin. It adds in missing snippets.
Some are partial translations but we need this content available to remove some duplicate pages.
=> Add ja snippets for FAQ and troubleshooting

jekyll/_cci2_ja/resource-class-overview.adoc
Fix a xref that was causing problems in another build
=> Fix resource class xref

jekyll/_cci2/rerun-failed-tests-only.adoc
=> a couple of additions

jekyll/_cci2/server/installation/phase-3-execution-environments.adoc, jekyll/_cci2/server/v4.1/installation/phase-3-execution-environments.adoc
We have hardcoded the port as 4647 in server 4.x.
=> chore: Remove port from Nomad Terraform

jekyll/_cci2/using-shell-scripts.md
Fix typo.
Spotted while reading.
N.b. nice style guide, covers it well.
=> Fix typo in `using-shell-scripts.md`

jekyll/_includes/snippets/secrets-masking.md
Add warning about secrets masking, and reformatting at output
Clarification of scope
=> Secrets masking warning

jekyll/_cci2/openid-connect-tokens.adoc, jekyll/_includes/snippets/built-in-env-vars.adoc, jekyll/_includes/snippets/find-organization-id.adoc
* use numbered steps where appropriate
* I've followed the steps in the AWS console to check they are correct
* tried to improve flow for readers as they will be following our docs and aws docs at the same time 😬 
* remove references to needing to use a context to get access to these env vars, confirmed as outdated by SNC team
Improve formatting before adding a new how-to guide for OIDC
=> Reformat AWS OIDC instructions

jekyll/_cci2/openid-connect-tokens.adoc, jekyll/_cci2/private-images.adoc, jekyll/_cci2/pull-an-image-from-aws-ecr-with-oidc.adoc, jekyll/_data/sidenav.yml
* Add how-to for configuring a job to pull and image from AWS ECR
* Update private-images page to link to this how to guide and present this method as the best-practice
* Add to the sidebar
* link to new page from main OIDC page
=> How to guide for pull image from ECR using OIDC

jekyll/_cci2/server/v4.1/overview/release-notes.adoc, jekyll/_config.yml
Docs updates for server v4.1.3 patch
=> server v4.1.3 release

jekyll/_cci2/faq.adoc, jekyll/_cci2/plan-overview.adoc, jekyll/_cci2/plan-performance.adoc, jekyll/_includes/snippets/faq/cancel-subscription-faq-snip.adoc
* Add a set of [FAQs](https://circleci.com/docs/faq/) (saved as a snippet) on cancelling a Performance plan subscription.
* Add backlinks to FAQ from Plan docs.
Easier to direct readers to details regarding cancelling the plan.
=> Performance plan cancellation FAQs

jekyll/_includes/snippets/xcode-intel-vm.md, jekyll/_includes/snippets/xcode-silicon-vm.md
=> Add Xcode 14.3.1

jekyll/_cci2/runner-api.adoc, jekyll/_cci2_ja/runner-api.adoc
Update the runner API version to v3 (This is the current actively developed version)
https://circleci.atlassian.net/browse/RT-964
=> [RT-964] Update runner API to v3

jekyll/_cci2/configuration-reference.md
* adds oidc field to config ref
* Also add more section headings to make auth clearer
=> Add aws oidc to config reference

jekyll/_includes/snippets/macos-resource-table.md
[Jira Ticket](https://circleci.atlassian.net/browse/MAC-1644)
Add M1 Medium and specs to macOS resource class table in prep for launch.
We are launching M1 Medium on June 7 to all paid plans.
=> [MAC-1644] Add M1 Medium resource to macOS resource table

jekyll/_includes/snippets/xcode-intel-vm.md, jekyll/_includes/snippets/xcode-silicon-vm.md
Add Xcode 15 beta 1 to support tables
Note: Do not merge until announcement is live (and added to this PR) 😄 
Xcode 15 beta 1 has been released
=> Add Xcode 15 beta 1

jekyll/_cci2/openid-connect-tokens.adoc
Added a caution banner to let people know that if they allow forked PRs OIDC tokens won't be generated unless they allow secrets for forked PRs
Security concerns
=> add caution about tokens and forks

jekyll/_cci2/dynamic-config.adoc, jekyll/_cci2/using-dynamic-configuration.adoc
Dynamic config is supported on server 3 and 4 so add tags
Tags were missing making it look like feature was unsupported
=> Add server tags to dynamic config docs

jekyll/_cci2/server/v4.1/air-gapped-installation/phase-1-prerequisites.adoc
Replaces support@circleci.com with support.circleci.com in server documentation.
[DOCSS-1182]
[DOCSS-1182]: https://circleci.atlassian.net/browse/DOCSS-1182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Replace support@circleci.com with support.circleci.com

jekyll/_cci2/server/v4.1/installation/installation-reference.adoc, jekyll/_cci2/server/v4.1/operator/troubleshooting-and-support.adoc, jekyll/_cci2/server/v4.1/overview/release-notes.adoc, jekyll/_config.yml
=> server 4.1.4 docs updates

crowdin.yml
add runner and server snippets to crowdin sync
needed for localization of all adoc content
=> add all snippets to crowdin config

jekyll/_cci2/create-project.adoc
internal context: https://circleci.atlassian.net/wiki/spaces/PECV/pages/6862012656/Inference+2
add in details that some users may see a different experience
=> prepare for inference rollout

jekyll/_cci2/getting-started.adoc
related to https://github.com/circleci/circleci-docs/pull/8107
=> add details that some customers may see modified project creation experience

jekyll/_cci2/rerun-failed-tests-only.adoc
=> more typos

jekyll/_cci2/workflows.md
Update payload limit banner on Workflows page to apply to any VCS
GitLab support in all docs
=> Make banner apply to all VCS

jekyll/_cci2/gitlab-integration.adoc
Add Contexts section under project roles matrix to show changes to permissions. Looks like this:
Contexts availability has been extended for GitLab projects
=> add context to project roles section

jekyll/_cci2/managing-api-tokens.md, src-api/source/includes/_overview.md
Provide clarity around usages for different API token types. To accompany this, I've opened a PR to add info to the v2 reference guide: #14605
* Project token with a "status" scope is ONLY for creating status badges (this is really the only recommended usage for project tokens at this time, but this is set to change soon)
* Project api tokens can be used for some v1 endpoints but we recommend using personal tokens
* Only personal tokens supported for v2
Customer request for clarity
Please take a moment to check through the following items when submitting your PR (this is just a guide so will not …
=> API token usage cleanup

jekyll/_cci2/webhooks-reference.adoc
Update to make clearer which params are available for which VCS
Clearing up GitLab support across docs
=> Webhooks banner update

jekyll/_cci2/ip-ranges.md
Fixed typo - wokflow --> workflow
Good to not have typos!
=> Fixed minor typo

jekyll/_cci2/using-macos.adoc
Fixes a broken link, looks like it was still using Markdown syntax while the doc is no longer Markdown.
=> Fix link to macOS dedicated hosts

jekyll/_cci2/rerun-failed-tests-only.adoc
=> add troubleshooting

jekyll/_cci2/workflows.md
match deprecation language from other pages for scheduled workflows
=> match deprecation language as other pages

jekyll/_cci2/rerun-failed-tests-only.adoc
=> add django example

jekyll/_cci2/migrating-from-aws.adoc, jekyll/_cci2/migrating-from-azuredevops.adoc, jekyll/_cci2/migrating-from-buildkite.adoc
Add GitLab to the following migration guides:
AWS
Azure
Buildkite
GitLab across all pages
=> GitLab added to migration guides

jekyll/_cci2/configuration-reference.md, jekyll/_cci2/using-docker.md, jekyll/_cci2/using-macos.adoc, jekyll/_includes/snippets/arm-resource-table.md, jekyll/_includes/snippets/docker-resource-table.md, jekyll/_includes/snippets/gpu-linux-resource-table.md, jekyll/_includes/snippets/gpu-windows-resource-table.md, jekyll/_includes/snippets/machine-resource-table.md, jekyll/_includes/snippets/macos-resource-table.adoc, jekyll/_includes/snippets/macos-resource-table.md, jekyll/_includes/snippets/windows-resource-table.md
Add server support info to resource class tables
Screenshots:
---
---
---
---
---
---
Customer request
=> Server resource class availability

jekyll/_cci2/linux-cuda-images-support-policy.adoc, jekyll/_data/sidenav.yml
* Add support policy doc for Linux CUDA images.
* Add new doc under Managed compute resources > Reference.
=> Linux CUDA support policy

jekyll/_cci2/rename-organizations-and-repositories.adoc
Add note to state that no action required when renaming orgs and repos in GitLab
Standalone projects don't use names to authenticate, they use IDs
=> GitLab accounts and renames

jekyll/_cci2/gitlab-integration.adoc
Add note
Possible conflicts if they don't
=> Note to tell people to disable GitLab CI/CD

jekyll/_cci2/orb-author-intro.md
fixes #8188 - links were the wrong way around
=> switch links

jekyll/_cci2/contexts.md
Contexts management via CLI unsupported
Standalone info across docs
=> Banner to show unsupported for standalone projects

jekyll/_cci2/building-docker-images.md, jekyll/_cci2/configuration-reference.md, jekyll/_cci2/using-arm.md, jekyll/_cci2/using-docker.md, jekyll/_data/sidenav.yml, jekyll/_includes/snippets/docker-arm-resource-table.md
* Create snippet for arm for Docker
* Add snippets to Arm page and config reference and building Docker images pages
* Update Using Arm page to specify that is Arm VM and add section linking to Arm on Docker as an alternative
To give an idea of how it looks:
New feature
=> Arm on Docker

Gemfile, Gemfile.lock
This is the same PR as https://github.com/circleci/circleci-docs/pull/7915. Snyk got confused with the symlink.
Severity                   | Priority Score (*)                   | Issue                   | Breaking Change                   | Exploit Maturity
:-------------------------:|-------------------------|:-------------------------|:-------------------------|:-------------------------
(*) Note that the real score may have changed since the PR was raised.
Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all …
=> Chore: update `ruby` dependencies

jekyll/_cci2/server/v4.1/operator/upgrade-mongo.adoc, jekyll/_cci2/server/v4.2/operator/upgrade-mongo.adoc
We've created a script which will help customers upgrade their mongoDB version to 4.4
This PR adds a link to this script in our 4.1 and 4.2 docs
=> adding instruction for using mongo upgrade script

jekyll/_cci2/gitlab-integration.adoc
Remove `Restore project version` and `Delete project canary` capabilities from Org & Project permissions charts.
These features are only available internally. We will update this chart once we are ready to make these capabilities available to customers.
=> Remove deploy & release capabilities

jekyll/_cci2/config-policy-management-overview.adoc, jekyll/_cci2/config-policy-reference.adoc
=> [SNC-370] added first draft of policies and parameterization section

jekyll/_cci2/server/v4.1/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.2/installation/phase-1-prerequisites.adoc
Updating the docs to reflect that server 4.1 and 4.2 do support EKS 1.24
https://circleci.atlassian.net/browse/SERVER-2490
=> Server 2490/server supports eks 1.24

jekyll/_cci2/concepts.md, jekyll/_cci2/glossary.adoc
Update Glossary and Concepts entries for "Project"
Include the concept of "standalone," for GitLab and GH App users
=> [GitHub app] Make sure we have definitions for "project" inclusive of standalone

jekyll/_cci2/migrate-scheduled-workflows-to-scheduled-pipelines.adoc
Original next steps linked to self. fixed this. 
Found while using docs. 
fixing: Include relevant backlinks to other CircleCI docs/pages.
- [x ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
=> docs to solve circular linking

jekyll/_cci2/api-developers-guide.md, jekyll/_cci2/first-steps.adoc, jekyll/_cci2/github-apps-integration.adoc, jekyll/_cci2/github-integration.adoc
Fix terminology around authorization vs authentication
=> Fix terminology

jekyll/_cci2/collect-test-data.md, jekyll/_cci2/insights-tests.md, jekyll/_cci2/test.md
Test insights is not supported for standalone projects. This PR adds a banner with this information.
Standalone support across docs.
=> Add banner for test insights support

jekyll/_cci2/plan-overview.adoc
Add link
Help people find the info they need
=> Add link from plans overview to support article

jekyll/_cci2/skip-build.md
Add more details about how the auto-cancel feature works
These points are not applicable in this case IMO.
=> Add auto-cance feature detail

jekyll/_cci2/remote-docker-images-support-policy.adoc, jekyll/_data/sidenav.yml
Add support policy around CircleCI remote Docker images.
DOCSS-1268
=> Add remote Docker policy

jekyll/_cci2/runner-overview.adoc
At least one credit required to use runners
=> Add note about runner credit requirement

jekyll/_cci2/templates/template-tutorial.adoc, jekyll/_data/sidenav.yml
Template for tutorial pages
Templates for all page types
=> Template for tutorials

jekyll/_cci2/contexts.md, jekyll/_cci2/rename-organizations-and-repositories.adoc
Update banners - Contexts CLI and Renaming guides
Support for all standalone projects
=> Update banners to account for both GitLab and GH App accounts

jekyll/_cci2/gitlab-integration.adoc
Remove GitLab yaml rather than disabling CI/CD
Disabling CI/CD caused downstream issues
=> Update to ask GitLab users to remove yaml config

jekyll/_cci2/env-vars.md
Move banner earlier to help reader understanding
=> Banner placement

src-api/source/includes/_artifacts.md, src-api/source/includes/_builds_and_jobs.md, src-api/source/includes/_overview.md, src-api/source/includes/_projects.md
Updates "build" references to "job".
The "build" terminology is out of date.
=> Update "build" terminology for API v1

jekyll/_cci2/local-cli.md
We are introducing opt-telemetry into the CLI. 
Telemetry behaviour and instructions for enabling and disabling should be documented in [this page](https://circleci.com/docs/local-cli/)
Ticket --> [DEVEX-1238](https://circleci.atlassian.net/browse/DEVEX-1238)
(Blocked by [DEVEX-898](https://circleci.atlassian.net/browse/DEVEX-898)) 
‼️ **This PR should not be merged before [DEVEX-1238](https://circleci.atlassian.net/browse/DEVEX-1238) is shipped** ⚠️ …
=> Update CLI docs to mention telemetry

jekyll/_cci2/server/v4.2/air-gapped-installation/additional-considerations.adoc, jekyll/_cci2/server/v4.2/air-gapped-installation/phase-3-install-circleci-server.adoc, jekyll/_cci2/server/v4.2/installation/hardening-your-cluster.adoc, jekyll/_cci2/server/v4.2/installation/installing-server-behind-a-proxy.adoc, jekyll/_cci2/server/v4.2/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.2/installation/phase-2-core-services.adoc, jekyll/_cci2/server/v4.2/installation/phase-3-execution-environments.adoc, jekyll/_cci2/server/v4.2/installation/phase-4-post-installation.adoc, jekyll/_cci2/server/v4.2/installation/upgrade-server.adoc, jekyll/_cci2/server/v4.2/operator/application-lifecycle.adoc, jekyll/_cci2/server/v4.2/operator/backup-and-restore.adoc, jekyll/_cci2/server/v4.2/operator/circleci-server-security-features.adoc, jekyll/_cci2/server/v4.2/operator/configuring-external-services.adoc, jekyll/_cci2/server/v4.2/operator/faq.adoc, jekyll/_cci2/server/v4.2/operator/manage-virtual-machines-with-vm-service.adoc, jekyll/_cci2/server/v4.2/operator/managing-orbs.adoc, jekyll/_cci2/server/v4.2/operator/managing-user-accounts.adoc, jekyll/_cci2/server/v4.2/operator/operator-overview.adoc, jekyll/_cci2/server/v4.2/operator/troubleshooting-and-support.adoc, jekyll/_cci2/server/v4.2/operator/usage-data-collection.adoc, jekyll/_cci2/server/v4.2/overview/circleci-server-overview.adoc, jekyll/_cci2/server/v4.2/overview/release-notes.adoc
Some minor fixes missed from the last server release
Consistency and readability
=> Server docs updates

jekyll/_cci2/deploy-to-firebase.adoc
Updates the guide based on user submission (service account key auth). 
* Authentication using user token is deprecated (https://github.com/firebase/firebase-tools#authentication)
* Resolves #8264 .
=> Update Deploy to Firebase guide

jekyll/_cci2/migrate-scheduled-workflows-to-scheduled-pipelines.adoc, jekyll/_cci2/schedule-pipelines-with-multiple-workflows.adoc, jekyll/_cci2/scheduled-pipelines.adoc, jekyll/_cci2/set-a-nightly-scheduled-pipeline.adoc, styles/Vocab/Docs/accept.txt, styles/circleci-docs/DefineFirstUse.yml
* Banner to state scheduled pipelines not supported for standalone projects
* Also some vale rule additions that were surfaced in these files
Standalone project support across docs
=> Scheduled pipelines support banner

jekyll/_cci2/linux-cuda-images-support-policy.adoc, jekyll/_cci2/using-gpu.md
Notice for ongoing Linux CUDA deprecation
Next brownout: September 25th
=> Change banner back to Linux CUDA deprecation notice

jekyll/_cci2/skip-build.md
* Banner to state auto-cancel not available for standalone projects
* Remove outdated steps for server
Standalone support across docs
=> Banner for auto-cancel feature

jekyll/_includes/snippets/xcode-intel-vm.adoc, jekyll/_includes/snippets/xcode-intel-vm.md, jekyll/_includes/snippets/xcode-silicon-vm.adoc, jekyll/_includes/snippets/xcode-silicon-vm.md
Add Xcode 15 to docs
Xcode 15 RC
=> Add Xcode 15 to docs

jekyll/_cci2/deploy-over-ssh.adoc
Fix YAML indentation
Resolves #8339 .
=> Fix YAML formatting in Deploy over SSH doc

jekyll/_cci2/pipeline-variables.adoc
=> Document setup workflows and pipeline parameters

jekyll/_data/sidenav.yml
=> Update title in nav to match page title

jekyll/_cci2/releases/set-up-a-release-integration.adoc, jekyll/_data/sidenav.yml
Onboarding content for releases feature
=> [Releases] onboarding tutorial

jekyll/_cci2/caching.md, jekyll/_cci2/using-docker.md
another change relates to something that is causing customer confusion and is not really a limitation of our system (max cache size)
one change relates to this: https://circleci.slack.com/archives/CKCV4LZ8V/p1695649611119769?thread_ts=1695420678.316349&cid=CKCV4LZ8V
=> update two different things

jekyll/_includes/snippets/runner/machine-runner-deb-package-install.adoc, jekyll/_includes/snippets/runner/machine-runner-rpm-package-install.adoc
Update code snippet
The snippet in the docs does not work as the format of the text in the config file is different and the command doesn't work
=> update snippet to match format in config file

jekyll/_cci2/first-steps.adoc, jekyll/_cci2/invite-your-team.adoc
* Move banners to individual sections to remind people to check their GH integration type
* Move VCS-specific signup instructions into tabs to make the page easier to read
Help readers get the right info for them
=> improve invite and signup flow docs

jekyll/_includes/snippets/linux-cuda-brownout.adoc, jekyll/_includes/snippets/linux-cuda-brownout.md, jekyll/_includes/snippets/linux-cuda-deprecation-notice.adoc, jekyll/_includes/snippets/linux-cuda-deprecation-notice.md, styles/circleci-docs/DefineFirstUse.yml
=> Remove brownout notice and update deprecation banner

src-api/source/includes/_builds_and_jobs.md
Recommendation to trigger pipeline not job
=> add recommendation to use api v2 trigger pipeline

jekyll/_cci2/server/operator/usage-data-collection.adoc, jekyll/_cci2/server/v4.1/operator/usage-data-collection.adoc, jekyll/_cci2/server/v4.2/operator/usage-data-collection.adoc
Rework a potentially confusing statement about potential of future data collection in server
https://circleci.atlassian.net/browse/ONPREM-501
=> [ONPREM-501] Rework paragraph on future data collection

jekyll/_cci2/troubleshoot-test-splitting.adoc, styles/Vocab/Docs/accept.txt
fixes #8025 
Add error message to troubleshooting step to help people find the content they need
=> Add error message to help discoverability

jekyll/_cci2/credits.adoc
Add link for discoverability
Customer feedback
=> add link to resource class credits comparison

jekyll/_cci2/server/v4.1/overview/release-notes.adoc, jekyll/_cci2/server/v4.2/overview/release-notes.adoc, jekyll/_config.yml, styles/Vocab/Docs/accept.txt
* Update global versions
* Add links to changelog
* Updates to Vale styles as necessary
Server patch releases
=> Update for server 4.1.5 and 4.2.1

jekyll/_cci2/roles-and-permissions-overview.adoc
Deploy and release updated permissions related to creating environments to only org admins. So the roles and permissions are updated accordingly.
Recent changes on permissions for creating release environments.
=> [REL-007] Update the role and permissions matrix

jekyll/_cci2/release/configure-your-kubernetes-components.adoc, jekyll/_cci2/release/releases-overview.adoc
=> Releases docs fixes

jekyll/_cci2/server/v4.3/installation/installation-reference.adoc, jekyll/_cci2/server/v4.3/installation/phase-3-execution-environments.adoc, jekyll/_cci2/server/v4.3/installation/upgrade-server.adoc
Updating the upgrade notes for 4.3
fixing some errors in the 4.3 machine provisioner docs
https://circleci.atlassian.net/browse/ONPREM-490
=> Onprem 490/machine provisioner upgrade docs

jekyll/_cci2/release/set-up-a-release-environment.adoc
Make it clear when and why to supply a list of namespaces to monitor when setting up Releases
=> Releases setup updates

jekyll/_cci2/server/overview/release-notes.adoc, jekyll/_config.yml
* Update version in config
* Link to changelog
=> Server docs updates for v4.0.5 release

jekyll/_cci2/using-windows.md
It's a markdown file and asciidoc syntax was used. Fixed #8434 
=> fix link formatting

jekyll/_cci2/enable-checks.md, jekyll/_cci2/faq.adoc, jekyll/_cci2/github-apps-integration.adoc, jekyll/_cci2/insights-snapshot-badge.adoc, jekyll/_cci2/oss.md, jekyll/_cci2/rotate-project-ssh-keys.adoc, jekyll/_cci2/runner-config-reference.adoc, jekyll/_cci2/status-badges.md, jekyll/_cci2/stop-building-a-project-on-circleci.adoc, jekyll/_cci2/triggers-overview.adoc, jekyll/_cci2/using-windows.md, jekyll/_includes/snippets/faq/pipelines-faq-snip.adoc
going thru and adding in some notes about what doesnt work for github app (yet)
=> mention that this doesnt work for gh app (yet)

jekyll/_cci2/building-docker-images.md, jekyll/_cci2/remote-docker-images-support-policy.adoc
Align and update docs according to the tags specified in the new remote docker image policy
https://circleci.atlassian.net/jira/software/c/projects/IMG/boards/657?selectedIssue=IMG-114
- [N/A] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
=> [IMG-114] Align remote docker docs with new tagging system

jekyll/_includes/snippets/gpu-linux-resource-table.md
update for new preview resource classes
=> [don't merge yet]

jekyll/_includes/snippets/gpu-linux-resource-table.md, jekyll/_includes/snippets/gpu-windows-resource-table.md
=> not true anymore

jekyll/_cci2/github-apps-integration.adoc
context: https://circleci.slack.com/archives/C055HTSAN8K/p1700498271224669
=> make explicit workaround

jekyll/_cci2/server/v4.1/operator/troubleshooting-and-support.adoc, jekyll/_cci2/server/v4.2/operator/troubleshooting-and-support.adoc, jekyll/_cci2/server/v4.3/operator/troubleshooting-and-support.adoc
Customers on versions where concurrency limits are not disabled by default should disable them
=> Update concurrency limit guidance for each server version

jekyll/_cci2/github-apps-integration.adoc
just so we have something we can at least point to as we start to prep for how we are gonna ask people to move over...eventually
if someone wants to move, and they are okay with the functionality that doesnt exist, let's let them
=> add basic instructions for moving to gh app

jekyll/_cci2/container-runner-installation.adoc
Some clarification around the install of Envoy Gateway after some initial feedback.
https://circleci.atlassian.net/browse/ONPREM-608
=> Clarify install of Gateway API for container runner SSH reruns [ONPREM-608]

jekyll/_cci2/server/v4.1/overview/release-notes.adoc, jekyll/_cci2/server/v4.2/overview/release-notes.adoc, jekyll/_config.yml
- https://circleci.atlassian.net/browse/ONPREM-610
- https://circleci.atlassian.net/browse/ONPREM-612
=> Update server release notes for 4.1.6 and 4.2.2 [ONPREM-612]

jekyll/_cci2/linux-vm-support-policy.adoc, jekyll/_data/sidenav.yml
Adds Linux Image Support Policy to docs
[IMG-178](https://circleci.atlassian.net/jira/software/c/projects/IMG/boards/683?selectedIssue=IMG-178)
- [N/A] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
[IMG-178]: https://circleci.atlassian.net/browse/IMG-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [IMG-178] Linux vm support policy

jekyll/_includes/snippets/xcode-intel-vm.adoc, jekyll/_includes/snippets/xcode-intel-vm.md, jekyll/_includes/snippets/xcode-silicon-vm.adoc, jekyll/_includes/snippets/xcode-silicon-vm.md
updates for a new XCode release
=> chore: xcode 15.1 RC docs update

jekyll/_cci2/dynamic-config.adoc, jekyll/_cci2/pipeline-variables.adoc, jekyll/_data/sidenav.yml
=> Pipeline params with dynamic config docs improvements

jekyll/_cci2/bitbucket-integration.adoc
Add section from https://github.com/circleci/circleci-docs/pull/8447
=> Bitbucket permissions

jekyll/_cci2/windows-images-support-policy.adoc, jekyll/_data/sidenav.yml
Adds Windows Image Support Policy to docs
[IMG-175](https://circleci.atlassian.net/jira/software/c/projects/IMG/boards/683?selectedIssue=IMG-175)
- [N/A] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
[IMG-175]: https://circleci.atlassian.net/browse/IMG-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [IMG-175] Windows support policy

jekyll/_includes/snippets/xcode-intel-vm.adoc, jekyll/_includes/snippets/xcode-intel-vm.md, jekyll/_includes/snippets/xcode-silicon-vm.adoc, jekyll/_includes/snippets/xcode-silicon-vm.md
just quick updates to the available xcode versions
=> chore: xcode 15.2 beta update

jekyll/_cci2/server/v4.1/installation/phase-2-core-services.adoc, jekyll/_cci2/server/v4.2/installation/phase-2-core-services.adoc, jekyll/_cci2/server/v4.3/installation/phase-2-core-services.adoc, jekyll/_cci2_ja/server/v4.1/installation/phase-2-core-services.adoc
Updates code blocks eto show aws_acm enabled in cases where it's appropriate.
[ONPREM-728]
[ONPREM-728]: https://circleci.atlassian.net/browse/ONPREM-728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updating aws_acm: enabled: true for server docs

jekyll/_cci2/container-runner.adoc
Removes container runner server limitation
No longer relevant
=> Remove container runner server limitation

jekyll/_cci2/release/set-up-a-release-environment.adoc, jekyll/_cci2/release/update-the-kubernetes-release-agent.adoc, jekyll/_data/sidenav.yml
Add short upgrade guide and link to it from the setup guide
Provide a location in docs for showing people how to update their release agent
=> Guide to update the Kubernetes release agent

jekyll/_cci2/create-and-manage-config-policies.adoc
Added missing - to CLI code samples
code samples can now be copy-pasted successfully
=> Fixed missing characters in code samples

jekyll/_cci2/server/v4.3/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.3/installation/upgrade-server.adoc
Updates supported versions and minimum requirements for server 4.3.x
[ONPREM-718]
[ONPREM-718]: https://circleci.atlassian.net/browse/ONPREM-718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updating supported k8 version and minimum requirements for server 4.3

jekyll/_cci2/oss.md
we do support "only build merge requests" for gitlab https://circleci.slack.com/archives/C014072VDLZ/p1683123154220879
=> update to make accurate

jekyll/_cci2/server/v4.3/installation/installation-reference.adoc
The server 4.3 installation reference is out of date. This updates the values with the auto-generated table from the head of server-4.3 branch, corresponding to the latest 4.3 patch release.
**Note** This table is autogenerated. Any desired modifications should be made to the circleci server values.yaml file directly in the corresponding branch.
[ONPREM-684]
[ONPREM-684]: https://circleci.atlassian.net/browse/ONPREM-684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updating server installation reference with branch 4.3

jekyll/_cci2/server/v4.2/installation/installation-reference.adoc, jekyll/_cci2/server/v4.2/overview/release-notes.adoc, jekyll/_config.yml
Quick update for the release docs for 4.2.3, and 4.2.4 (and the latest 4.2.4 values table).
[ONPREM-767]
[ONPREM-767]: https://circleci.atlassian.net/browse/ONPREM-767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Server 4.2.3 & 4.2.4 Release Docs

jekyll/_includes/snippets/xcode-intel-vm.adoc, jekyll/_includes/snippets/xcode-silicon-vm.adoc
Quick update for xcode 15.2 release
https://circleci.atlassian.net/browse/MAC-2022?atlOrigin=eyJpIjoiZmVhNWU0MmI3YzMwNGM2ZGFkOWUyZDQ2NjJiOGQ3ZmQiLCJwIjoiaiJ9
=> chore: xcode 15.2 release

jekyll/_cci2/server/installation/installation-reference.adoc, jekyll/_cci2/server/overview/release-notes.adoc, jekyll/_config.yml
updating the values.yaml and changelog for server 4.0.6
https://circleci.atlassian.net/browse/ONPREM-697
=> Onprem 697/server 4.0.6 update

jekyll/_cci2/create-an-orb.adoc, jekyll/_cci2/orb-author-validate-publish.md
* remove recommendation to use `--private` flag
* add note that unsupported
=> Server orb auth updates

jekyll/_cci2/server/v4.3/installation/phase-3-execution-environments.adoc
Adding volume related policy on IAM access keys.
Somehow, IAM access key policy doesn't have `"arn:aws:ec2:*:*:volume/*"` value on our docs.
I have faced below error when I update my server v4.3 and found only this version IAM is missing it.
```
{"data":{"app.loop_name":"creator","app.provider_create_error":"1 error occurred:\n\t* operation error EC2: RunInstances, https response error StatusCode: 403, RequestID: 508604ba-9e65-476b-b8bc-da740e496b3c, api error UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:iam::483285841698:user/circleci-machine-provisioner is not authorized to perform: ec2:RunInstances on resource: arn:aws:ec2:ap-northeast-1:483285841698:volume/* because no identity-based policy allows the ec2:RunInstances action. Encoded …
```
=> Add_volume_create_policy_for_iam_keys

jekyll/_cci2/server/v4.4/installation/phase-1-prerequisites.adoc
These requirements were updated for 4.3+ in PR #8545
https://circleci.atlassian.net/browse/ONPREM-820
=> Update cluster requirements for 4.4 [ONPREM-820]

jekyll/_cci2/oidc-tokens-with-custom-claims.adoc, jekyll/_cci2/openid-connect-tokens.adoc
Server support from 4.4 but not for air-gapped installations
=> OIDC on server

jekyll/_cci2/server/v4.4/overview/circleci-server-overview.adoc
=> Update services list for server 4.4

jekyll/_cci2/server/v4.4/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.4/installation/phase-3-execution-environments.adoc, jekyll/_cci2/server/v4.4/overview/circleci-server-overview.adoc, styles/circleci-docs/CapitalizationDocs.yml, styles/config/vocabularies/Docs/accept.txt
Some changes to the overview and prerequisites pages to make the flow and content clearer, and to take steps to account for local/cloud/air-gapped installs.
Further work is planned to make seaparate guides for these installation types.
=> Rework intro, prerequs and execution sections for flow and installation options

jekyll/_cci2/install-machine-runner-3-on-macos.adoc, jekyll/_cci2/machine-runner-3-manual-installation.adoc, jekyll/_cci2/runner-concepts.adoc, jekyll/_includes/snippets/runner/install-with-cli-steps.adoc, jekyll/_includes/snippets/runner/machine-runner-deb-package-install.adoc, jekyll/_includes/snippets/runner/terms.adoc
Updating Runner 3.0 docs to include server references
https://circleci.atlassian.net/browse/ONPREM-734
=> Updating Runner 3.0 docs to include server references

jekyll/_cci2/server/v4.4/installation/installation-reference.adoc
These values were generated off the [server-4.4](https://github.com/circleci/server/tree/server-4.4) branch using [the new automated process](https://github.com/circleci/server/blob/main/docs/how-values-yaml-readme-comments-work.md).
https://circleci.atlassian.net/browse/ONPREM-806
=> Update installation reference values for 4.4 [ONPREM-806]

jekyll/_includes/snippets/pipeline-values.adoc
There was an extra column added for one row which messed up the formatting of the rest of the table. This fixes by using a bullet list in a single cell
Broken table
=> Fix table formatting - pipeline values

jekyll/_cci2/resource-class-overview.adoc
modified:   jekyll/_cci2/resource-class-overview.adoc
Minor changes to text:
- Added 4th use case described in text: specifying environment.
- Summarized use cases in introduction.
- Added banners for notes.
=> Updates to resource-class-overview.adoc

jekyll/_cci2/bitbucket-integration.adoc, jekyll/_cci2/container-runner-installation.adoc, jekyll/_cci2/container-runner.adoc, jekyll/_cci2/deploy-to-aws.adoc, jekyll/_cci2/github-integration.adoc, jekyll/_cci2/how-to-use-the-circleci-local-cli.adoc, jekyll/_cci2/machine-runner-3-configuration-reference.adoc, jekyll/_cci2/migrate-scheduled-workflows-to-scheduled-pipelines.adoc, jekyll/_cci2/migration-intro.adoc, jekyll/_cci2/release/manage-releases.adoc, jekyll/_cci2/rename-organizations-and-repositories.adoc, jekyll/_cci2/scheduled-pipelines.adoc, jekyll/_cci2/set-a-nightly-scheduled-pipeline.adoc, jekyll/_cci2_ja/credits.adoc
Various formatting fixes - incorrect heading levels etc.
=> Fix a bunch of formatting errors

jekyll/_includes/snippets/xcode-intel-vm.adoc, jekyll/_includes/snippets/xcode-silicon-vm.adoc
=> [PROV-460] Update docs for Xcode 15.3 beta 1

jekyll/_cci2/manage-groups.adoc
Remove to do items highlighted in text
=> remove to do items

jekyll/_cci2/server/v4.4/overview/release-notes.adoc
Update changelog URL in server 4.4 release notes
broken link
=> fix link to changelog

jekyll/_cci2/oidc-tokens-with-custom-claims.adoc, styles/circleci-docs/CapitalizationDocs.yml
Make it explicit that only `aud` claim is customizable
Customer request
=> clarify OIDC custom claims

jekyll/_cci2/triggers-overview.adoc
feedback from customer that we should have curl example in docs. i agree
=> add explicit curl command based on feedback

jekyll/_data/sidenav.yml
Put all reference pages in a section together
To help people find the configuration reference
=> Make top level reference section

jekyll/_cci2/migrate-from-launch-agent-to-machine-runner-3-on-macos.adoc
https://circleci.atlassian.net/browse/ONPREM-890
=> Fix typo in macOS launch-agent to machine runner migration docs [ONPREM-890]

.circleci/config.yml, jekyll/_cci2/about-circleci.adoc
Use vale orb to lint docs content
I used a separate workflow to avoid the pipeline failing on a lint fail
Help everyone stick to the style guide
=> Add linting workflow to docs repo

jekyll/_cci2/server/v4.1/overview/release-notes.adoc, jekyll/_cci2/server/v4.3/overview/release-notes.adoc, jekyll/_cci2/server/v4.4/overview/release-notes.adoc, jekyll/_config.yml
Add 3 new server patch notes links
https://circleci.atlassian.net/browse/ONPREM-841
=> Add 3 new server patch release note links

jekyll/_includes/snippets/xcode-intel-vm.adoc, jekyll/_includes/snippets/xcode-silicon-vm.adoc
Update the manifest and information related to the Xcode 15.3 image currently in production
The macOS team has released a new image version. The docs update provides the new manifest and release announcement linked to the new images.
=> Update 15.3 beta 3 docs

jekyll/_cci2/local-cli.adoc
Replacing branch name master with main in "https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh"
The repo URL is outdated on the documentation on alternative installation methods for the CLI.
- [ N/A ] Break up walls of text by adding paragraph breaks.
- [ N/A ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- …
=> Replacing branch name master with main

jekyll/_includes/snippets/xcode-intel-vm.adoc, jekyll/_includes/snippets/xcode-silicon-vm.adoc
=> update xcode 15.3 RC docs

jekyll/_includes/snippets/xcode-intel-vm.adoc, jekyll/_includes/snippets/xcode-silicon-vm.adoc
=> update xcode 15.3 RC macOS version to 14.3.1

.github/CODEOWNERS
Unblock reviews by adding whole team
=> update docs content codeownders

jekyll/_cci2/audit-logs.adoc
New Audit logs events for Checkout and Deploy keys were added
- PR for this change is here: https://github.com/circleci/circle/pull/15075
- Additional internal context: https://circleci.slack.com/archives/C04FKTQGHSA/p1707435526938289
=> Added new Audit Log Events

jekyll/_cci2/artifacts.adoc, jekyll/_cci2/deployment-overview.adoc, jekyll/_cci2/ip-ranges.adoc, jekyll/_cci2/test.adoc, styles/config/vocabularies/Docs/accept.txt
* Add use cases to opening paragraph
* Cross link from other relevant pages
=> Ip ranges updates

jekyll/_cci2/ip-ranges.adoc
=> remove link to archived blog post

jekyll/_cci2/contexts.adoc
Add expression restrictions section to context restrictions
New functionality available to customers
- [x ] Break up walls of text by adding paragraph breaks.
- [x ] Keep the title between 20 and 70 characters.
- [x ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [x ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [x ] Include relevant backlinks to …
=> Add expression restrictions to context restrictions

jekyll/_includes/snippets/xcode-intel-vm.adoc, jekyll/_includes/snippets/xcode-silicon-vm.adoc
Update Xcode 15.3 documentation and links (manifest, discuss post)
https://circleci.atlassian.net/browse/MAC-2074
=> Update Xcode 15.3 documentation [MAC-2074]

jekyll/_cci2/release/releases-overview.adoc
It is possible to attempt to restore a version that no longer exists - provide some info
Looks like this:
=> Releases known limitation

jekyll/_includes/snippets/troubleshoot/self-hosted-runner-troubleshoot-snip.adoc, styles/config/vocabularies/Docs/accept.txt
Adding a section on how the liveness probe and prestop hook works to the troubleshooting docs for container agent
https://circleci.atlassian.net/browse/ONPREM-887
=> adding liveness probe to container agent troubleshooting

jekyll/_cci2/credits.adoc
https://circleci.slack.com/archives/CNHFJ07LZ/p1711536353280749
=> also update this

jekyll/_cci2/github-apps-integration.adoc
https://circleci.slack.com/archives/CNHFJ07LZ/p1711536353280749 means i dont think we need this anymore
=> update oss thing

jekyll/_cci2/using-windows.adoc
https://circleci.slack.com/archives/CNHFJ07LZ/p1711483893591329 removes the need for this
=> no longer needed with https checkout

jekyll/_cci2/server/overview/release-notes.adoc, jekyll/_cci2/server/v4.1/overview/release-notes.adoc, jekyll/_cci2/server/v4.2/overview/release-notes.adoc, jekyll/_cci2/server/v4.3/overview/release-notes.adoc, jekyll/_cci2/server/v4.4/overview/release-notes.adoc, jekyll/_config.yml
* Server 4.3.4 and 4.4.2
* Remove migration information as all installs are now on v4.x
Patch releases
=> Server docs update for patch releases

jekyll/_includes/snippets/troubleshoot/self-hosted-runner-troubleshoot-snip.adoc
I got an from the container agent pod when using it without the indents.
=> Update Livenessprobe code block on Runner Troubleshooting page

jekyll/_cci2/add-ssh-key.adoc, jekyll/_cci2/create-project.adoc
* Steps are the same for all users
* use numbered steps so its clear its a 2 step process
* Also catch a reference to SSH keys in create project guide that I had missed
Simplify and better flow
=> Additional ssh keys updates

jekyll/_cci2/container-runner-installation.adoc
Add supported server version to container runner install page supported matrix
Container runner is supported on server 4.3 and up
=> [ONPREM-1048] Add supported server version to container runner install page

jekyll/_cci2/browser-testing.adoc, jekyll/_cci2/building-docker-images.adoc, jekyll/_cci2/caching-strategy.adoc, jekyll/_cci2/caching.adoc, jekyll/_cci2/circleci-images.md, jekyll/_cci2/code-coverage.adoc, jekyll/_cci2/collect-test-data.md
Fix up errors in config.yml snippets - block 2
Make sure people can copy paste snippets into their own config files
=> fix indentation and formatting of circleci.yml

jekyll/_cci2/getting-started.adoc
=> move passthrough block to fix broken heading

jekyll/_cci2/release/releases-overview.adoc
We changed the format of our component name and version labels with v1.2.0 of the agent. There was one more place in the docs that we missed updating them.
=> Update labels to new format

jekyll/_cci2/server/v4.3/installation/installation-reference.adoc
updating the values.yaml reference for the 4.4.3 patch release.
https://circleci.atlassian.net/browse/ONPREM-1068
=> values ref update for 4.4.3

jekyll/_cci2/concepts.adoc, jekyll/_cci2/concurrency.adoc, jekyll/_cci2/config-intro.adoc, jekyll/_cci2/config-policy-management-overview.adoc
Fix up some snippet formatting for config.yml examples
copypasteability
=> Fix up snippets round 3

jekyll/_cci2/server/v4.4/air-gapped-installation/additional-considerations.adoc, jekyll/_cci2/server/v4.4/air-gapped-installation/example-values.adoc, jekyll/_cci2/server/v4.4/air-gapped-installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.4/air-gapped-installation/phase-2-configure-object-storage.adoc, jekyll/_cci2/server/v4.4/air-gapped-installation/phase-3-install-circleci-server.adoc, jekyll/_cci2/server/v4.4/air-gapped-installation/phase-5-test-your-installation.adoc, jekyll/_cci2/server/v4.4/installation/hardening-your-cluster.adoc, jekyll/_cci2/server/v4.4/installation/installation-reference.adoc, jekyll/_cci2/server/v4.4/installation/phase-4-post-installation.adoc, jekyll/_cci2/server/v4.4/operator/application-lifecycle.adoc, jekyll/_cci2/server/v4.4/operator/backup-and-restore.adoc, jekyll/_cci2/server/v4.4/operator/circleci-server-security-features.adoc, jekyll/_cci2/server/v4.4/operator/configuring-external-services.adoc, jekyll/_cci2/server/v4.4/operator/expanding-internal-database-volumes.adoc, jekyll/_cci2/server/v4.4/operator/faq.adoc, jekyll/_cci2/server/v4.4/operator/introduction-to-nomad-cluster-operation.adoc, jekyll/_cci2/server/v4.4/operator/managing-build-artifacts.adoc, jekyll/_cci2/server/v4.4/operator/managing-load-balancers.adoc, jekyll/_cci2/server/v4.4/operator/managing-orbs.adoc, jekyll/_cci2/server/v4.4/operator/operator-overview.adoc, jekyll/_cci2/server/v4.4/operator/troubleshooting-and-support.adoc, jekyll/_cci2/server/v4.4/operator/upgrade-mongo.adoc, jekyll/_cci2/server/v4.4/overview/circleci-server-overview.adoc, jekyll/_cci2/server/v4.4/overview/release-notes.adoc, styles/config/vocabularies/Docs/accept.txt, styles/config/vocabularies/Docs/reject.txt
Get server 4.4 docs to past linter before we create 4.5 docs
=> Style fixes for server 4.4

jekyll/_cci2/server/v4.2/air-gapped-installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.3/air-gapped-installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.4/air-gapped-installation/phase-1-prerequisites.adoc
=> remove support email address

jekyll/_includes/snippets/xcode-silicon-vm.adoc
Xcode 15.4 Beta is now available for use.
https://circleci.atlassian.net/browse/MAC-2147
=> Add Xcode 15.4 image to Apple Silicon documentation

jekyll/_cci2/pipeline-variables.adoc
=> Add parameter limits to pipeline variables 

jekyll/_cci2/pipeline-variables.adoc, jekyll/_cci2/runner-installation-docker.adoc, jekyll/_cci2/runner-installation-linux.adoc, jekyll/_cci2/runner-installation-mac.adoc, jekyll/_cci2/runner-installation-windows.adoc, jekyll/_cci2/runner-overview.adoc
Improve messaging for launch agent deprecation
We continue to have customers install launch agent for cloud. 
=> Nathanfishcircleci patch 2 eol launch agent

jekyll/_cci2/gitlab-integration.adoc, jekyll/_cci2/skip-build.md
=> Remove "Gitlab" from disclaimer about auto-cancellation

jekyll/_cci2/skip-build.md
https://circleci.atlassian.net/browse/DOCSS-1465 
=> Remove disclaimer that auto-cancellation is not supported for Github App 

jekyll/_cci2/dynamic-config.adoc
Add a new note to the notes sections of the dynamic workflow page.
=> add note to dynamic config doc

jekyll/_cci2/release/releases-overview.adoc, jekyll/_cci2/release/set-up-a-release-environment.adoc, jekyll/_includes/snippets/release/supported-versions.adoc
Update the supported K8s versions for Release docs
https://circleci.atlassian.net/browse/REL-3034
We now support the newer versions of Kubernetes
=> [REL-3034] Update the supported K8s versions for Release docs

jekyll/_cci2/server/v4.5/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.5/installation/phase-2-core-services.adoc, jekyll/_cci2/server/v4.5/installation/phase-3-execution-environments.adoc
* Updated Num of node required in GCP command
* Add few missing commands 
* Shuffle service account creation command where it is being used  
* Removed "Do Nothing" from TLS as we dont support self-signed certs in server now. 
https://circleci.atlassian.net/browse/ONPREM-958 
=> ONPREM-958 | GCP Doc Update

jekyll/_cci2/server/v4.5/installation/installation-reference.adoc
updating server 4.5 values.yaml ref
https://circleci.atlassian.net/browse/ONPREM-950
=> updating values ref for server 4.5

jekyll/_cci2/gitlab-integration.adoc
https://circleci.com/changelog/auto-cancel-redundant-workflows-for-gitlab-projects/
=> auto-cancel updates

jekyll/_cci2/server/v4.5/installation/phase-1-prerequisites.adoc
Some updates for the server 4.5 install docs
https://circleci.atlassian.net/browse/ONPREM-957
=> Onprem 957/update aws install docs server 4.5

jekyll/_cci2/github-apps-integration.adoc
i missed this my b
https://circleci.slack.com/archives/C0G6NTU4B/p1714504137753639
=> make explicit that this is not supported

jekyll/_cci2/runner-installation-linux.adoc, jekyll/_cci2/runner-installation-mac.adoc, jekyll/_cci2/runner-installation-windows.adoc, styles/config/vocabularies/Docs/accept.txt
Some style fixes in the runner docs
=> Style fixes

jekyll/_includes/snippets/runner/container-runner-prereq.adoc, jekyll/_includes/snippets/runner/ja/container-runner-prereq.adoc
setting the min k8s version of container runner to 1.25
https://circleci.atlassian.net/browse/ONPREM-262
=> set min k8s version to 1.25

jekyll/_cci2/add-ssh-key.adoc, jekyll/_cci2_ja/add-ssh-key.adoc
=> fix: Link to GH documentation

jekyll/_cci2/contexts.adoc
=> fix small errors in contexts page

jekyll/_data/sidenav.yml
* Rename Partnerships -> Third-party integrations (Totally open to other titles!)
* Move VCS integration pages out of getting started section and into the integrations section
"Partnerships" is not the right term for what these pages describe, and the Getting started section was getting way too big
=> 🧹 Integrations section 🧹 

jekyll/_cci2/testing-llm-enabled-applications-through-evaluations.adoc
=> Quick edit to eval page

jekyll/_cci2/release/configure-your-kubernetes-components.adoc
Explain how to use PROJECT ID from env vars and also explicitly explain that UI based actions are always enabled by default.
https://circleci.atlassian.net/browse/REL-3012
=> [REL-3012] Explain how to use PROJECT ID from env vars

jekyll/_cci2/roles-and-permissions-overview.adoc
Update some recently changed releases terminology like environment integration and reflect updated permissions on creating environment integrations and integration tokens.
https://circleci.atlassian.net/browse/REL-3063
=> [REL-3063] Update releases terms and recent access changes

jekyll/_cci2/example-configs.md
This removes dead links, and updates `master` --> `main` branch renames for several projects.
Several of the linked open source projects no longer use CircleCI, or have a CircleCI config.yml file in the repository.
This PR removes the projects that removed the CircleCI configs.
If we do not want to remove these items, we would need to find similar open source projects to list.
No reason to link to a project that does not have a sample config.yml file
=> Update dead links on config example page

jekyll/_cci2/release/configure-your-kubernetes-components.adoc
Simplify explanatory text and remove confusing annotations from example
Customer reported that this section was confusing
=> Clear up instructions on enable/disable release features with annotations

jekyll/_cci2/configuration-reference.adoc
fix incorrect table cols 
| before | after |
|--------|--------|
| <img width="300" alt="image" src="https://github.com/circleci/circleci-docs/assets/19329/d2dd4c19-34cf-49d5-982e-e02180fa1252"> | <img width="300" alt="image" src="https://github.com/circleci/circleci-docs/assets/19329/1dc63f6b-88db-4c5b-88b4-7ce93478195e">| 
See above screen shot "before"
=> fix: Incorrect table cols 4 -> 2

jekyll/_cci2/server/v4.1/operator/expanding-internal-database-volumes.adoc, jekyll/_cci2/server/v4.2/operator/expanding-internal-database-volumes.adoc, jekyll/_cci2/server/v4.3/operator/expanding-internal-database-volumes.adoc, jekyll/_cci2/server/v4.4/operator/expanding-internal-database-volumes.adoc, jekyll/_cci2/server/v4.5/operator/expanding-internal-database-volumes.adoc
https://circleci.atlassian.net/browse/ONPREM-1217
=> adding note to rerun stuck jobs after pvc expansion

jekyll/_cci2/status-badges.adoc
Added a section to include known issues and limitations 
https://circleci.atlassian.net/browse/SC-736
=> Add known limitations section

jekyll/_cci2/rerun-failed-tests.adoc
https://discuss.circleci.com/t/product-launch-rerun-failed-tests-circleci-tests-run/47775/193
adding this to FAQs based on the experience above
=> update based on feedback on Discuss

jekyll/_includes/snippets/pipeline-values.adoc
[--> Jira ticket](https://circleci.atlassian.net/browse/DOCSS-1573)
=> Remove unavailable trigger parameter values

jekyll/_cci2/server/v4.1/overview/release-notes.adoc, jekyll/_cci2/server/v4.2/overview/release-notes.adoc, jekyll/_config.yml
* Add new sections to release notes for 4.1 and 4.2
* Increase version in Jekyll config
=> Server patch release docs updates

jekyll/_cci2/server/v4.1/overview/release-notes.adoc, jekyll/_cci2/server/v4.2/overview/release-notes.adoc, jekyll/_cci2/server/v4.3/overview/release-notes.adoc
=> Server release notes updates

jekyll/_cci2/roles-and-permissions-overview.adoc
https://docs.google.com/spreadsheets/d/15Nm0F6_BxPuy8jvT4i8N16aZoZ9zmTBfFiKUp8SLZ8A/edit?gid=1588672497#gid=1588672497
org contributors can create config sources & triggers
=> fix incorrect permissions info

jekyll/_cci2/container-runner.adoc
Add docs for container runner on setting up and using [customizable service containers](https://circleci.atlassian.net/l/cp/cwBe11DM).
Jira: https://circleci.atlassian.net/browse/ONPREM-1025
=> Add docs on customizable service containers [ONPREM-1025]

jekyll/_cci2/ssh-access-jobs.adoc
Clarify situation for non-interactive VS interactive shell sessions.
there was missing context in the sentence itself.
=> docs: clarify situation for non-interactive mode

jekyll/_cci2/webhooks.adoc
=> Fixed a typo in the documentation

jekyll/_cci2/building-docker-images.adoc
More clarity to section on env specs for remote docker. I have moved all content to the specifications section of the page and tried to make it clearer
Reader confusion, and remove unnecessary link to Discuss
=> Clarify remote docker specs and exceptions

jekyll/_includes/snippets/xcode-silicon-vm.adoc
* https://circleci.atlassian.net/browse/MAC-2277
=> [MAC-2277] Xcode 16 Beta 2

jekyll/_cci2/stop-building-a-project-on-circleci.adoc
Expand steps for delete project section of the "Stop building..." guide to explicitly state what people need to do for the various VCS integrations, and make it clear how to submit a support ticket by linking to support articles
High number of users asking the AI bot how to do this
=> Improve steps to delete a project guide

jekyll/_cci2/server/v4.4/installation/phase-2-core-services.adoc, jekyll/_cci2/server/v4.5/installation/phase-2-core-services.adoc
https://circleci.atlassian.net/browse/ONPREM-897
=> Add steps on setting up OIDC on server 4.4+ [ONPREM-897]

jekyll/_cci2/server/v4.2/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.3/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.3/installation/upgrade-server.adoc, jekyll/_cci2/server/v4.4/installation/phase-1-prerequisites.adoc, jekyll/_cci2/server/v4.4/installation/upgrade-server.adoc
updating the supported versions of k8s 
https://circleci.atlassian.net/browse/ONPREM-1318
=> updating supported k8s versions on server

jekyll/_includes/snippets/xcode-silicon-vm.adoc
Xcode 16 Beta 3 is now available. This PR updates image documentation.
=> Update Xcode Image documentation for Xcode 16 Beta 3 release

jekyll/_cci2/server/v4.4/installation/phase-3-execution-environments.adoc, jekyll/_cci2/server/v4.5/installation/phase-3-execution-environments.adoc
clarifying in our docs that customers are able to create a secret for mtls values rather than just adding the values to their values.yaml
https://circleci.atlassian.net/browse/ONPREM-873
=> adding mtls secret generation command to docs

jekyll/_cci2/server/v4.2/overview/release-notes.adoc, jekyll/_config.yml
=> Update release-notes.adoc for server 4.2.7

jekyll/_cci2/webhooks.adoc
=> update webooks doc

jekyll/_cci2/server/latest/installation/installation-reference.adoc
Update the Helm values for 4.6, generated via [this script](https://github.com/circleci/server/tree/5ac6e9c34b4eb4790b72e3130c3ae53701e42f01/scripts/generate-values-yaml-file-readme-table). 
https://circleci.atlassian.net/browse/ONPREM-1228
=> Update Helm values for 4.6 [ONPREM-1228]

jekyll/_includes/snippets/faq/billing-faq-snip.adoc, styles/circleci-docs/CapitalizationDocs.yml
Added some info to our billing FAQ docs regarding the paid support plans, and our credit pricing
To clarify some of the information and promote our support packages. Please reach out to myself or Kami if you have any additional questions as this request for edits was made in a closed Support slack channel
- [N/A] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
=> M desmery add support package info

jekyll/_includes/snippets/xcode-silicon-vm.adoc
Release Xcode 16 Beta 5
Release Xcode 16 Beta 5
=> [MAC-2308] Xcode 16 Beta 5

jekyll/_cci2/server/v4.3/overview/release-notes.adoc, jekyll/_cci2/server/v4.4/overview/release-notes.adoc, jekyll/_cci2/server/v4.5/overview/release-notes.adoc, jekyll/_config.yml
* Update Jekyll for new versions
* Add links to changelogs
=> add release notes updates for server patch releases

jekyll/_includes/snippets/pipeline-values.adoc
The version this is available for Server customers is 4.7 and above, this fixes the incorrect version number from #8901.
=> Fix Server version for is default branch pipeline value

jekyll/_includes/snippets/xcode-silicon-vm.adoc
Update Xcode 16.1 documentation and links 
[manifest ](https://circle-macos-docs.s3.amazonaws.com/image-manifest/v14972/manifest.txt)
[discuss post](https://discuss.circleci.com/t/xcode-16-1-beta-1-released/51693)
https://circleci.atlassian.net/browse/MAC-2315
=> [MAC-2315] update xcode 16.1 documentation

jekyll/_cci2/api-developers-guide.adoc, jekyll/_cci2/github-apps-integration.adoc, jekyll/_cci2/github-integration.adoc, jekyll/_cci2/rename-organizations-and-repositories.adoc, jekyll/_cci2/set-up-multiple-configuration-files-for-a-project.adoc, jekyll/_cci2/webhooks.adoc
Some minor language fixes
Help understanding
=> Minor language changes around authorization with a VCS

jekyll/_cci2/workflows.adoc
Change `expressinos` to `expressions`.
=> s/expressinos/expressions/ in  workflows.adoc

jekyll/_cci2/plan-free.adoc
Removes "and our global ticket-based system" as an outright option for free plan users
Removes "and our global ticket-based system" as an outright option for free plan users.
Support to no longer offer ticketed support for free support plan orgs
- [ x] Break up walls of text by adding paragraph breaks.
- [ x] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ x] Keep the title between 20 …
=> Removes mention of opening tickets for plan-free.adoc

jekyll/_cci2/bitbucket-data-center-integration.adoc, jekyll/_cci2/github-apps-integration.adoc, jekyll/_cci2/gitlab-integration.adoc, jekyll/_cci2/insights-snapshot-badge.adoc
Remove notes about insights snapshot badge from "Coming Soon" sections of integration docs.
Insights snapshot badges to be deprecated.
=> Remove insights snapshot badge from coming soon

jekyll/_cci2/configuration-reference.adoc, jekyll/_cci2/workflows.adoc
Add notes in relevant places that scheduled workflows are unsupported for standalone projects
Help people find the info they need
=> Scheduled workflows unsupported for standalone

src-api/source/includes/_builds_and_jobs.md
Remove outdated API v1.1 doc entry
Removing outdated content
=> Remove add user to job doc

jekyll/_cci2/jobs-steps.adoc
=> Add section on job naming and restrictions

jekyll/_cci2/server/latest/overview/release-notes.adoc, jekyll/_config.yml
=> Add change log link for server 4.6.1

jekyll/_cci2/server/latest/overview/release-notes.adoc, jekyll/_cci2/server/v4.5/overview/release-notes.adoc
=> Couple fixes for the server release notes [ONPREM-1507] [ONPREM-1509]

jekyll/_cci2/collect-test-data.adoc
fixes #8057 
Update advice for people using Xcode tests with CircleCI
Very outdated content
=> update xcode test results advice

jekyll/_cci2/set-a-nightly-scheduled-pipeline.adoc
=> Fix example

jekyll/_cci2/server/latest/overview/release-notes.adoc, jekyll/_cci2/server/v4.3/overview/release-notes.adoc, jekyll/_config.yml
Add the changelog links for 2 new patch releases
4.6.2 & 4.3.9 are now released and the changelogs are out
=> [ONPREM-1534] Add changelog links for 4.3.9 & 4.6.2

jekyll/_cci2/server/v4.4/overview/release-notes.adoc, jekyll/_cci2/server/v4.5/overview/release-notes.adoc
release notes for 4.4.7 and 4.5.5
=> add 4.4.7 & 4.5.5 release notes

jekyll/_config.yml
Updating the server version reference values
=> Update server versions in _config.yml

src-api/Gemfile.lock
Update rexml to resolve CVE-2024-43398
=> Update rexml for CVE-2024-43398

jekyll/_includes/snippets/xcode-silicon-vm.adoc
Update the Xcode documentation for the Xcode 16 RC Release
[MAC-2340](https://circleci.atlassian.net/browse/MAC-2340)
[MAC-2340]: https://circleci.atlassian.net/browse/MAC-2340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Xcode 16 RC documentation updates

jekyll/_includes/snippets/xcode-silicon-vm.adoc
=> [MAC-2350] Xcode 16 GA

jekyll/_includes/snippets/xcode-silicon-vm.adoc
Release Xcode 16.1 Beta 2 docs.
=> [MAC-2351] Xcode 16.1 Beta 2

Gemfile, Gemfile.lock
no longer required, this was used for PDFs of server docs
=> remove pygments gem

jekyll/_includes/snippets/macos-resource-table.adoc
=> fix m2pro large vCPU and RAM

jekyll/_cci2/ip-ranges.adoc
=> add new macos ip ranges 18.97.4.0/24 and 18.97.6.0/24

jekyll/_cci2/triggers-overview.adoc
=> Add example that uses TAG instead of BRANCH

jekyll/_cci2/set-up-multiple-configuration-files-for-a-project.adoc, jekyll/_cci2/webhooks.adoc
i have removed the feature flag and opened these up to anyone
=> move from closed preview to open preview

jekyll/_cci2/pipelines.adoc
=> Remove warning banner about bug that has been fixed

jekyll/_cci2/ip-ranges.adoc
Add link to macos ip ranges json and example curl command to download
https://circleci.atlassian.net/browse/MAC-2282
=> [MAC-2284] Add link to macos ip ranges json and example curl command to download

jekyll/_cci2/authentication/set-up-sso.adoc, jekyll/_cci2/authentication/sign-in-to-an-sso-enabled-organization.adoc, jekyll/_cci2/authentication/sso-overview.adoc, jekyll/_data/sidenav.yml, styles/config/vocabularies/Docs/accept.txt
Ticket: https://circleci.atlassian.net/browse/CIAMP-1237
Contains the following sections:
* Introduction to SSO (with CircleCI)
* How to set up SSO
* How to join/login to an SSO org as a user
=> CIAMP-1237: documentation for SSO

jekyll/_includes/snippets/xcode-silicon-vm.adoc
New Xcode images for Xcode 16.1 GA and Xcode 16.2 Beta 2
* https://circleci.atlassian.net/browse/MAC-2389
* https://circleci.atlassian.net/browse/MAC-2384
=> [MAC-2384] Xcode 16.2 Beta 2; Xcode 16.1 GA

jekyll/_cci2/authentication/sign-in-to-an-sso-enabled-organization.adoc
Update the SSO docs to include the `Join with SSO` button on the homepage for joining an SSO org. Plus some clarifications on the documentation for a user authenticating with SSO for an org.
=> Tweak the SSO user documentation

jekyll/_cci2/triggers-overview.adoc
=> triggers overview page: remove API v2 documentation disclaimer

jekyll/_cci2/release/configure-your-kubernetes-components.adoc
Add the project ID annotation to the deployment example
It was mistakenly removed in a previous change
=> Fix error in deployment example

src-api/source/includes/_keys.md
Add note to docs for creating ssh keys to reflect that additional authorization step may be required on OAuth GitHub organizations with SAML SSO enabled
=> [CIAMP-1356] Add note to docs for creating ssh keys

jekyll/_includes/snippets/xcode-silicon-vm.adoc
New Xcode image for Xcode 16.2 Beta 2
https://circleci.atlassian.net/browse/MAC-2398
=> [MAC-2398] update xcode 16.2 info with new xcode 16.2 beta 2

jekyll/_cci2/release/configure-release-markers.adoc
Quick fix of transposed char typo
=> Quick fix of transposed typo in information

jekyll/_cci2/pipelines.adoc, jekyll/_cci2/webhooks.adoc, jekyll/_includes/snippets/custom-webhook-setup.adoc
add link to new docs page that talks about the "convergence" approach
=> link to the new docs page

jekyll/_cci2/reusing-config.md
Update parameter syntax definition to state that pipeline parameters require a default to be configured
Avoid confusion and make table correct
=> Pipeline params require default

jekyll/_cci2/skip-build.adoc
Updated description to make it clear that whether a pipeline is auto-canceled or not depends on whether the **trigger branch** is default or not.
=> Update docs about auto-cancellation

jekyll/_cci2/authentication/set-up-sso.adoc, jekyll/_cci2/authentication/sso-overview.adoc, jekyll/_data/sidenav.yml
* Add step to direct admins to set up their users in their IdP, and specify new users get the org viewer role
* Expand the limitations section to all features that require personal tokens: API, CLI, VS Code extension, config policies
=> Additions to SSO docs

jekyll/_cci2/concepts.adoc, jekyll/_cci2/persist-data.md, jekyll/_cci2/workspaces.adoc, jekyll/_cci2_ja/concepts.md, jekyll/_cci2_ja/persist-data.md, jekyll/_cci2_ja/workspaces.adoc
fixes #9098 
blog post was archived and a redirect was set up to link back to the workspaces doc so the change wasn't picked up by our link checker
=> remove link to archived blog

jekyll/_cci2/roles-and-permissions-overview.adoc
- Rename "config source" into "pipeline"
- Updated permission grid to match prod (= contributors can't edit triggers or pipelines)
=> Update pipeline permissions

renovate.json
Updating the Renovate config to work on a public repository.
Renovate was complaining in #9101
=> Update renovate.json for public repos

jekyll/_includes/snippets/xcode-silicon-vm.adoc
Update Xcode 16.2 RC documentation and links (manifest, discuss post)
https://circleci.atlassian.net/browse/MAC-2422
=> [MAC-2422] update xcode 16.2 RC

jekyll/_includes/snippets/troubleshoot/self-hosted-runner-troubleshoot-snip.adoc
Jira: https://circleci.atlassian.net/browse/ONPREM-1568
=> Add troubleshoot section for missing OIDC tokens on runner [ONPREM-1568]

jekyll/_includes/snippets/xcode-silicon-vm.adoc
New macOS image. Xcode 16.2 GA.
* https://circleci.atlassian.net/browse/MAC-2424
=> [MAC-2424] Xcode 16.2 GA

jekyll/_cci2/set-up-multiple-configuration-files-for-a-project.adoc
this has come up a few times, the workaround is needed until https://circleci.atlassian.net/browse/LIFE-1123 is completed
=> update for temporary workaround until we add the button to the trigger modal

jekyll/_cci2/server/v4.3/overview/release-notes.adoc
https://circleci.atlassian.net/browse/ONPREM-1891
=> adding note about changes to artifact hosting to 4.3.0 release notes

jekyll/_cci2/github-apps-integration.adoc, jekyll/_cci2/github-event-trigger-options.adoc, jekyll/_cci2/github-trigger-event-options.adoc, jekyll/_cci2/pipelines.adoc, jekyll/_data/sidenav.yml
Name change to be including of all GitHub users
=> Change page title to GitHub trigger event options

jekyll/_cci2/version-control-system-integration-overview.adoc
=> Adding entry for trigger on non-push events capability

.github/CODEOWNERS
Update team name from change-validation to sources-of-change
[_Created by Sourcegraph batch change `kira-m/remove-experiences-team`._](https://circleci.sourcegraphcloud.com/users/kira-m/batch-changes/remove-experiences-team)
=> Update CODEOWNERS team name

jekyll/_cci2/authentication/sign-in-to-an-sso-enabled-organization.adoc, jekyll/_cci2/authentication/sso-overview.adoc
Updates the SSO docs to also cater to classic/Oauth based flow.
https://circleci.atlassian.net/browse/CIAMP-1416
=> Updates the SSO docs to also cater to classic/Oauth based flow.

jekyll/_cci2/api-developers-guide.adoc, jekyll/_cci2/config-policies-for-self-hosted-runner.adoc, jekyll/_cci2/config-policy-management-overview.adoc, jekyll/_cci2/contexts.adoc, jekyll/_cci2/create-and-manage-config-policies.adoc, jekyll/_cci2/deploy-to-amazon-sagemaker.adoc, jekyll/_cci2/how-to-use-the-circleci-local-cli.adoc, jekyll/_cci2/manage-contexts-with-config-policies.adoc, jekyll/_cci2/openid-connect-tokens.adoc, jekyll/_cci2/server/latest/operator/configuring-external-services.adoc, jekyll/_cci2/server/v4.1/operator/configuring-external-services.adoc, jekyll/_cci2/server/v4.2/operator/configuring-external-services.adoc, jekyll/_cci2/server/v4.3/operator/configuring-external-services.adoc, jekyll/_cci2/server/v4.4/operator/configuring-external-services.adoc, jekyll/_cci2/server/v4.5/operator/configuring-external-services.adoc, jekyll/_cci2/server/v4.6/operator/configuring-external-services.adoc, styles/config/vocabularies/Docs/accept.txt
=> Convert pages to adoc include syntax

jekyll/_cci2/container-runner-installation.adoc, jekyll/_cci2/install-machine-runner-3-on-docker.adoc, jekyll/_cci2/install-machine-runner-3-on-linux.adoc, jekyll/_cci2/install-machine-runner-3-on-macos.adoc, jekyll/_cci2/install-machine-runner-3-on-windows.adoc, jekyll/_cci2/machine-runner-3-manual-installation-on-windows.adoc, jekyll/_cci2/machine-runner-3-manual-installation.adoc, jekyll/_cci2/migrate-from-launch-agent-to-machine-runner-3-on-windows.adoc, jekyll/_cci2/pipelines.adoc, jekyll/_cci2/resource-class-overview.adoc, jekyll/_cci2/runner-installation-docker.adoc, jekyll/_cci2/runner-installation-linux.adoc, jekyll/_cci2/runner-installation-mac.adoc, jekyll/_cci2/runner-installation-windows.adoc, jekyll/_cci2/triggers-overview.adoc, jekyll/_cci2/using-arm.adoc, jekyll/_cci2/using-gpu.adoc, jekyll/_cci2/using-linuxvm.adoc, jekyll/_cci2/using-macos.adoc, jekyll/_cci2/using-windows.adoc, jekyll/_cci2/webhooks.adoc, jekyll/_includes/snippets/runner/terms.adoc
=> Convert liquid includes to adoc -3

jekyll/_cci2/server/latest/air-gapped-installation/example-values.adoc, jekyll/_cci2/server/latest/air-gapped-installation/phase-2-configure-object-storage.adoc, jekyll/_cci2/server/latest/air-gapped-installation/phase-3-install-circleci-server.adoc, jekyll/_cci2/server/latest/installation/installation-reference.adoc, jekyll/_cci2/server/latest/installation/upgrade-server.adoc
- Removing launch agent reference from v4.8 version doc
=> ONPREM-1346  | Removing launch agent reference

jekyll/_cci2/enable-checks.adoc
The page Org Settings > "VCS" has been renamed into "VCS Connections".
**Important**: the content of this page will change soon too, with additional components to the current "Github checks" one. 
Another PR will be necessary to update the images in this page, but it feels worth waiting until UI changes are complete to avoid having to update the images multiple times
Ticket https://circleci.atlassian.net/browse/SC-1826 
=> Rename "VCS" page to "VCS Connections"

jekyll/_cci2/deploy/configure-your-kubernetes-components.adoc
Remove unsupported annotation
Remove unsupported annotation
=> [REL-1339] Remove unsupported annotation

jekyll/_cci2/contexts.adoc, styles/config/vocabularies/Docs/accept.txt
=> Documenting max number of contexts per config file

jekyll/_cci2/templates/test-page-one.adoc
=> Test page fix

jekyll/_cci2/github-integration.adoc
=> Fix bullet point list

jekyll/_cci2/deploy-to-aws.adoc, jekyll/_cci2/skip-build.adoc
=> fix broken include and bad formatting

jekyll/_cci2/configuration-reference.adoc
=> Fix sentence length in configuration reference

jekyll/_cci2/deploy/update-the-kubernetes-release-agent.adoc
=> Feature name change - update release agent page

jekyll/_cci2/deploy/configure-deploy-markers.adoc
=> Feature name change - configure deploy markers

jekyll/_cci2/deploy/configure-your-kubernetes-components.adoc
=> Feature name change - configure components

jekyll/_cci2/deploy/set-up-the-release-agent.adoc
=> Feature name change - set up the release agent

.vale.ini, jekyll/_cci2/deploy/manage-deploys.adoc
=> Feature name change - manage releases

jekyll/_cci2/webhooks.adoc
The example listed previously didn't work. This is tried and tested 
=> Fix custom webhook param extraction example

jekyll/_cci2/github-integration.adoc
=> Github integration - Remove note about CIRCLE_PULL_REQUEST

jekyll/_includes/partials/pipelines-and-triggers/pipeline-values.adoc
=> Remove references to inbound webhooks

jekyll/_cci2/orchestration-cookbook.adoc
=> Small fix on orchestration cookbook

jekyll/_cci2/server/latest/operator/introduction-to-nomad-cluster-operation.adoc
https://circleci.atlassian.net/browse/ONPREM-2101
=> [ONPREM-2101] Document accessing the Nomad web UI for troubleshooting

jekyll/_cci2/deploy/configure-deploy-markers.adoc, jekyll/_cci2/deploy/deploys-overview.adoc, styles/config/vocabularies/Docs/accept.txt
This adds tutorials around setting up a deploy markers and updating their status. It also calls out explicitly the existence of an agentless option as opposed to the agent based approach.
[REL-3699](https://circleci.atlassian.net/browse/REL-3699)
[REL-3699]: https://circleci.atlassian.net/browse/REL-3699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updating documentation around deploy markers

src-api/package.json, src-api/yarn.lock
This was breaking the docs platform because 🤷‍♂️ 
=> [INC-148] Downgrade redocly-cli

jekyll/_cci2/authentication/mfa.adoc
Add an FAQs section as suggested in this comment: https://github.com/circleci/circleci-docs/pull/9372#discussion_r2079432647
=> CIAMP-1505: Add MFA FAQs section

src-api/package.json, src-api/yarn.lock
This is a follow up PR to https://github.com/circleci/circleci-docs/commit/57701547c5594087abb0efda4cb5d110535b27ce
In my last merge, the babel resolutions broke the cypress tests. This PR restores the dependencies from `master` while still addressing the HIGH CVE from this PR. 
Essentially, through the various testing, the yarnlock file updated in an unintentional way, and I thought I had validated the latest change I made in my linked PR 😢 
I validated the master fail in preview branch, to make sure that I was correctly testing the followup reverts in preview
* https://app.circleci.com/pipelines/github/circleci/docs-platform/7784/workflows/e897e171-5dc6-445b-a9c4-705c14443b5d/jobs/68819?invite=true#step-104-55776_50
I've successfully validated this in this preview deploy: 
* …
=> [LIFE-1557] Revert babel resolution - breaks tests and are unnecessary

jekyll/_cci2/slack-orb-tutorial.adoc
fixes #9310 
fix indentation in slack orb tutorial
=> Fix indentation

jekyll/_cci2/server/latest/installation/installation-reference.adoc
=> [ONPREM-1995] Update values table for server 4.8

jekyll/_cci2/server/latest/installation/hardening-your-cluster.adoc
=> add mtls note 4.8

jekyll/_includes/partials/execution-resources/xcode-silicon-vm.adoc
The latest Xcode 16.4 GA release is the same as the RC. Just Updating the docs.
* https://circleci.atlassian.net/browse/EXEC-5494
=> [EXEC-5494] Xcode 16.4 GA Release

jekyll/_cci2/how-to-override-config.adoc
=> Fix requires config in override example

jekyll/_cci2/introduction-to-the-circleci-web-app.adoc
"release markers" --> "deploy makers"
=> make language consistent

Taskfile.yml, renovate.json
Now that we're all migrated, re-enable publishing to S3
=> Re-activate deploy

extensions/export-content-extension.js
Make sure old pages are no-longer indexed.
=> Replace all aloglia objects, instead of just adding

docs/reference/modules/ROOT/pages/configuration-reference.adoc
Added comprehensive error documentation for job retention configuration in CircleCI.
Users were encountering validation errors when configuring job retention but had no documentation to help them understand and fix these issues. The error messages in the CircleCI UI were not self-explanatory, leading to confusion and support requests. This documentation addresses the specific error patterns shown in screenshot and provides clear guidance on proper configuration syntax.
Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant …
=> Add error documentation for job retention configuration

docs/guides/modules/ROOT/partials/execution-resources/xcode-silicon-vm.adoc
New Xcode Image
New Xcode Image
=> [EXEC-5663] Xcode 26 Beta 6

docs/guides/modules/orchestrate/pages/using-dynamic-configuration.adoc
=> Adding the `parameters` parameter to the code snippet

docs/server-admin/modules/operator/pages/backup-and-restore.adoc
🍒 https://github.com/circleci/circleci-docs/pull/9552
=> recommend scaling down application before backups on server

docs/guides/modules/deploy/pages/configure-deploy-markers.adoc
Add caution around release plan and update commands and rerunning workflows
=> Rerun from failed caution for deploy markers

docs/guides/modules/getting-started/pages/introduction-to-yaml-configurations.adoc
Replace HP references in examples with Tea and Sesame Street themes
[JKR is an outspoken anti-trans activist](https://www.lgbtqnation.com/2025/05/j-k-rowling-is-personally-funding-attacks-on-trans-womens-rights-with-her-harry-potter-money/)
=> Replace references in yaml config examples

docs/guides/modules/ROOT/partials/execution-resources/xcode-silicon-vm.adoc
New Xcode 26 GA Image.
New Image.
=> [EXEC-5720] Xcode 26 GA

docs/guides/modules/security/pages/audit-logs.adoc
The minimum required permissions and the trust policy for audit logs streaming
Update the audit logs streaming with more restrictive permissions for us and added extra recommendation in the trust policy following least privilege.
=> [NOTIFY-365] update permissions recommended for audit logs streaming

scripts/redirects_v2.yml
=> remove redirect

docs/guides/modules/orchestrate/pages/pipelines.adoc
=> remove todo item

docs/guides/modules/ROOT/partials/pipelines-and-triggers/pipeline-values.adoc
Table formatting was going wrong with the event_type pipeline value selected:
This fixes it by preventing the lines from wrapping:
=> fix formatting for event_type pipeline event

docs/guides/modules/orchestrate/pages/github-trigger-event-options.adoc
using the syntax in document caused pipeline to error. updating to make sure the build can run.
copying the syntax from document experienced following error 
Make sure the pipeline run:
https://app.circleci.com/pipelines/github/nanophate-cci/check-draft-pr
=> fix erroring syntax for event parameter

docs/guides/modules/orchestrate/pages/workflows.adoc
=> Remove schedule workflow deprecation notice

docs/guides/modules/deploy/pages/set-up-the-circleci-release-agent.adoc
=> allow labels table to scroll horizontally
